import { defineText } from "@madrasha/shared-ui/src/i18n";

/** Shared settings building blocks (inline fields, image boxes, toggles). */
export const settingsUiText = defineText({
  bn: {
    notAdded: "যোগ করা হয়নি",
    editTitle: "সম্পাদনা",
    addAnother: "আরেকটি যোগ করুন",
    cannotBeEmpty: (label: string) => `${label} খালি রাখা যাবে না।`,
    onlyPngJpg: "শুধু PNG, JPG বা JPEG ছবি আপলোড করা যাবে",
    maxImageSize: (mb: string) => `ছবির সাইজ ${mb}MB এর কম হতে হবে`,
    ratioWide: "অনুপাত ১৬:৯",
    ratioSquare: "অনুপাত ১:১",
    uploadImage: "ছবি আপলোড করুন",
    change: "পরিবর্তন করুন",
    uploading: "আপলোড হচ্ছে...",
    changeBackground: "পটভূমি পরিবর্তন",
    darkBackground: "গাঢ় পটভূমি",
    checkerBackground: "চেক পটভূমি",
    openOriginal: "নতুন ট্যাবে মূল ছবি খুলুন",
    closeEsc: "বন্ধ করুন (Esc)",
    deleteImage: "ছবি মুছুন",
    deleteImageConfirm: (label: string) => `"${label}" মুছে ফেলা হবে। এগিয়ে যেতে চান?`,
    viewLarge: "বড় করে দেখুন",
    uploaded: "আপলোড করা আছে",
    deleting: "মুছে ফেলা হচ্ছে...",
    inactive: "নিষ্ক্রিয়",
    publish: "প্রকাশ করুন",
    socialLinks: "সোশ্যাল লিংক",
    socialLinksHint:
      'একই ধরনের একাধিক লিংক দেওয়া যাবে (যেমন কয়েকটি WhatsApp নম্বর বা একাধিক Facebook পেজ)। "নাম" ঐচ্ছিক — যেমন "অফিস", "{{head}} সাহেব"।',
    nameOptional: "নাম (ঐচ্ছিক)",
    moveUp: "উপরে নিন",
    moveDown: "নিচে নিন",
    invalidWhatsapp: "সঠিক WhatsApp নম্বর দিন",
    invalidLink: "সঠিক লিংক দিন",
    example: (v: string) => `যেমন: ${v}`,
    anyLink: "যেকোনো লিংক (https://...)",
  },
  en: {
    notAdded: "Not added",
    editTitle: "Edit",
    addAnother: "Add another",
    cannotBeEmpty: (label) => `${label} cannot be empty.`,
    onlyPngJpg: "Only PNG, JPG or JPEG images can be uploaded",
    maxImageSize: (mb) => `Image size must be under ${mb}MB`,
    ratioWide: "Ratio 16:9",
    ratioSquare: "Ratio 1:1",
    uploadImage: "Upload image",
    change: "Change",
    uploading: "Uploading...",
    changeBackground: "Change background",
    darkBackground: "Dark background",
    checkerBackground: "Checkered background",
    openOriginal: "Open original image in a new tab",
    closeEsc: "Close (Esc)",
    deleteImage: "Delete image",
    deleteImageConfirm: (label) => `"${label}" will be deleted. Continue?`,
    viewLarge: "View larger",
    uploaded: "Uploaded",
    deleting: "Deleting...",
    inactive: "Inactive",
    publish: "Publish",
    socialLinks: "Social links",
    socialLinksHint:
      'You can add several links of the same type (e.g. multiple WhatsApp numbers or Facebook pages). "Name" is optional — e.g. "Office", "{{head}}".',
    nameOptional: "Name (optional)",
    moveUp: "Move up",
    moveDown: "Move down",
    invalidWhatsapp: "Enter a valid WhatsApp number",
    invalidLink: "Enter a valid link",
    example: (v) => `e.g. ${v}`,
    anyLink: "Any link (https://...)",
  },
  ar: {
    notAdded: "لم تتم الإضافة",
    editTitle: "تعديل",
    addAnother: "إضافة أخرى",
    cannotBeEmpty: (label) => `لا يمكن ترك ${label} فارغًا.`,
    onlyPngJpg: "يمكن رفع صور PNG أو JPG أو JPEG فقط",
    maxImageSize: (mb) => `يجب أن يكون حجم الصورة أقل من ${mb} ميغابايت`,
    ratioWide: "النسبة ١٦:٩",
    ratioSquare: "النسبة ١:١",
    uploadImage: "رفع صورة",
    change: "تغيير",
    uploading: "جارٍ الرفع...",
    changeBackground: "تغيير الخلفية",
    darkBackground: "خلفية داكنة",
    checkerBackground: "خلفية مربعات",
    openOriginal: "فتح الصورة الأصلية في تبويب جديد",
    closeEsc: "إغلاق (Esc)",
    deleteImage: "حذف الصورة",
    deleteImageConfirm: (label) => `سيتم حذف "${label}". هل تريد المتابعة؟`,
    viewLarge: "عرض مكبّر",
    uploaded: "تم الرفع",
    deleting: "جارٍ الحذف...",
    inactive: "غير نشط",
    publish: "نشر",
    socialLinks: "روابط التواصل الاجتماعي",
    socialLinksHint:
      'يمكن إضافة عدة روابط من النوع نفسه (مثل عدة أرقام واتساب أو صفحات فيسبوك). "الاسم" اختياري — مثل "المكتب"، "{{head}}".',
    nameOptional: "الاسم (اختياري)",
    moveUp: "نقل لأعلى",
    moveDown: "نقل لأسفل",
    invalidWhatsapp: "أدخل رقم واتساب صحيحًا",
    invalidLink: "أدخل رابطًا صحيحًا",
    example: (v) => `مثال: ${v}`,
    anyLink: "أي رابط (https://...)",
  },
});
