import { defineText } from "@madrasha/shared-ui/src/i18n";

/** UI text for the leave-request workflow page. */
export const attendanceLeaveText = defineText({
  bn: {
    title: "ছুটির আবেদন",
    subtitle: "অভিভাবক ও অফিস থেকে আসা ছুটির আবেদন অনুমোদন / বাতিল করুন",
    newLeave: "নতুন ছুটি",
    refresh: "রিফ্রেশ",
    tabs: {
      PENDING: "অপেক্ষমাণ",
      APPROVED: "অনুমোদিত",
      REJECTED: "প্রত্যাখ্যাত",
      CANCELLED: "বাতিল",
      ALL: "সব",
    },
    status: {
      PENDING: "অপেক্ষমাণ",
      APPROVED: "অনুমোদিত",
      REJECTED: "প্রত্যাখ্যাত",
      CANCELLED: "বাতিল",
    },
    attendeeTypes: {
      STUDENT: "{{student}}",
      TEACHER: "{{teacher}}",
      STAFF: "কর্মচারী",
    },
    leaveTypes: {
      sick: "অসুস্থতা",
      family: "পারিবারিক",
      travel: "ভ্রমণ",
      other: "অন্যান্য",
    },
    via: {
      guardian: "অভিভাবক",
      office: "অফিস",
    },
    filters: {
      attendeeType: "ধরন",
      leaveType: "ছুটির ধরন",
      from: "তারিখ থেকে",
      to: "তারিখ পর্যন্ত",
      all: "সব",
      reset: "রিসেট",
    },
    days: (n: string) => `${n} দিন`,
    dayRange: "সময়কাল",
    reason: "কারণ",
    requestedBy: "আবেদনকারী",
    reviewedBy: "পর্যালোচনা",
    reviewNote: "মন্তব্য",
    roll: "রোল",
    loadFailed: "ছুটির আবেদন লোড করা যায়নি",
    empty: "এই তালিকায় কোনো আবেদন নেই",
    pageInfo: (from: string, to: string, total: string) => `${from}-${to} / মোট ${total}`,
    prev: "পূর্ববর্তী",
    next: "পরবর্তী",
    actions: {
      approve: "অনুমোদন",
      reject: "প্রত্যাখ্যান",
      cancel: "বাতিল করুন",
    },
    actionTitle: {
      approve: "ছুটি অনুমোদন",
      reject: "ছুটি প্রত্যাখ্যান",
      cancel: "ছুটি বাতিল",
    },
    actionHint: {
      approve: "অনুমোদনের পর প্রতিটি কর্মদিবসে উপস্থিতি 'ছুটি' হিসেবে চিহ্নিত হবে (যেদিন উপস্থিত ছিল সেদিন বাদে)।",
      reject: "প্রত্যাখ্যানের কারণ লিখুন - অভিভাবক এটি দেখতে পাবেন।",
      cancel: "অনুমোদিত ছুটি বাতিল করলে ছুটির দিনগুলো আবার অচিহ্নিত হয়ে যাবে।",
    },
    note: "মন্তব্য",
    noteOptional: "মন্তব্য (ঐচ্ছিক)",
    noteRequired: "মন্তব্য লেখা আবশ্যক",
    confirm: "নিশ্চিত করুন",
    close: "বন্ধ করুন",
    working: "অপেক্ষা করুন...",
    approved: (marked: string, skipped: string) => `অনুমোদিত - ${marked} দিন ছুটি চিহ্নিত, ${skipped} দিন বাদ`,
    rejected: "আবেদন প্রত্যাখ্যান করা হয়েছে",
    cancelled: "আবেদন বাতিল করা হয়েছে",
    create: {
      title: "নতুন ছুটির আবেদন",
      attendeeType: "কার ছুটি",
      class: "{{class}}",
      allClasses: "সব {{class}}",
      search: "নাম / রোল / আইডি দিয়ে খুঁজুন",
      person: "ব্যক্তি",
      pickPerson: "তালিকা থেকে একজন নির্বাচন করুন",
      peopleLoading: "তালিকা লোড হচ্ছে...",
      noPeople: "কাউকে পাওয়া যায়নি",
      moreResults: (n: string) => `আরও ${n} জন - খোঁজ আরও নির্দিষ্ট করুন`,
      selected: "নির্বাচিত",
      change: "পরিবর্তন",
      from: "শুরুর তারিখ",
      to: "শেষ তারিখ",
      leaveType: "ছুটির ধরন",
      reason: "কারণ",
      reasonPlaceholder: "ছুটির কারণ লিখুন",
      approveNow: "এখনই অনুমোদন করুন",
      submit: "আবেদন জমা দিন",
      submitting: "জমা হচ্ছে...",
      created: "ছুটির আবেদন তৈরি হয়েছে",
      missingPerson: "একজন ব্যক্তি নির্বাচন করুন",
      missingReason: "কারণ লিখুন",
      badRange: "শেষ তারিখ শুরুর তারিখের আগে হতে পারে না",
    },
    noPermission: "ছুটি অনুমোদন/তৈরির অনুমতি আপনার নেই",
  },
  en: {
    title: "Leave requests",
    subtitle: "Approve or reject leave requests from guardians and the office",
    newLeave: "New leave",
    refresh: "Refresh",
    tabs: {
      PENDING: "Pending",
      APPROVED: "Approved",
      REJECTED: "Rejected",
      CANCELLED: "Cancelled",
      ALL: "All",
    },
    status: {
      PENDING: "Pending",
      APPROVED: "Approved",
      REJECTED: "Rejected",
      CANCELLED: "Cancelled",
    },
    attendeeTypes: {
      STUDENT: "{{student}}",
      TEACHER: "{{teacher}}",
      STAFF: "Staff",
    },
    leaveTypes: {
      sick: "Sick",
      family: "Family",
      travel: "Travel",
      other: "Other",
    },
    via: {
      guardian: "Guardian",
      office: "Office",
    },
    filters: {
      attendeeType: "Type",
      leaveType: "Leave type",
      from: "From date",
      to: "To date",
      all: "All",
      reset: "Reset",
    },
    days: (n: string) => `${n} day(s)`,
    dayRange: "Period",
    reason: "Reason",
    requestedBy: "Requested by",
    reviewedBy: "Reviewed by",
    reviewNote: "Note",
    roll: "Roll",
    loadFailed: "Could not load leave requests",
    empty: "No requests in this list",
    pageInfo: (from: string, to: string, total: string) => `${from}-${to} of ${total}`,
    prev: "Previous",
    next: "Next",
    actions: {
      approve: "Approve",
      reject: "Reject",
      cancel: "Cancel",
    },
    actionTitle: {
      approve: "Approve leave",
      reject: "Reject leave",
      cancel: "Cancel leave",
    },
    actionHint: {
      approve: "Every working day in the range will be marked as leave (days the person was present are kept).",
      reject: "Write a reason for rejecting - the guardian will see it.",
      cancel: "Cancelling an approved leave makes those days unmarked again.",
    },
    note: "Note",
    noteOptional: "Note (optional)",
    noteRequired: "A note is required",
    confirm: "Confirm",
    close: "Close",
    working: "Please wait...",
    approved: (marked: string, skipped: string) => `Approved - ${marked} day(s) marked as leave, ${skipped} skipped`,
    rejected: "Request rejected",
    cancelled: "Request cancelled",
    create: {
      title: "New leave request",
      attendeeType: "Leave for",
      class: "{{class}}",
      allClasses: "All {{class}}es",
      search: "Search by name / roll / ID",
      person: "Person",
      pickPerson: "Pick one person from the list",
      peopleLoading: "Loading list...",
      noPeople: "Nobody found",
      moreResults: (n: string) => `${n} more - narrow the search`,
      selected: "Selected",
      change: "Change",
      from: "From date",
      to: "To date",
      leaveType: "Leave type",
      reason: "Reason",
      reasonPlaceholder: "Write the reason for leave",
      approveNow: "Approve immediately",
      submit: "Submit request",
      submitting: "Submitting...",
      created: "Leave request created",
      missingPerson: "Select a person",
      missingReason: "Write a reason",
      badRange: "End date cannot be before start date",
    },
    noPermission: "You don't have permission to create or approve leave",
  },
});
