import { defineText } from "@madrasha/shared-ui/src/i18n";

/** UI text for sub-day session attendance (marking, session setup, report). */
export const attendanceSessionText = defineText({
  bn: {
    title: "সেশনভিত্তিক উপস্থিতি",
    subtitle: "ফজর, মাগরিব, রাতের পড়া ইত্যাদি আলাদা সেশনে উপস্থিতি নিন",
    tabs: {
      mark: "উপস্থিতি নিন",
      manage: "সেশন ব্যবস্থাপনা",
      report: "রিপোর্ট",
    },
    status: {
      PRESENT: "উপস্থিত",
      LATE: "দেরি",
      ABSENT: "অনুপস্থিত",
      LEAVE: "ছুটি",
    },
    statusShort: {
      PRESENT: "উ",
      LATE: "দে",
      ABSENT: "অ",
      LEAVE: "ছু",
    },
    session: "সেশন",
    class: "{{class}}",
    date: "তারিখ",
    selectSession: "সেশন নির্বাচন করুন",
    selectClass: "{{class}} নির্বাচন করুন",
    allClasses: "সব {{class}}",
    allSessions: "সব সেশন",
    noSessions: "এখনো কোনো সেশন তৈরি হয়নি",
    noSessionsHint: "সেশন ব্যবস্থাপনা ট্যাব থেকে সেশন যোগ করুন",
    pickAll: "সেশন, {{class}} ও তারিখ নির্বাচন করুন",
    sheetFailed: "শিট লোড করা যায়নি",
    noStudents: "এই {{class}}তে এই সেশনের জন্য কোনো {{student}} নেই",
    residential: "আবাসিক",
    nonResidential: "অনাবাসিক",
    allPresent: "সবাই উপস্থিত",
    clearAll: "সব মুছুন",
    offDay: "আজ বন্ধের দিন",
    notEditable: "এই তারিখের উপস্থিতি পরিবর্তনের অনুমতি আপনার নেই (সম্পাদনার সময়সীমা পেরিয়ে গেছে)",
    counts: {
      total: "মোট",
      marked: "চিহ্নিত",
      unmarked: "বাকি",
    },
    remarks: "মন্তব্য",
    save: "সংরক্ষণ করুন",
    saving: "সংরক্ষণ হচ্ছে...",
    saved: "সেশন উপস্থিতি সংরক্ষণ করা হয়েছে",
    nothingToSave: "কোনো উপস্থিতি চিহ্নিত করা হয়নি",
    unmarkedWarn: (n: string) => `${n} জন এখনো চিহ্নিত হয়নি - তারা সংরক্ষিত হবে না`,
    skippedSome: (n: string) => `${n} জন সংরক্ষিত হয়নি (এই সেশন/{{class}}র জন্য প্রযোজ্য নয়)`,
    manage: {
      add: "নতুন সেশন",
      edit: "সেশন এডিট",
      name: "সেশনের নাম",
      namePlaceholder: "যেমন: ফজর, মাগরিব, রাতের পড়া",
      start: "শুরুর সময়",
      end: "শেষের সময়",
      residentialOnly: "শুধু আবাসিক {{student}}",
      residentialOnlyHint: "চালু থাকলে শিটে শুধু আবাসিক {{student}}রা আসবে",
      active: "সক্রিয়",
      inactive: "নিষ্ক্রিয়",
      sortOrder: "ক্রম",
      moveUp: "উপরে",
      moveDown: "নিচে",
      save: "সংরক্ষণ",
      cancel: "বাতিল",
      created: "সেশন তৈরি হয়েছে",
      updated: "সেশন আপডেট হয়েছে",
      deleted: "সেশন মুছে ফেলা হয়েছে",
      deactivated: "সেশন নিষ্ক্রিয় করা হয়েছে",
      nameRequired: "সেশনের নাম লিখুন",
      deleteTitle: "সেশন মুছবেন?",
      deleteMessage: (name: string) => `"${name}" সেশনটি মুছে ফেলা হবে।`,
      hasRecordsTitle: "এই সেশনে উপস্থিতির রেকর্ড আছে",
      hasRecordsMessage:
        "মুছে ফেললে এই সেশনের সব উপস্থিতির রেকর্ডও মুছে যাবে। এর বদলে সেশনটি নিষ্ক্রিয় করা নিরাপদ।",
      deactivateInstead: "নিষ্ক্রিয় করুন",
      forceDelete: "সব সহ মুছুন",
      delete: "মুছুন",
      noPermission: "সেশন যোগ / এডিট করার অনুমতি আপনার নেই",
      allDay: "সময় নির্ধারিত নেই",
      records: (n: string) => `${n}টি রেকর্ড`,
    },
    report: {
      from: "তারিখ থেকে",
      to: "তারিখ পর্যন্ত",
      load: "রিপোর্ট দেখুন",
      name: "নাম",
      roll: "রোল",
      overall: "সামগ্রিক",
      empty: "এই সময়ে কোনো রেকর্ড নেই",
      failed: "রিপোর্ট লোড করা যায়নি",
      cellTitle: (p: string, l: string, a: string, lv: string) => `উপস্থিত ${p} · দেরি ${l} · অনুপস্থিত ${a} · ছুটি ${lv}`,
    },
  },
  en: {
    title: "Session attendance",
    subtitle: "Take attendance for sub-day sessions like Fajr, Maghrib or night study",
    tabs: {
      mark: "Mark",
      manage: "Manage sessions",
      report: "Report",
    },
    status: {
      PRESENT: "Present",
      LATE: "Late",
      ABSENT: "Absent",
      LEAVE: "Leave",
    },
    statusShort: {
      PRESENT: "P",
      LATE: "L",
      ABSENT: "A",
      LEAVE: "Lv",
    },
    session: "Session",
    class: "{{class}}",
    date: "Date",
    selectSession: "Select session",
    selectClass: "Select {{class}}",
    allClasses: "All {{class}}es",
    allSessions: "All sessions",
    noSessions: "No sessions have been created yet",
    noSessionsHint: "Add sessions from the Manage sessions tab",
    pickAll: "Select a session, {{class}} and date",
    sheetFailed: "Could not load the sheet",
    noStudents: "No {{student}}s in this {{class}} for this session",
    residential: "Residential",
    nonResidential: "Day",
    allPresent: "All present",
    clearAll: "Clear all",
    offDay: "Off day",
    notEditable: "You can't change attendance for this date (outside the edit window)",
    counts: {
      total: "Total",
      marked: "Marked",
      unmarked: "Remaining",
    },
    remarks: "Remarks",
    save: "Save",
    saving: "Saving...",
    saved: "Session attendance saved",
    nothingToSave: "Nothing has been marked",
    unmarkedWarn: (n: string) => `${n} not marked yet - they won't be saved`,
    skippedSome: (n: string) => `${n} not saved (not applicable to this session/{{class}})`,
    manage: {
      add: "New session",
      edit: "Edit session",
      name: "Session name",
      namePlaceholder: "e.g. Fajr, Maghrib, Night study",
      start: "Start time",
      end: "End time",
      residentialOnly: "Residential {{student}}s only",
      residentialOnlyHint: "When on, only residential {{student}}s appear on the sheet",
      active: "Active",
      inactive: "Inactive",
      sortOrder: "Order",
      moveUp: "Up",
      moveDown: "Down",
      save: "Save",
      cancel: "Cancel",
      created: "Session created",
      updated: "Session updated",
      deleted: "Session deleted",
      deactivated: "Session deactivated",
      nameRequired: "Enter a session name",
      deleteTitle: "Delete session?",
      deleteMessage: (name: string) => `The session "${name}" will be deleted.`,
      hasRecordsTitle: "This session has attendance records",
      hasRecordsMessage:
        "Deleting removes every attendance record of this session too. Deactivating it is the safer choice.",
      deactivateInstead: "Deactivate",
      forceDelete: "Delete with records",
      delete: "Delete",
      noPermission: "You don't have permission to add or edit sessions",
      allDay: "No fixed time",
      records: (n: string) => `${n} record(s)`,
    },
    report: {
      from: "From",
      to: "To",
      load: "Show report",
      name: "Name",
      roll: "Roll",
      overall: "Overall",
      empty: "No records in this range",
      failed: "Could not load the report",
      cellTitle: (p: string, l: string, a: string, lv: string) => `Present ${p} · Late ${l} · Absent ${a} · Leave ${lv}`,
    },
  },
});
