import { defineText } from "@madrasha/shared-ui/src/i18n";

/** কার্ড এনরোলমেন্ট page, the single-person card modal and the series mode. */
export const deviceCardsText = defineText({
  bn: {
    title: "কার্ড এনরোলমেন্ট",
    subtitle:
      "প্রত্যেকের ডিভাইস আইডি স্বয়ংক্রিয়ভাবে তৈরি হয়। কার্ড যুক্ত করতে \"মেশিনে কার্ড দিন\" চাপুন, তারপর কার্ডটি K40 মেশিনে ছোঁয়ান — নম্বর নিজে থেকেই যুক্ত হবে।",
    tabs: { STUDENT: "{{student}}", TEACHER: "{{teacher}}", STAFF: "স্টাফ" },
    allOf: (label: string) => `সব ${label}`,
    assignPins: "সবার আইডি তৈরি করুন",
    assignPinsHint: "যাদের ডিভাইস আইডি নেই তাদের আইডি তৈরি হবে (সেটিংস অনুযায়ী রেজি. নং থেকে); কানেক্টর পরে মেশিনে লিখে দেবে।",
    assignPinsTitle: "ডিভাইস আইডি তৈরি",
    assignPinsMessage: (scope: string) =>
      `${scope} — যাদের ডিভাইস আইডি নেই তাদের সবার জন্য নতুন আইডি তৈরি হবে। কানেক্টর পরের সিঙ্কে এদের নাম মেশিনে লিখে দেবে।`,
    assignPinsConfirm: "আইডি তৈরি করুন",
    assignPinsDone: (n: string) => `${n} জনের নতুন আইডি তৈরি হয়েছে`,
    assignPinsNone: "সবার আইডি আগে থেকেই আছে",
    seriesMode: "সিরিজ মোড",
    seriesHint: "কার্ড নেই এমন সবাইকে একে একে এনরোল করুন",
    all: "সব",
    hasCard: "কার্ড আছে",
    noCard: "কার্ড নেই",
    total: "মোট",
    searchStudents: "নাম, রোল, রেজি. বা আইডি",
    searchOthers: "নাম, রেজি. বা আইডি",
    clearSearch: "সার্চ মুছুন",
    allDivisions: "সব {{division}}",
    allClasses: "সব {{class}}",
    refresh: "রিফ্রেশ",
    loadFailed: "তালিকা লোড করা যায়নি",
    retry: "আবার চেষ্টা করুন",
    noneFound: "কাউকে পাওয়া যায়নি",
    allDone: "সবার কার্ড যুক্ত হয়েছে!",
    tryChangingFilter: "ফিল্টার বা সার্চ বদলে দেখুন।",
    showMore: "আরও দেখুন",
    showingOf: (shown: string, total: string) => `${total} জনের মধ্যে ${shown} জন দেখানো হচ্ছে`,
    roll: (n: string) => `রোল ${n}`,
    reg: (n: string) => `রেজি. ${n}`,
    pin: (id: string) => `আইডি ${id}`,
    noPin: "আইডি নেই",
    card: (n: string) => `কার্ড ${n}`,
    enrollOnMachine: "মেশিনে কার্ড দিন",
    typeNumber: "নম্বর লিখুন",
    removeCard: "কার্ড সরান",
    removeCardTitle: "কার্ড সরান",
    removeCardMessage: (name: string, card: string) =>
      `${name} এর কার্ড (${card}) সরিয়ে ফেলতে চান? ডিভাইস আইডি থেকে যাবে, পরে নতুন কার্ড দেওয়া যাবে।`,
    cardRemoved: (name: string) => `${name} - কার্ড সরানো হয়েছে`,
    removePin: "ডিভাইস আইডি মুছুন",
    removePinTitle: "ডিভাইস আইডি মুছুন",
    removePinMessage: (name: string, pin: string) =>
      `${name} এর ডিভাইস আইডি (${pin}) ও কার্ড মুছে যাবে, এই আইডির পাঞ্চ আর কারো উপস্থিতি হিসেবে গণনা হবে না। চালিয়ে যাবেন?`,
    pinRemoved: (name: string) => `${name} - ডিভাইস আইডি মুছে ফেলা হয়েছে`,
    ineligible: "এই {{student}} এখন ডিভাইস উপস্থিতির তালিকায় নেই (ভর্তি অনুমোদিত ও সক্রিয় হতে হবে)।",
    personLoading: "তথ্য লোড হচ্ছে...",
    device: {
      label: "ডিভাইস",
      noActive: "কোনো সক্রিয় ডিভাইস নেই — আগে \"উপস্থিতি ডিভাইস\" পেজে ডিভাইস যোগ করুন।",
      offline: (name: string) =>
        `"${name}" এর কানেক্টর অফলাইন — কানেক্টর PC চালু না থাকলে মেশিন থেকে কার্ড আসবে না।`,
      online: "কানেক্টর অনলাইন",
      using: "এনরোলমেন্ট ডিভাইস:",
    },
    enroll: {
      modalTitle: "ডিভাইস কার্ড",
      tabMachine: "মেশিনে পাঞ্চ",
      tabManual: "নম্বর লিখুন",
      status: {
        idle: "শুরু করতে নিচের বাটন চাপুন",
        starting: "শুরু হচ্ছে...",
        pending: "অপেক্ষমাণ — কানেক্টর মেশিন প্রস্তুত করছে",
        waiting: "মেশিন প্রস্তুত, কার্ড পাঞ্চ করুন",
        completed: "সফল! কার্ড যুক্ত হয়েছে",
        failed: "ব্যর্থ",
        expired: "সময় শেষ — কোনো কার্ড পাঞ্চ হয়নি",
        cancelled: "বাতিল করা হয়েছে",
        error: "শুরু করা যায়নি",
      },
      pendingHint: "কানেক্টর কয়েক সেকেন্ডের মধ্যে মেশিনে এই ব্যক্তির আইডি লিখে কার্ডের অপেক্ষা করবে।",
      waitingHint: (name: string) => `${name} কে বলুন K40 মেশিনে কার্ডটি একবার ছোঁয়াতে।`,
      secondsLeft: (s: string) => `${s} সেকেন্ড বাকি`,
      cardNumber: (n: string) => `কার্ড নম্বর: ${n}`,
      start: "শুরু করুন",
      retry: "আবার চেষ্টা করুন",
      cancel: "বাতিল",
      close: "বন্ধ করুন",
      startFailed: "এনরোলমেন্ট শুরু করা যায়নি",
      pollFailed: "সার্ভারের সাথে যোগাযোগে সমস্যা — আবার চেষ্টা করুন",
      connectorOfflineNow: "কানেক্টর অফলাইন মনে হচ্ছে — PC ও কানেক্টর প্রোগ্রাম চালু আছে কিনা দেখুন।",
      manualLabel: "কার্ড নম্বর",
      manualPlaceholder: "যেমন: 0012345678",
      manualHint: "USB কার্ড রিডার থাকলে এই ঘরে ক্লিক করে কার্ড ছোঁয়ান — নম্বর নিজে টাইপ হয়ে Enter এ সেভ হবে।",
      save: "সেভ করুন",
      saving: "সেভ হচ্ছে...",
      cardSaved: (name: string) => `${name} - কার্ড যুক্ত হয়েছে`,
      invalidCard: "শুধু সংখ্যা দিন (সর্বোচ্চ ২০ অঙ্ক, শূন্য নয়)",
      saveFailed: "সেভ করা যায়নি",
      currentPin: "ডিভাইস আইডি",
      currentCard: "বর্তমান কার্ড",
      none: "নেই",
      replaceWarning: "নতুন কার্ড দিলে আগের কার্ডটি বাদ যাবে।",
      pinAutoHint: "আইডি না থাকলে স্বয়ংক্রিয়ভাবে তৈরি হবে।",
    },
    series: {
      title: "সিরিজ মোড — কার্ড এনরোলমেন্ট",
      progress: (cur: string, total: string) => `${cur} / ${total}`,
      enrolledCount: (n: string) => `যুক্ত ${n}`,
      failedCount: (n: string) => ` · ব্যর্থ ${n}`,
      nowEnrolling: "এখন কার্ড দিচ্ছেন",
      nextLabel: "পরবর্তী:",
      previous: "আগের",
      skip: "বাদ দিন",
      previousKey: "আগের জন (←)",
      skipKey: "বাদ দিন (→)",
      finishedTitle: "সিরিজ শেষ!",
      finishedSummary: (done: string, skipped: string) => `${done} জনের কার্ড যুক্ত হয়েছে, ${skipped} জন বাদ গেছে।`,
      goBack: "ফিরে যান",
      done: "শেষ",
      keyboardHint: "Enter = সেভ / আবার চেষ্টা · → = বাদ · ← = আগের · Esc = বন্ধ",
      readerLabel: "USB রিডার বা হাতে নম্বর",
      recent: "সাম্প্রতিক",
      success: "সফল!",
      autoNext: "পরের জনে যাচ্ছে...",
      empty: "কার্ড নেই এমন কেউ নেই",
    },
  },
  en: {
    title: "Card Enrollment",
    subtitle:
      "Everyone gets a device ID automatically. To add a card press \"Enroll on machine\", then tap the card on the K40 — the number is linked automatically.",
    tabs: { STUDENT: "{{student}}s", TEACHER: "{{teacher}}s", STAFF: "Staff" },
    allOf: (label) => `All ${label}`,
    assignPins: "Create IDs for all",
    assignPinsHint: "Creates a device ID (from the reg. no, per settings) for everyone who doesn't have one; the connector writes them to the machine.",
    assignPinsTitle: "Create device IDs",
    assignPinsMessage: (scope) =>
      `${scope} — a new device ID will be created for everyone without one. The connector writes them to the machine on its next sync.`,
    assignPinsConfirm: "Create IDs",
    assignPinsDone: (n) => `Created ${n} new IDs`,
    assignPinsNone: "Everyone already has an ID",
    seriesMode: "Series mode",
    seriesHint: "Enroll everyone without a card, one after another",
    all: "All",
    hasCard: "Has card",
    noCard: "No card",
    total: "Total",
    searchStudents: "Name, roll, reg. or ID",
    searchOthers: "Name, reg. or ID",
    clearSearch: "Clear search",
    allDivisions: "All {{division}}s",
    allClasses: "All {{class}}es",
    refresh: "Refresh",
    loadFailed: "Could not load the list",
    retry: "Try again",
    noneFound: "No one found",
    allDone: "Everyone has a card!",
    tryChangingFilter: "Try a different filter or search.",
    showMore: "Show more",
    showingOf: (shown, total) => `Showing ${shown} of ${total}`,
    roll: (n) => `Roll ${n}`,
    reg: (n) => `Reg. ${n}`,
    pin: (id) => `ID ${id}`,
    noPin: "No ID",
    card: (n) => `Card ${n}`,
    enrollOnMachine: "Enroll on machine",
    typeNumber: "Type number",
    removeCard: "Remove card",
    removeCardTitle: "Remove card",
    removeCardMessage: (name, card) =>
      `Remove ${name}'s card (${card})? The device ID stays; a new card can be added later.`,
    cardRemoved: (name) => `${name} - card removed`,
    removePin: "Remove device ID",
    removePinTitle: "Remove device ID",
    removePinMessage: (name, pin) =>
      `${name}'s device ID (${pin}) and card will be removed; punches with this ID will no longer count for anyone. Continue?`,
    pinRemoved: (name) => `${name} - device ID removed`,
    ineligible: "This {{student}} is not on the device attendance list now (admission must be approved and active).",
    personLoading: "Loading...",
    device: {
      label: "Device",
      noActive: "No active device — add one on the \"Attendance Devices\" page first.",
      offline: (name) => `The connector of "${name}" is offline — cards can't arrive from the machine until the connector PC is on.`,
      online: "Connector online",
      using: "Enrollment device:",
    },
    enroll: {
      modalTitle: "Device Card",
      tabMachine: "Tap on machine",
      tabManual: "Type number",
      status: {
        idle: "Press the button below to start",
        starting: "Starting...",
        pending: "Pending — the connector is preparing the machine",
        waiting: "Machine ready, tap the card",
        completed: "Done! Card linked",
        failed: "Failed",
        expired: "Time is up — no card was tapped",
        cancelled: "Cancelled",
        error: "Could not start",
      },
      pendingHint: "Within a few seconds the connector writes this person's ID to the machine and waits for the card.",
      waitingHint: (name) => `Ask ${name} to tap the card once on the K40.`,
      secondsLeft: (s) => `${s} sec left`,
      cardNumber: (n) => `Card number: ${n}`,
      start: "Start",
      retry: "Try again",
      cancel: "Cancel",
      close: "Close",
      startFailed: "Could not start the enrollment",
      pollFailed: "Problem reaching the server — please try again",
      connectorOfflineNow: "The connector seems offline — check that the PC and the connector program are running.",
      manualLabel: "Card number",
      manualPlaceholder: "e.g. 0012345678",
      manualHint: "With a USB card reader, click this box and tap the card — the number is typed and saved on Enter.",
      save: "Save",
      saving: "Saving...",
      cardSaved: (name) => `${name} - card linked`,
      invalidCard: "Digits only (up to 20, not zero)",
      saveFailed: "Could not save",
      currentPin: "Device ID",
      currentCard: "Current card",
      none: "None",
      replaceWarning: "A new card replaces the previous one.",
      pinAutoHint: "An ID is created automatically if missing.",
    },
    series: {
      title: "Series mode — Card enrollment",
      progress: (cur, total) => `${cur} / ${total}`,
      enrolledCount: (n) => `Linked ${n}`,
      failedCount: (n) => ` · failed ${n}`,
      nowEnrolling: "Now enrolling",
      nextLabel: "Next:",
      previous: "Previous",
      skip: "Skip",
      previousKey: "Previous (←)",
      skipKey: "Skip (→)",
      finishedTitle: "Series finished!",
      finishedSummary: (done, skipped) => `${done} cards linked, ${skipped} skipped.`,
      goBack: "Go back",
      done: "Done",
      keyboardHint: "Enter = save / retry · → = skip · ← = previous · Esc = close",
      readerLabel: "USB reader or typed number",
      recent: "Recent",
      success: "Done!",
      autoNext: "Moving to the next person...",
      empty: "No one without a card",
    },
  },
});
