import { defineText } from "@madrasha/shared-ui/src/i18n";

export const websiteText = defineText({
  bn: {
    sections: {
      show_notice_bar: ["চলমান নোটিশ বার", "নেভবারের নিচে স্ক্রলিং নোটিশ বার দেখাবে"],
      show_slider: ["হোম স্লাইডার", "হোমপেজে ছবির স্লাইডার দেখাবে"],
      show_about: ["আমাদের সম্পর্কে", "প্রতিষ্ঠানের পরিচিতি সেকশন দেখাবে"],
      show_muhtamim: ["{{head}}ের বাণী", "{{head}} সাহেবের বাণী সেকশন দেখাবে"],
      show_sovapoti: ["সভাপতির বাণী", "সভাপতি সাহেবের বাণী সেকশন দেখাবে"],
      show_admission: ["ভর্তি তথ্য", "ভর্তি সংক্রান্ত সেকশন দেখাবে"],
      show_notices: ["নোটিশ বোর্ড", "নোটিশ বোর্ড সেকশন দেখাবে"],
      show_gallery: ["গ্যালারি", "ছবি গ্যালারি সেকশন দেখাবে"],
      show_video_gallery: ["ভিডিও গ্যালারি", "ভিডিও গ্যালারি সেকশন দেখাবে"],
      show_teachers: ["{{teacher}}মণ্ডলী", "{{teacher}}দের তালিকা সেকশন দেখাবে"],
      show_committee: ["{{institution}} কমিটি", "কমিটির সদস্যদের তালিকা দেখাবে"],
      show_contact: ["যোগাযোগ", "যোগাযোগ তথ্য সেকশন দেখাবে"],
    } as Record<string, [string, string]>,
    themes: {
      classic: ["ক্লাসিক", "সাদা হেডারের নিচে রঙিন মেনু ব্যান্ড, নরম শ্যাডো কার্ড (বর্তমান ডিজাইন)"],
      modern: ["মডার্ন", "গোলাকার কার্ড, হালকা রঙিন সেকশন ব্যাকগ্রাউন্ড, এক লাইনের হেডার"],
      minimal: ["মিনিমাল", "ধারালো কোণ, বর্ডার-ভিত্তিক সাদামাটা ও পরিষ্কার লুক"],
    } as Record<string, [string, string]>,
    tabs: {
      general: "সাধারণ সেটিংস",
      appearance: "থিম ও হিরো ব্যানার",
      "notice-bar": "নোটিশ বার",
      notices: "নোটিশ",
      gallery: "গ্যালারি",
      video: "ভিডিও গ্যালারি",
      slider: "হিরো স্লাইডার",
      muhtamim: "{{head}}ের বাণী",
      sovapoti: "সভাপতির বাণী",
      committee: "{{institution}} কমিটি",
      social: "সোশ্যাল মিডিয়া",
      pages: "পেজ কন্টেন্ট",
    } as Record<string, string>,
    websiteTheme: "ওয়েবসাইট থিম",
    loadFailed: "সেটিংস লোড করতে সমস্যা হয়েছে। পেজ রিফ্রেশ করে আবার চেষ্টা করুন।",
    saved: "সংরক্ষণ হয়েছে।",
    saveFailed: "সংরক্ষণ করা যায়নি। আবার চেষ্টা করুন।",
    updated: "আপডেট হয়েছে।",
    updateFailed: "আপডেট করা যায়নি। আবার চেষ্টা করুন।",
    pageSaved: "পেজ সংরক্ষণ হয়েছে।",
    pageSaveFailed: "পেজ সংরক্ষণ করা যায়নি।",
    enterNoticeTitle: "নোটিশের শিরোনাম দিন।",
    noticeAdded: "নোটিশ যোগ করা হয়েছে।",
    noticeSaveFailed: "নোটিশ সংরক্ষণ করা যায়নি।",
    noticeUpdated: "নোটিশ আপডেট হয়েছে।",
    deleteNoticeTitle: "নোটিশ মুছুন",
    deleteNoticeMessage: (title: string) => `"${title}" নোটিশটি স্থায়ীভাবে মুছে ফেলতে চান?`,
    noticeDeleted: "নোটিশ মুছে ফেলা হয়েছে।",
    noticeDeleteFailed: "নোটিশ মুছতে সমস্যা হয়েছে।",
    enterVideoLink: "ভিডিও লিংক দিন।",
    videoAdded: "ভিডিও যোগ করা হয়েছে।",
    videoSaveFailed: "ভিডিও সংরক্ষণ করা যায়নি।",
    videoUpdated: "ভিডিও আপডেট হয়েছে।",
    deleteVideoTitle: "ভিডিও মুছুন",
    thisVideo: "এই ভিডিওটি",
    deleteItemMessage: (title: string) => `"${title}" স্থায়ীভাবে মুছে ফেলতে চান?`,
    videoDeleted: "ভিডিও মুছে ফেলা হয়েছে।",
    videoDeleteFailed: "ভিডিও মুছতে সমস্যা হয়েছে।",
    uploadImage: "ছবি আপলোড করুন।",
    galleryAdded: "গ্যালারিতে ছবি যোগ করা হয়েছে।",
    imageSaveFailed: "ছবি সংরক্ষণ করা যায়নি।",
    galleryUpdated: "গ্যালারি ছবি আপডেট হয়েছে।",
    deleteGalleryTitle: "গ্যালারি ছবি মুছুন",
    thisImage: "এই ছবিটি",
    imageDeleted: "ছবি মুছে ফেলা হয়েছে।",
    imageDeleteFailed: "ছবি মুছতে সমস্যা হয়েছে।",
    uploadSlideImage: "স্লাইডের ছবি আপলোড করুন।",
    slideAdded: "স্লাইড যোগ করা হয়েছে।",
    slideSaveFailed: "স্লাইড সংরক্ষণ করা যায়নি।",
    slideUpdated: "স্লাইড আপডেট হয়েছে।",
    deleteSlideTitle: "স্লাইড মুছুন",
    deleteSlideMessage: "এই স্লাইডটি স্থায়ীভাবে মুছে ফেলতে চান?",
    slideDeleted: "স্লাইড মুছে ফেলা হয়েছে।",
    slideDeleteFailed: "স্লাইড মুছতে সমস্যা হয়েছে।",
    enterMemberName: "সদস্যের নাম দিন।",
    memberAdded: "কমিটির সদস্য যোগ করা হয়েছে।",
    memberUpdated: "কমিটির সদস্য আপডেট হয়েছে।",
    deleteMemberTitle: "কমিটির সদস্য মুছুন",
    deleteMemberMessage: (name: string) => `"${name}" কে স্থায়ীভাবে মুছে ফেলতে চান?`,
    memberDeleted: "সদস্য মুছে ফেলা হয়েছে।",
    deleteFailed: "মুছতে সমস্যা হয়েছে।",
    title: "ওয়েবসাইট সেটিংস",
    settingsMenu: "সেটিংস মেনু",
    subtitle: "প্রতিষ্ঠানের পাবলিক ওয়েবসাইটের নাম, লোগো, ব্যানার, নোটিশ, গ্যালারি ও পেজ কন্টেন্ট এখান থেকে পরিচালনা করুন।",
    viewWebsite: "ওয়েবসাইট দেখুন",
    websitePublished: "ওয়েবসাইট প্রকাশিত",
    live: "লাইভ আছে",
    offline: "বন্ধ আছে",
    masterSwitchHint: "এটি মাস্টার সুইচ — বন্ধ করলে পুরো পাবলিক ওয়েবসাইট (সব ট্যাবের সব সেকশনসহ) সবার কাছে অদৃশ্য হয়ে যাবে।",
    sectionVisibility: "সেকশন দৃশ্যমানতা",
    sectionVisibilityHint: "ক্লিক করলেই সাথে সাথে আপডেট হয়ে যাবে — কোন সেকশনগুলো পাবলিক ওয়েবসাইটে দেখাবে তা নিয়ন্ত্রণ করুন",
    institutionInfoLogo: "প্রতিষ্ঠান পরিচিতি ও লোগো",
    brandingNoteBefore: "প্রতিষ্ঠানের নাম, ঠিকানা, যোগাযোগ ও লোগো এখন",
    brandingSettings: "প্রতিষ্ঠান ব্র্যান্ডিং সেটিংস",
    brandingNoteAfter: "থেকে স্বয়ংক্রিয়ভাবে নেওয়া হয়, যাতে একই তথ্য ওয়েবসাইট ও আইডি কার্ড/মার্কশিটের মতো সব রিপোর্টে একইরকম দেখায়।",
    editInBranding: "প্রতিষ্ঠান ব্র্যান্ডিং সেটিংসে সম্পাদনা করুন",
    themeHint: "নিচের থিম কালার প্রতিটি থিমেই প্রযোজ্য হবে।",
    themeColor: "থিম কালার",
    homeBanner: "হোমপেজ ব্যানার",
    heroTitle: "হিরো শিরোনাম",
    heroTitlePlaceholder: "প্রতিষ্ঠানের নাম/স্বাগতম বার্তা",
    heroSubtitle: "হিরো সাব-টাইটেল",
    noticeBar: "চলমান নোটিশ বার",
    noticeBarHint: "হোমপেজের একদম উপরে এই লেখাগুলো স্ক্রল হয়ে চলবে। খালি রাখলে বার দেখাবে না।",
    noticeText: "নোটিশ লেখা",
    noticeTextPlaceholder: "যেমনঃ আগামী ১৫ই রমজান থেকে ভর্তি কার্যক্রম শুরু হবে।",
    speed: "গতি (স্পিড)",
    speedHint: "কম মান = দ্রুত স্ক্রল, বেশি মান = ধীর স্ক্রল",
    headMessage: "{{head}} সাহেবের বাণী",
    designation: "পদবি",
    headNamePlaceholder: "মাওলানা মুহাম্মদ ...",
    headDesignationPlaceholder: "{{head}} ও শায়খুল হাদীস",
    headPhoto: "{{head}} সাহেবের ছবি",
    message: "বাণী",
    headMessagePlaceholder: "{{head}} সাহেবের বাণী লিখুন...",
    presidentMessage: "সভাপতি সাহেবের বাণী",
    presidentNamePlaceholder: "আলহাজ্ব মুহাম্মদ ...",
    presidentDesignationPlaceholder: "সভাপতি, {{institution}} পরিচালনা পর্ষদ",
    presidentPhoto: "সভাপতি সাহেবের ছবি",
    presidentMessagePlaceholder: "সভাপতি সাহেবের বাণী লিখুন...",
    socialLinks: "সোশ্যাল মিডিয়া লিংক",
    socialLinksHint: "খালি রাখলে সেই আইকনটি পাবলিক ওয়েবসাইটের ফুটার ও WhatsApp বাটনে দেখাবে না।",
    facebookUrl: "ফেসবুক পেজ URL",
    youtubeUrl: "ইউটিউব চ্যানেল URL",
    instagramUrl: "ইনস্টাগ্রাম প্রোফাইল URL",
    whatsappUrl: "WhatsApp চ্যানেল URL",
    locationMap: "লোকেশন ম্যাপ",
    locationMapHint:
      "Google Maps-এ প্রতিষ্ঠানের লোকেশন খুলে Share → Copy link করে এখানে দিন। ফুটারের যোগাযোগ কলামে ছোট ম্যাপে ক্লিক করলে এই লিংকে যাবে। খালি রাখলে ঠিকানা দিয়ে ম্যাপ খুঁজবে।",
    mapsLink: "Google Maps লিংক",
    pageContent: "পেজ কন্টেন্ট",
    pageContentHint: "আমাদের সম্পর্কে, ভর্তি তথ্য ও যোগাযোগ পেজের লেখা এখান থেকে সম্পাদনা করুন",
    unpublished: "অপ্রকাশিত",
    noContent: "কোনো কন্টেন্ট যোগ করা হয়নি",
    addNotice: "নতুন নোটিশ যোগ করুন",
    noticeTitlePlaceholder: "নোটিশের শিরোনাম",
    noticeDetailsPlaceholder: "নোটিশের বিস্তারিত",
    allNotices: "সব নোটিশ",
    allNoticesHint: "যেকোনো তথ্যের পাশের পেন্সিল আইকনে ক্লিক করলে সেটি এডিট করা যাবে",
    draftUnpublished: "খসড়া / অপ্রকাশিত",
    noNotices: "এখনো কোনো নোটিশ যোগ করা হয়নি",
    noNoticesHint: "উপরের ফর্ম থেকে প্রথম নোটিশটি যোগ করুন।",
    addImage: "নতুন ছবি যোগ করুন",
    imageTitle: "ছবির শিরোনাম",
    imageTitlePlaceholder: "যেমন: বার্ষিক সমাবর্তন ২০২৬",
    position: "ক্রম (অবস্থান)",
    atEnd: " (সবার শেষে)",
    allImages: "সব ছবি",
    allImagesHint: "যেকোনো ছবির পেন্সিল আইকনে ক্লিক করলে সেটি এডিট করা যাবে",
    galleryImage: "গ্যালারি ছবি",
    noGallery: "এখনো কোনো গ্যালারি ছবি যোগ করা হয়নি",
    noGalleryHint: "উপরের ফর্ম থেকে প্রথম ছবিটি যোগ করুন।",
    addVideo: "নতুন ভিডিও যোগ করুন",
    addVideoHint: "ইউটিউব ভিডিওর লিংক পেস্ট করুন (যেমন: https://youtube.com/watch?v=... বা https://youtu.be/...)",
    videoLink: "ভিডিও লিংক",
    videoTitle: "ভিডিওর শিরোনাম",
    videoTitlePlaceholder: "যেমন: বার্ষিক মাহফিল ২০২৬",
    allVideos: "সব ভিডিও",
    allVideosHint: "যেকোনো ভিডিওর পেন্সিল আইকনে ক্লিক করলে সেটি এডিট করা যাবে",
    video: "ভিডিও",
    noVideos: "এখনো কোনো ভিডিও যোগ করা হয়নি",
    noVideosHint: "উপরের ফর্ম থেকে ইউটিউব লিংক যোগ করুন।",
    addSlide: "নতুন স্লাইড যোগ করুন",
    slideImage: "স্লাইড ছবি",
    slideImageHint:
      "সাইজ: 2100 × 900px (২১:৯) — অন্য সাইজ দিলেও মাঝখান থেকে কেটে স্বয়ংক্রিয়ভাবে এই সাইজে রূপান্তরিত হয়ে JPG আকারে সংরক্ষণ হবে।",
    ratio219: "অনুপাত ২১:৯",
    linkOptional: "লিংক (ঐচ্ছিক)",
    linkPlaceholder: "https://... অথবা /admission",
    slideLinkHint: "দিলে স্লাইডে ক্লিক করলে এই লিংকে চলে যাবে।",
    allSlides: "সব স্লাইড",
    allSlidesHint: "যেকোনো স্লাইডের পেন্সিল আইকনে ক্লিক করলে সেটি এডিট করা যাবে",
    noLink: "লিংক নেই",
    noSlides: "এখনো কোনো স্লাইড যোগ করা হয়নি",
    noSlidesHint: "স্লাইড যোগ করলে হোমপেজে স্লাইডার হিসেবে দেখা যাবে।",
    addMember: "নতুন সদস্য যোগ করুন",
    designationPlaceholder: "যেমন: সভাপতি",
    phoneOptional: "ফোন (ঐচ্ছিক)",
    members: "কমিটির সদস্যরা",
    membersHint: "যেকোনো সদস্যের পেন্সিল আইকনে ক্লিক করলে সেটি এডিট করা যাবে",
    noMembers: "এখনো কোনো কমিটির সদস্য যোগ করা হয়নি",
    noMembersHint: "কমিটির সদস্য যোগ করলে পাবলিক ওয়েবসাইটে দেখা যাবে।",
  },
  en: {
    sections: {
      show_notice_bar: ["Scrolling notice bar", "Shows a scrolling notice bar below the navbar"],
      show_slider: ["Home slider", "Shows the image slider on the homepage"],
      show_about: ["About us", "Shows the {{institution}} introduction section"],
      show_muhtamim: ["{{head}}'s message", "Shows the {{head}}'s message section"],
      show_sovapoti: ["President's message", "Shows the president's message section"],
      show_admission: ["Admission info", "Shows the admission section"],
      show_notices: ["Notice board", "Shows the notice board section"],
      show_gallery: ["Gallery", "Shows the photo gallery section"],
      show_video_gallery: ["Video gallery", "Shows the video gallery section"],
      show_teachers: ["{{teacher}}s", "Shows the {{teacher}} list section"],
      show_committee: ["{{institution}} committee", "Shows the list of committee members"],
      show_contact: ["Contact", "Shows the contact information section"],
    },
    themes: {
      classic: ["Classic", "Colored menu band under a white header, soft shadow cards (current design)"],
      modern: ["Modern", "Rounded cards, lightly tinted section backgrounds, single-line header"],
      minimal: ["Minimal", "Sharp corners, border-based plain and clean look"],
    },
    tabs: {
      general: "General settings",
      appearance: "Theme & hero banner",
      "notice-bar": "Notice bar",
      notices: "Notices",
      gallery: "Gallery",
      video: "Video gallery",
      slider: "Hero slider",
      muhtamim: "{{head}}'s message",
      sovapoti: "President's message",
      committee: "{{institution}} committee",
      social: "Social media",
      pages: "Page content",
    },
    websiteTheme: "Website theme",
    loadFailed: "Could not load settings. Refresh the page and try again.",
    saved: "Saved.",
    saveFailed: "Could not save. Please try again.",
    updated: "Updated.",
    updateFailed: "Could not update. Please try again.",
    pageSaved: "Page saved.",
    pageSaveFailed: "Could not save the page.",
    enterNoticeTitle: "Enter the notice title.",
    noticeAdded: "Notice added.",
    noticeSaveFailed: "Could not save the notice.",
    noticeUpdated: "Notice updated.",
    deleteNoticeTitle: "Delete notice",
    deleteNoticeMessage: (title) => `Permanently delete the notice "${title}"?`,
    noticeDeleted: "Notice deleted.",
    noticeDeleteFailed: "Could not delete the notice.",
    enterVideoLink: "Enter the video link.",
    videoAdded: "Video added.",
    videoSaveFailed: "Could not save the video.",
    videoUpdated: "Video updated.",
    deleteVideoTitle: "Delete video",
    thisVideo: "this video",
    deleteItemMessage: (title) => `Permanently delete "${title}"?`,
    videoDeleted: "Video deleted.",
    videoDeleteFailed: "Could not delete the video.",
    uploadImage: "Upload an image.",
    galleryAdded: "Image added to the gallery.",
    imageSaveFailed: "Could not save the image.",
    galleryUpdated: "Gallery image updated.",
    deleteGalleryTitle: "Delete gallery image",
    thisImage: "this image",
    imageDeleted: "Image deleted.",
    imageDeleteFailed: "Could not delete the image.",
    uploadSlideImage: "Upload the slide image.",
    slideAdded: "Slide added.",
    slideSaveFailed: "Could not save the slide.",
    slideUpdated: "Slide updated.",
    deleteSlideTitle: "Delete slide",
    deleteSlideMessage: "Permanently delete this slide?",
    slideDeleted: "Slide deleted.",
    slideDeleteFailed: "Could not delete the slide.",
    enterMemberName: "Enter the member's name.",
    memberAdded: "Committee member added.",
    memberUpdated: "Committee member updated.",
    deleteMemberTitle: "Delete committee member",
    deleteMemberMessage: (name) => `Permanently delete "${name}"?`,
    memberDeleted: "Member deleted.",
    deleteFailed: "Could not delete.",
    title: "Website Settings",
    settingsMenu: "Settings menu",
    subtitle: "Manage the public website's name, logo, banner, notices, gallery and page content here.",
    viewWebsite: "View website",
    websitePublished: "Website published",
    live: "Live",
    offline: "Offline",
    masterSwitchHint: "This is the master switch — turning it off hides the entire public website (every section of every tab) from everyone.",
    sectionVisibility: "Section visibility",
    sectionVisibilityHint: "Changes apply instantly on click — choose which sections appear on the public website",
    institutionInfoLogo: "Institution info & logo",
    brandingNoteBefore: "The institution's name, address, contact and logo now come automatically from",
    brandingSettings: "Institution Branding Settings",
    brandingNoteAfter: ", so the same information looks identical on the website and on every report such as ID cards and marksheets.",
    editInBranding: "Edit in Institution Branding Settings",
    themeHint: "The theme color below applies to every theme.",
    themeColor: "Theme color",
    homeBanner: "Homepage banner",
    heroTitle: "Hero title",
    heroTitlePlaceholder: "Institution name / welcome message",
    heroSubtitle: "Hero subtitle",
    noticeBar: "Scrolling notice bar",
    noticeBarHint: "This text scrolls at the very top of the homepage. Leave empty to hide the bar.",
    noticeText: "Notice text",
    noticeTextPlaceholder: "e.g. Admission starts on 15 Ramadan.",
    speed: "Speed",
    speedHint: "Lower value = faster scroll, higher value = slower scroll",
    headMessage: "{{head}}'s message",
    designation: "Designation",
    headNamePlaceholder: "Maulana Muhammad ...",
    headDesignationPlaceholder: "{{head}} & Shaykh al-Hadith",
    headPhoto: "{{head}}'s photo",
    message: "Message",
    headMessagePlaceholder: "Write the {{head}}'s message...",
    presidentMessage: "President's message",
    presidentNamePlaceholder: "Alhaj Muhammad ...",
    presidentDesignationPlaceholder: "President, {{institution}} governing body",
    presidentPhoto: "President's photo",
    presidentMessagePlaceholder: "Write the president's message...",
    socialLinks: "Social media links",
    socialLinksHint: "Leave a field empty to hide that icon in the public website footer and WhatsApp button.",
    facebookUrl: "Facebook page URL",
    youtubeUrl: "YouTube channel URL",
    instagramUrl: "Instagram profile URL",
    whatsappUrl: "WhatsApp channel URL",
    locationMap: "Location map",
    locationMapHint:
      "Open the institution's location in Google Maps, use Share → Copy link and paste it here. Clicking the small map in the footer's contact column opens this link. If empty, the map searches by address.",
    mapsLink: "Google Maps link",
    pageContent: "Page content",
    pageContentHint: "Edit the text of the About, Admission and Contact pages here",
    unpublished: "Unpublished",
    noContent: "No content added",
    addNotice: "Add new notice",
    noticeTitlePlaceholder: "Notice title",
    noticeDetailsPlaceholder: "Notice details",
    allNotices: "All notices",
    allNoticesHint: "Click the pencil icon next to any item to edit it",
    draftUnpublished: "Draft / unpublished",
    noNotices: "No notices added yet",
    noNoticesHint: "Add the first notice using the form above.",
    addImage: "Add new image",
    imageTitle: "Image title",
    imageTitlePlaceholder: "e.g. Annual convocation 2026",
    position: "Order (position)",
    atEnd: " (at the end)",
    allImages: "All images",
    allImagesHint: "Click the pencil icon on any image to edit it",
    galleryImage: "Gallery image",
    noGallery: "No gallery images added yet",
    noGalleryHint: "Add the first image using the form above.",
    addVideo: "Add new video",
    addVideoHint: "Paste a YouTube video link (e.g. https://youtube.com/watch?v=... or https://youtu.be/...)",
    videoLink: "Video link",
    videoTitle: "Video title",
    videoTitlePlaceholder: "e.g. Annual Mahfil 2026",
    allVideos: "All videos",
    allVideosHint: "Click the pencil icon on any video to edit it",
    video: "Video",
    noVideos: "No videos added yet",
    noVideosHint: "Add a YouTube link using the form above.",
    addSlide: "Add new slide",
    slideImage: "Slide image",
    slideImageHint:
      "Size: 2100 × 900px (21:9) — other sizes are center-cropped and converted to this size automatically and saved as JPG.",
    ratio219: "Ratio 21:9",
    linkOptional: "Link (optional)",
    linkPlaceholder: "https://... or /admission",
    slideLinkHint: "If set, clicking the slide opens this link.",
    allSlides: "All slides",
    allSlidesHint: "Click the pencil icon on any slide to edit it",
    noLink: "No link",
    noSlides: "No slides added yet",
    noSlidesHint: "Added slides appear as a slider on the homepage.",
    addMember: "Add new member",
    designationPlaceholder: "e.g. President",
    phoneOptional: "Phone (optional)",
    members: "Committee members",
    membersHint: "Click the pencil icon on any member to edit",
    noMembers: "No committee members added yet",
    noMembersHint: "Added committee members appear on the public website.",
  },
  ar: {
    sections: {
      show_notice_bar: ["شريط الإعلانات المتحرك", "يُظهر شريط إعلانات متحركًا أسفل شريط التنقل"],
      show_slider: ["عارض الصفحة الرئيسية", "يُظهر عارض الصور في الصفحة الرئيسية"],
      show_about: ["من نحن", "يُظهر قسم التعريف بـ{{institution}}"],
      show_muhtamim: ["كلمة {{head}}", "يُظهر قسم كلمة {{head}}"],
      show_sovapoti: ["كلمة الرئيس", "يُظهر قسم كلمة رئيس المجلس"],
      show_admission: ["معلومات القبول", "يُظهر قسم القبول"],
      show_notices: ["لوحة الإعلانات", "يُظهر قسم لوحة الإعلانات"],
      show_gallery: ["معرض الصور", "يُظهر قسم معرض الصور"],
      show_video_gallery: ["معرض الفيديو", "يُظهر قسم معرض الفيديو"],
      show_teachers: ["هيئة التدريس", "يُظهر قسم قائمة المعلمين"],
      show_committee: ["لجنة المؤسسة", "يُظهر قائمة أعضاء اللجنة"],
      show_contact: ["التواصل", "يُظهر قسم معلومات التواصل"],
    },
    themes: {
      classic: ["كلاسيكي", "شريط قوائم ملون أسفل ترويسة بيضاء، وبطاقات بظلال ناعمة (التصميم الحالي)"],
      modern: ["عصري", "بطاقات دائرية الحواف، وخلفيات أقسام ملونة خفيفة، وترويسة بسطر واحد"],
      minimal: ["بسيط", "زوايا حادة ومظهر بسيط ونظيف قائم على الحدود"],
    },
    tabs: {
      general: "الإعدادات العامة",
      appearance: "السمة والبانر الرئيسي",
      "notice-bar": "شريط الإعلانات",
      notices: "الإعلانات",
      gallery: "معرض الصور",
      video: "معرض الفيديو",
      slider: "العارض الرئيسي",
      muhtamim: "كلمة {{head}}",
      sovapoti: "كلمة الرئيس",
      committee: "لجنة المؤسسة",
      social: "التواصل الاجتماعي",
      pages: "محتوى الصفحات",
    },
    websiteTheme: "سمة الموقع",
    loadFailed: "تعذّر تحميل الإعدادات. حدّث الصفحة وحاول مرة أخرى.",
    saved: "تم الحفظ.",
    saveFailed: "تعذّر الحفظ. حاول مرة أخرى.",
    updated: "تم التحديث.",
    updateFailed: "تعذّر التحديث. حاول مرة أخرى.",
    pageSaved: "تم حفظ الصفحة.",
    pageSaveFailed: "تعذّر حفظ الصفحة.",
    enterNoticeTitle: "أدخل عنوان الإعلان.",
    noticeAdded: "تمت إضافة الإعلان.",
    noticeSaveFailed: "تعذّر حفظ الإعلان.",
    noticeUpdated: "تم تحديث الإعلان.",
    deleteNoticeTitle: "حذف الإعلان",
    deleteNoticeMessage: (title) => `هل تريد حذف الإعلان "${title}" نهائيًا؟`,
    noticeDeleted: "تم حذف الإعلان.",
    noticeDeleteFailed: "تعذّر حذف الإعلان.",
    enterVideoLink: "أدخل رابط الفيديو.",
    videoAdded: "تمت إضافة الفيديو.",
    videoSaveFailed: "تعذّر حفظ الفيديو.",
    videoUpdated: "تم تحديث الفيديو.",
    deleteVideoTitle: "حذف الفيديو",
    thisVideo: "هذا الفيديو",
    deleteItemMessage: (title) => `هل تريد حذف "${title}" نهائيًا؟`,
    videoDeleted: "تم حذف الفيديو.",
    videoDeleteFailed: "تعذّر حذف الفيديو.",
    uploadImage: "ارفع صورة.",
    galleryAdded: "تمت إضافة الصورة إلى المعرض.",
    imageSaveFailed: "تعذّر حفظ الصورة.",
    galleryUpdated: "تم تحديث صورة المعرض.",
    deleteGalleryTitle: "حذف صورة المعرض",
    thisImage: "هذه الصورة",
    imageDeleted: "تم حذف الصورة.",
    imageDeleteFailed: "تعذّر حذف الصورة.",
    uploadSlideImage: "ارفع صورة الشريحة.",
    slideAdded: "تمت إضافة الشريحة.",
    slideSaveFailed: "تعذّر حفظ الشريحة.",
    slideUpdated: "تم تحديث الشريحة.",
    deleteSlideTitle: "حذف الشريحة",
    deleteSlideMessage: "هل تريد حذف هذه الشريحة نهائيًا؟",
    slideDeleted: "تم حذف الشريحة.",
    slideDeleteFailed: "تعذّر حذف الشريحة.",
    enterMemberName: "أدخل اسم العضو.",
    memberAdded: "تمت إضافة عضو اللجنة.",
    memberUpdated: "تم تحديث عضو اللجنة.",
    deleteMemberTitle: "حذف عضو اللجنة",
    deleteMemberMessage: (name) => `هل تريد حذف "${name}" نهائيًا؟`,
    memberDeleted: "تم حذف العضو.",
    deleteFailed: "تعذّر الحذف.",
    title: "إعدادات الموقع",
    settingsMenu: "قائمة الإعدادات",
    subtitle: "أدِر اسم الموقع العام وشعاره والبانر والإعلانات والمعرض ومحتوى الصفحات من هنا.",
    viewWebsite: "عرض الموقع",
    websitePublished: "الموقع منشور",
    live: "مباشر",
    offline: "متوقف",
    masterSwitchHint: "هذا هو المفتاح الرئيسي — إيقافه يخفي الموقع العام بالكامل (كل أقسام كل التبويبات) عن الجميع.",
    sectionVisibility: "ظهور الأقسام",
    sectionVisibilityHint: "يُطبَّق التغيير فور النقر — تحكّم في الأقسام التي تظهر على الموقع العام",
    institutionInfoLogo: "تعريف المؤسسة والشعار",
    brandingNoteBefore: "يُؤخذ اسم المؤسسة وعنوانها ومعلومات التواصل والشعار الآن تلقائيًا من",
    brandingSettings: "إعدادات هوية المؤسسة",
    brandingNoteAfter: "، لتظهر المعلومات نفسها بشكل موحّد على الموقع وفي جميع التقارير مثل البطاقات وكشوف الدرجات.",
    editInBranding: "التعديل في إعدادات هوية المؤسسة",
    themeHint: "يُطبَّق لون السمة أدناه على كل السمات.",
    themeColor: "لون السمة",
    homeBanner: "بانر الصفحة الرئيسية",
    heroTitle: "العنوان الرئيسي",
    heroTitlePlaceholder: "اسم المؤسسة / رسالة ترحيب",
    heroSubtitle: "العنوان الفرعي",
    noticeBar: "شريط الإعلانات المتحرك",
    noticeBarHint: "يتحرك هذا النص أعلى الصفحة الرئيسية. اتركه فارغًا لإخفاء الشريط.",
    noticeText: "نص الإعلان",
    noticeTextPlaceholder: "مثال: يبدأ القبول في ١٥ رمضان.",
    speed: "السرعة",
    speedHint: "قيمة أقل = تمرير أسرع، قيمة أعلى = تمرير أبطأ",
    headMessage: "كلمة {{head}}",
    designation: "المنصب",
    headNamePlaceholder: "الشيخ محمد ...",
    headDesignationPlaceholder: "{{head}} وشيخ الحديث",
    headPhoto: "صورة {{head}}",
    message: "الكلمة",
    headMessagePlaceholder: "اكتب كلمة {{head}}...",
    presidentMessage: "كلمة الرئيس",
    presidentNamePlaceholder: "الحاج محمد ...",
    presidentDesignationPlaceholder: "رئيس مجلس إدارة المؤسسة",
    presidentPhoto: "صورة الرئيس",
    presidentMessagePlaceholder: "اكتب كلمة الرئيس...",
    socialLinks: "روابط التواصل الاجتماعي",
    socialLinksHint: "اترك الحقل فارغًا لإخفاء الأيقونة في تذييل الموقع وزر واتساب.",
    facebookUrl: "رابط صفحة فيسبوك",
    youtubeUrl: "رابط قناة يوتيوب",
    instagramUrl: "رابط حساب إنستغرام",
    whatsappUrl: "رابط قناة واتساب",
    locationMap: "خريطة الموقع",
    locationMapHint:
      "افتح موقع المؤسسة في خرائط Google ثم Share → Copy link والصقه هنا. يؤدي النقر على الخريطة الصغيرة في عمود التواصل بالتذييل إلى هذا الرابط. إن تُرك فارغًا يُبحث في الخريطة بالعنوان.",
    mapsLink: "رابط خرائط Google",
    pageContent: "محتوى الصفحات",
    pageContentHint: "حرّر نصوص صفحات من نحن والقبول والتواصل من هنا",
    unpublished: "غير منشور",
    noContent: "لم يُضف أي محتوى",
    addNotice: "إضافة إعلان جديد",
    noticeTitlePlaceholder: "عنوان الإعلان",
    noticeDetailsPlaceholder: "تفاصيل الإعلان",
    allNotices: "جميع الإعلانات",
    allNoticesHint: "اضغط على أيقونة القلم بجانب أي عنصر لتعديله",
    draftUnpublished: "مسودة / غير منشور",
    noNotices: "لم تُضف أي إعلانات بعد",
    noNoticesHint: "أضف أول إعلان من النموذج أعلاه.",
    addImage: "إضافة صورة جديدة",
    imageTitle: "عنوان الصورة",
    imageTitlePlaceholder: "مثال: حفل التخرج السنوي ٢٠٢٦",
    position: "الترتيب (الموضع)",
    atEnd: " (في النهاية)",
    allImages: "جميع الصور",
    allImagesHint: "اضغط على أيقونة القلم على أي صورة لتعديلها",
    galleryImage: "صورة المعرض",
    noGallery: "لم تُضف أي صور للمعرض بعد",
    noGalleryHint: "أضف أول صورة من النموذج أعلاه.",
    addVideo: "إضافة فيديو جديد",
    addVideoHint: "الصق رابط فيديو يوتيوب (مثل: https://youtube.com/watch?v=... أو https://youtu.be/...)",
    videoLink: "رابط الفيديو",
    videoTitle: "عنوان الفيديو",
    videoTitlePlaceholder: "مثال: المحفل السنوي ٢٠٢٦",
    allVideos: "جميع الفيديوهات",
    allVideosHint: "اضغط على أيقونة القلم على أي فيديو لتعديله",
    video: "فيديو",
    noVideos: "لم تُضف أي فيديوهات بعد",
    noVideosHint: "أضف رابط يوتيوب من النموذج أعلاه.",
    addSlide: "إضافة شريحة جديدة",
    slideImage: "صورة الشريحة",
    slideImageHint: "الحجم: 2100 × 900px (٢١:٩) — الأحجام الأخرى تُقص من المنتصف وتُحوَّل تلقائيًا إلى هذا الحجم وتُحفظ بصيغة JPG.",
    ratio219: "النسبة ٢١:٩",
    linkOptional: "رابط (اختياري)",
    linkPlaceholder: "https://... أو /admission",
    slideLinkHint: "عند تحديده، يؤدي النقر على الشريحة إلى هذا الرابط.",
    allSlides: "جميع الشرائح",
    allSlidesHint: "اضغط على أيقونة القلم على أي شريحة لتعديلها",
    noLink: "لا يوجد رابط",
    noSlides: "لم تُضف أي شرائح بعد",
    noSlidesHint: "تظهر الشرائح المضافة كعارض في الصفحة الرئيسية.",
    addMember: "إضافة عضو جديد",
    designationPlaceholder: "مثال: الرئيس",
    phoneOptional: "الهاتف (اختياري)",
    members: "أعضاء اللجنة",
    membersHint: "اضغط على أيقونة القلم على أي عضو لتعديله",
    noMembers: "لم يُضف أي عضو في اللجنة بعد",
    noMembersHint: "يظهر أعضاء اللجنة المضافون على الموقع العام.",
  },
});
