import { defineBilingualText } from "@madrasha/shared-ui/src/i18n";

/** System document-template library + editor. */
export const documentTemplatesText = defineBilingualText({
  bn: {
    title: "ডকুমেন্ট টেমপ্লেট",
    subtitle: "আইডি কার্ড, প্রবেশপত্র ও অন্যান্য ডকুমেন্টের সিস্টেম-ব্যাপী টেমপ্লেট লাইব্রেরি ম্যানেজ করুন",
    newTemplate: "নতুন টেমপ্লেট",
    newTemplateName: (type: string) => `নতুন ${type}`,
    listLoadFailed: "টেমপ্লেট তালিকা লোড করা যায়নি",
    createFailed: "নতুন টেমপ্লেট তৈরি করা যায়নি, আবার চেষ্টা করুন",
    setDefaultFailed: "সিস্টেম ডিফল্ট নির্ধারণ করা যায়নি — প্রথমে প্রকাশ করুন",
    confirmDelete: (name: string) => `"${name}" টেমপ্লেটটি মুছে ফেলতে চান?`,
    deleteFailed: "মুছে ফেলা যায়নি",
    empty: "এই ধরনের কোনো সিস্টেম টেমপ্লেট নেই। একটি নতুন টেমপ্লেট তৈরি করুন।",
    systemDefault: "সিস্টেম ডিফল্ট",
    draft: "খসড়া",
    published: "প্রকাশিত",
    edit: "এডিট",
    setDefault: "ডিফল্ট করুন",
    delete: "মুছুন",

    // editor
    invalidAddress: "অবৈধ ঠিকানা",
    notFound: "টেমপ্লেট পাওয়া যায়নি",
    draftSaved: "খসড়া সংরক্ষণ হয়েছে",
    saveFailed: "সেভ করা যায়নি, আবার চেষ্টা করুন",
    published_: "টেমপ্লেট প্রকাশিত হয়েছে",
    publishFailed: "প্রকাশ করা যায়নি, আবার চেষ্টা করুন",
    backToList: "ডকুমেন্ট টেমপ্লেটে ফিরে যান",
    editingBefore: "আপনি একটি ",
    editingAfter: " সিস্টেম টেমপ্লেট এডিট করছেন। প্রিভিউতে নমুনা ডেটা ব্যবহার হয় — কখনো আসল শিক্ষার্থীর ডেটা নয়।",
    editDemoData: "ডেমো ডেটা এডিট করুন",
    modified: " (পরিবর্তিত)",
    done: "সম্পন্ন — তালিকায় ফিরুন",
  },
  en: {
    title: "Document Templates",
    subtitle: "Manage the system-wide template library for ID Card, Admit Card and other documents",
    newTemplate: "New Template",
    newTemplateName: (type) => `New ${type}`,
    listLoadFailed: "Could not load the template list",
    createFailed: "Could not create the template, please try again",
    setDefaultFailed: "Could not set the system default — publish it first",
    confirmDelete: (name) => `Delete the template "${name}"?`,
    deleteFailed: "Could not delete",
    empty: "No system template of this type yet. Create a new one.",
    systemDefault: "System Default",
    draft: "Draft",
    published: "Published",
    edit: "Edit",
    setDefault: "Set Default",
    delete: "Delete",

    invalidAddress: "Invalid address",
    notFound: "Template not found",
    draftSaved: "Draft saved",
    saveFailed: "Could not save the draft, please try again",
    published_: "Template published",
    publishFailed: "Could not publish, please try again",
    backToList: "Back to Document Templates",
    editingBefore: "Editing a ",
    editingAfter: " system template. Preview uses sample data — never real student data.",
    editDemoData: "Edit demo data",
    modified: " (modified)",
    done: "Done — back to list",
  },
});
