import { defineText } from "@madrasha/shared-ui/src/i18n";

/**
 * Words printed on reports/documents (column headers, titles, captions,
 * signature lines). Printed pages read it with usePrintText (institution
 * default language); on-screen report chrome and Excel headers may read the
 * same entries with useText (the user's UI language).
 */
export const reportText = defineText({
  bn: {
    // ---- column headers / field labels ----
    col: {
      roll: "রোল",
      rollNo: "রোল নম্বর",
      rollNoShort: "রোল নং",
      regNo: "রেজিঃ নম্বর",
      regNoFull: "রেজিস্ট্রেশন নম্বর",
      regNoShort: "রেজি. নং",
      regAbbr: "রেজিঃ",
      studentName: "শিক্ষার্থীর নাম",
      examineeName: "পরীক্ষার্থীর নাম",
      name: "নাম",
      father: "পিতা",
      mother: "মাতা",
      fatherName: "পিতার নাম",
      motherName: "মাতার নাম",
      class: "{{class}}",
      currentClass: "বর্তমান {{class}}",
      division: "{{division}}",
      session: "{{session}}",
      sessionShort: "সেশন",
      exam: "পরীক্ষা",
      total: "মোট",
      average: "গড়",
      grade: "গ্রেড",
      madrasaGrade: "মাদরাসা গ্রেড",
      resultDivision: "ফলাফল বিভাগ",
      status: "স্ট্যাটাস",
      state: "অবস্থা",
      // Zero-width space between মেধা and ক্রম gives the browser a clean wrap
      // point in the narrow result-sheet column.
      rankWrap: "মেধা​ক্রম",
      rank: "মেধাক্রম",
      meritPosition: "মেধাস্থান",
      mobile: "মোবাইল",
      mobileNo: "মোবাইল নম্বর",
      altMobileNo: "বিকল্প মোবাইল নম্বর",
      emergencyMobile: "জরুরি মোবাইল",
      district: "জেলা",
      date: "তারিখ",
      dob: "জন্ম তারিখ",
      day: "দিন",
      start: "শুরু",
      end: "শেষ",
      startTime: "শুরুর সময়",
      endTime: "শেষ সময়",
      inTime: "ইন টাইম",
      outTime: "আউট টাইম",
      subject: "{{subject}}",
      subjectName: "{{subject}}ের নাম",
      teacher: "{{teacher}}",
      teacherName: "{{teacher}}ের নাম",
      designation: "পদবি",
      department: "ডিপার্টমেন্ট",
      qualification: "যোগ্যতা",
      email: "ইমেইল",
      joining: "যোগদান",
      joiningDate: "যোগদানের তারিখ",
      roomNo: "রুম নং",
      room: "কক্ষ",
      seatNo: "আসন নং",
      invigilatorName: "পরিদর্শকের নাম",
      duty: "দায়িত্ব",
      candidateNo: "প্রার্থী নং",
      eligibility: "যোগ্যতা",
      examinees: "পরীক্ষার্থী",
      absent: "অনুপস্থিত",
      pass: "পাশ",
      fail: "ফেল",
      passed: "কৃতকার্য",
      averageMark: "গড় নম্বর",
      highest: "সর্বোচ্চ",
      lowest: "সর্বনিম্ন",
      passRate: "পাশের হার (%)",
      topScorer: "সর্বোচ্চ ফলাফলকারী",
      obtainedMarks: "প্রাপ্ত নম্বর",
      fullMarks: "পূর্ণমান",
      totalMarks: "মোট নম্বর",
      serialShort: "ক্রম",
      signature: "স্বাক্ষর",
      marks: "নম্বর",
      totalPresent: "মোট উপস্থিত",
      photo: "ছবি",
    },

    // ---- status values coming from the backend (PASS/FAIL...) ----
    status: {
      PASS: "পাশ",
      FAIL: "ফেল",
      PRESENT: "উপস্থিত",
      ABSENT: "অনুপস্থিত",
      DRAFT: "খসড়া",
      PUBLISHED: "প্রকাশিত",
      INCOMPLETE: "অসম্পূর্ণ",
    } as Record<string, string>,
    /** Merit rank 1-3 as printed ordinals. */
    ordinals: ["১ম", "২য়", "৩য়"],
    absentShort: "অনু",

    // ---- context lines / fallbacks ----
    allDivisions: "সকল {{division}}",
    allClasses: "সকল {{class}}",
    allExams: "সকল পরীক্ষা",
    subjectN: (n: string) => `{{subject}} ${n}`,
    /** "জামাতঃ" label for madrasa; other institutions print the class term. */
    jamat: "জামাত",
    classTerm: "{{class}}",
    colon: "ঃ",
    divisionLabel: "{{division}}:",
    classLabel: "{{class}}:",
    subjectLabel: "{{subject}}:",
    yearLabel: "বছর:",
    monthLabel: "মাস:",
    pageLabel: "পৃষ্ঠা:",
    yearSuffix: " ইং",
    dateLabel: "তারিখ:",
    phoneLabel: "ফোন:",

    // ---- titles ----
    title: {
      resultSummary: "ফলাফল সারসংক্ষেপ",
      gradeScale: "গ্রেড স্কেল",
      resultSheet: "ফলাফল পত্র",
      classRoutine: "ক্লাস রুটিন",
      dailyAttendance: "দৈনন্দিন হাজিরা খাতা",
      digitalAttendance: "ডিজিটাল হাজিরা রিপোর্ট",
      residentialAttendance: "আবাসিক শিক্ষার্থী হাজিরা খাতা",
      examNumberSheet: "পরীক্ষার নম্বরপত্র",
      examSignatureSheet: "পরীক্ষার স্বাক্ষরপত্র",
      signatureNumberSheet: "স্বাক্ষর ও নম্বরপত্র",
      guardianPhoneList: "অভিভাবক মোবাইল নম্বর তালিকা",
      admissionList: "ভর্তি তালিকা",
      teacherList: "{{teacher}} তালিকা",
      teacherPhoneList: "{{teacher}}দের মোবাইল নম্বর তালিকা",
      marksheet: "মার্কশিট",
      admitCard: "প্রবেশপত্র",
      studentIdCard: "শিক্ষার্থী পরিচয়পত্র",
      examRules: "পরীক্ষার নিয়মাবলী",
      sanad: "সনদ পত্র",
      certificate: "সার্টিফিকেট",
      testimonial: "প্রত্যয়ন পত্র",
      transferLetter: "ছাড়পত্র",
      admissionForm: "শিক্ষার্থী ভর্তি ফরম",
    },

    // ---- signature captions ----
    sign: {
      head: "{{head}}-এর স্বাক্ষর",
      headSeal: "{{head}}-এর স্বাক্ষর ও সীল",
      examController: "পরীক্ষা নিয়ন্ত্রকের স্বাক্ষর",
      classTeacher: "{{class}} {{teacher}}ের স্বাক্ষর",
    },
    /** Default ID-card back "principal title" when the tenant set none. */
    headTitle: "{{head}}",
    institution: "{{institution}}",
  },
  en: {
    col: {
      roll: "Roll",
      rollNo: "Roll No.",
      rollNoShort: "Roll No.",
      regNo: "Reg. No.",
      regNoFull: "Registration No.",
      regNoShort: "Reg. No.",
      regAbbr: "Reg.",
      studentName: "Student Name",
      examineeName: "Examinee Name",
      name: "Name",
      father: "Father",
      mother: "Mother",
      fatherName: "Father's Name",
      motherName: "Mother's Name",
      class: "{{class}}",
      currentClass: "Current {{class}}",
      division: "{{division}}",
      session: "{{session}}",
      sessionShort: "Session",
      exam: "Exam",
      total: "Total",
      average: "Average",
      grade: "Grade",
      madrasaGrade: "Madrasa Grade",
      resultDivision: "Result Division",
      status: "Status",
      state: "Status",
      rankWrap: "Merit​Position",
      rank: "Merit Position",
      meritPosition: "Merit Position",
      mobile: "Mobile",
      mobileNo: "Mobile No.",
      altMobileNo: "Alternate Mobile No.",
      emergencyMobile: "Emergency Mobile",
      district: "District",
      date: "Date",
      dob: "Date of Birth",
      day: "Day",
      start: "Start",
      end: "End",
      startTime: "Start Time",
      endTime: "End Time",
      inTime: "In Time",
      outTime: "Out Time",
      subject: "{{subject}}",
      subjectName: "{{subject}} Name",
      teacher: "{{teacher}}",
      teacherName: "{{teacher}}'s Name",
      designation: "Designation",
      department: "Department",
      qualification: "Qualification",
      email: "Email",
      joining: "Joined",
      joiningDate: "Joining Date",
      roomNo: "Room No.",
      room: "Room",
      seatNo: "Seat No.",
      invigilatorName: "Invigilator Name",
      duty: "Duty",
      candidateNo: "Candidate No.",
      eligibility: "Eligibility",
      examinees: "Examinees",
      absent: "Absent",
      pass: "Pass",
      fail: "Fail",
      passed: "Passed",
      averageMark: "Average Marks",
      highest: "Highest",
      lowest: "Lowest",
      passRate: "Pass Rate (%)",
      topScorer: "Top Scorer",
      obtainedMarks: "Marks Obtained",
      fullMarks: "Full Marks",
      totalMarks: "Total Marks",
      serialShort: "SL",
      signature: "Signature",
      marks: "Marks",
      totalPresent: "Total Present",
      photo: "Photo",
    },
    status: {
      PASS: "Pass",
      FAIL: "Fail",
      PRESENT: "Present",
      ABSENT: "Absent",
      DRAFT: "Draft",
      PUBLISHED: "Published",
      INCOMPLETE: "Incomplete",
    },
    ordinals: ["1st", "2nd", "3rd"],
    absentShort: "Abs",
    allDivisions: "All {{division}}s",
    allClasses: "All {{class}}es",
    allExams: "All Exams",
    subjectN: (n) => `{{subject}} ${n}`,
    jamat: "Class",
    classTerm: "{{class}}",
    colon: ":",
    divisionLabel: "{{division}}:",
    classLabel: "{{class}}:",
    subjectLabel: "{{subject}}:",
    yearLabel: "Year:",
    monthLabel: "Month:",
    pageLabel: "Page:",
    yearSuffix: "",
    dateLabel: "Date:",
    phoneLabel: "Phone:",
    title: {
      resultSummary: "Result Summary",
      gradeScale: "Grade Scale",
      resultSheet: "Result Sheet",
      classRoutine: "Class Routine",
      dailyAttendance: "Daily Attendance Register",
      digitalAttendance: "Digital Attendance Report",
      residentialAttendance: "Residential Student Attendance Register",
      examNumberSheet: "Exam Mark Sheet",
      examSignatureSheet: "Exam Signature Sheet",
      signatureNumberSheet: "Signature & Mark Sheet",
      guardianPhoneList: "Guardian Mobile Number List",
      admissionList: "Admission List",
      teacherList: "{{teacher}} List",
      teacherPhoneList: "{{teacher}} Mobile Number List",
      marksheet: "Marksheet",
      admitCard: "Admit Card",
      studentIdCard: "Student ID Card",
      examRules: "Examination Rules",
      sanad: "Sanad (Certificate)",
      certificate: "Certificate",
      testimonial: "Testimonial",
      transferLetter: "Transfer Certificate",
      admissionForm: "Student Admission Form",
    },
    sign: {
      head: "Signature of {{head}}",
      headSeal: "Signature & Seal of {{head}}",
      examController: "Signature of Exam Controller",
      classTeacher: "Signature of {{class}} {{teacher}}",
    },
    headTitle: "{{head}}",
    institution: "{{institution}}",
  },
  ar: {
    col: {
      roll: "الرقم",
      rollNo: "رقم الجلوس",
      rollNoShort: "رقم الجلوس",
      regNo: "رقم القيد",
      regNoFull: "رقم التسجيل",
      regNoShort: "رقم القيد",
      regAbbr: "القيد",
      studentName: "اسم الطالب",
      examineeName: "اسم الممتحَن",
      name: "الاسم",
      father: "الأب",
      mother: "الأم",
      fatherName: "اسم الأب",
      motherName: "اسم الأم",
      class: "{{class}}",
      currentClass: "{{class}} الحالي",
      division: "{{division}}",
      session: "{{session}}",
      sessionShort: "السنة",
      exam: "الامتحان",
      total: "المجموع",
      average: "المعدل",
      grade: "التقدير",
      madrasaGrade: "تقدير المدرسة",
      resultDivision: "التقدير العام",
      status: "الحالة",
      state: "الحالة",
      rankWrap: "الترتيب",
      rank: "الترتيب",
      meritPosition: "الترتيب",
      mobile: "الجوال",
      mobileNo: "رقم الجوال",
      altMobileNo: "رقم جوال بديل",
      emergencyMobile: "جوال الطوارئ",
      district: "المحافظة",
      date: "التاريخ",
      dob: "تاريخ الميلاد",
      day: "اليوم",
      start: "البداية",
      end: "النهاية",
      startTime: "وقت البدء",
      endTime: "وقت الانتهاء",
      inTime: "وقت الحضور",
      outTime: "وقت الانصراف",
      subject: "{{subject}}",
      subjectName: "اسم {{subject}}",
      teacher: "{{teacher}}",
      teacherName: "اسم {{teacher}}",
      designation: "المسمى الوظيفي",
      department: "القسم",
      qualification: "المؤهل",
      email: "البريد الإلكتروني",
      joining: "الالتحاق",
      joiningDate: "تاريخ الالتحاق",
      roomNo: "رقم القاعة",
      room: "القاعة",
      seatNo: "رقم المقعد",
      invigilatorName: "اسم المراقب",
      duty: "المهمة",
      candidateNo: "رقم المرشح",
      eligibility: "الأهلية",
      examinees: "الممتحَنون",
      absent: "غائب",
      pass: "ناجح",
      fail: "راسب",
      passed: "الناجحون",
      averageMark: "متوسط الدرجات",
      highest: "الأعلى",
      lowest: "الأدنى",
      passRate: "نسبة النجاح (%)",
      topScorer: "الأول",
      obtainedMarks: "الدرجة المحصلة",
      fullMarks: "الدرجة الكاملة",
      totalMarks: "مجموع الدرجات",
      serialShort: "م",
      signature: "التوقيع",
      marks: "الدرجة",
      totalPresent: "مجموع الحضور",
      photo: "صورة",
    },
    status: {
      PASS: "ناجح",
      FAIL: "راسب",
      PRESENT: "حاضر",
      ABSENT: "غائب",
      DRAFT: "مسودة",
      PUBLISHED: "منشور",
      INCOMPLETE: "غير مكتمل",
    },
    ordinals: ["الأول", "الثاني", "الثالث"],
    absentShort: "غ",
    allDivisions: "جميع المراحل",
    allClasses: "جميع الصفوف",
    allExams: "جميع الامتحانات",
    subjectN: (n) => `{{subject}} ${n}`,
    jamat: "الصف",
    classTerm: "{{class}}",
    colon: ":",
    divisionLabel: "{{division}}:",
    classLabel: "{{class}}:",
    subjectLabel: "{{subject}}:",
    yearLabel: "السنة:",
    monthLabel: "الشهر:",
    pageLabel: "الصفحة:",
    yearSuffix: " م",
    dateLabel: "التاريخ:",
    phoneLabel: "الهاتف:",
    title: {
      resultSummary: "ملخص النتائج",
      gradeScale: "سلم التقديرات",
      resultSheet: "كشف النتائج",
      classRoutine: "جدول الحصص",
      dailyAttendance: "سجل الحضور اليومي",
      digitalAttendance: "تقرير الحضور الرقمي",
      residentialAttendance: "سجل حضور الطلاب المقيمين",
      examNumberSheet: "كشف درجات الامتحان",
      examSignatureSheet: "كشف توقيعات الامتحان",
      signatureNumberSheet: "كشف التوقيعات والدرجات",
      guardianPhoneList: "قائمة أرقام جوال أولياء الأمور",
      admissionList: "قائمة القبول",
      teacherList: "قائمة المعلمين",
      teacherPhoneList: "قائمة أرقام جوال المعلمين",
      marksheet: "كشف الدرجات",
      admitCard: "بطاقة الدخول",
      studentIdCard: "بطاقة هوية الطالب",
      examRules: "تعليمات الامتحان",
      sanad: "السند (الشهادة)",
      certificate: "شهادة",
      testimonial: "شهادة حسن سيرة",
      transferLetter: "شهادة نقل",
      admissionForm: "استمارة قبول طالب",
    },
    sign: {
      head: "توقيع {{head}}",
      headSeal: "توقيع وختم {{head}}",
      examController: "توقيع مراقب الامتحانات",
      classTeacher: "توقيع معلم الصف",
    },
    headTitle: "{{head}}",
    institution: "{{institution}}",
  },
});

export type ReportText = typeof reportText.bn;
