import { defineText } from "@madrasha/shared-ui/src/i18n";

/** On-screen report chrome (filter bar, sidebar, settings panels, states) -
 * read with useText, i.e. the user's own UI language. */
export const reportUiText = defineText({
  bn: {
    reportsHeading: "রিপোর্ট সমূহ",
    preparing: "রিপোর্ট প্রস্তুত হচ্ছে...",
    noData: "কোনো ডাটা পাওয়া যায়নি",
    loading: "লোড হচ্ছে...",

    // filter bar
    searchPlaceholder: "ID / নাম / মোবাইল",
    selectExam: "পরীক্ষা নির্বাচন করুন",
    selectDivision: "{{division}} নির্বাচন করুন",
    allDivisions: "সকল {{division}}",
    selectClass: "{{class}} নির্বাচন করুন",
    allClasses: "সকল {{class}}",
    pickDivisionFirst: "আগে {{division}} নির্বাচন",
    allSubjects: "সকল {{subject}}",
    pickClassFirst: "আগে {{class}} নির্বাচন করুন",
    defaultDesign: "ডিফল্ট (সাধারণ ডিজাইন)",
    readyDesigns: "রেডিমেড ডিজাইন",
    myTemplates: "আমার / সিস্টেম টেমপ্লেট",
    bothSides: "দুই পাশ (সামনে + পিছনে)",
    backOnly: "শুধু পিছনের পাশ",
    frontOnly: "শুধু সামনের পাশ",
    templates: "টেমপ্লেট",
    clear: "মুছুন",
    idCardSingle: "একক শিক্ষার্থী (পাতায় ১টি)",
    idCardGrid: "সকল শিক্ষার্থী (পাতায় অনেকগুলো)",
    labelsAll: "সকল লেবেল (কাটার-রেখাসহ)",
    onePerPage: "প্রতি পাতায় ১টি",

    // settings panels
    saveFailed: "সংরক্ষণ করা যায়নি। আবার চেষ্টা করুন।",
    moveUp: "উপরে সরান",
    moveDown: "নিচে সরান",
    signaturePosition: "স্বাক্ষরের অবস্থান",
    infoFieldsHint: "তথ্য ফিল্ড — কোনটা দেখাবেন আর কোন ক্রমে",
    signaturesHint: "নিচের স্বাক্ষর — কোনটা দেখাবেন আর কোন পাশে",
    resetDefault: "ডিফল্টে ফিরিয়ে আনুন",
    marksheetSettings: "মার্কশিট সেটিং",
    fieldSettings: "ফিল্ড সেটিং",
    admitCardFieldSettings: "প্রবেশপত্র ফিল্ড সেটিং",
    closeSettings: "সেটিং প্যানেল বন্ধ করুন",
    positions: { left: "বাম", center: "মাঝ", right: "ডান" },
    /** Marksheet info-field names for the settings rows. */
    marksheetFields: {
      roll: "রোল নম্বর",
      registration_no: "রেজিস্ট্রেশন নম্বর",
      date_of_birth: "জন্ম তারিখ",
      student_name: "শিক্ষার্থীর নাম",
      father_name: "পিতার নাম",
      madrasa_grade: "ফলাফল বিভাগ",
      general_grade: "গ্রেড",
      status: "ফলাফল",
      rank_no: "মেধাস্থান",
    } as Record<string, string>,
    /** Admit-card info-field names for the settings rows. */
    admitCardFields: {
      student_name: "পরীক্ষার্থীর নাম",
      father_name: "পিতার নাম",
      class_name: "{{class}}",
      roll: "রোল নম্বর",
      registration_no: "রেজিস্ট্রেশন নম্বর",
      academic_year: "{{session}}",
    } as Record<string, string>,

    // notice board
    noNotices: "কোনো নোটিশ নেই",
    manageNotices: "নতুন/এডিট/ডিলিট",
    noNoticeYet: "এখনো কোনো নোটিশ তৈরি করা হয়নি।",
    writeFirstNotice: "এখান থেকে প্রথম নোটিশটি লিখুন",
    sentenceEnd: "।",
  },
  en: {
    reportsHeading: "Reports",
    preparing: "Preparing report...",
    noData: "No data found",
    loading: "Loading...",
    searchPlaceholder: "ID / Name / Mobile",
    selectExam: "Select exam",
    selectDivision: "Select {{division}}",
    allDivisions: "All {{division}}s",
    selectClass: "Select {{class}}",
    allClasses: "All {{class}}es",
    pickDivisionFirst: "Select {{division}} first",
    allSubjects: "All {{subject}}s",
    pickClassFirst: "Select {{class}} first",
    defaultDesign: "Default (plain design)",
    readyDesigns: "Ready-made designs",
    myTemplates: "My / system templates",
    bothSides: "Both sides (front + back)",
    backOnly: "Back side only",
    frontOnly: "Front side only",
    templates: "Templates",
    clear: "Clear",
    idCardSingle: "Single student (1 per page)",
    idCardGrid: "All students (many per page)",
    labelsAll: "All labels (with cut lines)",
    onePerPage: "1 per page",
    saveFailed: "Could not save. Please try again.",
    moveUp: "Move up",
    moveDown: "Move down",
    signaturePosition: "Signature position",
    infoFieldsHint: "Info fields — which to show and in what order",
    signaturesHint: "Bottom signatures — which to show and on which side",
    resetDefault: "Restore defaults",
    marksheetSettings: "Marksheet settings",
    fieldSettings: "Field settings",
    admitCardFieldSettings: "Admit card field settings",
    closeSettings: "Close settings panel",
    positions: { left: "Left", center: "Center", right: "Right" },
    marksheetFields: {
      roll: "Roll No.",
      registration_no: "Registration No.",
      date_of_birth: "Date of Birth",
      student_name: "Student Name",
      father_name: "Father's Name",
      madrasa_grade: "Result Division",
      general_grade: "Grade",
      status: "Result",
      rank_no: "Merit Position",
    },
    admitCardFields: {
      student_name: "Examinee Name",
      father_name: "Father's Name",
      class_name: "{{class}}",
      roll: "Roll No.",
      registration_no: "Registration No.",
      academic_year: "{{session}}",
    },
    noNotices: "No notices",
    manageNotices: "New/Edit/Delete",
    noNoticeYet: "No notice has been created yet.",
    writeFirstNotice: "Write the first notice here",
    sentenceEnd: ".",
  },
  ar: {
    reportsHeading: "التقارير",
    preparing: "جارٍ إعداد التقرير...",
    noData: "لا توجد بيانات",
    loading: "جارٍ التحميل...",
    searchPlaceholder: "المعرّف / الاسم / الجوال",
    selectExam: "اختر الامتحان",
    selectDivision: "اختر {{division}}",
    allDivisions: "جميع المراحل",
    selectClass: "اختر {{class}}",
    allClasses: "جميع الصفوف",
    pickDivisionFirst: "اختر {{division}} أولاً",
    allSubjects: "جميع المواد",
    pickClassFirst: "اختر {{class}} أولاً",
    defaultDesign: "الافتراضي (تصميم بسيط)",
    readyDesigns: "تصاميم جاهزة",
    myTemplates: "قوالبي / قوالب النظام",
    bothSides: "الوجهان (الأمامي + الخلفي)",
    backOnly: "الوجه الخلفي فقط",
    frontOnly: "الوجه الأمامي فقط",
    templates: "القوالب",
    clear: "مسح",
    idCardSingle: "طالب واحد (واحدة في الصفحة)",
    idCardGrid: "جميع الطلاب (عدة في الصفحة)",
    labelsAll: "جميع الملصقات (مع خطوط القص)",
    onePerPage: "واحدة في كل صفحة",
    saveFailed: "تعذّر الحفظ. حاول مرة أخرى.",
    moveUp: "نقل لأعلى",
    moveDown: "نقل لأسفل",
    signaturePosition: "موضع التوقيع",
    infoFieldsHint: "حقول البيانات — ما يُعرض وبأي ترتيب",
    signaturesHint: "التوقيعات السفلية — ما يُعرض وفي أي جهة",
    resetDefault: "استعادة الافتراضي",
    marksheetSettings: "إعدادات كشف الدرجات",
    fieldSettings: "إعدادات الحقول",
    admitCardFieldSettings: "إعدادات حقول بطاقة الدخول",
    closeSettings: "إغلاق لوحة الإعدادات",
    positions: { left: "يسار", center: "وسط", right: "يمين" },
    marksheetFields: {
      roll: "رقم الجلوس",
      registration_no: "رقم التسجيل",
      date_of_birth: "تاريخ الميلاد",
      student_name: "اسم الطالب",
      father_name: "اسم الأب",
      madrasa_grade: "التقدير العام",
      general_grade: "التقدير",
      status: "النتيجة",
      rank_no: "الترتيب",
    },
    admitCardFields: {
      student_name: "اسم الممتحَن",
      father_name: "اسم الأب",
      class_name: "{{class}}",
      roll: "رقم الجلوس",
      registration_no: "رقم التسجيل",
      academic_year: "{{session}}",
    },
    noNotices: "لا توجد إعلانات",
    manageNotices: "جديد/تعديل/حذف",
    noNoticeYet: "لم يتم إنشاء أي إعلان بعد.",
    writeFirstNotice: "اكتب أول إعلان من هنا",
    sentenceEnd: ".",
  },
});
