-- Hand-written migration (matches the existing hand-written-migration
-- convention already used in this repo, e.g. 20260910180000_add_exam_operations
-- - NOT generated by `prisma migrate dev`). Purely additive: adds foreign
-- key constraints for fields that were deliberately left as plain scoped
-- integers while sibling modules were still being built concurrently (see
-- the removed comments in exam-operations.prisma/routine.prisma/
-- result.prisma), tightens two `DEFAULT 1` tenant-id columns, and adds one
-- partial unique index. No columns are dropped, no data is deleted, no
-- table is destructively altered.
--
-- IMPORTANT - run before applying, on the target database:
--   Adding a FOREIGN KEY constraint fails if any existing row's value
--   doesn't match a parent row, and the new partial unique index (see the
--   bottom of this file) fails if a duplicate PENDING result_corrections
--   group already exists. Run pre-migration-check.sql (same directory)
--   FIRST - it's a counts-only/id-only safety check covering every
--   constraint this migration adds, with a remediation note under each
--   check. Every count must be 0 before applying this file. Do not
--   silently delete any flagged row - see that file's remediation notes.

-- ---- exam_rooms.madrasa_id -> madrasas.id ----
ALTER TABLE "exam_rooms" ADD CONSTRAINT "exam_rooms_madrasa_id_fkey"
  FOREIGN KEY ("madrasa_id") REFERENCES "madrasas"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- ---- exam_invigilator_assignments.madrasa_id -> madrasas.id ----
ALTER TABLE "exam_invigilator_assignments" ADD CONSTRAINT "exam_invigilator_assignments_madrasa_id_fkey"
  FOREIGN KEY ("madrasa_id") REFERENCES "madrasas"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- ---- exam_seat_allocations.madrasa_id -> madrasas.id, .exam_candidate_id -> exam_candidates.id ----
ALTER TABLE "exam_seat_allocations" ADD CONSTRAINT "exam_seat_allocations_madrasa_id_fkey"
  FOREIGN KEY ("madrasa_id") REFERENCES "madrasas"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "exam_seat_allocations" ADD CONSTRAINT "exam_seat_allocations_exam_candidate_id_fkey"
  FOREIGN KEY ("exam_candidate_id") REFERENCES "exam_candidates"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- ---- exam_attendances.madrasa_id -> madrasas.id, .exam_candidate_id -> exam_candidates.id ----
ALTER TABLE "exam_attendances" ADD CONSTRAINT "exam_attendances_madrasa_id_fkey"
  FOREIGN KEY ("madrasa_id") REFERENCES "madrasas"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "exam_attendances" ADD CONSTRAINT "exam_attendances_exam_candidate_id_fkey"
  FOREIGN KEY ("exam_candidate_id") REFERENCES "exam_candidates"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- ---- exam_routines.division_id -> divisions.id (nullable, SetNull) ----
ALTER TABLE "exam_routines" ADD CONSTRAINT "exam_routines_division_id_fkey"
  FOREIGN KEY ("division_id") REFERENCES "divisions"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- ---- mark_component_configs.exam_id -> exams.id (nullable, Cascade) ----
ALTER TABLE "mark_component_configs" ADD CONSTRAINT "mark_component_configs_exam_id_fkey"
  FOREIGN KEY ("exam_id") REFERENCES "exams"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- ---- Remove silent-fallback DEFAULT 1 on tenant-id columns ----
-- Every create call site already supplies madrasa_id explicitly (verified
-- in result-panel.service.ts / exam.service.ts), so this only removes a
-- footgun where an omitted madrasa_id would previously have silently
-- attached the row to tenant 1 instead of failing loudly.
ALTER TABLE "exams" ALTER COLUMN "madrasa_id" DROP DEFAULT;
ALTER TABLE "marks" ALTER COLUMN "madrasa_id" DROP DEFAULT;

-- ---- Block duplicate/competing PENDING corrections for the same target ----
-- Prisma has no native way to express a partial unique index, so this is
-- declared here directly (same pattern as results_master's uniq_session
-- index, see 20260805100000_add_trash_columns_division_class_book_result).
-- Only one PENDING row may exist per (result_master_id, student_id,
-- book_id, field) at a time; APPROVED/REJECTED/APPLIED history is
-- unrestricted.
CREATE UNIQUE INDEX "uniq_pending_result_correction" ON "result_corrections"
  ("result_master_id", "student_id", "book_id", "field")
  WHERE "status" = 'PENDING';
