import { defineBilingualText } from "@madrasha/shared-ui/src/i18n";

export const dashboardText = defineBilingualText({
  bn: {
    title: "ড্যাশবোর্ড",
    subtitle: "প্ল্যাটফর্মের সার্বিক অবস্থা",
    totalInstitutions: "মোট প্রতিষ্ঠান",
    active: "সক্রিয়",
    inactive: "নিষ্ক্রিয়",
    inTrash: "ট্র্যাশে",
    totalStudents: "মোট ছাত্র",
    growthTitle: "প্রতিষ্ঠান প্রবৃদ্ধি",
    growthSubtitle: "গত ১২ মাসে নতুন প্রতিষ্ঠান",
    newInstitutions: "নতুন প্রতিষ্ঠান",
    revenueTitle: "রাজস্ব প্রবণতা",
    revenueSubtitle: "গত ১২ মাসের সাবস্ক্রিপশন আয়",
    revenue: "রাজস্ব",
    expiringTitle: "মেয়াদ শেষের পথে (আগামী ৭ দিন)",
    noExpiring: "আগামী ৭ দিনে কোনো প্ল্যানের মেয়াদ শেষ হচ্ছে না ✅",
    plan: "প্ল্যান",
    ends: "শেষ",
    ended: "শেষ হয়েছে",
    daysLeft: (n: string) => `${n} দিন বাকি`,
    expiredTitle: "মেয়াদোত্তীর্ণ প্ল্যান",
    noExpired: "কোনো মেয়াদোত্তীর্ণ প্ল্যান নেই 🎉",
    daysOverdue: (n: string) => `${n} দিন অতিবাহিত`,
    recentActivity: "সাম্প্রতিক কার্যক্রম",
    noActivity: "কোনো কার্যক্রম পাওয়া যায়নি।",
    colTime: "সময়",
    colInstitution: "প্রতিষ্ঠান",
    colUser: "ইউজার",
    colAction: "কার্যক্রম",
    colEntity: "এনটিটি",
    colDetails: "বিস্তারিত",
  },
  en: {
    title: "Dashboard",
    subtitle: "Platform overview",
    totalInstitutions: "Total Institutions",
    active: "Active",
    inactive: "Inactive",
    inTrash: "In Trash",
    totalStudents: "Total Students",
    growthTitle: "Institution Growth",
    growthSubtitle: "New institutions in the last 12 months",
    newInstitutions: "New institutions",
    revenueTitle: "Revenue Trend",
    revenueSubtitle: "Subscription income over the last 12 months",
    revenue: "Revenue",
    expiringTitle: "Expiring Soon (next 7 days)",
    noExpiring: "No plan expires in the next 7 days ✅",
    plan: "Plan",
    ends: "Ends",
    ended: "Ended",
    daysLeft: (n) => `${n} days left`,
    expiredTitle: "Expired Plans",
    noExpired: "No expired plans 🎉",
    daysOverdue: (n) => `${n} days overdue`,
    recentActivity: "Recent Activity",
    noActivity: "No activity found.",
    colTime: "Time",
    colInstitution: "Institution",
    colUser: "User",
    colAction: "Action",
    colEntity: "Entity",
    colDetails: "Details",
  },
});
