import { defineText } from "@madrasha/shared-ui/src/i18n";

/** Printed admission form labels (print language). */
export const admissionFormText = defineText({
  bn: {
    male: "ছেলে",
    female: "মেয়ে",
    residential: "আবাসিক",
    nonResidential: "অনাবাসিক",
    readmission: "পুনঃভর্তি (পুরাতন)",
    newAdmission: "নতুন",
    studentInfo: "{{student}}র তথ্য",
    name: "নাম",
    arabicName: "আরবি নাম",
    nid: "NID/জন্ম নিবন্ধন",
    gender: "লিঙ্গ",
    dob: "জন্ম তারিখ",
    bloodGroup: "রক্তের গ্রুপ",
    residency: "আবাসিক/অনাবাসিক",
    orphan: "এতিম",
    yes: "হ্যাঁ",
    no: "না",
    admissionType: "ভর্তির ধরন",
    admissionInfo: "ভর্তির তথ্য",
    class: "{{class}}",
    session: "{{session}}",
    rollNo: "রোল নম্বর",
    regNo: "রেজিস্ট্রেশন নম্বর",
    admissionDate: "ভর্তির তারিখ",
    previousInstitution: "পূর্ববর্তী প্রতিষ্ঠান",
    previousResult: "পূর্বের ফলাফল",
    guardianInfo: "অভিভাবকের তথ্য",
    fatherName: "পিতার নাম",
    fatherNid: "পিতার NID",
    fatherOccupation: "পিতার পেশা",
    motherName: "মাতার নাম",
    motherNid: "মাতার NID",
    motherOccupation: "মাতার পেশা",
    mobileNo: "মোবাইল নম্বর",
    altMobileNo: "বিকল্প মোবাইল নম্বর",
    altGuardian: "বিকল্প অভিভাবক",
    relation: "সম্পর্ক",
    address: "ঠিকানা",
    adminDivision: "বিভাগ",
    district: "জেলা",
    thana: "থানা/উপজেলা",
    village: "গ্রাম",
    statusLabel: "অবস্থা:",
    approved: "অনুমোদিত",
    rejected: "বাতিলকৃত",
    pending: "পর্যালোচনাধীন",
    signatureNotApplicable: "অনুমোদনের পূর্বে স্বাক্ষর প্রযোজ্য নয়",
  },
  en: {
    male: "Male",
    female: "Female",
    residential: "Residential",
    nonResidential: "Non-residential",
    readmission: "Re-admission (existing)",
    newAdmission: "New",
    studentInfo: "{{student}} Information",
    name: "Name",
    arabicName: "Arabic Name",
    nid: "NID/Birth Registration",
    gender: "Gender",
    dob: "Date of Birth",
    bloodGroup: "Blood Group",
    residency: "Residential/Non-residential",
    orphan: "Orphan",
    yes: "Yes",
    no: "No",
    admissionType: "Admission Type",
    admissionInfo: "Admission Information",
    class: "{{class}}",
    session: "{{session}}",
    rollNo: "Roll No.",
    regNo: "Registration No.",
    admissionDate: "Admission Date",
    previousInstitution: "Previous Institution",
    previousResult: "Previous Result",
    guardianInfo: "Guardian Information",
    fatherName: "Father's Name",
    fatherNid: "Father's NID",
    fatherOccupation: "Father's Occupation",
    motherName: "Mother's Name",
    motherNid: "Mother's NID",
    motherOccupation: "Mother's Occupation",
    mobileNo: "Mobile No.",
    altMobileNo: "Alternate Mobile No.",
    altGuardian: "Alternate Guardian",
    relation: "Relation",
    address: "Address",
    adminDivision: "Division",
    district: "District",
    thana: "Thana/Upazila",
    village: "Village",
    statusLabel: "Status:",
    approved: "Approved",
    rejected: "Rejected",
    pending: "Under review",
    signatureNotApplicable: "Signature not applicable before approval",
  },
  ar: {
    male: "ذكر",
    female: "أنثى",
    residential: "مقيم",
    nonResidential: "غير مقيم",
    readmission: "إعادة قبول (قديم)",
    newAdmission: "جديد",
    studentInfo: "بيانات {{student}}",
    name: "الاسم",
    arabicName: "الاسم بالعربية",
    nid: "الهوية الوطنية/شهادة الميلاد",
    gender: "الجنس",
    dob: "تاريخ الميلاد",
    bloodGroup: "فصيلة الدم",
    residency: "مقيم/غير مقيم",
    orphan: "يتيم",
    yes: "نعم",
    no: "لا",
    admissionType: "نوع القبول",
    admissionInfo: "بيانات القبول",
    class: "{{class}}",
    session: "{{session}}",
    rollNo: "رقم الجلوس",
    regNo: "رقم التسجيل",
    admissionDate: "تاريخ القبول",
    previousInstitution: "المؤسسة السابقة",
    previousResult: "النتيجة السابقة",
    guardianInfo: "بيانات ولي الأمر",
    fatherName: "اسم الأب",
    fatherNid: "هوية الأب",
    fatherOccupation: "مهنة الأب",
    motherName: "اسم الأم",
    motherNid: "هوية الأم",
    motherOccupation: "مهنة الأم",
    mobileNo: "رقم الجوال",
    altMobileNo: "رقم جوال بديل",
    altGuardian: "ولي أمر بديل",
    relation: "صلة القرابة",
    address: "العنوان",
    adminDivision: "المنطقة",
    district: "المحافظة",
    thana: "المركز/المديرية",
    village: "القرية",
    statusLabel: "الحالة:",
    approved: "معتمد",
    rejected: "مرفوض",
    pending: "قيد المراجعة",
    signatureNotApplicable: "لا ينطبق التوقيع قبل الاعتماد",
  },
});
