import { defineText } from "@madrasha/shared-ui/src/i18n";

/** UI text for the ExamPanel components (exam list, grade scales, fail mark). */
export const examPanelText = defineText({
  bn: {
    // failMarkFeedback
    updatedDefault: "আপডেট হয়েছে!",
    failMarkSaved: (msg: string) => `${msg} — ফলাফলে প্রয়োগ করতে "ফলাফল পুনঃগণনা" চাপুন`,
    // examDivisionScope / DivisionScopePicker
    allDivisions: "সকল {{division}}",
    whichDivisions: "কোন {{division}}ের পরীক্ষা?",
    selectDivision: "{{division}} নির্বাচন",
    scopeHint: "শুধু নির্বাচিত {{division}}ের {{class}}গুলোর রুটিন, নম্বর ও ফলাফল এই পরীক্ষায় হবে।",
    // DivisionStatusChip / scope
    ownGrading: (n: string) => `নিজস্ব গ্রেডিং · ফেল মার্ক ${n}`,
    usingDefault: "ডিফল্ট ব্যবহার করছে",
    gradingScope: "গ্রেডিং স্কোপ",
    defaultShort: "ডিফল্ট",
    defaultAll: "ডিফল্ট (সব {{division}}ের জন্য)",
    failMarkN: (n: string) => `ফেল মার্ক ${n}`,
    divisions: "{{division}}সমূহ",
    noDivision: "কোনো {{division}} নেই",
    // GradeBandPreview
    fail: "ফেল",
    ungraded: "গ্রেডহীন",
    scalePreview: "গ্রেড স্কেল প্রিভিউ",
    pointN: (n: string) => `পয়েন্ট ${n}`,
    gapWarning: "কিছু নম্বর কোনো গ্রেডের আওতায় পড়ছে না (হ্যাচ করা অংশ) — গ্রেডগুলো ঠিক করুন।",
    // ScopeSummaryCard
    failMarkRange: "০ থেকে ১০০ এর মধ্যে পূর্ণসংখ্যা ফেল মার্ক দিন",
    updateFailed: "আপডেট করা যায়নি",
    resetTitle: "ডিফল্টে ফিরে যাবেন?",
    resetMessage: (name: string, mark: string) =>
      `"${name}" {{division}}ের আলাদা ফেল মার্ক ও এই {{division}}ের নিজস্ব সব গ্রেড মুছে যাবে। {{division}}টি সাধারণ ফেল মার্ক (${mark}) ও ডিফল্ট গ্রেড ব্যবহার করবে।`,
    resetConfirm: "ডিফল্টে ফিরুন",
    resetDone: "ডিফল্টে ফিরে গেছে",
    resetFailed: "ডিফল্টে ফেরানো যায়নি",
    selectedScope: "নির্বাচিত স্কোপ",
    generalGrading: "সাধারণ গ্রেডিং",
    failMark: "ফেল মার্ক",
    ownEnabled: "নিজস্ব গ্রেডিং চালু হয়েছে",
    marks: "নম্বর",
    changeFailMark: "ফেল মার্ক পরিবর্তন করুন",
    failRange: (from: string, to: string) => `${from}–${to} ফেল · `,
    passFrom: (n: string) => `পাস শুরু ${n} থেকে`,
    defaultExplain:
      "যে {{division}}ের নিজস্ব গ্রেডিং চালু নেই, সেগুলো এই ফেল মার্ক ও নিচের ডিফল্ট গ্রেড ব্যবহার করে। ফেল মার্ক বদলালে সর্বনিম্ন গ্রেডের সীমা স্বয়ংক্রিয়ভাবে মিলে যায়।",
    usesDefault: (n: string) => `এই {{division}} ডিফল্ট গ্রেডিং ব্যবহার করছে (ফেল মার্ক ${n})`,
    enableOwn: "এই {{division}}ের জন্য নিজস্ব গ্রেডিং চালু করুন",
    enableExplain: (n: string) =>
      `ওপরের ঘরে এই {{division}}ের ফেল মার্ক দিন (ডিফল্ট: ${n})। চালু করলে ডিফল্ট গ্রেডগুলোর একটি কপি এই {{division}}ের জন্য তৈরি হবে এবং সর্বনিম্ন গ্রেড নতুন ফেল মার্কের সাথে মিলিয়ে নেওয়া হবে। এরপর গ্রেডগুলো আলাদাভাবে সম্পাদনা করা যাবে।`,
    enabling: "চালু হচ্ছে...",
    enable: "চালু করুন",
    ownExplain: "এই {{division}}ের নিজস্ব গ্রেড ও ফেল মার্ক ব্যবহার হচ্ছে। ডিফল্টে ফিরলে নিজস্ব সব গ্রেড মুছে যাবে।",
    // GradeList
    generalGrade: "সাধারণ গ্রেড",
    generalGradePlaceholder: "গ্রেড (যেমনঃ A+)",
    madrasaGrade: "মাদরাসা গ্রেড",
    madrasaGradePlaceholder: "গ্রেড (যেমনঃ মুমতায)",
    scaleFixed: "গ্রেডের সীমা ঠিক করা হয়েছে",
    scaleFixFailed: "গ্রেডের সীমা ঠিক করা যায়নি",
    fillAll: "সব ঘর পূরণ করুন",
    failNotGrade: (label: string) =>
      `"${label}" আলাদা গ্রেড নয় — নম্বর ফেল মার্কের কম হলে শিক্ষার্থী স্বয়ংক্রিয়ভাবে ${label} (ফেল) হয়`,
    gradeAddFailed: "গ্রেড যোগ করা যায়নি",
    deleteGradeTitle: "গ্রেড মুছবেন?",
    deleteGradeMessage: (name: string) => `"${name}" গ্রেডটি মুছে ফেলতে চান?`,
    gradeNameRequired: "গ্রেডের নাম দিন",
    failNameReserved: (label: string) =>
      `"${label}" আলাদা গ্রেডের নাম হিসেবে ব্যবহার করা যাবে না — এটি ফেলের স্বয়ংক্রিয় গ্রেড`,
    gradeUpdated: "গ্রেড আপডেট হয়েছে",
    gradeUpdateFailed: "গ্রেড আপডেট করা যায়নি",
    countN: (n: string) => `${n}টি`,
    readOnly: "শুধু দেখার জন্য",
    maxPlaceholder: "সর্বোচ্চ",
    point: "পয়েন্ট",
    addGrade: "গ্রেড যোগ করুন",
    maxOnlyHint: "শুধু সর্বোচ্চ নম্বর দিন — সর্বনিম্ন নম্বর স্বয়ংক্রিয়ভাবে আগের গ্রেড থেকে হিসাব হয়ে যাবে। পয়েন্ট ঐচ্ছিক।",
    failAuto: "(ফেল · স্বয়ংক্রিয়)",
    failAutoHint: (mark: string, label: string) =>
      `নম্বর ${mark}-এর কম পেলে শিক্ষার্থী স্বয়ংক্রিয়ভাবে ${label} (ফেল) হবে — ${label}-কে আলাদা গ্রেড হিসেবে যোগ করার দরকার নেই।`,
    mismatch: (mark: string) =>
      `গ্রেডের সীমায় ফাঁক বা অমিল আছে — সর্বনিম্ন গ্রেড ${mark} থেকে শুরু হওয়ার কথা, কিন্তু সংরক্ষিত সীমা মেলেনি।`,
    fixing: "ঠিক করা হচ্ছে...",
    autoFix: "স্বয়ংক্রিয়ভাবে ঠিক করুন",
    noGrades: "কোনো গ্রেড যোগ করা হয়নি",
    noDefaultGrades: "ডিফল্টে কোনো গ্রেড নেই",
    addGradeHint: "উপরে থেকে নতুন গ্রেড যোগ করুন",
    grade: "গ্রেড",
    editAction: "সম্পাদনা করুন",
    deleteAction: "মুছে ফেলুন",
    cancelAction: "বাতিল করুন",
    // ExamList
    examNameRequired: "পরীক্ষার নাম দিন",
    examAddFailed: "পরীক্ষা যোগ করা যায়নি",
    examActivatedFee: (name: string) => `"${name}" চালু হয়েছে — এর ফি {{admin}} (ফি সেটাপ) থেকে চালু করতে হবে`,
    examToggleFailed: "পরীক্ষার অবস্থা পরিবর্তন করা যায়নি",
    examOffTitle: "পরীক্ষা বন্ধ করবেন?",
    examOffMessage: (name: string) =>
      `"${name}" পরীক্ষাটি বন্ধ হলে এর ফি-ও স্বয়ংক্রিয়ভাবে বন্ধ হবে এবং অপরিশোধিত ইনভয়েসগুলো বাতিল হবে। পরে পরীক্ষা চালু করলে ফি আবার {{admin}} থেকে চালু করতে হবে।`,
    turnOff: "বন্ধ করুন",
    examDeleteTitle: "পরীক্ষা মুছবেন?",
    examDeleteMessage: (name: string) =>
      `"${name}" পরীক্ষাটি ট্র্যাশে সরাতে চান? পরে প্রয়োজনে ট্র্যাশ থেকে ফিরিয়ে আনা যাবে।`,
    moveToTrash: "ট্র্যাশে সরান",
    movedToTrash: "ট্র্যাশে সরানো হয়েছে",
    examUpdated: "পরীক্ষা আপডেট হয়েছে",
    examUpdateFailed: "পরীক্ষা আপডেট করা যায়নি",
    reorderFailed: "ক্রম পরিবর্তন করা যায়নি",
    allShort: "সব",
    exams: "পরীক্ষাসমূহ",
    examNamePlaceholder: "পরীক্ষার নাম (যেমনঃ প্রথম সাময়িক পরীক্ষা)",
    adding: "যোগ হচ্ছে...",
    hideDetails: "বিস্তারিত লুকান",
    addDetails: "বিস্তারিত যোগ করুন (ধরন, তারিখ, বিবরণ)",
    examTypePlaceholder: "পরীক্ষার ধরন (যেমনঃ বার্ষিক)",
    startDate: "শুরুর তারিখ",
    endDate: "শেষের তারিখ",
    descriptionOptional: "বিবরণ (ঐচ্ছিক)",
    noExams: "কোনো পরীক্ষা যোগ করা হয়নি",
    addExamHint: "উপরে থেকে নতুন পরীক্ষা যোগ করুন",
    viewByDivision: "{{division}} অনুযায়ী দেখুন:",
    dragHint: "টেনে (drag) ক্রম পরিবর্তন করা যাবে",
    noDivisionExams: "এই {{division}}ের কোনো পরীক্ষা নেই",
    noDivisionExamsHint: "উপরে {{division}} নির্বাচন করে নতুন পরীক্ষা যোগ করুন",
    examName: "পরীক্ষার নাম",
    dragToMove: "টেনে সরান",
    deactivate: "নিষ্ক্রিয় করুন",
    activate: "সক্রিয় করুন",
  },
  en: {
    updatedDefault: "Updated!",
    failMarkSaved: (msg) => `${msg} — press "Recalculate results" to apply it to results`,
    allDivisions: "All {{division}}s",
    whichDivisions: "Exam for which {{division}}?",
    selectDivision: "Select {{division}}",
    scopeHint: "Only classes of the selected {{division}}s will have routine, marks and results in this exam.",
    ownGrading: (n) => `Own grading · fail mark ${n}`,
    usingDefault: "Using default",
    gradingScope: "Grading scope",
    defaultShort: "Default",
    defaultAll: "Default (for all {{division}}s)",
    failMarkN: (n) => `Fail mark ${n}`,
    divisions: "{{division}}s",
    noDivision: "No {{division}}",
    fail: "Fail",
    ungraded: "Ungraded",
    scalePreview: "Grade scale preview",
    pointN: (n) => `Point ${n}`,
    gapWarning: "Some marks fall under no grade (hatched area) — please fix the grades.",
    failMarkRange: "Enter a whole-number fail mark between 0 and 100",
    updateFailed: "Could not update",
    resetTitle: "Return to default?",
    resetMessage: (name, mark) =>
      `The separate fail mark and all own grades of the {{division}} "${name}" will be removed. It will use the general fail mark (${mark}) and default grades.`,
    resetConfirm: "Return to default",
    resetDone: "Returned to default",
    resetFailed: "Could not return to default",
    selectedScope: "Selected scope",
    generalGrading: "General grading",
    failMark: "Fail mark",
    ownEnabled: "Own grading enabled",
    marks: "marks",
    changeFailMark: "Change fail mark",
    failRange: (from, to) => `${from}–${to} fail · `,
    passFrom: (n) => `Pass starts at ${n}`,
    defaultExplain:
      "{{division}}s without their own grading use this fail mark and the default grades below. Changing the fail mark automatically adjusts the lowest grade's range.",
    usesDefault: (n) => `This {{division}} uses the default grading (fail mark ${n})`,
    enableOwn: "Enable own grading for this {{division}}",
    enableExplain: (n) =>
      `Enter this {{division}}'s fail mark in the box above (default: ${n}). Enabling creates a copy of the default grades for this {{division}} and aligns the lowest grade with the new fail mark. The grades can then be edited separately.`,
    enabling: "Enabling...",
    enable: "Enable",
    ownExplain: "This {{division}} uses its own grades and fail mark. Returning to default removes all its own grades.",
    generalGrade: "General Grade",
    generalGradePlaceholder: "Grade (e.g. A+)",
    madrasaGrade: "Madrasa Grade",
    madrasaGradePlaceholder: "Grade (e.g. Mumtaz)",
    scaleFixed: "Grade ranges fixed",
    scaleFixFailed: "Could not fix grade ranges",
    fillAll: "Fill in all fields",
    failNotGrade: (label) =>
      `"${label}" is not a separate grade — a student below the fail mark automatically gets ${label} (fail)`,
    gradeAddFailed: "Could not add grade",
    deleteGradeTitle: "Delete grade?",
    deleteGradeMessage: (name) => `Delete the grade "${name}"?`,
    gradeNameRequired: "Enter a grade name",
    failNameReserved: (label) => `"${label}" cannot be used as a grade name — it is the automatic fail grade`,
    gradeUpdated: "Grade updated",
    gradeUpdateFailed: "Could not update grade",
    countN: (n) => `${n}`,
    readOnly: "View only",
    maxPlaceholder: "Max",
    point: "Point",
    addGrade: "Add grade",
    maxOnlyHint: "Enter only the maximum mark — the minimum is calculated from the previous grade. Point is optional.",
    failAuto: "(fail · automatic)",
    failAutoHint: (mark, label) =>
      `A student scoring below ${mark} automatically gets ${label} (fail) — there is no need to add ${label} as a grade.`,
    mismatch: (mark) =>
      `The grade ranges have a gap or mismatch — the lowest grade should start at ${mark}, but the saved ranges do not match.`,
    fixing: "Fixing...",
    autoFix: "Fix automatically",
    noGrades: "No grades added",
    noDefaultGrades: "The default has no grades",
    addGradeHint: "Add a new grade above",
    grade: "Grade",
    editAction: "Edit",
    deleteAction: "Delete",
    cancelAction: "Cancel",
    examNameRequired: "Enter the exam name",
    examAddFailed: "Could not add exam",
    examActivatedFee: (name) => `"${name}" enabled — its fee must be enabled from {{admin}} (Fee Setup)`,
    examToggleFailed: "Could not change exam status",
    examOffTitle: "Turn off exam?",
    examOffMessage: (name) =>
      `Turning off "${name}" also turns off its fee automatically and cancels unpaid invoices. If you turn the exam on later, the fee must be enabled again from {{admin}}.`,
    turnOff: "Turn off",
    examDeleteTitle: "Delete exam?",
    examDeleteMessage: (name) => `Move the exam "${name}" to trash? It can be restored from trash later.`,
    moveToTrash: "Move to trash",
    movedToTrash: "Moved to trash",
    examUpdated: "Exam updated",
    examUpdateFailed: "Could not update exam",
    reorderFailed: "Could not change order",
    allShort: "All",
    exams: "Exams",
    examNamePlaceholder: "Exam name (e.g. First Term Exam)",
    adding: "Adding...",
    hideDetails: "Hide details",
    addDetails: "Add details (type, date, description)",
    examTypePlaceholder: "Exam type (e.g. Annual)",
    startDate: "Start date",
    endDate: "End date",
    descriptionOptional: "Description (optional)",
    noExams: "No exams added",
    addExamHint: "Add a new exam above",
    viewByDivision: "View by {{division}}:",
    dragHint: "Drag to change the order",
    noDivisionExams: "No exams for this {{division}}",
    noDivisionExamsHint: "Select a {{division}} above and add a new exam",
    examName: "Exam name",
    dragToMove: "Drag to move",
    deactivate: "Deactivate",
    activate: "Activate",
  },
  ar: {
    updatedDefault: "تم التحديث!",
    failMarkSaved: (msg) => `${msg} — اضغط "إعادة حساب النتائج" لتطبيقه على النتائج`,
    allDivisions: "جميع المراحل",
    whichDivisions: "الامتحان لأي {{division}}؟",
    selectDivision: "اختيار {{division}}",
    scopeHint: "سيُعقد الجدول والدرجات والنتائج في هذا الامتحان لصفوف المراحل المختارة فقط.",
    ownGrading: (n) => `تقدير خاص · درجة الرسوب ${n}`,
    usingDefault: "يستخدم الافتراضي",
    gradingScope: "نطاق التقدير",
    defaultShort: "الافتراضي",
    defaultAll: "الافتراضي (لجميع المراحل)",
    failMarkN: (n) => `درجة الرسوب ${n}`,
    divisions: "المراحل",
    noDivision: "لا توجد مراحل",
    fail: "راسب",
    ungraded: "بلا تقدير",
    scalePreview: "معاينة سلّم التقديرات",
    pointN: (n) => `النقاط ${n}`,
    gapWarning: "بعض الدرجات لا يشملها أي تقدير (الجزء المظلل) — يرجى تصحيح التقديرات.",
    failMarkRange: "أدخل درجة رسوب صحيحة بين 0 و100",
    updateFailed: "تعذّر التحديث",
    resetTitle: "العودة إلى الافتراضي؟",
    resetMessage: (name, mark) =>
      `ستُحذف درجة الرسوب الخاصة وجميع التقديرات الخاصة بـ{{division}} "${name}"، وستستخدم درجة الرسوب العامة (${mark}) والتقديرات الافتراضية.`,
    resetConfirm: "العودة إلى الافتراضي",
    resetDone: "تمت العودة إلى الافتراضي",
    resetFailed: "تعذّرت العودة إلى الافتراضي",
    selectedScope: "النطاق المختار",
    generalGrading: "التقدير العام",
    failMark: "درجة الرسوب",
    ownEnabled: "تم تفعيل التقدير الخاص",
    marks: "درجة",
    changeFailMark: "تغيير درجة الرسوب",
    failRange: (from, to) => `${from}–${to} رسوب · `,
    passFrom: (n) => `يبدأ النجاح من ${n}`,
    defaultExplain:
      "المراحل التي ليس لها تقدير خاص تستخدم درجة الرسوب هذه والتقديرات الافتراضية أدناه. عند تغيير درجة الرسوب يُعدَّل حد أدنى تقدير تلقائيًا.",
    usesDefault: (n) => `تستخدم هذه {{division}} التقدير الافتراضي (درجة الرسوب ${n})`,
    enableOwn: "تفعيل تقدير خاص لهذه {{division}}",
    enableExplain: (n) =>
      `أدخل درجة رسوب هذه {{division}} في الخانة أعلاه (الافتراضي: ${n}). عند التفعيل تُنشأ نسخة من التقديرات الافتراضية لهذه {{division}} ويُضبط أدنى تقدير وفق درجة الرسوب الجديدة، ثم يمكن تعديل التقديرات بشكل مستقل.`,
    enabling: "جارٍ التفعيل...",
    enable: "تفعيل",
    ownExplain: "تستخدم هذه {{division}} تقديراتها ودرجة رسوبها الخاصة. العودة إلى الافتراضي تحذف جميع تقديراتها الخاصة.",
    generalGrade: "التقدير العام",
    generalGradePlaceholder: "التقدير (مثل A+)",
    madrasaGrade: "تقدير المدرسة الدينية",
    madrasaGradePlaceholder: "التقدير (مثل ممتاز)",
    scaleFixed: "تم تصحيح حدود التقديرات",
    scaleFixFailed: "تعذّر تصحيح حدود التقديرات",
    fillAll: "املأ جميع الحقول",
    failNotGrade: (label) => `"${label}" ليس تقديرًا مستقلًا — من يحصل على أقل من درجة الرسوب يُمنح ${label} (راسب) تلقائيًا`,
    gradeAddFailed: "تعذّرت إضافة التقدير",
    deleteGradeTitle: "حذف التقدير؟",
    deleteGradeMessage: (name) => `هل تريد حذف التقدير "${name}"؟`,
    gradeNameRequired: "أدخل اسم التقدير",
    failNameReserved: (label) => `لا يمكن استخدام "${label}" اسمًا لتقدير — فهو تقدير الرسوب التلقائي`,
    gradeUpdated: "تم تحديث التقدير",
    gradeUpdateFailed: "تعذّر تحديث التقدير",
    countN: (n) => `${n}`,
    readOnly: "للعرض فقط",
    maxPlaceholder: "الأعلى",
    point: "النقاط",
    addGrade: "إضافة تقدير",
    maxOnlyHint: "أدخل الدرجة العليا فقط — تُحسب الدنيا تلقائيًا من التقدير السابق. النقاط اختيارية.",
    failAuto: "(رسوب · تلقائي)",
    failAutoHint: (mark, label) =>
      `من يحصل على أقل من ${mark} يُمنح ${label} (راسب) تلقائيًا — لا حاجة لإضافة ${label} تقديرًا مستقلًا.`,
    mismatch: (mark) => `في حدود التقديرات فجوة أو عدم تطابق — يجب أن يبدأ أدنى تقدير من ${mark}، لكن الحدود المحفوظة لا تطابق ذلك.`,
    fixing: "جارٍ التصحيح...",
    autoFix: "تصحيح تلقائي",
    noGrades: "لم تُضف أي تقديرات",
    noDefaultGrades: "لا توجد تقديرات في الافتراضي",
    addGradeHint: "أضف تقديرًا جديدًا من الأعلى",
    grade: "التقدير",
    editAction: "تعديل",
    deleteAction: "حذف",
    cancelAction: "إلغاء",
    examNameRequired: "أدخل اسم الامتحان",
    examAddFailed: "تعذّرت إضافة الامتحان",
    examActivatedFee: (name) => `تم تفعيل "${name}" — يجب تفعيل رسومه من {{admin}} (إعداد الرسوم)`,
    examToggleFailed: "تعذّر تغيير حالة الامتحان",
    examOffTitle: "إيقاف الامتحان؟",
    examOffMessage: (name) =>
      `عند إيقاف "${name}" تتوقف رسومه تلقائيًا وتُلغى الفواتير غير المدفوعة. وإذا أعيد تفعيل الامتحان لاحقًا فيجب تفعيل الرسوم من {{admin}} مجددًا.`,
    turnOff: "إيقاف",
    examDeleteTitle: "حذف الامتحان؟",
    examDeleteMessage: (name) => `نقل الامتحان "${name}" إلى سلة المحذوفات؟ يمكن استعادته لاحقًا.`,
    moveToTrash: "نقل إلى السلة",
    movedToTrash: "تم النقل إلى السلة",
    examUpdated: "تم تحديث الامتحان",
    examUpdateFailed: "تعذّر تحديث الامتحان",
    reorderFailed: "تعذّر تغيير الترتيب",
    allShort: "الكل",
    exams: "الامتحانات",
    examNamePlaceholder: "اسم الامتحان (مثل الامتحان الفصلي الأول)",
    adding: "جارٍ الإضافة...",
    hideDetails: "إخفاء التفاصيل",
    addDetails: "إضافة تفاصيل (النوع، التاريخ، الوصف)",
    examTypePlaceholder: "نوع الامتحان (مثل السنوي)",
    startDate: "تاريخ البدء",
    endDate: "تاريخ الانتهاء",
    descriptionOptional: "الوصف (اختياري)",
    noExams: "لم تُضف أي امتحانات",
    addExamHint: "أضف امتحانًا جديدًا من الأعلى",
    viewByDivision: "العرض حسب {{division}}:",
    dragHint: "يمكن تغيير الترتيب بالسحب",
    noDivisionExams: "لا توجد امتحانات لهذه {{division}}",
    noDivisionExamsHint: "اختر {{division}} من الأعلى وأضف امتحانًا جديدًا",
    examName: "اسم الامتحان",
    dragToMove: "اسحب للنقل",
    deactivate: "إلغاء التفعيل",
    activate: "تفعيل",
  },
});
