import { defineText } from "@madrasha/shared-ui/src/i18n";

export const photoText = defineText({
  bn: {
    cameraTitle: "ক্যামেরা দিয়ে ছবি তুলুন",
    noCameraSupport: "এই ব্রাউজারে ক্যামেরা সাপোর্ট নেই (HTTPS বা localhost প্রয়োজন)।",
    cameraDenied: "ক্যামেরা ব্যবহারের অনুমতি দেওয়া হয়নি। ব্রাউজারের ঠিকানা-বারের পাশ থেকে অনুমতি দিন।",
    noCamera: "কোনো ক্যামেরা পাওয়া যায়নি।",
    cameraFailed: "ক্যামেরা চালু করা যায়নি।",
    faceGuide: "মুখ ডিম্বাকার গাইডের ভেতরে রেখে ছবি তুলুন",
    retake: "আবার তুলুন",
    use: "ব্যবহার করুন",
    switchCamera: "ক্যামেরা বদলান",
    capture: "ছবি তুলুন",
    photo: "ছবি",
    hint: "JPG/PNG · পাসপোর্ট সাইজ (৩:৪)",
    readFailed: "ছবিটি পড়া যায়নি — সঠিক ইমেজ ফাইল দিন",
    uploading: "আপলোড হচ্ছে...",
    upload: "আপলোড",
    camera: "ক্যামেরা",
    removePhoto: "ছবি মুছুন",
  },
  en: {
    cameraTitle: "Take a photo with the camera",
    noCameraSupport: "This browser doesn't support the camera (HTTPS or localhost required).",
    cameraDenied: "Camera permission was denied. Allow it from beside the browser's address bar.",
    noCamera: "No camera found.",
    cameraFailed: "Could not start the camera.",
    faceGuide: "Keep the face inside the oval guide and take the photo",
    retake: "Retake",
    use: "Use Photo",
    switchCamera: "Switch camera",
    capture: "Take Photo",
    photo: "Photo",
    hint: "JPG/PNG · Passport size (3:4)",
    readFailed: "Could not read the image — please choose a valid image file",
    uploading: "Uploading...",
    upload: "Upload",
    camera: "Camera",
    removePhoto: "Remove photo",
  },
  ar: {
    cameraTitle: "التقاط صورة بالكاميرا",
    noCameraSupport: "هذا المتصفح لا يدعم الكاميرا (يتطلب HTTPS أو localhost).",
    cameraDenied: "لم يتم منح إذن استخدام الكاميرا. اسمح به من بجانب شريط العنوان في المتصفح.",
    noCamera: "لم يتم العثور على كاميرا.",
    cameraFailed: "تعذّر تشغيل الكاميرا.",
    faceGuide: "ضع الوجه داخل الإطار البيضاوي ثم التقط الصورة",
    retake: "إعادة الالتقاط",
    use: "استخدام",
    switchCamera: "تبديل الكاميرا",
    capture: "التقاط صورة",
    photo: "الصورة",
    hint: "JPG/PNG · مقاس جواز السفر (3:4)",
    readFailed: "تعذّرت قراءة الصورة — اختر ملف صورة صالحًا",
    uploading: "جارٍ الرفع...",
    upload: "رفع",
    camera: "الكاميرا",
    removePhoto: "حذف الصورة",
  },
});
