import { defineText } from "@madrasha/shared-ui/src/i18n";

/** UI text for the marks-entry / result / correction / recalculation screens. */
export const resultPanelText = defineText({
  bn: {
    absentShort: "অনু",
    status: {
      result: {
        DRAFT: "খসড়া",
        MARKS_SUBMITTED: "নম্বর জমা হয়েছে",
        MARKS_VERIFIED: "নম্বর যাচাই হয়েছে",
        PROCESSING: "প্রসেসিং",
        RESULT_VERIFIED: "যাচাইকৃত ফলাফল",
        APPROVED: "অনুমোদিত",
        PUBLISHED: "প্রকাশিত",
        LOCKED: "লকড",
      },
      submission: {
        DRAFT: "খসড়া",
        SUBMITTED: "জমা দেয়া হয়েছে",
        VERIFIED: "যাচাই হয়েছে",
        REJECTED: "বাতিল হয়েছে",
      },
      correction: {
        PENDING: "অপেক্ষমান",
        APPROVED: "অনুমোদিত",
        REJECTED: "বাতিল",
        APPLIED: "প্রয়োগ হয়েছে",
      },
      all: "সব",
      unknown: "অজানা",
    },
    resultStatus: { PASS: "পাস", FAIL: "ফেল", ABSENT: "অনুপস্থিত" } as Record<string, string>,
    actions: {
      saveAndProcess: "💾 সংরক্ষণ ও প্রসেস করুন",
      reset: "♻ রিসেট",
    },
    filter: {
      division: "{{division}}",
      exam: "পরীক্ষা",
      class: "{{class}}",
    },
    marks: {
      title: "📊 নম্বর এন্ট্রি",
      autosaving: "⏳ সংরক্ষণ হচ্ছে...",
      autosaved: "✓ সংরক্ষিত",
      autosaveFailed: "⚠ সংরক্ষণ ব্যর্থ",
      hintType: "⌨️ নাম্বার লিখে",
      hintPress: "চাপুন",
      hintMove: "একই {{subject}}ের নিচের {{student}}র ঘরে যেতে — তীর চিহ্ন (↑ ↓ ← →) কী দিয়েও ঘরে ঘরে যাওয়া যাবে।",
      hintAbsentPre: "কেউ পরীক্ষা না দিলে",
      hintAbsentPost: "চাপুন।",
      roll: "রোল",
      regNo: "রেজি. নং",
      studentName: "{{student}}র নাম",
      bookFallback: (id: string) => `{{subject}} ${id}`,
      miyari: "মিয়ারি",
      passMarkTitle: "এই {{subject}}ের জন্য আলাদা পাস মার্ক সেট করা আছে",
      pass: (n: string) => `পাস ${n}`,
      submittedBy: (by: string, at: string) => `জমা: ${by} ${at}`,
      submit: "জমা দিন",
      verify: "যাচাই",
      openForEdit: "সম্পাদনার জন্য খুলুন",
      reject: "বাতিল",
      subjectsHere: "{{subject}}সমূহ এখানে দেখাবে",
      noStudents: "এই {{class}}তে কোনো {{student}} পাওয়া যায়নি",
      noBooks: "এই {{class}}র জন্য কোনো {{subject}} যুক্ত করা হয়নি",
      lockedTitle: "এই {{subject}}টি জমা দেয়া হয়েছে — সম্পাদনা বন্ধ",
      addNote: "নোট যোগ করুন",
      notePlaceholder: "নোট লিখুন...",
      save: "সংরক্ষণ",
      legendFail: "ফেল",
      legendPass: "পাশ",
      legendAbsent: "অনুপস্থিত (-)",
    },
    full: {
      title: "📊 সম্পূর্ণ ফলাফল তালিকা",
      status: "অবস্থা:",
      deleteTitle: "ফলাফল মুছুন",
      deleteMessage: "আপনি কি নিশ্চিত?",
      editAllPublishedTitle: "প্রকাশিত ফলাফল — পুরো {{class}}র নাম্বার একসাথে সংশোধন করুন",
      editAllTitle: "পুরো {{class}}র নাম্বার একসাথে এডিট করুন",
      correctAll: "✏️ সব নম্বর সংশোধন",
      editMarks: "✏️ নম্বর এডিট",
      recalcTitle: "বর্তমান ফেল মার্ক ও গ্রেড সীমা অনুযায়ী এই ফলাফল নতুন করে হিসাব করুন",
      recalc: "🔄 পুনঃগণনা",
      rollByRankTitle: "ফলাফলের মেধাক্রম অনুযায়ী প্রত্যেক {{student}}র রোল নম্বর নতুন করে বসাবে",
      rollUpdating: "রোল আপডেট হচ্ছে...",
      rollByRank: "🏆 মেধাক্রম অনুযায়ী রোল",
      undoRollTitle: "মেধাক্রম অনুযায়ী বসানো রোলের ঠিক আগের রোল নম্বরগুলো ফিরিয়ে আনবে",
      undoRoll: "↩️ আগের রোলে ফিরে যান",
      verifyTitle: "নম্বর প্রসেস সম্পন্ন — এখন ফলাফল যাচাই করুন",
      verifying: "যাচাই হচ্ছে...",
      verify: "✅ ফলাফল যাচাই করুন",
      approveTitle: "যাচাইকৃত ফলাফল অনুমোদন করুন",
      approving: "অনুমোদন হচ্ছে...",
      approve: "👍 অনুমোদন করুন",
      rejectTitle: "ফলাফল প্রত্যাখ্যান করে আবার প্রসেসিং-এ ফেরত পাঠান",
      reject: "প্রত্যাখ্যান",
      publishing: "প্রকাশ হচ্ছে...",
      publish: "প্রকাশ করুন",
      regNo: "রেজিঃ নম্বর",
      studentName: "{{student}}র নাম",
      bookFallback: (id: string) => `{{subject}} ${id}`,
      miyari: "(মিয়ারি)",
      pass: (n: string) => `(পাস ${n})`,
      total: "মোট",
      average: "গড়",
      generalGrade: "সাধারণ গ্রেড",
      madrasaGrade: "মাদরাসা গ্রেড",
      resultState: "অবস্থা",
      rank: "মেধাক্রম",
      actions: "কার্যক্রম",
      noResult: "কোনো ফলাফল পাওয়া যায়নি",
      view: "দেখুন",
      correctPublishedTitle: "প্রকাশিত ফলাফল — সংশোধনের অনুরোধ পাঠান",
      editOneTitle: "শুধুমাত্র এর নাম্বার এডিট করুন",
      correct: "✏️ সংশোধন",
      edit: "✏️ এডিট",
    },
    components: {
      options: {
        WRITTEN: "লিখিত",
        MCQ: "এমসিকিউ",
        PRACTICAL: "ব্যবহারিক",
        ORAL: "মৌখিক",
        ASSIGNMENT: "অ্যাসাইনমেন্ট",
        CLASS_ASSESSMENT: "ক্লাস মূল্যায়ন",
        OTHER: "অন্যান্য",
      },
      needOne: "অন্তত একটি উপাদান যোগ করুন",
      invalidFullMark: "প্রতিটি উপাদানের পূর্ণমান সঠিক সংখ্যা হতে হবে",
      saved: "উপাদান সংরক্ষণ হয়েছে",
      saveFailed: "সংরক্ষণ করা যায়নি — পূর্ণমানের যোগফল মিলছে না",
      title: (book: string) => `নম্বর বিভাজন — ${book}`,
      examLabel: "পরীক্ষা (ঐচ্ছিক — খালি রাখলে সাধারণ/সব পরীক্ষার জন্য প্রযোজ্য হবে)",
      generalExam: "সাধারণ (সব পরীক্ষা)",
      none: "কোনো উপাদান যোগ করা হয়নি",
      fullMark: "পূর্ণমান",
      add: "উপাদান যোগ করুন",
    },
    overview: {
      notEntered: "⚪ এন্ট্রি হয়নি",
      published: "✅ প্রকাশিত",
      complete: "🟢 এন্ট্রি সম্পন্ন",
      partial: (done: string, total: string) => `🟡 আংশিক (${done}/${total})`,
      empty: "কোনো পরীক্ষা বা {{division}} পাওয়া যায়নি। প্রথমে পরীক্ষা ও {{division}} যোগ করুন।",
    },
    password: {
      label: "আপনার পাসওয়ার্ড দিন",
      hide: "পাসওয়ার্ড লুকান",
      show: "পাসওয়ার্ড দেখান",
      required: "পাসওয়ার্ড আবশ্যক",
      verifying: "যাচাই হচ্ছে...",
    },
    reason: {
      label: "কারণ লিখুন",
      placeholder: "কারণ লিখুন...",
      required: "কারণ লেখা আবশ্যক",
    },
    banner: {
      needUpdate: "ফলাফল হালনাগাদ করা দরকার:",
      willChange: (sessions: string, students: string, published: string | null) =>
        ` বর্তমান ফেল মার্ক ও গ্রেড সেটিং অনুযায়ী ${sessions}টি ফলাফলে ${students} জন {{student}}র ফলাফল বদলাবে${
          published ? ` (${published}টি প্রকাশিত)` : ""
        }। কী বদলাবে আগেই দেখাবে, আপনি নিশ্চিত করলে তবেই প্রয়োগ হবে।`,
      checking: "ফলাফল যাচাই করা হচ্ছে...",
      checkFailed: "ফলাফল হালনাগাদ আছে কি না যাচাই করা যায়নি। চাইলে পুনঃগণনা খুলে নিজে দেখে নিতে পারেন।",
      allUpToDate: "সব ফলাফল হালনাগাদ আছে।",
      allUpToDateHint: " গ্রেড সীমা বা ফেল মার্ক বদলালে এবং কোনো ফলাফলে পরিবর্তন প্রয়োজন হলে এখানে পুনঃগণনার বাটন চালু হবে।",
      noNeed: "এখন কোনো ফলাফল পুনঃগণনার প্রয়োজন নেই",
      button: "ফলাফল পুনঃগণনা",
    },
    recalc: {
      loadFailed: "পুনঃগণনার তথ্য আনা যায়নি",
      partialFail: (updated: string, failed: string) =>
        `${updated}টি ফলাফল হালনাগাদ হয়েছে, ${failed}টি ব্যর্থ হয়েছে`,
      done: (updated: string, students: string) =>
        `${updated}টি ফলাফল পুনঃগণনা হয়েছে (${students} জন {{student}}র ফলাফল বদলেছে)`,
      failed: "পুনঃগণনা করা যায়নি",
      titleOne: "🔄 ফলাফল পুনঃগণনা",
      titleAll: "🔄 সব ফলাফল পুনঃগণনা",
      intro:
        "বর্তমান ফেল মার্ক, গ্রেড সীমা ও {{subject}}ের সেটিং অনুযায়ী ফলাফল নতুন করে হিসাব করা হবে। নম্বর নিজে বদলাবে না — শুধু মোট, গড়, গ্রেড, পাস/ফেল ও মেধাক্রম হালনাগাদ হবে।",
      checking: "যাচাই করা হচ্ছে...",
      fetchFailed: "তথ্য আনা যায়নি।",
      retry: "আবার চেষ্টা করুন",
      nothingOne: "✅ এই ফলাফল বর্তমান সেটিং অনুযায়ী ইতিমধ্যে হালনাগাদ আছে — কিছু বদলানোর নেই।",
      nothingAll: "✅ সব ফলাফল বর্তমান সেটিং অনুযায়ী ইতিমধ্যে হালনাগাদ আছে — কিছু বদলানোর নেই।",
      examClass: "পরীক্ষা / {{class}}",
      state: "অবস্থা",
      willChange: "বদলাবে",
      people: (changed: string, total: string) => `${changed} / ${total} জন`,
      includePublished: "প্রকাশিত/লকড ফলাফলেও প্রয়োগ করুন",
      includePublishedHint: (n: string) =>
        ` (${n}টি)। এগুলো অভিভাবকরা আগেই দেখেছেন — শুধু নতুন নিয়ম আগের পরীক্ষাতেও কার্যকর করতে চাইলে টিক দিন। প্রয়োগ করলে প্রকাশিত অবস্থা থাকবে এবং আগের/পরের রেকর্ড অডিটের জন্য সংরক্ষিত থাকবে।`,
      unpublishedNote:
        'অপ্রকাশিত ফলাফল সরাসরি হালনাগাদ হবে। যাচাই/অনুমোদিত হয়ে থাকলে আবার "প্রসেসিং" অবস্থায় ফিরবে — প্রকাশের সময় আপনার অধিকারে যাচাই ও অনুমোদন একসাথেই হয়ে যাবে।',
      singlePublishedNote: "এটি প্রকাশিত ফলাফল — আপনি নিজে এটি বেছে নিয়েছেন বলে প্রয়োগ হবে; প্রকাশিত অবস্থা বজায় থাকবে।",
      skipped: (n: string) => `⚠️ ${n}টি ফলাফলে সব নম্বর পূর্ণ নেই বলে বাদ দেওয়া হয়েছে: `,
      totalsFailed: (n: string) => `${n}টি ফলাফল যাচাই করা যায়নি।`,
      applying: "হচ্ছে...",
      apply: (results: string, students: string) => `প্রয়োগ করুন (${results}টি ফলাফল, ${students} জন)`,
    },
    corrections: {
      fields: {
        mark: "নম্বর",
        is_absent: "অনুপস্থিতি",
        is_exempted: "অব্যাহতি",
        is_withheld: "স্থগিত",
        note: "মন্তব্য",
        general_grade: "সাধারণ গ্রেড",
        madrasa_grade: "মাদরাসা গ্রেড",
        total: "মোট",
        average: "গড়",
        status: "অবস্থা",
        rank_no: "মেধাক্রম",
      } as Record<string, string>,
      absent: "অনুপস্থিত",
      present: "উপস্থিত",
      yes: "হ্যাঁ",
      no: "না",
      studentFallback: (id: string) => `{{student}} #${id}`,
      bookFallback: (id: string) => `{{subject}} #${id}`,
      applied: "সংশোধন প্রয়োগ করা হয়েছে",
      rejected: "সংশোধনের অনুরোধ প্রত্যাখ্যান করা হয়েছে",
      decideFailed: "সিদ্ধান্ত নেওয়া যায়নি",
      approveTitle: "সংশোধন অনুমোদন করুন",
      approveMessage: (student: string, book: string, field: string, from: string, to: string) =>
        `${student} — ${book}: ${field} "${from}" থেকে "${to}" করা হবে। মোট, গড়, গ্রেড ও মেধাক্রম নতুন করে হিসাব হবে।`,
      approveConfirm: "অনুমোদন ও প্রয়োগ",
      title: "📝 ফলাফল সংশোধনের অনুরোধ",
      subtitle: 'প্রকাশিত ফলাফলে সরাসরি নম্বর বদলানো যায় না — "✏️ সংশোধন" চেপে অনুরোধ পাঠান, অনুমোদনের পর তা প্রয়োগ হবে।',
      showAll: (n: string) => `সব দেখান (${n})`,
      noneYet: "এখনো কোনো সংশোধনের অনুরোধ নেই",
      nonePending: "কোনো অপেক্ষমান অনুরোধ নেই",
      student: "{{student}}",
      subject: "{{subject}}",
      field: "ক্ষেত্র",
      beforeAfter: "আগে → নতুন",
      reason: "কারণ",
      state: "অবস্থা",
      actions: "কার্যক্রম",
      decision: (note: string) => `সিদ্ধান্ত: ${note}`,
      approve: "অনুমোদন",
      reject: "প্রত্যাখ্যান",
      rejectTitle: "সংশোধনের অনুরোধ প্রত্যাখ্যান",
      rejectMessage: "প্রত্যাখ্যান করলে ফলাফলে কোনো পরিবর্তন হবে না।",
      rejectLabel: "প্রত্যাখ্যানের কারণ",
      rejectConfirm: "প্রত্যাখ্যান করুন",
    },
    stats: {
      totalStudents: "মোট {{student}}",
      pass: "পাশ",
      fail: "ফেল",
      absent: "অনুপস্থিত",
      gradeScale: "গ্রেড স্কেল — কোন গ্রেড কত নম্বরে",
      general: "সাধারণ",
      madrasa: "মাদরাসা",
    },
    studentEdit: {
      correctTitle: "📝 ফলাফল সংশোধন",
      requestTitle: "📝 ফলাফল সংশোধনের অনুরোধ",
      editTitle: "✏️ শুধুমাত্র এর নাম্বার এডিট",
      directNote:
        "এই ফলাফল প্রকাশিত। আপনার অধিকারে সংশোধন এখনই ফলাফলে প্রয়োগ হবে এবং মোট, গড়, গ্রেড ও মেধাক্রম নতুন করে হিসাব হবে। কারণসহ সবকিছু অডিট লগে সংরক্ষিত থাকবে।",
      requestNote:
        "এই ফলাফল প্রকাশিত হয়ে গেছে। এখানে বদলানো নম্বর সরাসরি সেভ হবে না — সংশোধনের অনুরোধ হিসেবে জমা হবে এবং অনুমোদনের পর ফলাফলে প্রয়োগ হবে।",
      subject: "{{subject}}",
      mark: "নাম্বার",
      bookFallback: (id: string) => `{{subject}} ${id}`,
      passMarkTitle: "এই {{subject}}ের জন্য আলাদা পাস মার্ক সেট করা আছে",
      pass: (n: string) => `(পাস ${n})`,
      fail: "ফেল",
      passLegend: "পাস",
      absentLegend: 'অনুপস্থিত ("-" চাপুন)',
      reasonLabel: "সংশোধনের কারণ (আবশ্যক)",
      reasonPlaceholder: "যেমন: নম্বর তোলার সময় ভুল হয়েছিল...",
      reasonRequired: "কারণ লেখা আবশ্যক",
      applying: "প্রয়োগ হচ্ছে...",
      submitting: "জমা হচ্ছে...",
      saving: "সেভ হচ্ছে...",
      applyCorrection: "সংশোধন প্রয়োগ করুন",
      sendRequest: "অনুরোধ পাঠান",
      save: "সেভ করুন",
    },
  },
  en: {
    absentShort: "Ab",
    status: {
      result: {
        DRAFT: "Draft",
        MARKS_SUBMITTED: "Marks submitted",
        MARKS_VERIFIED: "Marks verified",
        PROCESSING: "Processing",
        RESULT_VERIFIED: "Result verified",
        APPROVED: "Approved",
        PUBLISHED: "Published",
        LOCKED: "Locked",
      },
      submission: {
        DRAFT: "Draft",
        SUBMITTED: "Submitted",
        VERIFIED: "Verified",
        REJECTED: "Rejected",
      },
      correction: {
        PENDING: "Pending",
        APPROVED: "Approved",
        REJECTED: "Rejected",
        APPLIED: "Applied",
      },
      all: "All",
      unknown: "Unknown",
    },
    resultStatus: { PASS: "Pass", FAIL: "Fail", ABSENT: "Absent" },
    actions: {
      saveAndProcess: "💾 Save & Process",
      reset: "♻ Reset",
    },
    filter: {
      division: "{{division}}",
      exam: "Exam",
      class: "{{class}}",
    },
    marks: {
      title: "📊 Marks Entry",
      autosaving: "⏳ Saving...",
      autosaved: "✓ Saved",
      autosaveFailed: "⚠ Save failed",
      hintType: "⌨️ Type a mark and press",
      hintPress: "",
      hintMove: "to move down to the next {{student}} in the same {{subject}} — arrow keys (↑ ↓ ← →) also move between cells.",
      hintAbsentPre: "If someone missed the exam, press",
      hintAbsentPost: ".",
      roll: "Roll",
      regNo: "Reg. No.",
      studentName: "{{student}} Name",
      bookFallback: (id) => `{{subject}} ${id}`,
      miyari: "Miyari",
      passMarkTitle: "A separate pass mark is set for this {{subject}}",
      pass: (n) => `Pass ${n}`,
      submittedBy: (by, at) => `Submitted: ${by} ${at}`,
      submit: "Submit",
      verify: "Verify",
      openForEdit: "Reopen for editing",
      reject: "Reject",
      subjectsHere: "{{subject}}s will appear here",
      noStudents: "No {{student}}s found in this {{class}}",
      noBooks: "No {{subject}}s have been added for this {{class}}",
      lockedTitle: "This {{subject}} has been submitted — editing is locked",
      addNote: "Add note",
      notePlaceholder: "Write a note...",
      save: "Save",
      legendFail: "Fail",
      legendPass: "Pass",
      legendAbsent: "Absent (-)",
    },
    full: {
      title: "📊 Full Result Table",
      status: "Status:",
      deleteTitle: "Delete Result",
      deleteMessage: "Are you sure?",
      editAllPublishedTitle: "Published result — correct the whole {{class}}'s marks at once",
      editAllTitle: "Edit the whole {{class}}'s marks at once",
      correctAll: "✏️ Correct All Marks",
      editMarks: "✏️ Edit Marks",
      recalcTitle: "Recalculate this result using the current fail mark and grade ranges",
      recalc: "🔄 Recalculate",
      rollByRankTitle: "Reassigns every {{student}}'s roll number by merit rank",
      rollUpdating: "Updating rolls...",
      rollByRank: "🏆 Roll by Merit",
      undoRollTitle: "Restores the roll numbers from just before the merit-based rolls",
      undoRoll: "↩️ Restore Previous Rolls",
      verifyTitle: "Marks processed — now verify the result",
      verifying: "Verifying...",
      verify: "✅ Verify Result",
      approveTitle: "Approve the verified result",
      approving: "Approving...",
      approve: "👍 Approve",
      rejectTitle: "Reject the result and send it back to processing",
      reject: "Reject",
      publishing: "Publishing...",
      publish: "Publish",
      regNo: "Reg. No.",
      studentName: "{{student}} Name",
      bookFallback: (id) => `{{subject}} ${id}`,
      miyari: "(Miyari)",
      pass: (n) => `(Pass ${n})`,
      total: "Total",
      average: "Average",
      generalGrade: "General Grade",
      madrasaGrade: "Madrasa Grade",
      resultState: "Status",
      rank: "Merit Rank",
      actions: "Actions",
      noResult: "No result found",
      view: "View",
      correctPublishedTitle: "Published result — send a correction request",
      editOneTitle: "Edit only this student's marks",
      correct: "✏️ Correct",
      edit: "✏️ Edit",
    },
    components: {
      options: {
        WRITTEN: "Written",
        MCQ: "MCQ",
        PRACTICAL: "Practical",
        ORAL: "Oral",
        ASSIGNMENT: "Assignment",
        CLASS_ASSESSMENT: "Class Assessment",
        OTHER: "Other",
      },
      needOne: "Add at least one component",
      invalidFullMark: "Each component's full mark must be a valid number",
      saved: "Components saved",
      saveFailed: "Could not save — full marks do not add up",
      title: (book) => `Mark Breakdown — ${book}`,
      examLabel: "Exam (optional — leave empty to apply to all exams)",
      generalExam: "General (all exams)",
      none: "No components added",
      fullMark: "Full mark",
      add: "Add component",
    },
    overview: {
      notEntered: "⚪ Not entered",
      published: "✅ Published",
      complete: "🟢 Entry complete",
      partial: (done, total) => `🟡 Partial (${done}/${total})`,
      empty: "No exam or {{division}} found. Add an exam and a {{division}} first.",
    },
    password: {
      label: "Enter your password",
      hide: "Hide password",
      show: "Show password",
      required: "Password is required",
      verifying: "Verifying...",
    },
    reason: {
      label: "Enter a reason",
      placeholder: "Enter a reason...",
      required: "A reason is required",
    },
    banner: {
      needUpdate: "Results need updating:",
      willChange: (sessions, students, published) =>
        ` under the current fail mark and grade settings, ${students} {{student}}(s) in ${sessions} result(s) will change${
          published ? ` (${published} published)` : ""
        }. You will see what changes first; nothing is applied until you confirm.`,
      checking: "Checking results...",
      checkFailed: "Could not check whether results are up to date. You can open recalculation to review manually.",
      allUpToDate: "All results are up to date.",
      allUpToDateHint: " If grade ranges or the fail mark change and a result needs updating, the recalculate button will be enabled here.",
      noNeed: "No results need recalculating right now",
      button: "Recalculate Results",
    },
    recalc: {
      loadFailed: "Could not load recalculation data",
      partialFail: (updated, failed) => `${updated} result(s) updated, ${failed} failed`,
      done: (updated, students) => `${updated} result(s) recalculated (${students} {{student}}(s) changed)`,
      failed: "Could not recalculate",
      titleOne: "🔄 Recalculate Result",
      titleAll: "🔄 Recalculate All Results",
      intro:
        "Results will be recalculated using the current fail mark, grade ranges and {{subject}} settings. Marks themselves will not change — only total, average, grade, pass/fail and merit rank are updated.",
      checking: "Checking...",
      fetchFailed: "Could not load data.",
      retry: "Try again",
      nothingOne: "✅ This result is already up to date with the current settings — nothing to change.",
      nothingAll: "✅ All results are already up to date with the current settings — nothing to change.",
      examClass: "Exam / {{class}}",
      state: "Status",
      willChange: "Will change",
      people: (changed, total) => `${changed} / ${total}`,
      includePublished: "Also apply to published/locked results",
      includePublishedHint: (n) =>
        ` (${n}). Guardians have already seen these — tick only if you want the new rules applied to past exams too. They stay published, and before/after records are kept for audit.`,
      unpublishedNote:
        'Unpublished results are updated directly. Verified/approved ones return to "Processing" — with your authority, verification and approval happen together at publish time.',
      singlePublishedNote: "This is a published result — it will be applied because you chose it; it stays published.",
      skipped: (n) => `⚠️ ${n} result(s) skipped because marks are incomplete: `,
      totalsFailed: (n) => `${n} result(s) could not be checked.`,
      applying: "Applying...",
      apply: (results, students) => `Apply (${results} result(s), ${students} student(s))`,
    },
    corrections: {
      fields: {
        mark: "Mark",
        is_absent: "Absence",
        is_exempted: "Exemption",
        is_withheld: "Withheld",
        note: "Remark",
        general_grade: "General grade",
        madrasa_grade: "Madrasa grade",
        total: "Total",
        average: "Average",
        status: "Status",
        rank_no: "Merit rank",
      },
      absent: "Absent",
      present: "Present",
      yes: "Yes",
      no: "No",
      studentFallback: (id) => `{{student}} #${id}`,
      bookFallback: (id) => `{{subject}} #${id}`,
      applied: "Correction applied",
      rejected: "Correction request rejected",
      decideFailed: "Could not record the decision",
      approveTitle: "Approve Correction",
      approveMessage: (student, book, field, from, to) =>
        `${student} — ${book}: ${field} will change from "${from}" to "${to}". Total, average, grade and merit rank will be recalculated.`,
      approveConfirm: "Approve & Apply",
      title: "📝 Result Correction Requests",
      subtitle: 'Marks on a published result can\'t be changed directly — press "✏️ Correct" to send a request; it is applied once approved.',
      showAll: (n) => `Show all (${n})`,
      noneYet: "No correction requests yet",
      nonePending: "No pending requests",
      student: "{{student}}",
      subject: "{{subject}}",
      field: "Field",
      beforeAfter: "Before → New",
      reason: "Reason",
      state: "Status",
      actions: "Actions",
      decision: (note) => `Decision: ${note}`,
      approve: "Approve",
      reject: "Reject",
      rejectTitle: "Reject Correction Request",
      rejectMessage: "Rejecting makes no change to the result.",
      rejectLabel: "Reason for rejection",
      rejectConfirm: "Reject",
    },
    stats: {
      totalStudents: "Total {{student}}s",
      pass: "Pass",
      fail: "Fail",
      absent: "Absent",
      gradeScale: "Grade scale — marks for each grade",
      general: "General",
      madrasa: "Madrasa",
    },
    studentEdit: {
      correctTitle: "📝 Correct Result",
      requestTitle: "📝 Result Correction Request",
      editTitle: "✏️ Edit This Student's Marks",
      directNote:
        "This result is published. With your authority the correction applies immediately, and total, average, grade and merit rank are recalculated. Everything, including the reason, is kept in the audit log.",
      requestNote:
        "This result is already published. Marks changed here are not saved directly — they are submitted as a correction request and applied after approval.",
      subject: "{{subject}}",
      mark: "Mark",
      bookFallback: (id) => `{{subject}} ${id}`,
      passMarkTitle: "A separate pass mark is set for this {{subject}}",
      pass: (n) => `(Pass ${n})`,
      fail: "Fail",
      passLegend: "Pass",
      absentLegend: 'Absent (press "-")',
      reasonLabel: "Reason for correction (required)",
      reasonPlaceholder: "e.g. A mistake was made while entering marks...",
      reasonRequired: "A reason is required",
      applying: "Applying...",
      submitting: "Submitting...",
      saving: "Saving...",
      applyCorrection: "Apply Correction",
      sendRequest: "Send Request",
      save: "Save",
    },
  },
  ar: {
    absentShort: "غ",
    status: {
      result: {
        DRAFT: "مسودة",
        MARKS_SUBMITTED: "تم تسليم الدرجات",
        MARKS_VERIFIED: "تم التحقق من الدرجات",
        PROCESSING: "قيد المعالجة",
        RESULT_VERIFIED: "نتيجة متحقَّق منها",
        APPROVED: "معتمدة",
        PUBLISHED: "منشورة",
        LOCKED: "مقفلة",
      },
      submission: {
        DRAFT: "مسودة",
        SUBMITTED: "تم التسليم",
        VERIFIED: "تم التحقق",
        REJECTED: "مرفوضة",
      },
      correction: {
        PENDING: "قيد الانتظار",
        APPROVED: "معتمد",
        REJECTED: "مرفوض",
        APPLIED: "تم التطبيق",
      },
      all: "الكل",
      unknown: "غير معروف",
    },
    resultStatus: { PASS: "ناجح", FAIL: "راسب", ABSENT: "غائب" },
    actions: {
      saveAndProcess: "💾 حفظ ومعالجة",
      reset: "♻ إعادة تعيين",
    },
    filter: {
      division: "{{division}}",
      exam: "الاختبار",
      class: "{{class}}",
    },
    marks: {
      title: "📊 إدخال الدرجات",
      autosaving: "⏳ جارٍ الحفظ...",
      autosaved: "✓ تم الحفظ",
      autosaveFailed: "⚠ فشل الحفظ",
      hintType: "⌨️ اكتب الدرجة واضغط",
      hintPress: "",
      hintMove: "للانتقال إلى {{student}} التالي في نفس {{subject}} — ويمكن التنقل بين الخانات بمفاتيح الأسهم (↑ ↓ ← →) أيضًا.",
      hintAbsentPre: "إذا لم يحضر أحد الاختبار فاضغط",
      hintAbsentPost: ".",
      roll: "رقم الجلوس",
      regNo: "رقم التسجيل",
      studentName: "اسم {{student}}",
      bookFallback: (id) => `{{subject}} ${id}`,
      miyari: "معياري",
      passMarkTitle: "تم تحديد درجة نجاح خاصة لهذا {{subject}}",
      pass: (n) => `النجاح ${n}`,
      submittedBy: (by, at) => `سُلِّم: ${by} ${at}`,
      submit: "تسليم",
      verify: "تحقق",
      openForEdit: "فتح للتعديل",
      reject: "رفض",
      subjectsHere: "ستظهر قائمة {{subject}} هنا",
      noStudents: "لم يوجد أي {{student}} في هذا {{class}}",
      noBooks: "لم يُضَف أي {{subject}} لهذا {{class}}",
      lockedTitle: "تم تسليم هذا {{subject}} — التعديل مغلق",
      addNote: "إضافة ملاحظة",
      notePlaceholder: "اكتب ملاحظة...",
      save: "حفظ",
      legendFail: "راسب",
      legendPass: "ناجح",
      legendAbsent: "غائب (-)",
    },
    full: {
      title: "📊 جدول النتائج الكامل",
      status: "الحالة:",
      deleteTitle: "حذف النتيجة",
      deleteMessage: "هل أنت متأكد؟",
      editAllPublishedTitle: "نتيجة منشورة — تصحيح درجات {{class}} كله دفعة واحدة",
      editAllTitle: "تعديل درجات {{class}} كله دفعة واحدة",
      correctAll: "✏️ تصحيح جميع الدرجات",
      editMarks: "✏️ تعديل الدرجات",
      recalcTitle: "إعادة حساب هذه النتيجة وفق درجة الرسوب وحدود التقديرات الحالية",
      recalc: "🔄 إعادة الحساب",
      rollByRankTitle: "يعيد ترقيم جلوس كل {{student}} حسب الترتيب",
      rollUpdating: "جارٍ تحديث الأرقام...",
      rollByRank: "🏆 الترقيم حسب الترتيب",
      undoRollTitle: "يستعيد أرقام الجلوس السابقة للترقيم حسب الترتيب",
      undoRoll: "↩️ استعادة الأرقام السابقة",
      verifyTitle: "اكتملت معالجة الدرجات — تحقق من النتيجة الآن",
      verifying: "جارٍ التحقق...",
      verify: "✅ التحقق من النتيجة",
      approveTitle: "اعتماد النتيجة المتحقَّق منها",
      approving: "جارٍ الاعتماد...",
      approve: "👍 اعتماد",
      rejectTitle: "رفض النتيجة وإعادتها إلى المعالجة",
      reject: "رفض",
      publishing: "جارٍ النشر...",
      publish: "نشر",
      regNo: "رقم التسجيل",
      studentName: "اسم {{student}}",
      bookFallback: (id) => `{{subject}} ${id}`,
      miyari: "(معياري)",
      pass: (n) => `(النجاح ${n})`,
      total: "المجموع",
      average: "المعدل",
      generalGrade: "التقدير العام",
      madrasaGrade: "تقدير المدرسة",
      resultState: "الحالة",
      rank: "الترتيب",
      actions: "الإجراءات",
      noResult: "لا توجد نتيجة",
      view: "عرض",
      correctPublishedTitle: "نتيجة منشورة — أرسل طلب تصحيح",
      editOneTitle: "تعديل درجات هذا الطالب فقط",
      correct: "✏️ تصحيح",
      edit: "✏️ تعديل",
    },
    components: {
      options: {
        WRITTEN: "تحريري",
        MCQ: "اختيار من متعدد",
        PRACTICAL: "عملي",
        ORAL: "شفهي",
        ASSIGNMENT: "واجب",
        CLASS_ASSESSMENT: "تقييم صفي",
        OTHER: "أخرى",
      },
      needOne: "أضف مكوّنًا واحدًا على الأقل",
      invalidFullMark: "يجب أن تكون الدرجة الكاملة لكل مكوّن رقمًا صحيحًا",
      saved: "تم حفظ المكوّنات",
      saveFailed: "تعذّر الحفظ — مجموع الدرجات الكاملة غير مطابق",
      title: (book) => `توزيع الدرجات — ${book}`,
      examLabel: "الاختبار (اختياري — اتركه فارغًا ليُطبَّق على جميع الاختبارات)",
      generalExam: "عام (جميع الاختبارات)",
      none: "لم تُضَف أي مكوّنات",
      fullMark: "الدرجة الكاملة",
      add: "إضافة مكوّن",
    },
    overview: {
      notEntered: "⚪ لم يُدخَل",
      published: "✅ منشورة",
      complete: "🟢 اكتمل الإدخال",
      partial: (done, total) => `🟡 جزئي (${done}/${total})`,
      empty: "لا يوجد اختبار أو {{division}}. أضف اختبارًا و{{division}} أولًا.",
    },
    password: {
      label: "أدخل كلمة المرور",
      hide: "إخفاء كلمة المرور",
      show: "إظهار كلمة المرور",
      required: "كلمة المرور مطلوبة",
      verifying: "جارٍ التحقق...",
    },
    reason: {
      label: "اكتب السبب",
      placeholder: "اكتب السبب...",
      required: "السبب مطلوب",
    },
    banner: {
      needUpdate: "النتائج تحتاج إلى تحديث:",
      willChange: (sessions, students, published) =>
        ` وفق إعدادات درجة الرسوب والتقديرات الحالية ستتغير نتيجة ${students} من الطلاب في ${sessions} نتيجة${
          published ? ` (${published} منشورة)` : ""
        }. سيُعرض ما سيتغير أولًا، ولن يُطبَّق شيء إلا بعد تأكيدك.`,
      checking: "جارٍ فحص النتائج...",
      checkFailed: "تعذّر التحقق من حداثة النتائج. يمكنك فتح إعادة الحساب للمراجعة بنفسك.",
      allUpToDate: "جميع النتائج محدَّثة.",
      allUpToDateHint: " عند تغيير حدود التقديرات أو درجة الرسوب واحتياج نتيجة إلى تحديث، سيُفعَّل زر إعادة الحساب هنا.",
      noNeed: "لا توجد نتائج تحتاج إلى إعادة حساب الآن",
      button: "إعادة حساب النتائج",
    },
    recalc: {
      loadFailed: "تعذّر جلب بيانات إعادة الحساب",
      partialFail: (updated, failed) => `تم تحديث ${updated} نتيجة، وفشلت ${failed}`,
      done: (updated, students) => `أُعيد حساب ${updated} نتيجة (تغيّرت نتيجة ${students} من الطلاب)`,
      failed: "تعذّرت إعادة الحساب",
      titleOne: "🔄 إعادة حساب النتيجة",
      titleAll: "🔄 إعادة حساب جميع النتائج",
      intro:
        "ستُعاد حساب النتائج وفق درجة الرسوب وحدود التقديرات وإعدادات {{subject}} الحالية. لن تتغير الدرجات نفسها — يُحدَّث فقط المجموع والمعدل والتقدير والنجاح/الرسوب والترتيب.",
      checking: "جارٍ التحقق...",
      fetchFailed: "تعذّر جلب البيانات.",
      retry: "أعد المحاولة",
      nothingOne: "✅ هذه النتيجة محدَّثة بالفعل وفق الإعدادات الحالية — لا شيء لتغييره.",
      nothingAll: "✅ جميع النتائج محدَّثة بالفعل وفق الإعدادات الحالية — لا شيء لتغييره.",
      examClass: "الاختبار / {{class}}",
      state: "الحالة",
      willChange: "سيتغيّر",
      people: (changed, total) => `${changed} / ${total}`,
      includePublished: "التطبيق على النتائج المنشورة/المقفلة أيضًا",
      includePublishedHint: (n) =>
        ` (${n}). اطّلع عليها أولياء الأمور مسبقًا — ضع علامة فقط إن أردت تطبيق القواعد الجديدة على الاختبارات السابقة. ستبقى منشورة، وتُحفظ السجلات قبل التغيير وبعده للتدقيق.`,
      unpublishedNote:
        'تُحدَّث النتائج غير المنشورة مباشرة. وإن كانت متحقَّقًا منها أو معتمدة فستعود إلى حالة "قيد المعالجة" — وبصلاحيتك يتم التحقق والاعتماد معًا عند النشر.',
      singlePublishedNote: "هذه نتيجة منشورة — ستُطبَّق لأنك اخترتها بنفسك، وتبقى منشورة.",
      skipped: (n) => `⚠️ استُبعدت ${n} نتيجة لعدم اكتمال الدرجات: `,
      totalsFailed: (n) => `تعذّر التحقق من ${n} نتيجة.`,
      applying: "جارٍ التطبيق...",
      apply: (results, students) => `تطبيق (${results} نتيجة، ${students} طالب)`,
    },
    corrections: {
      fields: {
        mark: "الدرجة",
        is_absent: "الغياب",
        is_exempted: "الإعفاء",
        is_withheld: "الحجب",
        note: "ملاحظة",
        general_grade: "التقدير العام",
        madrasa_grade: "تقدير المدرسة",
        total: "المجموع",
        average: "المعدل",
        status: "الحالة",
        rank_no: "الترتيب",
      },
      absent: "غائب",
      present: "حاضر",
      yes: "نعم",
      no: "لا",
      studentFallback: (id) => `{{student}} #${id}`,
      bookFallback: (id) => `{{subject}} #${id}`,
      applied: "تم تطبيق التصحيح",
      rejected: "تم رفض طلب التصحيح",
      decideFailed: "تعذّر اتخاذ القرار",
      approveTitle: "اعتماد التصحيح",
      approveMessage: (student, book, field, from, to) =>
        `${student} — ${book}: سيتغير ${field} من "${from}" إلى "${to}". وسيُعاد حساب المجموع والمعدل والتقدير والترتيب.`,
      approveConfirm: "اعتماد وتطبيق",
      title: "📝 طلبات تصحيح النتائج",
      subtitle: 'لا يمكن تغيير درجات النتيجة المنشورة مباشرة — اضغط "✏️ تصحيح" لإرسال طلب، ويُطبَّق بعد الاعتماد.',
      showAll: (n) => `عرض الكل (${n})`,
      noneYet: "لا توجد طلبات تصحيح بعد",
      nonePending: "لا توجد طلبات قيد الانتظار",
      student: "{{student}}",
      subject: "{{subject}}",
      field: "الحقل",
      beforeAfter: "السابق → الجديد",
      reason: "السبب",
      state: "الحالة",
      actions: "الإجراءات",
      decision: (note) => `القرار: ${note}`,
      approve: "اعتماد",
      reject: "رفض",
      rejectTitle: "رفض طلب التصحيح",
      rejectMessage: "الرفض لا يُحدث أي تغيير في النتيجة.",
      rejectLabel: "سبب الرفض",
      rejectConfirm: "رفض",
    },
    stats: {
      totalStudents: "إجمالي الطلاب",
      pass: "ناجح",
      fail: "راسب",
      absent: "غائب",
      gradeScale: "سلّم التقديرات — درجات كل تقدير",
      general: "عام",
      madrasa: "المدرسة",
    },
    studentEdit: {
      correctTitle: "📝 تصحيح النتيجة",
      requestTitle: "📝 طلب تصحيح النتيجة",
      editTitle: "✏️ تعديل درجات هذا الطالب فقط",
      directNote:
        "هذه النتيجة منشورة. بصلاحيتك يُطبَّق التصحيح فورًا ويُعاد حساب المجموع والمعدل والتقدير والترتيب. ويُحفظ كل شيء مع السبب في سجل التدقيق.",
      requestNote:
        "هذه النتيجة منشورة بالفعل. الدرجات المعدَّلة هنا لا تُحفظ مباشرة — بل تُرسَل طلبَ تصحيح وتُطبَّق بعد الاعتماد.",
      subject: "{{subject}}",
      mark: "الدرجة",
      bookFallback: (id) => `{{subject}} ${id}`,
      passMarkTitle: "تم تحديد درجة نجاح خاصة لهذا {{subject}}",
      pass: (n) => `(النجاح ${n})`,
      fail: "راسب",
      passLegend: "ناجح",
      absentLegend: 'غائب (اضغط "-")',
      reasonLabel: "سبب التصحيح (مطلوب)",
      reasonPlaceholder: "مثال: حدث خطأ أثناء إدخال الدرجات...",
      reasonRequired: "السبب مطلوب",
      applying: "جارٍ التطبيق...",
      submitting: "جارٍ الإرسال...",
      saving: "جارٍ الحفظ...",
      applyCorrection: "تطبيق التصحيح",
      sendRequest: "إرسال الطلب",
      save: "حفظ",
    },
  },
});
