import { defineText } from "@madrasha/shared-ui/src/i18n";

/** UI text for manual attendance, the attendance report and kiosk devices. */
export const attendanceText = defineText({
  bn: {
    common: {
      selectDivision: "{{division}} নির্বাচন করুন",
      classLoading: "{{class}} লোড হচ্ছে...",
      selectClass: "{{class}} নির্বাচন করুন",
      noName: "নাম নেই",
      markAllPresent: "সবাইকে উপস্থিত করুন",
      noStudentsInClass: "এই {{class}}তে কোনো {{student}} নেই",
      present: "উপস্থিত",
      absent: "অনুপস্থিত",
    },
    mark: {
      selectClassFirst: "প্রথমে {{class}} নির্বাচন করুন",
      saved: "উপস্থিতি সংরক্ষণ করা হয়েছে",
      saveFailed: "উপস্থিতি সংরক্ষণ করতে সমস্যা হয়েছে",
      title: "{{student}} উপস্থিতি",
      todayDate: "আজকের তারিখ:",
      tickHint: "টিক দিলে উপস্থিত, টিক না দিলে অনুপস্থিত",
      total: (n: string) => `মোট: ${n}`,
      presentCount: (n: string) => `উপস্থিত: ${n}`,
      absentCount: (n: string) => `অনুপস্থিত: ${n}`,
      alreadySubmitted: "আজকের উপস্থিতি ইতিমধ্যে জমা দেওয়া হয়েছে। পরিবর্তনের প্রয়োজন হলে উপস্থিতি রিপোর্ট থেকে এডিট করুন।",
      goToReport: "উপস্থিতি রিপোর্টে যান",
      selectFirst: "উপস্থিতি নেওয়ার জন্য প্রথমে {{division}} ও {{class}} নির্বাচন করুন",
      noStudentsYear: (year: string) => `এই {{class}}তে ${year} {{session}}ে কোনো {{student}} নেই`,
      saving: "সংরক্ষণ হচ্ছে...",
      save: "উপস্থিতি সংরক্ষণ করুন",
    },
    report: {
      loadFailed: "রিপোর্ট লোড করতে সমস্যা হয়েছে",
      classFallback: (id: string) => `{{class}} #${id}`,
      updated: "উপস্থিতি হালনাগাদ করা হয়েছে",
      updateFailed: "হালনাগাদ করতে সমস্যা হয়েছে",
      title: "উপস্থিতি রিপোর্ট",
      subtitle:
        "{{class}} নির্বাচন না করলে পুরো {{institution}}র সারাংশ দেখাবে; নির্দিষ্ট {{division}}/{{class}} বাছাই করলে শুধু সেটির রিপোর্ট ও এডিট অপশন দেখাবে",
      rate: "উপস্থিতির হার",
      totalPresent: "মোট উপস্থিত",
      totalAbsent: "মোট অনুপস্থিত",
      daysTaken: "উপস্থিতি নেওয়া হয়েছে",
      days: "দিন",
      daily: "দিনভিত্তিক সারাংশ",
      noRecords: "এই মাসে কোনো উপস্থিতি রেকর্ড নেই",
      date: "তারিখ",
      edit: "এডিট",
      editOtherDate: "অন্য কোনো তারিখ এডিট করুন:",
      classWise: "{{class}}ভিত্তিক সারাংশ",
      class: "{{class}}",
      rateShort: "হার",
      attendanceDays: "হাজিরার দিন",
      details: "বিস্তারিত",
      classHint: 'কোনো নির্দিষ্ট দিনের উপস্থিতি এডিট করতে উপরে {{division}} ও {{class}} নির্বাচন করুন, অথবা কোনো {{class}}র পাশে "বিস্তারিত" চাপুন',
      topAbsent: "সর্বাধিক অনুপস্থিত",
      noAbsence: "এই মাসে কোনো অনুপস্থিতি নেই",
      dayCount: (n: string) => `${n} দিন`,
      editTitle: (date: string) => `${date} - উপস্থিতি এডিট`,
      saveChanges: "পরিবর্তন সংরক্ষণ করুন",
    },
    kiosk: {
      nameRequired: "ডিভাইসের একটা নাম দিন",
      created: "কিওস্ক ডিভাইস তৈরি হয়েছে",
      createFailed: "ডিভাইস তৈরি করতে সমস্যা হয়েছে",
      copied: (label: string) => `${label} কপি হয়েছে`,
      copyFailed: "কপি করা যায়নি",
      deactivated: "ডিভাইস নিষ্ক্রিয় করা হয়েছে",
      activated: "ডিভাইস সক্রিয় করা হয়েছে",
      updateFailed: "আপডেট করতে সমস্যা হয়েছে",
      deleteTitle: "কিওস্ক ডিভাইস ডিলিট করুন",
      deleteMessage: (name: string) =>
        `"${name}" ডিভাইসটি স্থায়ীভাবে মুছে ফেলতে চান? এই ডিভাইসের কী দিয়ে আর কার্ড স্ক্যান করা যাবে না।`,
      deleteConfirm: "ডিলিট করুন",
      deleted: "ডিভাইস মুছে ফেলা হয়েছে",
      deleteFailed: "মুছতে সমস্যা হয়েছে",
      title: "কিওস্ক ডিভাইস ব্যবস্থাপনা",
      subtitle:
        "গেটে থাকা কিওস্ক ট্যাবলেট/পিসিকে অ্যাটেন্ডেন্স নেওয়ার অনুমতি দিতে এখানে ডিভাইস তৈরি করুন। প্রতিটি ডিভাইসের একটি নিজস্ব কী থাকে যা কিওস্ক পেজে একবার সেটআপ করতে হয়।",
      newDevice: "নতুন ডিভাইস তৈরি করুন",
      allDevices: "সব কিওস্ক ডিভাইস",
      emptyTitle: "এখনো কোনো কিওস্ক ডিভাইস তৈরি করা হয়নি",
      emptyHint: "উপরের বাটন থেকে প্রথম ডিভাইসটি তৈরি করুন।",
      active: "সক্রিয়",
      inactive: "নিষ্ক্রিয়",
      lastSeen: (v: string) => `সর্বশেষ সংযুক্ত: ${v}`,
      neverConnected: "কখনো সংযুক্ত হয়নি",
      createdAt: (v: string) => `তৈরি হয়েছে: ${v}`,
      deactivate: "নিষ্ক্রিয় করুন",
      activate: "সক্রিয় করুন",
      delete: "মুছুন",
      keyTitle: "ডিভাইস কী",
      newTitle: "নতুন কিওস্ক ডিভাইস",
      name: "ডিভাইসের নাম",
      namePlaceholder: "যেমন: প্রধান গেট কিওস্ক",
      creating: "তৈরি হচ্ছে...",
      create: "তৈরি করুন",
      keyWarning: "এই কী আর কখনো দেখানো যাবে না, এখনই কপি করে নিরাপদে রাখুন",
      deviceKey: "ডিভাইস কী",
      copy: "কপি করুন",
      kioskUrl: "কিওস্ক পেজের URL (ট্যাবলেটে খুলুন)",
      done: "বুঝেছি, বন্ধ করুন",
    },
  },
  en: {
    common: {
      selectDivision: "Select {{division}}",
      classLoading: "Loading {{class}}es...",
      selectClass: "Select {{class}}",
      noName: "No name",
      markAllPresent: "Mark everyone present",
      noStudentsInClass: "No {{student}}s in this {{class}}",
      present: "Present",
      absent: "Absent",
    },
    mark: {
      selectClassFirst: "Select a {{class}} first",
      saved: "Attendance saved",
      saveFailed: "Could not save attendance",
      title: "{{student}} Attendance",
      todayDate: "Today:",
      tickHint: "ticked = present, unticked = absent",
      total: (n) => `Total: ${n}`,
      presentCount: (n) => `Present: ${n}`,
      absentCount: (n) => `Absent: ${n}`,
      alreadySubmitted: "Today's attendance has already been submitted. To change it, edit it from the attendance report.",
      goToReport: "Go to Attendance Report",
      selectFirst: "Select a {{division}} and {{class}} to take attendance",
      noStudentsYear: (year) => `No {{student}}s in this {{class}} for the ${year} {{session}}`,
      saving: "Saving...",
      save: "Save Attendance",
    },
    report: {
      loadFailed: "Could not load the report",
      classFallback: (id) => `{{class}} #${id}`,
      updated: "Attendance updated",
      updateFailed: "Could not update",
      title: "Attendance Report",
      subtitle:
        "Without a {{class}} selected, the whole {{institution}} summary is shown; pick a {{division}}/{{class}} to see only its report and edit options",
      rate: "Attendance Rate",
      totalPresent: "Total Present",
      totalAbsent: "Total Absent",
      daysTaken: "Attendance Taken",
      days: "days",
      daily: "Daily Summary",
      noRecords: "No attendance records this month",
      date: "Date",
      edit: "Edit",
      editOtherDate: "Edit another date:",
      classWise: "{{class}}-wise Summary",
      class: "{{class}}",
      rateShort: "Rate",
      attendanceDays: "Attendance Days",
      details: "Details",
      classHint: 'To edit a specific day, select a {{division}} and {{class}} above, or press "Details" next to a {{class}}',
      topAbsent: "Most Absent",
      noAbsence: "No absences this month",
      dayCount: (n) => `${n} days`,
      editTitle: (date) => `${date} - Edit Attendance`,
      saveChanges: "Save Changes",
    },
    kiosk: {
      nameRequired: "Give the device a name",
      created: "Kiosk device created",
      createFailed: "Could not create the device",
      copied: (label) => `${label} copied`,
      copyFailed: "Could not copy",
      deactivated: "Device deactivated",
      activated: "Device activated",
      updateFailed: "Could not update",
      deleteTitle: "Delete Kiosk Device",
      deleteMessage: (name) =>
        `Permanently delete the device "${name}"? Cards can no longer be scanned with this device's key.`,
      deleteConfirm: "Delete",
      deleted: "Device deleted",
      deleteFailed: "Could not delete",
      title: "Kiosk Device Management",
      subtitle:
        "Create a device here to allow a kiosk tablet/PC at the gate to take attendance. Each device has its own key, set up once on the kiosk page.",
      newDevice: "Create New Device",
      allDevices: "All Kiosk Devices",
      emptyTitle: "No kiosk devices created yet",
      emptyHint: "Create your first device with the button above.",
      active: "Active",
      inactive: "Inactive",
      lastSeen: (v) => `Last connected: ${v}`,
      neverConnected: "Never connected",
      createdAt: (v) => `Created: ${v}`,
      deactivate: "Deactivate",
      activate: "Activate",
      delete: "Delete",
      keyTitle: "Device Key",
      newTitle: "New Kiosk Device",
      name: "Device name",
      namePlaceholder: "e.g. Main Gate Kiosk",
      creating: "Creating...",
      create: "Create",
      keyWarning: "This key will never be shown again — copy it now and keep it safe",
      deviceKey: "Device key",
      copy: "Copy",
      kioskUrl: "Kiosk page URL (open on the tablet)",
      done: "Got it, close",
    },
  },
  ar: {
    common: {
      selectDivision: "اختر {{division}}",
      classLoading: "جارٍ تحميل الصفوف...",
      selectClass: "اختر {{class}}",
      noName: "بلا اسم",
      markAllPresent: "تسجيل الجميع حاضرين",
      noStudentsInClass: "لا يوجد طلاب في هذا {{class}}",
      present: "حاضر",
      absent: "غائب",
    },
    mark: {
      selectClassFirst: "اختر {{class}} أولًا",
      saved: "تم حفظ الحضور",
      saveFailed: "تعذّر حفظ الحضور",
      title: "حضور الطلاب",
      todayDate: "تاريخ اليوم:",
      tickHint: "العلامة = حاضر، بدون علامة = غائب",
      total: (n) => `المجموع: ${n}`,
      presentCount: (n) => `حاضر: ${n}`,
      absentCount: (n) => `غائب: ${n}`,
      alreadySubmitted: "تم تسليم حضور اليوم مسبقًا. للتعديل، عدّله من تقرير الحضور.",
      goToReport: "الانتقال إلى تقرير الحضور",
      selectFirst: "اختر {{division}} و{{class}} أولًا لتسجيل الحضور",
      noStudentsYear: (year) => `لا يوجد طلاب في هذا {{class}} في {{session}} ${year}`,
      saving: "جارٍ الحفظ...",
      save: "حفظ الحضور",
    },
    report: {
      loadFailed: "تعذّر تحميل التقرير",
      classFallback: (id) => `{{class}} #${id}`,
      updated: "تم تحديث الحضور",
      updateFailed: "تعذّر التحديث",
      title: "تقرير الحضور",
      subtitle:
        "دون اختيار {{class}} يُعرض ملخص {{institution}} كلها؛ اختر {{division}}/{{class}} لعرض تقريره وخيارات التعديل فقط",
      rate: "نسبة الحضور",
      totalPresent: "إجمالي الحضور",
      totalAbsent: "إجمالي الغياب",
      daysTaken: "أيام تسجيل الحضور",
      days: "يوم",
      daily: "الملخص اليومي",
      noRecords: "لا توجد سجلات حضور هذا الشهر",
      date: "التاريخ",
      edit: "تعديل",
      editOtherDate: "تعديل تاريخ آخر:",
      classWise: "الملخص حسب {{class}}",
      class: "{{class}}",
      rateShort: "النسبة",
      attendanceDays: "أيام الحضور",
      details: "التفاصيل",
      classHint: 'لتعديل حضور يوم معين اختر {{division}} و{{class}} أعلاه، أو اضغط "التفاصيل" بجانب {{class}}',
      topAbsent: "الأكثر غيابًا",
      noAbsence: "لا يوجد غياب هذا الشهر",
      dayCount: (n) => `${n} يوم`,
      editTitle: (date) => `${date} - تعديل الحضور`,
      saveChanges: "حفظ التغييرات",
    },
    kiosk: {
      nameRequired: "أدخل اسمًا للجهاز",
      created: "تم إنشاء جهاز الكشك",
      createFailed: "تعذّر إنشاء الجهاز",
      copied: (label) => `تم نسخ ${label}`,
      copyFailed: "تعذّر النسخ",
      deactivated: "تم تعطيل الجهاز",
      activated: "تم تفعيل الجهاز",
      updateFailed: "تعذّر التحديث",
      deleteTitle: "حذف جهاز الكشك",
      deleteMessage: (name) => `هل تريد حذف الجهاز "${name}" نهائيًا؟ لن يمكن مسح البطاقات بمفتاح هذا الجهاز بعد ذلك.`,
      deleteConfirm: "حذف",
      deleted: "تم حذف الجهاز",
      deleteFailed: "تعذّر الحذف",
      title: "إدارة أجهزة الكشك",
      subtitle:
        "أنشئ جهازًا هنا للسماح لجهاز الكشك (لوحي/حاسوب) عند البوابة بتسجيل الحضور. لكل جهاز مفتاح خاص يُضبط مرة واحدة في صفحة الكشك.",
      newDevice: "إنشاء جهاز جديد",
      allDevices: "جميع أجهزة الكشك",
      emptyTitle: "لم يُنشأ أي جهاز كشك بعد",
      emptyHint: "أنشئ أول جهاز من الزر أعلاه.",
      active: "نشط",
      inactive: "غير نشط",
      lastSeen: (v) => `آخر اتصال: ${v}`,
      neverConnected: "لم يتصل أبدًا",
      createdAt: (v) => `أُنشئ: ${v}`,
      deactivate: "تعطيل",
      activate: "تفعيل",
      delete: "حذف",
      keyTitle: "مفتاح الجهاز",
      newTitle: "جهاز كشك جديد",
      name: "اسم الجهاز",
      namePlaceholder: "مثال: كشك البوابة الرئيسية",
      creating: "جارٍ الإنشاء...",
      create: "إنشاء",
      keyWarning: "لن يُعرض هذا المفتاح مرة أخرى، انسخه الآن واحفظه بأمان",
      deviceKey: "مفتاح الجهاز",
      copy: "نسخ",
      kioskUrl: "رابط صفحة الكشك (افتحه على الجهاز اللوحي)",
      done: "فهمت، إغلاق",
    },
  },
});
