import { defineText } from "@madrasha/shared-ui/src/i18n";

/** UI text for manual attendance and the attendance report. */
export const attendanceText = defineText({
  bn: {
    common: {
      selectDivision: "{{division}} নির্বাচন করুন",
      classLoading: "{{class}} লোড হচ্ছে...",
      selectClass: "{{class}} নির্বাচন করুন",
      noName: "নাম নেই",
      markAllPresent: "সবাইকে উপস্থিত করুন",
      noStudentsInClass: "এই {{class}}তে কোনো {{student}} নেই",
      present: "উপস্থিত",
      absent: "অনুপস্থিত",
    },
    mark: {
      selectClassFirst: "প্রথমে {{class}} নির্বাচন করুন",
      saved: "উপস্থিতি সংরক্ষণ করা হয়েছে",
      saveFailed: "উপস্থিতি সংরক্ষণ করতে সমস্যা হয়েছে",
      title: "{{student}} উপস্থিতি",
      todayDate: "আজকের তারিখ:",
      tickHint: "টিক দিলে উপস্থিত, টিক না দিলে অনুপস্থিত",
      total: (n: string) => `মোট: ${n}`,
      presentCount: (n: string) => `উপস্থিত: ${n}`,
      absentCount: (n: string) => `অনুপস্থিত: ${n}`,
      alreadySubmitted: "আজকের উপস্থিতি ইতিমধ্যে জমা দেওয়া হয়েছে। পরিবর্তনের প্রয়োজন হলে উপস্থিতি রিপোর্ট থেকে এডিট করুন।",
      goToReport: "উপস্থিতি রিপোর্টে যান",
      selectFirst: "উপস্থিতি নেওয়ার জন্য প্রথমে {{division}} ও {{class}} নির্বাচন করুন",
      noStudentsYear: (year: string) => `এই {{class}}তে ${year} {{session}}ে কোনো {{student}} নেই`,
      saving: "সংরক্ষণ হচ্ছে...",
      save: "উপস্থিতি সংরক্ষণ করুন",
    },
    report: {
      loadFailed: "রিপোর্ট লোড করতে সমস্যা হয়েছে",
      classFallback: (id: string) => `{{class}} #${id}`,
      updated: "উপস্থিতি হালনাগাদ করা হয়েছে",
      updateFailed: "হালনাগাদ করতে সমস্যা হয়েছে",
      title: "উপস্থিতি রিপোর্ট",
      subtitle:
        "{{class}} নির্বাচন না করলে পুরো {{institution}}র সারাংশ দেখাবে; নির্দিষ্ট {{division}}/{{class}} বাছাই করলে শুধু সেটির রিপোর্ট ও এডিট অপশন দেখাবে",
      rate: "উপস্থিতির হার",
      totalPresent: "মোট উপস্থিত",
      totalAbsent: "মোট অনুপস্থিত",
      daysTaken: "উপস্থিতি নেওয়া হয়েছে",
      days: "দিন",
      daily: "দিনভিত্তিক সারাংশ",
      noRecords: "এই মাসে কোনো উপস্থিতি রেকর্ড নেই",
      date: "তারিখ",
      edit: "এডিট",
      editOtherDate: "অন্য কোনো তারিখ এডিট করুন:",
      classWise: "{{class}}ভিত্তিক সারাংশ",
      class: "{{class}}",
      rateShort: "হার",
      attendanceDays: "হাজিরার দিন",
      details: "বিস্তারিত",
      classHint: 'কোনো নির্দিষ্ট দিনের উপস্থিতি এডিট করতে উপরে {{division}} ও {{class}} নির্বাচন করুন, অথবা কোনো {{class}}র পাশে "বিস্তারিত" চাপুন',
      topAbsent: "সর্বাধিক অনুপস্থিত",
      noAbsence: "এই মাসে কোনো অনুপস্থিতি নেই",
      dayCount: (n: string) => `${n} দিন`,
      editTitle: (date: string) => `${date} - উপস্থিতি এডিট`,
      saveChanges: "পরিবর্তন সংরক্ষণ করুন",
    },
  },
  en: {
    common: {
      selectDivision: "Select {{division}}",
      classLoading: "Loading {{class}}es...",
      selectClass: "Select {{class}}",
      noName: "No name",
      markAllPresent: "Mark everyone present",
      noStudentsInClass: "No {{student}}s in this {{class}}",
      present: "Present",
      absent: "Absent",
    },
    mark: {
      selectClassFirst: "Select a {{class}} first",
      saved: "Attendance saved",
      saveFailed: "Could not save attendance",
      title: "{{student}} Attendance",
      todayDate: "Today:",
      tickHint: "ticked = present, unticked = absent",
      total: (n) => `Total: ${n}`,
      presentCount: (n) => `Present: ${n}`,
      absentCount: (n) => `Absent: ${n}`,
      alreadySubmitted: "Today's attendance has already been submitted. To change it, edit it from the attendance report.",
      goToReport: "Go to Attendance Report",
      selectFirst: "Select a {{division}} and {{class}} to take attendance",
      noStudentsYear: (year) => `No {{student}}s in this {{class}} for the ${year} {{session}}`,
      saving: "Saving...",
      save: "Save Attendance",
    },
    report: {
      loadFailed: "Could not load the report",
      classFallback: (id) => `{{class}} #${id}`,
      updated: "Attendance updated",
      updateFailed: "Could not update",
      title: "Attendance Report",
      subtitle:
        "Without a {{class}} selected, the whole {{institution}} summary is shown; pick a {{division}}/{{class}} to see only its report and edit options",
      rate: "Attendance Rate",
      totalPresent: "Total Present",
      totalAbsent: "Total Absent",
      daysTaken: "Attendance Taken",
      days: "days",
      daily: "Daily Summary",
      noRecords: "No attendance records this month",
      date: "Date",
      edit: "Edit",
      editOtherDate: "Edit another date:",
      classWise: "{{class}}-wise Summary",
      class: "{{class}}",
      rateShort: "Rate",
      attendanceDays: "Attendance Days",
      details: "Details",
      classHint: 'To edit a specific day, select a {{division}} and {{class}} above, or press "Details" next to a {{class}}',
      topAbsent: "Most Absent",
      noAbsence: "No absences this month",
      dayCount: (n) => `${n} days`,
      editTitle: (date) => `${date} - Edit Attendance`,
      saveChanges: "Save Changes",
    },
  },
});
