import { defineText } from "@madrasha/shared-ui/src/i18n";

/** UI text for manual attendance, the attendance report and the attendance policy. */
export const attendanceText = defineText({
  bn: {
    common: {
      selectDivision: "{{division}} নির্বাচন করুন",
      classLoading: "{{class}} লোড হচ্ছে...",
      selectClass: "{{class}} নির্বাচন করুন",
      noName: "নাম নেই",
      markAllPresent: "সবাইকে উপস্থিত করুন",
      noStudentsInClass: "এই {{class}}তে কোনো {{student}} নেই",
      present: "উপস্থিত",
      absent: "অনুপস্থিত",
      late: "দেরি",
      leave: "ছুটি",
      unmarked: "চিহ্নিত নয়",
      status: {
        PRESENT: "উপস্থিত",
        LATE: "দেরি",
        ABSENT: "অনুপস্থিত",
        LEAVE: "ছুটি",
      },
      attendeeType: {
        STUDENT: "{{student}}",
        TEACHER: "{{teacher}}",
        STAFF: "স্টাফ",
      },
      source: {
        manual: "ম্যানুয়াল",
        k40: "ডিভাইস",
        auto: "অটো অনুপস্থিত",
        leave: "ছুটির আবেদন",
      } as Record<string, string>,
      history: "ইতিহাস",
      checkIn: (time: string) => `প্রবেশ ${time}`,
    },
    historyModal: {
      title: (name: string) => `পরিবর্তনের ইতিহাস - ${name}`,
      loading: "লোড হচ্ছে...",
      loadFailed: "ইতিহাস লোড করা যায়নি",
      empty: "কোনো পরিবর্তনের রেকর্ড নেই",
      by: "পরিবর্তন করেছেন",
      system: "সিস্টেম",
      reason: "কারণ",
      removed: "মুছে ফেলা হয়েছে",
      none: "নেই",
      via: {
        manual: "ম্যানুয়াল হাজিরা",
        bulk: "ম্যানুয়াল হাজিরা",
        correction: "সংশোধন",
        k40: "ডিভাইস",
        device: "ডিভাইস",
        auto: "অটো অনুপস্থিত",
        leave: "ছুটি অনুমোদন",
        leave_cancel: "ছুটি বাতিল",
        session: "সেশন",
      } as Record<string, string>,
    },
    reasonModal: {
      title: "পরিবর্তনের কারণ",
      hint: "আগের তারিখের বা ডিভাইস/ছুটির রেকর্ড পরিবর্তন করতে একটি কারণ লিখুন। এটি ইতিহাসে সংরক্ষিত থাকবে।",
      placeholder: "যেমন: ভুলবশত অনুপস্থিত দেওয়া হয়েছিল",
      required: "কারণ লিখুন",
      confirm: "কারণসহ সংরক্ষণ",
    },
    mark: {
      selectClassFirst: "প্রথমে {{class}} নির্বাচন করুন",
      saved: "উপস্থিতি সংরক্ষণ করা হয়েছে",
      saveFailed: "উপস্থিতি সংরক্ষণ করতে সমস্যা হয়েছে",
      title: "উপস্থিতি গ্রহণ",
      subtitle: "তারিখ ও তালিকা বাছাই করে প্রত্যেকের অবস্থা চিহ্নিত করুন",
      date: "তারিখ",
      today: "আজ",
      search: "নাম বা রোল দিয়ে খুঁজুন",
      total: (n: string) => `মোট: ${n}`,
      presentCount: (n: string) => `উপস্থিত: ${n}`,
      absentCount: (n: string) => `অনুপস্থিত: ${n}`,
      selectFirst: "উপস্থিতি নেওয়ার জন্য প্রথমে {{division}} ও {{class}} নির্বাচন করুন",
      noStudentsYear: (year: string) => `এই {{class}}তে ${year} {{session}}ে কোনো {{student}} নেই`,
      noPeople: "তালিকায় কেউ নেই",
      noMatch: "খোঁজার সাথে মিলে এমন কেউ নেই",
      saving: "সংরক্ষণ হচ্ছে...",
      save: "উপস্থিতি সংরক্ষণ করুন",
      allPresent: "সবাই উপস্থিত",
      changes: (n: string) => `${n}টি অসংরক্ষিত পরিবর্তন`,
      discard: "বাতিল",
      offDayHoliday: (title: string) => `এই দিনটি ছুটির দিন${title ? `: ${title}` : ""} - উপস্থিতি নেওয়া যাবে না।`,
      offDayWeekly: "এই দিনটি সাপ্তাহিক ছুটির দিন - উপস্থিতি নেওয়া যাবে না।",
      futureDate: "ভবিষ্যতের তারিখের উপস্থিতি নেওয়া যায় না।",
      outsideWindow: (days: string) =>
        `এই তারিখটি এডিটের সময়সীমার (${days} দিন) বাইরে। পরিবর্তনের জন্য "উপস্থিতি এডিট" অনুমতি প্রয়োজন।`,
      outsideWindowAllowed: (days: string) =>
        `এই তারিখটি এডিটের সময়সীমার (${days} দিন) বাইরে - আপনার অনুমতি আছে, তবে পরিবর্তনের কারণ লিখতে হবে।`,
      pastNotice: "আগের তারিখের বিদ্যমান রেকর্ড পরিবর্তন করলে কারণ লিখতে হবে।",
      existingNotice: (n: string) => `এই তারিখে ${n} জনের উপস্থিতি আগে থেকেই আছে - প্রয়োজনে পরিবর্তন করে আবার সংরক্ষণ করুন।`,
      noPermission: "আপনার উপস্থিতি নেওয়ার অনুমতি নেই - শুধু দেখা যাবে।",
      offDaySettings: "সাপ্তাহিক ছুটি ও ছুটির তালিকা",
      protectedHint: "ডিভাইস ও ছুটির রেকর্ড সুরক্ষিত - সাধারণভাবে পরিবর্তন হবে না।",
      overrideToggle: "ডিভাইস/ছুটির রেকর্ডও পরিবর্তন করুন",
      overrideHint: "চালু করলে সুরক্ষিত রেকর্ড পরিবর্তন করা যাবে (কারণ আবশ্যক)।",
      locked: "সুরক্ষিত",
      remarks: "মন্তব্য",
      remarksPlaceholder: "মন্তব্য (ঐচ্ছিক)",
      savedSummary: (created: string, updated: string, unchanged: string) =>
        `সংরক্ষিত - নতুন ${created}, পরিবর্তিত ${updated}, অপরিবর্তিত ${unchanged}`,
      skipped: (n: string, names: string) =>
        `${n} জনের ডিভাইস/ছুটির রেকর্ড পরিবর্তন হয়নি${names ? `: ${names}` : ""}`,
      nothingToSave: "সংরক্ষণের মতো কোনো পরিবর্তন নেই",
      loadFailed: "উপস্থিতি লোড করা যায়নি",
    },
    report: {
      loadFailed: "রিপোর্ট লোড করতে সমস্যা হয়েছে",
      classFallback: (id: string) => `{{class}} #${id}`,
      title: "উপস্থিতি রিপোর্ট",
      subtitle:
        "{{class}} নির্বাচন না করলে পুরো {{institution}}র সারাংশ দেখাবে; নির্দিষ্ট {{division}}/{{class}} বাছাই করলে শুধু সেটির রিপোর্ট ও এডিট অপশন দেখাবে",
      rate: "উপস্থিতির হার",
      totalPresent: "মোট উপস্থিত",
      totalAbsent: "মোট অনুপস্থিত",
      daysTaken: "উপস্থিতি নেওয়া হয়েছে",
      workingDays: "কর্মদিবস",
      offDays: (n: string) => `ছুটি ${n} দিন`,
      unmarked: "চিহ্নিত নয়",
      unmarkedHint: "হাজিরা নেওয়া দিনে রেকর্ড নেই (অনুপস্থিত ধরা হয়)",
      latePenalty: "দেরির জরিমানা",
      latePenaltyHint: "দেরির কারণে অনুপস্থিত ধরা দিন",
      days: "দিন",
      daily: "দিনভিত্তিক সারাংশ",
      noRecords: "এই মাসে কোনো উপস্থিতি রেকর্ড নেই",
      date: "তারিখ",
      edit: "এডিট",
      editOtherDate: "অন্য কোনো তারিখ এডিট করুন:",
      classWise: "{{class}}ভিত্তিক সারাংশ",
      class: "{{class}}",
      rateShort: "হার",
      attendanceDays: "হাজিরার দিন",
      details: "বিস্তারিত",
      classHint: 'কোনো নির্দিষ্ট দিনের উপস্থিতি এডিট করতে উপরে {{division}} ও {{class}} নির্বাচন করুন, অথবা কোনো {{class}}র পাশে "বিস্তারিত" চাপুন',
      topAbsent: "সর্বাধিক অনুপস্থিত",
      noAbsence: "এই মাসে কোনো অনুপস্থিতি নেই",
      dayCount: (n: string) => `${n} দিন`,
      studentWise: "{{student}}ভিত্তিক হিসাব",
      studentWiseHint: "হার = (উপস্থিত + দেরি − দেরির জরিমানা) ÷ গণনাকৃত দিন; ছুটির হিসাব উপস্থিতি নীতি অনুযায়ী",
      roll: "রোল",
      name: "নাম",
      statsFailed: "{{student}}ভিত্তিক হিসাব লোড করা যায়নি",
      noStats: "কোনো হিসাব নেই",
      policyLink: "উপস্থিতি নীতি",
    },
    policy: {
      title: "উপস্থিতি নীতি",
      subtitle: "শতাংশ হিসাব, এডিটের সময়সীমা, দেরি ও ছুটির নিয়ম এবং সতর্কতা",
      loadFailed: "নীতি লোড করা যায়নি",
      tryAgain: "আবার চেষ্টা করুন।",
      retry: "পুনরায় চেষ্টা",
      saved: "উপস্থিতি নীতি সংরক্ষণ করা হয়েছে",
      saveFailed: "নীতি সংরক্ষণ করা যায়নি",
      readOnly: "আপনার নীতি পরিবর্তনের অনুমতি নেই - শুধু দেখা যাবে।",
      unsaved: "অসংরক্ষিত পরিবর্তন আছে",
      discard: "বাতিল",
      save: "সংরক্ষণ করুন",
      saving: "সংরক্ষণ হচ্ছে...",
      rangeError: (min: string, max: string) => `${min} থেকে ${max} এর মধ্যে পূর্ণসংখ্যা দিন`,
      consecutiveError: "০ (বন্ধ) অথবা ২ থেকে ৩০ এর মধ্যে দিন",
      days: "দিন",
      edit: {
        title: "এডিটের সময়সীমা",
        hint: "আজ থেকে কত দিন আগ পর্যন্ত সাধারণ ব্যবহারকারী উপস্থিতি পরিবর্তন করতে পারবেন। এর আগের তারিখের জন্য \"উপস্থিতি এডিট\" অনুমতি লাগবে।",
        label: "এডিট করা যাবে (দিন)",
        help: "০ = শুধু আজকের দিন",
      },
      late: {
        title: "দেরির নিয়ম",
        hint: "নির্দিষ্ট সংখ্যক দেরিকে একটি অনুপস্থিত হিসেবে গণ্য করা হবে।",
        label: "কতটি দেরি = ১ অনুপস্থিত",
        help: "০ = বন্ধ (দেরিকে পূর্ণ উপস্থিত ধরা হবে)",
      },
      leave: {
        title: "ছুটির হিসাব",
        hint: "শতাংশ গণনায় অনুমোদিত ছুটির দিন কীভাবে ধরা হবে।",
        excluded: "হিসাব থেকে বাদ",
        excludedHint: "ছুটির দিন মোট দিন থেকে বাদ যাবে",
        present: "উপস্থিত ধরা হবে",
        presentHint: "ছুটির দিন উপস্থিত হিসেবে গণ্য",
        absent: "অনুপস্থিত ধরা হবে",
        absentHint: "ছুটির দিন অনুপস্থিত হিসেবে গণ্য",
      },
      low: {
        title: "কম উপস্থিতির সীমা",
        hint: "এই শতাংশের নিচে থাকলে রিপোর্ট ও ড্যাশবোর্ডে কম উপস্থিতি হিসেবে দেখাবে।",
        label: "সীমা (%)",
        help: "০ - ১০০",
      },
      consecutive: {
        title: "টানা অনুপস্থিতির সতর্কতা",
        hint: "কোনো {{student}} টানা এত কর্মদিবস অনুপস্থিত থাকলে অভিভাবককে এসএমএস যাবে (নোটিফিকেশন সেটিংসে চালু থাকলে)।",
        label: "টানা অনুপস্থিত (দিন)",
        help: "০ = বন্ধ, অথবা ২ - ৩০",
      },
      payroll: {
        title: "বেতন থেকে কর্তন",
        hint: "{{teacher}}/স্টাফের অনুপস্থিত দিনের জন্য বেতন কর্তনের প্রস্তাব দেখানো হবে (বেতন পাতায় প্রয়োগ করতে হয়)।",
      },
      calendar: {
        title: "সাপ্তাহিক ছুটি ও ছুটির দিন",
        hint: "ছুটির দিনে উপস্থিতি নেওয়া হয় না এবং শতাংশ হিসাবে গণ্য হয় না। এগুলো ডিভাইস সেটিংস থেকে নির্ধারণ করুন।",
        link: "ডিভাইস সেটিংসে যান",
      },
    },
  },
  en: {
    common: {
      selectDivision: "Select {{division}}",
      classLoading: "Loading {{class}}es...",
      selectClass: "Select {{class}}",
      noName: "No name",
      markAllPresent: "Mark everyone present",
      noStudentsInClass: "No {{student}}s in this {{class}}",
      present: "Present",
      absent: "Absent",
      late: "Late",
      leave: "Leave",
      unmarked: "Unmarked",
      status: {
        PRESENT: "Present",
        LATE: "Late",
        ABSENT: "Absent",
        LEAVE: "Leave",
      },
      attendeeType: {
        STUDENT: "{{student}}",
        TEACHER: "{{teacher}}",
        STAFF: "Staff",
      },
      source: {
        manual: "Manual",
        k40: "Device",
        auto: "Auto absent",
        leave: "Leave request",
      },
      history: "History",
      checkIn: (time) => `In ${time}`,
    },
    historyModal: {
      title: (name) => `Change history - ${name}`,
      loading: "Loading...",
      loadFailed: "Could not load the history",
      empty: "No changes recorded",
      by: "Changed by",
      system: "System",
      reason: "Reason",
      removed: "Removed",
      none: "None",
      via: {
        manual: "Manual marking",
        bulk: "Manual marking",
        correction: "Correction",
        k40: "Device",
        device: "Device",
        auto: "Auto absent",
        leave: "Leave approved",
        leave_cancel: "Leave cancelled",
        session: "Session",
      },
    },
    reasonModal: {
      title: "Reason for change",
      hint: "Changing a past date or a device/leave record needs a reason. It is kept in the history.",
      placeholder: "e.g. Marked absent by mistake",
      required: "Enter a reason",
      confirm: "Save with reason",
    },
    mark: {
      selectClassFirst: "Select a {{class}} first",
      saved: "Attendance saved",
      saveFailed: "Could not save attendance",
      title: "Take Attendance",
      subtitle: "Pick a date and list, then mark each person's status",
      date: "Date",
      today: "Today",
      search: "Search by name or roll",
      total: (n) => `Total: ${n}`,
      presentCount: (n) => `Present: ${n}`,
      absentCount: (n) => `Absent: ${n}`,
      selectFirst: "Select a {{division}} and {{class}} to take attendance",
      noStudentsYear: (year) => `No {{student}}s in this {{class}} for the ${year} {{session}}`,
      noPeople: "Nobody in this list",
      noMatch: "Nobody matches the search",
      saving: "Saving...",
      save: "Save Attendance",
      allPresent: "All present",
      changes: (n) => `${n} unsaved change(s)`,
      discard: "Discard",
      offDayHoliday: (title) => `This is a holiday${title ? `: ${title}` : ""} - attendance cannot be taken.`,
      offDayWeekly: "This is a weekly off day - attendance cannot be taken.",
      futureDate: "Attendance cannot be taken for a future date.",
      outsideWindow: (days) =>
        `This date is outside the edit window (${days} days). Changing it needs the "Edit attendance" permission.`,
      outsideWindowAllowed: (days) =>
        `This date is outside the edit window (${days} days) - you are allowed, but a reason is required.`,
      pastNotice: "Changing an existing record of a past date requires a reason.",
      existingNotice: (n) => `${n} record(s) already exist for this date - change them and save again if needed.`,
      noPermission: "You don't have permission to take attendance - view only.",
      offDaySettings: "Weekly off days & holidays",
      protectedHint: "Device and leave records are protected and are not changed normally.",
      overrideToggle: "Also change device/leave records",
      overrideHint: "When on, protected records can be changed (reason required).",
      locked: "Protected",
      remarks: "Remarks",
      remarksPlaceholder: "Remarks (optional)",
      savedSummary: (created, updated, unchanged) =>
        `Saved - ${created} new, ${updated} changed, ${unchanged} unchanged`,
      skipped: (n, names) => `${n} device/leave record(s) were not changed${names ? `: ${names}` : ""}`,
      nothingToSave: "Nothing to save",
      loadFailed: "Could not load attendance",
    },
    report: {
      loadFailed: "Could not load the report",
      classFallback: (id) => `{{class}} #${id}`,
      title: "Attendance Report",
      subtitle:
        "Without a {{class}} selected, the whole {{institution}} summary is shown; pick a {{division}}/{{class}} to see only its report and edit options",
      rate: "Attendance Rate",
      totalPresent: "Total Present",
      totalAbsent: "Total Absent",
      daysTaken: "Attendance Taken",
      workingDays: "Working Days",
      offDays: (n) => `${n} off day(s)`,
      unmarked: "Unmarked",
      unmarkedHint: "No record on a taken day (counted absent)",
      latePenalty: "Late Penalty",
      latePenaltyHint: "Days counted absent because of lateness",
      days: "days",
      daily: "Daily Summary",
      noRecords: "No attendance records this month",
      date: "Date",
      edit: "Edit",
      editOtherDate: "Edit another date:",
      classWise: "{{class}}-wise Summary",
      class: "{{class}}",
      rateShort: "Rate",
      attendanceDays: "Attendance Days",
      details: "Details",
      classHint: 'To edit a specific day, select a {{division}} and {{class}} above, or press "Details" next to a {{class}}',
      topAbsent: "Most Absent",
      noAbsence: "No absences this month",
      dayCount: (n) => `${n} days`,
      studentWise: "{{student}}-wise Statistics",
      studentWiseHint: "Rate = (present + late − late penalty) ÷ counted days; leave follows the attendance policy",
      roll: "Roll",
      name: "Name",
      statsFailed: "Could not load {{student}}-wise statistics",
      noStats: "No statistics",
      policyLink: "Attendance policy",
    },
    policy: {
      title: "Attendance Policy",
      subtitle: "Percentage rules, edit window, late and leave handling, and alerts",
      loadFailed: "Could not load the policy",
      tryAgain: "Please try again.",
      retry: "Retry",
      saved: "Attendance policy saved",
      saveFailed: "Could not save the policy",
      readOnly: "You don't have permission to change the policy - view only.",
      unsaved: "You have unsaved changes",
      discard: "Discard",
      save: "Save",
      saving: "Saving...",
      rangeError: (min, max) => `Enter a whole number from ${min} to ${max}`,
      consecutiveError: "Enter 0 (off) or a number from 2 to 30",
      days: "days",
      edit: {
        title: "Edit window",
        hint: 'How many days back regular users can change attendance. Older dates need the "Edit attendance" permission.',
        label: "Editable for (days)",
        help: "0 = today only",
      },
      late: {
        title: "Late rule",
        hint: "Count every N late days as one absence.",
        label: "Late days = 1 absence",
        help: "0 = off (late counts as present)",
      },
      leave: {
        title: "Leave handling",
        hint: "How approved leave days count in the percentage.",
        excluded: "Excluded",
        excludedHint: "Leave days are removed from the total",
        present: "Count as present",
        presentHint: "Leave days count as attended",
        absent: "Count as absent",
        absentHint: "Leave days count as absent",
      },
      low: {
        title: "Low attendance threshold",
        hint: "Below this percentage a person is flagged as low attendance in reports and the dashboard.",
        label: "Threshold (%)",
        help: "0 - 100",
      },
      consecutive: {
        title: "Consecutive absence alert",
        hint: "When a {{student}} is absent this many working days in a row the guardian gets an SMS (if enabled in notification settings).",
        label: "Consecutive absent (days)",
        help: "0 = off, or 2 - 30",
      },
      payroll: {
        title: "Payroll deduction",
        hint: "Suggest a salary deduction for {{teacher}}/staff absent days (applied from the payroll page).",
      },
      calendar: {
        title: "Weekly off days & holidays",
        hint: "Off days are not taken and are not counted in percentages. Set them in device settings.",
        link: "Go to device settings",
      },
    },
  },
});
