export const STUDENT_REQUIRED_FIELDS = [
  "name_bn",
  "division_id",
  "class_id",
  "academic_year",
] as const;

// snake_case incoming key -> Prisma (camelCase) field name
export const STUDENT_FIELD_MAP: Record<string, string> = {
  name_bn: "nameBn",
  arabic_name: "arabicName",
  nid: "nid",
  gender: "gender",
  dob: "dob",
  age: "age",
  blood_group: "bloodGroup",
  residency_type: "residencyType",
  is_orphan: "isOrphan",
  division_id: "divisionId",
  class_id: "classId",
  academic_year: "academicYear",
  previous_class_id: "previousClassId",
  previous_institution: "previousInstitution",
  previous_result: "previousResult",
  admission_date: "admissionDate",
  father_name: "fatherName",
  father_arabic_name: "fatherArabicName",
  father_nid: "fatherNid",
  father_occupation: "fatherOccupation",
  mother_name: "motherName",
  mother_nid: "motherNid",
  mother_occupation: "motherOccupation",
  guardian_phone: "guardianPhone",
  guardian_phone_2: "guardianPhone2",
  alt_guardian_name: "altGuardianName",
  alt_guardian_relation: "altGuardianRelation",
  alt_guardian_address: "altGuardianAddress",
  alt_guardian_phone: "altGuardianPhone",
  division: "division",
  district: "district",
  thana: "thana",
  village: "village",
  image: "image",
};

export const STUDENT_NUMERIC_FIELDS = [
  "age",
  "division_id",
  "class_id",
  "previous_class_id",
  "residency_type",
  "is_orphan",
] as const;
