import { defineText } from "@madrasha/shared-ui/src/i18n";

/** UI text for the attendance dashboard and the payroll-attendance page. */
export const attendanceAnalyticsText = defineText({
  bn: {
    attendeeTypes: {
      STUDENT: "{{student}}",
      TEACHER: "{{teacher}}",
      STAFF: "কর্মচারী",
    },
    dashboard: {
      title: "উপস্থিতি ড্যাশবোর্ড",
      subtitle: "আজকের অবস্থা, হাজিরা বাকি থাকা {{class}} ও সতর্কতা এক নজরে - বিস্তারিত হিসাব, এডিট ও প্রিন্টের জন্য রিপোর্ট পেজ",
      fullReport: "পূর্ণ রিপোর্ট",
      pending: "হাজিরা নেওয়া হয়নি",
      pendingHint: (n: string) => `${n}টি {{class}}তে এই তারিখের হাজিরা এখনো নেওয়া হয়নি`,
      takeAttendance: "হাজিরা নিন",
      date: "তারিখ",
      refresh: "রিফ্রেশ",
      offDay: "বন্ধের দিন",
      weeklyOff: "সাপ্তাহিক ছুটি",
      holiday: "ছুটির দিন",
      loadFailed: "ড্যাশবোর্ড লোড করা যায়নি",
      tileSub: (present: string, total: string, unmarked: string) =>
        `${present} / ${total} উপস্থিত · ${unmarked} অচিহ্নিত`,
      present: "উপস্থিত",
      late: "দেরি",
      absent: "অনুপস্থিত",
      leave: "ছুটি",
      unmarked: "অচিহ্নিত",
      total: "মোট",
      rate: "হার",
      classWise: "{{class}}ভিত্তিক উপস্থিতি",
      class: "{{class}}",
      noClasses: "কোনো {{class}}র তথ্য নেই",
      openReport: "রিপোর্ট দেখুন",
      selectClassHint: "কোনো {{class}}তে ক্লিক করলে নিচের প্রবণতা ও তালিকা সেই {{class}}র জন্য দেখাবে",
      trend: "মাসিক প্রবণতা",
      month: "মাস",
      allClasses: "সব {{class}}",
      clearClass: "সব {{class}} দেখুন",
      noTrend: "এই মাসে কোনো উপস্থিতির তথ্য নেই",
      trendTooltip: (rate: string, present: string, total: string) => `হার ${rate}% · উপস্থিত ${present}/${total}`,
      lowAttendance: "কম উপস্থিতি",
      threshold: "সীমা (%)",
      from: "থেকে",
      to: "পর্যন্ত",
      lowEmpty: "সীমার নিচে কেউ নেই",
      lowCount: (n: string, threshold: string) => `${n} জন ${threshold}% এর নিচে`,
      showAll: (n: string) => `সব দেখুন (${n})`,
      showLess: "কম দেখুন",
      consecutive: "টানা অনুপস্থিত",
      consecutiveHint: "শেষ কয়েক কর্মদিবস ধরে টানা অনুপস্থিত {{student}}",
      consecutiveEmpty: "এখন কেউ টানা অনুপস্থিত নেই",
      streak: (n: string) => `${n} দিন`,
      since: (d: string) => `${d} থেকে`,
      minDays: "ন্যূনতম দিন",
      roll: "রোল",
      call: "কল করুন",
      sectionFailed: "লোড করা যায়নি",
    },
    payroll: {
      title: "বেতন ও উপস্থিতি",
      subtitle: "মাসিক উপস্থিতি থেকে কর্তনের পরামর্শ এবং বেতন রেকর্ডে প্রয়োগ",
      month: "মাস",
      type: "ধরন",
      load: "দেখুন",
      loadFailed: "তথ্য লোড করা যায়নি",
      workingDays: "কর্মদিবস",
      deductAbsentOn: "নীতিমালা: অনুপস্থিতির জন্য কর্তন চালু",
      deductAbsentOff: "নীতিমালা: অনুপস্থিতির জন্য স্বয়ংক্রিয় কর্তন বন্ধ - প্রয়োজন হলে নিজে লিখুন",
      empty: "এই মাসের কোনো তথ্য নেই",
      name: "নাম",
      salary: "বেতন",
      worked: "কর্মঘণ্টা",
      avgCheckIn: "গড় আগমন",
      present: "উপস্থিত",
      absent: "অনুপস্থিত",
      late: "দেরি",
      leave: "ছুটি",
      unmarked: "অচিহ্নিত",
      latePenalty: (n: string) => `দেরির জন্য ${n} দিন`,
      perDay: (v: string) => `দৈনিক ${v}`,
      suggested: "প্রস্তাবিত কর্তন",
      deduction: "কর্তন",
      reset: "প্রস্তাবিত মানে ফেরান",
      payroll: "বেতন রেকর্ড",
      noPayroll: "রেকর্ড নেই",
      payrollStatus: {
        PENDING: "অপেক্ষমাণ",
        PAID: "পরিশোধিত",
      } as Record<string, string>,
      currentDeduction: (v: string) => `বর্তমান কর্তন ${v}`,
      net: (v: string) => `নিট ${v}`,
      hours: (h: string, m: string) => `${h} ঘ ${m} মি`,
      totals: "মোট",
      apply: "বেতনে প্রয়োগ করুন",
      applyHint: "শুধু 'অপেক্ষমাণ' বেতন রেকর্ড থাকা {{teacher}}দের কর্তন হালনাগাদ হবে",
      staffNoApply: "কর্মচারীদের বেতন রেকর্ড এই পাতা থেকে হালনাগাদ হয় না - তালিকাটি শুধু তথ্যের জন্য",
      nothingToApply: "প্রয়োগ করার মতো কোনো অপেক্ষমাণ রেকর্ড নেই",
      confirmTitle: "বেতনে কর্তন প্রয়োগ",
      confirmMessage: (n: string, total: string) =>
        `${n} জন {{teacher}}র অপেক্ষমাণ বেতন রেকর্ডে মোট ${total} কর্তন বসানো হবে। নিট বেতন নতুন করে হিসাব হবে।`,
      confirm: "প্রয়োগ করুন",
      cancel: "বাতিল",
      applying: "প্রয়োগ হচ্ছে...",
      resultTitle: "ফলাফল",
      applied: (n: string) => `${n} জনের রেকর্ড হালনাগাদ হয়েছে`,
      skipped: (n: string) => `${n} জন বাদ পড়েছে`,
      skippedReason: "কারণ",
      skipReasons: {
        no_record: "এই মাসের বেতন রেকর্ড নেই",
        not_pending: "বেতন রেকর্ড অপেক্ষমাণ নয়",
        exceeds_salary: "কর্তন বেতনের চেয়ে বেশি",
      } as Record<string, string>,
      close: "বন্ধ করুন",
      noPermission: "বেতন রেকর্ডে প্রয়োগের অনুমতি আপনার নেই",
    },
  },
  en: {
    attendeeTypes: {
      STUDENT: "{{student}}",
      TEACHER: "{{teacher}}",
      STAFF: "Staff",
    },
    dashboard: {
      title: "Attendance dashboard",
      subtitle: "Today's status, {{class}}es still unmarked and alerts at a glance - use the report page for details, editing and printing",
      fullReport: "Full report",
      pending: "Attendance not taken",
      pendingHint: (n: string) => `${n} {{class}}(es) have no attendance for this date yet`,
      takeAttendance: "Take attendance",
      date: "Date",
      refresh: "Refresh",
      offDay: "Off day",
      weeklyOff: "Weekly off",
      holiday: "Holiday",
      loadFailed: "Could not load the dashboard",
      tileSub: (present: string, total: string, unmarked: string) =>
        `${present} / ${total} present · ${unmarked} unmarked`,
      present: "Present",
      late: "Late",
      absent: "Absent",
      leave: "Leave",
      unmarked: "Unmarked",
      total: "Total",
      rate: "Rate",
      classWise: "{{class}}-wise attendance",
      class: "{{class}}",
      noClasses: "No {{class}} data",
      openReport: "Open report",
      selectClassHint: "Click a {{class}} to focus the trend and lists below on it",
      trend: "Monthly trend",
      month: "Month",
      allClasses: "All {{class}}es",
      clearClass: "Show all {{class}}es",
      noTrend: "No attendance data this month",
      trendTooltip: (rate: string, present: string, total: string) => `Rate ${rate}% · present ${present}/${total}`,
      lowAttendance: "Low attendance",
      threshold: "Threshold (%)",
      from: "From",
      to: "To",
      lowEmpty: "Nobody is below the threshold",
      lowCount: (n: string, threshold: string) => `${n} below ${threshold}%`,
      showAll: (n: string) => `Show all (${n})`,
      showLess: "Show less",
      consecutive: "Consecutive absence",
      consecutiveHint: "{{student}}s absent for the last several working days in a row",
      consecutiveEmpty: "No one is on an absence streak",
      streak: (n: string) => `${n} days`,
      since: (d: string) => `since ${d}`,
      minDays: "Min. days",
      roll: "Roll",
      call: "Call",
      sectionFailed: "Could not load",
    },
    payroll: {
      title: "Payroll attendance",
      subtitle: "Suggested deductions from monthly attendance, applied to payroll records",
      month: "Month",
      type: "Type",
      load: "Show",
      loadFailed: "Could not load data",
      workingDays: "Working days",
      deductAbsentOn: "Policy: deduction for absence is on",
      deductAbsentOff: "Policy: automatic absence deduction is off - enter amounts manually if needed",
      empty: "No data for this month",
      name: "Name",
      salary: "Salary",
      worked: "Worked",
      avgCheckIn: "Avg. check-in",
      present: "Present",
      absent: "Absent",
      late: "Late",
      leave: "Leave",
      unmarked: "Unmarked",
      latePenalty: (n: string) => `${n} day(s) for lateness`,
      perDay: (v: string) => `${v} / day`,
      suggested: "Suggested deduction",
      deduction: "Deduction",
      reset: "Reset to suggested",
      payroll: "Payroll record",
      noPayroll: "No record",
      payrollStatus: {
        PENDING: "Pending",
        PAID: "Paid",
      } as Record<string, string>,
      currentDeduction: (v: string) => `current deduction ${v}`,
      net: (v: string) => `net ${v}`,
      hours: (h: string, m: string) => `${h}h ${m}m`,
      totals: "Total",
      apply: "Apply to payroll",
      applyHint: "Only {{teacher}}s with a PENDING payroll record are updated",
      staffNoApply: "Staff payroll isn't updated from this page - the list is for information",
      nothingToApply: "No pending payroll records to update",
      confirmTitle: "Apply deductions to payroll",
      confirmMessage: (n: string, total: string) =>
        `Deductions totalling ${total} will be set on the pending payroll of ${n} {{teacher}}(s). Net pay will be recalculated.`,
      confirm: "Apply",
      cancel: "Cancel",
      applying: "Applying...",
      resultTitle: "Result",
      applied: (n: string) => `${n} record(s) updated`,
      skipped: (n: string) => `${n} skipped`,
      skippedReason: "Reason",
      skipReasons: {
        no_record: "No payroll record for this month",
        not_pending: "Payroll record is not pending",
        exceeds_salary: "Deduction exceeds salary",
      } as Record<string, string>,
      close: "Close",
      noPermission: "You don't have permission to apply deductions to payroll",
    },
  },
});
