import { defineText } from "@madrasha/shared-ui/src/i18n";

export const billingText = defineText({
  bn: {
    pageTitle: "SMS/Email বিলিং",
    pageSubtitle:
      "SMS ও ইমেইল ক্রেডিট প্যাকেজ সম্পূর্ণ আলাদাভাবে পরিচালিত হয় — প্যাকেজ কিনুন, অনুরোধের অবস্থা ও ব্যবহারের ইতিহাস দেখুন",
    tabs: {
      packages: "প্যাকেজ কিনুন",
      requests: "ক্রয়ের অনুরোধ",
      history: "লেনদেন ও ব্যবহার",
    },
    email: "ইমেইল",
    allChannels: "সব চ্যানেল",
    transactions: "লেনদেন",
    usageHistory: "ব্যবহারের ইতিহাস",
    noTransactions: "কোনো লেনদেন নেই",
    noUsage: "কোনো ব্যবহার নেই",
    credit: "ক্রেডিট",
    balance: "ব্যালেন্স",
    creditUsed: "ক্রেডিট ব্যবহৃত",
    segments: "সেগমেন্ট",
    error: "ত্রুটি",
    txType: {
      PACKAGE_PURCHASE: "প্যাকেজ ক্রয়",
      RECHARGE: "রিচার্জ",
      RENEWAL: "নবায়ন",
      USAGE: "ব্যবহার",
      REFUND: "ফেরত",
      MANUAL_CREDIT: "ম্যানুয়াল ক্রেডিট",
      MANUAL_DEDUCTION: "ম্যানুয়াল কর্তন",
    },
    usageStatus: {
      PENDING: "প্রক্রিয়াধীন",
      SENT: "পাঠানো হয়েছে",
      DELIVERED: "ডেলিভার হয়েছে",
      FAILED: "ব্যর্থ",
      REJECTED: "বাতিল",
    },
    requestStatus: {
      PENDING: "অপেক্ষমাণ",
      APPROVED: "অনুমোদিত",
      REJECTED: "বাতিল",
    },
    // Credit notice
    packageInactive: (ch: string) => `${ch} প্যাকেজ সক্রিয় নেই — মেসেজ পাঠানো যাবে না, আগে প্যাকেজ কিনুন`,
    creditExhausted: (ch: string) => `আপনার ${ch} শেষ হয়ে গেছে — নতুন প্যাকেজ কিনুন`,
    creditRemaining: (n: string, ch: string) => `আপনার কাছে আছে: ${n} টি ${ch}`,
    smsRules:
      "শুধু ইংরেজি/সংখ্যা দিয়ে লিখলে ১৬০ অক্ষর পর্যন্ত = ১টি SMS, তারপর প্রতি ১৫৩ অক্ষরে আরেকটি SMS যোগ হয়। মেসেজে বাংলা অক্ষর, আরবি বা ইমোজি থাকলে ৭০ অক্ষর পর্যন্ত = ১টি SMS, তারপর প্রতি ৬৭ অক্ষরে আরেকটি SMS যোগ হয়।",
    language: "ভাষা",
    encodingUnicode: "বাংলা/বিশেষ",
    encodingGsm: "ইংরেজি",
    smsLength: "SMS Length",
    perSmsLength: "Per SMS Length",
    smsCount: "SMS Count",
    estimatedCost: "আনুমানিক খরচ:",
    // Packages
    noPackages: "কোনো প্যাকেজ পাওয়া যায়নি",
    recharge: "রিচার্জ",
    packageBadge: "প্যাকেজ",
    creditCount: (n: string, ch: string) => `${n} টি ${ch}`,
    validity: (n: string) => `${n} দিন মেয়াদ`,
    buy: "কিনুন",
    // Purchase request modal
    enterPaymentMethod: "পেমেন্ট মেথড লিখুন",
    requestSent: (ch: string) => `ক্রয়ের অনুরোধ পাঠানো হয়েছে — Super Admin অনুমোদন করলে ${ch} যোগ হবে`,
    requestFailed: "অনুরোধ পাঠাতে সমস্যা হয়েছে",
    requestTitle: "প্যাকেজ কেনার অনুরোধ",
    paymentMethod: "পেমেন্ট মেথড",
    paymentMethodPlaceholder: "যেমন: বিকাশ, নগদ, ব্যাংক ট্রান্সফার",
    transactionIdOptional: "ট্রানজেকশন আইডি (ঐচ্ছিক)",
    noteOptional: "নোট (ঐচ্ছিক)",
    sending: "পাঠানো হচ্ছে...",
    sendRequest: "অনুরোধ পাঠান",
    // Requests table
    noRequests: "কোনো অনুরোধ নেই",
    note: "নোট",
    review: "পর্যালোচনা",
    // Summary cards
    notActive: (ch: string) => `${ch} প্যাকেজ সক্রিয় নেই`,
    buyPackage: "প্যাকেজ কিনুন",
    lowCredit: (ch: string) => `${ch} কম আছে`,
    usedOfTotal: (used: string, total: string, ch: string) => `ব্যবহৃত হয়েছে ${used} / মোট ${total} টি ${ch}`,
    remaining: "অবশিষ্ট আছে",
    unitOf: (ch: string) => `টি ${ch}`,
    expiry: "মেয়াদ",
    buyMore: "আরও কিনুন",
  },
  en: {
    pageTitle: "SMS/Email Billing",
    pageSubtitle:
      "SMS and email credit packages are managed separately — buy packages, track request status and view usage history",
    tabs: {
      packages: "Buy Packages",
      requests: "Purchase Requests",
      history: "Transactions & Usage",
    },
    email: "Email",
    allChannels: "All channels",
    transactions: "Transactions",
    usageHistory: "Usage history",
    noTransactions: "No transactions",
    noUsage: "No usage",
    credit: "credits",
    balance: "Balance",
    creditUsed: "credits used",
    segments: "segments",
    error: "Error",
    txType: {
      PACKAGE_PURCHASE: "Package purchase",
      RECHARGE: "Recharge",
      RENEWAL: "Renewal",
      USAGE: "Usage",
      REFUND: "Refund",
      MANUAL_CREDIT: "Manual credit",
      MANUAL_DEDUCTION: "Manual deduction",
    },
    usageStatus: {
      PENDING: "Processing",
      SENT: "Sent",
      DELIVERED: "Delivered",
      FAILED: "Failed",
      REJECTED: "Rejected",
    },
    requestStatus: {
      PENDING: "Pending",
      APPROVED: "Approved",
      REJECTED: "Rejected",
    },
    packageInactive: (ch) => `No active ${ch} package — messages cannot be sent, buy a package first`,
    creditExhausted: (ch) => `Your ${ch} credit is used up — buy a new package`,
    creditRemaining: (n, ch) => `You have: ${n} ${ch}`,
    smsRules:
      "English/numbers only: up to 160 characters = 1 SMS, then one more SMS per 153 characters. With Bangla, Arabic or emoji: up to 70 characters = 1 SMS, then one more SMS per 67 characters.",
    language: "Language",
    encodingUnicode: "Unicode/Special",
    encodingGsm: "English",
    smsLength: "SMS Length",
    perSmsLength: "Per SMS Length",
    smsCount: "SMS Count",
    estimatedCost: "Estimated cost:",
    noPackages: "No packages found",
    recharge: "Recharge",
    packageBadge: "Package",
    creditCount: (n, ch) => `${n} ${ch}`,
    validity: (n) => `${n} days validity`,
    buy: "Buy",
    enterPaymentMethod: "Enter the payment method",
    requestSent: (ch) => `Purchase request sent — ${ch} credit will be added once Super Admin approves`,
    requestFailed: "Could not send the request",
    requestTitle: "Package Purchase Request",
    paymentMethod: "Payment method",
    paymentMethodPlaceholder: "e.g. bKash, Nagad, bank transfer",
    transactionIdOptional: "Transaction ID (optional)",
    noteOptional: "Note (optional)",
    sending: "Sending...",
    sendRequest: "Send Request",
    noRequests: "No requests",
    note: "Note",
    review: "Review",
    notActive: (ch) => `No active ${ch} package`,
    buyPackage: "Buy Package",
    lowCredit: (ch) => `${ch} running low`,
    usedOfTotal: (used, total, ch) => `Used ${used} of ${total} ${ch}`,
    remaining: "Remaining",
    unitOf: (ch) => ch,
    expiry: "Expires",
    buyMore: "Buy more",
  },
  ar: {
    pageTitle: "فوترة الرسائل والبريد",
    pageSubtitle:
      "تُدار باقات رصيد الرسائل القصيرة والبريد الإلكتروني بشكل منفصل — اشترِ الباقات، وتابع حالة الطلبات، واطّلع على سجل الاستخدام",
    tabs: {
      packages: "شراء الباقات",
      requests: "طلبات الشراء",
      history: "المعاملات والاستخدام",
    },
    email: "البريد الإلكتروني",
    allChannels: "كل القنوات",
    transactions: "المعاملات",
    usageHistory: "سجل الاستخدام",
    noTransactions: "لا توجد معاملات",
    noUsage: "لا يوجد استخدام",
    credit: "رصيد",
    balance: "الرصيد",
    creditUsed: "رصيد مستخدم",
    segments: "أجزاء",
    error: "خطأ",
    txType: {
      PACKAGE_PURCHASE: "شراء باقة",
      RECHARGE: "إعادة شحن",
      RENEWAL: "تجديد",
      USAGE: "استخدام",
      REFUND: "استرداد",
      MANUAL_CREDIT: "إضافة يدوية",
      MANUAL_DEDUCTION: "خصم يدوي",
    },
    usageStatus: {
      PENDING: "قيد المعالجة",
      SENT: "تم الإرسال",
      DELIVERED: "تم التسليم",
      FAILED: "فشل",
      REJECTED: "مرفوض",
    },
    requestStatus: {
      PENDING: "قيد الانتظار",
      APPROVED: "مقبول",
      REJECTED: "مرفوض",
    },
    packageInactive: (ch) => `لا توجد باقة ${ch} نشطة — لا يمكن إرسال الرسائل، اشترِ باقة أولًا`,
    creditExhausted: (ch) => `نفد رصيد ${ch} — اشترِ باقة جديدة`,
    creditRemaining: (n, ch) => `المتوفر لديك: ${n} ${ch}`,
    smsRules:
      "بالأحرف الإنجليزية/الأرقام فقط: حتى 160 حرفًا = رسالة واحدة، ثم رسالة إضافية لكل 153 حرفًا. مع البنغالية أو العربية أو الرموز التعبيرية: حتى 70 حرفًا = رسالة واحدة، ثم رسالة إضافية لكل 67 حرفًا.",
    language: "اللغة",
    encodingUnicode: "يونيكود/خاص",
    encodingGsm: "إنجليزي",
    smsLength: "طول الرسالة",
    perSmsLength: "الطول لكل رسالة",
    smsCount: "عدد الرسائل",
    estimatedCost: "التكلفة التقديرية:",
    noPackages: "لم يتم العثور على باقات",
    recharge: "إعادة شحن",
    packageBadge: "باقة",
    creditCount: (n, ch) => `${n} ${ch}`,
    validity: (n) => `صلاحية ${n} يومًا`,
    buy: "شراء",
    enterPaymentMethod: "أدخل طريقة الدفع",
    requestSent: (ch) => `تم إرسال طلب الشراء — سيُضاف رصيد ${ch} بعد موافقة المشرف العام`,
    requestFailed: "تعذّر إرسال الطلب",
    requestTitle: "طلب شراء باقة",
    paymentMethod: "طريقة الدفع",
    paymentMethodPlaceholder: "مثل: بيكاش، نقد، تحويل بنكي",
    transactionIdOptional: "رقم المعاملة (اختياري)",
    noteOptional: "ملاحظة (اختياري)",
    sending: "جارٍ الإرسال...",
    sendRequest: "إرسال الطلب",
    noRequests: "لا توجد طلبات",
    note: "ملاحظة",
    review: "المراجعة",
    notActive: (ch) => `لا توجد باقة ${ch} نشطة`,
    buyPackage: "شراء باقة",
    lowCredit: (ch) => `رصيد ${ch} منخفض`,
    usedOfTotal: (used, total, ch) => `المستخدم ${used} من أصل ${total} ${ch}`,
    remaining: "المتبقي",
    unitOf: (ch) => ch,
    expiry: "تاريخ الانتهاء",
    buyMore: "شراء المزيد",
  },
});
