import { defineText } from "@madrasha/shared-ui/src/i18n";

type Card = { title: string; desc: string };

/** Platform (QMS) marketing landing page - not a tenant site, so no
 * institution placeholders here: it always talks about madrasas. */
export const landingText = defineText({
  bn: {
    nav: {
      about: "পরিচিতি",
      why: "কেন QMS",
      gettingStarted: "ব্যবহার গাইড",
      service: "সেবা নিন",
      contact: "যোগাযোগ",
    } as Record<string, string>,
    goToAdmin: "অ্যাডমিন প্যানেলে যান",
    closeMenu: "মেনু বন্ধ করুন",
    openMenu: "মেনু খুলুন",
    heroLine1: "কওমি মাদ্রাসা পরিচালনার",
    heroLine2: "সম্পূর্ণ ডিজিটাল সমাধান",
    heroBody:
      "QMS (Qawmi Madrasa Management System) একটি আধুনিক সফটওয়্যার, যা দিয়ে ছাত্র, শিক্ষক, ভর্তি, হাজিরা, পরীক্ষা-ফলাফল ও হিসাব — সবকিছু এক জায়গা থেকে সহজে পরিচালনা করা যায়।",
    getService: "সেবাটি নিন",
    learnMore: "আরও জানুন",
    badges: ["নিরাপদ ও নির্ভরযোগ্য ডেটা", "বাংলা, ইংরেজি ও আরবি ইন্টারফেস", "মোবাইল ও ডেস্কটপ সাপোর্ট"],
    mockModules: ["Students", "Teachers", "Admission", "Attendance", "Examination", "Accounts"],
    resultReady: "ফলাফল প্রস্তুত",
    oneClickReport: "এক ক্লিকে রিপোর্ট",
    aboutEyebrow: "About QMS",
    aboutTitle: "মাদ্রাসার সকল কার্যক্রম একটি প্ল্যাটফর্মে",
    aboutBody:
      "কওমি মাদ্রাসার দৈনন্দিন প্রশাসনিক ও একাডেমিক কাজগুলো সহজ ও গোছালো করতে QMS তৈরি করা হয়েছে। প্রতিটি মডিউল বাস্তব প্রয়োজন বিবেচনা করে ডিজাইন করা।",
    features: [
      { title: "Student Management", desc: "শিক্ষার্থীদের তথ্য, প্রোফাইল ও একাডেমিক রেকর্ড সহজে সংরক্ষণ ও পরিচালনা করুন।" },
      { title: "Teacher Management", desc: "শিক্ষকদের নিয়োগ, প্রোফাইল ও দায়িত্ব বণ্টন এক জায়গা থেকে নিয়ন্ত্রণ করুন।" },
      { title: "Admission", desc: "নতুন শিক্ষার্থী ভর্তি প্রক্রিয়া দ্রুত, নির্ভুল ও ডিজিটালভাবে সম্পন্ন করুন।" },
      { title: "Attendance", desc: "দৈনিক হাজিরা রেকর্ড রাখুন এবং উপস্থিতির প্রবণতা সহজে বিশ্লেষণ করুন।" },
      { title: "Examination & Result", desc: "পরীক্ষা পরিচালনা, নম্বর এন্ট্রি ও ফলাফল প্রকাশ স্বয়ংক্রিয়ভাবে করুন।" },
      { title: "Accounts", desc: "আয়-ব্যয়, ফান্ড ও আর্থিক হিসাব স্বচ্ছভাবে ট্র্যাক করুন।" },
      { title: "Reports", desc: "একাডেমিক, আর্থিক ও প্রশাসনিক রিপোর্ট মুহূর্তেই তৈরি ও প্রিন্ট করুন।" },
      { title: "SMS / Notification", desc: "অভিভাবক ও শিক্ষকদের কাছে গুরুত্বপূর্ণ তথ্য দ্রুত পৌঁছে দিন।" },
      { title: "Settings ও অন্যান্য", desc: "মাদ্রাসার নিজস্ব প্রয়োজন অনুযায়ী সিস্টেম কাস্টমাইজ ও নিয়ন্ত্রণ করুন।" },
    ] as Card[],
    whyEyebrow: "Why Choose QMS",
    whyTitle: "কেন আপনার মাদ্রাসার জন্য QMS",
    why: [
      { title: "সময় সাশ্রয়", desc: "ম্যানুয়াল রেজিস্টার ও হিসাবের ঝামেলা ছাড়াই কাজ হবে দ্রুত ও সহজ।" },
      { title: "নির্ভুল তথ্য সংরক্ষণ", desc: "প্রতিটি তথ্য নির্ভুলভাবে ডিজিটালি সংরক্ষিত থাকে, ভুলের সম্ভাবনা কমে যায়।" },
      { title: "সহজ রিপোর্ট", desc: "জটিল হিসাব-নিকাশ এক ক্লিকে রিপোর্ট আকারে দেখুন ও প্রিন্ট করুন।" },
      { title: "নিরাপদ ডেটা", desc: "মাদ্রাসার তথ্য সুরক্ষিত সার্ভারে নিরাপদে সংরক্ষিত থাকে।" },
      { title: "Modern Dashboard", desc: "প্রতিদিনের কার্যক্রম এক নজরে দেখার জন্য আধুনিক ড্যাশবোর্ড।" },
      { title: "Multi-user Support", desc: "প্রশাসন, শিক্ষক ও কর্মচারীরা একসাথে নিজ নিজ দায়িত্বে কাজ করতে পারবেন।" },
    ] as Card[],
    startEyebrow: "Getting Started",
    startTitle: "কীভাবে ব্যবহার শুরু করবেন",
    startBody: "মাত্র কয়েকটি ধাপে আপনার মাদ্রাসা QMS ব্যবহার শুরু করতে পারবে।",
    step: (n: string) => `ধাপ ${n}`,
    steps: [
      { title: "অ্যাকাউন্ট তৈরি", desc: "আপনার মাদ্রাসার জন্য একটি QMS অ্যাকাউন্ট খুলুন।" },
      { title: "মাদ্রাসার তথ্য সেটআপ", desc: "মাদ্রাসার নাম, ঠিকানা, লোগো ও প্রয়োজনীয় তথ্য যুক্ত করুন।" },
      { title: "শিক্ষক ও শিক্ষার্থী যুক্ত করা", desc: "শিক্ষক ও শিক্ষার্থীদের প্রোফাইল সিস্টেমে যুক্ত করুন।" },
      { title: "ক্লাস, বিভাগ ও বিষয় সেটআপ", desc: "মাদ্রাসার একাডেমিক কাঠামো অনুযায়ী ক্লাস, বিভাগ ও বিষয় নির্ধারণ করুন।" },
      { title: "দৈনন্দিন ব্যবহার", desc: "হাজিরা, পরীক্ষা, হিসাব ও রিপোর্ট — প্রতিদিনের কাজে QMS ব্যবহার শুরু করুন।" },
    ] as Card[],
    serviceEyebrow: "How to Get This Service",
    serviceTitle: "যেভাবে সেবাটি নিতে পারবেন",
    serviceBody: "Hikmah IT-এর সহায়তায় সম্পূর্ণ ঝামেলাহীনভাবে QMS চালু করুন।",
    service: [
      { title: "যোগাযোগ", desc: "ফোন বা ইমেইলে আমাদের সাথে যোগাযোগ করুন।" },
      { title: "ডেমো", desc: "সিস্টেমের একটি লাইভ ডেমো দেখুন।" },
      { title: "সেটআপ", desc: "আপনার মাদ্রাসার জন্য সিস্টেম কনফিগার করা হবে।" },
      { title: "ট্রেনিং", desc: "ব্যবহারকারীদের প্রয়োজনীয় প্রশিক্ষণ দেওয়া হবে।" },
      { title: "লাইভ চালু", desc: "সম্পূর্ণ প্রস্তুত হয়ে গেলে সিস্টেম লাইভ চালু হবে।" },
    ] as Card[],
    contactNow: "এখনই যোগাযোগ করুন",
    contactEyebrow: "Contact Us",
    contactBody: "আপনার মাদ্রাসার জন্য QMS চালু করতে আজই যোগাযোগ করুন। আমরা আছি প্রতিটি ধাপে পাশে।",
    phone: "ফোন",
    email: "ইমেইল",
    address: "ঠিকানা",
    addressValue: "জামালপুর, ঢাকা, বাংলাদেশ",
    poweredBy: "— পরিচালনায়",
    allRightsReserved: "সর্বস্বত্ব সংরক্ষিত।",
    // ContactFab
    call: "কল করুন",
    closeContactOptions: "যোগাযোগ অপশন বন্ধ করুন",
    contactUs: "যোগাযোগ করুন",
    // DomainNotConnected
    domainNotConfigured: "এই ডোমেইনে কোনো সাইট কনফিগার করা নেই",
    domainNotLinked: "এই ডোমেইনটি এখনো কোনো প্রতিষ্ঠানের সাথে সংযুক্ত করা হয়নি।",
  },
  en: {
    nav: {
      about: "About",
      why: "Why QMS",
      gettingStarted: "Guide",
      service: "Get Started",
      contact: "Contact",
    },
    goToAdmin: "Go to Admin Panel",
    closeMenu: "Close menu",
    openMenu: "Open menu",
    heroLine1: "A complete digital solution",
    heroLine2: "for running a Qawmi madrasa",
    heroBody:
      "QMS (Qawmi Madrasa Management System) is modern software for managing students, teachers, admission, attendance, exams & results and accounts — all easily from one place.",
    getService: "Get the Service",
    learnMore: "Learn More",
    badges: ["Secure and reliable data", "Bangla, English & Arabic interface", "Mobile and desktop support"],
    mockModules: ["Students", "Teachers", "Admission", "Attendance", "Examination", "Accounts"],
    resultReady: "Results ready",
    oneClickReport: "One-click reports",
    aboutEyebrow: "About QMS",
    aboutTitle: "Every madrasa activity on one platform",
    aboutBody:
      "QMS was built to make the daily administrative and academic work of Qawmi madrasas simple and organized. Every module is designed around real needs.",
    features: [
      { title: "Student Management", desc: "Easily store and manage student information, profiles and academic records." },
      { title: "Teacher Management", desc: "Handle teacher recruitment, profiles and duty assignments from one place." },
      { title: "Admission", desc: "Complete new student admissions quickly, accurately and digitally." },
      { title: "Attendance", desc: "Keep daily attendance records and easily analyze attendance trends." },
      { title: "Examination & Result", desc: "Run exams, enter marks and publish results automatically." },
      { title: "Accounts", desc: "Track income, expenses, funds and finances transparently." },
      { title: "Reports", desc: "Generate and print academic, financial and administrative reports instantly." },
      { title: "SMS / Notification", desc: "Deliver important information to guardians and teachers quickly." },
      { title: "Settings & More", desc: "Customize and control the system to fit your madrasa's own needs." },
    ],
    whyEyebrow: "Why Choose QMS",
    whyTitle: "Why QMS for your madrasa",
    why: [
      { title: "Saves Time", desc: "Work becomes fast and easy without the hassle of manual registers and ledgers." },
      { title: "Accurate Records", desc: "Every record is stored digitally and accurately, reducing the chance of errors." },
      { title: "Easy Reports", desc: "View and print complex accounts as reports with a single click." },
      { title: "Secure Data", desc: "Your madrasa's data is kept safe on secure servers." },
      { title: "Modern Dashboard", desc: "A modern dashboard to see daily activity at a glance." },
      { title: "Multi-user Support", desc: "Administration, teachers and staff can work together, each in their own role." },
    ],
    startEyebrow: "Getting Started",
    startTitle: "How to get started",
    startBody: "Your madrasa can start using QMS in just a few steps.",
    step: (n) => `Step ${n}`,
    steps: [
      { title: "Create an account", desc: "Open a QMS account for your madrasa." },
      { title: "Set up madrasa details", desc: "Add the madrasa's name, address, logo and other necessary details." },
      { title: "Add teachers and students", desc: "Add teacher and student profiles to the system." },
      { title: "Set up classes, divisions and subjects", desc: "Define classes, divisions and subjects according to your madrasa's academic structure." },
      { title: "Daily use", desc: "Attendance, exams, accounts and reports — start using QMS for your daily work." },
    ],
    serviceEyebrow: "How to Get This Service",
    serviceTitle: "How you can get the service",
    serviceBody: "Launch QMS completely hassle-free with the help of Hikmah IT.",
    service: [
      { title: "Contact", desc: "Get in touch with us by phone or email." },
      { title: "Demo", desc: "See a live demo of the system." },
      { title: "Setup", desc: "The system will be configured for your madrasa." },
      { title: "Training", desc: "Users will receive the necessary training." },
      { title: "Go Live", desc: "Once everything is ready, the system goes live." },
    ],
    contactNow: "Contact Us Now",
    contactEyebrow: "Contact Us",
    contactBody: "Contact us today to launch QMS for your madrasa. We are with you at every step.",
    phone: "Phone",
    email: "Email",
    address: "Address",
    addressValue: "Jamalpur, Dhaka, Bangladesh",
    poweredBy: "— Powered by",
    allRightsReserved: "All rights reserved.",
    call: "Call",
    closeContactOptions: "Close contact options",
    contactUs: "Contact us",
    domainNotConfigured: "No site is configured for this domain",
    domainNotLinked: "This domain has not been linked to any institution yet.",
  },
});
