import { defineText } from "@madrasha/shared-ui/src/i18n";

export const dashboardText = defineText({
  bn: {
    totalStudents: "মোট ছাত্র",
    maleStudents: "ছাত্র (ছেলে)",
    femaleStudents: "ছাত্রী (মেয়ে)",
    totalTeachers: "মোট শিক্ষক",
    totalIncome: "মোট আয়",
    totalExpense: "মোট ব্যয়",
    currentBalance: "বর্তমান ব্যালেন্স",
    todayIncomeExpense: "আজকের আয়/ব্যয়",
    expenseSub: (amount: string) => `ব্যয়: ${amount}`,
    onlineIncome: "অনলাইন আয়",
    ofTotalIncome: (pct: string) => `মোট আয়ের ${pct}%`,
    offlineIncome: "অফলাইন আয় (নগদ)",
    unassigned: "নির্ধারিত নয়",
    boys: "ছেলে",
    girls: "মেয়ে",
    online: "অনলাইন",
    offline: "অফলাইন",
    quickActions: "দ্রুত কাজ",
    quickActionsSub: "প্রায়ই ব্যবহৃত কাজ",
    viewWebsite: "ওয়েবসাইট দেখুন",
    incomeEntry: "আয় এন্ট্রি",
    expenseEntry: "ব্যয় এন্ট্রি",
    newAdmission: "নতুন ভর্তি",
    todayAttendance: "আজকের হাজিরা %",
    attendanceTaken: (n: string) => `${n} জনের হাজিরা নেওয়া হয়েছে`,
    pendingAdmissions: "অনুমোদনের অপেক্ষায় ভর্তি",
    overdueFees: "বকেয়া ফি",
    overdueStudents: (n: string) => `${n} জন শিক্ষার্থীর বকেয়া`,
    upcomingExams: "আসন্ন পরীক্ষা",
    upcomingExamsSub: "রুটিন অনুযায়ী আসন্ন পরীক্ষাসমূহ",
    noUpcomingExams: "আসন্ন কোনো পরীক্ষা নেই",
    incomeExpenseTrend: "আয় ও ব্যয়ের প্রবণতা",
    last12Months: "গত ১২ মাস",
    income: "আয়",
    expense: "ব্যয়",
    attendanceRate: "উপস্থিতির হার",
    attendanceRateSub: "ছাত্রদের মাসিক গড় উপস্থিতি",
    attendancePct: "উপস্থিতি %",
    fundDistribution: "ফান্ডভিত্তিক বণ্টন",
    fundDistributionSub: "মোট ব্যালেন্সের অনুপাত",
    fundBalance: "ফান্ড ব্যালেন্স",
    viewReport: "রিপোর্ট দেখুন",
    genderRatio: "ছাত্র-ছাত্রী অনুপাত",
    genderRatioSub: "লিঙ্গভিত্তিক বণ্টন",
    onlineVsOffline: "অনলাইন বনাম অফলাইন আয়-ব্যয়",
    onlineVsOfflineSub: "পেমেন্ট মাধ্যম অনুযায়ী হিসাব",
    paymentMethods: "লেনদেনের মাধ্যম",
    paymentMethodsSub: "মোট লেনদেনের ভাগ (আয় + ব্যয়)",
    importantLinks: "গুরুত্বপূর্ণ লিংক",
    importantLinksSub: "বোর্ড ও কর্তৃপক্ষ",
    noLinks: "কোনো লিংক যোগ করা হয়নি",
    recentTransactions: "সাম্প্রতিক লেনদেন",
    viewAll: "সব দেখুন",
    noTransactions: "কোনো লেনদেন নেই",
    overdueList: "বকেয়া ফি তালিকা",
    totalAmount: (amount: string) => `মোট ${amount}`,
    noOverdue: "কোনো বকেয়া নেই",
    overdueInvoices: (n: string) => `${n} টি বকেয়া ফি`,
  },
  en: {
    totalStudents: "Total Students",
    maleStudents: "Students (Boys)",
    femaleStudents: "Students (Girls)",
    totalTeachers: "Total Teachers",
    totalIncome: "Total Income",
    totalExpense: "Total Expense",
    currentBalance: "Current Balance",
    todayIncomeExpense: "Today's Income/Expense",
    expenseSub: (amount) => `Expense: ${amount}`,
    onlineIncome: "Online Income",
    ofTotalIncome: (pct) => `${pct}% of total income`,
    offlineIncome: "Offline Income (Cash)",
    unassigned: "Unassigned",
    boys: "Boys",
    girls: "Girls",
    online: "Online",
    offline: "Offline",
    quickActions: "Quick Actions",
    quickActionsSub: "Frequently used tasks",
    viewWebsite: "View Website",
    incomeEntry: "Income Entry",
    expenseEntry: "Expense Entry",
    newAdmission: "New Admission",
    todayAttendance: "Today's Attendance %",
    attendanceTaken: (n) => `Attendance taken for ${n}`,
    pendingAdmissions: "Admissions Awaiting Approval",
    overdueFees: "Overdue Fees",
    overdueStudents: (n) => `${n} students with dues`,
    upcomingExams: "Upcoming Exams",
    upcomingExamsSub: "Upcoming exams from the routine",
    noUpcomingExams: "No upcoming exams",
    incomeExpenseTrend: "Income & Expense Trend",
    last12Months: "Last 12 months",
    income: "Income",
    expense: "Expense",
    attendanceRate: "Attendance Rate",
    attendanceRateSub: "Monthly average student attendance",
    attendancePct: "Attendance %",
    fundDistribution: "Fund Distribution",
    fundDistributionSub: "Share of total balance",
    fundBalance: "Fund Balance",
    viewReport: "View Report",
    genderRatio: "Boys-Girls Ratio",
    genderRatioSub: "Distribution by gender",
    onlineVsOffline: "Online vs Offline Income & Expense",
    onlineVsOfflineSub: "By payment method",
    paymentMethods: "Payment Methods",
    paymentMethodsSub: "Share of all transactions (income + expense)",
    importantLinks: "Important Links",
    importantLinksSub: "Boards & authorities",
    noLinks: "No links added",
    recentTransactions: "Recent Transactions",
    viewAll: "View All",
    noTransactions: "No transactions",
    overdueList: "Overdue Fee List",
    totalAmount: (amount) => `Total ${amount}`,
    noOverdue: "No overdue fees",
    overdueInvoices: (n) => `${n} overdue fees`,
  },
});
