import { defineText } from "@madrasha/shared-ui/src/i18n";

/** Guardian portal (layout + pages). Status keys (PRESENT, PAID...) are the
 * backend's enum values - only their labels are translated here. */
export const guardianText = defineText({
  bn: {
    // Layout
    nav: {
      dashboard: "ড্যাশবোর্ড",
      profile: "প্রোফাইল",
      attendance: "হাজিরা",
      results: "ফলাফল",
      "exam-routine": "পরীক্ষার সময়সূচি",
      fees: "ফি",
      notices: "নোটিশ",
    } as Record<string, string>,
    home: "হোম",
    marksheet: "মার্কশিট",
    panelTitle: "অভিভাবক প্যানেল",
    selectChild: "সন্তান নির্বাচন করুন",
    logout: "লগআউট",
    // Common
    noChild: "কোনো সন্তান যুক্ত নেই",
    noChildHint: "এই লগইনের সাথে কোনো {{student}} যুক্ত পাওয়া যায়নি।",
    roll: "রোল",
    regShort: "রেজি.",
    noRecords: "কোনো রেকর্ড নেই",
    noData: "কোনো তথ্য নেই",
    // Login
    loginTitle: "অভিভাবক লগইন",
    tryAgain: "আবার চেষ্টা করুন",
    institutionLabel: "{{institution}}:",
    mobileNumber: "মোবাইল নম্বর",
    password: "পাসওয়ার্ড",
    showPassword: "পাসওয়ার্ড দেখান",
    hidePassword: "পাসওয়ার্ড লুকান",
    firstLoginHint: "প্রথমবার লগইন করছেন? ডিফল্ট পাসওয়ার্ড আপনার মোবাইল নম্বরের শেষ ৪ ডিজিট।",
    loggingIn: "লগইন হচ্ছে...",
    login: "লগইন",
    // Change password
    passwordTooShort: "পাসওয়ার্ড কমপক্ষে ৪ ক্যারেক্টার হতে হবে",
    passwordMismatch: "দুটি পাসওয়ার্ড মিলছে না",
    passwordChanged: "পাসওয়ার্ড পরিবর্তন হয়েছে",
    setNewPassword: "নতুন পাসওয়ার্ড সেট করুন",
    mustChangeHint: "নিরাপত্তার জন্য প্রথমবার লগইনে পাসওয়ার্ড পরিবর্তন করা আবশ্যক।",
    newPassword: "নতুন পাসওয়ার্ড",
    retypePassword: "পাসওয়ার্ড আবার লিখুন",
    saving: "সংরক্ষণ হচ্ছে...",
    savePassword: "পাসওয়ার্ড সংরক্ষণ করুন",
    // Dashboard / overview
    dashboard: "ড্যাশবোর্ড",
    monthAttendancePct: "এই মাসের হাজিরা %",
    publishedResults: "প্রকাশিত ফলাফল",
    upcomingExams: "আসন্ন পরীক্ষা",
    dueFees: "বকেয়া ফি",
    libraryRecords: "লাইব্রেরি রেকর্ড",
    // Notices
    notices: "নোটিশ",
    noticesSubtitle: "সাম্প্রতিক নোটিশসমূহ",
    noNotices: "কোনো নোটিশ নেই",
    // Exam routine
    examRoutine: "পরীক্ষার সময়সূচি",
    examRoutineSubtitle: "সন্তানের {{class}}র আসন্ন ও চলমান পরীক্ষার সময়সূচি",
    noRoutine: "কোনো পরীক্ষার সময়সূচি পাওয়া যায়নি",
    noRoutineHint: "সময়সূচি প্রকাশিত হলে এখানে দেখা যাবে।",
    exam: "পরীক্ষা",
    subject: "{{subject}}",
    date: "তারিখ",
    time: "সময়",
    roomNo: "কক্ষ নম্বর",
    // Results
    results: "ফলাফল",
    resultsSubtitle: "প্রকাশিত পরীক্ষার ফলাফল",
    noResults: "এখনো কোনো ফলাফল প্রকাশিত হয়নি",
    noResultsHint: "পরীক্ষার ফলাফল প্রকাশিত হলে এখানে দেখা যাবে।",
    class: "{{class}}",
    totalMarks: "মোট নম্বর",
    average: "গড়",
    grade: "গ্রেড",
    rank: "মেধাক্রম",
    viewMarksheet: "মার্কশিট দেখুন",
    // Attendance
    attendance: "হাজিরা",
    attendanceSubtitle: "এই মাসের হাজিরার সারাংশ ও সাম্প্রতিক রেকর্ড",
    attendanceRate: "হাজিরার হার",
    recentRecords: "সাম্প্রতিক রেকর্ড",
    status: "অবস্থা",
    attendanceStatus: {
      PRESENT: "উপস্থিত",
      ABSENT: "অনুপস্থিত",
      LATE: "বিলম্বে",
      LEAVE: "ছুটি",
    } as Record<string, string>,
    // Fees
    fees: "ফি",
    feesSubtitle: "ইনভয়েস ও বকেয়ার অবস্থা",
    totalBilled: "মোট বিল",
    paid: "পরিশোধিত",
    due: "বকেয়া",
    feeHead: "খাত",
    dueDate: "নির্ধারিত তারিখ",
    amount: "পরিমাণ",
    noInvoices: "কোনো ইনভয়েস নেই",
    invoices: "ইনভয়েস",
    invoiceStatus: {
      UNPAID: "বকেয়া",
      PARTIALLY_PAID: "আংশিক পরিশোধিত",
      PAID: "পরিশোধিত",
      OVERDUE: "মেয়াদোত্তীর্ণ",
      WAIVED: "মওকুফ",
    } as Record<string, string>,
    onlinePaymentSoon:
      "অনলাইনে ফি পরিশোধের সুবিধা শীঘ্রই আসছে। বর্তমানে ফি পরিশোধ করতে {{institution}} অফিসে যোগাযোগ করুন।",
    // Profile
    childProfile: "সন্তানের প্রোফাইল",
    tabs: {
      overview: "ওভারভিউ",
      academic: "একাডেমিক",
      attendance: "উপস্থিতি",
      financial: "আর্থিক",
      library: "লাইব্রেরি",
    } as Record<string, string>,
    promotionHistory: "পদোন্নতির ইতিহাস",
    session: "{{session}}",
    rollChange: "রোল পরিবর্তন",
    promotionStatus: {
      PROMOTED: "উন্নীত",
      RETAINED: "অবস্থান",
      TRANSFERRED: "স্থানান্তরিত",
    } as Record<string, string>,
    bookName: "বইয়ের নাম",
    borrowedDate: "নেওয়ার তারিখ",
    returnDate: "ফেরতের তারিখ",
    fine: "জরিমানা",
    libraryStatus: {
      BORROWED: "ধারে নেওয়া আছে",
      RETURNED: "ফেরত দেওয়া হয়েছে",
      LOST: "হারিয়ে গেছে",
    } as Record<string, string>,
    // Marksheet (screen chrome)
    resultNotFound: "ফলাফল পাওয়া যায়নি",
    resultNotFoundHint: "এই মার্কশিট প্রকাশিত নয় অথবা আপনার সন্তানের সাথে সম্পর্কিত নয়।",
    backToResults: "ফলাফল তালিকায় ফিরে যান",
    back: "ফিরে যান",
    print: "প্রিন্ট করুন",
    // Marksheet (printable body - institution default language)
    ms: {
      title: "মার্কশিট",
      classLabel: "{{class}}ঃ",
      yearSuffix: "ইং",
      rollNo: "রোল নম্বর:",
      registrationNo: "রেজিস্ট্রেশন নম্বর:",
      dob: "জন্ম তারিখ:",
      studentName: "{{student}}র নাম:",
      fatherName: "পিতার নাম:",
      resultDivision: "ফলাফল বিভাগ:",
      grade: "গ্রেড:",
      rank: "মেধাস্থান:",
      status: "অবস্থা:",
      serial: "ক্রম",
      subjectName: "{{subject}}ের নাম",
      obtained: "প্রাপ্ত নম্বর",
      fullMarks: "পূর্ণমান",
      absentShort: "অনু",
      totalMarks: "মোট নম্বর",
      averageMarks: "গড় নম্বর",
      resultStatus: {
        PASS: "পাশ",
        FAIL: "ফেল",
        ABSENT: "অনুপস্থিত",
      } as Record<string, string>,
    },
  },
  en: {
    nav: {
      dashboard: "Dashboard",
      profile: "Profile",
      attendance: "Attendance",
      results: "Results",
      "exam-routine": "Exam Schedule",
      fees: "Fees",
      notices: "Notices",
    },
    home: "Home",
    marksheet: "Marksheet",
    panelTitle: "Guardian Panel",
    selectChild: "Select child",
    logout: "Logout",
    noChild: "No child linked",
    noChildHint: "No {{student}} was found linked to this login.",
    roll: "Roll",
    regShort: "Reg.",
    noRecords: "No records",
    noData: "No data",
    loginTitle: "Guardian Login",
    tryAgain: "Try again",
    institutionLabel: "{{institution}}:",
    mobileNumber: "Mobile number",
    password: "Password",
    showPassword: "Show password",
    hidePassword: "Hide password",
    firstLoginHint: "Logging in for the first time? The default password is the last 4 digits of your mobile number.",
    loggingIn: "Logging in...",
    login: "Login",
    passwordTooShort: "Password must be at least 4 characters",
    passwordMismatch: "The two passwords do not match",
    passwordChanged: "Password changed",
    setNewPassword: "Set a New Password",
    mustChangeHint: "For security, you must change your password on first login.",
    newPassword: "New password",
    retypePassword: "Re-enter password",
    saving: "Saving...",
    savePassword: "Save Password",
    dashboard: "Dashboard",
    monthAttendancePct: "This month's attendance %",
    publishedResults: "Published results",
    upcomingExams: "Upcoming exams",
    dueFees: "Due fees",
    libraryRecords: "Library records",
    notices: "Notices",
    noticesSubtitle: "Recent notices from the {{institution}}",
    noNotices: "No notices",
    examRoutine: "Exam Schedule",
    examRoutineSubtitle: "Upcoming and ongoing exams for your child's {{class}}",
    noRoutine: "No exam schedule found",
    noRoutineHint: "The schedule will appear here once published.",
    exam: "Exam",
    subject: "{{subject}}",
    date: "Date",
    time: "Time",
    roomNo: "Room No.",
    results: "Results",
    resultsSubtitle: "Published exam results",
    noResults: "No results published yet",
    noResultsHint: "Exam results will appear here once published.",
    class: "{{class}}",
    totalMarks: "Total Marks",
    average: "Average",
    grade: "Grade",
    rank: "Merit Position",
    viewMarksheet: "View Marksheet",
    attendance: "Attendance",
    attendanceSubtitle: "This month's attendance summary and recent records",
    attendanceRate: "Attendance rate",
    recentRecords: "Recent Records",
    status: "Status",
    attendanceStatus: {
      PRESENT: "Present",
      ABSENT: "Absent",
      LATE: "Late",
      LEAVE: "Leave",
    },
    fees: "Fees",
    feesSubtitle: "Invoices and dues",
    totalBilled: "Total billed",
    paid: "Paid",
    due: "Due",
    feeHead: "Head",
    dueDate: "Due Date",
    amount: "Amount",
    noInvoices: "No invoices",
    invoices: "Invoices",
    invoiceStatus: {
      UNPAID: "Unpaid",
      PARTIALLY_PAID: "Partially paid",
      PAID: "Paid",
      OVERDUE: "Overdue",
      WAIVED: "Waived",
    },
    onlinePaymentSoon:
      "Online fee payment is coming soon. For now, please contact the {{institution}} office to pay fees.",
    childProfile: "Child's Profile",
    tabs: {
      overview: "Overview",
      academic: "Academic",
      attendance: "Attendance",
      financial: "Financial",
      library: "Library",
    },
    promotionHistory: "Promotion History",
    session: "{{session}}",
    rollChange: "Roll Change",
    promotionStatus: {
      PROMOTED: "Promoted",
      RETAINED: "Retained",
      TRANSFERRED: "Transferred",
    },
    bookName: "Book Title",
    borrowedDate: "Borrowed On",
    returnDate: "Return Date",
    fine: "Fine",
    libraryStatus: {
      BORROWED: "Borrowed",
      RETURNED: "Returned",
      LOST: "Lost",
    },
    resultNotFound: "Result not found",
    resultNotFoundHint: "This marksheet is not published or is not linked to your child.",
    backToResults: "Back to results",
    back: "Back",
    print: "Print",
    ms: {
      title: "Marksheet",
      classLabel: "{{class}}:",
      yearSuffix: "",
      rollNo: "Roll No.:",
      registrationNo: "Registration No.:",
      dob: "Date of Birth:",
      studentName: "{{student}}'s Name:",
      fatherName: "Father's Name:",
      resultDivision: "Result Division:",
      grade: "Grade:",
      rank: "Merit Position:",
      status: "Status:",
      serial: "SL",
      subjectName: "{{subject}} Name",
      obtained: "Marks Obtained",
      fullMarks: "Full Marks",
      absentShort: "Abs",
      totalMarks: "Total Marks",
      averageMarks: "Average Marks",
      resultStatus: {
        PASS: "Pass",
        FAIL: "Fail",
        ABSENT: "Absent",
      },
    },
  },
  ar: {
    nav: {
      dashboard: "لوحة التحكم",
      profile: "الملف الشخصي",
      attendance: "الحضور",
      results: "النتائج",
      "exam-routine": "جدول الامتحانات",
      fees: "الرسوم",
      notices: "الإعلانات",
    },
    home: "الرئيسية",
    marksheet: "كشف الدرجات",
    panelTitle: "بوابة ولي الأمر",
    selectChild: "اختر الابن",
    logout: "تسجيل الخروج",
    noChild: "لا يوجد ابن مرتبط",
    noChildHint: "لم يُعثر على أي {{student}} مرتبط بهذا الحساب.",
    roll: "رقم الجلوس",
    regShort: "رقم التسجيل",
    noRecords: "لا توجد سجلات",
    noData: "لا توجد بيانات",
    loginTitle: "دخول ولي الأمر",
    tryAgain: "حاول مرة أخرى",
    institutionLabel: "{{institution}}:",
    mobileNumber: "رقم الجوال",
    password: "كلمة المرور",
    showPassword: "إظهار كلمة المرور",
    hidePassword: "إخفاء كلمة المرور",
    firstLoginHint: "تسجّل الدخول لأول مرة؟ كلمة المرور الافتراضية هي آخر ٤ أرقام من رقم جوالك.",
    loggingIn: "جارٍ تسجيل الدخول...",
    login: "تسجيل الدخول",
    passwordTooShort: "يجب ألا تقل كلمة المرور عن ٤ أحرف",
    passwordMismatch: "كلمتا المرور غير متطابقتين",
    passwordChanged: "تم تغيير كلمة المرور",
    setNewPassword: "تعيين كلمة مرور جديدة",
    mustChangeHint: "حفاظًا على الأمان، يجب تغيير كلمة المرور عند أول تسجيل دخول.",
    newPassword: "كلمة المرور الجديدة",
    retypePassword: "أعد كتابة كلمة المرور",
    saving: "جارٍ الحفظ...",
    savePassword: "حفظ كلمة المرور",
    dashboard: "لوحة التحكم",
    monthAttendancePct: "نسبة حضور هذا الشهر %",
    publishedResults: "النتائج المنشورة",
    upcomingExams: "الامتحانات القادمة",
    dueFees: "الرسوم المستحقة",
    libraryRecords: "سجلات المكتبة",
    notices: "الإعلانات",
    noticesSubtitle: "أحدث إعلانات {{institution}}",
    noNotices: "لا توجد إعلانات",
    examRoutine: "جدول الامتحانات",
    examRoutineSubtitle: "الامتحانات القادمة والجارية لـ{{class}} ابنك",
    noRoutine: "لم يُعثر على جدول امتحانات",
    noRoutineHint: "سيظهر الجدول هنا بعد نشره.",
    exam: "الامتحان",
    subject: "{{subject}}",
    date: "التاريخ",
    time: "الوقت",
    roomNo: "رقم القاعة",
    results: "النتائج",
    resultsSubtitle: "نتائج الامتحانات المنشورة",
    noResults: "لم تُنشر أي نتائج بعد",
    noResultsHint: "ستظهر نتائج الامتحانات هنا بعد نشرها.",
    class: "{{class}}",
    totalMarks: "مجموع الدرجات",
    average: "المعدل",
    grade: "التقدير",
    rank: "الترتيب",
    viewMarksheet: "عرض كشف الدرجات",
    attendance: "الحضور",
    attendanceSubtitle: "ملخص حضور هذا الشهر وأحدث السجلات",
    attendanceRate: "نسبة الحضور",
    recentRecords: "أحدث السجلات",
    status: "الحالة",
    attendanceStatus: {
      PRESENT: "حاضر",
      ABSENT: "غائب",
      LATE: "متأخر",
      LEAVE: "إجازة",
    },
    fees: "الرسوم",
    feesSubtitle: "الفواتير والمستحقات",
    totalBilled: "إجمالي الفواتير",
    paid: "المدفوع",
    due: "المستحق",
    feeHead: "البند",
    dueDate: "تاريخ الاستحقاق",
    amount: "المبلغ",
    noInvoices: "لا توجد فواتير",
    invoices: "الفواتير",
    invoiceStatus: {
      UNPAID: "غير مدفوعة",
      PARTIALLY_PAID: "مدفوعة جزئيًا",
      PAID: "مدفوعة",
      OVERDUE: "متأخرة السداد",
      WAIVED: "معفاة",
    },
    onlinePaymentSoon:
      "خدمة دفع الرسوم إلكترونيًا قادمة قريبًا. حاليًا يرجى التواصل مع مكتب {{institution}} لدفع الرسوم.",
    childProfile: "ملف الابن",
    tabs: {
      overview: "نظرة عامة",
      academic: "الدراسة",
      attendance: "الحضور",
      financial: "المالية",
      library: "المكتبة",
    },
    promotionHistory: "سجل الترفيع",
    session: "{{session}}",
    rollChange: "تغيير رقم الجلوس",
    promotionStatus: {
      PROMOTED: "مُرفَّع",
      RETAINED: "باقٍ للإعادة",
      TRANSFERRED: "منقول",
    },
    bookName: "اسم الكتاب",
    borrowedDate: "تاريخ الاستعارة",
    returnDate: "تاريخ الإرجاع",
    fine: "الغرامة",
    libraryStatus: {
      BORROWED: "مُستعار",
      RETURNED: "تم الإرجاع",
      LOST: "مفقود",
    },
    resultNotFound: "لم يُعثر على النتيجة",
    resultNotFoundHint: "كشف الدرجات هذا غير منشور أو غير مرتبط بابنك.",
    backToResults: "العودة إلى قائمة النتائج",
    back: "رجوع",
    print: "طباعة",
    ms: {
      title: "كشف الدرجات",
      classLabel: "{{class}}:",
      yearSuffix: "م",
      rollNo: "رقم الجلوس:",
      registrationNo: "رقم التسجيل:",
      dob: "تاريخ الميلاد:",
      studentName: "اسم {{student}}:",
      fatherName: "اسم الأب:",
      resultDivision: "التقدير العام:",
      grade: "التقدير:",
      rank: "الترتيب:",
      status: "الحالة:",
      serial: "م",
      subjectName: "اسم {{subject}}",
      obtained: "الدرجة المحصّلة",
      fullMarks: "الدرجة الكاملة",
      absentShort: "غ",
      totalMarks: "مجموع الدرجات",
      averageMarks: "متوسط الدرجات",
      resultStatus: {
        PASS: "ناجح",
        FAIL: "راسب",
        ABSENT: "غائب",
      },
    },
  },
});
