import { defineText } from "@madrasha/shared-ui/src/i18n";

/** Tenant document template library + designer page. */
export const documentTemplatesText = defineText({
  bn: {
    // designer
    invalidUrl: "অবৈধ ঠিকানা",
    systemReadOnly:
      "এটি সুপার অ্যাডমিনের সিস্টেম টেমপ্লেট — এখান থেকে সরাসরি এডিট করা যাবে না। টেমপ্লেট লাইব্রেরি থেকে \"কপি করুন\" চেপে নিজের একটি কপি তৈরি করুন।",
    notFound: "টেমপ্লেট পাওয়া যায়নি",
    backToList: "ডকুমেন্ট টেমপ্লেট তালিকায় ফিরে যান",
    draftSaved: "খসড়া সেভ হয়েছে",
    saveFailed: "সেভ করা যায়নি, আবার চেষ্টা করুন",
    published: "টেমপ্লেট প্রকাশ হয়েছে",
    publishFailed: "প্রকাশ করা যায়নি, আবার চেষ্টা করুন",
    editingType: (type: string) => `${type} টেমপ্লেট এডিট করছেন`,
    nameRequired: "টেমপ্লেটের একটি নাম দিন",
    editDemoData: "ডেমো ডেটা এডিট করুন",
    modified: " (পরিবর্তিত)",
    noPreviewData:
      "প্রিভিউ দেখানোর জন্য কোনো সক্রিয় {{student}}ের তথ্য পাওয়া যায়নি — অন্তত একজন {{student}} যোগ করলে এখানে প্রকৃত তথ্য দিয়ে প্রিভিউ দেখা যাবে, অথবা \"ডেমো ডেটা এডিট করুন\" থেকে নিজের মতো নমুনা তথ্য বসিয়ে দেখুন।",
    doneBack: "সম্পন্ন — তালিকায় ফিরে যান",
    // library
    listLoadFailed: "টেমপ্লেট তালিকা লোড করা যায়নি",
    created: "নতুন টেমপ্লেট তৈরি হয়েছে",
    createFailed: "নতুন টেমপ্লেট তৈরি করা যায়নি, আবার চেষ্টা করুন",
    copyName: (name: string) => `${name} (কপি)`,
    copyFailed: "কপি করা যায়নি",
    copyFailedRetry: "কপি করা যায়নি, আবার চেষ্টা করুন",
    defaultSet: "ডিফল্ট নির্ধারণ করা হয়েছে",
    defaultSetFailed: "ডিফল্ট নির্ধারণ করা যায়নি",
    defaultSetFailedRetry: "ডিফল্ট নির্ধারণ করা যায়নি, আবার চেষ্টা করুন",
    deleteTitle: "টেমপ্লেট মুছে ফেলবেন?",
    deleteMessage: (name: string) => `"${name}" টেমপ্লেটটি স্থায়ীভাবে মুছে যাবে — এই কাজটি ফিরিয়ে নেওয়া যাবে না।`,
    deleteConfirm: "মুছে ফেলুন",
    deleted: "টেমপ্লেট মুছে ফেলা হয়েছে",
    deleteFailed: "মুছে ফেলা যায়নি — এটি সম্ভবত বর্তমান ডিফল্ট হিসেবে ব্যবহৃত হচ্ছে",
    libraryTitle: (title: string) => `${title} — টেমপ্লেট লাইব্রেরি`,
    librarySubtitle: "সিস্টেম টেমপ্লেট ব্যবহার করুন, কপি করে নিজের মতো সাজান, অথবা নিজের টেমপ্লেট তৈরি করুন",
    newTemplate: "নতুন টেমপ্লেট",
    newNamed: (title: string) => `নতুন ${title}`,
    noTemplates: "কোনো টেমপ্লেট পাওয়া যায়নি। একটি নতুন টেমপ্লেট তৈরি করুন।",
    yourDefault: "আপনার ডিফল্ট",
    system: "সিস্টেম",
    myTemplate: "আমার টেমপ্লেট",
    draft: "খসড়া",
    systemDefault: "সিস্টেম ডিফল্ট",
    edit: "এডিট",
    versionHistory: "সংস্করণ ইতিহাস",
    copying: "কপি হচ্ছে...",
    copy: "কপি করুন",
    setting: "সেট হচ্ছে...",
    makeDefault: "ডিফল্ট করুন",
    deleting: "মুছে ফেলা হচ্ছে...",
    delete: "মুছুন",
    versionsLoadFailed: "সংস্করণ তালিকা লোড করা যায়নি",
    restoreTitle: "সংস্করণ পুনরুদ্ধার করুন?",
    restoreMessage: (no: string) =>
      `সংস্করণ ${no} এর বিষয়বস্তু বর্তমান খসড়ায় কপি হবে। প্রকাশিত সংস্করণ অপরিবর্তিত থাকবে — পরিবর্তন কার্যকর করতে আবার "প্রকাশ করুন" চাপতে হবে।`,
    restoreConfirm: "পুনরুদ্ধার করুন",
    restored: "সংস্করণ খসড়ায় পুনরুদ্ধার হয়েছে",
    restoreFailed: "পুনরুদ্ধার করা যায়নি, আবার চেষ্টা করুন",
    historyTitle: (name: string) => `সংস্করণ ইতিহাস — ${name}`,
    noVersions: "কোনো সংস্করণ পাওয়া যায়নি",
    publishedLabel: "প্রকাশিত",
    publishedOn: (d: string) => `প্রকাশ: ${d}`,
    createdOn: (d: string) => `তৈরি: ${d}`,
    restoring: "পুনরুদ্ধার হচ্ছে...",
    restore: "পুনরুদ্ধার",
  },
  en: {
    invalidUrl: "Invalid address",
    systemReadOnly:
      "This is a super-admin system template — it cannot be edited here. Press \"Copy\" in the template library to create your own copy.",
    notFound: "Template not found",
    backToList: "Back to the document template list",
    draftSaved: "Draft saved",
    saveFailed: "Could not save, please try again",
    published: "Template published",
    publishFailed: "Could not publish, please try again",
    editingType: (type) => `Editing a ${type} template`,
    nameRequired: "Give the template a name",
    editDemoData: "Edit demo data",
    modified: " (modified)",
    noPreviewData:
      "No active {{student}} data found for the preview — add at least one {{student}} to preview with real data, or use \"Edit demo data\" to enter your own sample data.",
    doneBack: "Done — back to list",
    listLoadFailed: "Could not load the template list",
    created: "New template created",
    createFailed: "Could not create a new template, please try again",
    copyName: (name) => `${name} (copy)`,
    copyFailed: "Could not copy",
    copyFailedRetry: "Could not copy, please try again",
    defaultSet: "Default set",
    defaultSetFailed: "Could not set default",
    defaultSetFailedRetry: "Could not set default, please try again",
    deleteTitle: "Delete template?",
    deleteMessage: (name) => `The template "${name}" will be deleted permanently — this cannot be undone.`,
    deleteConfirm: "Delete",
    deleted: "Template deleted",
    deleteFailed: "Could not delete — it is probably in use as the current default",
    libraryTitle: (title) => `${title} — Template Library`,
    librarySubtitle: "Use a system template, copy and customise it, or create your own",
    newTemplate: "New template",
    newNamed: (title) => `New ${title}`,
    noTemplates: "No templates found. Create a new template.",
    yourDefault: "Your default",
    system: "System",
    myTemplate: "My template",
    draft: "Draft",
    systemDefault: "System default",
    edit: "Edit",
    versionHistory: "Version history",
    copying: "Copying...",
    copy: "Copy",
    setting: "Setting...",
    makeDefault: "Make default",
    deleting: "Deleting...",
    delete: "Delete",
    versionsLoadFailed: "Could not load the version list",
    restoreTitle: "Restore version?",
    restoreMessage: (no) =>
      `The content of version ${no} will be copied into the current draft. The published version stays unchanged — press "Publish" again to apply the change.`,
    restoreConfirm: "Restore",
    restored: "Version restored to draft",
    restoreFailed: "Could not restore, please try again",
    historyTitle: (name) => `Version history — ${name}`,
    noVersions: "No versions found",
    publishedLabel: "Published",
    publishedOn: (d) => `Published: ${d}`,
    createdOn: (d) => `Created: ${d}`,
    restoring: "Restoring...",
    restore: "Restore",
  },
  ar: {
    invalidUrl: "عنوان غير صالح",
    systemReadOnly:
      "هذا قالب نظام من المشرف العام — لا يمكن تعديله هنا. اضغط \"نسخ\" في مكتبة القوالب لإنشاء نسختك الخاصة.",
    notFound: "لم يتم العثور على القالب",
    backToList: "العودة إلى قائمة قوالب الوثائق",
    draftSaved: "تم حفظ المسودة",
    saveFailed: "تعذّر الحفظ، أعد المحاولة",
    published: "تم نشر القالب",
    publishFailed: "تعذّر النشر، أعد المحاولة",
    editingType: (type) => `تعديل قالب ${type}`,
    nameRequired: "أدخل اسمًا للقالب",
    editDemoData: "تعديل البيانات التجريبية",
    modified: " (معدّلة)",
    noPreviewData:
      "لا توجد بيانات طالب نشط للمعاينة — أضف طالبًا واحدًا على الأقل للمعاينة ببيانات حقيقية، أو استخدم \"تعديل البيانات التجريبية\" لإدخال بيانات نموذجية.",
    doneBack: "تم — العودة إلى القائمة",
    listLoadFailed: "تعذّر تحميل قائمة القوالب",
    created: "تم إنشاء قالب جديد",
    createFailed: "تعذّر إنشاء قالب جديد، أعد المحاولة",
    copyName: (name) => `${name} (نسخة)`,
    copyFailed: "تعذّر النسخ",
    copyFailedRetry: "تعذّر النسخ، أعد المحاولة",
    defaultSet: "تم تعيين الافتراضي",
    defaultSetFailed: "تعذّر تعيين الافتراضي",
    defaultSetFailedRetry: "تعذّر تعيين الافتراضي، أعد المحاولة",
    deleteTitle: "حذف القالب؟",
    deleteMessage: (name) => `سيُحذف القالب "${name}" نهائيًا — ولا يمكن التراجع.`,
    deleteConfirm: "حذف",
    deleted: "تم حذف القالب",
    deleteFailed: "تعذّر الحذف — ربما يُستخدم حاليًا كقالب افتراضي",
    libraryTitle: (title) => `${title} — مكتبة القوالب`,
    librarySubtitle: "استخدم قالب النظام، أو انسخه وخصّصه، أو أنشئ قالبك الخاص",
    newTemplate: "قالب جديد",
    newNamed: (title) => `${title} جديد`,
    noTemplates: "لا توجد قوالب. أنشئ قالبًا جديدًا.",
    yourDefault: "الافتراضي لديك",
    system: "النظام",
    myTemplate: "قالبي",
    draft: "مسودة",
    systemDefault: "افتراضي النظام",
    edit: "تعديل",
    versionHistory: "سجل الإصدارات",
    copying: "جارٍ النسخ...",
    copy: "نسخ",
    setting: "جارٍ التعيين...",
    makeDefault: "جعله افتراضيًا",
    deleting: "جارٍ الحذف...",
    delete: "حذف",
    versionsLoadFailed: "تعذّر تحميل قائمة الإصدارات",
    restoreTitle: "استعادة الإصدار؟",
    restoreMessage: (no) =>
      `سيُنسخ محتوى الإصدار ${no} إلى المسودة الحالية. يبقى الإصدار المنشور دون تغيير — اضغط "نشر" مجددًا لتطبيق التغيير.`,
    restoreConfirm: "استعادة",
    restored: "تمت استعادة الإصدار إلى المسودة",
    restoreFailed: "تعذّرت الاستعادة، أعد المحاولة",
    historyTitle: (name) => `سجل الإصدارات — ${name}`,
    noVersions: "لا توجد إصدارات",
    publishedLabel: "منشور",
    publishedOn: (d) => `نُشر: ${d}`,
    createdOn: (d) => `أُنشئ: ${d}`,
    restoring: "جارٍ الاستعادة...",
    restore: "استعادة",
  },
});
