import { defineText } from "@madrasha/shared-ui/src/i18n";

export const talimatDashboardText = defineText({
  bn: {
    upcoming: "আসন্ন",
    ongoing: "চলমান",
    completed: "সমাপ্ত",
    noRoutine: "রুটিন নেই",
    pass: "পাস",
    fail: "ফেল",
    absent: "অনুপস্থিত",
    classN: (id: string) => `{{class}} #${id}`,
    latestExam: "সর্বশেষ পরীক্ষা",
    none: "নেই",
    sessionN: (y: string) => `{{session}} ${y}`,
    present: "উপস্থিত",
    fromSlots: (n: string) => `${n}টি {{subject}}ের হাজিরা থেকে`,
    noAttendance: "হাজিরা এখনো নেওয়া হয়নি",
    absentInOne: "অন্তত এক {{subject}}ে অনুপস্থিত",
    passFail: "পাস / ফেল",
    latestResult: "সর্বশেষ পরীক্ষার ফলাফল",
    quickActions: "দ্রুত অ্যাকশন",
    marksEntry: "নম্বর এন্ট্রি",
    resultPreview: "ফলাফল প্রিভিউ",
    settings: "সেটিং",
    examStatus: "পরীক্ষার অবস্থা",
    examStatusHint: "সক্রিয় পরীক্ষাগুলো রুটিন অনুযায়ী আসন্ন, চলমান নাকি সমাপ্ত",
    activeN: (n: string) => `সক্রিয় ${n}`,
    upcomingN: (n: string) => `আসন্ন ${n}`,
    ongoingN: (n: string) => `চলমান ${n}`,
    completedN: (n: string) => `সমাপ্ত ${n}`,
    noActiveExam: "কোনো সক্রিয় পরীক্ষা নেই",
    noExamRoutine: "পরীক্ষার রুটিন যোগ করা হয়নি",
    resultStatus: "ফলাফলের অবস্থা",
    latestExamN: (name: string) => `সর্বশেষ পরীক্ষা: ${name}`,
    gradeDistribution: "গ্রেড বণ্টন",
    students: "{{student}}",
    classEntryStatus: "{{class}}ভিত্তিক নম্বর এন্ট্রির অবস্থা",
    noLatestExam: "সর্বশেষ পরীক্ষার তথ্য নেই",
  },
  en: {
    upcoming: "Upcoming",
    ongoing: "Ongoing",
    completed: "Completed",
    noRoutine: "No routine",
    pass: "Pass",
    fail: "Fail",
    absent: "Absent",
    classN: (id) => `{{class}} #${id}`,
    latestExam: "Latest exam",
    none: "None",
    sessionN: (y) => `{{session}} ${y}`,
    present: "Present",
    fromSlots: (n) => `From attendance of ${n} {{subject}}s`,
    noAttendance: "Attendance not taken yet",
    absentInOne: "Absent in at least one {{subject}}",
    passFail: "Pass / Fail",
    latestResult: "Latest exam result",
    quickActions: "Quick actions",
    marksEntry: "Marks entry",
    resultPreview: "Result preview",
    settings: "Settings",
    examStatus: "Exam status",
    examStatusHint: "Whether active exams are upcoming, ongoing or completed, per routine",
    activeN: (n) => `Active ${n}`,
    upcomingN: (n) => `Upcoming ${n}`,
    ongoingN: (n) => `Ongoing ${n}`,
    completedN: (n) => `Completed ${n}`,
    noActiveExam: "No active exam",
    noExamRoutine: "No exam routine added",
    resultStatus: "Result status",
    latestExamN: (name) => `Latest exam: ${name}`,
    gradeDistribution: "Grade distribution",
    students: "{{student}}s",
    classEntryStatus: "Marks entry status by {{class}}",
    noLatestExam: "No latest exam data",
  },
});
