import { defineText } from "@madrasha/shared-ui/src/i18n";

/** Exam-fee status card (dashboard). */
export const examFeeText = defineText({
  bn: {
    classN: (id: string) => `{{class}} #${id}`,
    title: "পরীক্ষার ফি",
    subtitle: "কারা ফি দিয়েছে আর কারা দেয়নি",
    selectExam: "পরীক্ষা নির্বাচন",
    latestExam: "সর্বশেষ পরীক্ষা",
    noActiveExam: "কোনো সক্রিয় পরীক্ষা নেই",
    notBilled: "এই পরীক্ষার ফি এখনো বিল হয়নি",
    notBilledHint: "পরীক্ষা চালু হলে বা রুটিন তৈরি হলে সব {{student}}ের ইনভয়েস তৈরি হবে।",
    viewFeeSetup: "ফি সেটাপ দেখুন",
    unpaid: "দেয়নি",
    paid: "দিয়েছে",
    dueAmount: (n: string) => `বাকি ৳${n}`,
    collectedAmount: (n: string) => `আদায় ৳${n}`,
    collectedPct: (n: string) => `${n}% আদায়`,
    searchPlaceholder: "নাম বা রোল খুঁজুন",
    class: "{{class}}",
    allClasses: "সব {{class}}",
    allPaid: "সবাই ফি দিয়েছে",
    noStudents: "কোনো {{student}} পাওয়া যায়নি",
    roll: "রোল",
    name: "নাম",
    due: "বাকি",
    payment: "পরিশোধ",
    partial: "(আংশিক)",
  },
  en: {
    classN: (id) => `{{class}} #${id}`,
    title: "Exam Fee",
    subtitle: "Who has paid and who has not",
    selectExam: "Select exam",
    latestExam: "Latest exam",
    noActiveExam: "No active exam",
    notBilled: "This exam's fee has not been billed yet",
    notBilledHint: "Invoices for all {{student}}s are created when the exam is enabled or its routine is created.",
    viewFeeSetup: "View fee setup",
    unpaid: "Unpaid",
    paid: "Paid",
    dueAmount: (n) => `Due ৳${n}`,
    collectedAmount: (n) => `Collected ৳${n}`,
    collectedPct: (n) => `${n}% collected`,
    searchPlaceholder: "Search name or roll",
    class: "{{class}}",
    allClasses: "All {{class}}es",
    allPaid: "Everyone has paid",
    noStudents: "No {{student}}s found",
    roll: "Roll",
    name: "Name",
    due: "Due",
    payment: "Paid",
    partial: "(partial)",
  },
});

/** ID card back settings form. Print-side defaults use usePrintText. */
export const idCardBackText = defineText({
  bn: {
    phone: (p: string) => `ফোন: ${p}`,
    principal: "অধ্যক্ষ",
    expiryBeforeIssue: "মেয়াদ শেষের তারিখ ইস্যু তারিখের আগে হতে পারে না",
    saved: "আইডি কার্ডের পিছনের তথ্য সেভ হয়েছে",
    title: "আইডি কার্ড ব্যাক",
    subtitle:
      "আইডি কার্ডের পিছনের পাতায় ছাপা হবে এমন তথ্য - ইস্যু ও মেয়াদের তারিখ, অধ্যক্ষের স্বাক্ষর, হারিয়ে গেলে ফেরতের ঠিকানা",
    saving: "সেভ হচ্ছে...",
    save: "সেভ করুন",
    defaultDesign: "ডিফল্ট পিছনের ডিজাইন",
    defaultDesignHint: "রিপোর্টে আইডি কার্ড খুললে এই ডিজাইন দিয়ে শুরু হয় - সেখান থেকে চাইলে অন্য ডিজাইনও বাছা যায়",
    readyDesigns: "রেডিমেড ডিজাইন",
    institutionName: "{{institution}}র নাম",
    institutionNameHint: "প্রতিষ্ঠান ব্র্যান্ডিং সেটিং থেকে আসে - সেখানেই বদলাতে হবে",
    issueDate: "কার্ড ইস্যুর তারিখ",
    expiryDate: "মেয়াদ শেষের তারিখ",
    principalTitle: "অধ্যক্ষের পদবি",
    principalTitleHint: "স্বাক্ষরের নিচে ছাপা হয় - ফাঁকা রাখলে “অধ্যক্ষ”",
    principalSignature: "অধ্যক্ষের স্বাক্ষর",
    signatureHint: "সাদা বা স্বচ্ছ জমিনে স্বাক্ষরের স্পষ্ট ছবি (PNG/JPG, সর্বোচ্চ ২MB)",
    ratio: "অনুপাত ২:১",
    returnAddress: "কার্ড হারিয়ে গেলে ফেরত দেওয়ার ঠিকানা",
    returnAddressHint: "ফাঁকা রাখলে {{institution}}র ঠিকানা ও ফোন নম্বর ছাপা হবে",
    previewSample: "প্রিভিউ (নমুনা)",
    printHint: "ছাপতে রিপোর্ট → ডকুমেন্ট → আইডি কার্ড (সামনে-পিছনে) বা আইডি কার্ড ব্যাক (শুধু পিছন)।",
  },
  en: {
    phone: (p) => `Phone: ${p}`,
    principal: "Principal",
    expiryBeforeIssue: "The expiry date cannot be before the issue date",
    saved: "ID card back details saved",
    title: "ID Card Back",
    subtitle: "Details printed on the back of the ID card - issue and expiry dates, principal's signature, return address if lost",
    saving: "Saving...",
    save: "Save",
    defaultDesign: "Default back design",
    defaultDesignHint: "ID cards in reports start with this design - another design can be chosen there",
    readyDesigns: "Ready-made designs",
    institutionName: "{{institution}} name",
    institutionNameHint: "Comes from the branding settings - change it there",
    issueDate: "Card issue date",
    expiryDate: "Expiry date",
    principalTitle: "Principal's title",
    principalTitleHint: "Printed under the signature - “Principal” if left empty",
    principalSignature: "Principal's signature",
    signatureHint: "A clear image of the signature on a white or transparent background (PNG/JPG, max 2MB)",
    ratio: "Ratio 2:1",
    returnAddress: "Return address if the card is lost",
    returnAddressHint: "If empty, the {{institution}}'s address and phone number are printed",
    previewSample: "Preview (sample)",
    printHint: "To print: Reports → Documents → ID Card (front & back) or ID Card Back (back only).",
  },
});

/** Notice board. The printed notice uses usePrintText. */
export const noticeText = defineText({
  bn: {
    notice: "নোটিশ",
    dateLine: "তারিখ: ........................",
    headSignature: "{{head}}ের স্বাক্ষর ও সীল",
    loadError: "নোটিশ লোড করা যায়নি। আবার চেষ্টা করুন।",
    bothRequired: "শিরোনাম ও নোটিশের লেখা দুটোই দিতে হবে।",
    saveError: "নোটিশ সেভ করা যায়নি। আবার চেষ্টা করুন।",
    confirmDelete: (title: string) => `"${title}" নোটিশটি মুছে ফেলতে চান?`,
    deleteError: "নোটিশ মুছে ফেলা যায়নি। আবার চেষ্টা করুন।",
    title: "নোটিশ বোর্ড",
    subtitle: "দেয়ালে টানানোর জন্য একাধিক নোটিশ লিখে সেভ করুন — দরকারমতো যেকোনোটি বেছে প্রিন্ট করুন",
    newNotice: "নতুন নোটিশ",
    empty: "এখনো কোনো নোটিশ তৈরি করা হয়নি। \"নতুন নোটিশ\" বাটনে ক্লিক করে প্রথম নোটিশটি লিখুন।",
    lastUpdated: (d: string) => `সর্বশেষ আপডেট: ${d}`,
    previewPrint: "প্রিভিউ / প্রিন্ট",
    edit: "এডিট",
    deleting: "মুছা হচ্ছে...",
    delete: "মুছুন",
    editNotice: "নোটিশ এডিট করুন",
    writeNotice: "নতুন নোটিশ লিখুন",
    noticeTitle: "নোটিশের শিরোনাম",
    titlePlaceholder: "যেমন: ঈদের ছুটি সংক্রান্ত নোটিশ",
    noticeBody: "নোটিশের লেখা",
    bodyPlaceholder: "এখানে নোটিশের পুরো লেখা লিখুন...",
    cancel: "বাতিল",
    saving: "সেভ হচ্ছে...",
    save: "সেভ করুন",
    preview: "প্রিভিউ",
    printPreview: "নোটিশ প্রিন্ট প্রিভিউ",
    close: "বন্ধ করুন",
    print: "প্রিন্ট করুন",
  },
  en: {
    notice: "Notice",
    dateLine: "Date: ........................",
    headSignature: "{{head}}'s signature & seal",
    loadError: "Could not load notices. Please try again.",
    bothRequired: "Both the title and the notice text are required.",
    saveError: "Could not save the notice. Please try again.",
    confirmDelete: (title) => `Delete the notice "${title}"?`,
    deleteError: "Could not delete the notice. Please try again.",
    title: "Notice Board",
    subtitle: "Write and save notices for the wall — pick any one to print when needed",
    newNotice: "New notice",
    empty: "No notices yet. Click \"New notice\" to write the first one.",
    lastUpdated: (d) => `Last updated: ${d}`,
    previewPrint: "Preview / Print",
    edit: "Edit",
    deleting: "Deleting...",
    delete: "Delete",
    editNotice: "Edit notice",
    writeNotice: "Write a new notice",
    noticeTitle: "Notice title",
    titlePlaceholder: "e.g. Notice about the Eid holidays",
    noticeBody: "Notice text",
    bodyPlaceholder: "Write the full notice here...",
    cancel: "Cancel",
    saving: "Saving...",
    save: "Save",
    preview: "Preview",
    printPreview: "Notice print preview",
    close: "Close",
    print: "Print",
  },
});
