import { defineText } from "@madrasha/shared-ui/src/i18n";

/** UI text for the K40 attendance-device screens (devices, mapping, today). */
export const attendanceDeviceText = defineText({
  bn: {
    time: {
      never: "কখনো নয়",
      justNow: "এইমাত্র",
      seconds: (n: string) => `${n} সেকেন্ড আগে`,
      minutes: (n: string) => `${n} মিনিট আগে`,
      hours: (n: string) => `${n} ঘণ্টা আগে`,
      days: (n: string) => `${n} দিন আগে`,
      months: (n: string) => `${n} মাস আগে`,
      years: (n: string) => `${n} বছর আগে`,
    },
    deviceStatus: { online: "অনলাইন", offline: "অফলাইন", unknown: "অজানা", inactive: "নিষ্ক্রিয়" },
    syncStatus: { PENDING: "অপেক্ষমাণ", SYNCING: "সিঙ্ক হচ্ছে", SYNCED: "সিঙ্ক হয়েছে", FAILED: "ব্যর্থ" },
    smsStatus: { PENDING: "অপেক্ষমাণ", PROCESSING: "পাঠানো হচ্ছে", SENT: "পাঠানো হয়েছে", FAILED: "ব্যর্থ" },
    strip: {
      loadFailed: "ডিভাইসের অবস্থা লোড করা যায়নি",
      none: "কোনো ডিভাইস যোগ করা হয়নি",
      lastContact: "সর্বশেষ যোগাযোগ:",
      refreshFailed: "রিফ্রেশ ব্যর্থ - পুরনো তথ্য দেখানো হচ্ছে",
    },
    devices: {
      testTimeout: (s: string) => `${s} সেকেন্ডে কোনো সাড়া মেলেনি - কানেক্টর চালু আছে কিনা দেখুন`,
      testOk: "ডিভাইসের সাথে সংযোগ সফল হয়েছে",
      testFailed: "ডিভাইসের সাথে সংযোগ হয়নি",
      testRequested: "টেস্ট অনুরোধ পাঠানো হয়েছে, কানেক্টরের সাড়ার অপেক্ষা...",
      deactivated: "ডিভাইস নিষ্ক্রিয় করা হয়েছে",
      activated: "ডিভাইস সক্রিয় করা হয়েছে",
      rotateTitle: "কানেক্টর কী পরিবর্তন করুন",
      rotateMessage: (name: string) =>
        `"${name}" ডিভাইসের নতুন কী ও নতুন পেয়ারিং কোড তৈরি হবে। পুরনো কী সাথে সাথে অচল হয়ে যাবে - কানেক্টর নতুন করে ইনস্টল/সেটআপ করার সময় নতুন পেয়ারিং কোডটি পেস্ট করুন। (পেয়ারিং কোড হারিয়ে গেলেও এভাবেই নতুন কোড পাওয়া যায়।)`,
      rotateConfirm: "নতুন কী ও পেয়ারিং কোড তৈরি করুন",
      deleteTitle: "ডিভাইস ডিলিট করুন",
      deleteMessage: (name: string) =>
        `"${name}" ডিভাইসটি মুছে ফেলতে চান? কানেক্টর আর এই ডিভাইসের হয়ে ডেটা পাঠাতে পারবে না।`,
      deleteConfirm: "ডিলিট করুন",
      deleted: "ডিভাইস মুছে ফেলা হয়েছে",
      testing: (s: string) => `টেস্ট চলছে - কানেক্টরের সাড়ার অপেক্ষা (সর্বোচ্চ ${s} সেকেন্ড)...`,
      title: "উপস্থিতি ডিভাইস",
      subtitle:
        "ZKTeco K40 ডিভাইস যোগ করুন ও অবস্থা দেখুন। ডিভাইসের কাছাকাছি চলা কানেক্টর প্রোগ্রাম এই তালিকা থেকে সংযোগের তথ্য নেয়।",
      refresh: "রিফ্রেশ",
      newDevice: "নতুন ডিভাইস",
      downloadConnector: "কানেক্টর ডাউনলোড",
      downloadConnectorHint: "ডিভাইসের একই নেটওয়ার্কের একটি Windows কম্পিউটারে কানেক্টর ইনস্টল করুন",
      allDevices: "সব ডিভাইস",
      autoUpdateHint: (s: string) => `প্রতি ${s} সেকেন্ডে অবস্থা নিজে থেকে আপডেট হয়`,
      listLoadFailed: "ডিভাইস তালিকা লোড করা যায়নি",
      checkInternet: "ইন্টারনেট সংযোগ দেখে আবার চেষ্টা করুন।",
      retry: "আবার চেষ্টা করুন",
      emptyTitle: "এখনো কোনো ডিভাইস যোগ করা হয়নি",
      emptyHint: "K40 ডিভাইসের আইপি ও পোর্ট দিয়ে প্রথম ডিভাইসটি যোগ করুন।",
      emptyConnectorHint:
        "ডিভাইস যোগ করলে একটি পেয়ারিং কোড পাবেন। ডিভাইসের একই নেটওয়ার্কের Windows কম্পিউটারে কানেক্টর ইনস্টল করে সেই কোড পেস্ট করলেই সংযোগ হয়ে যাবে।",
      id: (id: string) => `আইডি: ${id}`,
      polling: (s: string) => `পোলিং প্রতি ${s} সেকেন্ড`,
      connectionTest: "কানেকশন টেস্ট",
      edit: "সম্পাদনা",
      rotateKey: "কী পরিবর্তন / নতুন পেয়ারিং কোড",
      deactivate: "নিষ্ক্রিয় করুন",
      activate: "সক্রিয় করুন",
      delete: "মুছুন",
      connectorLastContact: "কানেক্টর সর্বশেষ যোগাযোগ",
      neverConnected: "কখনো সংযুক্ত হয়নি",
      deviceLastContact: "ডিভাইসে সর্বশেষ সংযোগ",
      lastSync: "সর্বশেষ সিঙ্ক",
      lastError: (e: string) => `সর্বশেষ ত্রুটি: ${e}`,
      clockDrift: "ঘড়ির পার্থক্য",
      driftAhead: (s: string) => `মেশিন ${s} সেকেন্ড এগিয়ে`,
      driftBehind: (s: string) => `মেশিন ${s} সেকেন্ড পিছিয়ে`,
      driftOk: "ঠিক আছে",
      unknown: "এখনো জানা নেই",
      userSync: "মেশিনে ইউজার",
      userSyncOk: "হালনাগাদ",
      userSyncPending: "হালনাগাদ বাকি",
      userSyncError: "সিঙ্ক ত্রুটি",
      deviceUsers: (n: string) => `${n} জন`,
      userSyncErrorMsg: (e: string) => `ইউজার সিঙ্ক ত্রুটি: ${e}`,
      offlineAlerted: "অফলাইন সতর্কতা SMS পাঠানো হয়েছে",
    },
    form: {
      deviceIdRequired: "ডিভাইস আইডি দিন",
      nameRequired: "ডিভাইসের নাম দিন",
      ipRequired: "আইপি অ্যাড্রেস দিন",
      ipInvalid: "সঠিক আইপি অ্যাড্রেস দিন (যেমন 192.168.1.201)",
      portInvalid: (min: string, max: string) => `${min} থেকে ${max} এর মধ্যে পোর্ট দিন`,
      pollInvalid: (min: string, max: string) => `${min} থেকে ${max} সেকেন্ডের মধ্যে দিন`,
      updated: "ডিভাইস আপডেট হয়েছে",
      added: "ডিভাইস যোগ করা হয়েছে",
      editTitle: "ডিভাইস সম্পাদনা",
      newTitle: "নতুন উপস্থিতি ডিভাইস",
      deviceId: "ডিভাইস আইডি",
      deviceIdPlaceholder: "যেমন: 1",
      deviceIdLocked: "ডিভাইস আইডি পরিবর্তন করা যায় না",
      name: "নাম",
      namePlaceholder: "যেমন: মেইন গেট K40",
      ip: "আইপি অ্যাড্রেস",
      port: "পোর্ট",
      commKey: "কমিউনিকেশন কী (ঐচ্ছিক)",
      commKeyKeep: "খালি রাখলে আগেরটিই থাকবে",
      commKeyNew: "ডিভাইসে সেট করা থাকলে দিন",
      commKeyHint: "এটি শুধু সেভ হয়, পরে আর দেখানো হয় না",
      pollInterval: "পোলিং ব্যবধান (সেকেন্ড)",
      saving: "সেভ হচ্ছে...",
    },
    key: {
      copied: (label: string) => `${label} কপি হয়েছে`,
      copyFailed: "কপি করা যায়নি, হাতে নির্বাচন করে কপি করুন",
      newTitle: "নতুন পেয়ারিং কোড",
      title: "কানেক্টর পেয়ারিং কোড",
      warning: "এই কোড (ও এর ভেতরের কী) আর কখনো দেখানো হবে না। এখনই কপি করে কানেক্টর ইনস্টলারে বসিয়ে নিন।",
      oldInvalid: " আগের কী ও পেয়ারিং কোড এখন থেকে আর কাজ করবে না।",
      pairingLabel: "পেয়ারিং কোড",
      pairingFor: (name: string) => `ডিভাইস: ${name}`,
      pairingWord: "পেয়ারিং কোড",
      stepsTitle: "কীভাবে সেটআপ করবেন",
      step1: "১. কানেক্টর ইনস্টলার ডাউনলোড করুন",
      step2: "২. ইনস্টল করার সময় এই কোড পেস্ট করুন",
      step3: "৩. কয়েক মিনিটের মধ্যে ডিভাইস অনলাইন দেখাবে",
      download: "ইনস্টলার ডাউনলোড",
      missingInfo:
        "মাদরাসার স্লাগ বা প্রতিষ্ঠান আইডি পাওয়া যায়নি, তাই পেয়ারিং কোড তৈরি করা গেল না। লগআউট করে আবার লগইন করুন, অথবা নিচের ম্যানুয়াল সেটআপ ব্যবহার করুন।",
      advanced: "অ্যাডভান্সড / ম্যানুয়াল সেটআপ",
      keyLabel: (name: string) => `${name} - কানেক্টর কী`,
      keyWord: "কী",
      copy: "কপি",
      commandLabel: "কমান্ড দিয়ে সেটআপ (কানেক্টর ফোল্ডারে চালান)",
      commandWord: "কমান্ড",
      configLabel: "config.json (কী ছাড়া)",
      configHint:
        "কী config.json-এ লিখবেন না। `connector.exe setup` চালালে কী চাইবে - তখন উপরের কী পেস্ট করুন, সেটি আলাদা গোপন ফাইলে সেভ হবে।",
      configWord: "কনফিগ",
      done: "বুঝেছি, কপি করেছি",
    },
    mapping: {
      userIdRequired: "K40 ইউজার আইডি দিন (মুছতে ✕ চাপুন)",
      digitsOnly: "শুধু সংখ্যা দেওয়া যাবে",
      saved: (name: string) => `${name} - ম্যাপিং সেভ হয়েছে`,
      saveFailed: "সেভ করা যায়নি, আবার চেষ্টা করুন",
      cleared: (name: string) => `${name} - ম্যাপিং মুছে ফেলা হয়েছে`,
      clearFailed: "মুছতে সমস্যা হয়েছে",
      title: "{{student}} ↔ K40 ইউজার ম্যাপিং",
      subtitle:
        "K40 ডিভাইসে নথিভুক্ত প্রতিটি ইউজার আইডি কোন {{student}}র, তা এখানে ঠিক করুন। ম্যাপ না হলে পাঞ্চ থেকে উপস্থিতি গণনা হবে না।",
      studentList: "{{student}} তালিকা",
      count: (n: string) => `${n} জন`,
      searchPlaceholder: "নাম, রোল বা আইডি দিয়ে খুঁজুন",
      allClasses: "সব {{class}}",
      listLoadFailed: "{{student}} তালিকা লোড করা যায়নি",
      tryAgainDot: "আবার চেষ্টা করুন।",
      retry: "আবার চেষ্টা করুন",
      noStudents: "কোনো {{student}} পাওয়া যায়নি",
      changeFilter: "সার্চ বা {{class}} ফিল্টার বদলে দেখুন।",
      student: "{{student}}",
      class: "{{class}}",
      k40UserId: "K40 ইউজার আইডি",
      idRoll: (id: string, roll: string | null) => `আইডি: ${id}${roll ? ` · রোল: ${roll}` : ""}`,
      userIdPlaceholder: "যেমন: 12",
      save: "সেভ করুন",
      clearMapping: "ম্যাপিং মুছুন",
      page: (p: string, total: string) => `পৃষ্ঠা ${p} / ${total}`,
      prev: "আগের",
      next: "পরের",
      unmappedTitle: "ম্যাপ না হওয়া ডিভাইস ইউজার",
      unmappedHint: "ডিভাইস থেকে পাঞ্চ এসেছে, কিন্তু কোনো {{student}}র সাথে যুক্ত নয়",
      refresh: "রিফ্রেশ",
      unmappedLoadFailed: "তালিকা লোড করা যায়নি।",
      allMapped: "সব ডিভাইস ইউজার ম্যাপ করা আছে।",
      userId: (id: string) => `ইউজার আইডি: ${id}`,
      unknownDevice: "অজানা ডিভাইস",
      punches: (n: string) => `${n}টি পাঞ্চ`,
      lastPunch: (v: string) => `সর্বশেষ: ${v}`,
      link: "যুক্ত করুন",
      assigned: (user: string, name: string) => `ইউজার ${user} → ${name} যুক্ত হয়েছে`,
      assignFailed: "যুক্ত করা যায়নি",
      assignTitle: (user: string) => `ইউজার ${user} কে {{student}}র সাথে যুক্ত করুন`,
      assignSearch: "{{student}}র নাম, রোল বা আইডি",
      searching: "খোঁজা হচ্ছে...",
      typeToSearch: "খুঁজতে নাম লিখুন",
      roll: (r: string) => ` · রোল ${r}`,
      alreadyUser: (id: string) => `আগে থেকে ইউজার ${id}`,
      willReplace: (id: string) => `এই {{student}}র আগের ইউজার আইডি (${id}) বদলে যাবে।`,
      linking: "যুক্ত হচ্ছে...",
      card: "কার্ড",
      autoAssign: "অটো আইডি তৈরি",
      autoAssignHint: "যাদের K40 আইডি নেই তাদের জন্য স্বয়ংক্রিয়ভাবে আইডি তৈরি করুন",
      autoAssignTitle: "অটো আইডি তৈরি",
      autoAssignMessage: (scope: string) =>
        `${scope} — যাদের K40 ইউজার আইডি নেই তাদের সবার জন্য নতুন আইডি তৈরি হবে, কানেক্টর পরে মেশিনে লিখে দেবে।`,
      autoAssignConfirm: "আইডি তৈরি করুন",
      autoAssignDone: (n: string) => `${n} জনের নতুন আইডি তৈরি হয়েছে`,
      autoAssignNone: "সবার আইডি আগে থেকেই আছে",
      allStudentsScope: "সব {{student}}",
      cardsLink: "কার্ড এনরোলমেন্ট",
    },
    today: {
      title: "আজকের উপস্থিতি (ডিভাইস)",
      subtitle: (s: string) => `K40 ডিভাইসের পাঞ্চ থেকে আসা উপস্থিতি। প্রতি ${s} সেকেন্ডে নিজে থেকে আপডেট হয়।`,
      refresh: "রিফ্রেশ",
      present: "উপস্থিত",
      unmapped: "ম্যাপ হয়নি",
      unmappedHint: "ম্যাপিং পেজে গিয়ে যুক্ত করুন",
      totalPunches: "মোট পাঞ্চ",
      lastSync: "সর্বশেষ সিঙ্ক",
      date: "তারিখ",
      device: "ডিভাইস",
      allDevices: "সব ডিভাইস",
      backToToday: "আজকের তারিখে ফিরুন",
      lastUpdate: (time: string) => `সর্বশেষ আপডেট: ${time}`,
      loadFailed: "উপস্থিতি লোড করা যায়নি",
      tryAgainDot: "আবার চেষ্টা করুন।",
      retry: "আবার চেষ্টা করুন",
      noPunchToday: "আজ এখনো কোনো পাঞ্চ আসেনি",
      noAttendance: "এই তারিখে কোনো উপস্থিতি নেই",
      emptyHint: "ডিভাইস অনলাইন আছে কিনা এবং {{student}}দের ম্যাপিং করা আছে কিনা দেখুন।",
      refreshFailed: "রিফ্রেশ ব্যর্থ হয়েছে - আগের তথ্য দেখানো হচ্ছে।",
      student: "{{student}}",
      id: "আইডি",
      class: "{{class}}",
      checkIn: "চেক-ইন",
      sync: "সিঙ্ক",
      sms: "SMS",
      syncTime: "সিঙ্কের সময়",
      tabs: { STUDENT: "{{student}}", TEACHER: "{{teacher}}", STAFF: "স্টাফ" },
      nameCol: { STUDENT: "{{student}}", TEACHER: "{{teacher}}", STAFF: "স্টাফ" },
      late: "দেরি",
      absent: "অনুপস্থিত",
      notArrived: "এখনো আসেনি",
      checkedOut: "চেক-আউট করেছে",
      ofMapped: (n: string) => `আইডি আছে ${n} জনের`,
      rejected: (n: string) => `${n}টি পাঞ্চ গণনা হয়নি`,
      statusLabels: { PRESENT: "উপস্থিত", LATE: "দেরি", ABSENT: "অনুপস্থিত", LEAVE: "ছুটি" },
      status: "অবস্থা",
      checkOut: "চেক-আউট",
      roll: "রোল",
      rollShort: (r: string) => `রোল ${r}`,
      pin: (id: string) => `আইডি ${id}`,
      punchCount: (n: string) => `${n}টি পাঞ্চ`,
      holiday: (title: string) => `ছুটির দিন: ${title} — এই দিনে উপস্থিতি/অনুপস্থিতি গণনা হয় না।`,
      holidayWeekly: "সাপ্তাহিক ছুটির দিন — এই দিনে উপস্থিতি/অনুপস্থিতি গণনা হয় না।",
      punchesTitle: "পাঞ্চ তালিকা",
      notArrivedTitle: "এখনো আসেনি",
      notArrivedHint: "ডিভাইস আইডি আছে কিন্তু এই দিনে কোনো পাঞ্চ নেই",
      allArrived: "ডিভাইস আইডি আছে এমন সবাই পাঞ্চ করেছে।",
      showAll: (n: string) => `সব দেখুন (${n})`,
      showLess: "কম দেখুন",
      classTitle: "{{class}}ভিত্তিক সারাংশ",
      classCol: "{{class}}",
      mappedCol: "আইডি আছে",
      presentCol: "উপস্থিত",
      lateCol: "দেরি",
      absentCol: "অনুপস্থিত",
      notArrivedCol: "আসেনি",
      rateCol: "উপস্থিতির হার",
      noClass: "{{class}} নেই",
      exportCsv: "CSV ডাউনলোড",
      csvName: "নাম",
      csvType: "ধরন",
      csvDeviceId: "ডিভাইস আইডি",
      csvClass: "{{class}}",
      csvRoll: "রোল",
      csvStatus: "অবস্থা",
      csvCheckIn: "চেক-ইন",
      csvCheckOut: "চেক-আউট",
      csvDevice: "ডিভাইস",
      csvNoPunch: "পাঞ্চ নেই",
      settingsLink: "ডিভাইস সেটিংস",
      cardsLink: "কার্ড এনরোলমেন্ট",
    },
  },
  en: {
    time: {
      never: "Never",
      justNow: "Just now",
      seconds: (n) => `${n} sec ago`,
      minutes: (n) => `${n} min ago`,
      hours: (n) => `${n} hr ago`,
      days: (n) => `${n} days ago`,
      months: (n) => `${n} months ago`,
      years: (n) => `${n} years ago`,
    },
    deviceStatus: { online: "Online", offline: "Offline", unknown: "Unknown", inactive: "Inactive" },
    syncStatus: { PENDING: "Pending", SYNCING: "Syncing", SYNCED: "Synced", FAILED: "Failed" },
    smsStatus: { PENDING: "Pending", PROCESSING: "Sending", SENT: "Sent", FAILED: "Failed" },
    strip: {
      loadFailed: "Could not load device status",
      none: "No devices added",
      lastContact: "Last contact:",
      refreshFailed: "Refresh failed - showing older data",
    },
    devices: {
      testTimeout: (s) => `No response within ${s} seconds - check that the connector is running`,
      testOk: "Connected to the device successfully",
      testFailed: "Could not connect to the device",
      testRequested: "Test request sent, waiting for the connector...",
      deactivated: "Device deactivated",
      activated: "Device activated",
      rotateTitle: "Change Connector Key",
      rotateMessage: (name) =>
        `A new key and a new pairing code will be created for "${name}". The old key stops working immediately - paste the new pairing code when installing / setting up the connector again. (This is also how to get a new code if the pairing code was lost.)`,
      rotateConfirm: "Create New Key & Pairing Code",
      deleteTitle: "Delete Device",
      deleteMessage: (name) =>
        `Delete the device "${name}"? The connector will no longer be able to send data for it.`,
      deleteConfirm: "Delete",
      deleted: "Device deleted",
      testing: (s) => `Testing - waiting for the connector (up to ${s} seconds)...`,
      title: "Attendance Devices",
      subtitle:
        "Add ZKTeco K40 devices and see their status. The connector program running near the device reads its connection details from this list.",
      refresh: "Refresh",
      newDevice: "New Device",
      downloadConnector: "Download Connector",
      downloadConnectorHint: "Install the connector on a Windows PC on the same network as the device",
      allDevices: "All Devices",
      autoUpdateHint: (s) => `Status updates automatically every ${s} seconds`,
      listLoadFailed: "Could not load the device list",
      checkInternet: "Check your internet connection and try again.",
      retry: "Try again",
      emptyTitle: "No devices added yet",
      emptyHint: "Add your first device using the K40's IP address and port.",
      emptyConnectorHint:
        "Adding a device gives you a pairing code. Install the connector on a Windows PC on the same network as the device and paste that code to connect.",
      id: (id) => `ID: ${id}`,
      polling: (s) => `polling every ${s} sec`,
      connectionTest: "Connection Test",
      edit: "Edit",
      rotateKey: "Change key / new pairing code",
      deactivate: "Deactivate",
      activate: "Activate",
      delete: "Delete",
      connectorLastContact: "Connector last contact",
      neverConnected: "Never connected",
      deviceLastContact: "Last device contact",
      lastSync: "Last sync",
      lastError: (e) => `Last error: ${e}`,
      clockDrift: "Clock difference",
      driftAhead: (s) => `Machine ${s} sec ahead`,
      driftBehind: (s) => `Machine ${s} sec behind`,
      driftOk: "In sync",
      unknown: "Not known yet",
      userSync: "Users on machine",
      userSyncOk: "Up to date",
      userSyncPending: "Update pending",
      userSyncError: "Sync error",
      deviceUsers: (n) => `${n} users`,
      userSyncErrorMsg: (e) => `User sync error: ${e}`,
      offlineAlerted: "Offline alert SMS sent",
    },
    form: {
      deviceIdRequired: "Enter the device ID",
      nameRequired: "Enter the device name",
      ipRequired: "Enter the IP address",
      ipInvalid: "Enter a valid IP address (e.g. 192.168.1.201)",
      portInvalid: (min, max) => `Enter a port between ${min} and ${max}`,
      pollInvalid: (min, max) => `Enter between ${min} and ${max} seconds`,
      updated: "Device updated",
      added: "Device added",
      editTitle: "Edit Device",
      newTitle: "New Attendance Device",
      deviceId: "Device ID",
      deviceIdPlaceholder: "e.g. 1",
      deviceIdLocked: "The device ID cannot be changed",
      name: "Name",
      namePlaceholder: "e.g. Main Gate K40",
      ip: "IP Address",
      port: "Port",
      commKey: "Communication key (optional)",
      commKeyKeep: "Leave empty to keep the current one",
      commKeyNew: "Enter it if set on the device",
      commKeyHint: "It is only saved, never shown again",
      pollInterval: "Polling interval (seconds)",
      saving: "Saving...",
    },
    key: {
      copied: (label) => `${label} copied`,
      copyFailed: "Could not copy; select it and copy manually",
      newTitle: "New Pairing Code",
      title: "Connector Pairing Code",
      warning: "This code (and the key inside it) will never be shown again. Copy it now into the connector installer.",
      oldInvalid: " The old key and pairing code no longer work.",
      pairingLabel: "Pairing code",
      pairingFor: (name) => `Device: ${name}`,
      pairingWord: "Pairing code",
      stepsTitle: "How to set up",
      step1: "1. Download the connector installer",
      step2: "2. Paste this code when the installer asks for it",
      step3: "3. The device will show as online within a few minutes",
      download: "Download installer",
      missingInfo:
        "The madrasa slug or institution ID is missing, so a pairing code could not be created. Log out and log in again, or use the manual setup below.",
      advanced: "Advanced / manual setup",
      keyLabel: (name) => `${name} - connector key`,
      keyWord: "Key",
      copy: "Copy",
      commandLabel: "Set up by command (run in the connector folder)",
      commandWord: "Command",
      configLabel: "config.json (without the key)",
      configHint:
        "Do not put the key in config.json. `connector.exe setup` asks for it - paste the key above and it is saved to a separate secret file.",
      configWord: "Config",
      done: "Got it, I've copied it",
    },
    mapping: {
      userIdRequired: "Enter the K40 user ID (press ✕ to remove)",
      digitsOnly: "Numbers only",
      saved: (name) => `${name} - mapping saved`,
      saveFailed: "Could not save, please try again",
      cleared: (name) => `${name} - mapping removed`,
      clearFailed: "Could not remove",
      title: "{{student}} ↔ K40 User Mapping",
      subtitle:
        "Set which {{student}} each user ID enrolled on the K40 belongs to. Unmapped punches are not counted as attendance.",
      studentList: "{{student}} List",
      count: (n) => `${n}`,
      searchPlaceholder: "Search by name, roll or ID",
      allClasses: "All {{class}}es",
      listLoadFailed: "Could not load the {{student}} list",
      tryAgainDot: "Please try again.",
      retry: "Try again",
      noStudents: "No {{student}}s found",
      changeFilter: "Try a different search or {{class}} filter.",
      student: "{{student}}",
      class: "{{class}}",
      k40UserId: "K40 User ID",
      idRoll: (id, roll) => `ID: ${id}${roll ? ` · Roll: ${roll}` : ""}`,
      userIdPlaceholder: "e.g. 12",
      save: "Save",
      clearMapping: "Remove mapping",
      page: (p, total) => `Page ${p} / ${total}`,
      prev: "Previous",
      next: "Next",
      unmappedTitle: "Unmapped Device Users",
      unmappedHint: "Punches came from the device but aren't linked to any {{student}}",
      refresh: "Refresh",
      unmappedLoadFailed: "Could not load the list.",
      allMapped: "All device users are mapped.",
      userId: (id) => `User ID: ${id}`,
      unknownDevice: "Unknown device",
      punches: (n) => `${n} punches`,
      lastPunch: (v) => `Last: ${v}`,
      link: "Link",
      assigned: (user, name) => `User ${user} → ${name} linked`,
      assignFailed: "Could not link",
      assignTitle: (user) => `Link user ${user} to a {{student}}`,
      assignSearch: "{{student}} name, roll or ID",
      searching: "Searching...",
      typeToSearch: "Type a name to search",
      roll: (r) => ` · Roll ${r}`,
      alreadyUser: (id) => `Already user ${id}`,
      willReplace: (id) => `This {{student}}'s previous user ID (${id}) will be replaced.`,
      linking: "Linking...",
      card: "Card",
      autoAssign: "Auto-create IDs",
      autoAssignHint: "Create K40 IDs automatically for everyone without one",
      autoAssignTitle: "Auto-create IDs",
      autoAssignMessage: (scope) =>
        `${scope} — a new ID will be created for everyone without a K40 user ID; the connector writes them to the machine.`,
      autoAssignConfirm: "Create IDs",
      autoAssignDone: (n) => `Created ${n} new IDs`,
      autoAssignNone: "Everyone already has an ID",
      allStudentsScope: "All {{student}}s",
      cardsLink: "Card Enrollment",
    },
    today: {
      title: "Today's Attendance (Device)",
      subtitle: (s) => `Attendance from K40 device punches. Updates automatically every ${s} seconds.`,
      refresh: "Refresh",
      present: "Present",
      unmapped: "Unmapped",
      unmappedHint: "Link them on the mapping page",
      totalPunches: "Total Punches",
      lastSync: "Last Sync",
      date: "Date",
      device: "Device",
      allDevices: "All devices",
      backToToday: "Back to today",
      lastUpdate: (time) => `Last updated: ${time}`,
      loadFailed: "Could not load attendance",
      tryAgainDot: "Please try again.",
      retry: "Try again",
      noPunchToday: "No punches yet today",
      noAttendance: "No attendance on this date",
      emptyHint: "Check that the device is online and {{student}}s are mapped.",
      refreshFailed: "Refresh failed - showing previous data.",
      student: "{{student}}",
      id: "ID",
      class: "{{class}}",
      checkIn: "Check-in",
      sync: "Sync",
      sms: "SMS",
      syncTime: "Sync Time",
      tabs: { STUDENT: "{{student}}s", TEACHER: "{{teacher}}s", STAFF: "Staff" },
      nameCol: { STUDENT: "{{student}}", TEACHER: "{{teacher}}", STAFF: "Staff" },
      late: "Late",
      absent: "Absent",
      notArrived: "Not arrived yet",
      checkedOut: "Checked out",
      ofMapped: (n) => `of ${n} with a device ID`,
      rejected: (n) => `${n} punches not counted`,
      statusLabels: { PRESENT: "Present", LATE: "Late", ABSENT: "Absent", LEAVE: "Leave" },
      status: "Status",
      checkOut: "Check-out",
      roll: "Roll",
      rollShort: (r) => `Roll ${r}`,
      pin: (id) => `ID ${id}`,
      punchCount: (n) => `${n} punches`,
      holiday: (title) => `Holiday: ${title} — attendance/absence is not counted on this day.`,
      holidayWeekly: "Weekly off day — attendance/absence is not counted on this day.",
      punchesTitle: "Punches",
      notArrivedTitle: "Not arrived yet",
      notArrivedHint: "Have a device ID but no punch on this day",
      allArrived: "Everyone with a device ID has punched.",
      showAll: (n) => `Show all (${n})`,
      showLess: "Show less",
      classTitle: "{{class}}-wise summary",
      classCol: "{{class}}",
      mappedCol: "With ID",
      presentCol: "Present",
      lateCol: "Late",
      absentCol: "Absent",
      notArrivedCol: "Not arrived",
      rateCol: "Attendance rate",
      noClass: "No {{class}}",
      exportCsv: "Download CSV",
      csvName: "Name",
      csvType: "Type",
      csvDeviceId: "Device ID",
      csvClass: "{{class}}",
      csvRoll: "Roll",
      csvStatus: "Status",
      csvCheckIn: "Check-in",
      csvCheckOut: "Check-out",
      csvDevice: "Device",
      csvNoPunch: "No punch",
      settingsLink: "Device Settings",
      cardsLink: "Card Enrollment",
    },
  },
});
