import { defineText } from "@madrasha/shared-ui/src/i18n";

/** UI text for the K40 attendance-device screens (devices, mapping, today). */
export const attendanceDeviceText = defineText({
  bn: {
    time: {
      never: "কখনো নয়",
      justNow: "এইমাত্র",
      seconds: (n: string) => `${n} সেকেন্ড আগে`,
      minutes: (n: string) => `${n} মিনিট আগে`,
      hours: (n: string) => `${n} ঘণ্টা আগে`,
      days: (n: string) => `${n} দিন আগে`,
      months: (n: string) => `${n} মাস আগে`,
      years: (n: string) => `${n} বছর আগে`,
    },
    deviceStatus: { online: "অনলাইন", offline: "অফলাইন", unknown: "অজানা", inactive: "নিষ্ক্রিয়" },
    syncStatus: { PENDING: "অপেক্ষমাণ", SYNCING: "সিঙ্ক হচ্ছে", SYNCED: "সিঙ্ক হয়েছে", FAILED: "ব্যর্থ" },
    smsStatus: { PENDING: "অপেক্ষমাণ", PROCESSING: "পাঠানো হচ্ছে", SENT: "পাঠানো হয়েছে", FAILED: "ব্যর্থ" },
    strip: {
      loadFailed: "ডিভাইসের অবস্থা লোড করা যায়নি",
      none: "কোনো ডিভাইস যোগ করা হয়নি",
      lastContact: "সর্বশেষ যোগাযোগ:",
      refreshFailed: "রিফ্রেশ ব্যর্থ - পুরনো তথ্য দেখানো হচ্ছে",
    },
    devices: {
      testTimeout: (s: string) => `${s} সেকেন্ডে কোনো সাড়া মেলেনি - কানেক্টর চালু আছে কিনা দেখুন`,
      testOk: "ডিভাইসের সাথে সংযোগ সফল হয়েছে",
      testFailed: "ডিভাইসের সাথে সংযোগ হয়নি",
      testRequested: "টেস্ট অনুরোধ পাঠানো হয়েছে, কানেক্টরের সাড়ার অপেক্ষা...",
      deactivated: "ডিভাইস নিষ্ক্রিয় করা হয়েছে",
      activated: "ডিভাইস সক্রিয় করা হয়েছে",
      rotateTitle: "কানেক্টর কী পরিবর্তন করুন",
      rotateMessage: (name: string) =>
        `"${name}" ডিভাইসের নতুন কী তৈরি হবে। পুরনো কী সাথে সাথে অচল হয়ে যাবে, কানেক্টরে নতুন কী বসাতে হবে।`,
      rotateConfirm: "নতুন কী তৈরি করুন",
      deleteTitle: "ডিভাইস ডিলিট করুন",
      deleteMessage: (name: string) =>
        `"${name}" ডিভাইসটি মুছে ফেলতে চান? কানেক্টর আর এই ডিভাইসের হয়ে ডেটা পাঠাতে পারবে না।`,
      deleteConfirm: "ডিলিট করুন",
      deleted: "ডিভাইস মুছে ফেলা হয়েছে",
      testing: (s: string) => `টেস্ট চলছে - কানেক্টরের সাড়ার অপেক্ষা (সর্বোচ্চ ${s} সেকেন্ড)...`,
      title: "উপস্থিতি ডিভাইস",
      subtitle:
        "ZKTeco K40 ডিভাইস যোগ করুন ও অবস্থা দেখুন। ডিভাইসের কাছাকাছি চলা কানেক্টর প্রোগ্রাম এই তালিকা থেকে সংযোগের তথ্য নেয়।",
      refresh: "রিফ্রেশ",
      newDevice: "নতুন ডিভাইস",
      allDevices: "সব ডিভাইস",
      autoUpdateHint: (s: string) => `প্রতি ${s} সেকেন্ডে অবস্থা নিজে থেকে আপডেট হয়`,
      listLoadFailed: "ডিভাইস তালিকা লোড করা যায়নি",
      checkInternet: "ইন্টারনেট সংযোগ দেখে আবার চেষ্টা করুন।",
      retry: "আবার চেষ্টা করুন",
      emptyTitle: "এখনো কোনো ডিভাইস যোগ করা হয়নি",
      emptyHint: "K40 ডিভাইসের আইপি ও পোর্ট দিয়ে প্রথম ডিভাইসটি যোগ করুন।",
      id: (id: string) => `আইডি: ${id}`,
      polling: (s: string) => `পোলিং প্রতি ${s} সেকেন্ড`,
      connectionTest: "কানেকশন টেস্ট",
      edit: "সম্পাদনা",
      rotateKey: "কী পরিবর্তন",
      deactivate: "নিষ্ক্রিয় করুন",
      activate: "সক্রিয় করুন",
      delete: "মুছুন",
      connectorLastContact: "কানেক্টর সর্বশেষ যোগাযোগ",
      neverConnected: "কখনো সংযুক্ত হয়নি",
      deviceLastContact: "ডিভাইসে সর্বশেষ সংযোগ",
      lastSync: "সর্বশেষ সিঙ্ক",
      lastError: (e: string) => `সর্বশেষ ত্রুটি: ${e}`,
    },
    form: {
      deviceIdRequired: "ডিভাইস আইডি দিন",
      nameRequired: "ডিভাইসের নাম দিন",
      ipRequired: "আইপি অ্যাড্রেস দিন",
      ipInvalid: "সঠিক আইপি অ্যাড্রেস দিন (যেমন 192.168.1.201)",
      portInvalid: (min: string, max: string) => `${min} থেকে ${max} এর মধ্যে পোর্ট দিন`,
      pollInvalid: (min: string, max: string) => `${min} থেকে ${max} সেকেন্ডের মধ্যে দিন`,
      updated: "ডিভাইস আপডেট হয়েছে",
      added: "ডিভাইস যোগ করা হয়েছে",
      editTitle: "ডিভাইস সম্পাদনা",
      newTitle: "নতুন উপস্থিতি ডিভাইস",
      deviceId: "ডিভাইস আইডি",
      deviceIdPlaceholder: "যেমন: 1",
      deviceIdLocked: "ডিভাইস আইডি পরিবর্তন করা যায় না",
      name: "নাম",
      namePlaceholder: "যেমন: মেইন গেট K40",
      ip: "আইপি অ্যাড্রেস",
      port: "পোর্ট",
      commKey: "কমিউনিকেশন কী (ঐচ্ছিক)",
      commKeyKeep: "খালি রাখলে আগেরটিই থাকবে",
      commKeyNew: "ডিভাইসে সেট করা থাকলে দিন",
      commKeyHint: "এটি শুধু সেভ হয়, পরে আর দেখানো হয় না",
      pollInterval: "পোলিং ব্যবধান (সেকেন্ড)",
      saving: "সেভ হচ্ছে...",
    },
    key: {
      copied: (label: string) => `${label} কপি হয়েছে`,
      copyFailed: "কপি করা যায়নি, হাতে নির্বাচন করে কপি করুন",
      setupComment: "# connector setup চালালে এই কী বসাতে বলবে",
      newTitle: "নতুন কানেক্টর কী",
      title: "কানেক্টর কী",
      warning: "এই কী আর কখনো দেখানো হবে না। এখনই কপি করে কানেক্টরের কনফিগে বসিয়ে নিন।",
      oldInvalid: " আগের কী এখন থেকে আর কাজ করবে না।",
      keyLabel: (name: string) => `${name} - কানেক্টর কী`,
      keyWord: "কী",
      copy: "কপি",
      setupLabel: "কানেক্টর সেটআপ (কনফিগ ফাইলে বসান)",
      configWord: "কনফিগ",
      copyAll: "সব কপি",
      done: "বুঝেছি, কপি করেছি",
    },
    mapping: {
      userIdRequired: "K40 ইউজার আইডি দিন (মুছতে ✕ চাপুন)",
      digitsOnly: "শুধু সংখ্যা দেওয়া যাবে",
      saved: (name: string) => `${name} - ম্যাপিং সেভ হয়েছে`,
      saveFailed: "সেভ করা যায়নি, আবার চেষ্টা করুন",
      cleared: (name: string) => `${name} - ম্যাপিং মুছে ফেলা হয়েছে`,
      clearFailed: "মুছতে সমস্যা হয়েছে",
      title: "{{student}} ↔ K40 ইউজার ম্যাপিং",
      subtitle:
        "K40 ডিভাইসে নথিভুক্ত প্রতিটি ইউজার আইডি কোন {{student}}র, তা এখানে ঠিক করুন। ম্যাপ না হলে পাঞ্চ থেকে উপস্থিতি গণনা হবে না।",
      studentList: "{{student}} তালিকা",
      count: (n: string) => `${n} জন`,
      searchPlaceholder: "নাম, রোল বা আইডি দিয়ে খুঁজুন",
      allClasses: "সব {{class}}",
      listLoadFailed: "{{student}} তালিকা লোড করা যায়নি",
      tryAgainDot: "আবার চেষ্টা করুন।",
      retry: "আবার চেষ্টা করুন",
      noStudents: "কোনো {{student}} পাওয়া যায়নি",
      changeFilter: "সার্চ বা {{class}} ফিল্টার বদলে দেখুন।",
      student: "{{student}}",
      class: "{{class}}",
      k40UserId: "K40 ইউজার আইডি",
      idRoll: (id: string, roll: string | null) => `আইডি: ${id}${roll ? ` · রোল: ${roll}` : ""}`,
      userIdPlaceholder: "যেমন: 12",
      save: "সেভ করুন",
      clearMapping: "ম্যাপিং মুছুন",
      page: (p: string, total: string) => `পৃষ্ঠা ${p} / ${total}`,
      prev: "আগের",
      next: "পরের",
      unmappedTitle: "ম্যাপ না হওয়া ডিভাইস ইউজার",
      unmappedHint: "ডিভাইস থেকে পাঞ্চ এসেছে, কিন্তু কোনো {{student}}র সাথে যুক্ত নয়",
      refresh: "রিফ্রেশ",
      unmappedLoadFailed: "তালিকা লোড করা যায়নি।",
      allMapped: "সব ডিভাইস ইউজার ম্যাপ করা আছে।",
      userId: (id: string) => `ইউজার আইডি: ${id}`,
      unknownDevice: "অজানা ডিভাইস",
      punches: (n: string) => `${n}টি পাঞ্চ`,
      lastPunch: (v: string) => `সর্বশেষ: ${v}`,
      link: "যুক্ত করুন",
      assigned: (user: string, name: string) => `ইউজার ${user} → ${name} যুক্ত হয়েছে`,
      assignFailed: "যুক্ত করা যায়নি",
      assignTitle: (user: string) => `ইউজার ${user} কে {{student}}র সাথে যুক্ত করুন`,
      assignSearch: "{{student}}র নাম, রোল বা আইডি",
      searching: "খোঁজা হচ্ছে...",
      typeToSearch: "খুঁজতে নাম লিখুন",
      roll: (r: string) => ` · রোল ${r}`,
      alreadyUser: (id: string) => `আগে থেকে ইউজার ${id}`,
      willReplace: (id: string) => `এই {{student}}র আগের ইউজার আইডি (${id}) বদলে যাবে।`,
      linking: "যুক্ত হচ্ছে...",
    },
    today: {
      title: "আজকের উপস্থিতি (ডিভাইস)",
      subtitle: (s: string) => `K40 ডিভাইসের পাঞ্চ থেকে আসা উপস্থিতি। প্রতি ${s} সেকেন্ডে নিজে থেকে আপডেট হয়।`,
      refresh: "রিফ্রেশ",
      present: "উপস্থিত",
      unmapped: "ম্যাপ হয়নি",
      unmappedHint: "ম্যাপিং পেজে গিয়ে যুক্ত করুন",
      totalPunches: "মোট পাঞ্চ",
      lastSync: "সর্বশেষ সিঙ্ক",
      date: "তারিখ",
      device: "ডিভাইস",
      allDevices: "সব ডিভাইস",
      backToToday: "আজকের তারিখে ফিরুন",
      lastUpdate: (time: string) => `সর্বশেষ আপডেট: ${time}`,
      loadFailed: "উপস্থিতি লোড করা যায়নি",
      tryAgainDot: "আবার চেষ্টা করুন।",
      retry: "আবার চেষ্টা করুন",
      noPunchToday: "আজ এখনো কোনো পাঞ্চ আসেনি",
      noAttendance: "এই তারিখে কোনো উপস্থিতি নেই",
      emptyHint: "ডিভাইস অনলাইন আছে কিনা এবং {{student}}দের ম্যাপিং করা আছে কিনা দেখুন।",
      refreshFailed: "রিফ্রেশ ব্যর্থ হয়েছে - আগের তথ্য দেখানো হচ্ছে।",
      student: "{{student}}",
      id: "আইডি",
      class: "{{class}}",
      checkIn: "চেক-ইন",
      sync: "সিঙ্ক",
      sms: "SMS",
      syncTime: "সিঙ্কের সময়",
    },
  },
  en: {
    time: {
      never: "Never",
      justNow: "Just now",
      seconds: (n) => `${n} sec ago`,
      minutes: (n) => `${n} min ago`,
      hours: (n) => `${n} hr ago`,
      days: (n) => `${n} days ago`,
      months: (n) => `${n} months ago`,
      years: (n) => `${n} years ago`,
    },
    deviceStatus: { online: "Online", offline: "Offline", unknown: "Unknown", inactive: "Inactive" },
    syncStatus: { PENDING: "Pending", SYNCING: "Syncing", SYNCED: "Synced", FAILED: "Failed" },
    smsStatus: { PENDING: "Pending", PROCESSING: "Sending", SENT: "Sent", FAILED: "Failed" },
    strip: {
      loadFailed: "Could not load device status",
      none: "No devices added",
      lastContact: "Last contact:",
      refreshFailed: "Refresh failed - showing older data",
    },
    devices: {
      testTimeout: (s) => `No response within ${s} seconds - check that the connector is running`,
      testOk: "Connected to the device successfully",
      testFailed: "Could not connect to the device",
      testRequested: "Test request sent, waiting for the connector...",
      deactivated: "Device deactivated",
      activated: "Device activated",
      rotateTitle: "Change Connector Key",
      rotateMessage: (name) =>
        `A new key will be created for "${name}". The old key stops working immediately; the connector must be given the new key.`,
      rotateConfirm: "Create New Key",
      deleteTitle: "Delete Device",
      deleteMessage: (name) =>
        `Delete the device "${name}"? The connector will no longer be able to send data for it.`,
      deleteConfirm: "Delete",
      deleted: "Device deleted",
      testing: (s) => `Testing - waiting for the connector (up to ${s} seconds)...`,
      title: "Attendance Devices",
      subtitle:
        "Add ZKTeco K40 devices and see their status. The connector program running near the device reads its connection details from this list.",
      refresh: "Refresh",
      newDevice: "New Device",
      allDevices: "All Devices",
      autoUpdateHint: (s) => `Status updates automatically every ${s} seconds`,
      listLoadFailed: "Could not load the device list",
      checkInternet: "Check your internet connection and try again.",
      retry: "Try again",
      emptyTitle: "No devices added yet",
      emptyHint: "Add your first device using the K40's IP address and port.",
      id: (id) => `ID: ${id}`,
      polling: (s) => `polling every ${s} sec`,
      connectionTest: "Connection Test",
      edit: "Edit",
      rotateKey: "Change key",
      deactivate: "Deactivate",
      activate: "Activate",
      delete: "Delete",
      connectorLastContact: "Connector last contact",
      neverConnected: "Never connected",
      deviceLastContact: "Last device contact",
      lastSync: "Last sync",
      lastError: (e) => `Last error: ${e}`,
    },
    form: {
      deviceIdRequired: "Enter the device ID",
      nameRequired: "Enter the device name",
      ipRequired: "Enter the IP address",
      ipInvalid: "Enter a valid IP address (e.g. 192.168.1.201)",
      portInvalid: (min, max) => `Enter a port between ${min} and ${max}`,
      pollInvalid: (min, max) => `Enter between ${min} and ${max} seconds`,
      updated: "Device updated",
      added: "Device added",
      editTitle: "Edit Device",
      newTitle: "New Attendance Device",
      deviceId: "Device ID",
      deviceIdPlaceholder: "e.g. 1",
      deviceIdLocked: "The device ID cannot be changed",
      name: "Name",
      namePlaceholder: "e.g. Main Gate K40",
      ip: "IP Address",
      port: "Port",
      commKey: "Communication key (optional)",
      commKeyKeep: "Leave empty to keep the current one",
      commKeyNew: "Enter it if set on the device",
      commKeyHint: "It is only saved, never shown again",
      pollInterval: "Polling interval (seconds)",
      saving: "Saving...",
    },
    key: {
      copied: (label) => `${label} copied`,
      copyFailed: "Could not copy; select it and copy manually",
      setupComment: "# connector setup will ask for this key",
      newTitle: "New Connector Key",
      title: "Connector Key",
      warning: "This key will never be shown again. Copy it now into the connector's config.",
      oldInvalid: " The old key no longer works.",
      keyLabel: (name) => `${name} - connector key`,
      keyWord: "Key",
      copy: "Copy",
      setupLabel: "Connector setup (put in the config file)",
      configWord: "Config",
      copyAll: "Copy all",
      done: "Got it, I've copied it",
    },
    mapping: {
      userIdRequired: "Enter the K40 user ID (press ✕ to remove)",
      digitsOnly: "Numbers only",
      saved: (name) => `${name} - mapping saved`,
      saveFailed: "Could not save, please try again",
      cleared: (name) => `${name} - mapping removed`,
      clearFailed: "Could not remove",
      title: "{{student}} ↔ K40 User Mapping",
      subtitle:
        "Set which {{student}} each user ID enrolled on the K40 belongs to. Unmapped punches are not counted as attendance.",
      studentList: "{{student}} List",
      count: (n) => `${n}`,
      searchPlaceholder: "Search by name, roll or ID",
      allClasses: "All {{class}}es",
      listLoadFailed: "Could not load the {{student}} list",
      tryAgainDot: "Please try again.",
      retry: "Try again",
      noStudents: "No {{student}}s found",
      changeFilter: "Try a different search or {{class}} filter.",
      student: "{{student}}",
      class: "{{class}}",
      k40UserId: "K40 User ID",
      idRoll: (id, roll) => `ID: ${id}${roll ? ` · Roll: ${roll}` : ""}`,
      userIdPlaceholder: "e.g. 12",
      save: "Save",
      clearMapping: "Remove mapping",
      page: (p, total) => `Page ${p} / ${total}`,
      prev: "Previous",
      next: "Next",
      unmappedTitle: "Unmapped Device Users",
      unmappedHint: "Punches came from the device but aren't linked to any {{student}}",
      refresh: "Refresh",
      unmappedLoadFailed: "Could not load the list.",
      allMapped: "All device users are mapped.",
      userId: (id) => `User ID: ${id}`,
      unknownDevice: "Unknown device",
      punches: (n) => `${n} punches`,
      lastPunch: (v) => `Last: ${v}`,
      link: "Link",
      assigned: (user, name) => `User ${user} → ${name} linked`,
      assignFailed: "Could not link",
      assignTitle: (user) => `Link user ${user} to a {{student}}`,
      assignSearch: "{{student}} name, roll or ID",
      searching: "Searching...",
      typeToSearch: "Type a name to search",
      roll: (r) => ` · Roll ${r}`,
      alreadyUser: (id) => `Already user ${id}`,
      willReplace: (id) => `This {{student}}'s previous user ID (${id}) will be replaced.`,
      linking: "Linking...",
    },
    today: {
      title: "Today's Attendance (Device)",
      subtitle: (s) => `Attendance from K40 device punches. Updates automatically every ${s} seconds.`,
      refresh: "Refresh",
      present: "Present",
      unmapped: "Unmapped",
      unmappedHint: "Link them on the mapping page",
      totalPunches: "Total Punches",
      lastSync: "Last Sync",
      date: "Date",
      device: "Device",
      allDevices: "All devices",
      backToToday: "Back to today",
      lastUpdate: (time) => `Last updated: ${time}`,
      loadFailed: "Could not load attendance",
      tryAgainDot: "Please try again.",
      retry: "Try again",
      noPunchToday: "No punches yet today",
      noAttendance: "No attendance on this date",
      emptyHint: "Check that the device is online and {{student}}s are mapped.",
      refreshFailed: "Refresh failed - showing previous data.",
      student: "{{student}}",
      id: "ID",
      class: "{{class}}",
      checkIn: "Check-in",
      sync: "Sync",
      sms: "SMS",
      syncTime: "Sync Time",
    },
  },
  ar: {
    time: {
      never: "أبدًا",
      justNow: "الآن",
      seconds: (n) => `قبل ${n} ثانية`,
      minutes: (n) => `قبل ${n} دقيقة`,
      hours: (n) => `قبل ${n} ساعة`,
      days: (n) => `قبل ${n} يوم`,
      months: (n) => `قبل ${n} شهر`,
      years: (n) => `قبل ${n} سنة`,
    },
    deviceStatus: { online: "متصل", offline: "غير متصل", unknown: "غير معروف", inactive: "غير نشط" },
    syncStatus: { PENDING: "قيد الانتظار", SYNCING: "جارٍ المزامنة", SYNCED: "تمت المزامنة", FAILED: "فشل" },
    smsStatus: { PENDING: "قيد الانتظار", PROCESSING: "جارٍ الإرسال", SENT: "تم الإرسال", FAILED: "فشل" },
    strip: {
      loadFailed: "تعذّر تحميل حالة الأجهزة",
      none: "لم تُضَف أي أجهزة",
      lastContact: "آخر اتصال:",
      refreshFailed: "فشل التحديث - تُعرض بيانات قديمة",
    },
    devices: {
      testTimeout: (s) => `لا استجابة خلال ${s} ثانية - تأكد من تشغيل برنامج الربط`,
      testOk: "تم الاتصال بالجهاز بنجاح",
      testFailed: "تعذّر الاتصال بالجهاز",
      testRequested: "أُرسل طلب الاختبار، بانتظار استجابة برنامج الربط...",
      deactivated: "تم تعطيل الجهاز",
      activated: "تم تفعيل الجهاز",
      rotateTitle: "تغيير مفتاح برنامج الربط",
      rotateMessage: (name) =>
        `سيُنشأ مفتاح جديد للجهاز "${name}". يتوقف المفتاح القديم فورًا، ويجب إدخال المفتاح الجديد في برنامج الربط.`,
      rotateConfirm: "إنشاء مفتاح جديد",
      deleteTitle: "حذف الجهاز",
      deleteMessage: (name) => `هل تريد حذف الجهاز "${name}"؟ لن يتمكن برنامج الربط من إرسال بياناته بعد ذلك.`,
      deleteConfirm: "حذف",
      deleted: "تم حذف الجهاز",
      testing: (s) => `جارٍ الاختبار - بانتظار برنامج الربط (حتى ${s} ثانية)...`,
      title: "أجهزة الحضور",
      subtitle:
        "أضف أجهزة ZKTeco K40 واطّلع على حالتها. يأخذ برنامج الربط العامل قرب الجهاز بيانات الاتصال من هذه القائمة.",
      refresh: "تحديث",
      newDevice: "جهاز جديد",
      allDevices: "جميع الأجهزة",
      autoUpdateHint: (s) => `تُحدَّث الحالة تلقائيًا كل ${s} ثانية`,
      listLoadFailed: "تعذّر تحميل قائمة الأجهزة",
      checkInternet: "تحقق من اتصال الإنترنت وأعد المحاولة.",
      retry: "أعد المحاولة",
      emptyTitle: "لم تُضَف أي أجهزة بعد",
      emptyHint: "أضف أول جهاز باستخدام عنوان IP والمنفذ لجهاز K40.",
      id: (id) => `المعرّف: ${id}`,
      polling: (s) => `الاستطلاع كل ${s} ثانية`,
      connectionTest: "اختبار الاتصال",
      edit: "تعديل",
      rotateKey: "تغيير المفتاح",
      deactivate: "تعطيل",
      activate: "تفعيل",
      delete: "حذف",
      connectorLastContact: "آخر اتصال لبرنامج الربط",
      neverConnected: "لم يتصل أبدًا",
      deviceLastContact: "آخر اتصال بالجهاز",
      lastSync: "آخر مزامنة",
      lastError: (e) => `آخر خطأ: ${e}`,
    },
    form: {
      deviceIdRequired: "أدخل معرّف الجهاز",
      nameRequired: "أدخل اسم الجهاز",
      ipRequired: "أدخل عنوان IP",
      ipInvalid: "أدخل عنوان IP صحيحًا (مثل 192.168.1.201)",
      portInvalid: (min, max) => `أدخل منفذًا بين ${min} و${max}`,
      pollInvalid: (min, max) => `أدخل قيمة بين ${min} و${max} ثانية`,
      updated: "تم تحديث الجهاز",
      added: "تمت إضافة الجهاز",
      editTitle: "تعديل الجهاز",
      newTitle: "جهاز حضور جديد",
      deviceId: "معرّف الجهاز",
      deviceIdPlaceholder: "مثال: 1",
      deviceIdLocked: "لا يمكن تغيير معرّف الجهاز",
      name: "الاسم",
      namePlaceholder: "مثال: البوابة الرئيسية K40",
      ip: "عنوان IP",
      port: "المنفذ",
      commKey: "مفتاح الاتصال (اختياري)",
      commKeyKeep: "اتركه فارغًا للإبقاء على الحالي",
      commKeyNew: "أدخله إن كان مضبوطًا على الجهاز",
      commKeyHint: "يُحفظ فقط ولا يُعرض مرة أخرى",
      pollInterval: "فاصل الاستطلاع (بالثواني)",
      saving: "جارٍ الحفظ...",
    },
    key: {
      copied: (label) => `تم نسخ ${label}`,
      copyFailed: "تعذّر النسخ، حدّده وانسخه يدويًا",
      setupComment: "# connector setup سيطلب هذا المفتاح",
      newTitle: "مفتاح برنامج الربط الجديد",
      title: "مفتاح برنامج الربط",
      warning: "لن يُعرض هذا المفتاح مرة أخرى. انسخه الآن وضعه في إعدادات برنامج الربط.",
      oldInvalid: " المفتاح القديم لم يعد يعمل.",
      keyLabel: (name) => `${name} - مفتاح برنامج الربط`,
      keyWord: "المفتاح",
      copy: "نسخ",
      setupLabel: "إعداد برنامج الربط (ضعه في ملف الإعدادات)",
      configWord: "الإعدادات",
      copyAll: "نسخ الكل",
      done: "فهمت، قمت بالنسخ",
    },
    mapping: {
      userIdRequired: "أدخل معرّف مستخدم K40 (اضغط ✕ للحذف)",
      digitsOnly: "أرقام فقط",
      saved: (name) => `${name} - تم حفظ الربط`,
      saveFailed: "تعذّر الحفظ، أعد المحاولة",
      cleared: (name) => `${name} - تم حذف الربط`,
      clearFailed: "تعذّر الحذف",
      title: "ربط {{student}} ↔ مستخدم K40",
      subtitle:
        "حدّد هنا لأي {{student}} يعود كل معرّف مستخدم مسجّل في جهاز K40. البصمات غير المربوطة لا تُحتسب حضورًا.",
      studentList: "قائمة الطلاب",
      count: (n) => `${n}`,
      searchPlaceholder: "ابحث بالاسم أو رقم الجلوس أو المعرّف",
      allClasses: "جميع الصفوف",
      listLoadFailed: "تعذّر تحميل قائمة الطلاب",
      tryAgainDot: "أعد المحاولة.",
      retry: "أعد المحاولة",
      noStudents: "لم يوجد أي {{student}}",
      changeFilter: "جرّب بحثًا آخر أو غيّر تصفية {{class}}.",
      student: "{{student}}",
      class: "{{class}}",
      k40UserId: "معرّف مستخدم K40",
      idRoll: (id, roll) => `المعرّف: ${id}${roll ? ` · رقم الجلوس: ${roll}` : ""}`,
      userIdPlaceholder: "مثال: 12",
      save: "حفظ",
      clearMapping: "حذف الربط",
      page: (p, total) => `الصفحة ${p} / ${total}`,
      prev: "السابق",
      next: "التالي",
      unmappedTitle: "مستخدمو الجهاز غير المربوطين",
      unmappedHint: "وصلت بصمات من الجهاز لكنها غير مربوطة بأي {{student}}",
      refresh: "تحديث",
      unmappedLoadFailed: "تعذّر تحميل القائمة.",
      allMapped: "جميع مستخدمي الجهاز مربوطون.",
      userId: (id) => `معرّف المستخدم: ${id}`,
      unknownDevice: "جهاز غير معروف",
      punches: (n) => `${n} بصمة`,
      lastPunch: (v) => `الأخيرة: ${v}`,
      link: "ربط",
      assigned: (user, name) => `تم ربط المستخدم ${user} → ${name}`,
      assignFailed: "تعذّر الربط",
      assignTitle: (user) => `ربط المستخدم ${user} بـ{{student}}`,
      assignSearch: "اسم {{student}} أو رقم الجلوس أو المعرّف",
      searching: "جارٍ البحث...",
      typeToSearch: "اكتب اسمًا للبحث",
      roll: (r) => ` · رقم الجلوس ${r}`,
      alreadyUser: (id) => `مرتبط مسبقًا بالمستخدم ${id}`,
      willReplace: (id) => `سيُستبدل معرّف المستخدم السابق لهذا {{student}} (${id}).`,
      linking: "جارٍ الربط...",
    },
    today: {
      title: "حضور اليوم (الجهاز)",
      subtitle: (s) => `الحضور المسجّل من بصمات جهاز K40. يُحدَّث تلقائيًا كل ${s} ثانية.`,
      refresh: "تحديث",
      present: "حاضر",
      unmapped: "غير مربوط",
      unmappedHint: "اربطهم من صفحة الربط",
      totalPunches: "إجمالي البصمات",
      lastSync: "آخر مزامنة",
      date: "التاريخ",
      device: "الجهاز",
      allDevices: "جميع الأجهزة",
      backToToday: "العودة إلى اليوم",
      lastUpdate: (time) => `آخر تحديث: ${time}`,
      loadFailed: "تعذّر تحميل الحضور",
      tryAgainDot: "أعد المحاولة.",
      retry: "أعد المحاولة",
      noPunchToday: "لم تصل أي بصمة اليوم بعد",
      noAttendance: "لا يوجد حضور في هذا التاريخ",
      emptyHint: "تأكد من أن الجهاز متصل وأن الطلاب مربوطون.",
      refreshFailed: "فشل التحديث - تُعرض البيانات السابقة.",
      student: "{{student}}",
      id: "المعرّف",
      class: "{{class}}",
      checkIn: "تسجيل الدخول",
      sync: "المزامنة",
      sms: "SMS",
      syncTime: "وقت المزامنة",
    },
  },
});
