import { defineBilingualText } from "@madrasha/shared-ui/src/i18n";

/** Shared super-admin components: institutions table, search bar,
 * clean-data and permanent-delete modals. */
export const superAdminText = defineBilingualText({
  bn: {
    // SearchPaginationBar
    searchByNameSlug: "নাম/স্লাগ দিয়ে খুঁজুন...",
    pageOf: "পৃষ্ঠা",
    totalLabel: "মোট",
    prev: "আগের",
    next: "পরের",

    // MadrasasTable
    selectPlan: "প্ল্যান বাছাই করুন",
    suspend: "স্থগিত করুন",
    activate: "সক্রিয় করুন",
    trash: "ট্র্যাশ",
    cleanDataTitle: "এই প্রতিষ্ঠানের ডেটা মুছে ফেলুন (পাসওয়ার্ড ভেরিফাই সহ)",
    cleanData: "ডেটা ক্লিন",
    staffPermissions: "স্টাফ ও পারমিশন",
    noInstitutions: "কোনো প্রতিষ্ঠান পাওয়া যায়নি।",
    selectRow: (name: string) => `${name} নির্বাচন করুন`,
    selectAll: "সব নির্বাচন করুন",
    colName: "নাম",
    colSlug: "স্লাগ",
    colType: "ধরন",
    colLanguage: "ভাষা",
    colWebsite: "ওয়েবসাইট",
    colPlan: "প্ল্যান",
    colStudentLimit: "শিক্ষার্থী লিমিট",
    colUserLimit: "ইউজার লিমিট",
    colStatus: "স্ট্যাটাস",
    colActions: "অ্যাকশন",
    websiteStatus: { active: "সক্রিয়", limited: "সীমিত", disabled: "বন্ধ" } as Record<string, string>,

    // CleanMadrasaModal
    cleanTitle: (name: string) => `"${name}" এর ডেটা ক্লিন করুন`,
    cleanIrreversible: "এই কাজ অপরিবর্তনীয় - মুছে যাওয়া ডেটা আর ফিরিয়ে আনা যাবে না।",
    modeOperational: "শুধু অপারেশনাল ডেটা",
    modeOperationalDesc:
      "ছাত্র, ভর্তি, ফি স্ট্রাকচার/ইনভয়েস/পেমেন্ট, একাউন্ট, উপস্থিতি, পরীক্ষা/রেজাল্ট/রুটিন, লাইব্রেরি ইস্যু, নোটিফিকেশন ও অ্যাক্টিভিটি লগ মুছে যাবে। প্রতিষ্ঠানের সেটিংস, বিভাগ/শ্রেণি/বিষয় কাঠামো, স্টাফ/শিক্ষক/ইউজার লগইন ও রোল-পারমিশন অক্ষত থাকবে।",
    modeFull: "একদম সব কিছু (ফ্যাক্টরি রিসেট)",
    modeFullDesc:
      "উপরের সব কিছুসহ সেটিংস, বিভাগ/শ্রেণি/বিষয় কাঠামো, স্টাফ/শিক্ষক, ওয়েবসাইট/ব্র্যান্ডিং, নথি টেমপ্লেট এবং প্রতিটি ইউজার লগইন-ও মুছে যাবে। শুধু প্রতিষ্ঠানের নাম/স্লাগ/প্ল্যান থাকবে - এরপর কেউ লগইন করতে পারবে না, যতক্ষণ না আপনি নতুন করে একটা ইউজার তৈরি করে দেন।",
    statStudents: "ছাত্র",
    statInvoices: "ইনভয়েস",
    statExams: "পরীক্ষা",
    statAttendance: "উপস্থিতি",
    statUsers: "ইউজার",
    statStaff: "স্টাফ/শিক্ষক",
    typeNameToConfirm: "নিশ্চিত করতে প্রতিষ্ঠানের নাম হুবহু লিখুন:",
    copyName: "নাম কপি করুন",
    acknowledge: "আমি নিশ্চিত যে এই ডেটা স্থায়ীভাবে মুছে ফেলতে চাই এবং জানি এটা আর ফিরিয়ে আনা যাবে না।",
    enterSuperAdminPassword: "আপনার সুপার অ্যাডমিন পাসওয়ার্ড দিন",
    showPassword: "পাসওয়ার্ড দেখান",
    hidePassword: "পাসওয়ার্ড লুকান",
    cleaning: "ক্লিন করা হচ্ছে...",
    cleanDataButton: "ডেটা ক্লিন করুন",

    // DeleteConfirmModal
    deleting: "মুছে ফেলা হচ্ছে...",
    permanentDeleteWarning: "স্থায়ীভাবে মুছে ফেলার সতর্কতা",
    willBePermanentlyDeleted: (n: string) => `${n}টি প্রতিষ্ঠান স্থায়ীভাবে মুছে ফেলা হবে`,
    statAccounts: "অ্যাকাউন্ট",
    cannotBeUndone: "এই কাজ আর ফেরানো যাবে না।",
    typeDeleteToConfirmBefore: "নিশ্চিত করতে ",
    typeDeleteToConfirmAfter: " লিখুন।",
    typeDeletePlaceholder: "DELETE লিখুন",
    permanentlyDelete: "স্থায়ীভাবে মুছুন",
  },
  en: {
    searchByNameSlug: "Search by name/slug...",
    pageOf: "Page",
    totalLabel: "Total",
    prev: "Prev",
    next: "Next",

    selectPlan: "Select plan",
    suspend: "Suspend",
    activate: "Activate",
    trash: "Trash",
    cleanDataTitle: "Wipe this institution's data (password verified)",
    cleanData: "Clean data",
    staffPermissions: "Staff & Permissions",
    noInstitutions: "No institutions found.",
    selectRow: (name) => `Select ${name}`,
    selectAll: "Select all",
    colName: "Name",
    colSlug: "Slug",
    colType: "Type",
    colLanguage: "Language",
    colWebsite: "Website",
    colPlan: "Plan",
    colStudentLimit: "Student Limit",
    colUserLimit: "User Limit",
    colStatus: "Status",
    colActions: "Actions",
    websiteStatus: { active: "Active", limited: "Limited", disabled: "Disabled" },

    cleanTitle: (name) => `Clean data of "${name}"`,
    cleanIrreversible: "This cannot be undone - deleted data can never be recovered.",
    modeOperational: "Operational data only",
    modeOperationalDesc:
      "Students, admissions, fee structures/invoices/payments, accounts, attendance, exams/results/routines, library issues, notifications and activity logs are deleted. The institution's settings, division/class/subject structure, staff/teacher/user logins and role permissions stay intact.",
    modeFull: "Everything (factory reset)",
    modeFullDesc:
      "Everything above plus settings, division/class/subject structure, staff/teachers, website/branding, document templates and every user login is deleted. Only the institution's name/slug/plan remain - nobody can log in until you create a new user.",
    statStudents: "Students",
    statInvoices: "Invoices",
    statExams: "Exams",
    statAttendance: "Attendance",
    statUsers: "Users",
    statStaff: "Staff/Teachers",
    typeNameToConfirm: "Type the institution name exactly to confirm:",
    copyName: "Copy name",
    acknowledge: "I am sure I want to permanently delete this data and understand it cannot be recovered.",
    enterSuperAdminPassword: "Enter your super admin password",
    showPassword: "Show password",
    hidePassword: "Hide password",
    cleaning: "Cleaning...",
    cleanDataButton: "Clean data",

    deleting: "Deleting...",
    permanentDeleteWarning: "Permanent Delete Warning",
    willBePermanentlyDeleted: (n) => `${n} institutions will be permanently deleted`,
    statAccounts: "Accounts",
    cannotBeUndone: "This action cannot be undone.",
    typeDeleteToConfirmBefore: "Type ",
    typeDeleteToConfirmAfter: " to confirm.",
    typeDeletePlaceholder: "Type DELETE",
    permanentlyDelete: "Permanently Delete",
  },
});
