import { defineText } from "@madrasha/shared-ui/src/i18n";

export const sessionText = defineText({
  bn: {
    divisionN: (id: string) => `{{division}} #${id}`,
    generic: "সাধারণ (সকল {{division}})",
    fillRequired: "নাম, শুরুর তারিখ ও শেষের তারিখ দিন",
    startBeforeEnd: "শুরুর তারিখ শেষের তারিখের আগে হতে হবে",
    created: "{{session}} তৈরি হয়েছে",
    createFailed: "{{session}} তৈরি করতে সমস্যা হয়েছে",
    updated: "{{session}} আপডেট হয়েছে",
    updateFailed: "{{session}} আপডেট করতে সমস্যা হয়েছে",
    nowActive: (name: string) => `"${name}" এখন সক্রিয় {{session}}`,
    setActiveFailed: "সক্রিয় {{session}} সেট করতে সমস্যা হয়েছে",
    deleteTitle: "{{session}} মুছে ফেলবেন?",
    deleteMessage: (name: string) => `"${name}" {{session}}টি স্থায়ীভাবে মুছে যাবে। এটি আর ফিরিয়ে আনা যাবে না।`,
    deleted: "{{session}} মুছে ফেলা হয়েছে",
    deleteFailed: "মুছতে সমস্যা হয়েছে",
    feeDeleteTitle: "ফি কাঠামো মুছে ফেলবেন?",
    feeDeleteMessage: (name: string) =>
      `"${name}" {{session}}ের ফি কাঠামোগুলো (কোনো ইনভয়েস তৈরি হয়নি এমনগুলো) স্থায়ীভাবে মুছে যাবে। এটি আর ফিরিয়ে আনা যাবে না।`,
    feeDeleted: "ফি কাঠামোগুলো মুছে ফেলা হয়েছে — এখন {{session}}টি আবার মুছে ফেলার চেষ্টা করুন",
    title: "{{session}} সেটআপ",
    subtitle: "{{session}} তৈরি করুন — প্রতিটি {{session}}ের শুরু ও শেষের তারিখ অনুযায়ী মাসিক ফি স্বয়ংক্রিয়ভাবে হিসাব হবে",
    newSession: "নতুন {{session}} তৈরি করুন",
    namePlaceholder: "{{session}}ের নাম (যেমন: ২০২৬)",
    noSessions: "কোনো {{session}} নেই",
    setActiveTitle: "সক্রিয় {{session}} হিসেবে সেট করুন",
    makeActive: "সক্রিয় করুন",
    editTitle: (name: string) => `{{session}} এডিট করুন — ${name}`,
    division: "{{division}}",
    startDate: "শুরুর তারিখ",
    endDate: "শেষের তারিখ",
    cannotDelete: "মুছে ফেলা যাচ্ছে না",
    understood: "বুঝেছি",
    goToTrash: "ট্র্যাশে যান",
    viewRejected: "বাতিল আবেদন দেখুন",
    deleteFeeStructures: "ফি কাঠামো মুছে ফেলুন",
    goToStudents: "{{student}} তালিকায় যান",
  },
  en: {
    divisionN: (id) => `{{division}} #${id}`,
    generic: "General (all {{division}}s)",
    fillRequired: "Enter the name, start date and end date",
    startBeforeEnd: "Start date must be before the end date",
    created: "{{session}} created",
    createFailed: "Could not create {{session}}",
    updated: "{{session}} updated",
    updateFailed: "Could not update {{session}}",
    nowActive: (name) => `"${name}" is now the active {{session}}`,
    setActiveFailed: "Could not set the active {{session}}",
    deleteTitle: "Delete {{session}}?",
    deleteMessage: (name) => `"${name}" will be deleted permanently. This cannot be undone.`,
    deleted: "{{session}} deleted",
    deleteFailed: "Could not delete",
    feeDeleteTitle: "Delete fee structures?",
    feeDeleteMessage: (name) =>
      `The fee structures of "${name}" (those without invoices) will be deleted permanently. This cannot be undone.`,
    feeDeleted: "Fee structures deleted — now try deleting the {{session}} again",
    title: "{{session}} Setup",
    subtitle: "Create {{session}}s — monthly fees are calculated automatically from each {{session}}'s start and end dates",
    newSession: "Create new {{session}}",
    namePlaceholder: "{{session}} name (e.g. 2026)",
    noSessions: "No {{session}}s",
    setActiveTitle: "Set as active {{session}}",
    makeActive: "Activate",
    editTitle: (name) => `Edit {{session}} — ${name}`,
    division: "{{division}}",
    startDate: "Start date",
    endDate: "End date",
    cannotDelete: "Cannot delete",
    understood: "Got it",
    goToTrash: "Go to trash",
    viewRejected: "View rejected applications",
    deleteFeeStructures: "Delete fee structures",
    goToStudents: "Go to {{student}} list",
  },
});
