import { defineBilingualText } from "@madrasha/shared-ui/src/i18n";

/** Default fee-structure templates copied into every new institution. */
export const feeTemplatesText = defineBilingualText({
  bn: {
    title: "ফি টেমপ্লেট",
    subtitle: "নতুন প্রতিষ্ঠান তৈরির সময় এই ফি কাঠামোগুলো স্বয়ংক্রিয়ভাবে কপি হয়ে যায়",
    frequency: { ONE_TIME: "একবার", MONTHLY: "মাসিক", YEARLY: "বাৎসরিক" },
    divisionsLoadFailed: "বিভাগ লোড করা যায়নি",
    classesLoadFailed: "শ্রেণি লোড করা যায়নি",
    itemsLoadFailed: "ফি টেমপ্লেট লোড করা যায়নি",
    nameAmountRequired: "নাম ও পরিমাণ দিন",
    created: "ফি টেমপ্লেট তৈরি হয়েছে",
    createFailed: "ফি টেমপ্লেট তৈরি করতে সমস্যা হয়েছে",
    updated: "ফি টেমপ্লেট আপডেট হয়েছে",
    updateFailed: "ফি টেমপ্লেট আপডেট করতে সমস্যা হয়েছে",
    deleted: "ফি টেমপ্লেট মুছে ফেলা হয়েছে",
    other: "অন্যান্য",
    classNo: (id: string) => `শ্রেণি #${id}`,
    genericGroup: "সাধারণ (সব শ্রেণির জন্য)",
    generic: "সাধারণ",
    divisionFilter: "বিভাগ (ফিল্টার)",
    classFilter: "শ্রেণি (ফিল্টার)",
    createHeading: "নতুন ফি টেমপ্লেট তৈরি করুন",
    forSelectedClass: "(নির্বাচিত শ্রেণির জন্য)",
    forAllClasses: "(সব শ্রেণির জন্য)",
    namePlaceholder: "নাম (যেমন: মাসিক বেতন)",
    amountTaka: "পরিমাণ (৳)",
    empty: "কোনো ফি টেমপ্লেট নেই",
    count: (n: string) => `${n}টি`,
    editTitle: (name: string) => `ফি টেমপ্লেট এডিট করুন — ${name}`,
    name: "নাম",
    frequencyLabel: "ফ্রিকোয়েন্সি",
    deleteTitle: "মুছে ফেলুন?",
    deleteMessage: (name: string) => `"${name}" ফি টেমপ্লেটটি মুছে ফেলতে চান?`,
  },
  en: {
    title: "Fee Templates",
    subtitle: "These fee structures are copied automatically when a new institution is created",
    frequency: { ONE_TIME: "One time", MONTHLY: "Monthly", YEARLY: "Yearly" },
    divisionsLoadFailed: "Could not load divisions",
    classesLoadFailed: "Could not load classes",
    itemsLoadFailed: "Could not load fee templates",
    nameAmountRequired: "Enter a name and amount",
    created: "Fee template created",
    createFailed: "Could not create the fee template",
    updated: "Fee template updated",
    updateFailed: "Could not update the fee template",
    deleted: "Fee template deleted",
    other: "Other",
    classNo: (id) => `Class #${id}`,
    genericGroup: "General (for every class)",
    generic: "General",
    divisionFilter: "Division (filter)",
    classFilter: "Class (filter)",
    createHeading: "Create a new fee template",
    forSelectedClass: "(for the selected class)",
    forAllClasses: "(for every class)",
    namePlaceholder: "Name (e.g. Monthly tuition)",
    amountTaka: "Amount (৳)",
    empty: "No fee templates yet",
    count: (n) => n,
    editTitle: (name) => `Edit fee template — ${name}`,
    name: "Name",
    frequencyLabel: "Frequency",
    deleteTitle: "Delete?",
    deleteMessage: (name) => `Delete the fee template "${name}"?`,
  },
});
