import { defineText } from "@madrasha/shared-ui/src/i18n";

/** Class & exam routine page. Also used (via usePrintText) for the printed routine. */
export const routineText = defineText({
  bn: {
    /** Full weekday names, index = Date#getDay() (0 = Sunday). */
    days: ["রবিবার", "সোমবার", "মঙ্গলবার", "বুধবার", "বৃহস্পতিবার", "শুক্রবার", "শনিবার"],
    statusDraft: "খসড়া",
    statusPublished: "প্রকাশিত",
    statusCancelled: "বাতিল",
    statusNone: "রুটিন নেই",
    statusMixed: "আংশিক",
    noDivisionAssigned: "{{division}} নির্ধারিত নেই",
    pickDivisionClassFirst: "প্রথমে {{division}} ও {{class}} নির্বাচন করুন",
    classFieldsRequired: "{{subject}}, শুরু ও শেষ সময় দিন",
    timeOrderError: (start: string, end: string) =>
      `শুরুর সময় (${start}) শেষের সময় (${end}) এর সমান বা পরে হয়ে গেছে। দুপুর ১২টা = 12:00, রাত ১২টা (মধ্যরাত) = 00:00 — AM/PM ঠিক আছে কিনা আবার দেখুন।`,
    routineAdded: "রুটিন যোগ করা হয়েছে",
    routineAddFailed: "রুটিন যোগ করতে সমস্যা হয়েছে",
    routineDeleted: "রুটিন মুছে ফেলা হয়েছে",
    deleteFailed: "মুছতে সমস্যা হয়েছে",
    pickExamClassFirst: "প্রথমে পরীক্ষা ও {{class}} নির্বাচন করুন",
    examFieldsRequired: "{{subject}}, তারিখ, শুরু ও শেষ সময় দিন",
    examRoutineAdded: "পরীক্ষার রুটিন যোগ করা হয়েছে",
    statusUpdated: "স্ট্যাটাস আপডেট হয়েছে",
    statusUpdateFailed: "স্ট্যাটাস পরিবর্তন করতে সমস্যা হয়েছে",
    pageTitle: "ক্লাস ও পরীক্ষার রুটিন",
    pageSubtitle: "সাপ্তাহিক ক্লাস রুটিন ও পরীক্ষার সময়সূচি তৈরি করুন",
    classRoutine: "ক্লাস রুটিন",
    examRoutine: "পরীক্ষার রুটিন",
    createRoutine: "রুটিন তৈরি করুন",
    classOverviewTitle: "কোন {{class}}ের রুটিন তৈরি হয়েছে",
    examOverviewTitle: "কোন {{class}}ের পরীক্ষার রুটিন তৈরি হয়েছে",
    noActiveClass: "কোনো সক্রিয় {{class}} পাওয়া যায়নি",
    hasRoutine: (n: string) => `রুটিন আছে (${n})`,
    noActiveExam: "কোনো সক্রিয় পরীক্ষা পাওয়া যায়নি",
    classEntryTitle: "ক্লাস রুটিন এন্ট্রি",
    examEntryTitle: "পরীক্ষার রুটিন এন্ট্রি",
    division: "{{division}}",
    selectDivision: "{{division}} নির্বাচন করুন",
    class: "{{class}}",
    selectClass: "{{class}} নির্বাচন করুন",
    exam: "পরীক্ষা",
    selectExam: "পরীক্ষা নির্বাচন করুন",
    selectClassFirst: "প্রথমে {{class}} নির্বাচন করুন",
    newClassRoutine: "নতুন ক্লাস রুটিন যোগ করুন",
    day: "বার",
    subject: "{{subject}}",
    selectSubject: "{{subject}} নির্বাচন করুন",
    noSubjects: "{{subject}} সেট করা নেই",
    teacherOptional: "{{teacher}} (ঐচ্ছিক)",
    selectTeacher: "{{teacher}} নির্বাচন করুন",
    startTime: "শুরুর সময়",
    endTime: "শেষের সময়",
    pickDivisionClassToView: "রুটিন দেখতে প্রথমে {{division}} ও {{class}} নির্বাচন করুন",
    noClassRoutine: "এই {{class}}ে এখনো কোনো রুটিন যোগ করা হয়নি",
    preview: "প্রিভিউ",
    newExamRoutine: "নতুন পরীক্ষার রুটিন যোগ করুন",
    date: "তারিখ",
    roomNoFree: "রুম নং (ফ্রি-টেক্সট, ঐচ্ছিক)",
    roomNoPlaceholder: "যেমনঃ ২০৩",
    roomFromList: "রুম (তালিকা থেকে, ঐচ্ছিক)",
    selectRoom: "রুম নির্বাচন করুন",
    maxCapacity: "সর্বোচ্চ ধারণক্ষমতা (ঐচ্ছিক)",
    maxCapacityPlaceholder: "যেমনঃ ৪০",
    status: "স্ট্যাটাস",
    instructions: "নির্দেশনা (ঐচ্ছিক)",
    instructionsPlaceholder: "যেমনঃ ক্যালকুলেটর সাথে আনা যাবে না",
    pickExamHint: "এবার উপরে থেকে একটি পরীক্ষা নির্বাচন করুন — তাহলে এই {{class}}ের রুটিন দেখা ও যোগ করা যাবে",
    noExamRoutine: "এই পরীক্ষা ও {{class}}ের জন্য এখনো কোনো রুটিন যোগ করা হয়নি",
    changeStatus: "রুটিনের স্ট্যাটাস পরিবর্তন করুন",
    mixed: "বিভিন্ন",
    scrollHint: "⟷ টেবিলটি পাশে স্ক্রল করে বাকি কলাম দেখুন",
    dateTime: "তারিখ ও সময়",
    roomCapacity: "রুম / ধারণক্ষমতা",
    actions: "কার্যক্রম",
    invigilator: "পরিদর্শক",
    classPreviewTitle: "ক্লাস রুটিন প্রিভিউ",
    examPreviewTitle: "পরীক্ষার রুটিন প্রিভিউ",
    // print
    weeklyClassRoutine: "সাপ্তাহিক ক্লাস রুটিন",
    divisionLabel: "{{division}}:",
    classLabel: "{{class}}:",
    start: "শুরু",
    end: "শেষ",
    teacher: "{{teacher}}",
    room: "রুম",
    printAction: "প্রিন্ট করুন",
  },
  en: {
    days: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
    statusDraft: "Draft",
    statusPublished: "Published",
    statusCancelled: "Cancelled",
    statusNone: "No routine",
    statusMixed: "Partial",
    noDivisionAssigned: "No {{division}} assigned",
    pickDivisionClassFirst: "Select a {{division}} and {{class}} first",
    classFieldsRequired: "Enter the {{subject}}, start and end time",
    timeOrderError: (start, end) =>
      `The start time (${start}) is equal to or after the end time (${end}). Noon = 12:00, midnight = 00:00 — please check AM/PM.`,
    routineAdded: "Routine added",
    routineAddFailed: "Could not add routine",
    routineDeleted: "Routine deleted",
    deleteFailed: "Could not delete",
    pickExamClassFirst: "Select an exam and {{class}} first",
    examFieldsRequired: "Enter the {{subject}}, date, start and end time",
    examRoutineAdded: "Exam routine added",
    statusUpdated: "Status updated",
    statusUpdateFailed: "Could not change status",
    pageTitle: "Class & Exam Routine",
    pageSubtitle: "Create the weekly class routine and exam schedule",
    classRoutine: "Class Routine",
    examRoutine: "Exam Routine",
    createRoutine: "Create routine",
    classOverviewTitle: "Which {{class}}es have a routine",
    examOverviewTitle: "Which {{class}}es have an exam routine",
    noActiveClass: "No active {{class}} found",
    hasRoutine: (n) => `Has routine (${n})`,
    noActiveExam: "No active exam found",
    classEntryTitle: "Class Routine Entry",
    examEntryTitle: "Exam Routine Entry",
    division: "{{division}}",
    selectDivision: "Select {{division}}",
    class: "{{class}}",
    selectClass: "Select {{class}}",
    exam: "Exam",
    selectExam: "Select exam",
    selectClassFirst: "Select a {{class}} first",
    newClassRoutine: "Add new class routine",
    day: "Day",
    subject: "{{subject}}",
    selectSubject: "Select {{subject}}",
    noSubjects: "No {{subject}}s set",
    teacherOptional: "{{teacher}} (optional)",
    selectTeacher: "Select {{teacher}}",
    startTime: "Start time",
    endTime: "End time",
    pickDivisionClassToView: "Select a {{division}} and {{class}} to view the routine",
    noClassRoutine: "No routine added for this {{class}} yet",
    preview: "Preview",
    newExamRoutine: "Add new exam routine",
    date: "Date",
    roomNoFree: "Room no. (free text, optional)",
    roomNoPlaceholder: "e.g. 203",
    roomFromList: "Room (from list, optional)",
    selectRoom: "Select room",
    maxCapacity: "Max capacity (optional)",
    maxCapacityPlaceholder: "e.g. 40",
    status: "Status",
    instructions: "Instructions (optional)",
    instructionsPlaceholder: "e.g. Calculators are not allowed",
    pickExamHint: "Now select an exam above — then this {{class}}'s routine can be viewed and added",
    noExamRoutine: "No routine added for this exam and {{class}} yet",
    changeStatus: "Change routine status",
    mixed: "Mixed",
    scrollHint: "⟷ Scroll the table sideways to see the remaining columns",
    dateTime: "Date & Time",
    roomCapacity: "Room / Capacity",
    actions: "Actions",
    invigilator: "Invigilators",
    classPreviewTitle: "Class Routine Preview",
    examPreviewTitle: "Exam Routine Preview",
    weeklyClassRoutine: "Weekly Class Routine",
    divisionLabel: "{{division}}:",
    classLabel: "{{class}}:",
    start: "Start",
    end: "End",
    teacher: "{{teacher}}",
    room: "Room",
    printAction: "Print",
  },
  ar: {
    days: ["الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس", "الجمعة", "السبت"],
    statusDraft: "مسودة",
    statusPublished: "منشور",
    statusCancelled: "ملغى",
    statusNone: "لا يوجد جدول",
    statusMixed: "جزئي",
    noDivisionAssigned: "لم تُحدَّد {{division}}",
    pickDivisionClassFirst: "اختر {{division}} و{{class}} أولًا",
    classFieldsRequired: "أدخل {{subject}} ووقت البدء والانتهاء",
    timeOrderError: (start, end) =>
      `وقت البدء (${start}) يساوي وقت الانتهاء (${end}) أو يليه. الظهر = 12:00، ومنتصف الليل = 00:00 — تحقق من صباحًا/مساءً.`,
    routineAdded: "تمت إضافة الجدول",
    routineAddFailed: "تعذّرت إضافة الجدول",
    routineDeleted: "تم حذف الجدول",
    deleteFailed: "تعذّر الحذف",
    pickExamClassFirst: "اختر الامتحان و{{class}} أولًا",
    examFieldsRequired: "أدخل {{subject}} والتاريخ ووقت البدء والانتهاء",
    examRoutineAdded: "تمت إضافة جدول الامتحان",
    statusUpdated: "تم تحديث الحالة",
    statusUpdateFailed: "تعذّر تغيير الحالة",
    pageTitle: "جدول الحصص والامتحانات",
    pageSubtitle: "أنشئ جدول الحصص الأسبوعي ومواعيد الامتحانات",
    classRoutine: "جدول الحصص",
    examRoutine: "جدول الامتحانات",
    createRoutine: "إنشاء جدول",
    classOverviewTitle: "الصفوف التي أُنشئ جدولها",
    examOverviewTitle: "الصفوف التي أُنشئ جدول امتحانها",
    noActiveClass: "لا يوجد صف نشط",
    hasRoutine: (n) => `يوجد جدول (${n})`,
    noActiveExam: "لا يوجد امتحان نشط",
    classEntryTitle: "إدخال جدول الحصص",
    examEntryTitle: "إدخال جدول الامتحان",
    division: "{{division}}",
    selectDivision: "اختر {{division}}",
    class: "{{class}}",
    selectClass: "اختر {{class}}",
    exam: "الامتحان",
    selectExam: "اختر الامتحان",
    selectClassFirst: "اختر {{class}} أولًا",
    newClassRoutine: "إضافة حصة جديدة",
    day: "اليوم",
    subject: "{{subject}}",
    selectSubject: "اختر {{subject}}",
    noSubjects: "لم يُحدَّد {{subject}}",
    teacherOptional: "{{teacher}} (اختياري)",
    selectTeacher: "اختر {{teacher}}",
    startTime: "وقت البدء",
    endTime: "وقت الانتهاء",
    pickDivisionClassToView: "اختر {{division}} و{{class}} لعرض الجدول",
    noClassRoutine: "لم يُضف أي جدول لهذا الصف بعد",
    preview: "معاينة",
    newExamRoutine: "إضافة موعد امتحان جديد",
    date: "التاريخ",
    roomNoFree: "رقم القاعة (نص حر، اختياري)",
    roomNoPlaceholder: "مثل 203",
    roomFromList: "القاعة (من القائمة، اختياري)",
    selectRoom: "اختر القاعة",
    maxCapacity: "السعة القصوى (اختياري)",
    maxCapacityPlaceholder: "مثل 40",
    status: "الحالة",
    instructions: "التعليمات (اختياري)",
    instructionsPlaceholder: "مثل: لا يُسمح بإحضار الآلة الحاسبة",
    pickExamHint: "اختر الآن امتحانًا من الأعلى — ليمكن عرض جدول هذا الصف وإضافته",
    noExamRoutine: "لم يُضف أي جدول لهذا الامتحان والصف بعد",
    changeStatus: "تغيير حالة الجدول",
    mixed: "متنوع",
    scrollHint: "⟷ مرّر الجدول أفقيًا لرؤية بقية الأعمدة",
    dateTime: "التاريخ والوقت",
    roomCapacity: "القاعة / السعة",
    actions: "الإجراءات",
    invigilator: "المراقبون",
    classPreviewTitle: "معاينة جدول الحصص",
    examPreviewTitle: "معاينة جدول الامتحان",
    weeklyClassRoutine: "جدول الحصص الأسبوعي",
    divisionLabel: "{{division}}:",
    classLabel: "{{class}}:",
    start: "البدء",
    end: "الانتهاء",
    teacher: "{{teacher}}",
    room: "القاعة",
    printAction: "طباعة",
  },
});
