import { defineText } from "@madrasha/shared-ui/src/i18n";

/** Topbar, plan badge, profile menu, lock screen, 404/unauthorized pages. */
export const shellText = defineText({
  bn: {
    expired: "মেয়াদ শেষ",
    endsToday: "আজই শেষ",
    daysLeft: (n: string) => `${n} দিন বাকি`,
    suspended: "স্থগিত",
    noSubscription: "সাবস্ক্রিপশন নেই",
    planTitle: (name: string) => `প্ল্যান: ${name}`,
    planStatus: "প্ল্যান স্ট্যাটাস",
    profileMenu: "প্রোফাইল মেনু",
    profile: "প্রোফাইল",
    openMenu: "মেনু খুলুন",
    lockScreen: "স্ক্রিন লক করুন",
    wrongPassword: "পাসওয়ার্ড সঠিক নয়।",
    screenLocked: "স্ক্রিন লক করা আছে",
    enterPasswordToContinue: "চালিয়ে যেতে পাসওয়ার্ড দিন",
    enterPasswordToContinueNamed: (name: string) => `${name}, চালিয়ে যেতে পাসওয়ার্ড দিন`,
    enterPassword: "পাসওয়ার্ড দিন",
    showPassword: "পাসওয়ার্ড দেখান",
    hidePassword: "পাসওয়ার্ড লুকান",
    unlock: "আনলক করুন",
    pageNotFound: "পেজ পাওয়া যায়নি",
    pageNotFoundBody: "আপনি যে পেজটি খুঁজছেন সেটি নেই অথবা URL ভুল।",
    backToDashboard: "ড্যাশবোর্ডে ফিরে যান",
    accessRestricted: "প্রবেশ সীমিত",
    accessRestrictedBody: "এই মডিউল ব্যবহারের অনুমতি আপনার অ্যাকাউন্টে নেই।",
  },
  en: {
    expired: "Expired",
    endsToday: "Ends today",
    daysLeft: (n) => `${n} days left`,
    suspended: "Suspended",
    noSubscription: "No subscription",
    planTitle: (name) => `Plan: ${name}`,
    planStatus: "Plan status",
    profileMenu: "Profile menu",
    profile: "Profile",
    openMenu: "Open menu",
    lockScreen: "Lock screen",
    wrongPassword: "Incorrect password.",
    screenLocked: "Screen is locked",
    enterPasswordToContinue: "Enter your password to continue",
    enterPasswordToContinueNamed: (name) => `${name}, enter your password to continue`,
    enterPassword: "Enter password",
    showPassword: "Show password",
    hidePassword: "Hide password",
    unlock: "Unlock",
    pageNotFound: "Page not found",
    pageNotFoundBody: "The page you are looking for does not exist or the URL is wrong.",
    backToDashboard: "Back to dashboard",
    accessRestricted: "Access restricted",
    accessRestrictedBody: "Your account does not have permission to use this module.",
  },
  ar: {
    expired: "انتهت الصلاحية",
    endsToday: "تنتهي اليوم",
    daysLeft: (n) => `متبقٍ ${n} يوم`,
    suspended: "موقوف",
    noSubscription: "لا يوجد اشتراك",
    planTitle: (name) => `الباقة: ${name}`,
    planStatus: "حالة الباقة",
    profileMenu: "قائمة الملف الشخصي",
    profile: "الملف الشخصي",
    openMenu: "فتح القائمة",
    lockScreen: "قفل الشاشة",
    wrongPassword: "كلمة المرور غير صحيحة.",
    screenLocked: "الشاشة مقفلة",
    enterPasswordToContinue: "أدخل كلمة المرور للمتابعة",
    enterPasswordToContinueNamed: (name) => `${name}، أدخل كلمة المرور للمتابعة`,
    enterPassword: "أدخل كلمة المرور",
    showPassword: "إظهار كلمة المرور",
    hidePassword: "إخفاء كلمة المرور",
    unlock: "فتح القفل",
    pageNotFound: "الصفحة غير موجودة",
    pageNotFoundBody: "الصفحة التي تبحث عنها غير موجودة أو أن الرابط غير صحيح.",
    backToDashboard: "العودة إلى لوحة التحكم",
    accessRestricted: "الوصول مقيد",
    accessRestrictedBody: "ليس لدى حسابك صلاحية استخدام هذه الوحدة.",
  },
});
