import { defineText } from "@madrasha/shared-ui/src/i18n";

/** Shared by the admission form sections (components/admission/*). */
export const admissionText = defineText({
  bn: {
    // section headings
    studentInfo: "{{student}}র তথ্য",
    parentInfo: "অভিভাবকের তথ্য",
    altGuardianInfo: "বিকল্প অভিভাবক (পিতা-মাতা ছাড়া)",
    addressInfo: "ঠিকানার তথ্য",
    otherInfo: "অন্যান্য তথ্য",
    noParents: "পিতা-মাতা নেই (বিকল্প অভিভাবক প্রযোজ্য)",

    // student
    studentNameBn: "{{student}}র নাম (বাংলা)",
    studentNameAr: "{{student}}র নাম (আরবি)",
    studentNameEn: "{{student}}র নাম (ইংরেজি)",
    nidOrBirthReg: "NID/জন্ম নিবন্ধন নম্বর",
    division: "{{division}}",
    currentClass: "বর্তমান {{class}}",
    previousClass: "পূর্বের {{class}}",
    previousInstitution: "পূর্ববর্তী প্রতিষ্ঠান",
    previousInstitutionPlaceholder: "পূর্ববর্তী প্রতিষ্ঠানের নাম",
    previousResult: "পূর্বের ফলাফল",
    previousResultPlaceholder: "যেমন: মুমতায/জায়্যিদ জিদ্দান",
    previousResultPlaceholderGeneric: "যেমন: GPA 5.00",
    gender: "লিঙ্গ",
    male: "ছেলে",
    female: "মেয়ে",
    dob: "জন্ম তারিখ",
    session: "{{session}}",
    auto: "স্বয়ংক্রিয়",
    noActiveSession: "কোনো সক্রিয় সেশন পাওয়া যায়নি",
    selectDivisionFirst: "প্রথমে {{division}} নির্বাচন করুন",
    rollNo: "রোল নম্বর",
    rollPlaceholder: "{{class}} নির্বাচন করলে সম্ভাব্য রোল দেখা যাবে",
    admissionType: "ভর্তির ধরন",
    readmission: "পুনঃভর্তি (পুরাতন)",
    newAdmission: "নতুন",
    admissionDate: "ভর্তির তারিখ",
    age: "বয়স",

    // parents
    fatherNameBn: "পিতার নাম (বাংলা)",
    fatherNameAr: "পিতার নাম (আরবি)",
    fatherNameEn: "পিতার নাম (ইংরেজি)",
    fatherNamePlaceholder: "পিতার নাম লিখুন",
    fatherNid: "পিতার NID",
    fatherNidPlaceholder: "পিতার NID নম্বর",
    fatherOccupation: "পিতার পেশা",
    motherNameBn: "মাতার নাম (বাংলা)",
    motherNameAr: "মাতার নাম (আরবি)",
    motherNameEn: "মাতার নাম (ইংরেজি)",
    motherNamePlaceholder: "মাতার নাম লিখুন",
    motherNid: "মাতার NID",
    motherNidPlaceholder: "মাতার NID নম্বর",
    motherOccupation: "মাতার পেশা",
    guardianMobile: "অভিভাবকের মোবাইল নম্বর",
    guardianAltMobile: "অভিভাবকের বিকল্প মোবাইল নম্বর",
    mobileNo: "মোবাইল নম্বর",
    altMobileNo: "বিকল্প মোবাইল নম্বর",

    // alternate guardian
    guardianNameBn: "অভিভাবকের নাম (বাংলা)",
    guardianNameAr: "অভিভাবকের নাম (আরবি)",
    guardianNameEn: "অভিভাবকের নাম (ইংরেজি)",
    enterName: "নাম লিখুন",
    relation: "{{student}}র সাথে সম্পর্ক",
    relationPlaceholder: "যেমন: চাচা, দাদা",

    // address / other
    village: "গ্রাম",
    bloodGroup: "রক্তের গ্রুপ",
    residency: "আবাসিক/অনাবাসিক",
    residential: "আবাসিক",
    nonResidential: "অনাবাসিক",
    orphan: "এতিম {{student}}",
    studentPhoto: "{{student}}র ছবি",

    // buttons / banners
    printAdmissionForm: "প্রিন্ট ভর্তি ফরম",
    submitting: "জমা হচ্ছে...",
    submitAdmission: "ভর্তি সম্পন্ন করুন",
    submitReadmission: "সেশন আপডেট করুন (পুনঃভর্তি)",
    lookingUpNid: "NID দিয়ে পূর্বের তথ্য খোঁজা হচ্ছে...",
    previousFound: "এই NID দিয়ে পূর্বে ভর্তিকৃত একজন {{student}} পাওয়া গেছে",
    previousSession: "পূর্বের সেশন:",
    previousClassLabel: "পূর্বের {{class}}:",
    autoFilledNote:
      "ফর্মটি স্বয়ংক্রিয়ভাবে পূরণ করা হয়েছে। জমা দিলে নতুন {{student}} তৈরি হবে না - শুধু এই {{student}}র সেশন/{{class}} আপডেট হয়ে পুনঃভর্তি সম্পন্ন হবে।",
    admitAsNew: "নতুন হিসেবে ভর্তি করুন",

    // bulk admission modal
    bulkTitle: "একসাথে ভর্তি (Excel)",
    bulkSubtitle: "Excel ফাইল আপলোড করে একসাথে {{student}} ভর্তি করুন",
    bulkDone: "একসাথে ভর্তি সম্পন্ন হয়েছে",
    newAdmissions: "নতুন ভর্তি:",
    sessionUpdates: "সেশন আপডেট (পুনঃভর্তি):",
    uploadAnother: "আরেকটি Excel আপলোড করুন",
    registration: "রেজিস্ট্রেশন",
    state: "অবস্থা",
    sessionUpdateBadge: "সেশন আপডেট (পুনঃভর্তি)",
    newAdmissionBadge: "নতুন ভর্তি",
    uploadExcelSheet: "Excel শিট আপলোড করুন",
    requiredFieldsHint: "আবশ্যক কলামগুলো টেমপ্লেটে লাল রঙে ও * চিহ্নসহ থাকবে",
    genderHint: "Gender: 1 = ছেলে, 2 = মেয়ে",
    idHint: "academic_division/current_class/previous_class এ ID দিতে হবে, প্রিভিউতে নাম দেখা যাবে",
    downloadTemplate: "টেমপ্লেট ডাউনলোড",
    uploadAdmissionExcel: "ভর্তির Excel আপলোড করুন",
    previewStudents: "{{student}} প্রিভিউ",
    studentsFound: (n: string) => `মোট ${n} জন {{student}} পাওয়া গেছে`,
    clearUploaded: "আপলোড করা ডেটা মুছুন",
    submitAll: "সকল {{student}} জমা দিন",
    uploaded: "আপলোড হয়েছে",
    colNameBn: "নাম (বাংলা)",
    colArabicName: "আরবি নাম",
    colNid: "NID",
    colDob: "জন্ম তারিখ",
    colAcademicDivision: "{{division}}",
    colGuardianPhone: "অভিভাবকের মোবাইল",
    colFatherArabicName: "পিতার আরবি নাম",
    colDivision: "বিভাগ (ঠিকানা)",
    colDistrict: "জেলা",
    colThana: "থানা",
  },
  en: {
    studentInfo: "{{student}} Information",
    parentInfo: "Guardian Information",
    altGuardianInfo: "Alternate Guardian (other than parents)",
    addressInfo: "Address",
    otherInfo: "Other Information",
    noParents: "No parents (alternate guardian applies)",

    studentNameBn: "{{student}} Name (Bangla)",
    studentNameAr: "{{student}} Name (Arabic)",
    studentNameEn: "{{student}} Name (English)",
    nidOrBirthReg: "NID / Birth Registration No.",
    division: "{{division}}",
    currentClass: "Current {{class}}",
    previousClass: "Previous {{class}}",
    previousInstitution: "Previous Institution",
    previousInstitutionPlaceholder: "Name of previous institution",
    previousResult: "Previous Result",
    previousResultPlaceholder: "e.g. Mumtaz / Jayyid Jiddan",
    previousResultPlaceholderGeneric: "e.g. GPA 5.00",
    gender: "Gender",
    male: "Male",
    female: "Female",
    dob: "Date of Birth",
    session: "{{session}}",
    auto: "Auto",
    noActiveSession: "No active session found",
    selectDivisionFirst: "Select a {{division}} first",
    rollNo: "Roll No.",
    rollPlaceholder: "Select a {{class}} to see the expected roll",
    admissionType: "Admission Type",
    readmission: "Re-admission (existing)",
    newAdmission: "New",
    admissionDate: "Admission Date",
    age: "Age",

    fatherNameBn: "Father's Name (Bangla)",
    fatherNameAr: "Father's Name (Arabic)",
    fatherNameEn: "Father's Name (English)",
    fatherNamePlaceholder: "Enter father's name",
    fatherNid: "Father's NID",
    fatherNidPlaceholder: "Father's NID number",
    fatherOccupation: "Father's Occupation",
    motherNameBn: "Mother's Name (Bangla)",
    motherNameAr: "Mother's Name (Arabic)",
    motherNameEn: "Mother's Name (English)",
    motherNamePlaceholder: "Enter mother's name",
    motherNid: "Mother's NID",
    motherNidPlaceholder: "Mother's NID number",
    motherOccupation: "Mother's Occupation",
    guardianMobile: "Guardian's Mobile No.",
    guardianAltMobile: "Guardian's Alternate Mobile No.",
    mobileNo: "Mobile number",
    altMobileNo: "Alternate mobile number",

    guardianNameBn: "Guardian's Name (Bangla)",
    guardianNameAr: "Guardian's Name (Arabic)",
    guardianNameEn: "Guardian's Name (English)",
    enterName: "Enter name",
    relation: "Relation to {{student}}",
    relationPlaceholder: "e.g. Uncle, Grandfather",

    village: "Village",
    bloodGroup: "Blood Group",
    residency: "Residential / Non-residential",
    residential: "Residential",
    nonResidential: "Non-residential",
    orphan: "Orphan {{student}}",
    studentPhoto: "{{student}} Photo",

    printAdmissionForm: "Print Admission Form",
    submitting: "Submitting...",
    submitAdmission: "Submit Admission",
    submitReadmission: "Update Session (Re-admission)",
    lookingUpNid: "Looking up previous records by NID...",
    previousFound: "A previously admitted {{student}} was found with this NID",
    previousSession: "Previous session:",
    previousClassLabel: "Previous {{class}}:",
    autoFilledNote:
      "The form has been filled automatically. Submitting will not create a new {{student}} - it will only update this {{student}}'s session/{{class}} and complete the re-admission.",
    admitAsNew: "Admit as new",

    bulkTitle: "Bulk Admission Upload",
    bulkSubtitle: "Admit {{student}}s in bulk by uploading an Excel file",
    bulkDone: "Bulk admission completed",
    newAdmissions: "New admissions:",
    sessionUpdates: "Session updates (re-admission):",
    uploadAnother: "Upload another Excel",
    registration: "Registration",
    state: "Status",
    sessionUpdateBadge: "Session update (re-admission)",
    newAdmissionBadge: "New admission",
    uploadExcelSheet: "Upload Excel Sheet",
    requiredFieldsHint: "Required columns are marked in red with * in the template",
    genderHint: "Gender: 1 = Male, 2 = Female",
    idHint: "Enter IDs in academic_division/current_class/previous_class; names appear in the preview",
    downloadTemplate: "Download Template",
    uploadAdmissionExcel: "Upload Admission Excel",
    previewStudents: "Preview {{student}}s",
    studentsFound: (n) => `Total ${n} {{student}}(s) found`,
    clearUploaded: "Clear Uploaded Data",
    submitAll: "Submit All {{student}}s",
    uploaded: "Uploaded",
    colNameBn: "Name (Bangla)",
    colArabicName: "Arabic Name",
    colNid: "NID",
    colDob: "DOB",
    colAcademicDivision: "{{division}}",
    colGuardianPhone: "Guardian Phone",
    colFatherArabicName: "Father's Arabic Name",
    colDivision: "Division (Address)",
    colDistrict: "District",
    colThana: "Thana",
  },
});
