import { defineText } from "@madrasha/shared-ui/src/i18n";

const fieldsBn = {
  name_bn: "নাম",
  arabic_name: "আরবি নাম",
  nid: "এনআইডি",
  gender: "লিঙ্গ",
  dob: "জন্ম তারিখ",
  age: "বয়স",
  blood_group: "রক্তের গ্রুপ",
  residency_type: "আবাসনের ধরন",
  is_orphan: "এতিম কিনা",
  previous_class_id: "পূর্ববর্তী {{class}} আইডি",
  previous_institution: "পূর্ববর্তী প্রতিষ্ঠান",
  previous_result: "পূর্ববর্তী ফলাফল",
  admission_date: "ভর্তির তারিখ",
  father_name: "বাবার নাম",
  father_arabic_name: "বাবার আরবি নাম",
  father_nid: "বাবার এনআইডি",
  father_occupation: "বাবার পেশা",
  mother_name: "মায়ের নাম",
  mother_nid: "মায়ের এনআইডি",
  mother_occupation: "মায়ের পেশা",
  guardian_phone: "অভিভাবকের ফোন",
  guardian_phone_2: "অভিভাবকের ফোন ২",
  alt_guardian_name: "বিকল্প অভিভাবকের নাম",
  alt_guardian_relation: "সম্পর্ক",
  alt_guardian_address: "বিকল্প অভিভাবকের ঠিকানা",
  alt_guardian_phone: "বিকল্প অভিভাবকের ফোন",
  division: "বিভাগ (ঠিকানা)",
  district: "জেলা",
  thana: "থানা",
  village: "গ্রাম",
};

export type BulkUpdateFieldKey = keyof typeof fieldsBn;

export const bulkUpdateText = defineText({
  bn: {
    fields: fieldsBn as Record<BulkUpdateFieldKey, string>,
    noStudentsToExport: "এক্সপোর্ট করার জন্য কোনো {{student}} পাওয়া যায়নি",
    sheetInstruction:
      "ধূসর রঙের কলামগুলো (registration_no, roll, current_class, division_name, academic_year) লক করা - এগুলোতে লেখা যাবে না। {{class}}/{{division}}/সেশন পরিবর্তনের জন্য 'প্রমোশন' ফিচার ব্যবহার করুন। শুধু name_bn আবশ্যক (*), বাকি ঘর খালি রাখলে সেই তথ্য মুছে যাবে।",
    guideLockedColumns: "লক করা কলাম (এগুলোতে লেখা যাবে না)",
    guideGender: "Gender Guide",
    guideName: "Name",
    male: "ছেলে",
    female: "মেয়ে",
    guideClass: "Class Guide (previous_class_id এর জন্য)",
    guideClassName: "Class Name",
    guideDivision: "{{division}}",
    noChangesToSend: "পাঠানোর মতো কোনো পরিবর্তন পাওয়া যায়নি",
    submitFailed: "বাল্ক আপডেট ব্যর্থ হয়েছে",
    title: "বাল্ক আপডেট (Excel)",
    subtitle:
      "বিদ্যমান {{student}}দের তথ্য একসাথে এক্সেল দিয়ে আপডেট করুন। {{class}}/{{division}}/সেশন/রোল এখানে পরিবর্তনযোগ্য নয়।",
    done: "বাল্ক আপডেট সম্পন্ন হয়েছে",
    updatedLabel: "আপডেট:",
    unchangedLabel: "অপরিবর্তিত:",
    skippedLabel: "বাদ পড়েছে:",
    uploadAnother: "আরেকটি Excel আপলোড করুন",
    regRoll: "রেজি. / রোল",
    state: "অবস্থা",
    changesNotes: "পরিবর্তন / নোট",
    statusUpdated: "আপডেট হয়েছে",
    statusUnchanged: "পরিবর্তন নেই",
    statusSkipped: "বাদ পড়েছে",
    exportUpload: "এক্সেল এক্সপোর্ট / আপলোড",
    exportHint: (n: string) => `বর্তমান ফিল্টার অনুযায়ী তালিকাভুক্ত ${n} জন {{student}}র তথ্য এক্সপোর্ট হবে।`,
    lockedHint: "ধূসর কলাম (id, class_id, roll ইত্যাদি) লক করা - সম্পাদনা করা যাবে না।",
    exportExcel: "এক্সেল এক্সপোর্ট করুন",
    uploadUpdated: "আপডেট করা Excel আপলোড করুন",
    preview: "প্রিভিউ",
    previewSummary: (total: string, changed: string) =>
      `মোট ${total} সারি — এর মধ্যে ${changed} সারিতে পরিবর্তন পাওয়া গেছে`,
    clearUploaded: "আপলোড করা ডেটা মুছুন",
    changedFields: "পরিবর্তিত ফিল্ড",
    regNotMatched: "রেজি. নং মেলেনি (বাদ যাবে)",
    willChange: "পরিবর্তন হবে",
    noChange: "কোনো পরিবর্তন নেই",
    willBeIgnored: "🔒 উপেক্ষা হবে",
    sending: "পাঠানো হচ্ছে...",
    updateN: (n: string) => `${n} জন আপডেট করুন`,
  },
  en: {
    fields: {
      name_bn: "Name",
      arabic_name: "Arabic Name",
      nid: "NID",
      gender: "Gender",
      dob: "Date of Birth",
      age: "Age",
      blood_group: "Blood Group",
      residency_type: "Residency Type",
      is_orphan: "Orphan",
      previous_class_id: "Previous {{class}} ID",
      previous_institution: "Previous Institution",
      previous_result: "Previous Result",
      admission_date: "Admission Date",
      father_name: "Father's Name",
      father_arabic_name: "Father's Arabic Name",
      father_nid: "Father's NID",
      father_occupation: "Father's Occupation",
      mother_name: "Mother's Name",
      mother_nid: "Mother's NID",
      mother_occupation: "Mother's Occupation",
      guardian_phone: "Guardian Phone",
      guardian_phone_2: "Guardian Phone 2",
      alt_guardian_name: "Alternate Guardian Name",
      alt_guardian_relation: "Relation",
      alt_guardian_address: "Alternate Guardian Address",
      alt_guardian_phone: "Alternate Guardian Phone",
      division: "Division (Address)",
      district: "District",
      thana: "Thana",
      village: "Village",
    },
    noStudentsToExport: "No {{student}}s found to export",
    sheetInstruction:
      "Grey columns (registration_no, roll, current_class, division_name, academic_year) are locked and cannot be edited. Use the 'Promotion' feature to change {{class}}/{{division}}/session. Only name_bn is required (*); leaving any other cell blank will clear that information.",
    guideLockedColumns: "Locked columns (cannot be edited)",
    guideGender: "Gender Guide",
    guideName: "Name",
    male: "Male",
    female: "Female",
    guideClass: "Class Guide (for previous_class_id)",
    guideClassName: "Class Name",
    guideDivision: "{{division}}",
    noChangesToSend: "No changes found to submit",
    submitFailed: "Bulk update failed",
    title: "Bulk Update (Excel)",
    subtitle:
      "Update existing {{student}}s' information in bulk via Excel. {{class}}/{{division}}/session/roll cannot be changed here.",
    done: "Bulk update completed",
    updatedLabel: "Updated:",
    unchangedLabel: "Unchanged:",
    skippedLabel: "Skipped:",
    uploadAnother: "Upload another Excel",
    regRoll: "Reg. / Roll",
    state: "Status",
    changesNotes: "Changes / Notes",
    statusUpdated: "Updated",
    statusUnchanged: "No change",
    statusSkipped: "Skipped",
    exportUpload: "Excel Export / Upload",
    exportHint: (n) => `${n} {{student}}(s) listed under the current filter will be exported.`,
    lockedHint: "Grey columns (id, class_id, roll, etc.) are locked and cannot be edited.",
    exportExcel: "Export Excel",
    uploadUpdated: "Upload Updated Excel",
    preview: "Preview",
    previewSummary: (total, changed) => `${total} rows in total — changes found in ${changed}`,
    clearUploaded: "Clear Uploaded Data",
    changedFields: "Changed Fields",
    regNotMatched: "Reg. no. not matched (will be skipped)",
    willChange: "Will change",
    noChange: "No change",
    willBeIgnored: "🔒 Will be ignored",
    sending: "Submitting...",
    updateN: (n) => `Update ${n}`,
  },
});
