import { defineText, getText } from "@madrasha/shared-ui/src/i18n";

/**
 * Text for the teacher & staff module (lists, admission forms, profiles,
 * bulk upload/update, dashboard). Shared by features/teachers, features/staff
 * and the components/teachers*, staff*, teacherProfile, staffProfile and
 * ExperiencePicker folders.
 */
export const teacherStaffText = defineText({
  bn: {
    /** Field labels keyed by the backend/Excel data key. */
    fields: {
      registration_no: "রেজিস্ট্রেশন নং",
      division_id: "একাডেমিক {{division}} আইডি",
      academic_division: "একাডেমিক {{division}}",
      name: "নাম",
      name_bn: "নাম",
      name_ar: "আরবি নাম",
      nid: "এনআইডি",
      gender: "লিঙ্গ",
      dob: "জন্ম তারিখ",
      age: "বয়স",
      phone: "ফোন",
      mobile: "মোবাইল",
      email: "ইমেইল",
      designation: "পদবি",
      department: "বিভাগ (পদ)",
      qualification: "যোগ্যতা",
      experience_year: "অভিজ্ঞতা (বছর)",
      experience_month: "অভিজ্ঞতা (মাস)",
      joining_date: "যোগদানের তারিখ",
      salary: "বেতন",
      father_name: "বাবার নাম",
      father_name_ar: "বাবার আরবি নাম",
      father_nid: "বাবার এনআইডি",
      father_occupation: "বাবার পেশা",
      mother_name: "মায়ের নাম",
      mother_nid: "মায়ের এনআইডি",
      mother_occupation: "মায়ের পেশা",
      parent_phone: "অভিভাবকের ফোন",
      division: "বিভাগ (ঠিকানা)",
      district: "জেলা",
      thana: "থানা",
      village: "গ্রাম",
      image: "ছবি",
    } as Record<string, string>,

    // Gender
    male: "পুরুষ",
    female: "মহিলা",
    allGenders: "সব লিঙ্গ",
    none: "নেই",

    // Lists
    teacherList: "{{teacher}} তালিকা",
    staffList: "স্টাফ তালিকা",
    totalTeachers: (n: string) => `মোট {{teacher}}: ${n} জন`,
    totalStaff: (n: string) => `মোট স্টাফ: ${n} জন`,
    addTeacher: "+ নতুন {{teacher}} যোগ করুন",
    addStaff: "+ নতুন স্টাফ যোগ করুন",
    listSearchPlaceholder: "ID, নাম, ফোন বা পদবি দিয়ে সার্চ করুন",
    allAcademicDivisions: "সব একাডেমিক {{division}}",
    bulkUpdate: "বাল্ক আপডেট",
    noTeacherFound: "কোন {{teacher}} পাওয়া যায়নি",
    noStaffFound: "কোন স্টাফ পাওয়া যায়নি",
    loadTeachersFailed: "{{teacher}} তালিকা লোড করতে সমস্যা হয়েছে",
    loadStaffFailed: "স্টাফ তালিকা লোড করতে সমস্যা হয়েছে",

    // Profile pages
    deleteTeacherTitle: "{{teacher}} মুছবেন?",
    deleteTeacherMessage: "এই {{teacher}}কে ট্র্যাশে সরাতে চান? পরে প্রয়োজনে ট্র্যাশ থেকে ফিরিয়ে আনা যাবে।",
    deleteStaffTitle: "স্টাফ মুছবেন?",
    deleteStaffMessage: "এই স্টাফকে ট্র্যাশে সরাতে চান? পরে প্রয়োজনে ট্র্যাশ থেকে ফিরিয়ে আনা যাবে।",
    moveToTrash: "ট্র্যাশে সরান",
    movedToTrash: "🗑️ ট্র্যাশে সরানো হয়েছে",
    deleteFailed: "❌ মুছে ফেলা যায়নি",
    regShort: (reg: string) => `রেজি. ${reg}`,
    searchOtherTeacher: "অন্য {{teacher}} খুঁজুন — নাম / রেজি. / পদবি",
    searchOtherTeacherAria: "অন্য {{teacher}} খুঁজুন",
    searchOtherStaff: "অন্য স্টাফ খুঁজুন — নাম / রেজি. / পদবি",
    searchOtherStaffAria: "অন্য স্টাফ খুঁজুন",

    // Admission forms
    teacherRegistration: "নতুন {{teacher}} নিবন্ধন",
    staffRegistration: "নতুন স্টাফ নিবন্ধন",
    saveTeacher: "{{teacher}} সংরক্ষণ করুন",
    saveStaff: "স্টাফ সংরক্ষণ করুন",
    bulkUpload: "বাল্ক আপলোড",
    enterTeacherName: "{{teacher}}ের নাম দিন",
    enterStaffName: "স্টাফের নাম দিন",
    selectAcademicDivision: "একাডেমিক {{division}} নির্বাচন করুন",
    teacherAdded: "{{teacher}} সফলভাবে যোগ করা হয়েছে ✅",
    teacherAddFailed: "{{teacher}} যোগ করতে ব্যর্থ ❌",
    staffAdded: "স্টাফ সফলভাবে যোগ করা হয়েছে ✅",
    staffAddFailed: "স্টাফ যোগ করতে ব্যর্থ ❌",
    teacherInfo: "{{teacher}}ের তথ্য",
    staffInfo: "স্টাফের তথ্য",
    familyInfo: "পারিবারিক তথ্য",
    addressInfo: "ঠিকানার তথ্য",
    teacherPhoto: "{{teacher}}ের ছবি",
    staffPhoto: "স্টাফের ছবি",
    nameBn: "নাম (বাংলা)",
    nameAr: "নাম (আরবি)",
    nameEn: "নাম (ইংরেজি)",
    educationalQualification: "শিক্ষাগত যোগ্যতা",
    experience: "অভিজ্ঞতা",
    staffDesignationPlaceholder: "যেমনঃ হিসাবরক্ষক, খাদেম, দারোয়ান",
    fatherNameBn: "পিতার নাম (বাংলা)",
    fatherNameAr: "পিতার নাম (আরবি)",
    fatherNameEn: "পিতার নাম (ইংরেজি)",
    fatherNid: "পিতার NID",
    fatherOccupation: "পিতার পেশা",
    motherNameBn: "মাতার নাম (বাংলা)",
    motherNameAr: "মাতার নাম (আরবি)",
    motherNameEn: "মাতার নাম (ইংরেজি)",
    motherNid: "মাতার NID",
    motherOccupation: "মাতার পেশা",
    guardianMobile: "অভিভাবকের মোবাইল নম্বর",
    enterFatherName: "পিতার নাম লিখুন",
    fatherNidNo: "পিতার NID নম্বর",
    enterMotherName: "মাতার নাম লিখুন",
    motherNidNo: "মাতার NID নম্বর",
    mobileNumber: "মোবাইল নম্বর",
    village: "গ্রাম",
    addressDivision: "বিভাগ",
    district: "জেলা",
    thana: "থানা",

    // Experience
    year: "বছর",
    month: "মাস",
    years: (n: string) => `${n} বছর`,
    months: (n: string) => `${n} মাস`,
    yearsMonths: (y: string, m: string) => `${y} বছর ${m} মাস`,

    // Bulk teacher upload (Excel)
    excelUploadFirst: "Excel ফাইল আপলোড করুন",
    rowNoName: (row: string) => `সারি ${row}: {{teacher}}ের নাম নেই`,
    rowNoDivision: (row: string) => `সারি ${row}: academic_division নেই`,
    bulkUploadSuccess: (inserted: string, updated: string) =>
      `বাল্ক আপলোড সফল ✅ নতুন: ${inserted} | আপডেট: ${updated}`,
    bulkUploadFailed: "বাল্ক আপলোড ব্যর্থ ❌",
    bulkTeacherUpload: "বাল্ক {{teacher}} আপলোড",
    bulkTeacherUploadHint: "Excel ফাইল আপলোড করে একসাথে একাধিক {{teacher}} যোগ করুন",
    uploadExcelSheet: "Excel শিট আপলোড করুন",
    requiredFieldsHint: "টেমপ্লেটে আবশ্যক ফিল্ডগুলো লাল রঙে ও * চিহ্নসহ থাকবে",
    genderHint: (male: string, female: string) => `লিঙ্গ: 1 = ${male}, 2 = ${female}`,
    requiredColumnsHint: "আবশ্যক কলাম: name_bn, academic_division",
    downloadTemplate: "টেমপ্লেট ডাউনলোড করুন",
    uploadTeacherExcel: "{{teacher}} Excel আপলোড করুন",
    previewTeachers: "{{teacher}} প্রিভিউ",
    totalFound: (n: string) => `মোট ${n} জন পাওয়া গেছে`,
    clearUploaded: "আপলোড করা ডেটা মুছুন",
    uploaded: "আপলোড হয়েছে",
    submitting: "জমা হচ্ছে...",
    submitAllTeachers: "সকল {{teacher}} জমা দিন",
    nameBnShort: "নাম (বাংলা)",

    // Bulk update (Excel)
    bulkUpdateTitle: "বাল্ক আপডেট (Excel)",
    bulkUpdateSubtitle: "বিদ্যমান {{teacher}}দের তথ্য একসাথে এক্সেল দিয়ে আপডেট করুন।",
    noTeacherToExport: "এক্সপোর্ট করার জন্য কোনো {{teacher}} পাওয়া যায়নি",
    excelLockNote:
      "ধূসর রঙের কলামগুলো (id, registration_no, academic_division_name) লক করা - এগুলোতে লেখা যাবে না। শুধু name_bn আবশ্যক (*), বাকি ঘর খালি রাখলে সেই তথ্য মুছে যাবে (division_id ব্যতিক্রম - খালি রাখলে অপরিবর্তিত থাকবে)।",
    lockedColumnsGuide: "লক করা কলাম (এগুলোতে লেখা যাবে না)",
    divisionGuide: "Division Guide (academic division id হিসেবে ব্যবহার করুন)",
    noChangesToSend: "পাঠানোর মতো কোনো পরিবর্তন পাওয়া যায়নি",
    bulkUpdateFailed: "বাল্ক আপডেট ব্যর্থ হয়েছে",
    bulkUpdateDone: "বাল্ক আপডেট সম্পন্ন হয়েছে",
    updatedCount: "আপডেট",
    unchangedCount: "অপরিবর্তিত",
    skippedCount: "বাদ পড়েছে",
    uploadAnotherExcel: "আরেকটি Excel আপলোড করুন",
    state: "অবস্থা",
    changesNotes: "পরিবর্তন / নোট",
    changedFields: "পরিবর্তিত ফিল্ড",
    statusUpdated: "আপডেট হয়েছে",
    statusUnchanged: "পরিবর্তন নেই",
    statusSkipped: "বাদ পড়েছে",
    exportUpload: "এক্সেল এক্সপোর্ট / আপলোড",
    exportHint: (n: string) => `বর্তমান ফিল্টার অনুযায়ী তালিকাভুক্ত ${n} জন {{teacher}}ের তথ্য এক্সপোর্ট হবে।`,
    lockedColsHint: "ধূসর কলাম (id, registration_no) লক করা - সম্পাদনা করা যাবে না।",
    exportExcel: "এক্সেল এক্সপোর্ট করুন",
    uploadUpdatedExcel: "আপডেট করা Excel আপলোড করুন",
    preview: "প্রিভিউ",
    previewSummary: (total: string, changed: string) =>
      `মোট ${total} সারি — এর মধ্যে ${changed} সারিতে পরিবর্তন পাওয়া গেছে`,
    idNotFound: "id পাওয়া যায়নি (তবুও পাঠানো হবে)",
    willChange: "পরিবর্তন হবে",
    noChange: "কোনো পরিবর্তন নেই",
    sending: "পাঠানো হচ্ছে...",
    updateN: (n: string) => `${n} জন আপডেট করুন`,

    // Dashboard
    totalTeachersLabel: "মোট {{teacher}}",
    totalStaffLabel: "মোট স্টাফ",
    quickActions: "দ্রুত অ্যাকশন",
    newTeacher: "নতুন {{teacher}}",
    teachers: "{{teacher}}সমূহ",
    newStaff: "নতুন স্টাফ",
    staffs: "স্টাফসমূহ",
    hiringTrend: "নিয়োগের প্রবণতা",
    hiringTrendSubtitle: "গত ১২ মাস, {{teacher}} বনাম স্টাফ",
    teacher: "{{teacher}}",
    staff: "স্টাফ",
    teacherByDesignation: "{{teacher}} - পদবি অনুযায়ী",
    staffByDesignation: "স্টাফ - পদবি অনুযায়ী",
    genderDistribution: "লিঙ্গ অনুযায়ী বণ্টন",
    teacherAndStaff: "{{teacher}} ও স্টাফ মিলিয়ে",
    loadTeacherFailed: "❌ {{teacher}}ের তথ্য লোড করা যায়নি",
    loadStaffProfileFailed: "❌ স্টাফের তথ্য লোড করা যায়নি",
    teacherUpdated: "✅ {{teacher}}ের তথ্য সফলভাবে আপডেট হয়েছে",
    staffUpdated: "✅ স্টাফের তথ্য সফলভাবে আপডেট হয়েছে",
    updateFailed: "❌ আপডেট করা যায়নি",
    teacherProfile: "{{teacher}} প্রোফাইল",
    staffProfile: "স্টাফ প্রোফাইল",
  },
  en: {
    fields: {
      registration_no: "Registration No.",
      division_id: "Academic {{division}} ID",
      academic_division: "Academic {{division}}",
      name: "Name",
      name_bn: "Name",
      name_ar: "Arabic Name",
      nid: "NID",
      gender: "Gender",
      dob: "Date of Birth",
      age: "Age",
      phone: "Phone",
      mobile: "Mobile",
      email: "Email",
      designation: "Designation",
      department: "Department (post)",
      qualification: "Qualification",
      experience_year: "Experience (years)",
      experience_month: "Experience (months)",
      joining_date: "Joining Date",
      salary: "Salary",
      father_name: "Father's Name",
      father_name_ar: "Father's Arabic Name",
      father_nid: "Father's NID",
      father_occupation: "Father's Occupation",
      mother_name: "Mother's Name",
      mother_nid: "Mother's NID",
      mother_occupation: "Mother's Occupation",
      parent_phone: "Guardian's Phone",
      division: "Division (address)",
      district: "District",
      thana: "Thana",
      village: "Village",
      image: "Photo",
    },
    male: "Male",
    female: "Female",
    allGenders: "All genders",
    none: "N/A",
    teacherList: "{{teacher}} List",
    staffList: "Staff List",
    totalTeachers: (n) => `Total {{teacher}}s: ${n}`,
    totalStaff: (n) => `Total staff: ${n}`,
    addTeacher: "+ Add New {{teacher}}",
    addStaff: "+ Add New Staff",
    listSearchPlaceholder: "Search by ID, name, phone or designation",
    allAcademicDivisions: "All academic {{division}}s",
    bulkUpdate: "Bulk Update",
    noTeacherFound: "No {{teacher}} found",
    noStaffFound: "No staff found",
    loadTeachersFailed: "Could not load the {{teacher}} list",
    loadStaffFailed: "Could not load the staff list",
    deleteTeacherTitle: "Delete {{teacher}}?",
    deleteTeacherMessage: "Move this {{teacher}} to the trash? You can restore them from the trash later if needed.",
    deleteStaffTitle: "Delete staff member?",
    deleteStaffMessage: "Move this staff member to the trash? You can restore them from the trash later if needed.",
    moveToTrash: "Move to trash",
    movedToTrash: "🗑️ Moved to trash",
    deleteFailed: "❌ Could not delete",
    regShort: (reg) => `Reg. ${reg}`,
    searchOtherTeacher: "Find another {{teacher}} — name / reg. / designation",
    searchOtherTeacherAria: "Find another {{teacher}}",
    searchOtherStaff: "Find another staff member — name / reg. / designation",
    searchOtherStaffAria: "Find another staff member",
    teacherRegistration: "New {{teacher}} Registration",
    staffRegistration: "New Staff Registration",
    saveTeacher: "Save {{teacher}}",
    saveStaff: "Save Staff",
    bulkUpload: "Bulk Upload",
    enterTeacherName: "Enter the {{teacher}}'s name",
    enterStaffName: "Enter the staff member's name",
    selectAcademicDivision: "Select an academic {{division}}",
    teacherAdded: "{{teacher}} added successfully ✅",
    teacherAddFailed: "Failed to add {{teacher}} ❌",
    staffAdded: "Staff added successfully ✅",
    staffAddFailed: "Failed to add staff ❌",
    teacherInfo: "{{teacher}} Information",
    staffInfo: "Staff Information",
    familyInfo: "Family Information",
    addressInfo: "Address Information",
    teacherPhoto: "{{teacher}} Photo",
    staffPhoto: "Staff Photo",
    nameBn: "Name (Bangla)",
    nameAr: "Name (Arabic)",
    nameEn: "Name (English)",
    educationalQualification: "Educational Qualification",
    experience: "Experience",
    staffDesignationPlaceholder: "e.g. Accountant, Khadem, Guard",
    fatherNameBn: "Father's Name (Bangla)",
    fatherNameAr: "Father's Name (Arabic)",
    fatherNameEn: "Father's Name (English)",
    fatherNid: "Father's NID",
    fatherOccupation: "Father's Occupation",
    motherNameBn: "Mother's Name (Bangla)",
    motherNameAr: "Mother's Name (Arabic)",
    motherNameEn: "Mother's Name (English)",
    motherNid: "Mother's NID",
    motherOccupation: "Mother's Occupation",
    guardianMobile: "Guardian's Mobile Number",
    enterFatherName: "Enter father's name",
    fatherNidNo: "Father's NID number",
    enterMotherName: "Enter mother's name",
    motherNidNo: "Mother's NID number",
    mobileNumber: "Mobile number",
    village: "Village",
    addressDivision: "Division",
    district: "District",
    thana: "Thana",
    year: "Year",
    month: "Month",
    years: (n) => `${n} yr`,
    months: (n) => `${n} mo`,
    yearsMonths: (y, m) => `${y} yr ${m} mo`,
    excelUploadFirst: "Please upload an Excel file",
    rowNoName: (row) => `Row ${row}: {{teacher}} name is missing`,
    rowNoDivision: (row) => `Row ${row}: academic_division is missing`,
    bulkUploadSuccess: (inserted, updated) => `Bulk upload successful ✅ New: ${inserted} | Updated: ${updated}`,
    bulkUploadFailed: "Bulk upload failed ❌",
    bulkTeacherUpload: "Bulk {{teacher}} Upload",
    bulkTeacherUploadHint: "Upload an Excel file to add many {{teacher}}s at once",
    uploadExcelSheet: "Upload Excel Sheet",
    requiredFieldsHint: "Required fields are marked in red with * in the template",
    genderHint: (male, female) => `Gender: 1 = ${male}, 2 = ${female}`,
    requiredColumnsHint: "Required columns: name_bn, academic_division",
    downloadTemplate: "Download Template",
    uploadTeacherExcel: "Upload {{teacher}} Excel",
    previewTeachers: "Preview {{teacher}}s",
    totalFound: (n) => `Total ${n} found`,
    clearUploaded: "Clear Uploaded Data",
    uploaded: "Uploaded",
    submitting: "Submitting...",
    submitAllTeachers: "Submit All {{teacher}}s",
    nameBnShort: "Name (Bangla)",
    bulkUpdateTitle: "Bulk Update (Excel)",
    bulkUpdateSubtitle: "Update existing {{teacher}}s' information together via Excel.",
    noTeacherToExport: "No {{teacher}} found to export",
    excelLockNote:
      "Grey columns (id, registration_no, academic_division_name) are locked - they cannot be edited. Only name_bn is required (*); leaving any other cell blank clears that value (except division_id - blank keeps it unchanged).",
    lockedColumnsGuide: "Locked columns (cannot be edited)",
    divisionGuide: "Division Guide (use as academic division id)",
    noChangesToSend: "No changes found to send",
    bulkUpdateFailed: "Bulk update failed",
    bulkUpdateDone: "Bulk update complete",
    updatedCount: "Updated",
    unchangedCount: "Unchanged",
    skippedCount: "Skipped",
    uploadAnotherExcel: "Upload another Excel",
    state: "Status",
    changesNotes: "Changes / Notes",
    changedFields: "Changed fields",
    statusUpdated: "Updated",
    statusUnchanged: "No change",
    statusSkipped: "Skipped",
    exportUpload: "Excel Export / Upload",
    exportHint: (n) => `Data for the ${n} {{teacher}}s in the current filter will be exported.`,
    lockedColsHint: "Grey columns (id, registration_no) are locked - they cannot be edited.",
    exportExcel: "Export Excel",
    uploadUpdatedExcel: "Upload updated Excel",
    preview: "Preview",
    previewSummary: (total, changed) => `${total} rows in total — changes found in ${changed}`,
    idNotFound: "id not found (will still be sent)",
    willChange: "Will change",
    noChange: "No change",
    sending: "Sending...",
    updateN: (n) => `Update ${n}`,
    totalTeachersLabel: "Total {{teacher}}s",
    totalStaffLabel: "Total Staff",
    quickActions: "Quick Actions",
    newTeacher: "New {{teacher}}",
    teachers: "{{teacher}}s",
    newStaff: "New Staff",
    staffs: "Staff",
    hiringTrend: "Hiring Trend",
    hiringTrendSubtitle: "Last 12 months, {{teacher}}s vs staff",
    teacher: "{{teacher}}",
    staff: "Staff",
    teacherByDesignation: "{{teacher}}s by designation",
    staffByDesignation: "Staff by designation",
    genderDistribution: "Gender Distribution",
    teacherAndStaff: "{{teacher}}s and staff combined",
    loadTeacherFailed: "❌ Failed to load {{teacher}}",
    loadStaffProfileFailed: "❌ Failed to load staff",
    teacherUpdated: "✅ {{teacher}} updated successfully",
    staffUpdated: "✅ Staff updated successfully",
    updateFailed: "❌ Update failed",
    teacherProfile: "{{teacher}} Profile",
    staffProfile: "Staff Profile",
  },
});

/** List-page column key (camelCase) -> data key used in `fields`. */
const COLUMN_FIELD: Record<string, string> = {
  registration: "registration_no",
  phone: "mobile",
  gender: "gender",
  designation: "designation",
  academicDivision: "academic_division",
  qualification: "qualification",
  nameAr: "name_ar",
  nid: "nid",
  dob: "dob",
  age: "age",
  email: "email",
  department: "department",
  experienceYear: "experience_year",
  experienceMonth: "experience_month",
  joiningDate: "joining_date",
  salary: "salary",
  fatherName: "father_name",
  fatherNameAr: "father_name_ar",
  fatherNid: "father_nid",
  fatherOccupation: "father_occupation",
  motherName: "mother_name",
  motherNid: "mother_nid",
  motherOccupation: "mother_occupation",
  parentPhone: "parent_phone",
  addressDivision: "division",
  district: "district",
  thana: "thana",
  village: "village",
};

/** Column label in the current UI language (reads fresh on each call). */
export const teacherStaffColumnLabel = (key: string): string => {
  const field = COLUMN_FIELD[key] ?? key;
  return getText(teacherStaffText).fields[field] ?? key;
};

/** `{ key, label }` column option whose label is a live-language getter. */
export const teacherStaffColumn = <K extends string>(key: K): { key: K; label: string } => ({
  key,
  get label() {
    return teacherStaffColumnLabel(key);
  },
});

/** Empty-value placeholder ("নেই" / "N/A") in the current UI language. */
export const orNoneText = (v: unknown) =>
  v === null || v === undefined || v === "" ? getText(teacherStaffText).none : String(v);
