import { defineText } from "@madrasha/shared-ui/src/i18n";

type EventLabel = { title: string; hint: string };

/** SMS/email pages. SMS bodies sent to guardians are data, not UI. */
export const notificationsText = defineText({
  bn: {
    events: {
      ADMISSION: {
        title: "ভর্তি অনুমোদনের পর",
        hint: "একজন শিক্ষার্থীর ভর্তি {{head}} অনুমোদন করলে অভিভাবককে স্বয়ংক্রিয়ভাবে SMS যাবে",
      },
      INFO_UPDATE: {
        title: "শিক্ষার্থীর তথ্য আপডেটের পর",
        hint: "কোনো শিক্ষার্থীর তথ্য এডিট করে সেভ করলে অভিভাবককে স্বয়ংক্রিয়ভাবে SMS যাবে",
      },
      FEE_PAYMENT: {
        title: "ফি জমা নেওয়ার পর",
        hint: "কোনো ইনভয়েসে পেমেন্ট রেকর্ড করলে অভিভাবককে স্বয়ংক্রিয়ভাবে SMS যাবে",
      },
      SALARY_PAYMENT: {
        title: "শিক্ষক বেতন পরিশোধের পর",
        hint: "পেরোল পেজে কোনো শিক্ষকের বেতন পরিশোধিত হিসেবে চিহ্নিত করলে তাকে স্বয়ংক্রিয়ভাবে SMS যাবে",
      },
      RESULT_PUBLISHED: {
        title: "পরীক্ষার ফলাফল প্রকাশের পর",
        hint: "{{academic}} প্যানেলে কোনো পরীক্ষার ফলাফল প্রকাশ করলে সংশ্লিষ্ট শ্রেণির প্রতিটি শিক্ষার্থীর অভিভাবককে স্বয়ংক্রিয়ভাবে SMS যাবে",
      },
      EXAM_FEE_ACTIVATED: {
        title: "পরীক্ষার ফি চালু হওয়ার পর",
        hint: "কোনো পরীক্ষার ফি চালু (activate) করলে সংশ্লিষ্ট শিক্ষার্থীর অভিভাবককে স্বয়ংক্রিয়ভাবে SMS যাবে",
      },
      ATTENDANCE_PRESENT: {
        title: "ডিভাইসে উপস্থিতির পর",
        hint: "K40 ডিভাইসে শিক্ষার্থীর কার্ড/আঙুলের ছাপ নেওয়ার পর উপস্থিতি সার্ভারে সেভ হলে অভিভাবককে দিনে একবার SMS যাবে ({status} = উপস্থিত / দেরিতে উপস্থিত; ডিফল্টভাবে বন্ধ)",
      },
      ATTENDANCE_ABSENT: {
        title: "অনুপস্থিত হলে",
        hint: "ডিভাইস সেটিংসে ঠিক করা সময়ের মধ্যে পাঞ্চ না করলে শিক্ষার্থীকে স্বয়ংক্রিয়ভাবে অনুপস্থিত ধরা হয় এবং অভিভাবককে SMS যায় (ডিফল্টভাবে বন্ধ)",
      },
      ATTENDANCE_CHECKOUT: {
        title: "ডিভাইসে চেক-আউটের পর",
        hint: "ছুটির পর শিক্ষার্থী ডিভাইসে পাঞ্চ করে বের হলে অভিভাবককে দিনে একবার SMS যায় (ডিফল্টভাবে বন্ধ)",
      },
      ATTENDANCE_CONSECUTIVE_ABSENT: {
        title: "টানা অনুপস্থিত হলে",
        hint: "উপস্থিতি নীতিতে ঠিক করা সংখ্যক কর্মদিবস টানা অনুপস্থিত থাকলে অভিভাবককে দিনে একবার SMS যায় ({days} = দিন, {from} = যেদিন থেকে; ডিফল্টভাবে বন্ধ)",
      },
    } as Record<string, EventLabel>,
    saveFailed: "সেভ করতে সমস্যা হয়েছে",
    messageSaved: "বার্তা সেভ হয়েছে",
    allOn: "সবগুলো চালু হয়েছে",
    allOff: "সবগুলো বন্ধ হয়েছে",
    autoTitle: "অটো নোটিফিকেশন",
    autoSubtitle: "নির্দিষ্ট কাজের পর স্বয়ংক্রিয়ভাবে SMS পাঠানো চালু/বন্ধ করুন ও বার্তা কাস্টমাইজ করুন",
    allNotifications: "সবগুলো নোটিফিকেশন",
    masterHint:
      "বন্ধ করলে নিচের সবগুলো অটো SMS সাময়িকভাবে বন্ধ থাকবে (কোনটার সেটিংস বদলাবে না); আবার চালু করলে যার যার আগের অবস্থায় ফিরে যাবে",
    off: "বন্ধ",
    turnOnMasterFirst: "আগে উপরের 'সবগুলো নোটিফিকেশন' চালু করুন",
    placeholders: (list: string) => `প্লেসহোল্ডার: ${list}`,
    saving: "সেভ হচ্ছে...",
    modes: {
      all_students: "সব শিক্ষার্থী",
      class_students: "নির্দিষ্ট ক্লাস",
      all_teachers: "সব শিক্ষক",
      results: "রেজাল্ট (এক্সাম)",
    } as Record<string, string>,
    writeMessage: "মেসেজ লিখুন",
    enterSubject: "ইমেইলের জন্য সাবজেক্ট দিন",
    sentSummary: (sent: string, failed: string) => `পাঠানো হয়েছে: ${sent} জন, ব্যর্থ: ${failed} জন`,
    sendFailed: "পাঠাতে সমস্যা হয়েছে",
    bulkTitle: "বাল্ক পাঠান",
    bulkSubtitle: "একসাথে অনেকজনকে SMS/ইমেইল পাঠান — প্রতিজনের নাম/রোল/নম্বর মেসেজে বসিয়ে দেওয়া যাবে",
    sendToAll: "সবাইকে পাঠান",
    chooseDivision: "{{division}} বাছুন",
    chooseClass: "ক্লাস বাছুন",
    chooseExam: "পরীক্ষা বাছুন",
    loading: "লোড হচ্ছে...",
    recipientsSelected: (n: string) => `${n} জন প্রাপক নির্বাচিত`,
    noStudentEmails: "শিক্ষার্থীদের কোনো ইমেইল ঠিকানা নেই — এই তালিকার জন্য শুধু SMS ব্যবহার করুন",
    email: "ইমেইল",
    sent: "পাঠানো",
    failed: "ব্যর্থ",
    pending: "পেন্ডিং",
    totalSent: "মোট পাঠানো",
    smsSent: "SMS পাঠানো",
    emailSub: (n: string) => `ইমেইল: ${n}`,
    quickActions: "দ্রুত অ্যাকশন",
    singleSend: "একক পাঠান",
    sendHistory: "পাঠানোর ইতিহাস",
    sendTrend: "পাঠানোর প্রবণতা",
    last14Days: "গত ১৪ দিন",
    byChannel: "চ্যানেল অনুযায়ী",
    smsVsEmail: "SMS বনাম ইমেইল",
    message: "মেসেজ",
    send: "পাঠান",
    subject: "সাবজেক্ট",
    sending: "পাঠানো হচ্ছে...",
    sendWithCount: (label: string, n: string) => `${label} (${n} জন)`,
    statusPending: "প্রক্রিয়াধীন",
    statusSent: "পাঠানো হয়েছে",
    noHistory: "কোনো ইতিহাস নেই",
    subjectLabel: "বিষয়:",
    errorLabel: "ত্রুটি:",
    historySubtitle: "SMS/ইমেইল পাঠানোর সম্পূর্ণ ইতিহাস",
    allRecords: "সব রেকর্ড",
    allStatuses: "সব স্ট্যাটাস",
    numberNotFound: "এই নম্বর পাওয়া যায়নি",
    emailNotFound: "এই ইমেইল পাওয়া যায়নি",
    singleSubtitle: "একজন নির্দিষ্ট শিক্ষার্থীর অভিভাবক বা শিক্ষককে SMS/ইমেইল পাঠান",
    enterNumber: "নম্বর লিখুন",
    enterEmail: "ইমেইল লিখুন",
    student: "শিক্ষার্থী",
    teacher: "শিক্ষক",
    phonePlaceholder: "যেমন: 01712345678",
    emailPlaceholder: "যেমন: example@mail.com",
    change: "বদলান",
    searchPlaceholder: "নাম বা রোল দিয়ে খুঁজুন...",
    noneFound: "কেউ পাওয়া যায়নি",
    roll: "রোল",
  },
  en: {
    events: {
      ADMISSION: { title: "After admission approval", hint: "When the {{head}} approves a student's admission, the guardian gets an SMS automatically" },
      INFO_UPDATE: { title: "After student info update", hint: "When a student's info is edited and saved, the guardian gets an SMS automatically" },
      FEE_PAYMENT: { title: "After fee collection", hint: "When a payment is recorded on an invoice, the guardian gets an SMS automatically" },
      SALARY_PAYMENT: { title: "After teacher salary payment", hint: "When a teacher's salary is marked paid on the payroll page, they get an SMS automatically" },
      RESULT_PUBLISHED: {
        title: "After exam result is published",
        hint: "When an exam result is published in the {{academic}} panel, every guardian of that class gets an SMS automatically",
      },
      EXAM_FEE_ACTIVATED: { title: "After exam fee is activated", hint: "When an exam fee is activated, the related students' guardians get an SMS automatically" },
      ATTENDANCE_PRESENT: {
        title: "After device attendance",
        hint: "After a card/fingerprint on the K40 device is saved as attendance, the guardian gets one SMS per day ({status} = present / late; off by default)",
      },
      ATTENDANCE_ABSENT: {
        title: "When absent",
        hint: "If a student doesn't punch on the device by the cut-off time set in device settings, they are marked absent automatically and the guardian gets an SMS (off by default)",
      },
      ATTENDANCE_CHECKOUT: {
        title: "After device check-out",
        hint: "When a student punches out on the device after school, the guardian gets one SMS per day (off by default)",
      },
      ATTENDANCE_CONSECUTIVE_ABSENT: {
        title: "When absent several days in a row",
        hint: "When a student is absent for the number of consecutive working days set in the attendance policy, the guardian gets one SMS per day ({days} = days, {from} = since; off by default)",
      },
    },
    saveFailed: "Could not save",
    messageSaved: "Message saved",
    allOn: "All turned on",
    allOff: "All turned off",
    autoTitle: "Auto Notifications",
    autoSubtitle: "Turn automatic SMS after specific actions on/off and customize the messages",
    allNotifications: "All notifications",
    masterHint:
      "Turning this off pauses every auto SMS below without changing their settings; turning it back on restores each to its previous state",
    off: "Off",
    turnOnMasterFirst: "Turn on 'All notifications' above first",
    placeholders: (list) => `Placeholders: ${list}`,
    saving: "Saving...",
    modes: {
      all_students: "All students",
      class_students: "Specific class",
      all_teachers: "All teachers",
      results: "Results (exam)",
    },
    writeMessage: "Write a message",
    enterSubject: "Enter a subject for email",
    sentSummary: (sent, failed) => `Sent: ${sent}, failed: ${failed}`,
    sendFailed: "Could not send",
    bulkTitle: "Bulk Send",
    bulkSubtitle: "Send SMS/email to many people at once — each person's name/roll/marks can be inserted into the message",
    sendToAll: "Send to all",
    chooseDivision: "Choose {{division}}",
    chooseClass: "Choose class",
    chooseExam: "Choose exam",
    loading: "Loading...",
    recipientsSelected: (n) => `${n} recipients selected`,
    noStudentEmails: "Students have no email addresses — use SMS for this list",
    email: "Email",
    sent: "Sent",
    failed: "Failed",
    pending: "Pending",
    totalSent: "Total Sent",
    smsSent: "SMS Sent",
    emailSub: (n) => `Email: ${n}`,
    quickActions: "Quick Actions",
    singleSend: "Single Send",
    sendHistory: "Send History",
    sendTrend: "Sending Trend",
    last14Days: "Last 14 days",
    byChannel: "By Channel",
    smsVsEmail: "SMS vs Email",
    message: "Message",
    send: "Send",
    subject: "Subject",
    sending: "Sending...",
    sendWithCount: (label, n) => `${label} (${n})`,
    statusPending: "Processing",
    statusSent: "Sent",
    noHistory: "No history",
    subjectLabel: "Subject:",
    errorLabel: "Error:",
    historySubtitle: "Complete SMS/email sending history",
    allRecords: "All records",
    allStatuses: "All statuses",
    numberNotFound: "This number was not found",
    emailNotFound: "This email was not found",
    singleSubtitle: "Send SMS/email to a specific student's guardian or a teacher",
    enterNumber: "Enter number",
    enterEmail: "Enter email",
    student: "Student",
    teacher: "Teacher",
    phonePlaceholder: "e.g. 01712345678",
    emailPlaceholder: "e.g. example@mail.com",
    change: "Change",
    searchPlaceholder: "Search by name or roll...",
    noneFound: "No one found",
    roll: "Roll",
  },
});
