import { defineBilingualText } from "@madrasha/shared-ui/src/i18n";

/** SMS/Email billing: packages, purchase requests, pricing, reports. */
export const billingText = defineBilingualText({
  bn: {
    // shared
    active: "সক্রিয়",
    inactive: "নিষ্ক্রিয়",
    pending: "পেন্ডিং",
    approved: "অনুমোদিত",
    rejected: "বাতিলকৃত",
    typePackage: "প্যাকেজ",
    typeRecharge: "রিচার্জ",
    loadFailed: "লোড করা যায়নি",
    saveFailed: "সংরক্ষণ করা যায়নি",
    refresh: "রিফ্রেশ",
    status: "স্ট্যাটাস",
    all: "সব",
    total: "মোট",
    edit: "এডিট",
    toggle: "টগল",
    delete: "মুছুন",
    days: (n: string) => `${n} দিন`,

    // packages
    smsCredit: "SMS ক্রেডিট",
    emailCredit: "Email ক্রেডিট",
    packagesTitle: (channel: string) => `${channel} প্যাকেজ`,
    packagesSubtitle: (channel: string) => `প্রতিষ্ঠানগুলোর জন্য ${channel} ক্রেডিট প্যাকেজ ও রিচার্জ ম্যানেজ করুন।`,
    newPackage: "+ নতুন প্যাকেজ",
    editPackageTitle: (channel: string, id: string) => `${channel} প্যাকেজ এডিট — #${id}`,
    newPackageTitle: (channel: string) => `নতুন ${channel} প্যাকেজ`,
    errPackageName: "প্যাকেজের নাম দিন",
    errPrice: "মূল্য ০ বা তার বেশি হতে হবে",
    errCredit: "ক্রেডিট ০ এর বেশি হতে হবে",
    errValidity: "মেয়াদ (দিন) ১ বা তার বেশি হতে হবে",
    packageUpdated: "প্যাকেজ আপডেট হয়েছে",
    packageCreated: "প্যাকেজ তৈরি হয়েছে",
    statusUpdated: "স্ট্যাটাস আপডেট হয়েছে",
    toggleFailed: "স্ট্যাটাস বদলানো যায়নি",
    packageDeleted: "প্যাকেজ মুছে ফেলা হয়েছে",
    packageDeleteFailed: "মুছে ফেলা যায়নি — সম্ভবত এই প্যাকেজ এখনও কোনো চলমান সাবস্ক্রিপশনে ব্যবহৃত হচ্ছে",
    noPackages: "কোনো প্যাকেজ পাওয়া যায়নি",
    noPackagesHint: 'নতুন প্যাকেজ যোগ করতে "নতুন প্যাকেজ" চাপুন',
    price: "মূল্য",
    colName: "নাম",
    colType: "ধরন",
    colValidity: "মেয়াদ",
    colActions: "অ্যাকশন",
    packageName: "প্যাকেজের নাম",
    smsNamePlaceholder: "যেমন: 5,000 SMS / 90 দিন",
    emailNamePlaceholder: "যেমন: 10,000 Email / 30 দিন",
    descriptionOptional: "বিবরণ (ঐচ্ছিক)",
    typeLabel: "ধরন",
    typeHint: "প্যাকেজ মেয়াদ সহ আসে (validity days); রিচার্জ শুধু ক্রেডিট যোগ করে, মেয়াদ ছাড়া।",
    validityDays: "মেয়াদ (দিন)",
    notApplicable: "(প্রযোজ্য নয়)",
    priceTaka: "মূল্য (৳)",
    currency: "মুদ্রা",
    deletePackageTitle: "প্যাকেজ মুছবেন?",
    deletePackageMessage: (name: string) =>
      `প্যাকেজ "${name}" স্থায়ীভাবে মুছে যাবে। এটি কোনো চলমান সাবস্ক্রিপশনে ব্যবহৃত থাকলে মুছে ফেলা ব্যর্থ হবে।`,

    // requests
    requestsTitle: "ক্রয় রিকোয়েস্ট",
    requestsSubtitle: "প্রতিষ্ঠানগুলোর SMS/Email ক্রেডিট ক্রয় রিকোয়েস্ট যাচাই করে অনুমোদন/বাতিল করুন।",
    approveTitle: "রিকোয়েস্ট অনুমোদন করবেন?",
    rejectTitle: "রিকোয়েস্ট বাতিল করবেন?",
    requestApproved: "রিকোয়েস্ট অনুমোদিত হয়েছে",
    requestRejected: "রিকোয়েস্ট বাতিল হয়েছে",
    actionFailed: "কাজটি সম্পন্ন করা যায়নি",
    noRequests: "কোনো রিকোয়েস্ট পাওয়া যায়নি",
    amount: "পরিমাণ",
    paymentMethod: "পেমেন্ট মাধ্যম",
    ref: "রেফ",
    note: "নোট",
    submitted: "জমার সময়",
    approve: "অনুমোদন",
    reject: "বাতিল",
    colInstitution: "প্রতিষ্ঠান",
    colChannel: "চ্যানেল",
    colPackage: "প্যাকেজ",
    colPayment: "পেমেন্ট",
    reviewNote: "রিভিউ নোট (ঐচ্ছিক)",
    approveNotePlaceholder: "যেমন: bKash এ পেমেন্ট যাচাই করা হয়েছে",
    rejectNotePlaceholder: "বাতিল করার কারণ লিখুন",
    pleaseWait: "অপেক্ষা করুন...",

    // pricing
    pricingTitle: "বিলিং প্রাইসিং",
    pricingSubtitle: "SMS ও Email এর global বিক্রয়মূল্য, প্রোভাইডার খরচ ও low-credit threshold সেট করুন।",
    smsPricing: "SMS প্রাইসিং",
    emailPricing: "Email প্রাইসিং",
    perSegment: "প্রতি সেগমেন্ট",
    perEmail: "প্রতি ইমেইল",
    unitPricing: (unit: string) => `${unit} মূল্য (৳)`,
    sellingPrice: "বিক্রয়মূল্য (৳)",
    sellingPriceHint: (unit: string) => `প্রতিষ্ঠানগুলোর কাছে বিক্রয়মূল্য — ${unit}।`,
    providerCost: "প্রোভাইডার খরচ (৳)",
    providerCostHint: "Gateway/provider এর প্রকৃত খরচ — শুধু সুপার অ্যাডমিন দেখবেন (profit report)।",
    lowCreditThreshold: "লো-ক্রেডিট সীমা",
    lowCreditHint: 'এর নিচে অবশিষ্ট ক্রেডিট নামলে প্রতিষ্ঠানটি "low credit" তালিকায় দেখাবে।',
    errSellingPrice: "বিক্রয়মূল্য ০ বা তার বেশি হতে হবে",
    errProviderCost: "প্রোভাইডার খরচ ০ বা তার বেশি হতে হবে",
    errThreshold: "লো-ক্রেডিট সীমা ০ বা তার বেশি হতে হবে",
    pricingUpdated: "প্রাইসিং আপডেট হয়েছে",

    // reports
    reportsTitle: "বিলিং রিপোর্ট",
    reportsSubtitle: "আয়, খরচ ও লাভের সারসংক্ষেপ।",
    unitSms: "SMS",
    unitEmails: "Email",
    totalSold: (u: string) => `মোট বিক্রি (${u})`,
    totalUsed: (u: string) => `মোট ব্যবহার (${u})`,
    totalRemaining: (u: string) => `মোট অবশিষ্ট (${u})`,
    activeSubscriptions: "সক্রিয় সাবস্ক্রিপশন",
    revenue: "আয়",
    providerCostTotal: "প্রোভাইডার খরচ",
    profit: "লাভ",
    loss: "লোকসান",
    expiredSubscriptions: "মেয়াদোত্তীর্ণ সাবস্ক্রিপশন",
    today: "আজ",
    thisMonth: "এই মাস",
    requests: "রিকোয়েস্ট",
    creditUsed: "ব্যবহৃত ক্রেডিট",
    cost: "খরচ",
    lowCreditTitle: "লো-ক্রেডিট প্রতিষ্ঠান",
    lowCreditSubtitle: "যেসব প্রতিষ্ঠানের অবশিষ্ট ক্রেডিট সীমার নিচে নেমে গেছে।",
    colSlug: "স্লাগ",
    remainingCredit: "অবশিষ্ট ক্রেডিট",
    noLowCredit: "কোনো লো-ক্রেডিট প্রতিষ্ঠান নেই",
  },
  en: {
    active: "Active",
    inactive: "Inactive",
    pending: "Pending",
    approved: "Approved",
    rejected: "Rejected",
    typePackage: "Package",
    typeRecharge: "Recharge",
    loadFailed: "Load failed",
    saveFailed: "Save failed",
    refresh: "Refresh",
    status: "Status",
    all: "All",
    total: "Total",
    edit: "Edit",
    toggle: "Toggle",
    delete: "Delete",
    days: (n) => `${n} days`,

    smsCredit: "SMS Credit",
    emailCredit: "Email Credit",
    packagesTitle: (channel) => `${channel} Packages`,
    packagesSubtitle: (channel) => `Manage ${channel} credit packages and recharges for institutions.`,
    newPackage: "+ New Package",
    editPackageTitle: (channel, id) => `Edit ${channel} Package — #${id}`,
    newPackageTitle: (channel) => `New ${channel} Package`,
    errPackageName: "Enter the package name",
    errPrice: "Price must be 0 or more",
    errCredit: "Credit must be more than 0",
    errValidity: "Validity days must be 1 or more",
    packageUpdated: "Package updated",
    packageCreated: "Package created",
    statusUpdated: "Status updated",
    toggleFailed: "Toggle failed",
    packageDeleted: "Package deleted",
    packageDeleteFailed: "Delete failed — this package is probably still used by an active subscription",
    noPackages: "No packages found",
    noPackagesHint: 'Press "New Package" to add one',
    price: "Price",
    colName: "Name",
    colType: "Type",
    colValidity: "Validity",
    colActions: "Actions",
    packageName: "Package Name",
    smsNamePlaceholder: "e.g. 5,000 SMS / 90 days",
    emailNamePlaceholder: "e.g. 10,000 Emails / 30 days",
    descriptionOptional: "Description (optional)",
    typeLabel: "Type",
    typeHint: "A package comes with validity days; a recharge only adds credit, without expiry.",
    validityDays: "Validity Days",
    notApplicable: "(N/A)",
    priceTaka: "Price (৳)",
    currency: "Currency",
    deletePackageTitle: "Delete Package?",
    deletePackageMessage: (name) =>
      `Package "${name}" will be permanently deleted. Deletion fails if an active subscription uses it.`,

    requestsTitle: "Purchase Requests",
    requestsSubtitle: "Review institutions' SMS/Email credit purchase requests and approve/reject them.",
    approveTitle: "Approve Request?",
    rejectTitle: "Reject Request?",
    requestApproved: "Request approved",
    requestRejected: "Request rejected",
    actionFailed: "Action failed",
    noRequests: "No requests found",
    amount: "Amount",
    paymentMethod: "Payment Method",
    ref: "Ref",
    note: "Note",
    submitted: "Submitted",
    approve: "Approve",
    reject: "Reject",
    colInstitution: "Institution",
    colChannel: "Channel",
    colPackage: "Package",
    colPayment: "Payment",
    reviewNote: "Review Note (optional)",
    approveNotePlaceholder: "e.g. payment verified on bKash",
    rejectNotePlaceholder: "Write the reason for rejecting",
    pleaseWait: "Please wait...",

    pricingTitle: "Billing Pricing",
    pricingSubtitle: "Set the global SMS and Email selling price, provider cost and low-credit threshold.",
    smsPricing: "SMS Pricing",
    emailPricing: "Email Pricing",
    perSegment: "Per segment",
    perEmail: "Per email",
    unitPricing: (unit) => `${unit} pricing (৳)`,
    sellingPrice: "Selling Price (৳)",
    sellingPriceHint: (unit) => `Selling price to institutions — ${unit.toLowerCase()}.`,
    providerCost: "Provider Cost (৳)",
    providerCostHint: "Actual gateway/provider cost — visible to the super admin only (profit report).",
    lowCreditThreshold: "Low Credit Threshold",
    lowCreditHint: 'When remaining credit falls below this, the institution shows up in the "low credit" list.',
    errSellingPrice: "Selling price must be 0 or more",
    errProviderCost: "Provider cost must be 0 or more",
    errThreshold: "Low credit threshold must be 0 or more",
    pricingUpdated: "Pricing updated",

    reportsTitle: "Billing Reports",
    reportsSubtitle: "Summary of revenue, cost and profit.",
    unitSms: "SMS",
    unitEmails: "Emails",
    totalSold: (u) => `Total Sold (${u})`,
    totalUsed: (u) => `Total Used (${u})`,
    totalRemaining: (u) => `Total Remaining (${u})`,
    activeSubscriptions: "Active Subscriptions",
    revenue: "Revenue",
    providerCostTotal: "Provider Cost",
    profit: "Profit",
    loss: "Loss",
    expiredSubscriptions: "Expired Subscriptions",
    today: "Today",
    thisMonth: "This Month",
    requests: "Requests",
    creditUsed: "Credit Used",
    cost: "Cost",
    lowCreditTitle: "Low Credit Institutions",
    lowCreditSubtitle: "Institutions whose remaining credit fell below the threshold.",
    colSlug: "Slug",
    remainingCredit: "Remaining Credit",
    noLowCredit: "No low-credit institutions",
  },
});
