import { defineText } from "@madrasha/shared-ui/src/i18n";

export const payrollText = defineText({
  bn: {
    status: { PENDING: "বকেয়া", PAID: "পরিশোধিত" },
    selectMonth: "মাস নির্বাচন করুন",
    generated: (created: string, skipped: string) =>
      `পেরোল তৈরি হয়েছে: ${created} জন {{teacher}}ের (আগে থেকে ছিল: ${skipped} জন)`,
    generateFailed: "পেরোল তৈরি করতে সমস্যা হয়েছে",
    selectFundCategory: "ফান্ড ও খাত নির্বাচন করুন",
    markedPaid: "বেতন পরিশোধিত হিসেবে চিহ্নিত হয়েছে",
    markPaidFailed: "পরিশোধ নিশ্চিত করতে সমস্যা হয়েছে",
    pageTitle: "{{teacher}} বেতন (পেরোল)",
    generateSubtitle: "মাস নির্বাচন করে সব সক্রিয় {{teacher}}ের বেতন একসাথে জেনারেট করুন",
    reportSubtitle: "কোন মাসে কার বেতন দেওয়া হয়েছে, কার বকেয়া আছে - এক নজরে দেখুন",
    tabGenerate: "পেরোল জেনারেট ও তালিকা",
    tabReport: "বেতন রেজিস্টার রিপোর্ট",
    allStatus: "সব স্ট্যাটাস",
    generating: "তৈরি হচ্ছে...",
    generateThisMonth: "এই মাসের পেরোল তৈরি করুন",
    alreadyGenerated: "এই মাসের পেরোল ইতিমধ্যে তৈরি করা হয়েছে",
    total: "মোট",
    paid: "পরিশোধিত",
    due: "বকেয়া",
    noPayroll: "এই মাসে এখনো কোনো পেরোল তৈরি করা হয়নি",
    teacherFallback: (id: string) => `{{teacher}} #${id}`,
    basicSalary: "মূল বেতন",
    allowances: "ভাতা",
    deductions: "কর্তন",
    net: "নীট",
    pay: "পরিশোধ করুন",
    confirmPayTitle: (name: string) => `বেতন পরিশোধ নিশ্চিত করুন — ${name}`,
    confirmPayBefore: "নীট বেতন",
    confirmPayAfter: "পরিশোধিত হিসেবে চিহ্নিত হবে এবং অ্যাকাউন্টস লেজারে খরচ হিসেবে যুক্ত হবে।",
    fund: "ফান্ড",
    category: "খাত",
    yesMarkPaid: "হ্যাঁ, পরিশোধিত করুন",
    // Report
    months: ["জানু", "ফেব্রু", "মার্চ", "এপ্রিল", "মে", "জুন", "জুলাই", "আগস্ট", "সেপ্ট", "অক্টো", "নভে", "ডিসে"],
    teacher: "{{teacher}}",
    designation: "পদবি",
    totalDue: "মোট বকেয়া",
    notGenerated: "তৈরি হয়নি",
    paidWith: (amount: string) => `পরিশোধিত (${amount})`,
    dueWith: (amount: string) => `বকেয়া (${amount})`,
    onlyDueTeachers: "শুধু বকেয়া {{teacher}} দেখান",
    registerTitle: "{{teacher}} বেতন রেজিস্টার",
    teachersWithDue: (n: string) => `বকেয়া {{teacher}}: ${n} জন`,
    totalPaid: "মোট পরিশোধিত",
    noRecordsForYear: (year: string) => `${year} সালের কোনো পেরোল রেকর্ড পাওয়া যায়নি`,
    monthlyTotal: "মাসিক মোট",
  },
  en: {
    status: { PENDING: "Due", PAID: "Paid" },
    selectMonth: "Select a month",
    generated: (created, skipped) => `Payroll generated for ${created} {{teacher}}s (already existed: ${skipped})`,
    generateFailed: "Could not generate payroll",
    selectFundCategory: "Select a fund and category",
    markedPaid: "Salary marked as paid",
    markPaidFailed: "Could not confirm the payment",
    pageTitle: "{{teacher}} Salary (Payroll)",
    generateSubtitle: "Pick a month to generate salaries for all active {{teacher}}s at once",
    reportSubtitle: "See at a glance who has been paid and who is due in each month",
    tabGenerate: "Generate & List Payroll",
    tabReport: "Salary Register Report",
    allStatus: "All statuses",
    generating: "Generating...",
    generateThisMonth: "Generate this month's payroll",
    alreadyGenerated: "This month's payroll has already been generated",
    total: "Total",
    paid: "Paid",
    due: "Due",
    noPayroll: "No payroll has been generated for this month yet",
    teacherFallback: (id) => `{{teacher}} #${id}`,
    basicSalary: "Basic",
    allowances: "Allowances",
    deductions: "Deductions",
    net: "Net",
    pay: "Pay",
    confirmPayTitle: (name) => `Confirm Salary Payment — ${name}`,
    confirmPayBefore: "Net salary",
    confirmPayAfter: "will be marked as paid and recorded as an expense in the accounts ledger.",
    fund: "Fund",
    category: "Category",
    yesMarkPaid: "Yes, mark as paid",
    months: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    teacher: "{{teacher}}",
    designation: "Designation",
    totalDue: "Total Due",
    notGenerated: "Not generated",
    paidWith: (amount) => `Paid (${amount})`,
    dueWith: (amount) => `Due (${amount})`,
    onlyDueTeachers: "Show only {{teacher}}s with dues",
    registerTitle: "{{teacher}} Salary Register",
    teachersWithDue: (n) => `{{teacher}}s with dues: ${n}`,
    totalPaid: "Total Paid",
    noRecordsForYear: (year) => `No payroll records found for ${year}`,
    monthlyTotal: "Monthly Total",
  },
});
