import { defineText } from "@madrasha/shared-ui/src/i18n";

export const authText = defineText({
  bn: {
    loginTitle: "{{institution}} অ্যাডমিন লগইন",
    loggedIn: "লগইন হয়েছে",
    pickSavedAccount: "এই ডিভাইসে সংরক্ষিত অ্যাকাউন্ট থেকে বেছে নিন",
    loginWithOther: "অন্য {{institution}}/ইমেইল দিয়ে লগইন করুন",
    otherAccount: "অন্য অ্যাকাউন্ট",
    savedAccountList: "সংরক্ষিত অ্যাকাউন্ট তালিকা",
    password: "পাসওয়ার্ড",
    email: "ইমেইল",
    institutionCode: "{{institution}} কোড",
    showPassword: "পাসওয়ার্ড দেখান",
    hidePassword: "পাসওয়ার্ড লুকান",
    loggingIn: "লগইন হচ্ছে...",
    login: "লগইন",
    forgotPassword: "পাসওয়ার্ড ভুলে গেছেন?",
    // Forgot password
    enterInstitutionCode: "{{institution}} কোড দিন",
    enterEmail: "ইমেইল দিন",
    requestFailed: "অনুরোধ ব্যর্থ হয়েছে",
    forgotHint: "আপনার অ্যাকাউন্টের ইমেইল দিন — একটা রিসেট লিংক পাঠানো হবে।",
    resetLinkSent: "যদি এই ইমেইলে অ্যাকাউন্ট থাকে, একটা পাসওয়ার্ড রিসেট লিংক পাঠানো হয়েছে।",
    devMode: "ডেভ মোড (এখনো ইমেইল সার্ভিস সেটআপ করা হয়নি):",
    goToResetLink: "রিসেট লিংকে যেতে ক্লিক করুন",
    backToLogin: "লগইন পেজে ফিরে যান",
    sending: "পাঠানো হচ্ছে...",
    sendResetLink: "রিসেট লিংক পাঠান",
    // Reset password
    invalidResetLink: "রিসেট লিংক সঠিক নয়",
    passwordMin6: "পাসওয়ার্ড কমপক্ষে ৬ অক্ষরের হতে হবে",
    passwordMismatch: "দুটো পাসওয়ার্ড মিলছে না",
    passwordChanged: "পাসওয়ার্ড পরিবর্তন হয়েছে",
    resetFailed: "রিসেট করতে সমস্যা হয়েছে",
    setNewPassword: "নতুন পাসওয়ার্ড সেট করুন",
    linkInvalidTryAgain: 'এই লিংকটি সঠিক নয়। আবার "পাসওয়ার্ড ভুলে গেছেন" থেকে চেষ্টা করুন।',
    passwordChangedLogin: "আপনার পাসওয়ার্ড সফলভাবে পরিবর্তন হয়েছে। এখন লগইন করুন।",
    loginNow: "লগইন করুন",
    newPassword: "নতুন পাসওয়ার্ড",
    retypePassword: "পাসওয়ার্ড আবার লিখুন",
    changePassword: "পাসওয়ার্ড পরিবর্তন করুন",
    // Saved accounts
    removeFromSaved: "সংরক্ষিত তালিকা থেকে সরান",
    removeSavedTitle: "সংরক্ষিত লগইন সরাবেন?",
    removeSavedBody: (label: string) =>
      `(${label}) এই ডিভাইসের সংরক্ষিত লগইন তালিকা থেকে সরে যাবে। পরের বার এই অ্যাকাউন্টে লগইন করতে আবার {{institution}} কোড ও ইমেইল দিতে হবে।`,
    remove: "সরিয়ে দিন",
  },
  en: {
    loginTitle: "{{institution}} Admin Login",
    loggedIn: "Logged in",
    pickSavedAccount: "Choose an account saved on this device",
    loginWithOther: "Log in with another {{institution}}/email",
    otherAccount: "Other account",
    savedAccountList: "Saved accounts",
    password: "Password",
    email: "Email",
    institutionCode: "{{institution}} code",
    showPassword: "Show password",
    hidePassword: "Hide password",
    loggingIn: "Logging in...",
    login: "Login",
    forgotPassword: "Forgot password?",
    enterInstitutionCode: "Enter the {{institution}} code",
    enterEmail: "Enter your email",
    requestFailed: "Request failed",
    forgotHint: "Enter your account email — a reset link will be sent.",
    resetLinkSent: "If an account exists for this email, a password reset link has been sent.",
    devMode: "Dev mode (no email service configured yet):",
    goToResetLink: "Click to open the reset link",
    backToLogin: "Back to login",
    sending: "Sending...",
    sendResetLink: "Send reset link",
    invalidResetLink: "The reset link is invalid",
    passwordMin6: "Password must be at least 6 characters",
    passwordMismatch: "The passwords do not match",
    passwordChanged: "Password changed",
    resetFailed: "Could not reset the password",
    setNewPassword: "Set a new password",
    linkInvalidTryAgain: 'This link is invalid. Please try again from "Forgot password".',
    passwordChangedLogin: "Your password has been changed. Please log in now.",
    loginNow: "Log in",
    newPassword: "New password",
    retypePassword: "Retype password",
    changePassword: "Change password",
    removeFromSaved: "Remove from saved list",
    removeSavedTitle: "Remove saved login?",
    removeSavedBody: (label) =>
      `(${label}) will be removed from this device's saved logins. Next time you will need to enter the {{institution}} code and email again.`,
    remove: "Remove",
  },
});
