import { defineBilingualText } from "@madrasha/shared-ui/src/i18n";

/** Create / edit institution form (create-madrasa/* sections). */
export const createMadrasaText = defineBilingualText({
  bn: {
    // Basic info
    basicInfo: "মৌলিক তথ্য",
    institutionNameRequired: "প্রতিষ্ঠানের নাম *",
    slugOptional: "স্লাগ (ঐচ্ছিক)",
    addressOptional: "ঠিকানা (ঐচ্ছিক)",
    contactNumber: "মোবাইল / যোগাযোগ নম্বর",

    // Institution type + default language
    typeAndLanguage: "প্রতিষ্ঠানের ধরন ও ভাষা",
    institutionType: "প্রতিষ্ঠানের ধরন",
    defaultLanguage: "ডিফল্ট ভাষা",
    typeDefault: (lang: string) => `ধরন অনুযায়ী ডিফল্ট (${lang})`,
    typeHint: "ধরন অনুযায়ী শুধু সেই ধরনের বিভাগ/শ্রেণি/কিতাব ক্যাটালগ দেখানো হবে।",
    languageHint: "প্রিন্ট/রিপোর্ট এই ভাষায় হবে; ইউজাররা চাইলে নিজের ভাষা বদলাতে পারবেন।",
    noDivisionsForType: "এই ধরনের জন্য ক্যাটালগে কোনো বিভাগ নেই — ক্যাটালগ পেজ থেকে যোগ করুন।",

    // Plan
    planAndLimits: "প্ল্যান ও লিমিট",
    plan: "প্ল্যান",
    studentLimit: "শিক্ষার্থী লিমিট",
    userLimit: "ইউজার লিমিট",
    planStartDate: "প্ল্যান শুরুর তারিখ",
    durationDays: "মেয়াদ (দিন)",
    startDateHint: "এই প্রতিষ্ঠান আগে থেকেই সাবস্ক্রিপশন ব্যবহার করে থাকলে প্রকৃত শুরুর তারিখ দিন, নাহলে আজকের তারিখ থাকবে।",
    regBlockTitle: "রেজি. নম্বর ব্লক (প্ল্যান অনুযায়ী)",
    regBlockHint:
      "তৈরির সময় প্রতিটি শ্রেণি নিচের সাইজের ব্লক পাবে, পরপর সাজানো। পরে প্রতিষ্ঠানের অ্যাডমিন কম-বেশি করতে পারবেন।",
    colDivision: "বিভাগ",
    colPerClass: "প্রতি শ্রেণি",
    colClasses: "শ্রেণি",
    colNumbers: "নম্বর",
    classCount: (n: string) => `${n}টি`,
    noAutoBlock: "অটো ব্লক নেই",

    // Catalog toggles
    divisions: "বিভাগসমূহ",
    modules: "মডিউলসমূহ",
    classes: "শ্রেণিসমূহ",
    books: "কিতাব / বিষয়সমূহ",
    totalClasses: (n: string) => `মোট শ্রেণি: ${n}`,
    unknown: "অজানা",

    // Default users
    defaultUserTitle: "ডিফল্ট ইউজার (প্রতিষ্ঠান প্রধান)",
    roleHead: "প্রতিষ্ঠান প্রধান",
    roleTalimat: "তালিমাত",
    roleAccountant: "অ্যাকাউন্টেন্ট",
    required: "আবশ্যক",
    name: "নাম",
    email: "ইমেইল",
    password: "পাসওয়ার্ড",
    showPassword: "পাসওয়ার্ড দেখান",
    hidePassword: "পাসওয়ার্ড লুকান",

    // Validation
    errInstitutionName: "প্রতিষ্ঠানের নাম দিন",
    errName: "নাম দিন",
    errEmail: "ইমেইল দিন",
    errPassword: "পাসওয়ার্ড দিন",
    errPasswordMin: "পাসওয়ার্ড কমপক্ষে ৬ অক্ষরের হতে হবে",

    creating: "তৈরি হচ্ছে...",

    // Institution users (edit)
    users: "ইউজার",
    loadingUsers: "ইউজার লোড হচ্ছে...",
    noRoles: "এই প্রতিষ্ঠানের কোনো রোল পাওয়া যায়নি।",
    defaultUserLocked: "ডিফল্ট ইউজার — মুছে ফেলা যাবে না",
    changeCredentials: "ইমেইল/পাসওয়ার্ড পরিবর্তন",
    newPasswordPlaceholder: "নতুন পাসওয়ার্ড (খালি রাখলে অপরিবর্তিত থাকবে)",
    adding: "যোগ হচ্ছে...",
    addRole: (role: string) => `+ ${role} যোগ করুন`,
    enterUserName: "ইউজারের নাম দিন",
    credentialsUpdated: "ক্রেডেনশিয়াল আপডেট হয়েছে",
    updateFailed: "আপডেট করা যায়নি",
    roleAdded: (role: string) => `${role} যোগ করা হয়েছে`,
    addUserFailed: "ইউজার যোগ করা যায়নি",
    deleteUserTitle: "ইউজার মুছুন",
    deleteUserMessage: (name: string, email: string) => `"${name}" (${email}) কে মুছে ফেলতে চান?`,
    userDeleted: "ইউজার মুছে ফেলা হয়েছে",
  },
  en: {
    basicInfo: "Basic Information",
    institutionNameRequired: "Institution Name *",
    slugOptional: "Slug (optional)",
    addressOptional: "Address (optional)",
    contactNumber: "Mobile / Contact Number",

    typeAndLanguage: "Institution Type & Language",
    institutionType: "Institution type",
    defaultLanguage: "Default language",
    typeDefault: (lang) => `Type default (${lang})`,
    typeHint: "Only the division/class/book catalogue of this type is offered.",
    languageHint: "Prints/reports use this language; users can still switch their own UI language.",
    noDivisionsForType: "No catalogue divisions exist for this type yet — add them on the Catalog page.",

    planAndLimits: "Plan & Limits",
    plan: "Plan",
    studentLimit: "Student Limit",
    userLimit: "User Limit",
    planStartDate: "Plan Start Date",
    durationDays: "Duration (Days)",
    startDateHint: "If this institution already had a subscription, enter the real start date; otherwise today is used.",
    regBlockTitle: "Registration No. Blocks (per plan)",
    regBlockHint:
      "On creation each class gets a block of the size below, laid out back to back. The institution admin can adjust them later.",
    colDivision: "Division",
    colPerClass: "Per class",
    colClasses: "Classes",
    colNumbers: "Numbers",
    classCount: (n) => `${n}`,
    noAutoBlock: "No auto block",

    divisions: "Divisions",
    modules: "Modules",
    classes: "Classes",
    books: "Books / Subjects",
    totalClasses: (n) => `Total Classes: ${n}`,
    unknown: "Unknown",

    defaultUserTitle: "Default User (Institution Head)",
    roleHead: "Institution Head",
    roleTalimat: "Talimat",
    roleAccountant: "Accountant",
    required: "Required",
    name: "Name",
    email: "Email",
    password: "Password",
    showPassword: "Show password",
    hidePassword: "Hide password",

    errInstitutionName: "Institution name required",
    errName: "Name required",
    errEmail: "Email required",
    errPassword: "Password required",
    errPasswordMin: "Password must be at least 6 characters",

    creating: "Creating...",

    users: "Users",
    loadingUsers: "Loading users...",
    noRoles: "No roles found for this institution.",
    defaultUserLocked: "Default user — cannot be deleted",
    changeCredentials: "Change email/password",
    newPasswordPlaceholder: "New password (leave blank to keep unchanged)",
    adding: "Adding...",
    addRole: (role) => `+ Add ${role}`,
    enterUserName: "Enter the user's name",
    credentialsUpdated: "Credentials updated",
    updateFailed: "Could not update",
    roleAdded: (role) => `${role} added`,
    addUserFailed: "Could not add user",
    deleteUserTitle: "Delete User",
    deleteUserMessage: (name, email) => `Delete "${name}" (${email})?`,
    userDeleted: "User deleted",
  },
});
