import { defineText } from "@madrasha/shared-ui/src/i18n";

type Entry = { title: string; subtitle: string };

/** Report pages: page headings, report picker titles/subtitles (also the
 * printed title of generic table reports) and the ReportShell chrome. */
export const reportsText = defineText({
  bn: {
    page: {
      studentTitle: "স্টুডেন্ট রিপোর্ট",
      studentSubtitle: "ভর্তি তালিকা ও অভিভাবক মোবাইল নাম্বার তালিকা database থেকে নিয়ে professional ভাবে দেখুন ও প্রিন্ট করুন।",
      teacherTitle: "{{teacher}} রিপোর্ট",
      teacherSubtitle: "{{teacher}} তালিকা ও মোবাইল নাম্বার database থেকে নিয়ে দ্রুত export/print করার সুবিধা।",
      examTitle: "পরীক্ষা রিপোর্ট",
      examSubtitle: "পরীক্ষা নির্বাচন করে স্বাক্ষরপত্র ও {{subject}}ভিত্তিক নম্বরপত্র দেখুন এবং প্রিন্ট করুন।",
    },
    r: {
      "student-admissions": { title: "ভর্তি তালিকা", subtitle: "ভর্তিকৃত শিক্ষার্থীর পূর্ণ তালিকা" },
      "student-guardian-phones": { title: "অভিভাবক মোবাইল নাম্বার", subtitle: "অভিভাবকদের যোগাযোগ তালিকা" },
      "teacher-list": { title: "{{teacher}} লিস্ট", subtitle: "সকল {{teacher}}ের পূর্ণ তালিকা" },
      "teacher-phones": { title: "{{teacher}}দের মোবাইল নাম্বার", subtitle: "{{teacher}} ও অভিভাবক/জরুরি যোগাযোগ নাম্বার" },
      "academic-results": { title: "ফলাফল", subtitle: "শিক্ষার্থীদের ফলাফল, গ্রেড, মেধাক্রম — রোল নম্বর অনুযায়ী সাজানো" },
      "academic-results-by-rank": { title: "ফলাফল (মেধাক্রম অনুযায়ী)", subtitle: "শিক্ষার্থীদের ফলাফল, গ্রেড — মেধাক্রম (১ম, ২য়, ৩য় ...) অনুযায়ী সাজানো" },
      "academic-results-pass-list": { title: "পাশ তালিকা", subtitle: "যেসব শিক্ষার্থী কৃতকার্য (পাশ) হয়েছে তাদের তালিকা" },
      "academic-results-fail-list": { title: "ফেল তালিকা", subtitle: "যেসব শিক্ষার্থী অকৃতকার্য (ফেল) হয়েছে তাদের তালিকা" },
      "academic-subject-performance": { title: "{{subject}}ভিত্তিক ফলাফল বিশ্লেষণ", subtitle: "প্রতিটি {{subject}}ে গড়, সর্বোচ্চ ও সর্বনিম্ন নম্বর — {{subject}}ভিত্তিক পারফরম্যান্স" },
      "academic-exam-summary": { title: "পরীক্ষার সারসংক্ষেপ", subtitle: "প্রতিটি {{class}}র পরীক্ষার্থী সংখ্যা, পাশের হার, গড় নম্বর ও সর্বোচ্চ ফলাফলকারী" },
      "academic-result-notice": { title: "ফলাফল সারসংক্ষেপ", subtitle: "প্রকাশিত ফলাফলের প্রিন্টযোগ্য নোটিশ" },
      "academic-routines": { title: "রুটিন", subtitle: "ক্লাস রুটিন, {{subject}}, {{teacher}}, সময়" },
      "residential-attendance": { title: "আবাসিক হাজিরা খাতা", subtitle: "শুধু শিক্ষার্থীর নাম দিয়ে A4 হাজিরা খাতা প্রিন্ট" },
      "daily-attendance": { title: "দৈনন্দিন হাজিরা খাতা", subtitle: "প্রতিদিনের উপস্থিতি তালিকা প্রিন্ট" },
      "digital-attendance": { title: "ডিজিটাল হাজিরা খাতা", subtitle: "ইন টাইম, আউট টাইম ও স্ট্যাটাসসহ ডিজিটাল হাজিরা রিপোর্ট" },
      "exam-signature-sheet": { title: "স্বাক্ষরপত্র", subtitle: "পরীক্ষার্থীদের স্বাক্ষর গ্রহণের জন্য প্রিন্টযোগ্য পত্র" },
      "exam-number-sheet": { title: "নম্বরপত্র", subtitle: "{{subject}}ভিত্তিক নম্বরসহ প্রিন্টযোগ্য পরীক্ষার নম্বরপত্র" },
      "exam-signature-number-sheet": { title: "স্বাক্ষর ও নম্বরপত্র", subtitle: "{{subject}}ভিত্তিক আলাদা পত্র — স্বাক্ষর ও হাতে-নম্বর তোলার জন্য" },
      "exam-signature-number-sheet-2col": { title: "স্বাক্ষর ও নম্বরপত্র (২ কলাম)", subtitle: "এক পাতায় ২ কলামে ২টি {{class}}র স্বাক্ষর ও নম্বর তোলার পত্র — কাগজ সাশ্রয়ী" },
      "exam-routine": { title: "পরীক্ষার রুটিন", subtitle: "তারিখ ও সময় অনুযায়ী সাজানো প্রিন্টযোগ্য পরীক্ষার সময়সূচি" },
      "exam-routine-by-room": { title: "রুম ভিত্তিক পরীক্ষার রুটিন", subtitle: "রুম নম্বর অনুযায়ী সাজানো প্রিন্টযোগ্য পরীক্ষার সময়সূচি" },
      "seat-plan": { title: "সিট প্ল্যান", subtitle: "কক্ষ ও আসন নম্বর অনুযায়ী পরীক্ষার্থীদের আসন বিন্যাস" },
      "invigilator-list": { title: "পরিদর্শক তালিকা", subtitle: "কক্ষ ও সময়সূচি অনুযায়ী নিয়োজিত পরিদর্শকদের তালিকা" },
      "exam-attendance-sheet": { title: "পরীক্ষার হাজিরা শিট", subtitle: "কক্ষভিত্তিক পরীক্ষার দিনের উপস্থিতি/অনুপস্থিতি তালিকা" },
      "exam-candidates": { title: "পরীক্ষার্থী তালিকা", subtitle: "এই পরীক্ষায় অংশগ্রহণকারী শিক্ষার্থীদের তালিকা" },
      "exam-absentees": { title: "অনুপস্থিত পরীক্ষার্থী তালিকা", subtitle: "যেসব শিক্ষার্থী কোনো {{subject}}ে পরীক্ষায় অনুপস্থিত ছিল তাদের তালিকা" },
      "student-marksheets": { title: "মার্কশিট", subtitle: "শিক্ষার্থীর ফলাফল ও মার্কশিট রিপোর্ট" },
      "student-id-cards": { title: "আইডি কার্ড", subtitle: "শিক্ষার্থীদের আইডি কার্ড রিপোর্ট ও প্রিন্ট" },
      "student-id-card-backs": { title: "আইডি কার্ড ব্যাক", subtitle: "আইডি কার্ডের পিছনের পাতা (ইস্যু/মেয়াদ, {{head}}-এর স্বাক্ষর, ফেরতের ঠিকানা) আলাদা প্রিন্ট" },
      "student-admit-cards": { title: "প্রবেশপত্র", subtitle: "শিক্ষার্থীদের পরীক্ষার প্রবেশপত্র তৈরি ও প্রিন্ট" },
      "student-admit-cards-with-rules": { title: "পরীক্ষার নিয়মাবলী", subtitle: "প্রবেশপত্রের সাথে দেওয়ার জন্য পরীক্ষার নিয়মাবলীর একটি মাত্র নোটিশ পৃষ্ঠা তৈরি ও প্রিন্ট" },
      "notice-board": { title: "নোটিশ বোর্ড", subtitle: "দেয়ালে টানানোর নোটিশ লিখুন, সেভ রাখুন ও যেকোনোটি প্রিন্ট করুন" },
      "student-sanads": { title: "সনদ / সার্টিফিকেট", subtitle: "শিক্ষার্থীদের শিক্ষাগত সনদ তৈরি ও প্রিন্ট" },
      "student-certificates": { title: "সার্টিফিকেট", subtitle: "শিক্ষার্থীদের শিক্ষাগত সার্টিফিকেট তৈরি ও প্রিন্ট" },
      "student-testimonials": { title: "প্রত্যয়ন পত্র", subtitle: "শিক্ষার্থীদের প্রত্যয়ন পত্র তৈরি ও প্রিন্ট" },
      "student-transfer-letters": { title: "ছাড়পত্র", subtitle: "শিক্ষার্থীদের ছাড়পত্র তৈরি ও প্রিন্ট" },
      "prize-book-labels-rank": { title: "পুরস্কার বই-লেবেল (মেধাক্রম ১-৩)", subtitle: "নির্বাচিত পরীক্ষায় ১ম, ২য়, ৩য় স্থান অধিকারীদের জন্য বইয়ের প্রচ্ছদ-লেবেল" },
      "prize-book-labels-mumtaz": { title: "পুরস্কার বই-লেবেল (১-৩ + মুমতাজ)", subtitle: "নির্বাচিত পরীক্ষায় মেধাক্রম ১ম-৩য় এবং মুমতাজ গ্রেডপ্রাপ্তদের জন্য বইয়ের প্রচ্ছদ-লেবেল" },
    } as Record<string, Entry>,
    shell: {
      selectExam: "পরীক্ষা নির্বাচন করুন",
      selectDivision: "{{division}} নির্বাচন করুন",
      selectClass: "{{class}} নির্বাচন করুন",
      loadFailed: "রিপোর্ট লোড করা যায়নি",
      emptyPickExam: "রিপোর্ট দেখতে উপর থেকে পরীক্ষা নির্বাচন করুন",
      emptyPickDivision: "রিপোর্ট দেখতে {{division}} ও {{class}} নির্বাচন করুন",
      emptyPickClass: "রিপোর্ট দেখতে {{class}} নির্বাচন করুন",
      onlyLabel: "শুধু:",
      selectedStudent: "নির্বাচিত শিক্ষার্থী",
      showAll: "সবাই দেখুন",
      totalRecords: (n: string) => `মোট ${n} টি রেকর্ড`,
      repeatHeaderHint: "চালু থাকলে {{subject}}ের নামসহ হেডার প্রতিটি পেজের উপরে ছাপা হবে",
      repeatHeader: "প্রতি পেজে {{subject}}ের নাম",
      signatureHint: "জায়গা কম হলে বন্ধ করুন - প্রতিটি {{class}}র নিচের পরীক্ষা নিয়ন্ত্রকের স্বাক্ষর বাদ যাবে",
      signatureToggle: "নিচে স্বাক্ষর",
      resetColumns: "ডিফল্ট কলাম ফিরিয়ে আনুন",
      perPage: (n: string) => `${n} জন/পেজ`,
      prev: "আগের",
      next: "পরের",
      addExamRoutine: "পরীক্ষার রুটিন যোগ করুন →",
    },
  },
  en: {
    page: {
      studentTitle: "Student Reports",
      studentSubtitle: "View and print the admission list and guardian mobile numbers straight from the database.",
      teacherTitle: "{{teacher}} Reports",
      teacherSubtitle: "Quickly export/print the {{teacher}} list and mobile numbers from the database.",
      examTitle: "Exam Reports",
      examSubtitle: "Select an exam to view and print signature sheets and {{subject}}-wise mark sheets.",
    },
    r: {
      "student-admissions": { title: "Admission List", subtitle: "Complete list of admitted students" },
      "student-guardian-phones": { title: "Guardian Mobile Numbers", subtitle: "Guardian contact list" },
      "teacher-list": { title: "{{teacher}} List", subtitle: "Complete list of all {{teacher}}s" },
      "teacher-phones": { title: "{{teacher}} Mobile Numbers", subtitle: "{{teacher}} and guardian/emergency contact numbers" },
      "academic-results": { title: "Results", subtitle: "Student results, grades and merit positions — sorted by roll number" },
      "academic-results-by-rank": { title: "Results (by Merit)", subtitle: "Student results and grades — sorted by merit position (1st, 2nd, 3rd ...)" },
      "academic-results-pass-list": { title: "Pass List", subtitle: "List of students who passed" },
      "academic-results-fail-list": { title: "Fail List", subtitle: "List of students who failed" },
      "academic-subject-performance": { title: "{{subject}}-wise Result Analysis", subtitle: "Average, highest and lowest marks in each {{subject}}" },
      "academic-exam-summary": { title: "Exam Summary", subtitle: "Examinees, pass rate, average marks and top scorer of each {{class}}" },
      "academic-result-notice": { title: "Result Summary", subtitle: "Printable notice of published results" },
      "academic-routines": { title: "Routine", subtitle: "Class routine, {{subject}}, {{teacher}}, time" },
      "residential-attendance": { title: "Residential Attendance Register", subtitle: "A4 attendance register with student names only" },
      "daily-attendance": { title: "Daily Attendance Register", subtitle: "Print the daily attendance list" },
      "digital-attendance": { title: "Digital Attendance Register", subtitle: "Digital attendance report with in time, out time and status" },
      "exam-signature-sheet": { title: "Signature Sheet", subtitle: "Printable sheet for collecting examinee signatures" },
      "exam-number-sheet": { title: "Mark Sheet", subtitle: "Printable exam mark sheet with {{subject}}-wise marks" },
      "exam-signature-number-sheet": { title: "Signature & Mark Sheet", subtitle: "A separate sheet per {{subject}} — for signatures and hand-written marks" },
      "exam-signature-number-sheet-2col": { title: "Signature & Mark Sheet (2 columns)", subtitle: "Two {{class}}es per page in 2 columns — saves paper" },
      "exam-routine": { title: "Exam Routine", subtitle: "Printable exam schedule sorted by date and time" },
      "exam-routine-by-room": { title: "Room-wise Exam Routine", subtitle: "Printable exam schedule sorted by room number" },
      "seat-plan": { title: "Seat Plan", subtitle: "Examinee seating arranged by room and seat number" },
      "invigilator-list": { title: "Invigilator List", subtitle: "Invigilators assigned by room and schedule" },
      "exam-attendance-sheet": { title: "Exam Attendance Sheet", subtitle: "Room-wise attendance/absence on exam days" },
      "exam-candidates": { title: "Examinee List", subtitle: "Students taking part in this exam" },
      "exam-absentees": { title: "Absent Examinee List", subtitle: "Students absent in any {{subject}} of the exam" },
      "student-marksheets": { title: "Marksheet", subtitle: "Student result and marksheet report" },
      "student-id-cards": { title: "ID Card", subtitle: "Student ID card report and print" },
      "student-id-card-backs": { title: "ID Card Back", subtitle: "Print the ID card back side (issue/expiry, {{head}}'s signature, return address) separately" },
      "student-admit-cards": { title: "Admit Card", subtitle: "Create and print student exam admit cards" },
      "student-admit-cards-with-rules": { title: "Examination Rules", subtitle: "A single notice page of exam rules to hand out with admit cards" },
      "notice-board": { title: "Notice Board", subtitle: "Write wall notices, save them and print any of them" },
      "student-sanads": { title: "Sanad / Certificate", subtitle: "Create and print students' academic sanads" },
      "student-certificates": { title: "Certificate", subtitle: "Create and print students' academic certificates" },
      "student-testimonials": { title: "Testimonial", subtitle: "Create and print student testimonials" },
      "student-transfer-letters": { title: "Transfer Certificate", subtitle: "Create and print student transfer certificates" },
      "prize-book-labels-rank": { title: "Prize Book Labels (Merit 1-3)", subtitle: "Book cover labels for 1st, 2nd and 3rd place holders of the selected exam" },
      "prize-book-labels-mumtaz": { title: "Prize Book Labels (1-3 + Mumtaz)", subtitle: "Book cover labels for merit 1st-3rd and Mumtaz grade holders of the selected exam" },
    },
    shell: {
      selectExam: "Select an exam",
      selectDivision: "Select a {{division}}",
      selectClass: "Select a {{class}}",
      loadFailed: "Could not load the report",
      emptyPickExam: "Select an exam above to view the report",
      emptyPickDivision: "Select a {{division}} and {{class}} to view the report",
      emptyPickClass: "Select a {{class}} to view the report",
      onlyLabel: "Only:",
      selectedStudent: "Selected student",
      showAll: "Show all",
      totalRecords: (n) => `Total ${n} records`,
      repeatHeaderHint: "When on, the header with {{subject}} names is printed at the top of every page",
      repeatHeader: "{{subject}} names on every page",
      signatureHint: "Turn off when space is short - drops the exam controller's signature below each {{class}}",
      signatureToggle: "Signature at bottom",
      resetColumns: "Restore default columns",
      perPage: (n) => `${n} / page`,
      prev: "Prev",
      next: "Next",
      addExamRoutine: "Add exam routine →",
    },
  },
});

export type ReportsText = typeof reportsText.bn;
