import { defineText } from "@madrasha/shared-ui/src/i18n";

/** Shared by the people tools (ছবি আপলোড, নাম (৩ ভাষা)) under photo-manager/. */
export const peopleToolsText = defineText({
  bn: {
    tabs: { students: "{{student}}", teachers: "{{teacher}}", staff: "স্টাফ" },
    allOf: (label: string) => `সব ${label}`,
    unnamed: "নামহীন",
    listLoadFailed: "তালিকা লোড করা যায়নি",

    // names
    owners: { self: "নিজের নাম", father: "পিতা", mother: "মাতা" },
    ownerName: { self: "নিজের নাম", father: "পিতার নাম", mother: "মাতার নাম" },
    langs: { bn: "বাংলা নাম", ar: "আরবি নাম", en: "English নাম" },

    // toolbar
    total: "মোট",
    remaining: "বাকি",
    searchStudents: "নাম, রোল বা রেজি. নং",
    searchOthers: "নাম বা রেজি. নং",
    clearSearch: "সার্চ মুছুন",
    allDivisions: "সব {{division}}",
    allClasses: "সব {{class}}",
    refresh: "রিফ্রেশ",

    // photo card
    clickToUpload: "ছবি আপলোড করতে ক্লিক করুন",
    noPhoto: "ছবি নেই",
    changePhoto: "ছবি বদলান",
    addPhoto: "ছবি দিন",
    saving: "সংরক্ষণ হচ্ছে...",
    saved: "সংরক্ষিত",
    failed: "ব্যর্থ",
    roll: (n: string) => `রোল ${n}`,
    reg: (n: string) => `রেজি. ${n}`,
    uploadFromFile: "ফাইল থেকে আপলোড",
    upload: "আপলোড",
    takeWithCamera: "ক্যামেরা দিয়ে তুলুন",
    camera: "ক্যামেরা",
    removePhoto: "ছবি মুছুন",

    // bulk photo upload
    bulkTitle: "একসাথে অনেক ছবি আপলোড",
    fileNameRule: (by: string, scope: string) => `ফাইলের নাম = ${by} (যেমন 1045.jpg) · পরিসর: ${scope}`,
    registrationNo: "রেজিস্ট্রেশন নম্বর",
    rollNo: "রোল নম্বর",
    matchByReg: "রেজি. নং দিয়ে মেলান",
    matchByRoll: "রোল দিয়ে মেলান",
    matchedLabel: "মিলেছে",
    unmatchedLabel: "মেলেনি",
    rollNeedsClass: "রোল দিয়ে মেলাতে ওপরের ফিল্টার থেকে একটি {{class}} নির্বাচন করুন।",
    dropHere: "ছবিগুলো এখানে টেনে আনুন বা ক্লিক করে বাছাই করুন",
    dropHint: "একাধিক JPG/PNG · নামের প্রথম সংখ্যাটি দিয়ে মেলানো হবে",
    noNumber: "নামে কোনো সংখ্যা নেই",
    noneFound: "কাউকে পাওয়া যায়নি",
    multiMatched: (n: string) => `${n} জন মিলেছে — {{class}} নির্বাচন করুন`,
    duplicateFile: "একই জনের জন্য আগে আরেকটি ফাইল আছে",
    willReplace: "আগের ছবি প্রতিস্থাপন হবে",
    bulkDone: (saved: string, failed: string | null) =>
      `সম্পন্ন: ${saved} টি সংরক্ষিত${failed ? `, ${failed} টি ব্যর্থ` : ""}`,
    bulkRunning: (done: string, total: string) => `সংরক্ষণ হচ্ছে... ${done} / ${total}`,
    bulkSelected: (n: string) => `${n} টি ছবি সংরক্ষণের জন্য নির্বাচিত`,
    clearAll: "খালি করুন",
    done: "সম্পন্ন",
    saveN: (n: string) => `${n} টি সংরক্ষণ করুন`,

    // series capture
    seriesTitle: "ক্যামেরা সিরিজ মোড",
    savedCount: "সংরক্ষিত",
    running: (n: string) => ` · চলছে ${n}`,
    failedCount: (n: string) => ` · ব্যর্থ ${n}`,
    seriesFinished: "সিরিজ শেষ হয়েছে",
    seriesSaved: (n: string) => `${n} টি ছবি সংরক্ষিত`,
    seriesPending: (n: string) => `, ${n} টি সংরক্ষণ হচ্ছে`,
    seriesFailed: (n: string) => `, ${n} টি ব্যর্থ`,
    seriesSkipped: (n: string) => `, ${n} জন বাদ গেছে`,
    goBack: "পেছনে যান",
    nowCapturing: "এখন যার ছবি তুলবেন",
    nextLabel: "পরবর্তী:",
    rollSuffix: (n: string) => ` · রোল ${n}`,
    previousKey: "পূর্ববর্তী (←)",
    previous: "পূর্ববর্তী",
    skipKey: "এড়িয়ে যান (→)",
    skip: "এড়িয়ে যান",
    switchCamera: "ক্যামেরা বদলান",
    captureNext: "ছবি তুলুন ও পরবর্তী",
    keyboardHint: "কিবোর্ড: Space = ছবি তুলুন · → = এড়িয়ে যান · ← = পূর্ববর্তী",
    recent: "সাম্প্রতিক",
    retakeHint: (name: string) => `${name} - আবার তুলতে ক্লিক করুন`,
    noCameraSupport: "এই ব্রাউজারে ক্যামেরা সাপোর্ট নেই (HTTPS বা localhost প্রয়োজন)।",
    cameraDenied: "ক্যামেরা ব্যবহারের অনুমতি দেওয়া হয়নি। ব্রাউজারের ঠিকানা-বারের পাশ থেকে অনুমতি দিন।",
    noCamera: "কোনো ক্যামেরা পাওয়া যায়নি।",
    cameraFailed: "ক্যামেরা চালু করা যায়নি।",

    // names excel
    excelTitle: (tab: string, scope: string, n: string) =>
      `নাম (৩ ভাষা) — ${tab} · ${scope} · মোট ${n} জন। ` +
      "ধূসর কলাম (ID, রেজি., রোল, {{class}}) লক করা — শুধু নামের ঘরে লেখা যাবে। প্রতিটা নামের কলামে শুধু সেই ভাষায় লিখুন। " +
      "খালি ঘর রাখলে আগের নাম অপরিবর্তিত থাকবে।",
    colRegNo: "রেজি. নং",
    colRoll: "রোল",
    colClass: "{{class}}",
    colDesignation: "পদবি",
    noSheet: "Excel ফাইলে কোনো শিট নেই",
    wrongTab: (tab: string) => `এই ফাইলটি ${tab} ট্যাবের — ${tab} ট্যাবে গিয়ে আপলোড করুন`,
    wrongFormat: "ফরম্যাট মেলেনি — এই পেজ থেকে ডাউনলোড করা ফরম্যাট ব্যবহার করুন",
  },
  en: {
    tabs: { students: "{{student}}s", teachers: "{{teacher}}s", staff: "Staff" },
    allOf: (label) => `All ${label}`,
    unnamed: "Unnamed",
    listLoadFailed: "Could not load the list",

    owners: { self: "Own name", father: "Father", mother: "Mother" },
    ownerName: { self: "Own name", father: "Father's name", mother: "Mother's name" },
    langs: { bn: "Bangla name", ar: "Arabic name", en: "English name" },

    total: "Total",
    remaining: "Remaining",
    searchStudents: "Name, roll or reg. no.",
    searchOthers: "Name or reg. no.",
    clearSearch: "Clear search",
    allDivisions: "All {{division}}s",
    allClasses: "All {{class}}es",
    refresh: "Refresh",

    clickToUpload: "Click to upload a photo",
    noPhoto: "No photo",
    changePhoto: "Change photo",
    addPhoto: "Add photo",
    saving: "Saving...",
    saved: "Saved",
    failed: "Failed",
    roll: (n) => `Roll ${n}`,
    reg: (n) => `Reg. ${n}`,
    uploadFromFile: "Upload from file",
    upload: "Upload",
    takeWithCamera: "Take with camera",
    camera: "Camera",
    removePhoto: "Remove photo",

    bulkTitle: "Bulk Photo Upload",
    fileNameRule: (by, scope) => `File name = ${by} (e.g. 1045.jpg) · Scope: ${scope}`,
    registrationNo: "registration no.",
    rollNo: "roll no.",
    matchByReg: "Match by reg. no.",
    matchByRoll: "Match by roll",
    matchedLabel: "matched",
    unmatchedLabel: "unmatched",
    rollNeedsClass: "Select a {{class}} in the filter above to match by roll.",
    dropHere: "Drag photos here or click to choose",
    dropHint: "Multiple JPG/PNG · matched by the first number in the file name",
    noNumber: "No number in the file name",
    noneFound: "No one found",
    multiMatched: (n) => `${n} people matched — select a {{class}}`,
    duplicateFile: "Another file already targets the same person",
    willReplace: "Existing photo will be replaced",
    bulkDone: (saved, failed) => `Done: ${saved} saved${failed ? `, ${failed} failed` : ""}`,
    bulkRunning: (done, total) => `Saving... ${done} / ${total}`,
    bulkSelected: (n) => `${n} photo(s) selected to save`,
    clearAll: "Clear",
    done: "Done",
    saveN: (n) => `Save ${n}`,

    seriesTitle: "Camera Series Mode",
    savedCount: "saved",
    running: (n) => ` · in progress ${n}`,
    failedCount: (n) => ` · failed ${n}`,
    seriesFinished: "Series complete",
    seriesSaved: (n) => `${n} photo(s) saved`,
    seriesPending: (n) => `, ${n} saving`,
    seriesFailed: (n) => `, ${n} failed`,
    seriesSkipped: (n) => `, ${n} skipped`,
    goBack: "Go back",
    nowCapturing: "Now photographing",
    nextLabel: "Next:",
    rollSuffix: (n) => ` · Roll ${n}`,
    previousKey: "Previous (←)",
    previous: "Previous",
    skipKey: "Skip (→)",
    skip: "Skip",
    switchCamera: "Switch camera",
    captureNext: "Capture & Next",
    keyboardHint: "Keyboard: Space = capture · → = skip · ← = previous",
    recent: "Recent",
    retakeHint: (name) => `${name} - click to retake`,
    noCameraSupport: "This browser doesn't support the camera (HTTPS or localhost required).",
    cameraDenied: "Camera permission was denied. Allow it from beside the browser's address bar.",
    noCamera: "No camera found.",
    cameraFailed: "Could not start the camera.",

    excelTitle: (tab, scope, n) =>
      `Names (3 languages) — ${tab} · ${scope} · Total ${n}. ` +
      "Grey columns (ID, Reg., Roll, {{class}}) are locked — only name cells can be edited. Write each name column only in its language. " +
      "Blank cells leave the existing name unchanged.",
    colRegNo: "Reg. No.",
    colRoll: "Roll",
    colClass: "{{class}}",
    colDesignation: "Designation",
    noSheet: "The Excel file has no sheet",
    wrongTab: (tab) => `This file belongs to the ${tab} tab — upload it from the ${tab} tab`,
    wrongFormat: "Format not recognised — use the template downloaded from this page",
  },
  ar: {
    tabs: { students: "الطلاب", teachers: "الأساتذة", staff: "الموظفون" },
    allOf: (label) => `جميع ${label}`,
    unnamed: "بلا اسم",
    listLoadFailed: "تعذّر تحميل القائمة",

    owners: { self: "الاسم الشخصي", father: "الأب", mother: "الأم" },
    ownerName: { self: "الاسم الشخصي", father: "اسم الأب", mother: "اسم الأم" },
    langs: { bn: "الاسم بالبنغالية", ar: "الاسم بالعربية", en: "الاسم بالإنجليزية" },

    total: "الإجمالي",
    remaining: "المتبقي",
    searchStudents: "الاسم أو رقم الجلوس أو رقم التسجيل",
    searchOthers: "الاسم أو رقم التسجيل",
    clearSearch: "مسح البحث",
    allDivisions: "جميع المراحل",
    allClasses: "جميع الصفوف",
    refresh: "تحديث",

    clickToUpload: "انقر لرفع صورة",
    noPhoto: "لا توجد صورة",
    changePhoto: "تغيير الصورة",
    addPhoto: "إضافة صورة",
    saving: "جارٍ الحفظ...",
    saved: "تم الحفظ",
    failed: "فشل",
    roll: (n) => `الجلوس ${n}`,
    reg: (n) => `التسجيل ${n}`,
    uploadFromFile: "رفع من ملف",
    upload: "رفع",
    takeWithCamera: "التقاط بالكاميرا",
    camera: "الكاميرا",
    removePhoto: "حذف الصورة",

    bulkTitle: "رفع صور متعددة دفعة واحدة",
    fileNameRule: (by, scope) => `اسم الملف = ${by} (مثال 1045.jpg) · النطاق: ${scope}`,
    registrationNo: "رقم التسجيل",
    rollNo: "رقم الجلوس",
    matchByReg: "المطابقة برقم التسجيل",
    matchByRoll: "المطابقة برقم الجلوس",
    matchedLabel: "مطابق",
    unmatchedLabel: "غير مطابق",
    rollNeedsClass: "للمطابقة برقم الجلوس اختر صفًا من التصفية أعلاه.",
    dropHere: "اسحب الصور إلى هنا أو انقر للاختيار",
    dropHint: "عدة ملفات JPG/PNG · تتم المطابقة بأول رقم في اسم الملف",
    noNumber: "لا يوجد رقم في اسم الملف",
    noneFound: "لم يتم العثور على أحد",
    multiMatched: (n) => `تطابق ${n} أشخاص — اختر صفًا`,
    duplicateFile: "يوجد ملف آخر سابق للشخص نفسه",
    willReplace: "سيتم استبدال الصورة السابقة",
    bulkDone: (saved, failed) => `اكتمل: حُفظت ${saved}${failed ? `، وفشلت ${failed}` : ""}`,
    bulkRunning: (done, total) => `جارٍ الحفظ... ${done} / ${total}`,
    bulkSelected: (n) => `${n} صورة محددة للحفظ`,
    clearAll: "إفراغ",
    done: "تم",
    saveN: (n) => `حفظ ${n}`,

    seriesTitle: "وضع التصوير المتتابع",
    savedCount: "محفوظة",
    running: (n) => ` · قيد التنفيذ ${n}`,
    failedCount: (n) => ` · فاشلة ${n}`,
    seriesFinished: "انتهت السلسلة",
    seriesSaved: (n) => `حُفظت ${n} صورة`,
    seriesPending: (n) => `، ${n} قيد الحفظ`,
    seriesFailed: (n) => `، ${n} فاشلة`,
    seriesSkipped: (n) => `، تم تخطي ${n}`,
    goBack: "رجوع",
    nowCapturing: "الشخص المراد تصويره الآن",
    nextLabel: "التالي:",
    rollSuffix: (n) => ` · الجلوس ${n}`,
    previousKey: "السابق (←)",
    previous: "السابق",
    skipKey: "تخطٍّ (→)",
    skip: "تخطٍّ",
    switchCamera: "تبديل الكاميرا",
    captureNext: "التقاط والتالي",
    keyboardHint: "لوحة المفاتيح: Space = التقاط · → = تخطٍّ · ← = السابق",
    recent: "الأحدث",
    retakeHint: (name) => `${name} - انقر لإعادة الالتقاط`,
    noCameraSupport: "هذا المتصفح لا يدعم الكاميرا (يتطلب HTTPS أو localhost).",
    cameraDenied: "لم يتم منح إذن استخدام الكاميرا. اسمح به من بجانب شريط العنوان في المتصفح.",
    noCamera: "لم يتم العثور على كاميرا.",
    cameraFailed: "تعذّر تشغيل الكاميرا.",

    excelTitle: (tab, scope, n) =>
      `الأسماء (3 لغات) — ${tab} · ${scope} · الإجمالي ${n}. ` +
      "الأعمدة الرمادية (ID، التسجيل، الجلوس، {{class}}) مقفلة — يمكن الكتابة في خانات الأسماء فقط. اكتب كل عمود اسم بلغته فقط. " +
      "ترك الخانة فارغة يُبقي الاسم السابق دون تغيير.",
    colRegNo: "رقم التسجيل",
    colRoll: "الجلوس",
    colClass: "{{class}}",
    colDesignation: "المسمى الوظيفي",
    noSheet: "لا توجد ورقة في ملف Excel",
    wrongTab: (tab) => `هذا الملف خاص بتبويب ${tab} — ارفعه من تبويب ${tab}`,
    wrongFormat: "التنسيق غير مطابق — استخدم القالب المنزَّل من هذه الصفحة",
  },
});
