import { defineBilingualText } from "@madrasha/shared-ui/src/i18n";

/** Subscription plans page. */
export const plansText = defineBilingualText({
  bn: {
    title: "প্ল্যান",
    subtitle: "সুপার অ্যাডমিন এখান থেকে মূল্য/লিমিট ম্যানেজ করবেন।",
    tabPlans: "প্ল্যান",
    tabTrash: "ট্র্যাশ",
    newPlan: "+ নতুন প্ল্যান",
    editPlanTitle: (id: string) => `প্ল্যান এডিট — #${id}`,
    createPlanTitle: "নতুন প্ল্যান তৈরি",
    active: "সক্রিয়",
    inactive: "নিষ্ক্রিয়",
    notSet: "সেট করা নেই",
    loadFailed: "লোড করা যায়নি",
    trashLoadFailed: "ট্র্যাশ লোড করা যায়নি",
    errName: "প্ল্যানের নাম দিন",
    errStudentLimit: "শিক্ষার্থী লিমিট ০ বা তার বেশি হতে হবে",
    errUserLimit: "ইউজার লিমিট ০ বা তার বেশি হতে হবে",
    errDuration: "মেয়াদ (দিন) ১ বা তার বেশি হতে হবে",
    errPrice: "মূল্য ০ এর কম হতে পারবে না",
    errRegBlock: "রেজি. ব্লকের সাইজ 0 থেকে 100000 এর মধ্যে পূর্ণসংখ্যা দিন",
    updated: "প্ল্যান আপডেট হয়েছে",
    created: "প্ল্যান তৈরি হয়েছে",
    saveFailed: "সংরক্ষণ করা যায়নি",
    statusUpdated: "স্ট্যাটাস আপডেট হয়েছে",
    toggleFailed: "স্ট্যাটাস বদলানো যায়নি",
    movedToTrash: "প্ল্যান ট্র্যাশে পাঠানো হয়েছে",
    restored: "প্ল্যান ফিরিয়ে আনা হয়েছে",
    permanentlyDeleted: "প্ল্যান স্থায়ীভাবে মুছে ফেলা হয়েছে",
    actionFailed: "কাজটি সম্পন্ন করা যায়নি",
    confirmTrashTitle: "ট্র্যাশে পাঠাবেন?",
    confirmRestoreTitle: "প্ল্যান ফিরিয়ে আনবেন?",
    confirmPermanentTitle: "স্থায়ীভাবে মুছবেন?",
    confirmTrashMessage: (name: string) => `প্ল্যান "${name}" ট্র্যাশে যাবে (ফিরিয়ে আনা যাবে)।`,
    confirmRestoreMessage: (name: string) => `প্ল্যান "${name}" আবার সক্রিয় তালিকায় ফিরে আসবে।`,
    confirmPermanentMessage: (name: string) => `প্ল্যান "${name}" স্থায়ীভাবে মুছে যাবে (ফিরিয়ে আনা যাবে না)।`,
    moveToTrash: "ট্র্যাশে পাঠান",
    restore: "ফিরিয়ে আনুন",
    permanentDelete: "স্থায়ীভাবে মুছুন",
    permanent: "স্থায়ী",
    search: "খুঁজুন",
    searchPlaceholder: "প্ল্যানের নাম দিয়ে খুঁজুন...",
    status: "স্ট্যাটাস",
    all: "সব",
    refresh: "রিফ্রেশ",
    refreshTrash: "ট্র্যাশ রিফ্রেশ",
    total: "মোট",
    totalTrash: "ট্র্যাশে মোট",
    noPlans: "কোনো প্ল্যান পাওয়া যায়নি",
    noPlansHint: "নতুন প্ল্যান যোগ করতে “নতুন প্ল্যান” চাপুন",
    trashEmpty: "ট্র্যাশ খালি",
    trashEmptyHint: "কোনো প্ল্যান ট্র্যাশে নেই",
    duration: (days: string) => `মেয়াদ: ${days} দিন`,
    deleted: "মুছে ফেলা হয়েছে",
    students: "শিক্ষার্থী",
    users: "ইউজার",
    price: "মূল্য",
    regBlockPerClass: "রেজি. ব্লক (প্রতি শ্রেণি)",
    regBlockCol: "রেজি. ব্লক / শ্রেণি",
    days: "দিন",
    edit: "এডিট",
    toggle: "টগল",
    trash: "ট্র্যাশ",
    colName: "নাম",
    colActions: "অ্যাকশন",
    planName: "প্ল্যানের নাম",
    planNamePlaceholder: "যেমন: Basic / Standard",
    studentLimit: "শিক্ষার্থী লিমিট",
    userLimit: "ইউজার লিমিট",
    durationDays: "মেয়াদ (দিন)",
    priceTaka: "মূল্য (৳)",
    regBlockTitle: "রেজি. নম্বর ব্লক (প্রতি শ্রেণি)",
    regBlockHint:
      "নতুন প্রতিষ্ঠান তৈরির সময় প্রতিটি শ্রেণি এই সাইজের ব্লক পাবে (যেমন ৩০ হলে ১–৩০, ৩১–৬০…)। খালি বা 0 রাখলে ওই বিভাগে অটো ব্লক হবে না। পরে প্রতিষ্ঠানের অ্যাডমিন ব্লক কম-বেশি করতে পারবেন; এখানে বদলালে আগের প্রতিষ্ঠানের ব্লক বদলাবে না।",
  },
  en: {
    title: "Plans",
    subtitle: "The super admin manages pricing/limits here.",
    tabPlans: "Plans",
    tabTrash: "Trash",
    newPlan: "+ New Plan",
    editPlanTitle: (id) => `Edit Plan — #${id}`,
    createPlanTitle: "Create New Plan",
    active: "Active",
    inactive: "Inactive",
    notSet: "Not set",
    loadFailed: "Load failed",
    trashLoadFailed: "Trash load failed",
    errName: "Enter the plan name",
    errStudentLimit: "Student limit must be 0 or more",
    errUserLimit: "User limit must be 0 or more",
    errDuration: "Duration days must be 1 or more",
    errPrice: "Price can't be below 0",
    errRegBlock: "Registration block size must be a whole number from 0 to 100000",
    updated: "Plan updated",
    created: "Plan created",
    saveFailed: "Save failed",
    statusUpdated: "Status updated",
    toggleFailed: "Toggle failed",
    movedToTrash: "Plan moved to trash",
    restored: "Plan restored",
    permanentlyDeleted: "Plan permanently deleted",
    actionFailed: "Action failed",
    confirmTrashTitle: "Move to Trash?",
    confirmRestoreTitle: "Restore Plan?",
    confirmPermanentTitle: "Permanent Delete?",
    confirmTrashMessage: (name) => `Plan "${name}" will go to trash (can be restored).`,
    confirmRestoreMessage: (name) => `Plan "${name}" will return to the active list.`,
    confirmPermanentMessage: (name) => `Plan "${name}" will be permanently deleted (cannot be undone).`,
    moveToTrash: "Move to Trash",
    restore: "Restore",
    permanentDelete: "Permanent Delete",
    permanent: "Permanent",
    search: "Search",
    searchPlaceholder: "Search by plan name...",
    status: "Status",
    all: "All",
    refresh: "Refresh",
    refreshTrash: "Refresh Trash",
    total: "Total",
    totalTrash: "Total Trash",
    noPlans: "No plans found",
    noPlansHint: "Press “New Plan” to add one",
    trashEmpty: "Trash is empty",
    trashEmptyHint: "No plan in trash",
    duration: (days) => `Duration: ${days} days`,
    deleted: "Deleted",
    students: "Students",
    users: "Users",
    price: "Price",
    regBlockPerClass: "Reg. block (per class)",
    regBlockCol: "Reg. block / class",
    days: "Days",
    edit: "Edit",
    toggle: "Toggle",
    trash: "Trash",
    colName: "Name",
    colActions: "Actions",
    planName: "Plan Name",
    planNamePlaceholder: "e.g. Basic / Standard",
    studentLimit: "Student Limit",
    userLimit: "User Limit",
    durationDays: "Duration Days",
    priceTaka: "Price (৳)",
    regBlockTitle: "Registration No. Block (per class)",
    regBlockHint:
      "When a new institution is created each class gets a block of this size (e.g. 30 → 1–30, 31–60…). Blank or 0 = no auto block for that division. The institution admin can adjust blocks later; changing this doesn't affect existing institutions.",
  },
});
