import { defineText } from "@madrasha/shared-ui/src/i18n";

/** ডিভাইস সেটিংস page (late / absent / check-out rules, holidays, alerts). */
export const deviceSettingsText = defineText({
  bn: {
    title: "ডিভাইস সেটিংস",
    subtitle: "ডিভাইসের পাঞ্চ থেকে উপস্থিতি কীভাবে গণনা হবে — দেরি, অনুপস্থিত, চেক-আউট, ছুটি ও সতর্কতা।",
    save: "সেভ করুন",
    saving: "সেভ হচ্ছে...",
    saved: "সেটিংস সেভ হয়েছে",
    saveFailed: "সেভ করা যায়নি",
    unsaved: "পরিবর্তন সেভ করা হয়নি",
    discard: "বাতিল",
    loadFailed: "সেটিংস লোড করা যায়নি",
    retry: "আবার চেষ্টা করুন",
    tryAgainDot: "আবার চেষ্টা করুন।",
    minutes: "মিনিট",
    smsLink: "অটো নোটিফিকেশন",
    late: {
      title: "দেরি",
      hint: "শুরুর সময় + ছাড়ের মিনিট পার হওয়ার পর প্রথম পাঞ্চ করলে \"দেরি\" হিসেবে গণনা হবে।",
      studentStart: "{{student}}দের শুরুর সময়",
      teacherStart: "{{teacher}} ও স্টাফদের শুরুর সময়",
      grace: "ছাড় (মিনিট)",
      graceInvalid: "০ থেকে ১৮০ মিনিটের মধ্যে দিন",
    },
    absent: {
      title: "স্বয়ংক্রিয় অনুপস্থিত",
      hint: "এই সময়ের মধ্যে যারা পাঞ্চ করেনি (যাদের ডিভাইস আইডি আছে), তাদের স্বয়ংক্রিয়ভাবে অনুপস্থিত ধরা হবে। পরে পাঞ্চ করলে উপস্থিত/দেরি হয়ে যাবে। ছুটির দিনে চলে না।",
      cutoff: "অনুপস্থিত ধরার সময়",
      maxWait: "ডিভাইস সিঙ্কের জন্য সর্বোচ্চ অপেক্ষা (মিনিট)",
      maxWaitHelp: "ইন্টারনেট বন্ধ থাকলে বা ডিভাইসে পাঞ্চ জমে থাকলে অনুপস্থিত ধরা এই সময় পর্যন্ত পিছিয়ে যাবে, যাতে পাঞ্চ করা কেউ ভুলে অনুপস্থিত না হয়। ০ = অপেক্ষা নয়।",
      maxWaitInvalid: "০ থেকে ৪৮০ এর মধ্যে মিনিট দিন",
      smsHint: "অভিভাবককে অনুপস্থিতির SMS পাঠাতে চালু করুন:",
    },
    manualSms: {
      title: "হাতে নেওয়া হাজিরায় SMS",
      hint: "\"হাজিরা নিন\" পেজ থেকে আজকের হাজিরা দিলে বা বদলালে অভিভাবক ডিভাইসের মতোই উপস্থিত/অনুপস্থিত SMS পাবেন। একই দিনে একই SMS একবারই যাবে, ডিভাইসে পাঞ্চ করলেও আবার যাবে না। পুরনো তারিখের এডিটে SMS যায় না।",
      smsHint: "SMS-এর লেখা ও চালু/বন্ধ (উপস্থিত, অনুপস্থিত) এখান থেকে:",
    },
    checkout: {
      title: "চেক-আউট",
      hint: "এই সময়ের পর (এবং চেক-ইনের অন্তত ৩০ মিনিট পরে) আবার পাঞ্চ করলে তা চেক-আউট হিসেবে গণনা হবে।",
      after: "চেক-আউট শুরুর সময়",
      smsHint: "চেক-আউটের SMS পাঠাতে চালু করুন:",
    },
    weekly: {
      title: "সাপ্তাহিক ছুটি",
      hint: "এই দিনগুলোতে পাঞ্চ এলেও উপস্থিতি গণনা হবে না, অনুপস্থিতও ধরা হবে না।",
      days: ["রবি", "সোম", "মঙ্গল", "বুধ", "বৃহস্পতি", "শুক্র", "শনি"],
    },
    holidays: {
      title: "ছুটির তালিকা",
      hint: "নির্দিষ্ট তারিখের ছুটি (ঈদ, জাতীয় দিবস ইত্যাদি)। এই দিনগুলোতে উপস্থিতি/অনুপস্থিতি গণনা হয় না।",
      year: "বছর",
      date: "তারিখ",
      name: "ছুটির নাম",
      namePlaceholder: "যেমন: ঈদুল ফিতর",
      add: "যোগ করুন",
      adding: "যোগ হচ্ছে...",
      added: "ছুটি যোগ হয়েছে",
      addFailed: "ছুটি যোগ করা যায়নি",
      dateRequired: "তারিখ দিন",
      nameRequired: "ছুটির নাম দিন",
      empty: "এই বছরে কোনো ছুটি যোগ করা হয়নি",
      loadFailed: "ছুটির তালিকা লোড করা যায়নি",
      deleteTitle: "ছুটি মুছুন",
      deleteMessage: (title: string, date: string) => `"${title}" (${date}) ছুটিটি মুছে ফেলতে চান?`,
      deleteConfirm: "মুছুন",
      deleted: "ছুটি মুছে ফেলা হয়েছে",
      count: (n: string) => `${n}টি`,
    },
    offline: {
      title: "অফলাইন সতর্কতা",
      hint: "কোনো ডিভাইস/কানেক্টর নির্দিষ্ট সময় ধরে অফলাইন থাকলে একবার SMS যাবে (SMS ব্যালান্স থেকে কাটবে)।",
      minutes: "কত মিনিট অফলাইন থাকলে",
      minutesInvalid: "৫ থেকে ১৪৪০ মিনিটের মধ্যে দিন",
      phone: "সতর্কতার মোবাইল নম্বর (ঐচ্ছিক)",
      phonePlaceholder: "যেমন: 01712345678",
      phoneHint: "খালি রাখলে {{institution}}র ফোন নম্বরে যাবে।",
      phoneInvalid: "সঠিক মোবাইল নম্বর দিন",
    },
    clock: {
      title: "ঘড়ি স্বয়ংক্রিয় মেলানো",
      hint: "মেশিনের ঘড়ি কানেক্টর PC-র সময় থেকে ১ মিনিটের বেশি আগে/পিছে থাকলে কানেক্টর নিজে থেকেই ঠিক করে দেবে। PC-র সময় সঠিক রাখুন।",
    },
    pin: {
      title: "ডিভাইস আইডি (PIN)",
      hint: "মেশিনে প্রত্যেকের আইডি কীভাবে তৈরি হবে। নতুন আইডি দেওয়ার সময় এই নিয়ম মানা হয়।",
      modeRegistration: "রেজিস্ট্রেশন নম্বর (সুপারিশকৃত)",
      modeRegistrationHint: "শিক্ষার্থী = রেজি. নং, শিক্ষক = ৯০০০০ + রেজি. নং, স্টাফ = ৯৫০০০ + রেজি. নং",
      modeAuto: "অটো নম্বর",
      modeAutoHint: "নিচের শুরুর সংখ্যা থেকে ক্রমানুসারে",
      label: "অটো নম্বরের শুরু",
      labelHint: "রেজি. নং না থাকলে বা অন্য কারো সাথে মিলে গেলেও এখান থেকে নম্বর নেওয়া হয়",
      invalid: "১ থেকে ৯৯৯৯৯৯৯৯ এর মধ্যে দিন",
      convert: "পুরনো অটো আইডি রেজি. নং-এ বদলান",
      convertHint: "সিস্টেমের দেওয়া আইডিগুলো নতুন নিয়মে বদলাবে; হাতে বসানো আইডি বদলাবে না। মেশিনে আঙুলের ছাপ ও কার্ড থেকে যাবে।",
      convertSaveFirst: "আগে সেটিংস সেভ করুন",
      convertTitle: "আইডি রূপান্তর",
      convertMessage: "সিস্টেমের দেওয়া সব ডিভাইস আইডি রেজিস্ট্রেশন নম্বর অনুযায়ী বদলানো হবে। কানেক্টর মেশিনের ইউজারগুলোর আইডি বদলে দেবে (আঙুলের ছাপ ও কার্ড থাকবে)। চালিয়ে যাবেন?",
      convertConfirm: "বদলান",
      converted: (changed: string, skipped: string) => `${changed} জনের আইডি বদলেছে${skipped !== "0" && skipped !== "০" ? `, ${skipped} জন বাদ (আইডি অন্য কারো সাথে মিলে যায়)` : ""}`,
      convertFailed: "আইডি বদলানো যায়নি",
    },
    timeInvalid: "সঠিক সময় দিন",
  },
  en: {
    title: "Device Settings",
    subtitle: "How attendance is counted from device punches — late, absent, check-out, holidays and alerts.",
    save: "Save",
    saving: "Saving...",
    saved: "Settings saved",
    saveFailed: "Could not save",
    unsaved: "Unsaved changes",
    discard: "Discard",
    loadFailed: "Could not load the settings",
    retry: "Try again",
    tryAgainDot: "Please try again.",
    minutes: "minutes",
    smsLink: "Auto Notifications",
    late: {
      title: "Late",
      hint: "A first punch after the start time + grace minutes counts as \"late\".",
      studentStart: "{{student}} start time",
      teacherStart: "{{teacher}} & staff start time",
      grace: "Grace (minutes)",
      graceInvalid: "Enter 0 to 180 minutes",
    },
    absent: {
      title: "Auto absent",
      hint: "Everyone with a device ID who hasn't punched by this time is marked absent automatically. A later punch upgrades it to present/late. Doesn't run on holidays.",
      cutoff: "Mark absent at",
      maxWait: "Max wait for device sync (minutes)",
      maxWaitHelp: "While the internet is down or a device still has queued punches, marking absent waits up to this long, so nobody who punched in is wrongly marked absent. 0 = don't wait.",
      maxWaitInvalid: "Enter 0 to 480 minutes",
      smsHint: "To SMS guardians about absence, turn it on in:",
    },
    manualSms: {
      title: "SMS for attendance marked by hand",
      hint: "When today's attendance is marked or changed on the \"Take attendance\" page, guardians get the same present/absent SMS as with the device. Each SMS goes at most once a day, also when the student punches. Edits of past days never send SMS.",
      smsHint: "SMS text and on/off (present, absent) are set in:",
    },
    checkout: {
      title: "Check-out",
      hint: "A punch after this time (and at least 30 minutes after check-in) counts as check-out.",
      after: "Check-out starts at",
      smsHint: "To send the check-out SMS, turn it on in:",
    },
    weekly: {
      title: "Weekly off days",
      hint: "On these days punches are not counted and no one is marked absent.",
      days: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
    },
    holidays: {
      title: "Holidays",
      hint: "Specific dated holidays (Eid, national days, ...). Attendance isn't counted on these days.",
      year: "Year",
      date: "Date",
      name: "Holiday name",
      namePlaceholder: "e.g. Eid ul-Fitr",
      add: "Add",
      adding: "Adding...",
      added: "Holiday added",
      addFailed: "Could not add the holiday",
      dateRequired: "Enter a date",
      nameRequired: "Enter the holiday name",
      empty: "No holidays added for this year",
      loadFailed: "Could not load the holidays",
      deleteTitle: "Delete holiday",
      deleteMessage: (title, date) => `Delete the holiday "${title}" (${date})?`,
      deleteConfirm: "Delete",
      deleted: "Holiday deleted",
      count: (n) => `${n}`,
    },
    offline: {
      title: "Offline alert",
      hint: "If a device/connector stays offline for this long, one SMS is sent (charged to the SMS balance).",
      minutes: "Alert after (minutes offline)",
      minutesInvalid: "Enter 5 to 1440 minutes",
      phone: "Alert mobile number (optional)",
      phonePlaceholder: "e.g. 01712345678",
      phoneHint: "Leave empty to use the {{institution}}'s phone number.",
      phoneInvalid: "Enter a valid mobile number",
    },
    clock: {
      title: "Automatic clock sync",
      hint: "If the machine clock is more than 1 minute off the connector PC's time, the connector corrects it. Keep the PC time correct.",
    },
    pin: {
      title: "Device ID (PIN)",
      hint: "How each person's ID on the machine is made. Applied whenever a new ID is given.",
      modeRegistration: "Registration number (recommended)",
      modeRegistrationHint: "Student = reg. no, teacher = 90000 + reg. no, staff = 95000 + reg. no",
      modeAuto: "Auto number",
      modeAutoHint: "Counts up from the start number below",
      label: "Auto number start",
      labelHint: "Also used when there is no reg. no or it clashes with someone else",
      invalid: "Enter 1 to 99999999",
      convert: "Change old auto IDs to reg. no",
      convertHint: "System-assigned IDs move to the new scheme; IDs typed by hand stay. Fingerprints and cards on the machine are kept.",
      convertSaveFirst: "Save the settings first",
      convertTitle: "Convert IDs",
      convertMessage: "All system-assigned device IDs will change to the registration-number scheme. The connector renames the users on the machine (fingerprints and cards are kept). Continue?",
      convertConfirm: "Convert",
      converted: (changed: string, skipped: string) => `${changed} IDs changed${skipped !== "0" ? `, ${skipped} skipped (ID clashes with someone else)` : ""}`,
      convertFailed: "Could not convert IDs",
    },
    timeInvalid: "Enter a valid time",
  },
});
