import { defineText } from "@madrasha/shared-ui/src/i18n";

export const usersText = defineText({
  bn: {
    fillRequired: "নাম, ইমেইল, পাসওয়ার্ড ও রোল দিন",
    userCreated: "ইউজার তৈরি হয়েছে",
    createFailed: "ইউজার তৈরি করতে সমস্যা হয়েছে",
    roleChanged: "রোল পরিবর্তন করা হয়েছে",
    roleChangeFailed: "রোল পরিবর্তন করতে সমস্যা হয়েছে",
    updateFailed: "আপডেট করতে সমস্যা হয়েছে",
    mobileSaved: "মোবাইল নম্বর সংরক্ষণ হয়েছে",
    mobileSaveFailed: "মোবাইল সংরক্ষণ করতে সমস্যা হয়েছে",
    passwordMin6: "পাসওয়ার্ড কমপক্ষে ৬ অক্ষরের হতে হবে",
    passwordReset: (name: string) => `"${name}"-এর পাসওয়ার্ড রিসেট হয়েছে`,
    passwordResetFailed: "পাসওয়ার্ড রিসেট করতে সমস্যা হয়েছে",
    unlocked: (name: string) => `"${name}"-এর অ্যাকাউন্ট আনলক হয়েছে`,
    unlockFailed: "আনলক করতে সমস্যা হয়েছে",
    deleteTitle: "ইউজার ডিলিট করুন",
    deleteMessage: (name: string, email: string) =>
      `"${name}" (${email}) কে স্থায়ীভাবে মুছে ফেলতে চান? তিনি আর এই প্যানেলে লগইন করতে পারবেন না।`,
    deleteConfirm: "ডিলিট করুন",
    userDeleted: "ইউজার মুছে ফেলা হয়েছে",
    title: "স্টাফ ব্যবস্থাপনা",
    subtitle: "যারা এই প্যানেলে লগইন করবে তাদের অ্যাকাউন্ট তৈরি ও রোল নির্ধারণ করুন",
    addNewUser: "নতুন ইউজার যোগ করুন",
    staffName: "স্টাফের নাম",
    loginEmail: "লগইন ইমেইল",
    password: "পাসওয়ার্ড",
    min6Chars: "কমপক্ষে ৬ অক্ষর",
    showPassword: "পাসওয়ার্ড দেখান",
    hidePassword: "পাসওয়ার্ড লুকান",
    role: "রোল",
    selectRole: "রোল নির্বাচন করুন",
    headRoleNote: "{{head}} রোল এখান থেকে দেওয়া যায় না — প্রতিটি প্রতিষ্ঠানের একজনই ডিফল্ট {{head}} থাকতে পারেন।",
    creating: "তৈরি হচ্ছে...",
    allUsers: "সব ইউজার",
    noUsers: "কোনো ইউজার নেই",
    defaultHead: "ডিফল্ট {{head}}",
    locked: "লকড",
    mobileNumber: "মোবাইল নম্বর",
    save: "সংরক্ষণ",
    addMobile: "মোবাইল যোগ করুন",
    superAdminOnly: "শুধু সুপার অ্যাডমিন এটি পরিবর্তন করতে পারবেন",
    deactivate: "নিষ্ক্রিয় করুন",
    activate: "সক্রিয় করুন",
    unlockAccount: "অ্যাকাউন্ট আনলক করুন",
    unlocking: "আনলক হচ্ছে...",
    unlock: "আনলক",
    resetPassword: "পাসওয়ার্ড রিসেট করুন",
    newPasswordMin6: "নতুন পাসওয়ার্ড (কমপক্ষে ৬ অক্ষর)",
    setPassword: "পাসওয়ার্ড সেট করুন",
  },
  en: {
    fillRequired: "Enter name, email, password and role",
    userCreated: "User created",
    createFailed: "Could not create the user",
    roleChanged: "Role changed",
    roleChangeFailed: "Could not change the role",
    updateFailed: "Could not update",
    mobileSaved: "Mobile number saved",
    mobileSaveFailed: "Could not save the mobile number",
    passwordMin6: "Password must be at least 6 characters",
    passwordReset: (name) => `Password reset for "${name}"`,
    passwordResetFailed: "Could not reset the password",
    unlocked: (name) => `"${name}"'s account unlocked`,
    unlockFailed: "Could not unlock",
    deleteTitle: "Delete user",
    deleteMessage: (name, email) =>
      `Permanently delete "${name}" (${email})? They will no longer be able to log in to this panel.`,
    deleteConfirm: "Delete",
    userDeleted: "User deleted",
    title: "Staff Management",
    subtitle: "Create accounts for people who will log in to this panel and assign their roles",
    addNewUser: "Add new user",
    staffName: "Staff name",
    loginEmail: "Login email",
    password: "Password",
    min6Chars: "At least 6 characters",
    showPassword: "Show password",
    hidePassword: "Hide password",
    role: "Role",
    selectRole: "Select a role",
    headRoleNote: "The {{head}} role cannot be assigned here — each {{institution}} can have only one default {{head}}.",
    creating: "Creating...",
    allUsers: "All users",
    noUsers: "No users",
    defaultHead: "Default {{head}}",
    locked: "Locked",
    mobileNumber: "Mobile number",
    save: "Save",
    addMobile: "Add mobile",
    superAdminOnly: "Only the super admin can change this",
    deactivate: "Deactivate",
    activate: "Activate",
    unlockAccount: "Unlock account",
    unlocking: "Unlocking...",
    unlock: "Unlock",
    resetPassword: "Reset password",
    newPasswordMin6: "New password (at least 6 characters)",
    setPassword: "Set password",
  },
  ar: {
    fillRequired: "أدخل الاسم والبريد الإلكتروني وكلمة المرور والدور",
    userCreated: "تم إنشاء المستخدم",
    createFailed: "تعذّر إنشاء المستخدم",
    roleChanged: "تم تغيير الدور",
    roleChangeFailed: "تعذّر تغيير الدور",
    updateFailed: "تعذّر التحديث",
    mobileSaved: "تم حفظ رقم الجوال",
    mobileSaveFailed: "تعذّر حفظ رقم الجوال",
    passwordMin6: "يجب ألا تقل كلمة المرور عن ٦ أحرف",
    passwordReset: (name) => `تمت إعادة تعيين كلمة مرور "${name}"`,
    passwordResetFailed: "تعذّرت إعادة تعيين كلمة المرور",
    unlocked: (name) => `تم فتح حساب "${name}"`,
    unlockFailed: "تعذّر فتح القفل",
    deleteTitle: "حذف المستخدم",
    deleteMessage: (name, email) => `هل تريد حذف "${name}" (${email}) نهائيًا؟ لن يتمكن من تسجيل الدخول إلى هذه اللوحة بعد الآن.`,
    deleteConfirm: "حذف",
    userDeleted: "تم حذف المستخدم",
    title: "إدارة الموظفين",
    subtitle: "أنشئ حسابات من سيسجلون الدخول إلى هذه اللوحة وحدّد أدوارهم",
    addNewUser: "إضافة مستخدم جديد",
    staffName: "اسم الموظف",
    loginEmail: "بريد الدخول",
    password: "كلمة المرور",
    min6Chars: "٦ أحرف على الأقل",
    showPassword: "إظهار كلمة المرور",
    hidePassword: "إخفاء كلمة المرور",
    role: "الدور",
    selectRole: "اختر دورًا",
    headRoleNote: "لا يمكن إسناد دور {{head}} من هنا — لكل مؤسسة {{head}} افتراضي واحد فقط.",
    creating: "جارٍ الإنشاء...",
    allUsers: "جميع المستخدمين",
    noUsers: "لا يوجد مستخدمون",
    defaultHead: "{{head}} الافتراضي",
    locked: "مقفل",
    mobileNumber: "رقم الجوال",
    save: "حفظ",
    addMobile: "إضافة جوال",
    superAdminOnly: "لا يغيّر هذا إلا المشرف العام",
    deactivate: "تعطيل",
    activate: "تفعيل",
    unlockAccount: "فتح قفل الحساب",
    unlocking: "جارٍ فتح القفل...",
    unlock: "فتح القفل",
    resetPassword: "إعادة تعيين كلمة المرور",
    newPasswordMin6: "كلمة مرور جديدة (٦ أحرف على الأقل)",
    setPassword: "تعيين كلمة المرور",
  },
});
