import { defineText } from "@madrasha/shared-ui/src/i18n";

/** UI text for the {{academic}} settings pages. */
export const talimatSettingsText = defineText({
  bn: {
    // layout
    navClassBook: "{{division}} {{class}} {{subject}}",
    navExam: "পরীক্ষা",
    navGrade: "গ্রেডিং সিস্টেম",
    navDocuments: "ডকুমেন্টস টেমপ্লেট",
    navNotices: "নোটিশ বোর্ড",
    navSessions: "{{session}} সেটআপ",
    navRegistration: "রেজি. নম্বর ব্লক",
    settings: "সেটিং",
    settingsMenu: "সেটিং মেনু",
    // shared
    loadErrorTitle: "তথ্য লোড করা যায়নি",
    retry: "আবার চেষ্টা করুন",
    // exam settings
    examTitle: "পরীক্ষা ব্যবস্থাপনা",
    examSubtitle: "{{division}}ভিত্তিক পরীক্ষার তালিকা তৈরি ও ব্যবস্থাপনা করুন",
    examLoadError: "পরীক্ষার তালিকা আনতে সমস্যা হয়েছে। আবার চেষ্টা করুন।",
    // grade settings
    madrasaGrade: "মাদরাসা গ্রেড",
    generalGrade: "সাধারণ গ্রেড",
    gradeTitle: "গ্রেডিং সিস্টেম",
    gradeSubtitle: "{{division}}ভিত্তিক ফেল মার্ক ও গ্রেড স্কেল ব্যবস্থাপনা",
    gradeLoadError: "গ্রেডিং সেটিং আনতে সমস্যা হয়েছে। আবার চেষ্টা করুন।",
    gradeKind: "গ্রেডের ধরন",
    inheritedNote: "ডিফল্ট গ্রেড স্কেল — নিজস্ব গ্রেডিং চালু করলে এখানে সম্পাদনা করা যাবে",
    scalePreviewInherited: (kind: string) => `${kind} স্কেল প্রিভিউ (ডিফল্ট থেকে পাওয়া)`,
    scalePreview: (kind: string) => `${kind} স্কেল প্রিভিউ`,
    // registration blocks
    regTitle: "রেজিস্ট্রেশন নম্বর ব্লক",
    regSubtitle:
      "প্রতিটি {{class}}ের জন্য আলাদা নম্বরের ব্লক দিন (যেমন এক {{class}} ১–৫০, আরেক {{class}} ৫১–১০০)। নতুন {{student}} অনুমোদন বা প্রমোশনের সময় তার {{class}}ের ব্লকের পরের ফাঁকা নম্বরটি পাবে। একই নম্বর কখনো দুইজন {{student}}ের হবে না। আগে থেকে দেওয়া নম্বর বদলাবে না।",
    regLoadFailed: "ব্লকের তথ্য লোড করা যায়নি",
    noClasses: "কোনো {{class}} যোগ করা হয়নি",
    classCount: (n: string) => `${n}টি {{class}}`,
    noBlock: "ব্লক নেই — {{institution}}র সর্বশেষ নম্বরের পরেরটা পাবে",
    blockFull: (n: string) => `ব্লক পূর্ণ (${n}টি নম্বর ব্যবহৃত) — শেষ নম্বর বাড়ান`,
    usedNext: (n: string) => `ব্যবহৃত ${n}টি · পরের নম্বর `,
    start: "শুরু",
    end: "শেষ",
    startNoOf: (name: string) => `${name} — শুরুর নম্বর`,
    endNoOf: (name: string) => `${name} — শেষ নম্বর`,
    clearBlock: "ব্লক মুছুন",
    // class & book
    serialN: (n: string) => `ক্রম ${n}`,
    deleteDivisionTitle: "{{division}} ডিলিট করুন",
    deleteDivisionMessage: "{{division}}টি ট্রাশে পাঠাতে চান? পরে ট্রাশ থেকে ফিরিয়ে আনা যাবে।",
    deleteAction: "ডিলিট করুন",
    orderSaveFailed: "ক্রম সংরক্ষণ করা যায়নি",
    deleteClassTitle: "{{class}} ডিলিট করুন",
    deleteClassMessage: "{{class}}টি ডিলিট করতে চান?",
    deleteBookTitle: "{{subject}} ডিলিট করুন",
    deleteBookMessage: (name: string) =>
      `“${name}” {{subject}}টি ট্রাশে পাঠাতে চান? এর নম্বরসমূহ সংরক্ষিত থাকবে, ট্রাশ থেকে ফিরিয়ে আনা যাবে।`,
    fullMarksInvalid: "পূর্ণমান সঠিক সংখ্যা হতে হবে",
    passMarkInvalid: "পাস মার্ক ০ থেকে পূর্ণমানের মধ্যে হতে হবে",
    miyariSaved: "মিয়ারি {{subject}} সংরক্ষণ হয়েছে",
    classBookTitle: "{{institution}} {{class}} ও {{subject}} ব্যবস্থাপনা",
    classBookSubtitle:
      "{{division}} ও {{class}} বেছে নিয়ে {{subject}} সাজান। {{subject}}ের ✎ চাপলে পূর্ণমান, পাস মার্ক, মিয়ারি ও নম্বর বিভাজন পাওয়া যাবে। টেনে (drag) যেকোনো কলামের ক্রম সাজানো যায়।",
    divisions: "{{division}}",
    countN: (n: string) => `${n}টি`,
    moveDivision: "{{division}} সরান",
    editDivision: "{{division}} এডিট করুন",
    classes: "{{class}}",
    addClass: "{{class}} যোগ করুন",
    className: "{{class}}ের নাম",
    moveClass: "{{class}} সরান",
    editClass: "{{class}} এডিট করুন",
    books: "{{subject}}সমূহ",
    addBook: "{{subject}} যোগ করুন",
    bookName: "{{subject}}ের নাম",
    miyariSummary: (n: string) => `মিয়ারি ${n}টি · পূর্ণমান, পাস মার্ক, মিয়ারি ও নম্বর বিভাজন বদলাতে ✎ চাপুন`,
    noBooks: "কোনো {{subject}} যোগ করা হয়নি",
    fullMarks: "পূর্ণমান",
    passMark: "পাস মার্ক",
    global: "গ্লোবাল",
    passMarkHint: "পাস মার্ক খালি রাখলে {{institution}}র গ্লোবাল ফেল মার্ক প্রযোজ্য হবে",
    miyariBook: "মিয়ারি {{subject}}",
    miyariHint: "এতে ফেল করলে গড়ে পাস হলেও ফলাফল FAIL হবে। চাপলেই সাথে সাথে সংরক্ষণ হয়।",
    markComponents: "নম্বর বিভাজন (লিখিত/এমসিকিউ/...)",
    moveBook: "{{subject}} সরান",
    fullMarksN: (n: string) => `পূর্ণমান ${n}`,
    ownPassMark: "এই {{subject}}ের জন্য আলাদা পাস মার্ক",
    passN: (n: string) => `· পাস ${n}`,
    miyari: "মিয়ারি",
    editBook: "{{subject}} এডিট করুন",
    deleteBook: "{{subject}} ডিলিট করুন",
  },
  en: {
    navClassBook: "{{division}}, {{class}} & {{subject}}",
    navExam: "Exams",
    navGrade: "Grading System",
    navDocuments: "Document Templates",
    navNotices: "Notice Board",
    navSessions: "{{session}} Setup",
    navRegistration: "Reg. No. Blocks",
    settings: "Settings",
    settingsMenu: "Settings menu",
    loadErrorTitle: "Could not load data",
    retry: "Try again",
    examTitle: "Exam Management",
    examSubtitle: "Create and manage the exam list by {{division}}",
    examLoadError: "Could not fetch the exam list. Please try again.",
    madrasaGrade: "Madrasa Grade",
    generalGrade: "General Grade",
    gradeTitle: "Grading System",
    gradeSubtitle: "Manage fail marks and grade scales by {{division}}",
    gradeLoadError: "Could not fetch grading settings. Please try again.",
    gradeKind: "Grade type",
    inheritedNote: "Default grade scale — enable own grading to edit it here",
    scalePreviewInherited: (kind) => `${kind} scale preview (inherited from default)`,
    scalePreview: (kind) => `${kind} scale preview`,
    regTitle: "Registration Number Blocks",
    regSubtitle:
      "Give each {{class}} its own number block (e.g. one {{class}} 1–50, another 51–100). On approval or promotion a {{student}} gets the next free number in their {{class}}'s block. No number is ever shared by two {{student}}s, and existing numbers do not change.",
    regLoadFailed: "Could not load block data",
    noClasses: "No {{class}}es added",
    classCount: (n) => `${n} {{class}}es`,
    noBlock: "No block — gets the next number after the {{institution}}'s latest",
    blockFull: (n) => `Block full (${n} numbers used) — increase the end number`,
    usedNext: (n) => `${n} used · next number `,
    start: "Start",
    end: "End",
    startNoOf: (name) => `${name} — start number`,
    endNoOf: (name) => `${name} — end number`,
    clearBlock: "Clear block",
    serialN: (n) => `Order ${n}`,
    deleteDivisionTitle: "Delete {{division}}",
    deleteDivisionMessage: "Move this {{division}} to trash? It can be restored from trash later.",
    deleteAction: "Delete",
    orderSaveFailed: "Could not save the order",
    deleteClassTitle: "Delete {{class}}",
    deleteClassMessage: "Delete this {{class}}?",
    deleteBookTitle: "Delete {{subject}}",
    deleteBookMessage: (name) =>
      `Move the {{subject}} “${name}” to trash? Its marks are kept and it can be restored from trash.`,
    fullMarksInvalid: "Full marks must be a valid number",
    passMarkInvalid: "Pass mark must be between 0 and full marks",
    miyariSaved: "Core {{subject}}s saved",
    classBookTitle: "{{institution}} {{class}} & {{subject}} Management",
    classBookSubtitle:
      "Pick a {{division}} and {{class}}, then arrange its {{subject}}s. Press ✎ on a {{subject}} for full marks, pass mark, core flag and mark breakdown. Drag to reorder any column.",
    divisions: "{{division}}",
    countN: (n) => `${n}`,
    moveDivision: "Move {{division}}",
    editDivision: "Edit {{division}}",
    classes: "{{class}}",
    addClass: "Add {{class}}",
    className: "{{class}} name",
    moveClass: "Move {{class}}",
    editClass: "Edit {{class}}",
    books: "{{subject}}s",
    addBook: "Add {{subject}}",
    bookName: "{{subject}} name",
    miyariSummary: (n) => `${n} core · press ✎ to change full marks, pass mark, core flag and mark breakdown`,
    noBooks: "No {{subject}}s added",
    fullMarks: "Full marks",
    passMark: "Pass mark",
    global: "Global",
    passMarkHint: "Leave the pass mark empty to use the {{institution}}'s global fail mark",
    miyariBook: "Core {{subject}}",
    miyariHint: "Failing this means the result is FAIL even if the average passes. Saved instantly when toggled.",
    markComponents: "Mark breakdown (written/MCQ/...)",
    moveBook: "Move {{subject}}",
    fullMarksN: (n) => `Full marks ${n}`,
    ownPassMark: "Separate pass mark for this {{subject}}",
    passN: (n) => `· Pass ${n}`,
    miyari: "Core",
    editBook: "Edit {{subject}}",
    deleteBook: "Delete {{subject}}",
  },
  ar: {
    navClassBook: "{{division}} و{{class}} و{{subject}}",
    navExam: "الامتحانات",
    navGrade: "نظام التقديرات",
    navDocuments: "قوالب الوثائق",
    navNotices: "لوحة الإعلانات",
    navSessions: "إعداد {{session}}",
    navRegistration: "كتل أرقام التسجيل",
    settings: "الإعدادات",
    settingsMenu: "قائمة الإعدادات",
    loadErrorTitle: "تعذّر تحميل البيانات",
    retry: "أعد المحاولة",
    examTitle: "إدارة الامتحانات",
    examSubtitle: "أنشئ قائمة الامتحانات وأدرها حسب {{division}}",
    examLoadError: "تعذّر جلب قائمة الامتحانات. أعد المحاولة.",
    madrasaGrade: "تقدير المدرسة الدينية",
    generalGrade: "التقدير العام",
    gradeTitle: "نظام التقديرات",
    gradeSubtitle: "إدارة درجات الرسوب وسلالم التقديرات حسب {{division}}",
    gradeLoadError: "تعذّر جلب إعدادات التقدير. أعد المحاولة.",
    gradeKind: "نوع التقدير",
    inheritedNote: "سلّم التقديرات الافتراضي — فعّل التقدير الخاص لتعديله هنا",
    scalePreviewInherited: (kind) => `معاينة سلّم ${kind} (موروث من الافتراضي)`,
    scalePreview: (kind) => `معاينة سلّم ${kind}`,
    regTitle: "كتل أرقام التسجيل",
    regSubtitle:
      "خصّص لكل صف كتلة أرقام مستقلة (مثل صف 1–50 وآخر 51–100). عند اعتماد الطالب أو ترفيعه يحصل على أول رقم شاغر في كتلة صفه. لا يتكرر الرقم لطالبين أبدًا، ولا تتغير الأرقام الممنوحة سابقًا.",
    regLoadFailed: "تعذّر تحميل بيانات الكتل",
    noClasses: "لم يُضف أي صف",
    classCount: (n) => `${n} صفوف`,
    noBlock: "لا توجد كتلة — يحصل على الرقم التالي لآخر رقم في {{institution}}",
    blockFull: (n) => `الكتلة ممتلئة (استُخدم ${n} رقمًا) — زِد رقم النهاية`,
    usedNext: (n) => `مستخدم ${n} · الرقم التالي `,
    start: "البداية",
    end: "النهاية",
    startNoOf: (name) => `${name} — رقم البداية`,
    endNoOf: (name) => `${name} — رقم النهاية`,
    clearBlock: "حذف الكتلة",
    serialN: (n) => `الترتيب ${n}`,
    deleteDivisionTitle: "حذف {{division}}",
    deleteDivisionMessage: "نقل هذه المرحلة إلى السلة؟ يمكن استعادتها لاحقًا.",
    deleteAction: "حذف",
    orderSaveFailed: "تعذّر حفظ الترتيب",
    deleteClassTitle: "حذف {{class}}",
    deleteClassMessage: "هل تريد حذف هذا الصف؟",
    deleteBookTitle: "حذف {{subject}}",
    deleteBookMessage: (name) => `نقل “${name}” إلى السلة؟ ستبقى درجاته محفوظة ويمكن استعادته.`,
    fullMarksInvalid: "يجب أن تكون الدرجة الكاملة رقمًا صحيحًا",
    passMarkInvalid: "يجب أن تكون درجة النجاح بين 0 والدرجة الكاملة",
    miyariSaved: "تم حفظ المواد الأساسية",
    classBookTitle: "إدارة الصفوف و{{subject}}",
    classBookSubtitle:
      "اختر {{division}} و{{class}} ثم رتّب المواد. اضغط ✎ على المادة لضبط الدرجة الكاملة ودرجة النجاح والأساسية وتقسيم الدرجات. اسحب لإعادة ترتيب أي عمود.",
    divisions: "{{division}}",
    countN: (n) => `${n}`,
    moveDivision: "نقل {{division}}",
    editDivision: "تعديل {{division}}",
    classes: "{{class}}",
    addClass: "إضافة {{class}}",
    className: "اسم {{class}}",
    moveClass: "نقل {{class}}",
    editClass: "تعديل {{class}}",
    books: "{{subject}}",
    addBook: "إضافة {{subject}}",
    bookName: "اسم {{subject}}",
    miyariSummary: (n) => `الأساسية ${n} · اضغط ✎ لتغيير الدرجة الكاملة ودرجة النجاح والأساسية وتقسيم الدرجات`,
    noBooks: "لم يُضف أي {{subject}}",
    fullMarks: "الدرجة الكاملة",
    passMark: "درجة النجاح",
    global: "عامة",
    passMarkHint: "اترك درجة النجاح فارغة لتطبيق درجة الرسوب العامة في {{institution}}",
    miyariBook: "{{subject}} أساسي",
    miyariHint: "الرسوب فيه يجعل النتيجة راسبًا ولو نجح المعدل. يُحفظ فور الضغط.",
    markComponents: "تقسيم الدرجات (تحريري/اختيار من متعدد/...)",
    moveBook: "نقل {{subject}}",
    fullMarksN: (n) => `الدرجة الكاملة ${n}`,
    ownPassMark: "درجة نجاح خاصة بهذا {{subject}}",
    passN: (n) => `· النجاح ${n}`,
    miyari: "أساسي",
    editBook: "تعديل {{subject}}",
    deleteBook: "حذف {{subject}}",
  },
});
