import { defineText } from "@madrasha/shared-ui/src/i18n";

/** Shared list/export widgets in components/common. */
export const commonUiText = defineText({
  bn: {
    // ColumnVisibilityMenu
    showAllDefault: "সব দেখান (ডিফল্ট)",
    columns: "কলাম",
    showHideColumns: "কলাম দেখান / লুকান",
    reorderHint: "তীর বোতাম দিয়ে কলামের ক্রম আগে-পরে করা যাবে",
    moveEarlier: "আগে সরান",
    moveLater: "পরে সরান",
    // DataExportPrintActions
    marginTop: "উপর",
    marginRight: "ডান",
    marginBottom: "নিচ",
    marginLeft: "বাম",
    previewNotReady: "প্রিভিউ প্রস্তুত হয়নি, একটু পর আবার চেষ্টা করুন",
    pdfCancelled: "PDF তৈরি বাতিল করা হয়েছে",
    pdfDownloaded: (file: string) => `PDF ডাউনলোড হয়েছে (${file})`,
    pdfFailed: "PDF তৈরি করা যায়নি",
    pdfGenerating: "PDF তৈরি হচ্ছে, অপেক্ষা করুন...",
    downloading: "ডাউনলোড হচ্ছে...",
    pdfDownloadDone: (file: string) => `✓ PDF ডাউনলোড সম্পন্ন হয়েছে (${file})`,
    pdfDownloadStarted: (file: string) => `PDF ডাউনলোড শুরু হয়েছে (${file}) - ব্রাউজারের ডাউনলোড তালিকা দেখুন`,
    pdfFailedRetry: "PDF তৈরি করা যায়নি, আবার চেষ্টা করুন",
    portrait: "পোর্ট্রেট",
    landscape: "ল্যান্ডস্কেপ",
    marginTitle: "মার্জিন - পেজের চার পাশের ফাঁকা জায়গা আলাদাভাবে কম-বেশি করুন",
    margin: "মার্জিন",
    pageMarginMm: "পেজ মার্জিন (mm)",
    setDefault: "ডিফল্ট সেট",
    generating: "তৈরি হচ্ছে...",
    cancelPdf: "PDF তৈরি বাতিল করুন",
    print: "প্রিন্ট",
    // ExcelUpload
    uploadExcel: "Excel ফাইল আপলোড করুন",
    fileReadFailed: "ফাইল পড়া যায়নি",
    sheetNotFound: "Excel শিট পাওয়া যায়নি",
    excelEmpty: "Excel ফাইলটি খালি",
    noStudentData: "কোনো {{student}}র তথ্য পাওয়া যায়নি",
    excelHintBefore: "ভর্তির Excel ফাইল নির্বাচন করুন।",
    excelHintAfter: "চিহ্নিত আবশ্যক কলামগুলো স্বয়ংক্রিয়ভাবে শনাক্ত হবে।",
    supportedFiles: "সমর্থিত ফাইল: .xlsx, .xls, .csv",
    requiredColumns: "আবশ্যক টেমপ্লেট কলাম",
    requiredColumnsHint: "টেমপ্লেটে এই কলামগুলো লাল রঙে ও * চিহ্নসহ থাকবে",
    required: "আবশ্যক",
    orDropHere: "অথবা ফাইলটি এখানে টেনে এনে ছাড়ুন",
    // ProfileQuickNav
    noName: "নাম নেই",
    clearSearch: "সার্চ মুছুন",
    nothingFound: "কিছু পাওয়া যায়নি",
    expelled: "বহিষ্কৃত",
    inactive: "নিষ্ক্রিয়",
    previousProfile: "আগের প্রোফাইল",
    previousNamed: (name: string) => `আগের: ${name}`,
    noPrevious: "আগের কেউ নেই",
    nextProfile: "পরের প্রোফাইল",
    nextNamed: (name: string) => `পরের: ${name}`,
    noNext: "পরের কেউ নেই",
  },
  en: {
    showAllDefault: "Show all (default)",
    columns: "Columns",
    showHideColumns: "Show / hide columns",
    reorderHint: "Use the arrow buttons to reorder columns",
    moveEarlier: "Move earlier",
    moveLater: "Move later",
    marginTop: "Top",
    marginRight: "Right",
    marginBottom: "Bottom",
    marginLeft: "Left",
    previewNotReady: "Preview is not ready yet, please try again shortly",
    pdfCancelled: "PDF generation cancelled",
    pdfDownloaded: (file) => `PDF downloaded (${file})`,
    pdfFailed: "Could not create the PDF",
    pdfGenerating: "Generating PDF, please wait...",
    downloading: "Downloading...",
    pdfDownloadDone: (file) => `✓ PDF download complete (${file})`,
    pdfDownloadStarted: (file) => `PDF download started (${file}) - check your browser's downloads`,
    pdfFailedRetry: "Could not create the PDF, please try again",
    portrait: "Portrait",
    landscape: "Landscape",
    marginTitle: "Margins - adjust the blank space on each side of the page",
    margin: "Margin",
    pageMarginMm: "Page margin (mm)",
    setDefault: "Set default",
    generating: "Generating...",
    cancelPdf: "Cancel PDF generation",
    print: "Print",
    uploadExcel: "Upload Excel File",
    fileReadFailed: "File read failed",
    sheetNotFound: "Excel sheet not found",
    excelEmpty: "Excel file is empty",
    noStudentData: "No {{student}} data found",
    excelHintBefore: "Select the admission Excel file. Required columns marked with",
    excelHintAfter: "will be detected automatically.",
    supportedFiles: "Supported files: .xlsx, .xls, .csv",
    requiredColumns: "Required Template Columns",
    requiredColumnsHint: "These columns are shown in red with a * mark in the template",
    required: "Required",
    orDropHere: "or drag and drop the file here",
    noName: "No name",
    clearSearch: "Clear search",
    nothingFound: "Nothing found",
    expelled: "Expelled",
    inactive: "Inactive",
    previousProfile: "Previous profile",
    previousNamed: (name) => `Previous: ${name}`,
    noPrevious: "No previous record",
    nextProfile: "Next profile",
    nextNamed: (name) => `Next: ${name}`,
    noNext: "No next record",
  },
});
