import { defineText } from "@madrasha/shared-ui/src/i18n";

export const brandingText = defineText({
  bn: {
    saved: "সংরক্ষণ হয়েছে।",
    saveFailed: "সংরক্ষণ করা যায়নি। আবার চেষ্টা করুন।",
    imageDeleted: "ছবি মুছে ফেলা হয়েছে।",
    resetDefault: "ডিফল্টে ফিরিয়ে আনুন",
    resetDefaultConfirm:
      "নাম-ঠিকানার সাইজ/রঙ, লোগোর সাইজ-অবস্থান, হেডারের জায়গা এবং ফুটার — এই সেকশনের সব সেটিং ডিফল্ট মানে ফিরে যাবে। এগিয়ে যেতে চান?",
    title: "প্রতিষ্ঠান ব্র্যান্ডিং সেটিংস",
    subtitle:
      "প্রতিষ্ঠানের নাম, ঠিকানা, মোবাইল নম্বর, ইমেইল, সোশ্যাল লিংক ও লোগো দিন — এগুলো সব রিপোর্ট পেজে (আইডি কার্ড, মার্কশিট, উপস্থিতি, আয়-ব্যয় ইত্যাদি) স্বয়ংক্রিয়ভাবে দেখাবে।",
    reportTitle: "রিপোর্ট ডিজাইন সেটিংস",
    reportSubtitle:
      "রিপোর্টের ব্যাকগ্রাউন্ড, হেডার-ফুটার, ওয়াটারমার্ক ও প্রিন্ট মোড — আইডি কার্ড, মার্কশিট, উপস্থিতি, আয়-ব্যয় ইত্যাদি সব রিপোর্টে প্রযোজ্য।",
    basicInfo: "মূল তথ্য",
    basicInfoHint: "যেকোনো তথ্যের পাশের পেন্সিল আইকনে ক্লিক করলে শুধু সেই ফিল্ডটি এডিট করা যাবে",
    institutionName: "প্রতিষ্ঠানের নাম",
    namePlaceholder: "যেমন: জামিয়া ইসলামিয়া মাদ্রাসা",
    address: "ঠিকানা",
    addressPlaceholder: "যেমন: গ্রাম/মহল্লা, উপজেলা, জেলা",
    mobileNumber: "মোবাইল নম্বর",
    mobilePlaceholder: "যেমন: ০১৭xxxxxxxx",
    email: "ইমেইল",
    emailPlaceholder: "যেমন: info@example.com",
    socialLinks: "সোশ্যাল লিংক",
    socialLinksHint:
      "WhatsApp নম্বর, Facebook পেজ/প্রোফাইল/গ্রুপ, YouTube চ্যানেল সহ যেকোনো লিংক — একই ধরনের একাধিকও দেওয়া যাবে",
    logoAndBackground: "লোগো ও ব্যাকগ্রাউন্ড",
    logo: "লোগো",
    logoHint: "বর্গাকার ছবি ভালো দেখায় (স্বচ্ছ পটভূমি সহ PNG সবচেয়ে ভালো)",
    background: "ব্যাকগ্রাউন্ড",
    backgroundHint: "রিপোর্ট পেজের পুরো পটভূমি জুড়ে দেখাবে (PNG, JPG বা JPEG) — ফিল্ডের তথ্য অপরিবর্তিত থাকবে",
    defaultHeaderFooter: "ডিফল্ট হেডার-ফুটার ডিজাইন",
    defaultHeaderFooterHint:
      "উপরের 'কাস্টম হেডার-ফুটার' বন্ধ থাকলে এই সেটিং অনুযায়ী লোগো-নাম-ঠিকানা হেডার এবং (ঐচ্ছিক) ফুটার দেখাবে — চালু থাকলে এই সেটিং প্রযোজ্য হবে না",
    nameSize: "নামের সাইজ",
    nameColor: "নামের রঙ",
    addressSize: "ঠিকানার সাইজ",
    addressColor: "ঠিকানার রঙ",
    logoSize: "লোগোর সাইজ",
    basePosition: "মূল অবস্থান",
    posLeft: "বামে",
    posCenter: "মাঝে",
    posRight: "ডানে",
    fineMove: "সূক্ষ্মভাবে সরান",
    backToBase: "মূল জায়গায় ফিরুন",
    moveLogoUp: "লোগো উপরে সরান",
    moveLogoLeft: "লোগো বামে সরান",
    moveLogoRight: "লোগো ডানে সরান",
    moveLogoDown: "লোগো নিচে সরান",
    offsetX: (px: string) => `বামে/ডানে: ${px}px`,
    offsetY: (px: string) => `উপরে/নিচে: ${px}px`,
    fineMoveHint:
      "উপরে বেছে নেওয়া মূল অবস্থান থেকে সামান্য সরিয়ে (চাপ দিলেই কয়েক পিক্সেল করে) ঠিক জায়গায় বসাতে ব্যবহার করুন।",
    headerTotalSpace: "হেডারের মোট জায়গা",
    auto: "স্বয়ংক্রিয়",
    autoByContent: "স্বয়ংক্রিয় (কনটেন্ট অনুযায়ী)",
    backToAuto: "স্বয়ংক্রিয়তে ফিরুন",
    headerHeightHint:
      "স্বয়ংক্রিয় থাকলে হেডার যতটুকু লাগে ততটুকু জায়গা নেবে। নির্দিষ্ট মান দিলে হেডার কমপক্ষে ওই জায়গা নেবে (নিচের কনটেন্ট প্রয়োজনে নিচে নেমে যাবে)।",
    defaultFooter: "ডিফল্ট ফুটার (ঐচ্ছিক)",
    footerPlaceholder: "যেমন: প্রতিষ্ঠানের নাম, ঠিকানা, ফোন — প্রতিটি পেজের নিচে ছোট করে দেখাবে",
    footerEmptyHint: "ফাঁকা রাখলে ফুটারে কিছু দেখাবে না (শুধু পৃষ্ঠা নম্বর থাকবে)।",
    footerTextSize: "ফুটার টেক্সটের সাইজ",
    footerSpace: "ফুটারের জায়গা",
    footerTextColor: "ফুটার টেক্সটের রঙ",
    watermark: "ওয়াটারমার্ক",
    watermarkHint: "রিপোর্টের পেছনে হালকাভাবে ছাপা হয়",
    watermarkImage: "ওয়াটারমার্ক ছবি",
    watermarkImageHint: "রিপোর্টের পেছনে হালকাভাবে দেখাবে (স্বচ্ছ ব্যাকগ্রাউন্ড সহ PNG ব্যবহার করুন)",
    opacity: "স্বচ্ছতা (Opacity)",
    reportHeaderFooter: "রিপোর্ট হেডার-ফুটার",
    reportHeaderFooterHint: "চালু না থাকলে রিপোর্টে আগের মতোই প্রতিষ্ঠানের নাম-ঠিকানা দিয়ে ডিফল্ট হেডার দেখাবে",
    enableCustomHeaderFooter: "কাস্টম হেডার-ফুটার চালু করুন",
    customEnabledWarning: "চালু থাকায় ডিফল্ট লোগো-নাম-ঠিকানা হেডার আর দেখাবে না — নিচে ছবি না দিলে ওই জায়গা ফাঁকা থাকবে।",
    printMode: "প্রিন্ট মোড",
    normalPage: "সাধারণ পেজ",
    pressPaper: "প্রেস পেপার (লেটারহেড)",
    pressPaperHint:
      "প্রেস পেপার মোডে লোগো, ব্যাকগ্রাউন্ড, ওয়াটারমার্ক ও হেডার-ফুটার ছবি — কিছুই প্রিন্ট হবে না, শুধু মূল লেখাগুলো প্রিন্ট হবে (আগে থেকে ছাপানো লেটারহেড কাগজে প্রিন্টের জন্য)। উপরে-নিচে হেডার-ফুটার ছবির সমান জায়গা তবুও ফাঁকা রাখা হবে, যাতে লেখা গিয়ে ছাপানো লেটারহেডের উপর না পড়ে।",
    headerImage: "হেডার ছবি",
    headerImageHint:
      "প্রস্তাবিত সাইজ: ১৬০০×৩২০ পিক্সেল (৫:১ অনুপাত) — এই সাইজে দিলে A4 ও A5, দুই পেজেই ঠিকভাবে বসবে। অন্য অনুপাতেও দেওয়া যাবে (ছবি কখনো বিকৃত/কাটা হবে না), শুধু আশেপাশে কিছুটা ফাঁকা জায়গা থাকতে পারে।",
    headerRatio: "৫:১ (১৬০০×৩২০px)",
    footerImage: "ফুটার ছবি",
    footerImageHint: "প্রস্তাবিত সাইজ: ১৬০০×১৬০ পিক্সেল (১০:১ অনুপাত) — এই সাইজে দিলে A4 ও A5, দুই পেজেই ঠিকভাবে বসবে।",
    footerRatio: "১০:১ (১৬০০×১৬০px)",
    pressPaperNoUpload:
      "প্রেস পেপার মোডে হেডার/ফুটার ছবি আপলোডের দরকার নেই — যেহেতু এটা প্রিন্ট হবেই না। আগে আপলোড করা ছবি থাকলেও সেটা মুছে যাবে না, শুধু এই মোডে থাকা অবস্থায় প্রিন্ট হবে না।",
  },
  en: {
    saved: "Saved.",
    saveFailed: "Could not save. Please try again.",
    imageDeleted: "Image deleted.",
    resetDefault: "Reset to default",
    resetDefaultConfirm:
      "Name/address size and color, logo size and position, header space and footer — every setting in this section will return to its default. Continue?",
    title: "Institution Branding Settings",
    subtitle:
      "Enter the {{institution}}'s name, address, mobile number, email, social links and logo — they appear automatically on every report page (ID cards, marksheets, attendance, income-expense, etc.).",
    reportTitle: "Report Design Settings",
    reportSubtitle:
      "Report background, header & footer, watermark and print mode — applies to every report (ID cards, marksheets, attendance, income-expense, etc.).",
    basicInfo: "Basic information",
    basicInfoHint: "Click the pencil icon next to any field to edit only that field",
    institutionName: "{{institution}} name",
    namePlaceholder: "e.g. Jamia Islamia Madrasa",
    address: "Address",
    addressPlaceholder: "e.g. Village/Area, Upazila, District",
    mobileNumber: "Mobile number",
    mobilePlaceholder: "e.g. 017xxxxxxxx",
    email: "Email",
    emailPlaceholder: "e.g. info@example.com",
    socialLinks: "Social links",
    socialLinksHint:
      "Any link including WhatsApp numbers, Facebook pages/profiles/groups and YouTube channels — several of the same type are allowed",
    logoAndBackground: "Logo & background",
    logo: "Logo",
    logoHint: "Square images look best (PNG with a transparent background is ideal)",
    background: "Background",
    backgroundHint: "Shown across the whole report page background (PNG, JPG or JPEG) — field data is unchanged",
    defaultHeaderFooter: "Default header & footer design",
    defaultHeaderFooterHint:
      "When 'Custom header & footer' is off, the logo-name-address header and (optional) footer follow these settings — they do not apply while it is on",
    nameSize: "Name size",
    nameColor: "Name color",
    addressSize: "Address size",
    addressColor: "Address color",
    logoSize: "Logo size",
    basePosition: "Base position",
    posLeft: "Left",
    posCenter: "Center",
    posRight: "Right",
    fineMove: "Fine adjust",
    backToBase: "Back to base position",
    moveLogoUp: "Move logo up",
    moveLogoLeft: "Move logo left",
    moveLogoRight: "Move logo right",
    moveLogoDown: "Move logo down",
    offsetX: (px) => `Left/right: ${px}px`,
    offsetY: (px) => `Up/down: ${px}px`,
    fineMoveHint: "Nudge the logo a few pixels per click from the base position chosen above to place it exactly.",
    headerTotalSpace: "Total header space",
    auto: "Auto",
    autoByContent: "Auto (by content)",
    backToAuto: "Back to auto",
    headerHeightHint:
      "On auto, the header takes only the space it needs. With a fixed value the header takes at least that much space (content below moves down if needed).",
    defaultFooter: "Default footer (optional)",
    footerPlaceholder: "e.g. {{institution}} name, address, phone — shown small at the bottom of every page",
    footerEmptyHint: "Leave empty to show nothing in the footer (only the page number).",
    footerTextSize: "Footer text size",
    footerSpace: "Footer space",
    footerTextColor: "Footer text color",
    watermark: "Watermark",
    watermarkHint: "Printed faintly behind the report",
    watermarkImage: "Watermark image",
    watermarkImageHint: "Shown faintly behind the report (use a PNG with a transparent background)",
    opacity: "Opacity",
    reportHeaderFooter: "Report header & footer",
    reportHeaderFooterHint: "When off, reports show the default header with the {{institution}}'s name and address as before",
    enableCustomHeaderFooter: "Enable custom header & footer",
    customEnabledWarning:
      "While enabled, the default logo-name-address header is hidden — if no image is added below, that space stays empty.",
    printMode: "Print mode",
    normalPage: "Normal page",
    pressPaper: "Press paper (letterhead)",
    pressPaperHint:
      "In press paper mode, the logo, background, watermark and header/footer images are not printed — only the main text is (for pre-printed letterhead paper). Space equal to the header/footer images is still left blank so the text does not overlap the printed letterhead.",
    headerImage: "Header image",
    headerImageHint:
      "Recommended size: 1600×320 pixels (5:1 ratio) — fits both A4 and A5 pages. Other ratios also work (the image is never stretched or cropped), there may just be some empty space around it.",
    headerRatio: "5:1 (1600×320px)",
    footerImage: "Footer image",
    footerImageHint: "Recommended size: 1600×160 pixels (10:1 ratio) — fits both A4 and A5 pages.",
    footerRatio: "10:1 (1600×160px)",
    pressPaperNoUpload:
      "Header/footer images are not needed in press paper mode since they are never printed. Previously uploaded images are kept, they just won't print while this mode is on.",
  },
});
