import { defineText } from "@madrasha/shared-ui/src/i18n";

export const planText = defineText({
  bn: {
    status: { trial: "ট্রায়াল", active: "সক্রিয়", expired: "মেয়াদ শেষ", suspended: "স্থগিত" },
    limitReached: "সীমা শেষ — বাড়ানোর জন্য সুপার এডমিনের সাথে যোগাযোগ করুন",
    loadFailed: "প্ল্যানের তথ্য লোড করা যায়নি।",
    title: "প্ল্যান ও সাবস্ক্রিপশন",
    subtitle: "আপনার প্রতিষ্ঠানের বর্তমান প্ল্যান, মেয়াদ ও ব্যবহারের তথ্য — এটি সম্পূর্ণভাবে সুপার এডমিন কর্তৃপক্ষ থেকে নিয়ন্ত্রিত হয়।",
    expiredAlready: "মেয়াদ শেষ হয়ে গেছে",
    expiresToday: "আজই মেয়াদ শেষ হবে",
    daysLeft: (n: string) => `${n} দিন বাকি`,
    currentPlan: "বর্তমান প্ল্যান",
    noPlan: "কোনো প্ল্যান বরাদ্দ নেই",
    pricePer: (price: string, days: string) => `৳${price} / ${days} দিন`,
    validity: "মেয়াদ",
    validityHint: "প্ল্যানের শুরু ও শেষের তারিখ",
    startDate: "শুরুর তারিখ",
    endDate: "শেষের তারিখ",
    state: "অবস্থা",
    usageLimits: "ব্যবহারের সীমা",
    usageLimitsHint: "সুপার এডমিন কর্তৃক নির্ধারিত সর্বোচ্চ সীমার তুলনায় বর্তমান ব্যবহার",
    studentLimit: "{{student}} সীমা",
    userLimit: "ইউজার সীমা",
    changePlan: "প্ল্যান পরিবর্তন",
    changePlanBody:
      "নিরাপত্তার স্বার্থে প্ল্যান, মেয়াদ ও সীমা শুধুমাত্র সুপার এডমিন কর্তৃপক্ষ থেকে পরিবর্তন করা যায়। প্ল্যান আপগ্রেড, নবায়ন বা কোনো সীমা বাড়ানোর প্রয়োজন হলে সুপার এডমিনের সাথে যোগাযোগ করুন।",
    supportHint: "সহায়তার জন্য অ্যাডমিন প্যানেল থেকে দায়িত্বপ্রাপ্ত কর্তৃপক্ষের সাথে যোগাযোগ করুন।",
  },
  en: {
    status: { trial: "Trial", active: "Active", expired: "Expired", suspended: "Suspended" },
    limitReached: "Limit reached — contact the super admin to increase it",
    loadFailed: "Could not load plan information.",
    title: "Plan & Subscription",
    subtitle: "Your {{institution}}'s current plan, validity and usage — fully controlled by the super admin.",
    expiredAlready: "Expired",
    expiresToday: "Expires today",
    daysLeft: (n) => `${n} days left`,
    currentPlan: "Current plan",
    noPlan: "No plan assigned",
    pricePer: (price, days) => `৳${price} / ${days} days`,
    validity: "Validity",
    validityHint: "Plan start and end dates",
    startDate: "Start date",
    endDate: "End date",
    state: "Status",
    usageLimits: "Usage limits",
    usageLimitsHint: "Current usage compared with the maximum set by the super admin",
    studentLimit: "{{student}} limit",
    userLimit: "User limit",
    changePlan: "Change plan",
    changePlanBody:
      "For security, the plan, validity and limits can only be changed by the super admin. Contact the super admin to upgrade, renew or raise a limit.",
    supportHint: "For help, contact the responsible authority of the admin panel.",
  },
  ar: {
    status: { trial: "تجريبي", active: "نشط", expired: "منتهي", suspended: "موقوف" },
    limitReached: "تم بلوغ الحد — تواصل مع المشرف العام لزيادته",
    loadFailed: "تعذّر تحميل معلومات الباقة.",
    title: "الباقة والاشتراك",
    subtitle: "الباقة الحالية لـ{{institution}} ومدتها واستخدامها — يتحكم بها المشرف العام بالكامل.",
    expiredAlready: "انتهت الصلاحية",
    expiresToday: "تنتهي الصلاحية اليوم",
    daysLeft: (n) => `متبقٍ ${n} يوم`,
    currentPlan: "الباقة الحالية",
    noPlan: "لم تُخصَّص أي باقة",
    pricePer: (price, days) => `৳${price} / ${days} يوم`,
    validity: "المدة",
    validityHint: "تاريخ بداية الباقة ونهايتها",
    startDate: "تاريخ البداية",
    endDate: "تاريخ النهاية",
    state: "الحالة",
    usageLimits: "حدود الاستخدام",
    usageLimitsHint: "الاستخدام الحالي مقارنة بالحد الأقصى الذي حدده المشرف العام",
    studentLimit: "حد الطلاب",
    userLimit: "حد المستخدمين",
    changePlan: "تغيير الباقة",
    changePlanBody:
      "لدواعٍ أمنية، لا يمكن تغيير الباقة والمدة والحدود إلا من قِبل المشرف العام. تواصل معه للترقية أو التجديد أو زيادة أي حد.",
    supportHint: "للمساعدة، تواصل مع الجهة المسؤولة عن لوحة الإدارة.",
  },
});

export const profileText = defineText({
  bn: {
    unknownDevice: "অজানা ডিভাইস",
    browser: "ব্রাউজার",
    sessionsLoadFailed: "সেশন তালিকা লোড করা যায়নি।",
    profileLoadFailed: "প্রোফাইল লোড করা যায়নি।",
    enterBothPasswords: "বর্তমান ও নতুন পাসওয়ার্ড দিন।",
    newPasswordMin6: "নতুন পাসওয়ার্ড কমপক্ষে ৬ অক্ষরের হতে হবে।",
    newPasswordMismatch: "নতুন পাসওয়ার্ড দুইবার একই দিতে হবে।",
    passwordChanged: "পাসওয়ার্ড পরিবর্তন হয়েছে।",
    passwordChangeFailed: "পাসওয়ার্ড পরিবর্তন করা যায়নি।",
    enterPassword: "পাসওয়ার্ড দিন।",
    wrongPassword: "পাসওয়ার্ড সঠিক নয়।",
    loggedOut: "লগআউট করা হয়েছে।",
    sessionLoggedOut: "সেশনটি লগআউট করা হয়েছে।",
    loggedOutOthers: "অন্য সব ডিভাইস থেকে লগআউট করা হয়েছে।",
    loggedOutAll: "সব ডিভাইস থেকে লগআউট করা হয়েছে।",
    logoutFailed: "লগআউট করা যায়নি। আবার চেষ্টা করুন।",
    title: "প্রোফাইল সেটিংস",
    subtitle: "আপনার নিজের নাম, মোবাইল নম্বর, ছবি ও পাসওয়ার্ড এখান থেকে আপডেট করুন।",
    profilePhoto: "প্রোফাইল ছবি",
    basicInfo: "মূল তথ্য",
    basicInfoHint: "তথ্যের পাশের পেন্সিল আইকনে ক্লিক করলে শুধু সেই ফিল্ডটি এডিট করা যাবে",
    mobileNumber: "মোবাইল নম্বর",
    mobilePlaceholder: "যেমন: 01xxxxxxxxx",
    role: "রোল",
    changePassword: "পাসওয়ার্ড পরিবর্তন",
    changePasswordHint: "নিরাপত্তার জন্য বর্তমান পাসওয়ার্ড দিয়ে যাচাই করা হবে",
    currentPassword: "বর্তমান পাসওয়ার্ড",
    newPassword: "নতুন পাসওয়ার্ড",
    retypeNewPassword: "নতুন পাসওয়ার্ড আবার লিখুন",
    showPassword: "পাসওয়ার্ড দেখান",
    hidePassword: "পাসওয়ার্ড লুকান",
    changing: "পরিবর্তন হচ্ছে...",
    changePasswordBtn: "পাসওয়ার্ড পরিবর্তন করুন",
    loginSessions: "লগইন সেশন",
    loginSessionsHint: "আপনি বর্তমানে যেসব ডিভাইস/ব্রাউজার থেকে লগইন করা আছেন, তার তালিকা",
    noSessions: "কোনো সক্রিয় সেশন পাওয়া যায়নি।",
    thisDevice: "এই ডিভাইস",
    loginAt: (date: string) => `লগইন: ${date}`,
    logoutOthers: "অন্য সব ডিভাইস থেকে লগআউট করুন",
    logoutAllIncluding: "এই ডিভাইসসহ সব ডিভাইস থেকে লগআউট করুন",
    takesUpTo15: "অন্য ডিভাইসে কার্যকর হতে সর্বোচ্চ ১৫ মিনিট সময় লাগতে পারে।",
    sessionLogout: "সেশন লগআউট",
    othersLogout: "অন্য সব ডিভাইস থেকে লগআউট",
    allLogout: "সব ডিভাইস থেকে লগআউট",
    confirmSelf: "আপনি নিজের এই ডিভাইস থেকে লগআউট হয়ে যাবেন। নিশ্চিত করছেন?",
    confirmDevice: "এই ডিভাইসটি থেকে লগআউট হয়ে যাবে। নিশ্চিত করছেন?",
    confirmOthers: "এই ডিভাইস ছাড়া বাকি সব ডিভাইস/ব্রাউজার থেকে লগআউট হয়ে যাবে। আপনি এখানে লগইন করা থাকবেন। নিশ্চিত করছেন?",
    confirmAll: "আপনি লগইন করা আছেন এমন সব ডিভাইস থেকে (এই ডিভাইসসহ) লগআউট হয়ে যাবেন। নিশ্চিত করছেন?",
    confirmPasswordHint: "নিরাপত্তার জন্য নিশ্চিত করতে আপনার পাসওয়ার্ড দিন।",
    password: "পাসওয়ার্ড",
    verifying: "যাচাই হচ্ছে...",
    loggingOut: "লগআউট হচ্ছে...",
  },
  en: {
    unknownDevice: "Unknown device",
    browser: "Browser",
    sessionsLoadFailed: "Could not load the session list.",
    profileLoadFailed: "Could not load the profile.",
    enterBothPasswords: "Enter the current and new password.",
    newPasswordMin6: "The new password must be at least 6 characters.",
    newPasswordMismatch: "Enter the same new password twice.",
    passwordChanged: "Password changed.",
    passwordChangeFailed: "Could not change the password.",
    enterPassword: "Enter your password.",
    wrongPassword: "Incorrect password.",
    loggedOut: "Logged out.",
    sessionLoggedOut: "The session has been logged out.",
    loggedOutOthers: "Logged out from all other devices.",
    loggedOutAll: "Logged out from all devices.",
    logoutFailed: "Could not log out. Please try again.",
    title: "Profile Settings",
    subtitle: "Update your own name, mobile number, photo and password here.",
    profilePhoto: "Profile photo",
    basicInfo: "Basic information",
    basicInfoHint: "Click the pencil icon next to a field to edit only that field",
    mobileNumber: "Mobile number",
    mobilePlaceholder: "e.g. 01xxxxxxxxx",
    role: "Role",
    changePassword: "Change password",
    changePasswordHint: "Your current password is required for security",
    currentPassword: "Current password",
    newPassword: "New password",
    retypeNewPassword: "Retype new password",
    showPassword: "Show password",
    hidePassword: "Hide password",
    changing: "Changing...",
    changePasswordBtn: "Change password",
    loginSessions: "Login sessions",
    loginSessionsHint: "Devices/browsers you are currently logged in from",
    noSessions: "No active sessions found.",
    thisDevice: "This device",
    loginAt: (date) => `Login: ${date}`,
    logoutOthers: "Log out from all other devices",
    logoutAllIncluding: "Log out from all devices, including this one",
    takesUpTo15: "It may take up to 15 minutes to take effect on other devices.",
    sessionLogout: "Log out session",
    othersLogout: "Log out other devices",
    allLogout: "Log out all devices",
    confirmSelf: "You will be logged out from this device. Continue?",
    confirmDevice: "That device will be logged out. Continue?",
    confirmOthers: "All devices/browsers except this one will be logged out. You will stay logged in here. Continue?",
    confirmAll: "You will be logged out from every device you are logged in on (including this one). Continue?",
    confirmPasswordHint: "Enter your password to confirm.",
    password: "Password",
    verifying: "Verifying...",
    loggingOut: "Logging out...",
  },
  ar: {
    unknownDevice: "جهاز غير معروف",
    browser: "متصفح",
    sessionsLoadFailed: "تعذّر تحميل قائمة الجلسات.",
    profileLoadFailed: "تعذّر تحميل الملف الشخصي.",
    enterBothPasswords: "أدخل كلمة المرور الحالية والجديدة.",
    newPasswordMin6: "يجب ألا تقل كلمة المرور الجديدة عن ٦ أحرف.",
    newPasswordMismatch: "أدخل كلمة المرور الجديدة نفسها مرتين.",
    passwordChanged: "تم تغيير كلمة المرور.",
    passwordChangeFailed: "تعذّر تغيير كلمة المرور.",
    enterPassword: "أدخل كلمة المرور.",
    wrongPassword: "كلمة المرور غير صحيحة.",
    loggedOut: "تم تسجيل الخروج.",
    sessionLoggedOut: "تم تسجيل خروج الجلسة.",
    loggedOutOthers: "تم تسجيل الخروج من جميع الأجهزة الأخرى.",
    loggedOutAll: "تم تسجيل الخروج من جميع الأجهزة.",
    logoutFailed: "تعذّر تسجيل الخروج. حاول مرة أخرى.",
    title: "إعدادات الملف الشخصي",
    subtitle: "حدّث اسمك ورقم جوالك وصورتك وكلمة المرور من هنا.",
    profilePhoto: "صورة الملف الشخصي",
    basicInfo: "المعلومات الأساسية",
    basicInfoHint: "اضغط على أيقونة القلم بجانب الحقل لتعديله وحده",
    mobileNumber: "رقم الجوال",
    mobilePlaceholder: "مثال: 01xxxxxxxxx",
    role: "الدور",
    changePassword: "تغيير كلمة المرور",
    changePasswordHint: "سيتم التحقق بكلمة المرور الحالية لدواعٍ أمنية",
    currentPassword: "كلمة المرور الحالية",
    newPassword: "كلمة المرور الجديدة",
    retypeNewPassword: "أعد كتابة كلمة المرور الجديدة",
    showPassword: "إظهار كلمة المرور",
    hidePassword: "إخفاء كلمة المرور",
    changing: "جارٍ التغيير...",
    changePasswordBtn: "تغيير كلمة المرور",
    loginSessions: "جلسات الدخول",
    loginSessionsHint: "الأجهزة/المتصفحات التي أنت مسجّل الدخول منها حاليًا",
    noSessions: "لا توجد جلسات نشطة.",
    thisDevice: "هذا الجهاز",
    loginAt: (date) => `الدخول: ${date}`,
    logoutOthers: "تسجيل الخروج من جميع الأجهزة الأخرى",
    logoutAllIncluding: "تسجيل الخروج من جميع الأجهزة بما فيها هذا الجهاز",
    takesUpTo15: "قد يستغرق التطبيق على الأجهزة الأخرى حتى ١٥ دقيقة.",
    sessionLogout: "تسجيل خروج الجلسة",
    othersLogout: "تسجيل الخروج من الأجهزة الأخرى",
    allLogout: "تسجيل الخروج من جميع الأجهزة",
    confirmSelf: "سيتم تسجيل خروجك من هذا الجهاز. هل أنت متأكد؟",
    confirmDevice: "سيتم تسجيل الخروج من ذلك الجهاز. هل أنت متأكد؟",
    confirmOthers: "سيتم تسجيل الخروج من جميع الأجهزة/المتصفحات عدا هذا الجهاز، وستبقى مسجّلًا هنا. هل أنت متأكد؟",
    confirmAll: "سيتم تسجيل خروجك من جميع الأجهزة (بما فيها هذا الجهاز). هل أنت متأكد؟",
    confirmPasswordHint: "أدخل كلمة المرور للتأكيد.",
    password: "كلمة المرور",
    verifying: "جارٍ التحقق...",
    loggingOut: "جارٍ تسجيل الخروج...",
  },
});
