import { defineBilingualText } from "@madrasha/shared-ui/src/i18n";

/** Dashboard "important links" shown on every institution's dashboard. */
export const importantLinksText = defineBilingualText({
  bn: {
    title: "গুরুত্বপূর্ণ লিংক",
    subtitle: 'এখানে যোগ করা লিংকগুলো প্রতিটি প্রতিষ্ঠানের ড্যাশবোর্ডে "গুরুত্বপূর্ণ লিংক" কার্ডে দেখা যায়',
    loadFailed: "লিংক লোড করা যায়নি",
    labelUrlRequired: "লেবেল ও লিংক (URL) দিন",
    created: "লিংক তৈরি হয়েছে",
    createFailed: "লিংক তৈরি করতে সমস্যা হয়েছে",
    updated: "লিংক আপডেট হয়েছে",
    updateFailed: "লিংক আপডেট করতে সমস্যা হয়েছে",
    statusFailed: "অবস্থা আপডেট করতে সমস্যা হয়েছে",
    deleted: "লিংক মুছে ফেলা হয়েছে",
    orderFailed: "ক্রম সংরক্ষণ করা যায়নি",
    addHeading: "নতুন লিংক যোগ করুন",
    label: "লেবেল",
    labelPlaceholder: "যেমন: বেফাকুল মাদারিসিল আরাবিয়া",
    subLabel: "সাব-লেবেল (ঐচ্ছিক)",
    subLabelPlaceholder: "যেমন: বাংলাদেশ",
    url: "লিংক (URL)",
    empty: "কোনো লিংক নেই",
    moveUp: "উপরে সরান",
    moveDown: "নিচে সরান",
    editTitle: (label: string) => `লিংক এডিট করুন — ${label}`,
    deleteTitle: "মুছে ফেলুন?",
    deleteMessage: (label: string) => `"${label}" লিংকটি মুছে ফেলতে চান?`,
  },
  en: {
    title: "Important Links",
    subtitle: 'Links added here appear in the "Important Links" card on every institution\'s dashboard',
    loadFailed: "Could not load links",
    labelUrlRequired: "Enter a label and link (URL)",
    created: "Link created",
    createFailed: "Could not create the link",
    updated: "Link updated",
    updateFailed: "Could not update the link",
    statusFailed: "Could not update the status",
    deleted: "Link deleted",
    orderFailed: "Could not save the order",
    addHeading: "Add a new link",
    label: "Label",
    labelPlaceholder: "e.g. Education Board",
    subLabel: "Sub-label (optional)",
    subLabelPlaceholder: "e.g. Bangladesh",
    url: "Link (URL)",
    empty: "No links yet",
    moveUp: "Move up",
    moveDown: "Move down",
    editTitle: (label) => `Edit link — ${label}`,
    deleteTitle: "Delete?",
    deleteMessage: (label) => `Delete the link "${label}"?`,
  },
});
