import { defineText } from "../../i18n";

/** Document designer editor chrome (toolbar, panels, modals). Printed
 * template content is data and lives in the templates themselves. */
export const designerText = defineText({
  bn: {
    // Document types (BackendDocumentType -> label)
    documentTypes: {
      ID_CARD: "আইডি কার্ড",
      ADMIT_CARD: "প্রবেশপত্র",
      CERTIFICATE: "সনদ",
      CLEARANCE_CERTIFICATE: "ছাড়পত্র",
      TESTIMONIAL: "প্রত্যয়ন পত্র",
      MARKSHEET: "মার্কশিট",
      FEE_RECEIPT: "ফি রশিদ",
      SALARY_SLIP: "বেতন স্লিপ",
      BOOK_LABEL: "পুরস্কার বই-লেবেল",
    } as Record<string, string>,
    // Field-binding labels (binding keys never change)
    fields: {
      student_name: "{{student}}র নাম",
      father_name: "পিতার নাম",
      mother_name: "মাতার নাম",
      image: "{{student}}র ছবি",
      roll: "রোল নং",
      registration_no: "রেজিস্ট্রেশন নং",
      class_name: "{{class}}",
      division_name: "{{division}}",
      academic_year: "{{session}}",
      guardian_phone: "অভিভাবকের মোবাইল",
      id_issue_date: "কার্ড ইস্যুর তারিখ",
      id_expiry_date: "কার্ডের মেয়াদ শেষ",
      principal_title: "{{head}}-এর পদবি",
      id_lost_return: "হারিয়ে গেলে ফেরতের ঠিকানা",
      principal_signature: "{{head}}-এর স্বাক্ষর",
      exam_name: "পরীক্ষার নাম",
      exam_year: "পরীক্ষার বছর",
      rank_label: "মেধাক্রম (১ম/২য়/৩য়...)",
      rank_no: "মেধাক্রম (সংখ্যা)",
      class_info: "{{class}} ({{division}}) • রোল",
      madrasa_grade: "{{institution}} গ্রেড",
      exam_label: "পরীক্ষা ও বছর",
    } as Record<string, string>,
    // Layer types
    layerTypes: {
      text: "টেক্সট",
      image: "ছবি",
      photo: "ছবি (ডাইনামিক)",
      qrcode: "কিউআর কোড",
      barcode: "বারকোড",
      logo: "লোগো",
      signature: "স্বাক্ষর",
      shape: "শেপ",
    } as Record<string, string>,
    customSize: "কাস্টম",
    // Toolbar
    templateName: "টেমপ্লেটের নাম",
    zoomIn: "জুম ইন",
    zoomOut: "জুম আউট",
    pageSize: "পেজ সাইজ",
    portrait: "উলম্ব (Portrait)",
    landscape: "অনুভূমিক (Landscape)",
    widthMm: "প্রস্থ (mm)",
    heightMm: "উচ্চতা (mm)",
    bgUploadFailed: "ব্যাকগ্রাউন্ড ছবি আপলোড করা যায়নি, আবার চেষ্টা করুন",
    uploading: "আপলোড হচ্ছে...",
    uploadBackground: "ব্যাকগ্রাউন্ড আপলোড",
    removeBackground: "ব্যাকগ্রাউন্ড সরান",
    backgroundColor: "ব্যাকগ্রাউন্ড রং",
    savingDraft: "সেভ হচ্ছে...",
    saveDraft: "খসড়া সেভ করুন",
    publishing: "প্রকাশ হচ্ছে...",
    published: "প্রকাশিত",
    republish: "পুনঃপ্রকাশ করুন",
    publish: "প্রকাশ করুন",
    // Layer panel
    empty: "(খালি)",
    fieldSummary: (field: string) => `ফিল্ড: ${field}`,
    addElement: "এলিমেন্ট যোগ করুন",
    layers: (n: string) => `লেয়ার (${n})`,
    noLayers: "কোনো লেয়ার নেই",
    bringToFront: "সবচেয়ে সামনে আনুন",
    bringForward: "এক ধাপ সামনে",
    sendBackward: "এক ধাপ পেছনে",
    sendToBack: "সবচেয়ে পেছনে পাঠান",
    show: "দেখান",
    hide: "লুকান",
    unlock: "আনলক করুন",
    lock: "লক করুন",
    duplicate: "ডুপ্লিকেট",
    rotateLayer: "লেয়ার ঘোরান",
    // Property inspector
    noSelection: "কোনো এলিমেন্ট নির্বাচিত নেই — ক্যানভাসে কোনো এলিমেন্টে ক্লিক করুন",
    positionSize: "অবস্থান ও আকার",
    width: "প্রস্থ",
    height: "উচ্চতা",
    rotation: "ঘূর্ণন (°)",
    text: "টেক্সট",
    bindField: "ফিল্ড বাইন্ড করুন",
    selectOption: "— নির্বাচন করুন —",
    textContent: "লেখা (স্ট্যাটিক অথবা {{ফিল্ড}} সহ)",
    font: "ফন্ট",
    fontKalpurush: "কালপুরুষ (Kalpurush)",
    fontHind: "হিন্দ শিলিগুড়ি (Hind Siliguri)",
    fontSize: "ফন্ট সাইজ",
    color: "রং",
    bold: "বোল্ড",
    image: "ছবি",
    staticImage: "— স্ট্যাটিক ছবি —",
    uploadImage: "ছবি আপলোড করুন",
    lockAspect: "আকার পরিবর্তনের সময় অনুপাত ঠিক রাখুন (ছবি গোল হয়ে যাবে)",
    border: "বর্ডার",
    widthPx: "প্রস্থ (px)",
    removeBorder: "বর্ডার মুছুন",
    encodeField: "কোন ফিল্ডের মান এনকোড হবে",
    shape: "শেপ",
    shapeType: "ধরন",
    rectangle: "আয়তক্ষেত্র",
    circle: "বৃত্ত",
    line: "রেখা",
    fillColor: "ফিল রং",
    visible: "দৃশ্যমান",
    // Create template modal
    createTemplateTitle: "নতুন টেমপ্লেট তৈরি করুন",
    templateNamePlaceholder: "যেমন: হিফজ {{division}}ের আইডি কার্ড",
    createHint: "নাম দিয়ে \"তৈরি করুন\" চাপলে খালি ডিজাইনার খুলবে — সেখানে ব্যাকগ্রাউন্ড, ফিল্ড ও লেআউট সাজানো যাবে।",
    creating: "তৈরি হচ্ছে...",
    // Demo data modal
    demoDataTitle: "ডেমো ডেটা এডিট করুন",
    demoDataHint: "এখানে যা বদলাবেন তা শুধু এই ডিজাইনারের প্রিভিউতে দেখাবে — কোনো প্রকৃত তথ্য পরিবর্তিত বা সংরক্ষিত হবে না।",
    resetDemo: "মূল ডেটায় ফিরিয়ে নিন",
  },
  en: {
    documentTypes: {
      ID_CARD: "ID Card",
      ADMIT_CARD: "Admit Card",
      CERTIFICATE: "Certificate",
      CLEARANCE_CERTIFICATE: "Transfer Certificate",
      TESTIMONIAL: "Testimonial",
      MARKSHEET: "Marksheet",
      FEE_RECEIPT: "Fee Receipt",
      SALARY_SLIP: "Salary Slip",
      BOOK_LABEL: "Prize Book Label",
    },
    fields: {
      student_name: "{{student}} Name",
      father_name: "Father's Name",
      mother_name: "Mother's Name",
      image: "{{student}} Photo",
      roll: "Roll No.",
      registration_no: "Registration No.",
      class_name: "{{class}}",
      division_name: "{{division}}",
      academic_year: "{{session}}",
      guardian_phone: "Guardian's Mobile",
      id_issue_date: "Card Issue Date",
      id_expiry_date: "Card Expiry Date",
      principal_title: "{{head}}'s Title",
      id_lost_return: "Return Address If Lost",
      principal_signature: "{{head}}'s Signature",
      exam_name: "Exam Name",
      exam_year: "Exam Year",
      rank_label: "Merit Position (1st/2nd/3rd...)",
      rank_no: "Merit Position (number)",
      class_info: "{{class}} ({{division}}) • Roll",
      madrasa_grade: "{{institution}} Grade",
      exam_label: "Exam & Year",
    },
    layerTypes: {
      text: "Text",
      image: "Image",
      photo: "Photo (dynamic)",
      qrcode: "QR Code",
      barcode: "Barcode",
      logo: "Logo",
      signature: "Signature",
      shape: "Shape",
    },
    customSize: "Custom",
    templateName: "Template name",
    zoomIn: "Zoom in",
    zoomOut: "Zoom out",
    pageSize: "Page size",
    portrait: "Portrait",
    landscape: "Landscape",
    widthMm: "Width (mm)",
    heightMm: "Height (mm)",
    bgUploadFailed: "Could not upload the background image, please try again",
    uploading: "Uploading...",
    uploadBackground: "Upload background",
    removeBackground: "Remove background",
    backgroundColor: "Background color",
    savingDraft: "Saving...",
    saveDraft: "Save draft",
    publishing: "Publishing...",
    published: "Published",
    republish: "Republish",
    publish: "Publish",
    empty: "(empty)",
    fieldSummary: (field) => `Field: ${field}`,
    addElement: "Add element",
    layers: (n) => `Layers (${n})`,
    noLayers: "No layers",
    bringToFront: "Bring to front",
    bringForward: "Bring forward",
    sendBackward: "Send backward",
    sendToBack: "Send to back",
    show: "Show",
    hide: "Hide",
    unlock: "Unlock",
    lock: "Lock",
    duplicate: "Duplicate",
    rotateLayer: "Rotate layer",
    noSelection: "No element selected — click an element on the canvas",
    positionSize: "Position & size",
    width: "Width",
    height: "Height",
    rotation: "Rotation (°)",
    text: "Text",
    bindField: "Bind field",
    selectOption: "— Select —",
    textContent: "Text (static or with {{field}})",
    font: "Font",
    fontKalpurush: "Kalpurush",
    fontHind: "Hind Siliguri",
    fontSize: "Font size",
    color: "Color",
    bold: "Bold",
    image: "Image",
    staticImage: "— Static image —",
    uploadImage: "Upload image",
    lockAspect: "Keep aspect ratio while resizing (image becomes round)",
    border: "Border",
    widthPx: "Width (px)",
    removeBorder: "Remove border",
    encodeField: "Field value to encode",
    shape: "Shape",
    shapeType: "Type",
    rectangle: "Rectangle",
    circle: "Circle",
    line: "Line",
    fillColor: "Fill color",
    visible: "Visible",
    createTemplateTitle: "Create new template",
    templateNamePlaceholder: "e.g. Hifz {{division}} ID card",
    createHint: "Enter a name and press \"Create\" to open a blank designer — arrange the background, fields and layout there.",
    creating: "Creating...",
    demoDataTitle: "Edit demo data",
    demoDataHint: "Changes here only affect this designer's preview — no real data is changed or saved.",
    resetDemo: "Revert to original data",
  },
  ar: {
    documentTypes: {
      ID_CARD: "بطاقة الهوية",
      ADMIT_CARD: "بطاقة الدخول",
      CERTIFICATE: "الشهادة",
      CLEARANCE_CERTIFICATE: "شهادة النقل",
      TESTIMONIAL: "شهادة حسن السيرة",
      MARKSHEET: "كشف الدرجات",
      FEE_RECEIPT: "إيصال الرسوم",
      SALARY_SLIP: "قسيمة الراتب",
      BOOK_LABEL: "ملصق كتاب الجائزة",
    },
    fields: {
      student_name: "اسم {{student}}",
      father_name: "اسم الأب",
      mother_name: "اسم الأم",
      image: "صورة {{student}}",
      roll: "رقم الجلوس",
      registration_no: "رقم التسجيل",
      class_name: "{{class}}",
      division_name: "{{division}}",
      academic_year: "{{session}}",
      guardian_phone: "جوال ولي الأمر",
      id_issue_date: "تاريخ إصدار البطاقة",
      id_expiry_date: "تاريخ انتهاء البطاقة",
      principal_title: "لقب {{head}}",
      id_lost_return: "عنوان الإرجاع عند الفقدان",
      principal_signature: "توقيع {{head}}",
      exam_name: "اسم الاختبار",
      exam_year: "سنة الاختبار",
      rank_label: "الترتيب (الأول/الثاني/الثالث...)",
      rank_no: "الترتيب (رقم)",
      class_info: "{{class}} ({{division}}) • رقم الجلوس",
      madrasa_grade: "تقدير {{institution}}",
      exam_label: "الاختبار والسنة",
    },
    layerTypes: {
      text: "نص",
      image: "صورة",
      photo: "صورة (ديناميكية)",
      qrcode: "رمز QR",
      barcode: "باركود",
      logo: "شعار",
      signature: "توقيع",
      shape: "شكل",
    },
    customSize: "مخصص",
    templateName: "اسم القالب",
    zoomIn: "تكبير",
    zoomOut: "تصغير",
    pageSize: "حجم الصفحة",
    portrait: "عمودي",
    landscape: "أفقي",
    widthMm: "العرض (مم)",
    heightMm: "الارتفاع (مم)",
    bgUploadFailed: "تعذّر رفع صورة الخلفية، يرجى المحاولة مرة أخرى",
    uploading: "جارٍ الرفع...",
    uploadBackground: "رفع الخلفية",
    removeBackground: "إزالة الخلفية",
    backgroundColor: "لون الخلفية",
    savingDraft: "جارٍ الحفظ...",
    saveDraft: "حفظ المسودة",
    publishing: "جارٍ النشر...",
    published: "منشور",
    republish: "إعادة النشر",
    publish: "نشر",
    empty: "(فارغ)",
    fieldSummary: (field) => `الحقل: ${field}`,
    addElement: "إضافة عنصر",
    layers: (n) => `الطبقات (${n})`,
    noLayers: "لا توجد طبقات",
    bringToFront: "إحضار إلى الأمام",
    bringForward: "تقديم خطوة",
    sendBackward: "إرجاع خطوة",
    sendToBack: "إرسال إلى الخلف",
    show: "إظهار",
    hide: "إخفاء",
    unlock: "إلغاء القفل",
    lock: "قفل",
    duplicate: "تكرار",
    rotateLayer: "تدوير الطبقة",
    noSelection: "لم يتم تحديد أي عنصر — انقر على عنصر في لوحة التصميم",
    positionSize: "الموضع والحجم",
    width: "العرض",
    height: "الارتفاع",
    rotation: "الدوران (°)",
    text: "نص",
    bindField: "ربط حقل",
    selectOption: "— اختر —",
    textContent: "النص (ثابت أو مع {{حقل}})",
    font: "الخط",
    fontKalpurush: "كالبوروش (Kalpurush)",
    fontHind: "هند سيليغوري (Hind Siliguri)",
    fontSize: "حجم الخط",
    color: "اللون",
    bold: "عريض",
    image: "صورة",
    staticImage: "— صورة ثابتة —",
    uploadImage: "رفع صورة",
    lockAspect: "الحفاظ على النسبة عند تغيير الحجم (تصبح الصورة دائرية)",
    border: "الإطار",
    widthPx: "العرض (px)",
    removeBorder: "إزالة الإطار",
    encodeField: "الحقل المراد ترميز قيمته",
    shape: "شكل",
    shapeType: "النوع",
    rectangle: "مستطيل",
    circle: "دائرة",
    line: "خط",
    fillColor: "لون التعبئة",
    visible: "مرئي",
    createTemplateTitle: "إنشاء قالب جديد",
    templateNamePlaceholder: "مثال: بطاقة هوية {{division}} التحفيظ",
    createHint: "أدخل الاسم واضغط \"إنشاء\" لفتح مصمم فارغ — يمكنك هناك ترتيب الخلفية والحقول والتخطيط.",
    creating: "جارٍ الإنشاء...",
    demoDataTitle: "تعديل البيانات التجريبية",
    demoDataHint: "التغييرات هنا تظهر في معاينة هذا المصمم فقط — لن تُغيَّر أو تُحفظ أي بيانات حقيقية.",
    resetDemo: "الرجوع إلى البيانات الأصلية",
  },
});
