import { defineText } from "@madrasha/shared-ui/src/i18n";

export const trashText = defineText({
  bn: {
    tabs: {
      students: "{{student}}",
      teachers: "{{teacher}}",
      exams: "পরীক্ষা",
      divisions: "{{division}}",
      classes: "{{class}}",
      books: "{{subject}}",
      results: "রেজাল্ট",
    },
    deletesToday: "আজই মুছে যাবে",
    daysLeft: (n: string) => `বাকি আছে: ${n} দিন`,
    loadFailed: "ট্র্যাশ লোড করা যায়নি",
    restoreTitle: "ফিরিয়ে আনবেন?",
    restoreMessage: (name: string) => `"${name}" ট্র্যাশ থেকে ফিরিয়ে আনতে চান? এটি আগের মতোই সক্রিয় হয়ে যাবে।`,
    restore: "ফিরিয়ে আনুন",
    restored: "ফিরিয়ে আনা হয়েছে",
    restoreFailed: "ফিরিয়ে আনা যায়নি",
    deleteTitle: "স্থায়ীভাবে মুছবেন?",
    deleteMessage: (name: string) =>
      `"${name}" স্থায়ীভাবে মুছে ফেলতে চান? এই কাজটি আর ফিরিয়ে আনা যাবে না — সম্পর্কিত সব তথ্য (রেজাল্ট, মার্কস ইত্যাদি) একসাথে মুছে যাবে।`,
    deleteForever: "স্থায়ীভাবে মুছে ফেলুন",
    deletedForever: "স্থায়ীভাবে মুছে ফেলা হয়েছে",
    deleteFailed: "মুছে ফেলা যায়নি",
    bulkRestoreMessage: (n: string) => `নির্বাচিত ${n}টি আইটেম ট্র্যাশ থেকে ফিরিয়ে আনতে চান? এগুলো আগের মতোই সক্রিয় হয়ে যাবে।`,
    bulkRestorePartial: (ok: string, fail: string) => `${ok}টি ফিরিয়ে আনা হয়েছে, ${fail}টি ব্যর্থ হয়েছে`,
    bulkDeleteMessage: (n: string) =>
      `নির্বাচিত ${n}টি আইটেম স্থায়ীভাবে মুছে ফেলতে চান? এই কাজটি আর ফিরিয়ে আনা যাবে না — সম্পর্কিত সব তথ্য (রেজাল্ট, মার্কস ইত্যাদি) একসাথে মুছে যাবে।`,
    bulkDeletePartial: (ok: string, fail: string) => `${ok}টি মুছে ফেলা হয়েছে, ${fail}টি ব্যর্থ হয়েছে`,
    title: "ট্র্যাশ",
    subtitle:
      "মুছে ফেলা {{student}}, {{teacher}}, পরীক্ষা, {{division}}, {{class}}, {{subject}} ও রেজাল্ট এখানে ৭ দিন থাকে — এর মধ্যে ফিরিয়ে আনতে না পারলে স্বয়ংক্রিয়ভাবে স্থায়ীভাবে মুছে যাবে।",
    selectedCount: (n: string) => `${n}টি নির্বাচিত`,
    restoreSelected: "নির্বাচিতগুলো ফিরিয়ে আনুন",
    deleteSelected: "নির্বাচিতগুলো স্থায়ী মুছুন",
    empty: "ট্র্যাশ খালি আছে",
    none: "নেই",
    roll: "রোল",
    class: "{{class}}",
    regNo: "রেজি. নং",
    phone: "ফোন",
    year: "সাল",
    division: "{{division}}",
    state: "অবস্থা",
    deletedAt: "মুছে ফেলা হয়েছে",
    validity: "মেয়াদ",
    permanentDelete: "স্থায়ী মুছুন",
  },
  en: {
    tabs: {
      students: "{{student}}s",
      teachers: "{{teacher}}s",
      exams: "Exams",
      divisions: "{{division}}s",
      classes: "{{class}}es",
      books: "{{subject}}s",
      results: "Results",
    },
    deletesToday: "Deleted today",
    daysLeft: (n) => `${n} days left`,
    loadFailed: "Could not load the trash",
    restoreTitle: "Restore?",
    restoreMessage: (name) => `Restore "${name}" from the trash? It will become active again as before.`,
    restore: "Restore",
    restored: "Restored",
    restoreFailed: "Could not restore",
    deleteTitle: "Delete permanently?",
    deleteMessage: (name) =>
      `Permanently delete "${name}"? This cannot be undone — all related data (results, marks, etc.) will be deleted too.`,
    deleteForever: "Delete permanently",
    deletedForever: "Deleted permanently",
    deleteFailed: "Could not delete",
    bulkRestoreMessage: (n) => `Restore ${n} selected items from the trash? They will become active again as before.`,
    bulkRestorePartial: (ok, fail) => `${ok} restored, ${fail} failed`,
    bulkDeleteMessage: (n) =>
      `Permanently delete ${n} selected items? This cannot be undone — all related data (results, marks, etc.) will be deleted too.`,
    bulkDeletePartial: (ok, fail) => `${ok} deleted, ${fail} failed`,
    title: "Trash",
    subtitle:
      "Deleted {{student}}s, {{teacher}}s, exams, {{division}}s, {{class}}es, {{subject}}s and results stay here for 7 days — if not restored by then, they are permanently deleted automatically.",
    selectedCount: (n) => `${n} selected`,
    restoreSelected: "Restore selected",
    deleteSelected: "Delete selected permanently",
    empty: "The trash is empty",
    none: "None",
    roll: "Roll",
    class: "{{class}}",
    regNo: "Reg. No.",
    phone: "Phone",
    year: "Year",
    division: "{{division}}",
    state: "Status",
    deletedAt: "Deleted on",
    validity: "Expires",
    permanentDelete: "Delete permanently",
  },
});
