import { defineText } from "@madrasha/shared-ui/src/i18n";

/** UI text for exam operations: rooms, seat plan, attendance, invigilators. */
export const examOpsText = defineText({
  bn: {
    // shared
    selectExam: "পরীক্ষা নির্বাচন করুন",
    selectDivision: "{{division}} নির্বাচন করুন",
    selectClass: "{{class}} নির্বাচন করুন",
    selectSchedule: "সময়সূচি ({{subject}}/তারিখ) নির্বাচন করুন",
    saveFailed: "সংরক্ষণ করতে সমস্যা হয়েছে",
    updateFailed: "আপডেট করতে সমস্যা হয়েছে",
    deleteFailed: "মুছতে সমস্যা হয়েছে",
    genericError: "সমস্যা হয়েছে",
    // invigilator
    pickInvigilator: "একজন {{teacher}}/স্টাফ নির্বাচন করুন",
    invigilatorAssigned: "পরিদর্শক নিয়োগ করা হয়েছে",
    assignFailed: "নিয়োগ করতে সমস্যা হয়েছে",
    removeFailed: "সরাতে সমস্যা হয়েছে",
    invigilators: "পরিদর্শক নিয়োগ",
    teacher: "{{teacher}}",
    staff: "স্টাফ",
    chief: "প্রধান",
    assistant: "সহকারী",
    remove: "সরান",
    assign: "নিয়োগ করুন",
    // rooms
    roomNameCodeRequired: "রুমের নাম ও কোড দিন",
    roomUpdated: "রুম আপডেট করা হয়েছে",
    roomAdded: "রুম যোগ করা হয়েছে",
    roomDeactivated: "রুম নিষ্ক্রিয় করা হয়েছে",
    roomsTitle: "রুম / হল ব্যবস্থাপনা",
    roomsSubtitle: "পরীক্ষার জন্য রুম/হল যোগ ও ব্যবস্থাপনা করুন",
    editRoom: "রুম সম্পাদনা করুন",
    newRoom: "নতুন রুম যোগ করুন",
    roomName: "রুমের নাম",
    code: "কোড",
    capacity: "ধারণক্ষমতা",
    floorOptional: "ফ্লোর (ঐচ্ছিক)",
    locationOptional: "অবস্থান (ঐচ্ছিক)",
    noteOptional: "নোট (ঐচ্ছিক)",
    noRooms: "এখনো কোনো রুম যোগ করা হয়নি",
    capacityN: (n: string) => `· ধারণক্ষমতা ${n}`,
    inactiveParen: "(নিষ্ক্রিয়)",
    editShort: "সম্পাদনা",
    deactivate: "নিষ্ক্রিয় করুন",
    activate: "সক্রিয় করুন",
    // attendance
    noChanges: "কোনো পরিবর্তন নেই",
    attendanceSaved: "হাজিরা সংরক্ষণ করা হয়েছে",
    allMarkedPresent: "সবাইকে উপস্থিত হিসেবে চিহ্নিত করা হয়েছে",
    confirmUnlock: "হাজিরা আনলক করতে চান? এরপর আবার সম্পাদনা করা যাবে।",
    confirmLock: "হাজিরা লক করতে চান? লক করার পর আর সম্পাদনা করা যাবে না, শুধু আনলক করলে হবে।",
    unlocked: "আনলক করা হয়েছে",
    locked: "লক করা হয়েছে",
    attendanceTitle: "পরীক্ষার হাজিরা",
    attendanceSubtitle: "প্রতিটি পরীক্ষার সিটিং-এর জন্য পৃথক হাজিরা নিন",
    searchNameRoll: "নাম/রোল দিয়ে খুঁজুন",
    studentList: "{{student}} তালিকা",
    lockedParen: "(লকড)",
    markAllPresent: "সবাইকে উপস্থিত করুন",
    unlock: "আনলক করুন",
    lock: "লক করুন",
    noCandidates: "এই সময়সূচির জন্য কোনো নিবন্ধিত পরীক্ষার্থী নেই",
    rollN: (n: string) => ` · রোল ${n}`,
    seatN: (n: string) => ` · আসন ${n}`,
    // seat plan
    strategySequential: "ক্রমিক",
    strategyRoll: "রোল অনুসারে",
    strategyAlternating: "পর্যায়ক্রমিক (মিশ্র)",
    strategyManual: "ম্যানুয়াল",
    listLoadFailed: "পরীক্ষা/{{division}}/রুমের তালিকা লোড করতে সমস্যা হয়েছে",
    pickScheduleRoom: "পরীক্ষার সময়সূচি ও অন্তত একটি রুম নির্বাচন করুন",
    seatsAllocated: (n: string) => `${n}টি আসন বণ্টন করা হয়েছে`,
    allocateFailed: "আসন বণ্টন করতে সমস্যা হয়েছে",
    allocationCleared: "আসন বণ্টন মুছে ফেলা হয়েছে",
    seatUpdated: "আসন আপডেট করা হয়েছে",
    seatPlanTitle: "সিট প্ল্যান",
    seatPlanSubtitle: "পরীক্ষার আসন বিন্যাস স্বয়ংক্রিয়ভাবে বণ্টন করুন বা ম্যানুয়ালি সমন্বয় করুন",
    autoAllocation: "স্বয়ংক্রিয় বণ্টন",
    keepManual: "ম্যানুয়াল পরিবর্তনগুলো রাখুন",
    autoAllocate: "স্বয়ংক্রিয় বণ্টন করুন",
    clearAll: "সব মুছুন",
    currentLayout: "বর্তমান আসন বিন্যাস",
    noAllocation: "এখনো কোনো আসন বণ্টন করা হয়নি",
    roomN: (n: string) => `রুম #${n}`,
    seatLabel: (n: string) => `আসন ${n}`,
    candidateN: (n: string) => `প্রার্থী #${n}`,
    newSeatPrompt: "নতুন আসন নম্বর দিন",
    change: "পরিবর্তন",
  },
  en: {
    selectExam: "Select exam",
    selectDivision: "Select {{division}}",
    selectClass: "Select {{class}}",
    selectSchedule: "Select schedule ({{subject}}/date)",
    saveFailed: "Could not save",
    updateFailed: "Could not update",
    deleteFailed: "Could not delete",
    genericError: "Something went wrong",
    pickInvigilator: "Select a {{teacher}}/staff member",
    invigilatorAssigned: "Invigilator assigned",
    assignFailed: "Could not assign",
    removeFailed: "Could not remove",
    invigilators: "Invigilator Assignment",
    teacher: "{{teacher}}",
    staff: "Staff",
    chief: "Chief",
    assistant: "Assistant",
    remove: "Remove",
    assign: "Assign",
    roomNameCodeRequired: "Enter the room name and code",
    roomUpdated: "Room updated",
    roomAdded: "Room added",
    roomDeactivated: "Room deactivated",
    roomsTitle: "Room / Hall Management",
    roomsSubtitle: "Add and manage rooms/halls for exams",
    editRoom: "Edit room",
    newRoom: "Add new room",
    roomName: "Room name",
    code: "Code",
    capacity: "Capacity",
    floorOptional: "Floor (optional)",
    locationOptional: "Location (optional)",
    noteOptional: "Note (optional)",
    noRooms: "No rooms added yet",
    capacityN: (n) => `· Capacity ${n}`,
    inactiveParen: "(inactive)",
    editShort: "Edit",
    deactivate: "Deactivate",
    activate: "Activate",
    noChanges: "No changes",
    attendanceSaved: "Attendance saved",
    allMarkedPresent: "Everyone marked present",
    confirmUnlock: "Unlock attendance? It can be edited again afterwards.",
    confirmLock: "Lock attendance? Once locked it cannot be edited until unlocked.",
    unlocked: "Unlocked",
    locked: "Locked",
    attendanceTitle: "Exam Attendance",
    attendanceSubtitle: "Take separate attendance for each exam sitting",
    searchNameRoll: "Search by name/roll",
    studentList: "{{student}} List",
    lockedParen: "(locked)",
    markAllPresent: "Mark all present",
    unlock: "Unlock",
    lock: "Lock",
    noCandidates: "No registered candidates for this schedule",
    rollN: (n) => ` · Roll ${n}`,
    seatN: (n) => ` · Seat ${n}`,
    strategySequential: "Sequential",
    strategyRoll: "By roll",
    strategyAlternating: "Alternating (mixed)",
    strategyManual: "Manual",
    listLoadFailed: "Could not load the exam/{{division}}/room lists",
    pickScheduleRoom: "Select an exam schedule and at least one room",
    seatsAllocated: (n) => `${n} seats allocated`,
    allocateFailed: "Could not allocate seats",
    allocationCleared: "Seat allocation cleared",
    seatUpdated: "Seat updated",
    seatPlanTitle: "Seat Plan",
    seatPlanSubtitle: "Allocate exam seating automatically or adjust it manually",
    autoAllocation: "Automatic allocation",
    keepManual: "Keep manual changes",
    autoAllocate: "Allocate automatically",
    clearAll: "Clear all",
    currentLayout: "Current seating",
    noAllocation: "No seats allocated yet",
    roomN: (n) => `Room #${n}`,
    seatLabel: (n) => `Seat ${n}`,
    candidateN: (n) => `Candidate #${n}`,
    newSeatPrompt: "Enter the new seat number",
    change: "Change",
  },
  ar: {
    selectExam: "اختر الامتحان",
    selectDivision: "اختر {{division}}",
    selectClass: "اختر {{class}}",
    selectSchedule: "اختر الموعد ({{subject}}/التاريخ)",
    saveFailed: "تعذّر الحفظ",
    updateFailed: "تعذّر التحديث",
    deleteFailed: "تعذّر الحذف",
    genericError: "حدث خطأ",
    pickInvigilator: "اختر {{teacher}} أو موظفًا",
    invigilatorAssigned: "تم تعيين المراقب",
    assignFailed: "تعذّر التعيين",
    removeFailed: "تعذّرت الإزالة",
    invigilators: "تعيين المراقبين",
    teacher: "{{teacher}}",
    staff: "موظف",
    chief: "رئيس",
    assistant: "مساعد",
    remove: "إزالة",
    assign: "تعيين",
    roomNameCodeRequired: "أدخل اسم القاعة ورمزها",
    roomUpdated: "تم تحديث القاعة",
    roomAdded: "تمت إضافة القاعة",
    roomDeactivated: "تم تعطيل القاعة",
    roomsTitle: "إدارة القاعات",
    roomsSubtitle: "إضافة قاعات الامتحان وإدارتها",
    editRoom: "تعديل القاعة",
    newRoom: "إضافة قاعة جديدة",
    roomName: "اسم القاعة",
    code: "الرمز",
    capacity: "السعة",
    floorOptional: "الطابق (اختياري)",
    locationOptional: "الموقع (اختياري)",
    noteOptional: "ملاحظة (اختياري)",
    noRooms: "لم تُضف أي قاعة بعد",
    capacityN: (n) => `· السعة ${n}`,
    inactiveParen: "(معطّلة)",
    editShort: "تعديل",
    deactivate: "تعطيل",
    activate: "تفعيل",
    noChanges: "لا توجد تغييرات",
    attendanceSaved: "تم حفظ الحضور",
    allMarkedPresent: "تم تسجيل الجميع حاضرين",
    confirmUnlock: "فتح قفل الحضور؟ يمكن تعديله بعد ذلك.",
    confirmLock: "قفل الحضور؟ لا يمكن تعديله بعد القفل إلا بفتحه.",
    unlocked: "تم فتح القفل",
    locked: "تم القفل",
    attendanceTitle: "حضور الامتحان",
    attendanceSubtitle: "سجّل حضورًا منفصلًا لكل جلسة امتحان",
    searchNameRoll: "ابحث بالاسم/رقم الجلوس",
    studentList: "قائمة الطلاب",
    lockedParen: "(مقفل)",
    markAllPresent: "تسجيل الجميع حاضرين",
    unlock: "فتح القفل",
    lock: "قفل",
    noCandidates: "لا يوجد ممتحنون مسجلون لهذا الموعد",
    rollN: (n) => ` · رقم الجلوس ${n}`,
    seatN: (n) => ` · المقعد ${n}`,
    strategySequential: "تسلسلي",
    strategyRoll: "حسب رقم الجلوس",
    strategyAlternating: "متناوب (مختلط)",
    strategyManual: "يدوي",
    listLoadFailed: "تعذّر تحميل قوائم الامتحانات/المراحل/القاعات",
    pickScheduleRoom: "اختر موعد الامتحان وقاعة واحدة على الأقل",
    seatsAllocated: (n) => `تم توزيع ${n} مقعدًا`,
    allocateFailed: "تعذّر توزيع المقاعد",
    allocationCleared: "تم حذف توزيع المقاعد",
    seatUpdated: "تم تحديث المقعد",
    seatPlanTitle: "خطة الجلوس",
    seatPlanSubtitle: "وزّع مقاعد الامتحان تلقائيًا أو عدّلها يدويًا",
    autoAllocation: "التوزيع التلقائي",
    keepManual: "الإبقاء على التعديلات اليدوية",
    autoAllocate: "توزيع تلقائي",
    clearAll: "حذف الكل",
    currentLayout: "توزيع المقاعد الحالي",
    noAllocation: "لم تُوزَّع أي مقاعد بعد",
    roomN: (n) => `القاعة #${n}`,
    seatLabel: (n) => `المقعد ${n}`,
    candidateN: (n) => `الممتحن #${n}`,
    newSeatPrompt: "أدخل رقم المقعد الجديد",
    change: "تغيير",
  },
});
