import { defineText } from "@madrasha/shared-ui/src/i18n";

export const rolesText = defineText({
  bn: {
    other: "অন্যান্য",
    enterRoleName: "রোলের নাম দিন",
    roleCreated: "রোল তৈরি হয়েছে",
    roleCreateFailed: "রোল তৈরি করতে সমস্যা হয়েছে",
    permissionsSaved: "পারমিশন সংরক্ষণ করা হয়েছে",
    saveFailed: "সংরক্ষণ করতে সমস্যা হয়েছে",
    deleteTitle: "রোল ডিলিট করুন",
    deleteMessage: (name: string) => `"${name}" রোলটি স্থায়ীভাবে মুছে ফেলতে চান?`,
    deleteConfirm: "ডিলিট করুন",
    roleDeleted: "রোল মুছে ফেলা হয়েছে",
    title: "রোল ও পারমিশন",
    subtitle: "নতুন রোল তৈরি করুন এবং প্রতিটা রোলের জন্য কোন কোন মডিউলে অ্যাক্সেস থাকবে তা নির্ধারণ করুন",
    createRole: "নতুন রোল তৈরি করুন",
    roleNamePlaceholder: "রোলের নাম (যেমন: ক্লাস টিচার)",
    creating: "তৈরি হচ্ছে...",
    allRoles: "সব রোল",
    noRoles: "কোনো রোল নেই",
    defaultRole: "ডিফল্ট রোল",
    allPermissions: "সকল পারমিশন (সবসময়, পরিবর্তনযোগ্য নয়)",
    permissionCount: (n: string) => `${n} টি পারমিশন`,
    userCount: (n: string) => `${n} জন ইউজার`,
    academicAutoNote:
      "পরীক্ষা বিভাগের (পরীক্ষা, নম্বর, ফলাফল, রুটিন) সব পারমিশন এই রোল স্বয়ংক্রিয়ভাবে পায় — আলাদা করে দিতে হয় না। নিচের তালিকা শুধু অন্য বিভাগের অ্যাক্সেসের জন্য।",
    headAlwaysFull: "{{head}} সবসময় সম্পূর্ণ অ্যাক্সেস পাবেন — এটি পরিবর্তনযোগ্য নয়",
    setPermissions: "পারমিশন সেট করুন",
    cannotDeleteHasUsers: "এই রোলে ইউজার আছে বলে মুছা যাবে না",
    setPermissionsFor: (name: string) => `পারমিশন সেট করুন — ${name}`,
    fullModuleOn: "পুরো মডিউল চালু",
    partiallyOn: "আংশিক চালু",
    off: "বন্ধ",
    turnModuleOff: "পুরো মডিউলের সব পারমিশন বন্ধ করুন",
    turnModuleOn: "পুরো মডিউলের সব পারমিশন চালু করুন",
  },
  en: {
    other: "Other",
    enterRoleName: "Enter a role name",
    roleCreated: "Role created",
    roleCreateFailed: "Could not create the role",
    permissionsSaved: "Permissions saved",
    saveFailed: "Could not save",
    deleteTitle: "Delete role",
    deleteMessage: (name) => `Permanently delete the role "${name}"?`,
    deleteConfirm: "Delete",
    roleDeleted: "Role deleted",
    title: "Roles & Permissions",
    subtitle: "Create new roles and decide which modules each role can access",
    createRole: "Create new role",
    roleNamePlaceholder: "Role name (e.g. Class Teacher)",
    creating: "Creating...",
    allRoles: "All roles",
    noRoles: "No roles",
    defaultRole: "Default role",
    allPermissions: "All permissions (always, not editable)",
    permissionCount: (n) => `${n} permissions`,
    userCount: (n) => `${n} users`,
    academicAutoNote:
      "This role automatically gets every exam-department permission (exams, marks, results, routine) — no need to grant them separately. The list below is only for access to other departments.",
    headAlwaysFull: "The {{head}} always has full access — this cannot be changed",
    setPermissions: "Set permissions",
    cannotDeleteHasUsers: "Cannot delete because this role has users",
    setPermissionsFor: (name) => `Set permissions — ${name}`,
    fullModuleOn: "Whole module on",
    partiallyOn: "Partially on",
    off: "Off",
    turnModuleOff: "Turn off all permissions of this module",
    turnModuleOn: "Turn on all permissions of this module",
  },
});
