import { defineText } from "@madrasha/shared-ui/src/i18n";

export const examFeeTableText = defineText({
  bn: {
    other: "অন্যান্য",
    saveOrCancelFirst: (name: string) => `আগে "${name}" এর পরিবর্তন সংরক্ষণ বা বাতিল করুন`,
    invalidAmount: "সঠিক পরিমাণ লিখুন",
    savedWithInvoices: (name: string, n: string) => `"${name}" এর ফি সংরক্ষণ হয়েছে — ${n}টি ইনভয়েস তৈরি হয়েছে`,
    saved: (name: string) => `"${name}" এর ফি সংরক্ষণ হয়েছে`,
    saveFailed: "ফি সংরক্ষণ করা যায়নি",
    examOffCannotEnable: (name: string) =>
      `"${name}" পরীক্ষাটি বন্ধ আছে — {{academic}} পরীক্ষা চালু করলে তবেই ফি চালু করা যাবে`,
    unsavedFirst: "আগে অসংরক্ষিত ফি সংরক্ষণ বা বাতিল করুন",
    enableTitle: "পরীক্ষার ফি চালু করবেন?",
    disableTitle: "পরীক্ষার ফি বন্ধ করবেন?",
    enableMessage: (name: string) =>
      `"${name}" পরীক্ষার ফি চালু হবে: বিদ্যমান সব {{student}}র ইনভয়েস তৈরি হবে এবং অভিভাবকদের এসএমএস পাঠানো হবে।`,
    disableMessage: (name: string) =>
      `"${name}" পরীক্ষার ফি বন্ধ হবে — {{student}}দের যে ইনভয়েস এখনো পরিশোধ হয়নি সেগুলো বাতিল হয়ে যাবে। যেসব ইনভয়েসে টাকা জমা বা মওকুফ হয়েছে সেগুলো থাকবে। আবার চালু করলে ইনভয়েস নতুন করে তৈরি হবে।`,
    enable: "চালু করুন",
    disable: "বন্ধ করুন",
    enabledToast: (created: string, notified: string) =>
      `ফি চালু হয়েছে — ${created}টি ইনভয়েস তৈরি, ${notified} জন অভিভাবককে এসএমএস`,
    disabledToast: (name: string, removed: string) => `"${name}" পরীক্ষার ফি বন্ধ হয়েছে — ${removed}টি ইনভয়েস বাতিল`,
    keptSuffix: (kept: string) => `, টাকা জমা/মওকুফ থাকায় ${kept}টি রাখা হয়েছে`,
    enableFailed: "ফি চালু করা যায়নি",
    disableFailed: "ফি বন্ধ করা যায়নি",
    amount: "পরিমাণ",
    apply: "প্রয়োগ",
    clearTitle: (scope: string) => `${scope} পরিবর্তন মুছুন (আগের সংরক্ষিত ফি ফিরে আসবে)`,
    clearAria: (scope: string) => `${scope} পরিবর্তন মুছুন`,
    title: "পরীক্ষার ফি",
    summary: (exams: string, active: string) => `${exams}টি পরীক্ষা · ${active}টির ফি চালু`,
    manageLink: "পরীক্ষা ও {{division}} ব্যবস্থাপনা",
    noExams: "এখনো কোনো পরীক্ষা তৈরি করা হয়নি — পরীক্ষা তৈরি করলে এখানে তার ফি নির্ধারণ করা যাবে।",
    classesSet: (set: string, total: string) => ` · ${set}/${total} {{class}}র ফি নির্ধারিত`,
    editFee: (name: string) => `"${name}" এর ফি সম্পাদনা করুন`,
    lockedTitle: "{{academic}} পরীক্ষাটি বন্ধ রেখেছে — পরীক্ষা চালু হলে ফি চালু করা যাবে",
    examOff: "পরীক্ষা বন্ধ",
    feeOn: "ফি চালু",
    feeOff: "ফি বন্ধ",
    turnOff: "ফি বন্ধ করুন",
    turnOn: "ফি চালু করুন (অভিভাবকদের এসএমএস যাবে)",
    lockedNote: "{{academic}} পরীক্ষা চালু করলে ফি চালু করা যাবে — পরিমাণ আগেই ঠিক রাখতে পারেন।",
    legacyNote: (amount: string) =>
      `পুরনো নিয়মে এই পরীক্ষার ফি সব {{class}}র জন্য ৳${amount} হিসেবে বিল হয়ে গেছে, তাই {{class}}ভিত্তিক ফি বসানো যাবে না। এই ফি শুধু পরীক্ষার নিজের {{division}}ের {{student}}দের বিল হয়।`,
    noActiveClasses: "এই পরীক্ষার {{division}}ে কোনো সক্রিয় {{class}} নেই",
    countSuffix: (n: string) => `${n}টি`,
    divisionBulkLabel: (division: string) => `${division} {{division}}ের সব {{class}}র জন্য একই পরিমাণ`,
    divisionScope: (division: string) => `${division} {{division}}ের`,
    classFallback: (id: string) => `{{class}} #${id}`,
    invoicesFromFee: "এই ফি থেকে তৈরি ইনভয়েস",
    invoiceCount: (n: string) => `${n} ইনভয়েস`,
    notSet: "ফি নির্ধারণ করা নেই",
    feeAria: (cls: string) => `${cls} — ফি`,
    billedHint: "ইনভয়েস হয়ে গেছে — পরিমাণ বদলালে শুধু নতুন ইনভয়েসে প্রযোজ্য হবে",
    allBulkLabel: "সব {{class}}র জন্য একই পরিমাণ",
    allScope: "সব {{class}}র",
    cancelEditTitle: "সম্পাদনা বাতিল — আগের সংরক্ষিত ফি থাকবে",
    saveCount: (n: string) => `সংরক্ষণ (${n})`,
    save: "সংরক্ষণ",
  },
  en: {
    other: "Other",
    saveOrCancelFirst: (name) => `Save or discard the changes to "${name}" first`,
    invalidAmount: "Enter a valid amount",
    savedWithInvoices: (name, n) => `Fees for "${name}" saved — ${n} invoices created`,
    saved: (name) => `Fees for "${name}" saved`,
    saveFailed: "Could not save the fee",
    examOffCannotEnable: (name) => `The exam "${name}" is off — the fee can be enabled only after {{academic}} turns the exam on`,
    unsavedFirst: "Save or discard the unsaved fees first",
    enableTitle: "Enable the exam fee?",
    disableTitle: "Disable the exam fee?",
    enableMessage: (name) =>
      `The fee for "${name}" will be enabled: invoices will be created for all existing {{student}}s and guardians will be sent an SMS.`,
    disableMessage: (name) =>
      `The fee for "${name}" will be disabled — unpaid {{student}} invoices will be cancelled. Invoices with payments or waivers are kept. Re-enabling creates the invoices again.`,
    enable: "Enable",
    disable: "Disable",
    enabledToast: (created, notified) => `Fee enabled — ${created} invoices created, SMS to ${notified} guardians`,
    disabledToast: (name, removed) => `Fee for "${name}" disabled — ${removed} invoices cancelled`,
    keptSuffix: (kept) => `, ${kept} kept because of payments/waivers`,
    enableFailed: "Could not enable the fee",
    disableFailed: "Could not disable the fee",
    amount: "Amount",
    apply: "Apply",
    clearTitle: (scope) => `Clear changes to ${scope} (saved fees come back)`,
    clearAria: (scope) => `Clear changes to ${scope}`,
    title: "Exam Fees",
    summary: (exams, active) => `${exams} exams · fee on for ${active}`,
    manageLink: "Manage exams & {{division}}s",
    noExams: "No exams created yet — once an exam is created you can set its fee here.",
    classesSet: (set, total) => ` · fee set for ${set}/${total} {{class}}es`,
    editFee: (name) => `Edit fees for "${name}"`,
    lockedTitle: "{{academic}} has turned this exam off — the fee can be enabled once the exam is on",
    examOff: "Exam off",
    feeOn: "Fee on",
    feeOff: "Fee off",
    turnOff: "Turn the fee off",
    turnOn: "Turn the fee on (guardians get an SMS)",
    lockedNote: "The fee can be enabled once {{academic}} turns the exam on — you can set the amounts in advance.",
    legacyNote: (amount) =>
      `Under the old rule this exam was billed ৳${amount} for every {{class}}, so per-{{class}} fees cannot be set. This fee is billed only to {{student}}s of the exam's own {{division}}.`,
    noActiveClasses: "No active {{class}} in this exam's {{division}}",
    countSuffix: (n) => `${n}`,
    divisionBulkLabel: (division) => `Same amount for every {{class}} of ${division}`,
    divisionScope: (division) => division,
    classFallback: (id) => `{{class}} #${id}`,
    invoicesFromFee: "Invoices created from this fee",
    invoiceCount: (n) => `${n} invoices`,
    notSet: "Fee not set",
    feeAria: (cls) => `${cls} — fee`,
    billedHint: "Already invoiced — a new amount applies only to new invoices",
    allBulkLabel: "Same amount for every {{class}}",
    allScope: "all {{class}}es",
    cancelEditTitle: "Cancel editing — saved fees stay",
    saveCount: (n) => `Save (${n})`,
    save: "Save",
  },
});
