import { defineText } from "@madrasha/shared-ui/src/i18n";

export const examFeeBulkText = defineText({
  bn: {
    methods: {
      CASH: "ক্যাশ (হাতে নগদ)",
      BKASH: "বিকাশ",
      NAGAD: "নগদ",
      BANK: "ব্যাংক",
      ONLINE: "অনলাইন",
    },
    classFallback: (id: string) => `{{class}} #${id}`,
    listLoadFailed: "তালিকা লোড করা যায়নি",
    selectAtLeastOne: "অন্তত একজন {{student}} নির্বাচন করুন",
    invalidDate: "সঠিক তারিখ দিন — ভবিষ্যতের তারিখ দেওয়া যাবে না",
    collectedToast: (n: string, amount: string) => `${n} জনের পরীক্ষার ফি গ্রহণ হয়েছে (${amount})`,
    noneCollectedToast: "কোনো ফি গ্রহণ করা যায়নি — কারণগুলো দেখুন",
    collectFailed: "ফি গ্রহণ করা যায়নি, আবার চেষ্টা করুন",
    exam: "পরীক্ষা",
    inactiveSuffix: " — নিষ্ক্রিয়",
    classLabel: "{{class}}",
    selectClass: "{{class}} নির্বাচন করুন",
    selectClassHint: "{{class}} বাছাই করলে যাদের পরীক্ষার ফি বাকি আছে তাদের তালিকা এখানে দেখাবে।",
    listLoading: "তালিকা লোড হচ্ছে...",
    retry: "আবার চেষ্টা করুন",
    allPaidTitle: "এই {{class}}র সবাই ফি দিয়েছে",
    allPaidHint: (n: string, exam: string) => `${n} জন ইতিমধ্যে ${exam}-এর ফি পরিশোধ করেছে।`,
    noDueTitle: "এই {{class}}তে কোনো বকেয়া পরীক্ষার ফি নেই",
    dueBadge: (n: string, amount: string) => `বাকি: ${n} জন · ${amount}`,
    paidBadge: (n: string) => `ইতিমধ্যে পরিশোধ করেছে: ${n} জন`,
    searchPlaceholder: "নাম বা রোল দিয়ে খুঁজুন",
    selectAllAria: "সবাইকে নির্বাচন করুন",
    selectAllTitle: "সবাইকে নির্বাচন / বাদ দিন",
    roll: "রোল",
    due: "বাকি",
    nobodyFound: (q: string) => `"${q}" — কাউকে পাওয়া যায়নি`,
    selectRowAria: (name: string) => `${name} নির্বাচন`,
    totalAmount: (amount: string) => `মোট ${amount}`,
    paidBefore: (amount: string) => ` · আগে দিয়েছে ${amount}`,
    waived: (amount: string) => ` · মওকুফ ${amount}`,
    fullDueOnly: "এখানে শুধু সম্পূর্ণ বাকি গ্রহণ করা হয়। আংশিক পরিশোধের জন্য {{student}} খুঁজে আলাদাভাবে ফি গ্রহণ করুন।",
    confirmQuestion: (n: string, amount: string) => `${n} জনের মোট ${amount} গ্রহণ করবেন?`,
    smsWillGo: " · অভিভাবককে SMS যাবে",
    smsWontGo: " · SMS যাবে না",
    goBack: "ফিরে যান",
    collecting: "গ্রহণ করা হচ্ছে...",
    yesCollect: "হ্যাঁ, গ্রহণ করুন",
    method: "পদ্ধতি",
    channelOptional: "চ্যানেল (ঐচ্ছিক)",
    transactionRefOptional: "ট্রানজেকশন রেফ (ঐচ্ছিক)",
    noteOptional: "নোট (ঐচ্ছিক)",
    selectedSummary: (n: string) => `${n} জন`,
    selectedLabel: "নির্বাচিত",
    total: "মোট",
    smsGuardian: "অভিভাবককে SMS পাঠান",
    collectFee: "ফি গ্রহণ করুন",
    collectedResult: (n: string) => `${n} জনের ফি গ্রহণ হয়েছে`,
    noneCollected: "কোনো ফি গ্রহণ হয়নি",
    totalCollected: "মোট সংগৃহীত",
    failedHeader: (n: string) => `${n} জনের ফি গ্রহণ করা যায়নি`,
    backToList: "তালিকায় ফিরে যান",
    anotherClass: "আরেকটি {{class}}",
    examListLoadFailed: "পরীক্ষার তালিকা লোড করা যায়নি",
    noExamFee: "কোনো পরীক্ষার ফি চালু নেই",
    noExamFeeHint: "ফি সেটাপ → পরীক্ষার ফি থেকে পরিমাণ বসিয়ে ফি চালু করলে এখানে {{class}}ভিত্তিক গ্রহণ করা যাবে।",
    titleResult: "পরীক্ষার ফি — ফলাফল",
    titleClass: (name: string) => `পরীক্ষার ফি — ${name}`,
    titleDefault: "পরীক্ষার ফি — {{class}}ভিত্তিক গ্রহণ",
  },
  en: {
    methods: {
      CASH: "Cash (in hand)",
      BKASH: "bKash",
      NAGAD: "Nagad",
      BANK: "Bank",
      ONLINE: "Online",
    },
    classFallback: (id) => `{{class}} #${id}`,
    listLoadFailed: "Could not load the list",
    selectAtLeastOne: "Select at least one {{student}}",
    invalidDate: "Enter a valid date — future dates are not allowed",
    collectedToast: (n, amount) => `Exam fee collected from ${n} (${amount})`,
    noneCollectedToast: "No fee could be collected — see the reasons",
    collectFailed: "Could not collect the fee, please try again",
    exam: "Exam",
    inactiveSuffix: " — inactive",
    classLabel: "{{class}}",
    selectClass: "Select a {{class}}",
    selectClassHint: "Pick a {{class}} to list everyone whose exam fee is still due.",
    listLoading: "Loading list...",
    retry: "Try again",
    allPaidTitle: "Everyone in this {{class}} has paid",
    allPaidHint: (n, exam) => `${n} have already paid the fee for ${exam}.`,
    noDueTitle: "No exam fee is due in this {{class}}",
    dueBadge: (n, amount) => `Due: ${n} · ${amount}`,
    paidBadge: (n) => `Already paid: ${n}`,
    searchPlaceholder: "Search by name or roll",
    selectAllAria: "Select everyone",
    selectAllTitle: "Select / deselect everyone",
    roll: "Roll",
    due: "Due",
    nobodyFound: (q) => `"${q}" — nobody found`,
    selectRowAria: (name) => `Select ${name}`,
    totalAmount: (amount) => `Total ${amount}`,
    paidBefore: (amount) => ` · paid earlier ${amount}`,
    waived: (amount) => ` · waived ${amount}`,
    fullDueOnly: "Only the full due is collected here. For a partial payment, find the {{student}} and collect separately.",
    confirmQuestion: (n, amount) => `Collect a total of ${amount} from ${n}?`,
    smsWillGo: " · SMS to guardians",
    smsWontGo: " · no SMS",
    goBack: "Go back",
    collecting: "Collecting...",
    yesCollect: "Yes, collect",
    method: "Method",
    channelOptional: "Channel (optional)",
    transactionRefOptional: "Transaction ref (optional)",
    noteOptional: "Note (optional)",
    selectedSummary: (n) => `${n}`,
    selectedLabel: "Selected",
    total: "Total",
    smsGuardian: "Send SMS to guardians",
    collectFee: "Collect Fee",
    collectedResult: (n) => `Fee collected from ${n}`,
    noneCollected: "No fee collected",
    totalCollected: "Total collected",
    failedHeader: (n) => `Could not collect from ${n}`,
    backToList: "Back to the list",
    anotherClass: "Another {{class}}",
    examListLoadFailed: "Could not load the exam list",
    noExamFee: "No exam fee is active",
    noExamFeeHint: "Set an amount and enable the fee under Fee Setup → Exam Fee to collect by {{class}} here.",
    titleResult: "Exam Fee — Result",
    titleClass: (name) => `Exam Fee — ${name}`,
    titleDefault: "Exam Fee — Collect by {{class}}",
  },
  ar: {
    methods: {
      CASH: "نقدًا (باليد)",
      BKASH: "بيكاش",
      NAGAD: "نقد (Nagad)",
      BANK: "بنك",
      ONLINE: "إلكتروني",
    },
    classFallback: (id) => `{{class}} #${id}`,
    listLoadFailed: "تعذّر تحميل القائمة",
    selectAtLeastOne: "اختر {{student}} واحدًا على الأقل",
    invalidDate: "أدخل تاريخًا صحيحًا — لا يُسمح بتاريخ مستقبلي",
    collectedToast: (n, amount) => `تم تحصيل رسوم الامتحان من ${n} (${amount})`,
    noneCollectedToast: "تعذّر تحصيل أي رسوم — راجع الأسباب",
    collectFailed: "تعذّر تحصيل الرسوم، حاول مرة أخرى",
    exam: "الامتحان",
    inactiveSuffix: " — غير نشط",
    classLabel: "{{class}}",
    selectClass: "اختر {{class}}",
    selectClassHint: "اختر {{class}} لعرض قائمة من عليهم رسوم امتحان مستحقة.",
    listLoading: "جارٍ تحميل القائمة...",
    retry: "حاول مرة أخرى",
    allPaidTitle: "دفع الجميع في هذا {{class}}",
    allPaidHint: (n, exam) => `دفع ${n} رسوم ${exam} مسبقًا.`,
    noDueTitle: "لا توجد رسوم امتحان مستحقة في هذا {{class}}",
    dueBadge: (n, amount) => `المستحق: ${n} · ${amount}`,
    paidBadge: (n) => `دفع مسبقًا: ${n}`,
    searchPlaceholder: "ابحث بالاسم أو رقم الجلوس",
    selectAllAria: "تحديد الجميع",
    selectAllTitle: "تحديد / إلغاء تحديد الجميع",
    roll: "رقم الجلوس",
    due: "المستحق",
    nobodyFound: (q) => `"${q}" — لم يُعثر على أحد`,
    selectRowAria: (name) => `تحديد ${name}`,
    totalAmount: (amount) => `المجموع ${amount}`,
    paidBefore: (amount) => ` · دفع سابقًا ${amount}`,
    waived: (amount) => ` · معفى ${amount}`,
    fullDueOnly: "يُحصَّل هنا المستحق كاملًا فقط. للدفع الجزئي ابحث عن {{student}} وحصّل الرسوم بشكل منفصل.",
    confirmQuestion: (n, amount) => `هل تريد تحصيل ${amount} إجمالًا من ${n}؟`,
    smsWillGo: " · ستُرسل رسالة لولي الأمر",
    smsWontGo: " · لن تُرسل رسالة",
    goBack: "رجوع",
    collecting: "جارٍ التحصيل...",
    yesCollect: "نعم، حصِّل",
    method: "الطريقة",
    channelOptional: "القناة (اختياري)",
    transactionRefOptional: "مرجع المعاملة (اختياري)",
    noteOptional: "ملاحظة (اختياري)",
    selectedSummary: (n) => `${n}`,
    selectedLabel: "المحدد",
    total: "المجموع",
    smsGuardian: "إرسال رسالة لولي الأمر",
    collectFee: "تحصيل الرسوم",
    collectedResult: (n) => `تم تحصيل الرسوم من ${n}`,
    noneCollected: "لم تُحصَّل أي رسوم",
    totalCollected: "إجمالي المحصَّل",
    failedHeader: (n) => `تعذّر التحصيل من ${n}`,
    backToList: "العودة إلى القائمة",
    anotherClass: "{{class}} آخر",
    examListLoadFailed: "تعذّر تحميل قائمة الامتحانات",
    noExamFee: "لا توجد رسوم امتحان مفعّلة",
    noExamFeeHint: "حدّد المبلغ وفعّل الرسوم من إعداد الرسوم ← رسوم الامتحان ليمكن التحصيل هنا حسب {{class}}.",
    titleResult: "رسوم الامتحان — النتيجة",
    titleClass: (name) => `رسوم الامتحان — ${name}`,
    titleDefault: "رسوم الامتحان — التحصيل حسب {{class}}",
  },
});
