import { defineText } from "@madrasha/shared-ui/src/i18n";

/** Invoice status labels (display only - the codes are backend values). */
export const invoiceStatusText = defineText({
  bn: {
    UNPAID: "অপরিশোধিত",
    PARTIALLY_PAID: "আংশিক পরিশোধিত",
    PAID: "পরিশোধিত",
    OVERDUE: "মেয়াদোত্তীর্ণ",
    WAIVED: "মওকুফকৃত",
  } as Record<string, string>,
  en: {
    UNPAID: "Unpaid",
    PARTIALLY_PAID: "Partially paid",
    PAID: "Paid",
    OVERDUE: "Overdue",
    WAIVED: "Waived",
  },
});

export const feeDashboardText = defineText({
  bn: {
    totalInvoiced: "মোট বিলকৃত",
    totalCollected: "মোট আদায়",
    totalDue: "মোট বকেয়া",
    overdue: "ওভারডিউ",
    invoiceCount: (n: string) => `${n} টি চালান`,
    quickActions: "দ্রুত অ্যাকশন",
    collectFee: "ফি গ্রহণ",
    admissionFeePending: "ভর্তি ফি পেন্ডিং",
    overdueFees: "বকেয়া ফী",
    feeSetup: "ফি সেটাপ",
    trendTitle: "ফি আদায়ের প্রবণতা",
    last12Months: "গত ১২ মাস",
    collected: "আদায়",
    statusTitle: "চালানের অবস্থা",
    byCount: "সংখ্যা অনুযায়ী",
  },
  en: {
    totalInvoiced: "Total Invoiced",
    totalCollected: "Total Collected",
    totalDue: "Total Due",
    overdue: "Overdue",
    invoiceCount: (n) => `${n} invoices`,
    quickActions: "Quick Actions",
    collectFee: "Collect Fee",
    admissionFeePending: "Pending Admission Fees",
    overdueFees: "Overdue Fees",
    feeSetup: "Fee Setup",
    trendTitle: "Fee Collection Trend",
    last12Months: "Last 12 months",
    collected: "Collected",
    statusTitle: "Invoice Status",
    byCount: "By count",
  },
});

/** Printed invoice - institution default language. */
export const invoicePrintText = defineText({
  bn: {
    invoice: "ইনভয়েস",
    roll: "রোল",
    invoiceNo: "ইনভয়েস নং",
    dueDate: "ডিউ তারিখ",
    student: "{{student}}",
    description: "বিবরণ",
    totalAmount: "মোট পরিমাণ",
    paid: "পরিশোধিত",
    waived: "মওকুফকৃত",
    status: "স্ট্যাটাস",
    remaining: (amount: string) => `বাকি ${amount}`,
    fullyPaid: "সম্পূর্ণ পরিশোধ",
    guardianSignature: "অভিভাবকের স্বাক্ষর",
    authoritySignature: "কর্তৃপক্ষের স্বাক্ষর",
  },
  en: {
    invoice: "Invoice",
    roll: "Roll",
    invoiceNo: "Invoice No.",
    dueDate: "Due date",
    student: "{{student}}",
    description: "Description",
    totalAmount: "Total amount",
    paid: "Paid",
    waived: "Waived",
    status: "Status",
    remaining: (amount) => `Due ${amount}`,
    fullyPaid: "Fully paid",
    guardianSignature: "Guardian's signature",
    authoritySignature: "Authorized signature",
  },
});

export const invoicePreviewText = defineText({
  bn: { title: "ইনভয়েস প্রিন্ট প্রিভিউ", printNow: "প্রিন্ট করুন" },
  en: { title: "Invoice Print Preview", printNow: "Print" },
});

export const overdueText = defineText({
  bn: {
    title: "বকেয়া ফী",
    subtitle: "প্রতিটি {{student}}র সব বকেয়া ফি এক জায়গায় — মোট বকেয়া",
    searchPlaceholder: "নাম, রোল, রেজিস্ট্রেশন নম্বর বা {{class}} দিয়ে খুঁজুন...",
    noDues: "কোনো বকেয়া ফি নেই — সব ফি পরিশোধিত",
    noResults: "এই সার্চে কোনো ফলাফল পাওয়া যায়নি",
    roll: "রোল",
    reg: "রেজি.",
    dueCount: (n: string) => `${n} টি বকেয়া ফি`,
    oldestDue: "প্রথম বকেয়ার তারিখ",
    collect: "ফি আদায় করুন",
    dueDateLabel: "নির্ধারিত তারিখ",
    showing: (from: string, to: string, total: string) => `দেখাচ্ছে ${from}–${to}, মোট ${total} জন`,
    perPage: (n: string) => `পাতায় ${n} জন`,
    prev: "আগের",
    next: "পরের",
    page: (p: string, total: string) => `পাতা ${p} / ${total}`,
  },
  en: {
    title: "Overdue Fees",
    subtitle: "All dues of every {{student}} in one place — total due",
    searchPlaceholder: "Search by name, roll, registration no. or {{class}}...",
    noDues: "No dues — all fees are paid",
    noResults: "No results for this search",
    roll: "Roll",
    reg: "Reg.",
    dueCount: (n) => `${n} dues`,
    oldestDue: "oldest due date",
    collect: "Collect Fee",
    dueDateLabel: "due date",
    showing: (from, to, total) => `Showing ${from}–${to} of ${total}`,
    perPage: (n) => `${n} per page`,
    prev: "Previous",
    next: "Next",
    page: (p, total) => `Page ${p} / ${total}`,
  },
});

export const feeCategoryText = defineText({
  bn: {
    enterName: "একটা নাম দিন",
    added: "ফি ধরণ যোগ করা হয়েছে",
    saveFailed: "সংরক্ষণ করতে সমস্যা হয়েছে",
    updateFailed: "আপডেট করতে সমস্যা হয়েছে",
    deleteFailed: "মুছতে সমস্যা হয়েছে",
    disableTitle: "ফি ধরণ বন্ধ করুন",
    disableMessage: (name: string) =>
      `"${name}" বন্ধ করলে এই ধরণ ব্যবহার করা সব ফি কাঠামোও (Fee Structure পেজে) বন্ধ হয়ে যাবে - সেগুলো আর কোনো {{student}}র জন্য বিল হবে না। এগিয়ে যেতে চান?`,
    disableConfirm: "বন্ধ করুন",
    deleteTitle: "ফি ধরণ ডিলিট করুন",
    deleteMessage: (name: string) =>
      `"${name}" ফি ধরণটি স্থায়ীভাবে মুছে ফেলতে চান? যেসব ফি কাঠামো ইতিমধ্যে এই ধরণ ব্যবহার করছে সেগুলো প্রভাবিত হবে না — সেগুলোতে নামটা শুধু টেক্সট হিসেবে থেকে যাবে।`,
    deleteConfirm: "ডিলিট করুন",
    toggleHint: "বন্ধ করলে এই ধরণের সব ফি কাঠামোও বন্ধ (আর বিল হবে না) হয়ে যাবে",
    backToSetup: "ফি সেটাপে ফিরুন",
    title: "ফি ধরণ সেটিংস",
    sectionTitle: "ফি ধরণসমূহ",
    sectionHint: "নতুন একটি ফি ধরণ যোগ করুন",
    newPlaceholder: "নতুন ফি ধরণের নাম",
    emptyTitle: "এখনো কোনো ফি ধরণ যোগ করা হয়নি",
    emptyHint: "উপরের ফর্ম থেকে প্রথম ফি ধরণটি যোগ করুন।",
  },
  en: {
    enterName: "Enter a name",
    added: "Fee type added",
    saveFailed: "Could not save",
    updateFailed: "Could not update",
    deleteFailed: "Could not delete",
    disableTitle: "Disable Fee Type",
    disableMessage: (name) =>
      `Disabling "${name}" also disables every fee structure using this type (on the Fee Structure page) - they will no longer be billed to any {{student}}. Continue?`,
    disableConfirm: "Disable",
    deleteTitle: "Delete Fee Type",
    deleteMessage: (name) =>
      `Permanently delete the fee type "${name}"? Fee structures already using it are not affected — the name stays on them as plain text.`,
    deleteConfirm: "Delete",
    toggleHint: "Disabling also disables all fee structures of this type (no more billing)",
    backToSetup: "Back to Fee Setup",
    title: "Fee Type Settings",
    sectionTitle: "Fee Types",
    sectionHint: "Add a new fee type",
    newPlaceholder: "New fee type name",
    emptyTitle: "No fee types added yet",
    emptyHint: "Add the first fee type using the form above.",
  },
});

export const paymentMethodText = defineText({
  bn: {
    types: {
      CASH: "নগদ",
      BKASH: "বিকাশ",
      NAGAD: "নগদ (Nagad)",
      BANK: "ব্যাংক",
      OTHER: "অন্যান্য",
    },
    type: "ধরন",
    label: "লেবেল (যেমন: বিকাশ - পার্সোনাল)",
    accountNumber: "অ্যাকাউন্ট/নম্বর",
    accountNumberPlaceholder: "017XXXXXXXX / হিসাব নম্বর",
    accountName: "নামে (Account Name)",
    bankName: "ব্যাংকের নাম",
    branch: "শাখা",
    instructions: "নির্দেশনা (ঐচ্ছিক)",
    instructionsPlaceholder: "যেমন: Send Money করুন, তারপর ট্রানজেকশন আইডি অফিসে জানান",
    enterLabel: "একটা নাম/লেবেল দিন (যেমন: বিকাশ - পার্সোনাল)",
    added: "পেমেন্ট পদ্ধতি যোগ করা হয়েছে",
    updated: "পেমেন্ট পদ্ধতি আপডেট হয়েছে",
    saveFailed: "সংরক্ষণ করতে সমস্যা হয়েছে",
    updateFailed: "আপডেট করতে সমস্যা হয়েছে",
    deleteFailed: "মুছতে সমস্যা হয়েছে",
    deleteTitle: "পেমেন্ট পদ্ধতি ডিলিট করুন",
    deleteMessage: (label: string) => `"${label}" পদ্ধতিটি স্থায়ীভাবে মুছে ফেলতে চান?`,
    deleteConfirm: "ডিলিট করুন",
    deleted: "পেমেন্ট পদ্ধতি মুছে ফেলা হয়েছে",
    title: "পেমেন্ট পদ্ধতি সেটআপ",
    subtitle:
      "এখানে যেসব ম্যানুয়াল পেমেন্ট চ্যানেল (বিকাশ নম্বর, ব্যাংক অ্যাকাউন্ট, নগদ) যোগ করবেন, সেগুলো ফি পেমেন্ট রেকর্ড করার সময় বেছে নেওয়া যাবে। এখানে কোনো পেমেন্ট গেটওয়ে/অটো পেমেন্ট সিস্টেম নেই — এটি সম্পূর্ণ ম্যানুয়াল।",
    addTitle: "নতুন পেমেন্ট পদ্ধতি যোগ করুন",
    allTitle: "সব পেমেন্ট পদ্ধতি",
    allHint: "যেকোনো পদ্ধতির পেন্সিল আইকনে ক্লিক করলে সেটি এডিট করা যাবে",
    emptyTitle: "এখনো কোনো পেমেন্ট পদ্ধতি যোগ করা হয়নি",
    emptyHint: "উপরের ফর্ম থেকে প্রথম পেমেন্ট পদ্ধতিটি যোগ করুন।",
  },
  en: {
    types: {
      CASH: "Cash",
      BKASH: "bKash",
      NAGAD: "Nagad",
      BANK: "Bank",
      OTHER: "Other",
    },
    type: "Type",
    label: "Label (e.g. bKash - Personal)",
    accountNumber: "Account/Number",
    accountNumberPlaceholder: "017XXXXXXXX / account number",
    accountName: "Account Name",
    bankName: "Bank name",
    branch: "Branch",
    instructions: "Instructions (optional)",
    instructionsPlaceholder: "e.g. Use Send Money, then tell the office the transaction ID",
    enterLabel: "Enter a name/label (e.g. bKash - Personal)",
    added: "Payment method added",
    updated: "Payment method updated",
    saveFailed: "Could not save",
    updateFailed: "Could not update",
    deleteFailed: "Could not delete",
    deleteTitle: "Delete Payment Method",
    deleteMessage: (label) => `Permanently delete the payment method "${label}"?`,
    deleteConfirm: "Delete",
    deleted: "Payment method deleted",
    title: "Payment Method Setup",
    subtitle:
      "Manual payment channels added here (bKash number, bank account, cash) can be picked when recording fee payments. There is no payment gateway or automatic payment — this is fully manual.",
    addTitle: "Add a New Payment Method",
    allTitle: "All Payment Methods",
    allHint: "Click the pencil icon of any method to edit it",
    emptyTitle: "No payment methods added yet",
    emptyHint: "Add the first payment method using the form above.",
  },
});
