import { defineText } from "@madrasha/shared-ui/src/i18n";

export const feeInvoicesText = defineText({
  bn: {
    months: ["জানুয়ারি", "ফেব্রুয়ারি", "মার্চ", "এপ্রিল", "মে", "জুন", "জুলাই", "আগস্ট", "সেপ্টেম্বর", "অক্টোবর", "নভেম্বর", "ডিসেম্বর"],
    monthsShort: ["জানু", "ফেব্রু", "মার্চ", "এপ্রিল", "মে", "জুন", "জুলাই", "আগস্ট", "সেপ্ট", "অক্টো", "নভে", "ডিসে"],
    selectAtLeastOne: "অন্তত একটি ফি নির্বাচন করে পরিমাণ দিন",
    paidMany: (n: string) => `${n}টি ফি একসাথে পরিশোধ রেকর্ড হয়েছে`,
    paidOne: "পেমেন্ট রেকর্ড করা হয়েছে",
    partialFailure: (ok: string, failed: string) => `${ok}টি পরিশোধ হয়েছে, ${failed}টি ব্যর্থ হয়েছে — আবার চেষ্টা করুন`,
    title: "ফি গ্রহণ",
    subtitle: "{{student}} খুঁজে নিন, মাসিক ফি আদায়-অনাদায় ছক দেখুন ও পেমেন্ট রেকর্ড করুন",
    bulkExamFee: "পরীক্ষার ফি — {{class}}ভিত্তিক",
    selected: "নির্বাচিত",
    studentFallback: (id: string) => `{{student}} #${id}`,
    change: "বদলান",
    searchPlaceholder: "{{student}}র নাম, রোল বা রেজি নং দিয়ে খুঁজুন",
    noStudentFound: "কোনো {{student}} পাওয়া যায়নি",
    classLabel: "{{class}}",
    roll: "রোল",
    reg: "রেজি",
    studentInfo: "{{student}}র তথ্য",
    idNo: "আইডি নং",
    guardianName: "অভিভাবকের নাম",
    allStatus: "সব স্ট্যাটাস",
    totalDue: "মোট বকেয়া",
    collected: "সংগৃহীত",
    ledgerTitle: (year: string) => `মাসিক ফি আদায় - অনাদায় ছক, সাল - ${year}`,
    scrollHint: "⟷ টেবিলটি পাশে স্ক্রল করে বাকি মাসগুলো দেখুন",
    items: "বিষয়সমূহ",
    amount: "পরিমাণ",
    pickStudentHint: "ফি দেখতে ও নিতে উপরের সার্চ বারে একজন {{student}} খুঁজে নির্বাচন করুন",
    noFees: "এই {{student}}র কোনো ফি নেই",
    unlockHint: "ফি নিতে এই ঘরে টিক দিয়ে মাসগুলো খুলুন",
    waivedShort: "মওকুফ",
    partialAmountHint: "আংশিক পরিমাণ দিতে ক্লিক করুন",
    grandTotal: "সর্বমোট",
    selectedCount: (n: string) => `${n}টি নির্বাচিত`,
    collectSelected: "নির্বাচিত ফি সংগ্রহ করুন",
    payTitle: (name: string) => `পেমেন্ট রেকর্ড করুন — ${name}`,
    remainingParen: (amount: string) => `(বাকি ৳${amount})`,
    partial: "আংশিক",
    totalToCollect: "মোট নেওয়া হবে",
    amountTaka: "পরিমাণ (৳)",
    remainingHint: (amount: string) =>
      `বাকি আছে: ৳${amount} — সম্পূর্ণ না দিয়ে কম অঙ্ক লিখলে আংশিক পরিশোধ হিসেবে রেকর্ড হবে`,
    method: "পদ্ধতি",
    channel: "কোন চ্যানেলে টাকা পাওয়া গেছে (ঐচ্ছিক)",
    selectOptional: "নির্বাচন করুন (ঐচ্ছিক)",
    transactionRef: "ট্রানজেকশন রেফারেন্স (ঐচ্ছিক)",
    noteOptional: "নোট (ঐচ্ছিক)",
    notePlaceholder: "যেমন: আংশিক পরিশোধ, বাকিটা পরের মাসে দেবে",
    confirmPay: (amount: string) => `৳${amount} পেমেন্ট নিশ্চিত করুন`,
  },
  en: {
    months: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
    monthsShort: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    selectAtLeastOne: "Select at least one fee and enter an amount",
    paidMany: (n) => `Payment recorded for ${n} fees together`,
    paidOne: "Payment recorded",
    partialFailure: (ok, failed) => `${ok} paid, ${failed} failed — please try again`,
    title: "Collect Fee",
    subtitle: "Find a {{student}}, view the monthly paid/unpaid sheet and record payments",
    bulkExamFee: "Exam Fee — by {{class}}",
    selected: "Selected",
    studentFallback: (id) => `{{student}} #${id}`,
    change: "Change",
    searchPlaceholder: "Search {{student}} by name, roll or reg. no.",
    noStudentFound: "No {{student}} found",
    classLabel: "{{class}}",
    roll: "Roll",
    reg: "Reg",
    studentInfo: "{{student}} Information",
    idNo: "ID No.",
    guardianName: "Guardian's name",
    allStatus: "All statuses",
    totalDue: "Total Due",
    collected: "Collected",
    ledgerTitle: (year) => `Monthly fee paid/unpaid sheet, year - ${year}`,
    scrollHint: "⟷ Scroll the table sideways to see the other months",
    items: "Items",
    amount: "Amount",
    pickStudentHint: "Search and select a {{student}} above to view and collect fees",
    noFees: "This {{student}} has no fees",
    unlockHint: "Tick this box to unlock the months for collection",
    waivedShort: "Waived",
    partialAmountHint: "Click to enter a partial amount",
    grandTotal: "Grand Total",
    selectedCount: (n) => `${n} selected`,
    collectSelected: "Collect selected fees",
    payTitle: (name) => `Record Payment — ${name}`,
    remainingParen: (amount) => `(due ৳${amount})`,
    partial: "Partial",
    totalToCollect: "Total to collect",
    amountTaka: "Amount (৳)",
    remainingHint: (amount) => `Due: ৳${amount} — entering less than the full amount records a partial payment`,
    method: "Method",
    channel: "Channel the money was received in (optional)",
    selectOptional: "Select (optional)",
    transactionRef: "Transaction reference (optional)",
    noteOptional: "Note (optional)",
    notePlaceholder: "e.g. partial payment, rest next month",
    confirmPay: (amount) => `Confirm payment of ৳${amount}`,
  },
  ar: {
    months: ["يناير", "فبراير", "مارس", "أبريل", "مايو", "يونيو", "يوليو", "أغسطس", "سبتمبر", "أكتوبر", "نوفمبر", "ديسمبر"],
    monthsShort: ["ينا", "فبر", "مار", "أبر", "ماي", "يون", "يول", "أغس", "سبت", "أكت", "نوف", "ديس"],
    selectAtLeastOne: "اختر رسمًا واحدًا على الأقل وأدخل المبلغ",
    paidMany: (n) => `تم تسجيل دفع ${n} من الرسوم معًا`,
    paidOne: "تم تسجيل الدفعة",
    partialFailure: (ok, failed) => `تم دفع ${ok}، وفشل ${failed} — حاول مرة أخرى`,
    title: "تحصيل الرسوم",
    subtitle: "ابحث عن {{student}} واطّلع على جدول الرسوم الشهرية المدفوعة وغير المدفوعة وسجّل الدفعات",
    bulkExamFee: "رسوم الامتحان — حسب {{class}}",
    selected: "المحدد",
    studentFallback: (id) => `{{student}} #${id}`,
    change: "تغيير",
    searchPlaceholder: "ابحث عن {{student}} بالاسم أو رقم الجلوس أو رقم التسجيل",
    noStudentFound: "لم يتم العثور على {{student}}",
    classLabel: "{{class}}",
    roll: "رقم الجلوس",
    reg: "التسجيل",
    studentInfo: "بيانات {{student}}",
    idNo: "رقم الهوية",
    guardianName: "اسم ولي الأمر",
    allStatus: "كل الحالات",
    totalDue: "إجمالي المستحق",
    collected: "المحصَّل",
    ledgerTitle: (year) => `جدول الرسوم الشهرية المدفوعة وغير المدفوعة، سنة - ${year}`,
    scrollHint: "⟷ مرّر الجدول جانبيًا لرؤية بقية الأشهر",
    items: "البنود",
    amount: "المبلغ",
    pickStudentHint: "ابحث عن {{student}} واختره أعلاه لعرض الرسوم وتحصيلها",
    noFees: "لا توجد رسوم على هذا {{student}}",
    unlockHint: "ضع علامة هنا لفتح الأشهر للتحصيل",
    waivedShort: "معفى",
    partialAmountHint: "انقر لإدخال مبلغ جزئي",
    grandTotal: "الإجمالي",
    selectedCount: (n) => `تم تحديد ${n}`,
    collectSelected: "تحصيل الرسوم المحددة",
    payTitle: (name) => `تسجيل دفعة — ${name}`,
    remainingParen: (amount) => `(المتبقي ৳${amount})`,
    partial: "جزئي",
    totalToCollect: "إجمالي ما سيُحصَّل",
    amountTaka: "المبلغ (৳)",
    remainingHint: (amount) => `المتبقي: ৳${amount} — إدخال مبلغ أقل من الكامل يُسجَّل دفعًا جزئيًا`,
    method: "الطريقة",
    channel: "القناة التي استُلم فيها المبلغ (اختياري)",
    selectOptional: "اختر (اختياري)",
    transactionRef: "مرجع المعاملة (اختياري)",
    noteOptional: "ملاحظة (اختياري)",
    notePlaceholder: "مثال: دفع جزئي، والباقي الشهر القادم",
    confirmPay: (amount) => `تأكيد دفع ৳${amount}`,
  },
});
