import { defineText } from "@madrasha/shared-ui/src/i18n";

export const feeStructureText = defineText({
  bn: {
    frequency: { ONE_TIME: "একবার", MONTHLY: "মাসিক", YEARLY: "বাৎসরিক" },
    menu: {
      general: { label: "নিয়মিত ও অন্যান্য ফি", hint: "মাসিক, বাৎসরিক ও এককালীন ফি" },
      exam: { label: "পরীক্ষার ফি", hint: "পরীক্ষা × {{class}} অনুযায়ী ফি" },
      categories: { label: "ফি ধরণ সেটিংস", hint: "ফি-র ধরণ যোগ/বদল" },
    },
    requiredFields: "ফি ধরণ, পরিমাণ ও সেশন দিন",
    createdWithInvoices: (inv: string, students: string) =>
      `ফি কাঠামো তৈরি হয়েছে — ${inv}টি ইনভয়েস তৈরি হয়েছে (${students} জন {{student}}র জন্য)`,
    createdBackfillFailed: "ফি কাঠামো তৈরি হয়েছে, তবে বিদ্যমান {{student}}দের ইনভয়েস তৈরিতে সমস্যা হয়েছে",
    createFailed: "ফি কাঠামো তৈরি করতে সমস্যা হয়েছে",
    updatedWithInvoices: (inv: string, students: string) =>
      `ফি কাঠামো আপডেট হয়েছে — ${inv}টি ইনভয়েস তৈরি হয়েছে (${students} জন {{student}}র জন্য)`,
    updatedBackfillFailed: "ফি কাঠামো আপডেট হয়েছে, তবে বিদ্যমান {{student}}দের ইনভয়েস তৈরিতে সমস্যা হয়েছে",
    updateFailed: "ফি কাঠামো আপডেট করতে সমস্যা হয়েছে",
    deleted: "ফি কাঠামো মুছে ফেলা হয়েছে",
    deleteFailed: "মুছতে সমস্যা হয়েছে",
    toggleFailed: "আপডেট করতে সমস্যা হয়েছে",
    activatedWithInvoices: (inv: string, students: string) =>
      `ফি কাঠামো চালু হয়েছে — ${inv}টি ইনভয়েস তৈরি হয়েছে (${students} জন {{student}}র জন্য)`,
    other: "অন্যান্য",
    classFallback: (id: string) => `{{class}} #${id}`,
    genericGroup: "সাধারণ (সব {{division}} ও {{class}}র জন্য)",
    allClasses: "সব {{class}}",
    feeMenu: "ফি মেনু",
    title: "ফি সেটাপ",
    subtitle: "ফি নির্ধারণ করুন — নতুন ভর্তি হওয়া {{student}}দের পাশাপাশি বিদ্যমান সব যোগ্য {{student}}র জন্যও ইনভয়েস অটোমেটিক তৈরি হয়ে যায়",
    createTitle: "নতুন ফি কাঠামো তৈরি করুন",
    forSelectedClass: "(নির্বাচিত {{class}}র জন্য)",
    forAllClasses: "(সব {{class}}র জন্য)",
    createHint:
      "তৈরি করার সাথে সাথেই যোগ্য বিদ্যমান {{student}}দের জন্য অটোমেটিক ইনভয়েস তৈরি হয়ে যাবে — এডিট করলে বা নিষ্ক্রিয় থেকে আবার সক্রিয় করলেও একইভাবে হয়ে যায়, আলাদা কিছু চালাতে হয় না। পরীক্ষার ফি এখানে নয় — পাশের \"পরীক্ষার ফি\" মেনুতে প্রতিটি পরীক্ষার {{division}} অনুযায়ী {{class}}গুলো নিজে থেকেই আসে।",
    feeType: "ফি ধরণ",
    frequencyLabel: "ফ্রিকোয়েন্সি",
    amountTaka: "পরিমাণ (৳)",
    amount: "পরিমাণ",
    division: "{{division}}",
    generalAllDivisions: "সাধারণ (সব {{division}})",
    classLabel: "{{class}}",
    generalAllClasses: "সাধারণ (সব {{class}})",
    session: "সেশন",
    selectSession: "সেশন নির্বাচন করুন",
    activeSuffix: " (সক্রিয়)",
    creating: "তৈরি হচ্ছে...",
    byDivisionTitle: "{{division}} অনুযায়ী ফি কাঠামো",
    allDivisions: "সব {{division}}",
    general: "সাধারণ",
    feeCount: (n: string) => `${n}টি ফি`,
    classCount: (n: string) => ` · ${n}টি {{class}}`,
    addFee: "ফি যোগ করুন",
    emptyGeneric: "এই অংশে এখনো কোনো ফি সেট করা হয়নি",
    emptyDivision: "এই {{division}}ে এখনো কোনো ফি সেট করা হয়নি",
    count: (n: string) => `${n}টি`,
    examLinkedHint: "নির্দিষ্ট এই পরীক্ষার সাথে যুক্ত - ভর্তির সাথে সাথে বিল হয় না, শুধু তৈরি/আবার-সেট করার সময় বিল হয়",
    toggleOffHint: "বন্ধ করলে এই ফি কাঠামো আর কোনো {{student}}র জন্য বিল হবে না",
    turnOn: "চালু করুন",
    editTitle: (name: string) => `ফি কাঠামো এডিট করুন — ${name}`,
  },
  en: {
    frequency: { ONE_TIME: "One-time", MONTHLY: "Monthly", YEARLY: "Yearly" },
    menu: {
      general: { label: "Regular & Other Fees", hint: "Monthly, yearly and one-time fees" },
      exam: { label: "Exam Fees", hint: "Fees by exam × {{class}}" },
      categories: { label: "Fee Type Settings", hint: "Add/change fee types" },
    },
    requiredFields: "Enter fee type, amount and session",
    createdWithInvoices: (inv, students) => `Fee structure created — ${inv} invoices created (for ${students} {{student}}s)`,
    createdBackfillFailed: "Fee structure created, but invoices for existing {{student}}s could not be created",
    createFailed: "Could not create the fee structure",
    updatedWithInvoices: (inv, students) => `Fee structure updated — ${inv} invoices created (for ${students} {{student}}s)`,
    updatedBackfillFailed: "Fee structure updated, but invoices for existing {{student}}s could not be created",
    updateFailed: "Could not update the fee structure",
    deleted: "Fee structure deleted",
    deleteFailed: "Could not delete",
    toggleFailed: "Could not update",
    activatedWithInvoices: (inv, students) => `Fee structure enabled — ${inv} invoices created (for ${students} {{student}}s)`,
    other: "Other",
    classFallback: (id) => `{{class}} #${id}`,
    genericGroup: "General (all {{division}}s and {{class}}es)",
    allClasses: "All {{class}}es",
    feeMenu: "Fee Menu",
    title: "Fee Setup",
    subtitle: "Set fees — invoices are created automatically for newly admitted {{student}}s as well as all eligible existing ones",
    createTitle: "Create a New Fee Structure",
    forSelectedClass: "(for the selected {{class}})",
    forAllClasses: "(for all {{class}}es)",
    createHint:
      "Invoices for eligible existing {{student}}s are created as soon as you save — the same happens on edit or when re-enabling, nothing else to run. Exam fees are not set here — under the \"Exam Fees\" menu each exam's {{class}}es appear automatically from its {{division}}s.",
    feeType: "Fee type",
    frequencyLabel: "Frequency",
    amountTaka: "Amount (৳)",
    amount: "Amount",
    division: "{{division}}",
    generalAllDivisions: "General (all {{division}}s)",
    classLabel: "{{class}}",
    generalAllClasses: "General (all {{class}}es)",
    session: "Session",
    selectSession: "Select a session",
    activeSuffix: " (active)",
    creating: "Creating...",
    byDivisionTitle: "Fee Structures by {{division}}",
    allDivisions: "All {{division}}s",
    general: "General",
    feeCount: (n) => `${n} fees`,
    classCount: (n) => ` · ${n} {{class}}es`,
    addFee: "Add fee",
    emptyGeneric: "No fees set in this section yet",
    emptyDivision: "No fees set in this {{division}} yet",
    count: (n) => n,
    examLinkedHint: "Linked to this exam - not billed at admission, only when created/re-set",
    toggleOffHint: "When off, this fee structure is no longer billed to any {{student}}",
    turnOn: "Turn on",
    editTitle: (name) => `Edit Fee Structure — ${name}`,
  },
  ar: {
    frequency: { ONE_TIME: "مرة واحدة", MONTHLY: "شهري", YEARLY: "سنوي" },
    menu: {
      general: { label: "الرسوم الدورية والأخرى", hint: "رسوم شهرية وسنوية ولمرة واحدة" },
      exam: { label: "رسوم الامتحانات", hint: "الرسوم حسب الامتحان × {{class}}" },
      categories: { label: "إعدادات أنواع الرسوم", hint: "إضافة/تعديل أنواع الرسوم" },
    },
    requiredFields: "أدخل نوع الرسوم والمبلغ والعام الدراسي",
    createdWithInvoices: (inv, students) => `تم إنشاء هيكل الرسوم — أُنشئت ${inv} فاتورة (لـ ${students} من الطلاب)`,
    createdBackfillFailed: "تم إنشاء هيكل الرسوم، لكن تعذّر إنشاء فواتير الطلاب الحاليين",
    createFailed: "تعذّر إنشاء هيكل الرسوم",
    updatedWithInvoices: (inv, students) => `تم تحديث هيكل الرسوم — أُنشئت ${inv} فاتورة (لـ ${students} من الطلاب)`,
    updatedBackfillFailed: "تم تحديث هيكل الرسوم، لكن تعذّر إنشاء فواتير الطلاب الحاليين",
    updateFailed: "تعذّر تحديث هيكل الرسوم",
    deleted: "تم حذف هيكل الرسوم",
    deleteFailed: "تعذّر الحذف",
    toggleFailed: "تعذّر التحديث",
    activatedWithInvoices: (inv, students) => `تم تفعيل هيكل الرسوم — أُنشئت ${inv} فاتورة (لـ ${students} من الطلاب)`,
    other: "أخرى",
    classFallback: (id) => `{{class}} #${id}`,
    genericGroup: "عام (لكل المراحل والصفوف)",
    allClasses: "كل الصفوف",
    feeMenu: "قائمة الرسوم",
    title: "إعداد الرسوم",
    subtitle: "حدّد الرسوم — تُنشأ الفواتير تلقائيًا للطلاب المقبولين حديثًا ولجميع الطلاب الحاليين المستحقين",
    createTitle: "إنشاء هيكل رسوم جديد",
    forSelectedClass: "(لـ{{class}} المحدد)",
    forAllClasses: "(لكل الصفوف)",
    createHint:
      "تُنشأ فواتير الطلاب الحاليين المستحقين فور الحفظ — ويحدث الشيء نفسه عند التعديل أو إعادة التفعيل دون خطوات إضافية. رسوم الامتحانات لا تُحدَّد هنا — في قائمة \"رسوم الامتحانات\" تظهر صفوف كل امتحان تلقائيًا حسب مراحله.",
    feeType: "نوع الرسوم",
    frequencyLabel: "التكرار",
    amountTaka: "المبلغ (৳)",
    amount: "المبلغ",
    division: "{{division}}",
    generalAllDivisions: "عام (كل المراحل)",
    classLabel: "{{class}}",
    generalAllClasses: "عام (كل الصفوف)",
    session: "العام الدراسي",
    selectSession: "اختر العام الدراسي",
    activeSuffix: " (نشط)",
    creating: "جارٍ الإنشاء...",
    byDivisionTitle: "هياكل الرسوم حسب {{division}}",
    allDivisions: "كل المراحل",
    general: "عام",
    feeCount: (n) => `${n} رسوم`,
    classCount: (n) => ` · ${n} صفوف`,
    addFee: "إضافة رسوم",
    emptyGeneric: "لم تُحدَّد رسوم في هذا القسم بعد",
    emptyDivision: "لم تُحدَّد رسوم في هذه المرحلة بعد",
    count: (n) => n,
    examLinkedHint: "مرتبط بهذا الامتحان - لا يُفوتر عند القبول، بل عند الإنشاء/إعادة الضبط فقط",
    toggleOffHint: "عند الإيقاف لن يُفوتر هذا الهيكل لأي طالب",
    turnOn: "تفعيل",
    editTitle: (name) => `تعديل هيكل الرسوم — ${name}`,
  },
});
