import { defineText } from "@madrasha/shared-ui/src/i18n";

export const pendingAdmissionFeeText = defineText({
  bn: {
    clearTitle: "পুরো তালিকা ক্লিয়ার করবেন?",
    clearMessage:
      "এই তালিকার সবগুলো এখান থেকে সরে যাবে (সবার জন্য)। ভর্তি ফি বাতিল হবে না — পরে \"ফি গ্রহণ\" পেজ থেকে সেগুলো নেওয়া যাবে।",
    clearConfirm: "ক্লিয়ার করুন",
    cleared: "তালিকা ক্লিয়ার করা হয়েছে",
    clearFailed: "ক্লিয়ার করতে সমস্যা হয়েছে",
    bulkPaid: (n: string) => `${n} জনের ভর্তি ফি একসাথে নেওয়া হয়েছে`,
    bulkPartial: (ok: string, failed: string) => `${ok} জনের ফি নেওয়া হয়েছে, ${failed} জনের ব্যর্থ হয়েছে`,
    enterAmount: "পরিমাণ দিন",
    paymentRecorded: "পেমেন্ট রেকর্ড করা হয়েছে",
    paymentFailed: "পেমেন্ট রেকর্ড করতে সমস্যা হয়েছে",
    enterWaiveAmount: "মওকুফের পরিমাণ দিন",
    enterWaiveReason: "মওকুফের কারণ লিখুন",
    waived: "ভর্তি ফি মওকুফ করা হয়েছে",
    waiveFailed: "মওকুফ করতে সমস্যা হয়েছে",
    title: "ভর্তি ফি পেন্ডিং",
    subtitle: "যেসব {{student}} আবেদন করেছে কিন্তু এখনও ভর্তি ফি পরিশোধ করেনি",
    clearing: "ক্লিয়ার হচ্ছে...",
    clearAll: "সব ক্লিয়ার করুন",
    searchPlaceholder: "নাম, রোল বা রেজিস্ট্রেশন নম্বর দিয়ে খুঁজুন...",
    selectedCount: (n: string) => `${n} জন নির্বাচিত হয়েছে`,
    collectSelected: "নির্বাচিত সবার ফি একসাথে নিন",
    empty: "কোনো {{student}}র ভর্তি ফি পেন্ডিং নেই — সব ভর্তি ফি পরিশোধিত বা মওকুফকৃত",
    selectAll: "সব নির্বাচন করুন",
    studentFallback: (id: string) => `{{student}} #${id}`,
    roll: "রোল",
    regNo: "রেজি. নং",
    dueDate: "নির্ধারিত তারিখ",
    collect: "ফি নিন",
    waive: "মওকুফ",
    payTitle: (name: string) => `ভর্তি ফি নিন — ${name}`,
    remaining: (amount: string) => `বাকি আছে: ৳${amount}`,
    confirmPayment: "পেমেন্ট নিশ্চিত করুন",
    waiveTitle: (name: string) => `ভর্তি ফি মওকুফ করুন — ${name}`,
    waiveAmount: "মওকুফের পরিমাণ (৳)",
    waiveFull: "সম্পূর্ণ মওকুফ করুন",
    reason: "কারণ",
    reasonPlaceholder: "যেমন: এতিম {{student}}, আর্থিক অসচ্ছলতা",
    confirmWaive: "মওকুফ নিশ্চিত করুন",
    bulkTitle: (n: string) => `নির্বাচিত ${n} জনের ভর্তি ফি একসাথে নিন`,
    bulkHint: "প্রতিটি নির্বাচিত {{student}}র বাকি থাকা সম্পূর্ণ ভর্তি ফি একসাথে পরিশোধিত হিসেবে রেকর্ড হবে।",
    confirmAll: "সবার পেমেন্ট নিশ্চিত করুন",
  },
  en: {
    clearTitle: "Clear the whole list?",
    clearMessage:
      "Everything in this list will be removed from here (for everyone). Admission fees are not cancelled — they can still be collected later from the \"Collect Fee\" page.",
    clearConfirm: "Clear",
    cleared: "List cleared",
    clearFailed: "Could not clear the list",
    bulkPaid: (n) => `Admission fee collected from ${n} together`,
    bulkPartial: (ok, failed) => `Collected from ${ok}, failed for ${failed}`,
    enterAmount: "Enter an amount",
    paymentRecorded: "Payment recorded",
    paymentFailed: "Could not record the payment",
    enterWaiveAmount: "Enter the waiver amount",
    enterWaiveReason: "Enter the waiver reason",
    waived: "Admission fee waived",
    waiveFailed: "Could not waive",
    title: "Pending Admission Fees",
    subtitle: "{{student}}s who applied but have not yet paid the admission fee",
    clearing: "Clearing...",
    clearAll: "Clear all",
    searchPlaceholder: "Search by name, roll or registration no....",
    selectedCount: (n) => `${n} selected`,
    collectSelected: "Collect fees of all selected",
    empty: "No pending admission fees — all are paid or waived",
    selectAll: "Select all",
    studentFallback: (id) => `{{student}} #${id}`,
    roll: "Roll",
    regNo: "Reg. No.",
    dueDate: "due date",
    collect: "Collect",
    waive: "Waive",
    payTitle: (name) => `Collect Admission Fee — ${name}`,
    remaining: (amount) => `Due: ৳${amount}`,
    confirmPayment: "Confirm payment",
    waiveTitle: (name) => `Waive Admission Fee — ${name}`,
    waiveAmount: "Waiver amount (৳)",
    waiveFull: "Waive in full",
    reason: "Reason",
    reasonPlaceholder: "e.g. orphan {{student}}, financial hardship",
    confirmWaive: "Confirm waiver",
    bulkTitle: (n) => `Collect admission fees of ${n} selected together`,
    bulkHint: "The full remaining admission fee of every selected {{student}} will be recorded as paid.",
    confirmAll: "Confirm all payments",
  },
  ar: {
    clearTitle: "مسح القائمة بالكامل؟",
    clearMessage:
      "سيُزال كل ما في هذه القائمة من هنا (للجميع). لن تُلغى رسوم القبول — ويمكن تحصيلها لاحقًا من صفحة \"تحصيل الرسوم\".",
    clearConfirm: "مسح",
    cleared: "تم مسح القائمة",
    clearFailed: "تعذّر مسح القائمة",
    bulkPaid: (n) => `تم تحصيل رسوم القبول من ${n} معًا`,
    bulkPartial: (ok, failed) => `تم التحصيل من ${ok}، وفشل لـ ${failed}`,
    enterAmount: "أدخل المبلغ",
    paymentRecorded: "تم تسجيل الدفعة",
    paymentFailed: "تعذّر تسجيل الدفعة",
    enterWaiveAmount: "أدخل مبلغ الإعفاء",
    enterWaiveReason: "اكتب سبب الإعفاء",
    waived: "تم الإعفاء من رسوم القبول",
    waiveFailed: "تعذّر الإعفاء",
    title: "رسوم القبول المعلّقة",
    subtitle: "الطلاب الذين قدّموا طلباتهم ولم يدفعوا رسوم القبول بعد",
    clearing: "جارٍ المسح...",
    clearAll: "مسح الكل",
    searchPlaceholder: "ابحث بالاسم أو رقم الجلوس أو رقم التسجيل...",
    selectedCount: (n) => `تم تحديد ${n}`,
    collectSelected: "تحصيل رسوم جميع المحددين",
    empty: "لا توجد رسوم قبول معلّقة — جميعها مدفوعة أو معفاة",
    selectAll: "تحديد الكل",
    studentFallback: (id) => `{{student}} #${id}`,
    roll: "رقم الجلوس",
    regNo: "رقم التسجيل",
    dueDate: "تاريخ الاستحقاق",
    collect: "تحصيل",
    waive: "إعفاء",
    payTitle: (name) => `تحصيل رسوم القبول — ${name}`,
    remaining: (amount) => `المتبقي: ৳${amount}`,
    confirmPayment: "تأكيد الدفع",
    waiveTitle: (name) => `الإعفاء من رسوم القبول — ${name}`,
    waiveAmount: "مبلغ الإعفاء (৳)",
    waiveFull: "إعفاء كامل",
    reason: "السبب",
    reasonPlaceholder: "مثال: طالب يتيم، ضائقة مالية",
    confirmWaive: "تأكيد الإعفاء",
    bulkTitle: (n) => `تحصيل رسوم قبول ${n} من المحددين معًا`,
    bulkHint: "سيُسجَّل كامل رسوم القبول المتبقية لكل طالب محدد كمدفوعة.",
    confirmAll: "تأكيد جميع الدفعات",
  },
});
