import { defineBilingualText } from "@madrasha/shared-ui/src/i18n";

/** All-institutions list, edit modal and trash page. */
export const madrasasText = defineBilingualText({
  bn: {
    // List page
    title: "সকল প্রতিষ্ঠান",
    subtitle: "প্ল্যাটফর্মের সব প্রতিষ্ঠানের তালিকা",
    trash: "ট্র্যাশ",
    createInstitution: "+ নতুন প্রতিষ্ঠান",
    allTypes: "সব ধরন",
    filterByType: "ধরন অনুযায়ী ফিল্টার",
    moveToTrash: "ট্র্যাশে পাঠান",
    moveOneToTrash: (name: string) => `"${name}" ট্র্যাশে পাঠাবেন?`,
    moveManyToTrash: (n: string) => `${n}টি প্রতিষ্ঠান ট্র্যাশে পাঠাবেন?`,
    moveNToTrash: (n: string) => `${n}টি ট্র্যাশে পাঠান`,
    selectedCount: (n: string) => `${n}টি প্রতিষ্ঠান নির্বাচিত`,
    deleting: "মুছে ফেলা হচ্ছে...",
    cleanSuccess: "প্রতিষ্ঠানের ডেটা ক্লিন করা হয়েছে",
    cleanFailed: "ডেটা ক্লিন করতে সমস্যা হয়েছে",

    // Edit modal
    editTitle: "প্রতিষ্ঠান এডিট",
    editSubtitle: "প্রতিষ্ঠানের মৌলিক তথ্য, ধরন/ভাষা, লিমিট, স্ট্যাটাস, ওয়েবসাইট স্ট্যাটাস এবং প্ল্যান আপডেট করুন।",
    name: "নাম",
    slug: "স্লাগ",
    address: "ঠিকানা",
    phone: "ফোন",
    plan: "প্ল্যান",
    noChange: "পরিবর্তন নেই",
    studentLimit: "শিক্ষার্থী লিমিট",
    userLimit: "ইউজার লিমিট",
    planStartDate: "প্ল্যান শুরুর তারিখ",
    startDateHint:
      "অনেক প্রতিষ্ঠান আগে থেকেই সাবস্ক্রিপশন ব্যবহার করছে — প্রকৃত শুরুর তারিখ বসিয়ে দিন, নাহলে আজকের তারিখ ধরা হবে।",
    institutionStatus: "প্রতিষ্ঠানের স্ট্যাটাস",
    websiteStatus: "ওয়েবসাইট স্ট্যাটাস",
    websiteActive: "সক্রিয়",
    websiteLimited: "সীমিত",
    websiteDisabled: "বন্ধ",
    customDomain: "কাস্টম ডোমেইন",
    customDomainHint:
      "এই প্রতিষ্ঠানের নিজস্ব ডোমেইন (DNS/SSL আলাদাভাবে সেট করতে হবে)। খালি রাখলে slug-path URL-ই ব্যবহার হবে।",
    loadingSetup: "বিভাগ ও মডিউল লোড হচ্ছে...",
    saveChanges: "পরিবর্তন সংরক্ষণ করুন",

    // Trash page
    trashTitle: "ট্র্যাশ",
    selected: (n: string) => `${n}টি নির্বাচিত`,
    permanentlyDeleteN: (n: string) => `${n}টি স্থায়ীভাবে মুছুন`,
    trashEmpty: "ট্র্যাশ খালি",
    selectAll: "সব নির্বাচন করুন",
    selectRow: (name: string) => `${name} নির্বাচন করুন`,
    deletedAt: "মুছে ফেলার সময়",
    restore: "ফিরিয়ে আনুন",
    deletePermanently: "স্থায়ীভাবে মুছুন",
    restored: "সফলভাবে ফিরিয়ে আনা হয়েছে",
    restoreFailed: "ফিরিয়ে আনা যায়নি",
    statsFailed: "মুছে ফেলার তথ্য লোড করা যায়নি",
    manyDeleted: (n: string) => `${n}টি প্রতিষ্ঠান স্থায়ীভাবে মুছে ফেলা হয়েছে`,
    oneDeleted: "স্থায়ীভাবে মুছে ফেলা হয়েছে",
    partialDeleted: (ok: string, failed: string) =>
      `${ok}টি মুছে ফেলা হয়েছে, ${failed}টি ব্যর্থ হয়েছে। Slug এখনও ব্যবহারে আছে।`,
    deleteFailed: "স্থায়ীভাবে মুছে ফেলা যায়নি। Slug এখনও ব্যবহারে আছে।",
    deletingProgress: (done: string, total: string) => `মুছে ফেলা হচ্ছে ${done}/${total}...`,
  },
  en: {
    title: "All Institutions",
    subtitle: "Platform-wide institution list",
    trash: "Trash",
    createInstitution: "+ Create Institution",
    allTypes: "All types",
    filterByType: "Filter by type",
    moveToTrash: "Move to Trash",
    moveOneToTrash: (name) => `Move "${name}" to Trash?`,
    moveManyToTrash: (n) => `Move ${n} institutions to Trash?`,
    moveNToTrash: (n) => `Move ${n} to Trash`,
    selectedCount: (n) => `${n} institutions selected`,
    deleting: "Deleting...",
    cleanSuccess: "Institution data cleaned",
    cleanFailed: "Could not clean the data",

    editTitle: "Edit Institution",
    editSubtitle: "Update the institution's basic info, type/language, limits, status, website status and plan.",
    name: "Name",
    slug: "Slug",
    address: "Address",
    phone: "Phone",
    plan: "Plan",
    noChange: "No change",
    studentLimit: "Student Limit",
    userLimit: "User Limit",
    planStartDate: "Plan Start Date",
    startDateHint:
      "Many institutions already had a subscription — enter the real start date, otherwise today is used.",
    institutionStatus: "Institution Status",
    websiteStatus: "Website Status",
    websiteActive: "Active",
    websiteLimited: "Limited",
    websiteDisabled: "Disabled",
    customDomain: "Custom Domain",
    customDomainHint:
      "This institution's own domain (DNS/SSL must be set up separately). Leave blank to use the slug-path URL.",
    loadingSetup: "Loading divisions & modules...",
    saveChanges: "Save changes",

    trashTitle: "Trash",
    selected: (n) => `${n} selected`,
    permanentlyDeleteN: (n) => `Permanently Delete ${n}`,
    trashEmpty: "Trash is empty",
    selectAll: "Select all",
    selectRow: (name) => `Select ${name}`,
    deletedAt: "Deleted At",
    restore: "Restore",
    deletePermanently: "Delete Permanently",
    restored: "Restored successfully",
    restoreFailed: "Restore failed",
    statsFailed: "Failed to load delete stats",
    manyDeleted: (n) => `${n} institutions permanently deleted`,
    oneDeleted: "Permanently deleted",
    partialDeleted: (ok, failed) => `${ok} deleted, ${failed} failed. Slug is still in use.`,
    deleteFailed: "Permanent delete failed. Slug is still in use.",
    deletingProgress: (done, total) => `Deleting ${done}/${total}...`,
  },
});
