import { defineText } from "@madrasha/shared-ui/src/i18n";

export const admissionPageText = defineText({
  bn: {
    errName: "{{student}}র নাম দিন",
    errSession: "{{session}} নির্বাচন করুন",
    errDivision: "{{division}} নির্বাচন করুন",
    errClass: "বর্তমান {{class}} নির্বাচন করুন",
    uploadExcelFirst: "Excel ফাইল আপলোড করুন",
    rowNoName: (row: string) => `সারি ${row}: {{student}}র নাম নেই`,
    rowNoDivision: (row: string) => `সারি ${row}: academic_division নেই`,
    rowNoClass: (row: string) => `সারি ${row}: current_class/class_id নেই`,
    templateNote: "আবশ্যক কলামগুলো লাল রঙ ও * চিহ্ন দিয়ে চিহ্নিত",
    genderGuide: "Gender Guide",
    guideName: "Name",
    male: "ছেলে",
    female: "মেয়ে",
    divisionGuide: "Division Guide",
    divisionName: "Division Name",
    classGuide: "Class Guide",
    className: "Class Name",
    divisionId: "Division ID",
    serverSlow:
      "সার্ভার থেকে উত্তর আসতে দেরি হচ্ছে - আবার আপলোডের আগে {{student}} তালিকা দেখে নিন, হয়তো ভর্তি হয়ে গেছে।",
    bulkFailed: "একসাথে ভর্তি ব্যর্থ হয়েছে ❌",
    fillRequired: "* চিহ্নিত প্রয়োজনীয় ফিল্ডগুলো পূরণ করুন",
    failed: "ব্যর্থ হয়েছে ❌",
    bulkUpload: "একসাথে আপলোড",
    pageTitle: "{{student}} ভর্তি",
    readmissionSuccess: "পুনঃভর্তি সফল হয়েছে ✅",
    admissionSuccess: "ভর্তি সফল হয়েছে ✅",
    previousSession: "পূর্বের সেশন:",
    newSession: "নতুন সেশন:",
    registrationNo: "রেজিস্ট্রেশন নম্বর",
    rollNo: "রোল নম্বর",
    awaitingApproval: "{{head}}র অনুমোদনের অপেক্ষায়",
    newAdmissionForm: "নতুন ভর্তি ফর্ম",
  },
  en: {
    errName: "Enter the {{student}}'s name",
    errSession: "Select the {{session}}",
    errDivision: "Select a {{division}}",
    errClass: "Select the current {{class}}",
    uploadExcelFirst: "Upload an Excel file",
    rowNoName: (row) => `Row ${row}: {{student}} name missing`,
    rowNoDivision: (row) => `Row ${row}: academic_division missing`,
    rowNoClass: (row) => `Row ${row}: current_class/class_id missing`,
    templateNote: "Required fields are marked with red color and * symbol",
    genderGuide: "Gender Guide",
    guideName: "Name",
    male: "Male",
    female: "Female",
    divisionGuide: "Division Guide",
    divisionName: "Division Name",
    classGuide: "Class Guide",
    className: "Class Name",
    divisionId: "Division ID",
    serverSlow:
      "The server is taking long to respond - check the {{student}} list before uploading again; the admissions may already be done.",
    bulkFailed: "Bulk admission failed ❌",
    fillRequired: "Fill in the required fields marked with *",
    failed: "Failed ❌",
    bulkUpload: "Bulk Upload",
    pageTitle: "{{student}} Admission",
    readmissionSuccess: "Re-admission successful ✅",
    admissionSuccess: "Admission successful ✅",
    previousSession: "Previous session:",
    newSession: "New session:",
    registrationNo: "Registration No.",
    rollNo: "Roll No.",
    awaitingApproval: "Awaiting {{head}}'s approval",
    newAdmissionForm: "New Admission Form",
  },
});
