import { defineText } from "@madrasha/shared-ui/src/i18n";

/** Shared by PendingAdmissionsPage + RejectedAdmissionsPage. */
export const admissionReviewText = defineText({
  bn: {
    // shared labels
    residential: "আবাসিক",
    nonResidential: "অনাবাসিক",
    none: "নেই",
    readmission: "পুনঃভর্তি",
    newAdmission: "নতুন",
    frequency: { ONE_TIME: "একবার", MONTHLY: "মাসিক", YEARLY: "বাৎসরিক" },
    feeDue: (due: string) => `বকেয়া ৳${due}`,
    feeWaived: "মওকুফকৃত",
    feePaid: "পরিশোধিত",
    selectedN: (n: string) => `${n}টি নির্বাচিত`,
    noName: "নাম নেই",
    rollLabel: "রোল:",
    fatherLabel: "পিতা:",
    phoneLabel: "ফোন:",
    classLabel: "{{class}}:",
    orphan: "এতিম",
    details: "বিস্তারিত",
    approve: "অনুমোদন",
    reject: "বাতিল",
    colName: "নাম",
    colRoll: "রোল",
    colFatherName: "পিতার নাম",
    colPhone: "ফোন",
    colClass: "{{class}}",
    colAdmissionType: "ভর্তির ধরন",
    colSpecial: "বিশেষ",
    colActions: "অ্যাকশন",
    detailTitle: (name: string) => `ভর্তি আবেদনের বিস্তারিত${name}`,
    studentInfo: "{{student}}র তথ্য",
    arabicName: "আরবি নাম",
    nid: "NID/জন্ম নিবন্ধন",
    gender: "লিঙ্গ",
    male: "ছেলে",
    female: "মেয়ে",
    dob: "জন্ম তারিখ",
    bloodGroup: "রক্তের গ্রুপ",
    residency: "আবাসিক/অনাবাসিক",
    previousInstitution: "পূর্ববর্তী প্রতিষ্ঠান",
    previousResult: "পূর্বের ফলাফল",
    determinedFees: "নির্ধারিত ফি",
    noFeesForClass: "এই {{class}}র জন্য কোনো নির্ধারিত ফি সেট করা নেই",
    examLinkedTitle:
      "নির্দিষ্ট একটি পরীক্ষার সাথে যুক্ত - ভর্তি অনুমোদনের সাথে সাথে এখনই বিল হবে না, পরীক্ষা আসন্ন হলে আলাদাভাবে বিল করা হবে",
    examLinkedTitleShort: "নির্দিষ্ট একটি পরীক্ষার সাথে যুক্ত - ভর্তি অনুমোদনের সাথে সাথে এখনই বিল হবে না",
    billedOnExam: "পরীক্ষা এলে বিল হবে",
    discountAmt: (n: string) => ` · ছাড় ৳${n}`,
    netAmt: (n: string) => ` · নেট ৳${n}`,
    guardianInfo: "অভিভাবকের তথ্য",
    fatherNid: "পিতার NID",
    fatherOccupation: "পিতার পেশা",
    motherName: "মাতার নাম",
    motherNid: "মাতার NID",
    motherOccupation: "মাতার পেশা",
    mobile: "মোবাইল নম্বর",
    altMobile: "বিকল্প মোবাইল নম্বর",
    altGuardian: "বিকল্প অভিভাবক (পিতা-মাতা ছাড়া)",
    relation: "সম্পর্ক",
    address: "ঠিকানা",
    addrDivision: "বিভাগ",
    district: "জেলা",
    thana: "থানা/উপজেলা",
    village: "গ্রাম",
    editInfo: "তথ্য সম্পাদনা করুন",
    approveFailed: "অনুমোদন করতে সমস্যা হয়েছে",
    approveConfirm: "অনুমোদন করুন",

    // pending page
    pendingLoadFailed: "পেন্ডিং ভর্তির তালিকা লোড করতে সমস্যা হয়েছে",
    validAmount: "সঠিক পরিমাণ দিন",
    enterReason: "কারণ লিখুন",
    discountSet: "ছাড় সেট করা হয়েছে",
    somethingWrong: "সমস্যা হয়েছে",
    discountRemoved: "ছাড় সরিয়ে ফেলা হয়েছে",
    approved: "ভর্তি অনুমোদন করা হয়েছে",
    approveTitle: "অনুমোদন করবেন?",
    approveMessage: (n: string) => `নির্বাচিত ${n}টি ভর্তি অনুমোদন করতে চান?`,
    approvedShort: "অনুমোদন করা হয়েছে",
    approvePartial: (ok: string, failed: string) => `${ok}টি অনুমোদন হয়েছে, ${failed}টি ব্যর্থ হয়েছে`,
    enterRejectReason: "বাতিলের কারণ লিখুন",
    rejected: "ভর্তি বাতিল করা হয়েছে",
    rejectFailed: "বাতিল করতে সমস্যা হয়েছে",
    rejectedShort: "বাতিল করা হয়েছে",
    rejectPartial: (ok: string, failed: string) => `${ok}টি বাতিল হয়েছে, ${failed}টি ব্যর্থ হয়েছে`,
    pendingTitle: "পেন্ডিং ভর্তি অনুমোদন",
    awaitingReview: (n: string) => `পর্যালোচনার অপেক্ষায় আছে: ${n} জন`,
    rejectedApplications: "বাতিল হওয়া আবেদন",
    backToList: "{{student}} তালিকায় ফিরে যান",
    approveSelected: "নির্বাচিতগুলো অনুমোদন করুন",
    rejectSelected: "নির্বাচিতগুলো বাতিল করুন",
    noPending: "অনুমোদনের অপেক্ষায় কোনো ভর্তি নেই",
    rejectReasonBulk: (n: string) => `ভর্তি বাতিলের কারণ — ${n}টি নির্বাচিত`,
    rejectReasonOne: (name: string) => `ভর্তি বাতিলের কারণ${name}`,
    rejectReasonPlaceholder: "বাতিলের কারণ লিখুন...",
    editDiscount: "ছাড় এডিট করুন",
    setDiscount: "ছাড়/মওকুফ করুন",
    remove: "সরিয়ে ফেলুন",
    discountAmount: "ছাড়ের পরিমাণ (৳)",
    reason: "কারণ",
    reasonPlaceholder: "যেমন: এতিম {{student}}",

    // rejected page
    rejectedLoadFailed: "বাতিল হওয়া আবেদনের তালিকা লোড করতে সমস্যা হয়েছে",
    thisApplication: "এই আবেদন",
    reapproveTitle: "পুনরায় অনুমোদন করবেন?",
    reapproveMessage: (name: string) =>
      `"${name}" পুনরায় অনুমোদন করা হবে — একজন সক্রিয় {{student}} হিসেবে রোল/রেজিস্ট্রেশন বসবে এবং ফি বিল হবে।`,
    reapproved: "ভর্তি পুনরায় অনুমোদন করা হয়েছে",
    reapproveBulkMessage: (n: string) =>
      `নির্বাচিত ${n}টি আবেদন পুনরায় অনুমোদন করা হবে — প্রত্যেকে সক্রিয় {{student}} হিসেবে রোল/রেজিস্ট্রেশন পাবে এবং ফি বিল হবে।`,
    reapproveSelected: "নির্বাচিতগুলো পুনরায় অনুমোদন",
    reapprovePartial: (ok: string, failed: string) => `${ok}টি পুনরায় অনুমোদন হয়েছে, ${failed}টি ব্যর্থ হয়েছে`,
    selectAllShort: "সব নির্বাচন",
    deleteForeverTitle: "স্থায়ীভাবে মুছে ফেলবেন?",
    deleteForeverMessage: (name: string) => `"${name}" আবেদনটি স্থায়ীভাবে মুছে যাবে। এটি আর ফিরিয়ে আনা যাবে না।`,
    deleteForeverBulk: (n: string) => `নির্বাচিত ${n}টি আবেদন স্থায়ীভাবে মুছে যাবে। এটি আর ফিরিয়ে আনা যাবে না।`,
    deleteConfirm: "মুছে ফেলুন",
    deletedForever: "আবেদনটি স্থায়ীভাবে মুছে ফেলা হয়েছে",
    deleteFailed: "মুছতে সমস্যা হয়েছে",
    deleted: "মুছে ফেলা হয়েছে",
    deletePartial: (ok: string, failed: string) => `${ok}টি মুছে ফেলা হয়েছে, ${failed}টি ব্যর্থ হয়েছে`,
    rejectedTitle: "বাতিল হওয়া ভর্তির আবেদন",
    totalN: (n: string) => `মোট ${n}টি`,
    sessionFiltered: " (নির্দিষ্ট সেশনে ফিল্টার করা)",
    goToPending: "পেন্ডিং ভর্তি অনুমোদনে যান",
    deleteSelectedForever: "নির্বাচিতগুলো স্থায়ীভাবে মুছুন",
    noRejected: "বাতিল হওয়া কোনো আবেদন নেই",
    reapprove: "পুনরায় অনুমোদন",
    deleteForever: "স্থায়ীভাবে মুছুন",
    rejectReasonCol: "বাতিলের কারণ",
    noReason: "কারণ উল্লেখ নেই",
    noReasonGiven: "কোনো কারণ উল্লেখ করা হয়নি",
    reapproveFeeNote:
      "পুনরায় অনুমোদন করলে এই ফিগুলো বিল হবে। ছাড়/মওকুফ এখান থেকে সেট করা যাবে না - অনুমোদনের পর প্রয়োজনে {{student}} তালিকা থেকে ইনভয়েসে মওকুফ প্রয়োগ করুন।",
  },
  en: {
    residential: "Residential",
    nonResidential: "Non-residential",
    none: "N/A",
    readmission: "Re-admission",
    newAdmission: "New",
    frequency: { ONE_TIME: "One-time", MONTHLY: "Monthly", YEARLY: "Yearly" },
    feeDue: (due) => `Due ৳${due}`,
    feeWaived: "Waived",
    feePaid: "Paid",
    selectedN: (n) => `${n} selected`,
    noName: "No name",
    rollLabel: "Roll:",
    fatherLabel: "Father:",
    phoneLabel: "Phone:",
    classLabel: "{{class}}:",
    orphan: "Orphan",
    details: "Details",
    approve: "Approve",
    reject: "Reject",
    colName: "Name",
    colRoll: "Roll",
    colFatherName: "Father's Name",
    colPhone: "Phone",
    colClass: "{{class}}",
    colAdmissionType: "Admission Type",
    colSpecial: "Notes",
    colActions: "Actions",
    detailTitle: (name) => `Admission Application Details${name}`,
    studentInfo: "{{student}} Information",
    arabicName: "Arabic Name",
    nid: "NID/Birth Reg.",
    gender: "Gender",
    male: "Male",
    female: "Female",
    dob: "Date of Birth",
    bloodGroup: "Blood Group",
    residency: "Residential/Non-residential",
    previousInstitution: "Previous Institution",
    previousResult: "Previous Result",
    determinedFees: "Assigned Fees",
    noFeesForClass: "No fees are set for this {{class}}",
    examLinkedTitle:
      "Linked to a specific exam - not billed at admission approval; billed separately when the exam approaches",
    examLinkedTitleShort: "Linked to a specific exam - not billed at admission approval",
    billedOnExam: "Billed at exam time",
    discountAmt: (n) => ` · discount ৳${n}`,
    netAmt: (n) => ` · net ৳${n}`,
    guardianInfo: "Guardian Information",
    fatherNid: "Father's NID",
    fatherOccupation: "Father's Occupation",
    motherName: "Mother's Name",
    motherNid: "Mother's NID",
    motherOccupation: "Mother's Occupation",
    mobile: "Mobile No.",
    altMobile: "Alternate Mobile No.",
    altGuardian: "Alternate Guardian (other than parents)",
    relation: "Relation",
    address: "Address",
    addrDivision: "Division",
    district: "District",
    thana: "Thana/Upazila",
    village: "Village",
    editInfo: "Edit Information",
    approveFailed: "Failed to approve",
    approveConfirm: "Approve",

    pendingLoadFailed: "Failed to load pending admissions",
    validAmount: "Enter a valid amount",
    enterReason: "Enter a reason",
    discountSet: "Discount set",
    somethingWrong: "Something went wrong",
    discountRemoved: "Discount removed",
    approved: "Admission approved",
    approveTitle: "Approve?",
    approveMessage: (n) => `Approve the ${n} selected admission(s)?`,
    approvedShort: "Approved",
    approvePartial: (ok, failed) => `${ok} approved, ${failed} failed`,
    enterRejectReason: "Enter the rejection reason",
    rejected: "Admission rejected",
    rejectFailed: "Failed to reject",
    rejectedShort: "Rejected",
    rejectPartial: (ok, failed) => `${ok} rejected, ${failed} failed`,
    pendingTitle: "Pending Admission Approval",
    awaitingReview: (n) => `Awaiting review: ${n}`,
    rejectedApplications: "Rejected Applications",
    backToList: "Back to {{student}} List",
    approveSelected: "Approve Selected",
    rejectSelected: "Reject Selected",
    noPending: "No admissions awaiting approval",
    rejectReasonBulk: (n) => `Rejection reason — ${n} selected`,
    rejectReasonOne: (name) => `Rejection reason${name}`,
    rejectReasonPlaceholder: "Enter the rejection reason...",
    editDiscount: "Edit Discount",
    setDiscount: "Discount/Waive",
    remove: "Remove",
    discountAmount: "Discount (৳)",
    reason: "Reason",
    reasonPlaceholder: "e.g. orphan {{student}}",

    rejectedLoadFailed: "Failed to load rejected applications",
    thisApplication: "this application",
    reapproveTitle: "Re-approve?",
    reapproveMessage: (name) =>
      `"${name}" will be re-approved — a roll/registration will be assigned as an active {{student}} and fees will be billed.`,
    reapproved: "Admission re-approved",
    reapproveBulkMessage: (n) =>
      `${n} selected application(s) will be re-approved — each gets a roll/registration as an active {{student}} and fees will be billed.`,
    reapproveSelected: "Re-approve Selected",
    reapprovePartial: (ok, failed) => `${ok} re-approved, ${failed} failed`,
    selectAllShort: "Select all",
    deleteForeverTitle: "Delete permanently?",
    deleteForeverMessage: (name) => `The application "${name}" will be permanently deleted. This cannot be undone.`,
    deleteForeverBulk: (n) => `${n} selected application(s) will be permanently deleted. This cannot be undone.`,
    deleteConfirm: "Delete",
    deletedForever: "Application permanently deleted",
    deleteFailed: "Failed to delete",
    deleted: "Deleted",
    deletePartial: (ok, failed) => `${ok} deleted, ${failed} failed`,
    rejectedTitle: "Rejected Admission Applications",
    totalN: (n) => `Total ${n}`,
    sessionFiltered: " (filtered to a session)",
    goToPending: "Go to Pending Approvals",
    deleteSelectedForever: "Permanently Delete Selected",
    noRejected: "No rejected applications",
    reapprove: "Re-approve",
    deleteForever: "Delete Permanently",
    rejectReasonCol: "Rejection Reason",
    noReason: "No reason given",
    noReasonGiven: "No reason was given",
    reapproveFeeNote:
      "These fees will be billed on re-approval. Discounts/waivers can't be set here - after approval, apply a waiver to the invoice from the {{student}} list if needed.",
  },
});
