import { defineText } from "@madrasha/shared-ui/src/i18n";

const columnsBn = {
  roll: "রোল নম্বর",
  registration: "রেজিস্ট্রেশন নম্বর",
  fatherName: "বাবার নাম",
  phone: "ফোন",
  academicYear: "{{session}}",
  division: "{{division}}",
  currentClass: "বর্তমান {{class}}",
  status: "স্ট্যাটাস",
  arabicName: "আরবি নাম",
  nid: "জন্ম সনদ/এনআইডি",
  gender: "লিঙ্গ",
  dob: "জন্ম তারিখ",
  age: "বয়স",
  bloodGroup: "রক্তের গ্রুপ",
  residencyType: "আবাসনের ধরন",
  isOrphan: "এতিম কিনা",
  previousInstitution: "পূর্ববর্তী প্রতিষ্ঠান",
  previousResult: "পূর্ববর্তী ফলাফল",
  admissionDate: "ভর্তির তারিখ",
  fatherArabicName: "বাবার আরবি নাম",
  fatherNid: "বাবার এনআইডি",
  fatherOccupation: "বাবার পেশা",
  motherName: "মায়ের নাম",
  motherNid: "মায়ের এনআইডি",
  motherOccupation: "মায়ের পেশা",
  guardianPhone2: "অভিভাবকের ফোন ২",
  altGuardianName: "বিকল্প অভিভাবকের নাম",
  altGuardianRelation: "সম্পর্ক",
  altGuardianPhone: "বিকল্প অভিভাবকের ফোন",
  altGuardianAddress: "বিকল্প অভিভাবকের ঠিকানা",
  addressDivision: "বিভাগ (ঠিকানা)",
  district: "জেলা",
  thana: "থানা",
  village: "গ্রাম",
  admissionStatus: "ভর্তির আবেদনের অবস্থা",
  admissionType: "ভর্তির ধরন",
};

export type StudentListColumnKey = keyof typeof columnsBn;

/** Student list page + shared student-feature strings. */
export const studentsText = defineText({
  bn: {
    columns: columnsBn as Record<StudentListColumnKey, string>,
    regNotFound: "এই রেজিস্ট্রেশন নম্বরে কোনো {{student}} পাওয়া যায়নি",
    none: "নেই",
    male: "ছেলে",
    female: "মেয়ে",
    residential: "আবাসিক",
    nonResidential: "অনাবাসিক",
    approved: "অনুমোদিত",
    rejected: "বাতিল",
    pending: "পেন্ডিং",
    readmission: "পুনঃভর্তি",
    newAdmission: "নতুন",
    loadFailed: "{{student}} তালিকা লোড করতে সমস্যা হয়েছে",
    trashTitle: "নির্বাচিত {{student}}দের ট্র্যাশে পাঠাবেন?",
    trashMessage: (n: string) => `${n} জন {{student}}কে ট্র্যাশে সরাতে চান? পরে প্রয়োজনে ট্র্যাশ থেকে ফিরিয়ে আনা যাবে।`,
    sendToTrash: "ট্র্যাশে পাঠান",
    sentToTrash: "ট্র্যাশে পাঠানো হয়েছে",
    title: "{{student}} তালিকা",
    totalStudents: (n: string) => `মোট {{student}}: ${n} জন`,
    newAdmission2: "+ নতুন {{student}} ভর্তি",
    searchPlaceholder: "রেজিস্ট্রেশন, রোল বা নাম দিয়ে সার্চ করুন",
    allSessions: "সব সেশন",
    allDivisions: "সব {{division}}",
    loadingClasses: "{{class}} লোড হচ্ছে...",
    allClasses: "সব {{class}}",
    selectDivisionFirst: "আগে {{division}} নির্বাচন করুন",
    allGenders: "সব লিঙ্গ",
    bulkUpdate: "বাল্ক আপডেট",
    selectedN: (n: string) => `${n} জন নির্বাচিত হয়েছে`,
    sending: "পাঠানো হচ্ছে...",
    noStudents: "কোনো {{student}} পাওয়া যায়নি",
    registrationLabel: "রেজিস্ট্রেশন:",
    roll: (n: string) => `রোল ${n}`,
    profile: "প্রোফাইল",
    showing: (from: string, to: string, total: string) => `দেখাচ্ছে ${from}–${to}, মোট ${total} জন`,
    perPage: (n: string) => `পাতায় ${n} জন`,
    prevPage: "আগের",
    nextPage: "পরের",
    pageOf: (p: string, total: string) => `পাতা ${p} / ${total}`,
  },
  en: {
    columns: {
      roll: "Roll No.",
      registration: "Registration No.",
      fatherName: "Father's Name",
      phone: "Phone",
      academicYear: "{{session}}",
      division: "{{division}}",
      currentClass: "Current {{class}}",
      status: "Status",
      arabicName: "Arabic Name",
      nid: "Birth Cert./NID",
      gender: "Gender",
      dob: "Date of Birth",
      age: "Age",
      bloodGroup: "Blood Group",
      residencyType: "Residency Type",
      isOrphan: "Orphan",
      previousInstitution: "Previous Institution",
      previousResult: "Previous Result",
      admissionDate: "Admission Date",
      fatherArabicName: "Father's Arabic Name",
      fatherNid: "Father's NID",
      fatherOccupation: "Father's Occupation",
      motherName: "Mother's Name",
      motherNid: "Mother's NID",
      motherOccupation: "Mother's Occupation",
      guardianPhone2: "Guardian Phone 2",
      altGuardianName: "Alternate Guardian Name",
      altGuardianRelation: "Relation",
      altGuardianPhone: "Alternate Guardian Phone",
      altGuardianAddress: "Alternate Guardian Address",
      addressDivision: "Division (Address)",
      district: "District",
      thana: "Thana",
      village: "Village",
      admissionStatus: "Application Status",
      admissionType: "Admission Type",
    },
    regNotFound: "No {{student}} found with this registration number",
    none: "N/A",
    male: "Male",
    female: "Female",
    residential: "Residential",
    nonResidential: "Non-residential",
    approved: "Approved",
    rejected: "Rejected",
    pending: "Pending",
    readmission: "Re-admission",
    newAdmission: "New",
    loadFailed: "Failed to load the {{student}} list",
    trashTitle: "Move selected {{student}}s to trash?",
    trashMessage: (n) => `Move ${n} {{student}}(s) to trash? They can be restored from the trash later if needed.`,
    sendToTrash: "Move to Trash",
    sentToTrash: "Moved to trash",
    title: "{{student}} List",
    totalStudents: (n) => `Total {{student}}s: ${n}`,
    newAdmission2: "+ New {{student}} Admission",
    searchPlaceholder: "Search by registration, roll or name",
    allSessions: "All sessions",
    allDivisions: "All {{division}}s",
    loadingClasses: "Loading {{class}}es...",
    allClasses: "All {{class}}es",
    selectDivisionFirst: "Select a {{division}} first",
    allGenders: "All genders",
    bulkUpdate: "Bulk Update",
    selectedN: (n) => `${n} selected`,
    sending: "Submitting...",
    noStudents: "No {{student}}s found",
    registrationLabel: "Registration:",
    roll: (n) => `Roll ${n}`,
    profile: "Profile",
    showing: (from, to, total) => `Showing ${from}–${to} of ${total}`,
    perPage: (n) => `${n} per page`,
    prevPage: "Previous",
    nextPage: "Next",
    pageOf: (p, total) => `Page ${p} / ${total}`,
  },
  ar: {
    columns: {
      roll: "رقم الجلوس",
      registration: "رقم التسجيل",
      fatherName: "اسم الأب",
      phone: "الهاتف",
      academicYear: "{{session}}",
      division: "{{division}}",
      currentClass: "{{class}} الحالي",
      status: "الحالة",
      arabicName: "الاسم العربي",
      nid: "شهادة الميلاد/الهوية",
      gender: "الجنس",
      dob: "تاريخ الميلاد",
      age: "العمر",
      bloodGroup: "فصيلة الدم",
      residencyType: "نوع السكن",
      isOrphan: "يتيم؟",
      previousInstitution: "المؤسسة السابقة",
      previousResult: "النتيجة السابقة",
      admissionDate: "تاريخ القبول",
      fatherArabicName: "اسم الأب بالعربية",
      fatherNid: "هوية الأب",
      fatherOccupation: "مهنة الأب",
      motherName: "اسم الأم",
      motherNid: "هوية الأم",
      motherOccupation: "مهنة الأم",
      guardianPhone2: "هاتف ولي الأمر 2",
      altGuardianName: "اسم ولي الأمر البديل",
      altGuardianRelation: "صلة القرابة",
      altGuardianPhone: "هاتف ولي الأمر البديل",
      altGuardianAddress: "عنوان ولي الأمر البديل",
      addressDivision: "المحافظة",
      district: "المديرية",
      thana: "المركز",
      village: "القرية",
      admissionStatus: "حالة طلب القبول",
      admissionType: "نوع القبول",
    },
    regNotFound: "لا يوجد طالب بهذا الرقم التسجيلي",
    none: "لا يوجد",
    male: "ذكر",
    female: "أنثى",
    residential: "داخلي",
    nonResidential: "خارجي",
    approved: "مقبول",
    rejected: "مرفوض",
    pending: "قيد الانتظار",
    readmission: "إعادة قبول",
    newAdmission: "جديد",
    loadFailed: "تعذّر تحميل قائمة الطلاب",
    trashTitle: "نقل الطلاب المحددين إلى سلة المهملات؟",
    trashMessage: (n) => `هل تريد نقل ${n} طالب إلى سلة المهملات؟ يمكن استعادتهم لاحقًا عند الحاجة.`,
    sendToTrash: "نقل إلى المهملات",
    sentToTrash: "تم النقل إلى المهملات",
    title: "قائمة الطلاب",
    totalStudents: (n) => `إجمالي الطلاب: ${n}`,
    newAdmission2: "+ قبول طالب جديد",
    searchPlaceholder: "ابحث برقم التسجيل أو الجلوس أو الاسم",
    allSessions: "كل الأعوام",
    allDivisions: "جميع المراحل",
    loadingClasses: "جارٍ تحميل الصفوف...",
    allClasses: "جميع الصفوف",
    selectDivisionFirst: "اختر {{division}} أولًا",
    allGenders: "كل الأجناس",
    bulkUpdate: "تحديث جماعي",
    selectedN: (n) => `تم تحديد ${n}`,
    sending: "جارٍ الإرسال...",
    noStudents: "لم يتم العثور على طلاب",
    registrationLabel: "التسجيل:",
    roll: (n) => `الجلوس ${n}`,
    profile: "الملف الشخصي",
    showing: (from, to, total) => `عرض ${from}–${to} من ${total}`,
    perPage: (n) => `${n} في الصفحة`,
    prevPage: "السابق",
    nextPage: "التالي",
    pageOf: (p, total) => `صفحة ${p} / ${total}`,
  },
});
