import { defineText } from "@madrasha/shared-ui/src/i18n";

export const namesManagerText = defineText({
  bn: {
    bnRequired: "বাংলা নাম আবশ্যক",
    placeholderBn: "বাংলায় নাম",
    ownerNameSuffix: (owner: string) => ` · ${owner}`,
    scriptWarning: {
      bn: "এই ঘরে শুধু বাংলায় লিখুন",
      ar: "এই ঘরে শুধু আরবিতে লিখুন",
      en: "এই ঘরে শুধু English-এ লিখুন",
    },
    nothingToDownload: "ডাউনলোড করার মতো কেউ নেই",
    rowsUnmatched: (n: string) => `${n} টি সারি মেলেনি`,
    wrongScriptDropped: (n: string) => `${n} ঘরে ভুল ভাষার অক্ষর বাদ দেওয়া হয়েছে`,
    importedNames: (people: string, names: string, suffix: string) =>
      `${people} জনের ${names} টি নাম বসানো হয়েছে — দেখে "সব সেভ করুন" চাপুন${suffix}`,
    noNewChanges: (suffix: string) => `কোনো নতুন পরিবর্তন পাওয়া যায়নি${suffix}`,
    excelReadFailed: "Excel ফাইল পড়া যায়নি",
    pastedRows: (n: string) => `${n} সারিতে পেস্ট হয়েছে`,
    bnEmpty: (n: string) => `${n} জনের বাংলা নাম খালি — বাংলা নাম আবশ্যক, সেগুলো সেভ হয়নি`,
    savedFailed: (ok: string, failed: string, err: string) => `${ok} টি সেভ হয়েছে, ${failed} টি ব্যর্থ${err}`,
    savedAll: (ok: string) => `${ok} জনের নাম সেভ হয়েছে`,
    discardTitle: "পরিবর্তন বাতিল করবেন?",
    discardMessage: (n: string) => `${n} টি সারির সেভ-না-করা পরিবর্তন মুছে যাবে।`,
    discardConfirm: "বাতিল করুন",
    leaveTitle: "সেভ না করেই চলে যাবেন?",
    leaveMessage: "কিছু নামের পরিবর্তন এখনো সেভ হয়নি। চলে গেলে সেগুলো হারিয়ে যাবে।",
    leaveConfirm: "না সেভ করে যান",
    roll: (n: string) => `রোল ${n}`,
    reg: (n: string) => `রেজি. ${n}`,
    title: "নাম (৩ ভাষা)",
    titleBilingual: "নাম (২ ভাষা)",
    subtitle: "বাংলা, আরবি ও ইংরেজি নাম এক জায়গা থেকে — Excel থেকে পুরো কলাম পেস্টও করা যায়।",
    subtitleBilingual: "বাংলা ও ইংরেজি নাম এক জায়গা থেকে — Excel থেকে পুরো কলাম পেস্টও করা যায়।",
    templateTitle: "বর্তমান ফিল্টারের তালিকাসহ Excel ফরম্যাট",
    downloadTemplate: "ফরম্যাট ডাউনলোড",
    uploadExcel: "Excel আপলোড",
    saveOrDiscardFirst: "আগে পরিবর্তন সেভ বা বাতিল করুন",
    stopEditing: "এডিট বন্ধ করুন",
    done: "সম্পন্ন",
    edit: "এডিট করুন",
    allLangsDone: "৩ ভাষাই আছে",
    allLangsDoneBilingual: "২ ভাষাই আছে",
    incomplete: "অসম্পূর্ণ",
    complete: "সম্পূর্ণ",
    all: "সব",
    readOnly: "নাম পরিবর্তনের অনুমতি আপনার নেই — শুধু দেখতে পারবেন।",
    keyboardHint: "Enter/↓ = নিচের ঘর · Tab = পাশের ঘর · Ctrl+S = সব সেভ",
    pasteHint: 'Excel থেকে কপি করা কলাম যেকোনো ঘরে পেস্ট করলে নিচের দিকে ভরে যাবে · অথবা "ফরম্যাট ডাউনলোড" করে পূরণ করে "Excel আপলোড" দিন',
    everyoneComplete: "সবার সব ভাষার নাম দেওয়া আছে",
    noneFound: "কাউকে পাওয়া যায়নি",
    tryChangingFilter: "ফিল্টার বা সার্চ পরিবর্তন করে দেখুন।",
    classAndRoll: "{{class}} ও রোল",
    designationAndReg: "পদবি ও রেজি.",
    showMore: "আরও দেখান",
    showingOf: (shown: string, total: string) => `${shown} / ${total} দেখানো হচ্ছে`,
    changesN: (n: string) => `${n} টি পরিবর্তন`,
    discard: "বাতিল",
    saveAll: "সব সেভ করুন",
  },
  en: {
    bnRequired: "Bangla name is required",
    placeholderBn: "Name in Bangla",
    ownerNameSuffix: (owner) => ` · ${owner}`,
    scriptWarning: {
      bn: "Write only in Bangla in this cell",
      ar: "Write only in Arabic in this cell",
      en: "Write only in English in this cell",
    },
    nothingToDownload: "No one to download",
    rowsUnmatched: (n) => `${n} row(s) not matched`,
    wrongScriptDropped: (n) => `wrong-script characters removed in ${n} cell(s)`,
    importedNames: (people, names, suffix) =>
      `${names} name(s) filled for ${people} people — review and press "Save All"${suffix}`,
    noNewChanges: (suffix) => `No new changes found${suffix}`,
    excelReadFailed: "Could not read the Excel file",
    pastedRows: (n) => `Pasted into ${n} row(s)`,
    bnEmpty: (n) => `${n} Bangla name(s) are empty — Bangla name is required; those were not saved`,
    savedFailed: (ok, failed, err) => `${ok} saved, ${failed} failed${err}`,
    savedAll: (ok) => `Names saved for ${ok}`,
    discardTitle: "Discard changes?",
    discardMessage: (n) => `Unsaved changes in ${n} row(s) will be lost.`,
    discardConfirm: "Discard",
    leaveTitle: "Leave without saving?",
    leaveMessage: "Some name changes are not saved yet. They will be lost if you leave.",
    leaveConfirm: "Leave without saving",
    roll: (n) => `Roll ${n}`,
    reg: (n) => `Reg. ${n}`,
    title: "Names (3 languages)",
    titleBilingual: "Names (2 languages)",
    subtitle: "Bangla, Arabic and English names in one place — whole columns can be pasted from Excel.",
    subtitleBilingual: "Bangla and English names in one place — whole columns can be pasted from Excel.",
    templateTitle: "Excel template with the current filtered list",
    downloadTemplate: "Download Template",
    uploadExcel: "Upload Excel",
    saveOrDiscardFirst: "Save or discard changes first",
    stopEditing: "Stop editing",
    done: "Done",
    edit: "Edit",
    allLangsDone: "All 3 languages",
    allLangsDoneBilingual: "Both languages",
    incomplete: "Incomplete",
    complete: "Complete",
    all: "All",
    readOnly: "You don't have permission to change names — view only.",
    keyboardHint: "Enter/↓ = cell below · Tab = next cell · Ctrl+S = save all",
    pasteHint: 'Paste a column copied from Excel into any cell to fill downward · or use "Download Template", fill it and "Upload Excel"',
    everyoneComplete: "Everyone has names in all languages",
    noneFound: "No one found",
    tryChangingFilter: "Try changing the filter or search.",
    classAndRoll: "{{class}} & Roll",
    designationAndReg: "Designation & Reg.",
    showMore: "Show more",
    showingOf: (shown, total) => `Showing ${shown} / ${total}`,
    changesN: (n) => `${n} change(s)`,
    discard: "Discard",
    saveAll: "Save All",
  },
  ar: {
    bnRequired: "الاسم بالبنغالية إلزامي",
    placeholderBn: "الاسم بالبنغالية",
    ownerNameSuffix: (owner) => ` · ${owner}`,
    scriptWarning: {
      bn: "اكتب بالبنغالية فقط في هذه الخانة",
      ar: "اكتب بالعربية فقط في هذه الخانة",
      en: "اكتب بالإنجليزية فقط في هذه الخانة",
    },
    nothingToDownload: "لا يوجد أحد للتنزيل",
    rowsUnmatched: (n) => `${n} صف غير مطابق`,
    wrongScriptDropped: (n) => `حُذفت أحرف بلغة خاطئة في ${n} خانة`,
    importedNames: (people, names, suffix) =>
      `تم إدخال ${names} اسمًا لـ ${people} شخصًا — راجعها ثم اضغط "حفظ الكل"${suffix}`,
    noNewChanges: (suffix) => `لا توجد تغييرات جديدة${suffix}`,
    excelReadFailed: "تعذّرت قراءة ملف Excel",
    pastedRows: (n) => `تم اللصق في ${n} صف`,
    bnEmpty: (n) => `${n} اسم بالبنغالية فارغ — الاسم بالبنغالية إلزامي، ولم تُحفظ`,
    savedFailed: (ok, failed, err) => `حُفظ ${ok}، وفشل ${failed}${err}`,
    savedAll: (ok) => `تم حفظ أسماء ${ok}`,
    discardTitle: "تجاهل التغييرات؟",
    discardMessage: (n) => `ستُفقد التغييرات غير المحفوظة في ${n} صف.`,
    discardConfirm: "تجاهل",
    leaveTitle: "المغادرة دون حفظ؟",
    leaveMessage: "بعض تغييرات الأسماء لم تُحفظ بعد، وستُفقد إذا غادرت.",
    leaveConfirm: "مغادرة دون حفظ",
    roll: (n) => `الجلوس ${n}`,
    reg: (n) => `التسجيل ${n}`,
    title: "الأسماء (3 لغات)",
    titleBilingual: "الأسماء (لغتان)",
    subtitle: "الأسماء بالبنغالية والعربية والإنجليزية في مكان واحد — ويمكن لصق أعمدة كاملة من Excel.",
    subtitleBilingual: "الأسماء بالبنغالية والإنجليزية في مكان واحد — ويمكن لصق أعمدة كاملة من Excel.",
    templateTitle: "قالب Excel بقائمة التصفية الحالية",
    downloadTemplate: "تنزيل القالب",
    uploadExcel: "رفع Excel",
    saveOrDiscardFirst: "احفظ التغييرات أو تجاهلها أولًا",
    stopEditing: "إيقاف التعديل",
    done: "تم",
    edit: "تعديل",
    allLangsDone: "اللغات الثلاث مكتملة",
    allLangsDoneBilingual: "اللغتان مكتملتان",
    incomplete: "غير مكتمل",
    complete: "مكتمل",
    all: "الكل",
    readOnly: "ليست لديك صلاحية تغيير الأسماء — العرض فقط.",
    keyboardHint: "Enter/↓ = الخانة التالية أسفل · Tab = الخانة المجاورة · Ctrl+S = حفظ الكل",
    pasteHint: 'الصق عمودًا منسوخًا من Excel في أي خانة ليُملأ إلى الأسفل · أو استخدم "تنزيل القالب" ثم "رفع Excel"',
    everyoneComplete: "أسماء الجميع مكتملة بكل اللغات",
    noneFound: "لم يتم العثور على أحد",
    tryChangingFilter: "جرّب تغيير التصفية أو البحث.",
    classAndRoll: "{{class}} والجلوس",
    designationAndReg: "المسمى والتسجيل",
    showMore: "عرض المزيد",
    showingOf: (shown, total) => `عرض ${shown} / ${total}`,
    changesN: (n) => `${n} تغيير`,
    discard: "تجاهل",
    saveAll: "حفظ الكل",
  },
});
