import { defineText } from "@madrasha/shared-ui/src/i18n";

export const profile360Text = defineText({
  bn: {
    tabs: { overview: "ওভারভিউ", academic: "একাডেমিক", attendance: "উপস্থিতি", financial: "আর্থিক", library: "লাইব্রেরি" },
    attendanceStatus: { PRESENT: "উপস্থিত", ABSENT: "অনুপস্থিত", LATE: "বিলম্বে", LEAVE: "ছুটি" } as Record<string, string>,
    libraryStatus: { BORROWED: "ধারে দেওয়া আছে", RETURNED: "ফেরত দেওয়া হয়েছে", LOST: "হারিয়ে গেছে" } as Record<string, string>,
    promotionStatus: { PROMOTED: "উন্নীত", RETAINED: "অবস্থান", TRANSFERRED: "স্থানান্তরিত" } as Record<string, string>,
    invoiceStatus: { UNPAID: "বকেয়া", PARTIALLY_PAID: "আংশিক পরিশোধিত", PAID: "পরিশোধিত", WAIVED: "মওকুফ" } as Record<string, string>,
    loadFailed: "প্রোফাইল লোড করা যায়নি",
    notFound: "{{student}} পাওয়া যায়নি",
    profileTitle: "{{student}} প্রোফাইল",
    subtitle: (cls: string, roll: string, reg: string) => `${cls} · রোল ${roll} · রেজি. ${reg}`,
    none: "নেই",
    edit: "সম্পাদনা",
    printIdCard: "আইডি কার্ড প্রিন্ট",
    downloadMarksheet: "মার্কশিট ডাউনলোড",
    collectFee: "ফি কালেক্ট",
    attendanceRate: "হাজিরার হার",
    publishedResults: "প্রকাশিত ফলাফল",
    dueFee: "বকেয়া ফি",
    libraryRecords: "লাইব্রেরি রেকর্ড",
    basicInfo: "মৌলিক তথ্য",
    fatherName: "পিতার নাম",
    guardianPhone: "অভিভাবকের ফোন",
    session: "{{session}}",
    admissionDate: "ভর্তির তারিখ",
    state: "অবস্থা",
    photo: "ছবি",
    noPhoto: "ছবি নেই",
    examResults: "পরীক্ষার ফলাফল",
    exam: "পরীক্ষা",
    class: "{{class}}",
    totalMarks: "মোট নম্বর",
    average: "গড়",
    grade: "গ্রেড",
    rank: "মেধাক্রম",
    noResults: "কোনো ফলাফল পাওয়া যায়নি",
    published: "প্রকাশিত",
    draft: "খসড়া",
    promotionHistory: "পদোন্নতির ইতিহাস",
    rollChange: "রোল পরিবর্তন",
    date: "তারিখ",
    noInfo: "কোনো তথ্য নেই",
    present: "উপস্থিত",
    absent: "অনুপস্থিত",
    late: "বিলম্বে",
    recentRecords: "সাম্প্রতিক রেকর্ড (গত ৩০ দিন)",
    noRecords: "কোনো রেকর্ড নেই",
    totalBilled: "মোট বিল",
    paid: "পরিশোধিত",
    waived: "মওকুফ",
    due: "বকেয়া",
    recentInvoices: "সাম্প্রতিক ইনভয়েস",
    head: "খাত",
    dueDate: "নির্ধারিত তারিখ",
    amount: "পরিমাণ",
    noInvoices: "কোনো ইনভয়েস নেই",
    bookName: "বইয়ের নাম",
    borrowedDate: "নেওয়ার তারিখ",
    returnDate: "ফেরতের তারিখ",
    fine: "জরিমানা",
  },
  en: {
    tabs: { overview: "Overview", academic: "Academic", attendance: "Attendance", financial: "Financial", library: "Library" },
    attendanceStatus: { PRESENT: "Present", ABSENT: "Absent", LATE: "Late", LEAVE: "Leave" },
    libraryStatus: { BORROWED: "Borrowed", RETURNED: "Returned", LOST: "Lost" },
    promotionStatus: { PROMOTED: "Promoted", RETAINED: "Retained", TRANSFERRED: "Transferred" },
    invoiceStatus: { UNPAID: "Unpaid", PARTIALLY_PAID: "Partially paid", PAID: "Paid", WAIVED: "Waived" },
    loadFailed: "Could not load the profile",
    notFound: "{{student}} not found",
    profileTitle: "{{student}} Profile",
    subtitle: (cls, roll, reg) => `${cls} · Roll ${roll} · Reg. ${reg}`,
    none: "N/A",
    edit: "Edit",
    printIdCard: "Print ID Card",
    downloadMarksheet: "Download Marksheet",
    collectFee: "Collect Fee",
    attendanceRate: "Attendance Rate",
    publishedResults: "Published Results",
    dueFee: "Due Fees",
    libraryRecords: "Library Records",
    basicInfo: "Basic Information",
    fatherName: "Father's Name",
    guardianPhone: "Guardian Phone",
    session: "{{session}}",
    admissionDate: "Admission Date",
    state: "Status",
    photo: "Photo",
    noPhoto: "No photo",
    examResults: "Exam Results",
    exam: "Exam",
    class: "{{class}}",
    totalMarks: "Total Marks",
    average: "Average",
    grade: "Grade",
    rank: "Rank",
    noResults: "No results found",
    published: "Published",
    draft: "Draft",
    promotionHistory: "Promotion History",
    rollChange: "Roll Change",
    date: "Date",
    noInfo: "No data",
    present: "Present",
    absent: "Absent",
    late: "Late",
    recentRecords: "Recent Records (last 30 days)",
    noRecords: "No records",
    totalBilled: "Total Billed",
    paid: "Paid",
    waived: "Waived",
    due: "Due",
    recentInvoices: "Recent Invoices",
    head: "Category",
    dueDate: "Due Date",
    amount: "Amount",
    noInvoices: "No invoices",
    bookName: "Book Title",
    borrowedDate: "Borrowed On",
    returnDate: "Return Date",
    fine: "Fine",
  },
  ar: {
    tabs: { overview: "نظرة عامة", academic: "الأكاديمي", attendance: "الحضور", financial: "المالية", library: "المكتبة" },
    attendanceStatus: { PRESENT: "حاضر", ABSENT: "غائب", LATE: "متأخر", LEAVE: "إجازة" },
    libraryStatus: { BORROWED: "مُعار", RETURNED: "مُعاد", LOST: "مفقود" },
    promotionStatus: { PROMOTED: "مُرفَّع", RETAINED: "باقٍ", TRANSFERRED: "منقول" },
    invoiceStatus: { UNPAID: "غير مدفوع", PARTIALLY_PAID: "مدفوع جزئيًا", PAID: "مدفوع", WAIVED: "معفى" },
    loadFailed: "تعذّر تحميل الملف",
    notFound: "لم يتم العثور على الطالب",
    profileTitle: "ملف الطالب",
    subtitle: (cls, roll, reg) => `${cls} · الجلوس ${roll} · التسجيل ${reg}`,
    none: "لا يوجد",
    edit: "تعديل",
    printIdCard: "طباعة البطاقة",
    downloadMarksheet: "تنزيل كشف الدرجات",
    collectFee: "تحصيل الرسوم",
    attendanceRate: "نسبة الحضور",
    publishedResults: "النتائج المنشورة",
    dueFee: "الرسوم المستحقة",
    libraryRecords: "سجلات المكتبة",
    basicInfo: "البيانات الأساسية",
    fatherName: "اسم الأب",
    guardianPhone: "هاتف ولي الأمر",
    session: "{{session}}",
    admissionDate: "تاريخ القبول",
    state: "الحالة",
    photo: "الصورة",
    noPhoto: "لا توجد صورة",
    examResults: "نتائج الامتحانات",
    exam: "الامتحان",
    class: "{{class}}",
    totalMarks: "مجموع الدرجات",
    average: "المعدل",
    grade: "التقدير",
    rank: "الترتيب",
    noResults: "لا توجد نتائج",
    published: "منشورة",
    draft: "مسودة",
    promotionHistory: "سجل الترفيع",
    rollChange: "تغيير رقم الجلوس",
    date: "التاريخ",
    noInfo: "لا توجد بيانات",
    present: "حاضر",
    absent: "غائب",
    late: "متأخر",
    recentRecords: "السجلات الأخيرة (آخر 30 يومًا)",
    noRecords: "لا توجد سجلات",
    totalBilled: "إجمالي الفواتير",
    paid: "المدفوع",
    waived: "المعفى",
    due: "المستحق",
    recentInvoices: "أحدث الفواتير",
    head: "البند",
    dueDate: "تاريخ الاستحقاق",
    amount: "المبلغ",
    noInvoices: "لا توجد فواتير",
    bookName: "اسم الكتاب",
    borrowedDate: "تاريخ الاستعارة",
    returnDate: "تاريخ الإرجاع",
    fine: "الغرامة",
  },
});
