import { defineText } from "@madrasha/shared-ui/src/i18n";

export const studentsDashboardText = defineText({
  bn: {
    approved: "অনুমোদিত",
    pending: "পেন্ডিং",
    rejected: "বাতিল",
    totalActive: "মোট সক্রিয় {{student}}",
    male: "ছাত্র",
    female: "ছাত্রী",
    pendingAdmissions: "পেন্ডিং ভর্তি",
    quickActions: "দ্রুত অ্যাকশন",
    newAdmission: "নতুন ভর্তি",
    approvePending: "পেন্ডিং ভর্তি অনুমোদন",
    rejectedApplications: "বাতিল হওয়া আবেদন",
    students: "{{student}} সমূহ",
    promotion: "{{student}} প্রমোশন",
    admissionTrend: "ভর্তির প্রবণতা",
    last12Months: "গত ১২ মাস",
    admissions: "ভর্তি",
    admissionStatus: "ভর্তির অবস্থা",
    allApplications: "সর্বমোট আবেদন",
    byClass: "{{class}} অনুযায়ী {{student}}",
    byClassSubtitle: "সক্রিয় ও অনুমোদিত {{student}} সংখ্যা",
    studentsSeries: "{{student}}",
  },
  en: {
    approved: "Approved",
    pending: "Pending",
    rejected: "Rejected",
    totalActive: "Total Active {{student}}s",
    male: "Boys",
    female: "Girls",
    pendingAdmissions: "Pending Admissions",
    quickActions: "Quick Actions",
    newAdmission: "New Admission",
    approvePending: "Approve Pending Admissions",
    rejectedApplications: "Rejected Applications",
    students: "{{student}}s",
    promotion: "{{student}} Promotion",
    admissionTrend: "Admission Trend",
    last12Months: "Last 12 months",
    admissions: "Admissions",
    admissionStatus: "Admission Status",
    allApplications: "All applications",
    byClass: "{{student}}s by {{class}}",
    byClassSubtitle: "Active and approved {{student}}s",
    studentsSeries: "{{student}}s",
  },
  ar: {
    approved: "مقبول",
    pending: "قيد الانتظار",
    rejected: "مرفوض",
    totalActive: "إجمالي الطلاب النشطين",
    male: "طلاب",
    female: "طالبات",
    pendingAdmissions: "طلبات قبول معلقة",
    quickActions: "إجراءات سريعة",
    newAdmission: "قبول جديد",
    approvePending: "اعتماد طلبات القبول المعلقة",
    rejectedApplications: "الطلبات المرفوضة",
    students: "الطلاب",
    promotion: "ترفيع الطلاب",
    admissionTrend: "اتجاه القبول",
    last12Months: "آخر 12 شهرًا",
    admissions: "القبول",
    admissionStatus: "حالة القبول",
    allApplications: "إجمالي الطلبات",
    byClass: "الطلاب حسب الصف",
    byClassSubtitle: "عدد الطلاب النشطين والمقبولين",
    studentsSeries: "الطلاب",
  },
});
