import { defineText } from "@madrasha/shared-ui/src/i18n";

export const photoManagerPageText = defineText({
  bn: {
    saveFailed: (name: string) => `${name} — ছবি সংরক্ষণ করা যায়নি`,
    readFailed: "ছবিটি পড়া যায়নি — অন্য একটি ফাইল দিন",
    removeTitle: "ছবি মুছবেন?",
    removeMessage: (name: string) => `${name}-এর ছবি মুছে ফেলা হবে।`,
    title: "ছবি আপলোড",
    subtitle: "শুধু ছবি যোগ/পরিবর্তন — প্রতিটি ছবি সঙ্গে সঙ্গে সংরক্ষিত হয়।",
    bulkUpload: "একসাথে আপলোড",
    seriesHint: "তালিকায় যাদের ছবি নেই তাদের একে একে ছবি তুলুন",
    seriesMode: "ক্যামেরা সিরিজ মোড",
    hasPhoto: "ছবি আছে",
    noPhoto: "ছবি নেই",
    all: "সব",
    readOnly: "ছবি পরিবর্তনের অনুমতি আপনার নেই — শুধু দেখতে পারবেন।",
    allDone: "সবার ছবি দেওয়া হয়েছে",
    noneFound: "কাউকে পাওয়া যায়নি",
    tryChangingFilter: "ফিল্টার বা সার্চ পরিবর্তন করে দেখুন।",
    showMore: "আরও দেখান",
    showingOf: (shown: string, total: string) => `${shown} / ${total} দেখানো হচ্ছে`,
    rollSuffix: (n: string) => ` · রোল ${n}`,
  },
  en: {
    saveFailed: (name) => `${name} — could not save the photo`,
    readFailed: "Could not read the image — please choose another file",
    removeTitle: "Remove photo?",
    removeMessage: (name) => `${name}'s photo will be removed.`,
    title: "Photo Upload",
    subtitle: "Add/change photos only — each photo is saved immediately.",
    bulkUpload: "Bulk Upload",
    seriesHint: "Photograph everyone in the list without a photo, one by one",
    seriesMode: "Camera Series Mode",
    hasPhoto: "Has photo",
    noPhoto: "No photo",
    all: "All",
    readOnly: "You don't have permission to change photos — view only.",
    allDone: "Everyone has a photo",
    noneFound: "No one found",
    tryChangingFilter: "Try changing the filter or search.",
    showMore: "Show more",
    showingOf: (shown, total) => `Showing ${shown} / ${total}`,
    rollSuffix: (n) => ` · Roll ${n}`,
  },
  ar: {
    saveFailed: (name) => `${name} — تعذّر حفظ الصورة`,
    readFailed: "تعذّرت قراءة الصورة — اختر ملفًا آخر",
    removeTitle: "حذف الصورة؟",
    removeMessage: (name) => `سيتم حذف صورة ${name}.`,
    title: "رفع الصور",
    subtitle: "إضافة/تغيير الصور فقط — تُحفظ كل صورة فورًا.",
    bulkUpload: "رفع جماعي",
    seriesHint: "صوّر كل من ليس له صورة في القائمة واحدًا تلو الآخر",
    seriesMode: "وضع التصوير المتتابع",
    hasPhoto: "له صورة",
    noPhoto: "بلا صورة",
    all: "الكل",
    readOnly: "ليست لديك صلاحية تغيير الصور — العرض فقط.",
    allDone: "تمت إضافة صور الجميع",
    noneFound: "لم يتم العثور على أحد",
    tryChangingFilter: "جرّب تغيير التصفية أو البحث.",
    showMore: "عرض المزيد",
    showingOf: (shown, total) => `عرض ${shown} / ${total}`,
    rollSuffix: (n) => ` · الجلوس ${n}`,
  },
});
