import { defineText } from "@madrasha/shared-ui/src/i18n";

export const studentProfilePageText = defineText({
  bn: {
    loadFailed: "{{student}}র তথ্য লোড করা যায়নি",
    updated: "সফলভাবে আপডেট হয়েছে",
    updateFailed: "আপডেট করা যায়নি",
    deleteTitle: "{{student}} মুছবেন?",
    deleteMessage: "এই {{student}}কে ট্র্যাশে সরাতে চান? পরে প্রয়োজনে ট্র্যাশ থেকে ফিরিয়ে আনা যাবে।",
    moveToTrash: "ট্র্যাশে সরান",
    movedToTrash: "ট্র্যাশে সরানো হয়েছে",
    deactivateTitle: "{{student}}কে নিষ্ক্রিয় করবেন?",
    activateTitle: "{{student}}কে সক্রিয় করবেন?",
    deactivateMessage:
      "নিষ্ক্রিয় {{student}} হাজিরা, পরীক্ষা ও বিভিন্ন তালিকায় আসবে না। এটি বহিষ্কার নয় — রেকর্ড থাকবে, পরে চাইলে আবার সক্রিয় করা যাবে।",
    activateMessage: "এই {{student}}কে আবার সক্রিয় করতে চান?",
    deactivate: "নিষ্ক্রিয় করুন",
    activate: "সক্রিয় করুন",
    deactivated: "নিষ্ক্রিয় করা হয়েছে",
    activated: "সক্রিয় করা হয়েছে",
    actionFailed: "করা যায়নি",
    expelTitle: "{{student}}কে বহিষ্কার করবেন?",
    unexpelTitle: "বহিষ্কার বাতিল করবেন?",
    expelMessage: "এই {{student}}কে বহিষ্কার করা হবে। রেকর্ড ট্র্যাশে যাবে না, পরে চাইলে বহিষ্কার বাতিল করা যাবে।",
    unexpelMessage: "এই {{student}}র বহিষ্কার অবস্থা বাতিল করে আবার সক্রিয় করতে চান?",
    expel: "বহিষ্কার করুন",
    expelled: "বহিষ্কার করা হয়েছে",
    unexpelled: "বহিষ্কার বাতিল করা হয়েছে",
    selectSession: "সেশন নির্বাচন করুন",
    transferDone: (roll: string) => `সেশন ট্রান্সফার সফল হয়েছে (নতুন রোল: ${roll})`,
    transferFailed: "সেশন ট্রান্সফার করা যায়নি",
    enterCardUid: "কার্ড UID লিখুন",
    cardAssigned: "কার্ড যুক্ত করা হয়েছে",
    cardFailed: "কার্ড যুক্ত করা যায়নি",
    roll: (v: string) => `রোল ${v}`,
    reg: (v: string) => `রেজি. ${v}`,
    none: "নেই",
    searchOther: "অন্য {{student}} খুঁজুন — নাম / রোল / রেজি. / {{class}}",
    searchOtherAria: "অন্য {{student}} খুঁজুন",
    notFound: "কোনো {{student}} পাওয়া যায়নি",
    title: "{{student}} প্রোফাইল",
    sessionTransfer: "সেশন ট্রান্সফার",
    assignCard: "RFID কার্ড যুক্ত করুন",
    inactive: "নিষ্ক্রিয়",
    unexpel: "বহিষ্কার বাতিল",
    expelShort: "বহিষ্কার",
    currentSession: "বর্তমান সেশন:",
    transferNote: "— এই {{student}}কে সরাসরি নতুন সেশনে নিয়ে যাওয়া হবে, রোল স্বয়ংক্রিয়ভাবে নতুন করে বসবে।",
    newSession: "নতুন সেশন",
    activeSuffix: " (সক্রিয়)",
    rollOptional: "রোল নম্বর (ঐচ্ছিক)",
    rollPlaceholder: "খালি রাখলে স্বয়ংক্রিয়ভাবে পরবর্তী রোল বসবে",
    reasonOptional: "কারণ (ঐচ্ছিক)",
    transferring: "ট্রান্সফার হচ্ছে...",
    transfer: "ট্রান্সফার করুন",
    currentCard: "বর্তমান কার্ড:",
    tapCard: "কার্ডটি রিডারে ট্যাপ করুন অথবা ম্যানুয়ালি লিখুন",
  },
  en: {
    loadFailed: "Failed to load {{student}}",
    updated: "Updated successfully",
    updateFailed: "Update failed",
    deleteTitle: "Delete {{student}}?",
    deleteMessage: "Move this {{student}} to trash? They can be restored from the trash later if needed.",
    moveToTrash: "Move to Trash",
    movedToTrash: "Moved to trash",
    deactivateTitle: "Deactivate this {{student}}?",
    activateTitle: "Activate this {{student}}?",
    deactivateMessage:
      "An inactive {{student}} won't appear in attendance, exams or lists. This is not expulsion — the record stays and can be reactivated later.",
    activateMessage: "Activate this {{student}} again?",
    deactivate: "Deactivate",
    activate: "Activate",
    deactivated: "Deactivated",
    activated: "Activated",
    actionFailed: "Action failed",
    expelTitle: "Expel this {{student}}?",
    unexpelTitle: "Revoke expulsion?",
    expelMessage: "This {{student}} will be expelled. The record won't go to trash; the expulsion can be revoked later.",
    unexpelMessage: "Revoke this {{student}}'s expulsion and make them active again?",
    expel: "Expel",
    expelled: "Expelled",
    unexpelled: "Expulsion revoked",
    selectSession: "Select a session",
    transferDone: (roll) => `Session transfer successful (new roll: ${roll})`,
    transferFailed: "Session transfer failed",
    enterCardUid: "Enter the card UID",
    cardAssigned: "Card assigned",
    cardFailed: "Could not assign the card",
    roll: (v) => `Roll ${v}`,
    reg: (v) => `Reg. ${v}`,
    none: "N/A",
    searchOther: "Find another {{student}} — name / roll / reg. / {{class}}",
    searchOtherAria: "Find another {{student}}",
    notFound: "No {{student}} found",
    title: "{{student}} Profile",
    sessionTransfer: "Session Transfer",
    assignCard: "Assign RFID Card",
    inactive: "Deactivate",
    unexpel: "Revoke Expulsion",
    expelShort: "Expel",
    currentSession: "Current session:",
    transferNote: "— this {{student}} will be moved straight to the new session; the roll is reassigned automatically.",
    newSession: "New Session",
    activeSuffix: " (active)",
    rollOptional: "Roll No. (optional)",
    rollPlaceholder: "Leave blank to assign the next roll automatically",
    reasonOptional: "Reason (optional)",
    transferring: "Transferring...",
    transfer: "Transfer",
    currentCard: "Current card:",
    tapCard: "Tap the card on the reader or type it manually",
  },
});
