import { defineText } from "@madrasha/shared-ui/src/i18n";

export const promotionText = defineText({
  bn: {
    status: {
      PROMOTED: "উত্তীর্ণ (পরের {{class}}তে)",
      RETAINED: "অকৃতকার্য (একই {{class}}তে থাকবে)",
      TRANSFERRED: "স্থানান্তরিত",
    },
    result: { PASS: "পাস", FAIL: "ফেল", ABSENT: "অনুপস্থিত", NO_RESULT: "ফলাফল নেই" } as Record<string, string>,
    selectFirst: "আগে {{class}} ও {{session}} নির্বাচন করুন",
    previewFailed: "প্রিভিউ লোড করতে সমস্যা হয়েছে",
    done: (p: string, r: string, t: string) => `প্রমোশন সম্পন্ন হয়েছে — উত্তীর্ণ: ${p}, অকৃতকার্য: ${r}, স্থানান্তরিত: ${t}`,
    failed: "প্রমোশন সম্পন্ন করতে সমস্যা হয়েছে",
    title: "{{student}} প্রমোশন",
    subtitle: "এক {{class}} থেকে পরের {{class}}তে/{{session}}ে একসাথে সবাইকে প্রমোট করুন",
    step1: "১. বর্তমান {{class}}",
    selectDivision: "{{division}} নির্বাচন করুন",
    selectClass: "{{class}} নির্বাচন করুন",
    resultCheck: "ফলাফল যাচাই (ঐচ্ছিক - সর্বশেষ পরীক্ষা)",
    previewLoading: "প্রিভিউ লোড হচ্ছে...",
    showPreview: "প্রিভিউ দেখুন",
    step2: "২. প্রতিটি {{student}}র সিদ্ধান্ত পর্যালোচনা করুন",
    totalLabel: "মোট:",
    promotedLabel: "উত্তীর্ণ:",
    retainedLabel: "অকৃতকার্য:",
    transferredLabel: "স্থানান্তরিত:",
    noActive: "এই {{class}} ও {{session}}ে কোনো সক্রিয় {{student}} পাওয়া যায়নি",
    step3: "৩. যে {{class}}/{{session}}ে প্রমোট হবে",
    execute: "প্রমোশন সম্পন্ন করুন",
    confirmTitle: "প্রমোশন নিশ্চিত করুন",
    confirmBody: (total: string, p: string, r: string, t: string) =>
      `মোট ${total} জন {{student}}র মধ্যে ${p} জন উত্তীর্ণ, ${r} জন অকৃতকার্য এবং ${t} জন স্থানান্তরিত হিসেবে চিহ্নিত হবে। এই কাজটি পরে সহজে undo করা যাবে না। নিশ্চিত?`,
    executing: "সম্পন্ন হচ্ছে...",
    yesConfirm: "হ্যাঁ, নিশ্চিত করুন",
  },
  en: {
    status: {
      PROMOTED: "Promoted (next {{class}})",
      RETAINED: "Retained (same {{class}})",
      TRANSFERRED: "Transferred",
    },
    result: { PASS: "Pass", FAIL: "Fail", ABSENT: "Absent", NO_RESULT: "No result" },
    selectFirst: "Select a {{class}} and {{session}} first",
    previewFailed: "Failed to load the preview",
    done: (p, r, t) => `Promotion complete — promoted: ${p}, retained: ${r}, transferred: ${t}`,
    failed: "Failed to complete the promotion",
    title: "{{student}} Promotion",
    subtitle: "Promote everyone from one {{class}} to the next {{class}}/{{session}} at once",
    step1: "1. Current {{class}}",
    selectDivision: "Select {{division}}",
    selectClass: "Select {{class}}",
    resultCheck: "Result check (optional - latest exam)",
    previewLoading: "Loading preview...",
    showPreview: "Show Preview",
    step2: "2. Review each {{student}}'s decision",
    totalLabel: "Total:",
    promotedLabel: "Promoted:",
    retainedLabel: "Retained:",
    transferredLabel: "Transferred:",
    noActive: "No active {{student}}s found in this {{class}} and {{session}}",
    step3: "3. Target {{class}}/{{session}}",
    execute: "Complete Promotion",
    confirmTitle: "Confirm Promotion",
    confirmBody: (total, p, r, t) =>
      `Of ${total} {{student}}s, ${p} will be marked promoted, ${r} retained and ${t} transferred. This cannot easily be undone. Continue?`,
    executing: "Processing...",
    yesConfirm: "Yes, confirm",
  },
  ar: {
    status: {
      PROMOTED: "ناجح (إلى الصف التالي)",
      RETAINED: "راسب (يبقى في الصف نفسه)",
      TRANSFERRED: "منقول",
    },
    result: { PASS: "ناجح", FAIL: "راسب", ABSENT: "غائب", NO_RESULT: "لا توجد نتيجة" },
    selectFirst: "اختر الصف والعام الدراسي أولًا",
    previewFailed: "تعذّر تحميل المعاينة",
    done: (p, r, t) => `اكتمل الترفيع — ناجح: ${p}، راسب: ${r}، منقول: ${t}`,
    failed: "تعذّر إتمام الترفيع",
    title: "ترفيع الطلاب",
    subtitle: "رفّع الجميع دفعة واحدة من صف إلى الصف/العام الدراسي التالي",
    step1: "1. الصف الحالي",
    selectDivision: "اختر {{division}}",
    selectClass: "اختر {{class}}",
    resultCheck: "التحقق من النتيجة (اختياري - آخر امتحان)",
    previewLoading: "جارٍ تحميل المعاينة...",
    showPreview: "عرض المعاينة",
    step2: "2. راجع قرار كل طالب",
    totalLabel: "الإجمالي:",
    promotedLabel: "ناجح:",
    retainedLabel: "راسب:",
    transferredLabel: "منقول:",
    noActive: "لا يوجد طلاب نشطون في هذا الصف والعام الدراسي",
    step3: "3. الصف/العام الدراسي المستهدف",
    execute: "إتمام الترفيع",
    confirmTitle: "تأكيد الترفيع",
    confirmBody: (total, p, r, t) =>
      `من بين ${total} طالبًا سيُعلَّم ${p} ناجحين و${r} راسبين و${t} منقولين. لا يمكن التراجع عن ذلك بسهولة. هل أنت متأكد؟`,
    executing: "جارٍ التنفيذ...",
    yesConfirm: "نعم، تأكيد",
  },
});
