import { defineText } from "@madrasha/shared-ui/src/i18n";

/** On-screen accounts UI (dashboard, lists, forms, settings). */
export const accountsText = defineText({
  bn: {
    income: "আয়",
    expense: "ব্যয়",
    totalIncome: "মোট আয়",
    totalExpense: "মোট ব্যয়",
    balance: "ব্যালেন্স",
    currentBalance: "বর্তমান ব্যালেন্স",
    todayIncome: "আজকের আয়",
    todayExpense: (amount: string) => `আজকের ব্যয়: ${amount}`,
    shareOfIncome: "মোট আয়ের অংশ",
    quickActions: "দ্রুত অ্যাকশন",
    incomeReceiptEntry: "আয়/রশিদ জমা",
    expenseVoucherCreate: "ব্যয়/ভাউচার তৈরি",
    allTransactions: "সকল লেনদেন",
    incomeExpenseReport: "আয়-ব্যয় রিপোর্ট",
    onlineIncome: "অনলাইন আয় (ব্যাংক/মোবাইল)",
    offlineIncome: "অফলাইন আয় (নগদ)",
    online: "অনলাইন",
    offlineCash: "অফলাইন (নগদ)",
    trendTitle: "আয়-ব্যয়ের প্রবণতা",
    last12Months: "গত ১২ মাস",
    fundDistribution: "ফান্ড অনুযায়ী বণ্টন",
    fundBalance: "ফান্ড ব্যালেন্স",
    fundBalanceSubtitle: "ফান্ড অনুযায়ী বর্তমান স্থিতি",
    viewReport: "রিপোর্ট দেখুন",
    byMethodTitle: "মাধ্যম অনুযায়ী আয়-ব্যয়",
    byMethodSubtitle: "অনলাইন বনাম অফলাইন (নগদ)",
    recentTransactions: "সাম্প্রতিক লেনদেন",
    viewAll: "সব দেখুন",
    type: "ধরন",
    fundCategory: "ফান্ড / খাত",
    noTransactions: "কোনো লেনদেন পাওয়া যায়নি",
    printReceipt: "রশিদ প্রিন্ট",
    printVoucher: "ভাউচার প্রিন্ট",
    unassigned: "নির্ধারিত নয়",
    // Delete
    deleteEntryTitle: "এন্ট্রি ডিলিট করুন",
    deleteEntryMessage: (name: string, amount: string) => `"${name}" এর ${amount} টাকার এন্ট্রিটি মুছে ফেলতে চান?`,
    deleteConfirm: "ডিলিট করুন",
    entryDeleted: "এন্ট্রি মুছে ফেলা হয়েছে",
    deleteFailed: "মুছতে সমস্যা হয়েছে",
    // Recent panel
    recentOf: (kind: string) => `সাম্প্রতিক ${kind}`,
    lastNEntries: (n: string) => `সর্বশেষ ${n}টি এন্ট্রি`,
    noEntries: "কোনো এন্ট্রি পাওয়া যায়নি",
    no: "নং",
    method: "মাধ্যম",
    category: "খাত",
    fund: "ফান্ড",
    // Edit modal / forms
    enterName: "নাম দিন",
    enterAmount: "পরিমাণ দিন",
    entryUpdated: "এন্ট্রি আপডেট হয়েছে",
    updateFailed: "আপডেট করতে সমস্যা হয়েছে",
    editIncomeTitle: "আয় এন্ট্রি এডিট করুন",
    editExpenseTitle: "ব্যয় এন্ট্রি এডিট করুন",
    time: "সময়",
    receiptNumber: "রশিদ নম্বর",
    voucherNumber: "ভাউচার নম্বর",
    expenseGroup: "ব্যয় বিভাগ",
    expenseCategory: "ব্যয়ের খাত",
    mobileNumber: "মোবাইল নম্বর",
    paymentMethod: "পেমেন্ট মাধ্যম",
    noteDescription: "নোট / বিবরণ",
    // Income / Expense pages
    incomeSaved: "আয়/রশিদ জমা সংরক্ষণ হয়েছে",
    expenseSaved: "ব্যয়/ভাউচার সংরক্ষণ হয়েছে",
    incomeTitle: "রশিদ জমা / আয় এন্ট্রি",
    incomeSubtitle: "{{institution}} ফান্ডভিত্তিক আয় ও রশিদ জমা",
    expenseTitle: "ভাউচার তৈরি / ব্যয় এন্ট্রি",
    expenseSubtitle: "ফান্ডভিত্তিক ভাউচার ও ব্যয় সংরক্ষণ",
    donorNamePlaceholder: "দাতার নাম",
    receiverNamePlaceholder: "গ্রহণকারীর নাম",
    usedForSms: "SMS পাঠানোর জন্য ব্যবহৃত হবে",
    optionalNote: "ঐচ্ছিক নোট",
    // List page
    presets: {
      all: "সব",
      today: "আজ",
      "3d": "গত ৩ দিন",
      "7d": "গত ৭ দিন",
      "15d": "গত ১৫ দিন",
      "30d": "গত ৩০ দিন",
    },
    bulkDeleteTitle: "নির্বাচিত এন্ট্রি ডিলিট করুন",
    bulkDeleteMessage: (n: string, total: string) =>
      `${n} টি এন্ট্রি (মোট ${total}) স্থায়ীভাবে মুছে ফেলতে চান? এই কাজ আর ফিরিয়ে নেওয়া যাবে না।`,
    deleteAll: "সব ডিলিট করুন",
    bulkDeleted: (n: string) => `${n} টি এন্ট্রি মুছে ফেলা হয়েছে`,
    listTitle: "সকল লেনদেন",
    listSubtitle: "সব আয় ও ব্যয় এন্ট্রি — এডিট ও ডিলিট করুন",
    allCategories: "সব খাত",
    searchFund: "ফান্ড খুঁজুন",
    fundNamePlaceholder: "ফান্ডের নাম লিখুন",
    startDate: "শুরুর তারিখ",
    endDate: "শেষ তারিখ",
    selectedSummary: (n: string, total: string) => `${n} টি এন্ট্রি নির্বাচিত (মোট ${total})`,
    clearSelection: "নির্বাচন বাতিল",
    deleting: "মুছে ফেলা হচ্ছে...",
    deleteSelected: "নির্বাচিত এন্ট্রি মুছুন",
    selectAll: "সব নির্বাচন করুন",
    selectEntry: "এন্ট্রি নির্বাচন করুন",
    // Report page
    reportFilters: {
      daily: "দৈনিক",
      monthly: "মাসিক",
      yearly: "বাৎসরিক",
      byFund: "ফান্ড ভিত্তিক",
      byCategory: "খাত ভিত্তিক",
      fundCategory: "ফান্ড ও খাত বিস্তারিত",
    },
    reportSubtitle: "দৈনিক, মাসিক, ফান্ড ও খাতভিত্তিক রিপোর্ট",
    reportLoadFailed: "রিপোর্ট লোড করা যায়নি। Backend/schema check করুন।",
    // Receipt modal (screen chrome)
    printPreview: (doc: string) => `${doc} প্রিন্ট প্রিভিউ`,
    printNow: "প্রিন্ট করুন",
    // Fund settings
    settingsTitle: "ফান্ড ও খাত সেটিংস",
    settingsSubtitle: "আয়ের ফান্ড ও ব্যয়ের বিভাগ, এবং তাদের খাত এখান থেকে যোগ/এডিট/ডিলিট করুন",
    sections: {
      income: {
        title: "আয়ের ফান্ড",
        hint: "প্রতিটা ফান্ডের নিচে তার খাতগুলো যোগ করুন",
        addPlaceholder: "নতুন ফান্ডের নাম",
        addButtonLabel: "ফান্ড যোগ করুন",
        emptyTitle: "এখনো কোনো আয়ের ফান্ড যোগ করা হয়নি",
        emptyHint: "উপরের ফর্ম থেকে প্রথম ফান্ডটি যোগ করুন।",
        deleteWarningNoun: "ফান্ডটি",
      },
      expense: {
        title: "ব্যয়ের বিভাগ",
        hint: "প্রতিটা বিভাগের নিচে তার খাতগুলো যোগ করুন",
        addPlaceholder: "নতুন বিভাগের নাম",
        addButtonLabel: "বিভাগ যোগ করুন",
        emptyTitle: "এখনো কোনো ব্যয়ের বিভাগ যোগ করা হয়নি",
        emptyHint: "উপরের ফর্ম থেকে প্রথম বিভাগটি যোগ করুন।",
        deleteWarningNoun: "বিভাগটি",
      },
    },
    enterAName: "একটা নাম দিন",
    addedToast: (title: string) => `${title} যোগ করা হয়েছে`,
    saveFailed: "সংরক্ষণ করতে সমস্যা হয়েছে",
    deleteTitle: (title: string) => `${title} ডিলিট করুন`,
    deleteFundMessage: (name: string, noun: string, n: string) =>
      `"${name}" ${noun} স্থায়ীভাবে মুছে ফেলতে চান? এর ভেতরের সব খাতও (${n}টি) একসাথে মুছে যাবে।`,
    enterCategoryName: "একটা খাতের নাম দিন",
    categoryAdded: "খাত যোগ করা হয়েছে",
    deleteCategoryTitle: "খাত ডিলিট করুন",
    deleteCategoryMessage: (name: string) => `"${name}" খাতটি স্থায়ীভাবে মুছে ফেলতে চান?`,
    categoryDeleted: "খাত মুছে ফেলা হয়েছে",
    newCategoryPlaceholder: "নতুন খাতের নাম",
    addCategory: "খাত যোগ করুন",
  },
  en: {
    income: "Income",
    expense: "Expense",
    totalIncome: "Total Income",
    totalExpense: "Total Expense",
    balance: "Balance",
    currentBalance: "Current Balance",
    todayIncome: "Today's Income",
    todayExpense: (amount) => `Today's expense: ${amount}`,
    shareOfIncome: "Share of total income",
    quickActions: "Quick Actions",
    incomeReceiptEntry: "Income / Receipt",
    expenseVoucherCreate: "Expense / Voucher",
    allTransactions: "All Transactions",
    incomeExpenseReport: "Income-Expense Report",
    onlineIncome: "Online income (bank/mobile)",
    offlineIncome: "Offline income (cash)",
    online: "Online",
    offlineCash: "Offline (cash)",
    trendTitle: "Income-Expense Trend",
    last12Months: "Last 12 months",
    fundDistribution: "Distribution by Fund",
    fundBalance: "Fund Balance",
    fundBalanceSubtitle: "Current position by fund",
    viewReport: "View report",
    byMethodTitle: "Income-Expense by Method",
    byMethodSubtitle: "Online vs offline (cash)",
    recentTransactions: "Recent Transactions",
    viewAll: "View all",
    type: "Type",
    fundCategory: "Fund / Category",
    noTransactions: "No transactions found",
    printReceipt: "Print receipt",
    printVoucher: "Print voucher",
    unassigned: "Unassigned",
    deleteEntryTitle: "Delete Entry",
    deleteEntryMessage: (name, amount) => `Delete the ${amount} entry of "${name}"?`,
    deleteConfirm: "Delete",
    entryDeleted: "Entry deleted",
    deleteFailed: "Could not delete",
    recentOf: (kind) => `Recent ${kind}`,
    lastNEntries: (n) => `Last ${n} entries`,
    noEntries: "No entries found",
    no: "No.",
    method: "Method",
    category: "Category",
    fund: "Fund",
    enterName: "Enter a name",
    enterAmount: "Enter an amount",
    entryUpdated: "Entry updated",
    updateFailed: "Could not update",
    editIncomeTitle: "Edit Income Entry",
    editExpenseTitle: "Edit Expense Entry",
    time: "Time",
    receiptNumber: "Receipt number",
    voucherNumber: "Voucher number",
    expenseGroup: "Expense group",
    expenseCategory: "Expense category",
    mobileNumber: "Mobile number",
    paymentMethod: "Payment method",
    noteDescription: "Note / Description",
    incomeSaved: "Income/receipt saved",
    expenseSaved: "Expense/voucher saved",
    incomeTitle: "Receipt / Income Entry",
    incomeSubtitle: "Fund-wise income and receipts of the {{institution}}",
    expenseTitle: "Voucher / Expense Entry",
    expenseSubtitle: "Record fund-wise vouchers and expenses",
    donorNamePlaceholder: "Donor name",
    receiverNamePlaceholder: "Receiver name",
    usedForSms: "Used for sending SMS",
    optionalNote: "Optional note",
    presets: {
      all: "All",
      today: "Today",
      "3d": "Last 3 days",
      "7d": "Last 7 days",
      "15d": "Last 15 days",
      "30d": "Last 30 days",
    },
    bulkDeleteTitle: "Delete Selected Entries",
    bulkDeleteMessage: (n, total) => `Permanently delete ${n} entries (total ${total})? This cannot be undone.`,
    deleteAll: "Delete all",
    bulkDeleted: (n) => `${n} entries deleted`,
    listTitle: "All Transactions",
    listSubtitle: "All income and expense entries — edit and delete",
    allCategories: "All categories",
    searchFund: "Search fund",
    fundNamePlaceholder: "Type a fund name",
    startDate: "Start date",
    endDate: "End date",
    selectedSummary: (n, total) => `${n} entries selected (total ${total})`,
    clearSelection: "Clear selection",
    deleting: "Deleting...",
    deleteSelected: "Delete selected",
    selectAll: "Select all",
    selectEntry: "Select entry",
    reportFilters: {
      daily: "Daily",
      monthly: "Monthly",
      yearly: "Yearly",
      byFund: "By fund",
      byCategory: "By category",
      fundCategory: "Fund & category detail",
    },
    reportSubtitle: "Daily, monthly, fund-wise and category-wise reports",
    reportLoadFailed: "Could not load the report. Check the backend/schema.",
    printPreview: (doc) => `${doc} Print Preview`,
    printNow: "Print",
    settingsTitle: "Fund & Category Settings",
    settingsSubtitle: "Add, edit or delete income funds, expense groups and their categories",
    sections: {
      income: {
        title: "Income Funds",
        hint: "Add categories under each fund",
        addPlaceholder: "New fund name",
        addButtonLabel: "Add fund",
        emptyTitle: "No income funds added yet",
        emptyHint: "Add the first fund using the form above.",
        deleteWarningNoun: "fund",
      },
      expense: {
        title: "Expense Groups",
        hint: "Add categories under each group",
        addPlaceholder: "New group name",
        addButtonLabel: "Add group",
        emptyTitle: "No expense groups added yet",
        emptyHint: "Add the first group using the form above.",
        deleteWarningNoun: "group",
      },
    },
    enterAName: "Enter a name",
    addedToast: (title) => `${title}: added`,
    saveFailed: "Could not save",
    deleteTitle: (title) => `Delete from ${title}`,
    deleteFundMessage: (name, noun, n) =>
      `Permanently delete the ${noun} "${name}"? All its categories (${n}) will be deleted too.`,
    enterCategoryName: "Enter a category name",
    categoryAdded: "Category added",
    deleteCategoryTitle: "Delete Category",
    deleteCategoryMessage: (name) => `Permanently delete the category "${name}"?`,
    categoryDeleted: "Category deleted",
    newCategoryPlaceholder: "New category name",
    addCategory: "Add category",
  },
});

/** Printed receipt/voucher and the printed income-expense report -
 * always in the institution's default language. */
export const accountsPrintText = defineText({
  bn: {
    receipt: "রশিদ",
    voucher: "ভাউচার",
    receiptNo: "রশিদ নং",
    voucherNo: "ভাউচার নং",
    date: "তারিখ",
    donorName: "দাতার নাম",
    receiverName: "গ্রহীতার নাম",
    address: "ঠিকানা",
    fund: "ফান্ড",
    category: "খাত",
    paymentMethod: "পেমেন্ট মাধ্যম",
    note: "নোট",
    donorSignature: "দাতার স্বাক্ষর",
    receiverSignature: "গ্রহীতার স্বাক্ষর",
    authoritySignature: "কর্তৃপক্ষের স্বাক্ষর",
    // Report
    reportTitle: "আয়-ব্যয় রিপোর্ট",
    reportSubtitle: (label: string) => `${label} রিপোর্ট`,
    description: "বিবরণ",
    income: "আয়",
    expense: "ব্যয়",
    balance: "ব্যালেন্স",
    grandTotal: "সর্বমোট",
    unassigned: "নির্ধারিত নয়",
    reportFilters: {
      daily: "দৈনিক",
      monthly: "মাসিক",
      yearly: "বাৎসরিক",
      byFund: "ফান্ড ভিত্তিক",
      byCategory: "খাত ভিত্তিক",
      fundCategory: "ফান্ড ও খাত বিস্তারিত",
    },
  },
  en: {
    receipt: "Receipt",
    voucher: "Voucher",
    receiptNo: "Receipt No.",
    voucherNo: "Voucher No.",
    date: "Date",
    donorName: "Donor name",
    receiverName: "Receiver name",
    address: "Address",
    fund: "Fund",
    category: "Category",
    paymentMethod: "Payment method",
    note: "Note",
    donorSignature: "Donor's signature",
    receiverSignature: "Receiver's signature",
    authoritySignature: "Authorized signature",
    reportTitle: "Income-Expense Report",
    reportSubtitle: (label) => `${label} report`,
    description: "Description",
    income: "Income",
    expense: "Expense",
    balance: "Balance",
    grandTotal: "Grand total",
    unassigned: "Unassigned",
    reportFilters: {
      daily: "Daily",
      monthly: "Monthly",
      yearly: "Yearly",
      byFund: "Fund-wise",
      byCategory: "Category-wise",
      fundCategory: "Fund & category detail",
    },
  },
});
