import { defineText } from "@madrasha/shared-ui/src/i18n";

/** Public online admission form. Option values sent to the backend (gender
 * 1/2, residency 1/2, blood groups) stay as they are - only labels translate. */
export const admissionApplyText = defineText({
  bn: {
    goBack: "ফিরে যান",
    logo: "লোগো",
    title: "অনলাইনে ভর্তি আবেদন",
    intro:
      "নিচের ফরমটি সঠিকভাবে পূরণ করে জমা দিন। আবেদনটি {{institution}} কর্তৃপক্ষের অনুমোদনের পর চূড়ান্ত ভর্তি সম্পন্ন হবে।",
    requiredError: "লাল চিহ্নিত আবশ্যক (*) ঘরগুলো পূরণ করুন",
    submitFailed: "আবেদন জমা দেওয়া যায়নি, আবার চেষ্টা করুন।",
    successTitle: "আবেদন সফলভাবে জমা হয়েছে",
    successBody:
      "আপনার আবেদনটি পর্যালোচনার অপেক্ষায় আছে। {{institution}} কর্তৃপক্ষ অনুমোদন করলে আপনার দেওয়া ফোন নম্বরে যোগাযোগ করা হবে।",
    applicableFees: "প্রযোজ্য ভর্তি ফি",
    total: "মোট",
    payAtOffice:
      "অনুগ্রহ করে এই ফি {{institution}} অফিসে সরাসরি গিয়ে জমা দিন। অনুমোদনের আগে ফি জমা না হলে ভর্তি প্রক্রিয়া সম্পন্ন হবে না।",
    backHome: "হোমপেজে ফিরে যান",
    uploadPhoto: "ছবি আপলোড",
    studentInfo: "{{student}}র তথ্য",
    fullNameBn: "{{student}}র পূর্ণ নাম (বাংলা)",
    fullNamePlaceholder: "সম্পূর্ণ নাম লিখুন",
    nameAr: "নাম (আরবি)",
    nameEn: "নাম (ইংরেজি)",
    nid: "NID/জন্ম নিবন্ধন নম্বর",
    gender: "লিঙ্গ",
    select: "নির্বাচন করুন",
    male: "ছেলে",
    female: "মেয়ে",
    dob: "জন্ম তারিখ",
    bloodGroup: "রক্তের গ্রুপ",
    residency: "আবাসিক/অনাবাসিক",
    residential: "আবাসিক",
    nonResidential: "অনাবাসিক",
    orphan: "এতিম {{student}}",
    no: "না",
    yes: "হ্যাঁ",
    admissionInfo: "ভর্তির তথ্য",
    division: "{{division}}",
    desiredClass: "ভর্তি হতে ইচ্ছুক {{class}}",
    previousClass: "পূর্বের {{class}}",
    previousInstitution: "পূর্ববর্তী প্রতিষ্ঠান",
    previousInstitutionPlaceholder: "পূর্ববর্তী প্রতিষ্ঠানের নাম",
    previousResult: "পূর্বের ফলাফল",
    guardianInfo: "অভিভাবকের তথ্য",
    fatherNameBn: "পিতার নাম (বাংলা)",
    fatherNameAr: "পিতার নাম (আরবি)",
    fatherNameEn: "পিতার নাম (ইংরেজি)",
    fatherNid: "পিতার NID",
    fatherOccupation: "পিতার পেশা",
    motherNameBn: "মাতার নাম (বাংলা)",
    motherNameAr: "মাতার নাম (আরবি)",
    motherNameEn: "মাতার নাম (ইংরেজি)",
    motherNid: "মাতার NID",
    motherOccupation: "মাতার পেশা",
    guardianPhone: "অভিভাবকের ফোন নম্বর",
    guardianPhone2: "অভিভাবকের বিকল্প ফোন নম্বর",
    hasAltGuardian: "পিতা-মাতা ছাড়া অন্য অভিভাবক আছে",
    altGuardianNameBn: "অভিভাবকের নাম (বাংলা)",
    altGuardianNameAr: "অভিভাবকের নাম (আরবি)",
    altGuardianNameEn: "অভিভাবকের নাম (ইংরেজি)",
    relation: "{{student}}র সাথে সম্পর্ক",
    relationPlaceholder: "যেমন: চাচা, দাদা",
    mobile: "মোবাইল নম্বর",
    address: "ঠিকানা",
    village: "গ্রাম",
    submitting: "জমা দেওয়া হচ্ছে...",
    submit: "আবেদন জমা দিন",
    requiredNote: "* চিহ্নিত ঘরগুলো আবশ্যক",
  },
  en: {
    goBack: "Go back",
    logo: "Logo",
    title: "Online Admission Application",
    intro:
      "Please fill in the form below correctly and submit it. Admission will be final once the {{institution}} authority approves the application.",
    requiredError: "Please fill in the required (*) fields marked in red",
    submitFailed: "Could not submit the application, please try again.",
    successTitle: "Application submitted successfully",
    successBody:
      "Your application is awaiting review. Once the {{institution}} authority approves it, you will be contacted on the phone number you provided.",
    applicableFees: "Applicable Admission Fees",
    total: "Total",
    payAtOffice:
      "Please pay these fees in person at the {{institution}} office. Admission will not be completed unless the fees are paid before approval.",
    backHome: "Back to Homepage",
    uploadPhoto: "Upload photo",
    studentInfo: "{{student}} Information",
    fullNameBn: "{{student}}'s Full Name (Bangla)",
    fullNamePlaceholder: "Enter full name",
    nameAr: "Name (Arabic)",
    nameEn: "Name (English)",
    nid: "NID/Birth Registration No.",
    gender: "Gender",
    select: "Select",
    male: "Male",
    female: "Female",
    dob: "Date of Birth",
    bloodGroup: "Blood Group",
    residency: "Residential/Non-residential",
    residential: "Residential",
    nonResidential: "Non-residential",
    orphan: "Orphan {{student}}",
    no: "No",
    yes: "Yes",
    admissionInfo: "Admission Information",
    division: "{{division}}",
    desiredClass: "{{class}} Applying For",
    previousClass: "Previous {{class}}",
    previousInstitution: "Previous Institution",
    previousInstitutionPlaceholder: "Name of previous institution",
    previousResult: "Previous Result",
    guardianInfo: "Guardian Information",
    fatherNameBn: "Father's Name (Bangla)",
    fatherNameAr: "Father's Name (Arabic)",
    fatherNameEn: "Father's Name (English)",
    fatherNid: "Father's NID",
    fatherOccupation: "Father's Occupation",
    motherNameBn: "Mother's Name (Bangla)",
    motherNameAr: "Mother's Name (Arabic)",
    motherNameEn: "Mother's Name (English)",
    motherNid: "Mother's NID",
    motherOccupation: "Mother's Occupation",
    guardianPhone: "Guardian's Phone Number",
    guardianPhone2: "Guardian's Alternate Phone Number",
    hasAltGuardian: "Has a guardian other than the parents",
    altGuardianNameBn: "Guardian's Name (Bangla)",
    altGuardianNameAr: "Guardian's Name (Arabic)",
    altGuardianNameEn: "Guardian's Name (English)",
    relation: "Relation to {{student}}",
    relationPlaceholder: "e.g. uncle, grandfather",
    mobile: "Mobile Number",
    address: "Address",
    village: "Village",
    submitting: "Submitting...",
    submit: "Submit Application",
    requiredNote: "Fields marked * are required",
  },
  ar: {
    goBack: "رجوع",
    logo: "الشعار",
    title: "طلب القبول الإلكتروني",
    intro:
      "يرجى تعبئة الاستمارة أدناه بدقة ثم إرسالها. يكتمل القبول نهائيًا بعد موافقة إدارة {{institution}} على الطلب.",
    requiredError: "يرجى تعبئة الحقول المطلوبة (*) المظللة بالأحمر",
    submitFailed: "تعذّر إرسال الطلب، يرجى المحاولة مرة أخرى.",
    successTitle: "تم إرسال الطلب بنجاح",
    successBody:
      "طلبك قيد المراجعة. عند موافقة إدارة {{institution}} سيتم التواصل معك على رقم الهاتف الذي أدخلته.",
    applicableFees: "رسوم القبول المستحقة",
    total: "المجموع",
    payAtOffice:
      "يرجى دفع هذه الرسوم حضوريًا في مكتب {{institution}}. لن تكتمل إجراءات القبول ما لم تُدفع الرسوم قبل الموافقة.",
    backHome: "العودة إلى الصفحة الرئيسية",
    uploadPhoto: "رفع صورة",
    studentInfo: "بيانات {{student}}",
    fullNameBn: "اسم {{student}} الكامل (بالبنغالية)",
    fullNamePlaceholder: "اكتب الاسم الكامل",
    nameAr: "الاسم (بالعربية)",
    nameEn: "الاسم (بالإنجليزية)",
    nid: "رقم الهوية/شهادة الميلاد",
    gender: "الجنس",
    select: "اختر",
    male: "ذكر",
    female: "أنثى",
    dob: "تاريخ الميلاد",
    bloodGroup: "فصيلة الدم",
    residency: "داخلي/خارجي",
    residential: "داخلي",
    nonResidential: "خارجي",
    orphan: "هل {{student}} يتيم؟",
    no: "لا",
    yes: "نعم",
    admissionInfo: "بيانات القبول",
    division: "{{division}}",
    desiredClass: "{{class}} المراد الالتحاق به",
    previousClass: "{{class}} السابق",
    previousInstitution: "المؤسسة السابقة",
    previousInstitutionPlaceholder: "اسم المؤسسة السابقة",
    previousResult: "النتيجة السابقة",
    guardianInfo: "بيانات ولي الأمر",
    fatherNameBn: "اسم الأب (بالبنغالية)",
    fatherNameAr: "اسم الأب (بالعربية)",
    fatherNameEn: "اسم الأب (بالإنجليزية)",
    fatherNid: "رقم هوية الأب",
    fatherOccupation: "مهنة الأب",
    motherNameBn: "اسم الأم (بالبنغالية)",
    motherNameAr: "اسم الأم (بالعربية)",
    motherNameEn: "اسم الأم (بالإنجليزية)",
    motherNid: "رقم هوية الأم",
    motherOccupation: "مهنة الأم",
    guardianPhone: "رقم هاتف ولي الأمر",
    guardianPhone2: "رقم هاتف بديل لولي الأمر",
    hasAltGuardian: "يوجد ولي أمر غير الوالدين",
    altGuardianNameBn: "اسم ولي الأمر (بالبنغالية)",
    altGuardianNameAr: "اسم ولي الأمر (بالعربية)",
    altGuardianNameEn: "اسم ولي الأمر (بالإنجليزية)",
    relation: "صلة القرابة مع {{student}}",
    relationPlaceholder: "مثل: العم، الجد",
    mobile: "رقم الجوال",
    address: "العنوان",
    village: "القرية",
    submitting: "جارٍ الإرسال...",
    submit: "إرسال الطلب",
    requiredNote: "الحقول المميزة بـ * مطلوبة",
  },
});
