import { defineText } from "@madrasha/shared-ui/src/i18n";

/** Public website chrome (nav, section headings, buttons, footer). The
 * website CONTENT itself (slides, notices, pages, committee...) is DB data
 * and is never translated. */
export const websiteText = defineText({
  bn: {
    nav: {
      home: "হোম",
      about: "পরিচিতি",
      muhtamim: "{{head}}ের বাণী",
      sovapoti: "সভাপতির বাণী",
      admission: "ভর্তি তথ্য",
      teachers: "{{teacher}}বৃন্দ",
      committee: "কমিটি",
      gallery: "গ্যালারি",
      video: "ভিডিও গ্যালারি",
      notices: "নোটিশ",
      contact: "যোগাযোগ",
    } as Record<string, string>,
    loadingSite: "ওয়েবসাইট লোড হচ্ছে...",
    siteUnavailable: "ওয়েবসাইটটি এখন পাওয়া যাচ্ছে না",
    unavailableHint: "সুপার অ্যাডমিন অথবা {{institution}} অ্যাডমিন ওয়েবসাইটের স্ট্যাটাস/সেটিংস যাচাই করতে পারেন।",
    officialWebsite: "অফিসিয়াল ওয়েবসাইট",
    logo: "লোগো",
    menu: "মেনু",
    closeMenu: "মেনু বন্ধ করুন",
    guardianLogin: "অভিভাবক লগইন",
    onlineAdmission: "অনলাইনে ভর্তি",
    welcomeFallback: "আমাদের ওয়েবসাইটে স্বাগতম।",
    learnAboutUs: "আমাদের সম্পর্কে জানুন",
    aboutEyebrow: "পরিচিতি",
    admissionInfoApply: "ভর্তির তথ্য ও আবেদন",
    galleryEyebrow: "আমাদের মুহূর্তগুলো",
    galleryTitle: "গ্যালারি",
    galleryFallback: "গ্যালারি",
    galleryEmpty: "গ্যালারি চালু আছে। ছবি আপলোড করলে এখানে দেখা যাবে।",
    videoEyebrow: "আমাদের ভিডিও",
    videoTitle: "ভিডিও গ্যালারি",
    videoFallback: "ভিডিও",
    teachersEyebrow: "আমাদের {{teacher}}বৃন্দ",
    teachersTitle: "{{teacher}}বৃন্দ",
    teacherFallback: "{{teacher}}",
    noticeBoard: "নোটিশ বোর্ড",
    newBadge: "নতুন",
    noNotices: "এখনো কোনো নোটিশ নেই।",
    headMessage: "{{head}}ের বাণী",
    presidentMessage: "সভাপতির বাণী",
    committeeTitle: "{{institution}} কমিটি",
    admissionEyebrow: "ভর্তি",
    fillAdmissionForm: "অনলাইনে ভর্তি ফরম পূরণ করুন",
    contactUs: "যোগাযোগ করুন",
    taglineMadrasa: "একটি ইসলামিক শিক্ষা প্রতিষ্ঠান।",
    tagline: "একটি শিক্ষা প্রতিষ্ঠান।",
    quickLinks: "প্রয়োজনীয় লিংক",
    contact: "যোগাযোগ",
    messageOnWhatsApp: "হোয়াটসঅ্যাপে মেসেজ করুন",
    guardianAndAdmission: "অভিভাবক ও ভর্তি",
    allRightsReserved: "সর্বস্বত্ব সংরক্ষিত।",
    backToTop: "উপরে যান",
    chatOnWhatsApp: "হোয়াটসঅ্যাপে চ্যাট করুন",
    close: "বন্ধ করুন",
    // HeroSlider
    openSlideLink: "স্লাইডের লিংক খুলুন",
    limitedMode: "সুপার অ্যাডমিন সীমিত মোড চালু করেছেন।",
    slide: (n: string) => `স্লাইড ${n}`,
    prevSlide: "পূর্ববর্তী স্লাইড",
    nextSlide: "পরবর্তী স্লাইড",
    // NoticeMarquee
    notice: "নোটিশ",
    // ContactSection
    whatsappChannel: "হোয়াটসঅ্যাপ চ্যানেল",
    phone: "ফোন",
    email: "ইমেইল",
    address: "ঠিকানা",
    // MapPreview
    viewOnMap: "ম্যাপে দেখুন",
    viewOnGoogleMaps: "Google Maps-এ লোকেশন দেখুন",
    directions: "দিকনির্দেশনা",
  },
  en: {
    nav: {
      home: "Home",
      about: "About",
      muhtamim: "{{head}}'s Message",
      sovapoti: "President's Message",
      admission: "Admission",
      teachers: "{{teacher}}s",
      committee: "Committee",
      gallery: "Gallery",
      video: "Video Gallery",
      notices: "Notices",
      contact: "Contact",
    },
    loadingSite: "Loading website...",
    siteUnavailable: "This website is currently unavailable",
    unavailableHint: "The Super Admin or the {{institution}} admin can check the website status/settings.",
    officialWebsite: "Official Website",
    logo: "Logo",
    menu: "Menu",
    closeMenu: "Close menu",
    guardianLogin: "Guardian Login",
    onlineAdmission: "Apply Online",
    welcomeFallback: "Welcome to our {{institution}} website.",
    learnAboutUs: "Learn About Us",
    aboutEyebrow: "About",
    admissionInfoApply: "Admission Info & Application",
    galleryEyebrow: "Our Moments",
    galleryTitle: "Gallery",
    galleryFallback: "Gallery",
    galleryEmpty: "The gallery is enabled. Uploaded photos will appear here.",
    videoEyebrow: "Our Videos",
    videoTitle: "Video Gallery",
    videoFallback: "Video",
    teachersEyebrow: "Our {{teacher}}s",
    teachersTitle: "{{teacher}}s",
    teacherFallback: "{{teacher}}",
    noticeBoard: "Notice Board",
    newBadge: "New",
    noNotices: "No notices yet.",
    headMessage: "Message from the {{head}}",
    presidentMessage: "Message from the President",
    committeeTitle: "{{institution}} Committee",
    admissionEyebrow: "Admission",
    fillAdmissionForm: "Fill in the Online Admission Form",
    contactUs: "Contact Us",
    taglineMadrasa: "An Islamic educational institution.",
    tagline: "An educational institution.",
    quickLinks: "Quick Links",
    contact: "Contact",
    messageOnWhatsApp: "Message on WhatsApp",
    guardianAndAdmission: "Guardians & Admission",
    allRightsReserved: "All rights reserved.",
    backToTop: "Back to top",
    chatOnWhatsApp: "Chat on WhatsApp",
    close: "Close",
    openSlideLink: "Open slide link",
    limitedMode: "Limited mode enabled by Super Admin.",
    slide: (n) => `Slide ${n}`,
    prevSlide: "Previous slide",
    nextSlide: "Next slide",
    notice: "Notice",
    whatsappChannel: "WhatsApp Channel",
    phone: "Phone",
    email: "Email",
    address: "Address",
    viewOnMap: "View on map",
    viewOnGoogleMaps: "View location on Google Maps",
    directions: "Directions",
  },
  ar: {
    nav: {
      home: "الرئيسية",
      about: "من نحن",
      muhtamim: "كلمة {{head}}",
      sovapoti: "كلمة الرئيس",
      admission: "القبول",
      teachers: "هيئة التدريس",
      committee: "اللجنة",
      gallery: "معرض الصور",
      video: "معرض الفيديو",
      notices: "الإعلانات",
      contact: "اتصل بنا",
    },
    loadingSite: "جارٍ تحميل الموقع...",
    siteUnavailable: "الموقع غير متاح حاليًا",
    unavailableHint: "يمكن للمشرف العام أو مشرف {{institution}} التحقق من حالة الموقع وإعداداته.",
    officialWebsite: "الموقع الرسمي",
    logo: "الشعار",
    menu: "القائمة",
    closeMenu: "إغلاق القائمة",
    guardianLogin: "دخول ولي الأمر",
    onlineAdmission: "التسجيل الإلكتروني",
    welcomeFallback: "مرحبًا بكم في موقع {{institution}}.",
    learnAboutUs: "تعرّف علينا",
    aboutEyebrow: "من نحن",
    admissionInfoApply: "معلومات القبول والتقديم",
    galleryEyebrow: "من لحظاتنا",
    galleryTitle: "معرض الصور",
    galleryFallback: "معرض الصور",
    galleryEmpty: "معرض الصور مفعّل، وستظهر الصور هنا بعد رفعها.",
    videoEyebrow: "مقاطعنا المرئية",
    videoTitle: "معرض الفيديو",
    videoFallback: "فيديو",
    teachersEyebrow: "هيئة التدريس لدينا",
    teachersTitle: "هيئة التدريس",
    teacherFallback: "{{teacher}}",
    noticeBoard: "لوحة الإعلانات",
    newBadge: "جديد",
    noNotices: "لا توجد إعلانات بعد.",
    headMessage: "كلمة {{head}}",
    presidentMessage: "كلمة الرئيس",
    committeeTitle: "لجنة {{institution}}",
    admissionEyebrow: "القبول",
    fillAdmissionForm: "املأ استمارة القبول الإلكترونية",
    contactUs: "تواصل معنا",
    taglineMadrasa: "مؤسسة تعليمية إسلامية.",
    tagline: "مؤسسة تعليمية.",
    quickLinks: "روابط مهمة",
    contact: "اتصل بنا",
    messageOnWhatsApp: "راسلنا عبر واتساب",
    guardianAndAdmission: "أولياء الأمور والقبول",
    allRightsReserved: "جميع الحقوق محفوظة.",
    backToTop: "العودة إلى الأعلى",
    chatOnWhatsApp: "تحدث معنا عبر واتساب",
    close: "إغلاق",
    openSlideLink: "فتح رابط الشريحة",
    limitedMode: "فعّل المشرف العام الوضع المحدود.",
    slide: (n) => `الشريحة ${n}`,
    prevSlide: "الشريحة السابقة",
    nextSlide: "الشريحة التالية",
    notice: "إعلان",
    whatsappChannel: "قناة واتساب",
    phone: "الهاتف",
    email: "البريد الإلكتروني",
    address: "العنوان",
    viewOnMap: "عرض على الخريطة",
    viewOnGoogleMaps: "عرض الموقع على خرائط Google",
    directions: "الاتجاهات",
  },
});
